### ISSUE TITLE
Assault Orders misbehaviours

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#1000]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Some issues after accepting Assault Orders:

**Problem 1:** When you accept an assault mission for an area, you can teleport there via the Runic Portal even without prior unlocking of the staging point.
**Problem 2:** With the first issue, another issue arises. When you can teleport there without having it unlocked and then teleport back, you unlock the staging point. So you can cheat and unlock all staging points with this method. This shouldn't be changed but rather Problem 1.
**Expected behaviour:** When you accept an assault mission for an area, you can't teleport there via the Runic Portal if you didn't unlock the staging point beforehand. You just can't use the Runic Portal at all then. You can chocobo/walk to the staging point. Do the mission and teleing back while unlocking the staging point or vice versa.

**Problem 3:** When you are inside the staging point while having Assault Orders you can leave through the Heavy Iron Gate.
**Expected behaviour:** You can't go outside but you can go inside while having Assault Orders.

**Possible Problem 4/Expected behaviour:** I don't know how it's currently handled but when the leader starts the assault, all members with the same orders WITHIN the staging point will be teleported to the mission area. Everyone outside the Heavy Iron Gate will be ignored and not teleported. This should be the case to prevent cheesing for example entering Arrapago Reef and saving the trip to the staging point.

`"Assault Orders will not permit you to travel to Runic Portals that you have not already visited." `

`"Exiting the secured area with Assault Orders is prohibited."`
https://www.bg-wiki.com/ffxi/Category:Assault#Signing_up_for_an_Assault_Mission

`
"After accepting a mission from one of the Assault Mission Giver NPCs, you must make your way to the Staging Point for the particular assault area. If you have previously used the Runic Portal in that area, you may use the Chamber of Passage to teleport directly to the area without charge."
`
https://ffxiclopedia.fandom.com/wiki/Category:Assault

`
"Once the party is prepared, the designated leader initiates the mission by interacting with the Runic Seal. After selecting parameters, any party members in the vicinity of the Runic Seal will be automatically transported to the assault location and their Assault Orders will be marked as used. "
"Players in other zones or a large distance from the Seal will not be transported. Please ensure all your party members are nearby before initiating the mission."
`
https://www.bg-wiki.com/ffxi/Category:Assault#Initiating_an_Assault_Mission

**Comment by Skerxan** [comment]
Wooo issue number 1000! xD

**Comment by Skerxan** [comment]
Partly dublicate of #900

**Comment by TeoTwawki** [comment]
well then I guess technically issue number 999½ :stuck_out_tongue:

**Comment by claywar** [comment]
Just a heads up, this was merged into the TOAU Mission branch, and is not in base/everything yet
