### ISSUE TITLE
Incorrect File Path: FileWatch.hpp

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#1016]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

As per this previous issue: https://github.com/LandSandBoat/server/issues/683

This appears to still be an issue on some systems. I ran into this on a fresh install of LSB tonight. 
Information on the setup:

 - Windows 10 Pro (1607)
 - Visual Studio 2019 Enterprise (16.11.1)
 - LandSandBoat latest repo as of: 399659bc1ebc4ab42557b64f5e134c4c0ba57bc2
 - LandSandBoat location: `D:\Source Code\LandSandBoat\`

No changes have been made to anything source wise. This is directly pulled from Git. 
Moved the config files and updated the DB info. Nothing else was changed/altered.

For my systems setup, adding the additional `../` is valid as well since it would otherwise only go back far enough to be stuck inside of the `/src` folder.

I don't use CMAKE, so not sure if this is a bug / issue with the build system not handling base paths as expected or resetting the path between build steps etc.

**Comment by TeoTwawki** [comment]
Wondering if updates are related to triggering the error, as I also build with visual studio 2019 instead of cmake and its working for me, **but** my version is a out of date and my windows is older.

(you would think a path related error would be a universal same for everybody kind of thing..)

**Comment by atom0s** [comment]
Think the wording of my last sentence is a little misleading. 

 - I am using CMAKE as defined by the new build guide for LSB.
 - I don't use CMAKE personally on a regular basis to be familiar with how it works/what it does.

**Comment by TeoTwawki** [comment]
oh ok, I read "I don't use CMAKE" so yeah I was confused. I just let the cmake through vs do its thing.

**Comment by zach2good** [comment]
Yeah, I defined this dependency very lazily and it's very fragile. I'll take a look at this today, shouldn't take long 👍
