### ISSUE TITLE
Cannot Unequip Sub-Weapons

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#1017]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

While dual-wielding, it is impossible to unequip your sub-weapon directly. 
The check for this is happening here:
https://github.com/LandSandBoat/server/blob/base/src/map/utils/charutils.cpp#L2190

The check is too specific for a single situation and breaks the ability to work for other situations.

Steps to reproduce:

 - Login to any character.
 - Change to NIN 99. (!changejob nin 99)
 - Add two daggers. (!additem 16482, !additem 16482)
 - Equip one in your main hand, other in off hand.
 - Try to unequip off hand.

You'll get the error: "You must have a two-handed weapon equipped in the main weapon slot in order to equip a grip." since the check linked above is being too specific for all sub-item use cases.

**Comment by claywar** [comment]
Just checked this out on my end with the above procedure and was able to remove sub weapon without issue.  The check that you linked is for the initial equip (and grips should be the only sub item that have `SKILL_NONE`).  Is there an issue going on with equip on your end?

**Comment by TeoTwawki** [comment]
While I've never seen the specific bug mentioned (I don't recall ever having tried to empty my offhand though) I have noted that changing my mainhand de-equips my offhand even when it should not - on retail I am able swap either dagger on my thf without it affecting the other, which is not trues on LSB atm.

So DW in general deserves some investigating.

**Comment by atom0s** [comment]
~~I am not able to recreate the issue with the existing character after logging off and back on since I made the report. Wondering if it was due to a bug with a fresh char that just logged in and performed said actions immediately without logging out at all first.~~

~~From what I recall while checking loosely debug-wise, the check that was ultimately failing was the item was returning it had a skill type of SKILL_NONE on a dagger. That same dagger is working fine now though, so that is kind of odd.~~

~~Just tried with two more chars and both worked fine as well. So perhaps its a weird edge-case on an initial server launch after fully fresh install of LSB and first boot etc.~~

**Comment by atom0s** [comment]
Alright, spent a little more time and found the cause. This is happening due to an issue with how the first line is pulling an item.

See here:
https://github.com/LandSandBoat/server/blob/base/src/map/utils/charutils.cpp#L2183

When you are unequipping, `slotID` is set to 0, so with this current setup, you are pulling the players `Gil` item. Since its then casted to an invalid type for `ItemCurrency`, `getSkillType()` has a chance of returning 0, or any other value it wants since its casted to invalid memory.

**Comment by zach2good** [comment]
Thanks for digging in to this 🙏  I'll have some time to fix this after work today
