### ISSUE TITLE
Mog Garden is shared betweebn players and should not be

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#1021]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: All

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Right now on private servers if 2 players enter thier Mog Garden, they see each other and land at the same area with the same NPCs. this needs to be handled similar to a mog house "instance" (which are not instanced), where each player sees different content and can't interact with each other. Unlike the mog house however, the garden does NOT share zoneID with the zone you entered from - this is not a full fledged mog house acting as a sub-zone the way those do.

Implementing anything for the mog garden is problematic until this is solved.

**Comment by zach2good** [comment]
Ohhh this is fun, I can do this 👍

**Comment by zach2good** [comment]
In terms of seeing different NPCs, we'll probably handle all of that with show/hide in scripting, depending on your Mog House quest progress

**Comment by TeoTwawki** [comment]
> In terms of seeing different NPCs, we'll probably handle all of that with show/hide in scripting, depending on your Mog House quest progress

can't, since that would act on the object universally. a new thing has to be made for them to be toggled via script without every player causing all players mog gardens to be affected. I have an idea how tho.
