### ISSUE TITLE
Quadav Stew can only be stolen from Garnet Quadavs ATM

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#1039]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
It should be able to be stolen from Bronze, Silver and Zircon Quadavs. Only in Beadeaux Zone.

**Comment by claywar** [comment]
Need some confirmation on this from a thief without this quest flagged.  While it *should* be able to be stolen without the quest flagged, there's conflicting info about how it falls compared to the beastcoin steal for these mobs.

**Comment by TeoTwawki** [comment]
both before quest flagged and after quest completed tests would be desirable just to put to rest any further myths about that as well.

**Comment by Skerxan** [comment]
You both are talking about retail behaviour, right? Or test cases on LSB?

**Comment by TeoTwawki** [comment]
> You both are talking about retail behaviour, right? Or test cases on LSB?

@Skerxan we're looking for testing on retail to confirm what LSB should do

**Comment by CatsEyeXI** [comment]
No quest flagged
![image](https://user-images.githubusercontent.com/65316697/150545735-3d23290e-1189-4723-a8d6-b3eb7d0e8cc6.png)

**Comment by TeoTwawki** [comment]
@beneliezer and thats on retail right? Just making sure - wiki info got tainted by a wings player putting private server info to it

**Comment by CatsEyeXI** [comment]
> @beneliezer and thats on retail right? Just making sure - wiki info got tainted by a wings player putting private server info to it

Yes this is from retail

**Comment by CatsEyeXI** [comment]
That being said, i dont really understand how this is broken in LSB... according to scripts/globals/abilities/steal.lua the following ID's are already factored in... it appears to me that the correct mobs are already set? 

payload@DESKTOP-14BPVKT:~/catseyexi/sql$ for line in $(cat ids) ; do grep $line mob_spawn_points.sql ; done
INSERT INTO `mob_spawn_points` VALUES (17379367,'Bronze_Quadav','Bronze Quadav',10,-44.268,2.924,159.605,127);
INSERT INTO `mob_spawn_points` VALUES (17379368,'Bronze_Quadav','Bronze Quadav',10,-40.048,2.925,159.956,127);
INSERT INTO `mob_spawn_points` VALUES (17379459,'Bronze_Quadav','Bronze Quadav',10,-99.02,-0.217,-65.695,127);
INSERT INTO `mob_spawn_points` VALUES (17379470,'Bronze_Quadav','Bronze Quadav',10,-34.342,0.799,-126.935,11);
INSERT INTO `mob_spawn_points` VALUES (17379477,'Bronze_Quadav','Bronze Quadav',10,-135.809,-0.447,-178.141,26);
INSERT INTO `mob_spawn_points` VALUES (17379489,'Bronze_Quadav','Bronze Quadav',10,-239.241,2.944,-82.531,127);
INSERT INTO `mob_spawn_points` VALUES (17379493,'Bronze_Quadav','Bronze Quadav',10,-4.301,2.876,-81.055,127);
INSERT INTO `mob_spawn_points` VALUES (17379495,'Bronze_Quadav','Bronze Quadav',10,-40.132,2.924,-199.266,40);
INSERT INTO `mob_spawn_points` VALUES (17379501,'Bronze_Quadav','Bronze Quadav',10,-283.146,-3.668,-137.424,99);
INSERT INTO `mob_spawn_points` VALUES (17379505,'Bronze_Quadav','Bronze Quadav',10,-277.362,-3.826,-125.220,73);
INSERT INTO `mob_spawn_points` VALUES (17379509,'Bronze_Quadav','Bronze Quadav',10,-252.611,-3.5,-65.5,34);
INSERT INTO `mob_spawn_points` VALUES (17379513,'Bronze_Quadav','Bronze Quadav',10,-243.305,-3.659,-69.214,127);
INSERT INTO `mob_spawn_points` VALUES (17379517,'Bronze_Quadav','Bronze Quadav',10,-247.159,-3.528,13.870,70);
INSERT INTO `mob_spawn_points` VALUES (17379521,'Bronze_Quadav','Bronze Quadav',10,-195.374,-3.773,39.748,127);
INSERT INTO `mob_spawn_points` VALUES (17379525,'Bronze_Quadav','Bronze Quadav',10,-202.587,-3.388,20.781,40);
INSERT INTO `mob_spawn_points` VALUES (17379529,'Bronze_Quadav','Bronze Quadav',10,-159.598,-3.694,110.376,120);
INSERT INTO `mob_spawn_points` VALUES (17379533,'Bronze_Quadav','Bronze Quadav',10,-55.027,-3.562,81.477,111);
INSERT INTO `mob_spawn_points` VALUES (17379538,'Bronze_Quadav','Bronze Quadav',10,-39.815,-3.779,112.414,127);
INSERT INTO `mob_spawn_points` VALUES (17379543,'Bronze_Quadav','Bronze Quadav',10,-140.549,-3.505,163.328,127);
INSERT INTO `mob_spawn_points` VALUES (17379547,'Bronze_Quadav','Bronze Quadav',10,-189.135,-4.491,142.517,127);
INSERT INTO `mob_spawn_points` VALUES (17379552,'Bronze_Quadav','Bronze Quadav',10,-186.026,-3.458,-3.999,127);
INSERT INTO `mob_spawn_points` VALUES (17379556,'Bronze_Quadav','Bronze Quadav',10,-124.454,-3.285,-51.318,27);
INSERT INTO `mob_spawn_points` VALUES (17379560,'Bronze_Quadav','Bronze Quadav',10,-245.790,-3.495,-250.715,127);
INSERT INTO `mob_spawn_points` VALUES (17379565,'Bronze_Quadav','Bronze Quadav',10,-206.568,-3.669,-219.765,36);
INSERT INTO `mob_spawn_points` VALUES (17379569,'Bronze_Quadav','Bronze Quadav',10,-36.571,-3.626,-207.486,127);
INSERT INTO `mob_spawn_points` VALUES (17379573,'Bronze_Quadav','Bronze Quadav',10,-110.609,-3.048,-192.216,48);
INSERT INTO `mob_spawn_points` VALUES (17379577,'Bronze_Quadav','Bronze Quadav',10,3.604,-3.788,-122.909,127);
INSERT INTO `mob_spawn_points` VALUES (17379581,'Bronze_Quadav','Bronze Quadav',10,-30.360,-3.414,-90.256,127);
INSERT INTO `mob_spawn_points` VALUES (17379585,'Bronze_Quadav','Bronze Quadav',10,-212.043,-3.640,-157.621,127);
INSERT INTO `mob_spawn_points` VALUES (17379597,'Bronze_Quadav','Bronze Quadav',10,25.864,-3.570,-110.983,127);
INSERT INTO `mob_spawn_points` VALUES (17379363,'Garnet_Quadav','Garnet Quadav',8,-198.767,2.929,155.974,48);
INSERT INTO `mob_spawn_points` VALUES (17379364,'Garnet_Quadav','Garnet Quadav',8,-200.093,2.943,158.771,79);
INSERT INTO `mob_spawn_points` VALUES (17379462,'Garnet_Quadav','Garnet Quadav',8,-51.550,-4.261,-50.171,127);
INSERT INTO `mob_spawn_points` VALUES (17379473,'Garnet_Quadav','Garnet Quadav',8,-34.577,-2.410,-140.082,47);
INSERT INTO `mob_spawn_points` VALUES (17379480,'Garnet_Quadav','Garnet Quadav',8,-139.179,-3.763,-190.602,94);
INSERT INTO `mob_spawn_points` VALUES (17379496,'Garnet_Quadav','Garnet Quadav',8,-39.541,2.950,-197.550,127);
INSERT INTO `mob_spawn_points` VALUES (17379498,'Garnet_Quadav','Garnet Quadav',8,-202.084,2.972,-233.628,127);
INSERT INTO `mob_spawn_points` VALUES (17379500,'Garnet_Quadav','Garnet Quadav',8,-276.810,2.936,-236.784,127);
INSERT INTO `mob_spawn_points` VALUES (17379504,'Garnet_Quadav','Garnet Quadav',8,-267.198,-3.252,-122.763,17);
INSERT INTO `mob_spawn_points` VALUES (17379508,'Garnet_Quadav','Garnet Quadav',8,-240.718,-3.344,-126.709,75);
INSERT INTO `mob_spawn_points` VALUES (17379512,'Garnet_Quadav','Garnet Quadav',8,-240.910,-3.801,-80.242,34);
INSERT INTO `mob_spawn_points` VALUES (17379516,'Garnet_Quadav','Garnet Quadav',8,-234.075,-3.374,-5.490,96);
INSERT INTO `mob_spawn_points` VALUES (17379520,'Garnet_Quadav','Garnet Quadav',8,-233.663,-3.125,11.963,127);
INSERT INTO `mob_spawn_points` VALUES (17379524,'Garnet_Quadav','Garnet Quadav',8,-181.497,-3.499,22.280,127);
INSERT INTO `mob_spawn_points` VALUES (17379528,'Garnet_Quadav','Garnet Quadav',8,-117.604,-3.750,37.079,112);
INSERT INTO `mob_spawn_points` VALUES (17379532,'Garnet_Quadav','Garnet Quadav',8,-155.537,-3.349,102.085,127);
INSERT INTO `mob_spawn_points` VALUES (17379536,'Garnet_Quadav','Garnet Quadav',8,-73.371,-3.501,44.107,62);
INSERT INTO `mob_spawn_points` VALUES (17379541,'Garnet_Quadav','Garnet Quadav',8,-60.051,-3.532,164.011,10);
INSERT INTO `mob_spawn_points` VALUES (17379546,'Garnet_Quadav','Garnet Quadav',8,-122.272,-3.102,157.548,66);
INSERT INTO `mob_spawn_points` VALUES (17379550,'Garnet_Quadav','Garnet Quadav',8,-206.340,-3.536,166.275,127);
INSERT INTO `mob_spawn_points` VALUES (17379555,'Garnet_Quadav','Garnet Quadav',8,-199.099,-3.731,-2.042,123);
INSERT INTO `mob_spawn_points` VALUES (17379559,'Garnet_Quadav','Garnet Quadav',8,-119.802,-3.772,-39.419,10);
INSERT INTO `mob_spawn_points` VALUES (17379563,'Garnet_Quadav','Garnet Quadav',8,-285.203,-3.670,-216.772,104);
INSERT INTO `mob_spawn_points` VALUES (17379568,'Garnet_Quadav','Garnet Quadav',8,-190.290,-3.533,-222.881,127);
INSERT INTO `mob_spawn_points` VALUES (17379572,'Garnet_Quadav','Garnet Quadav',8,-75.551,-3.5,-213.477,3);
INSERT INTO `mob_spawn_points` VALUES (17379576,'Garnet_Quadav','Garnet Quadav',8,-40.998,-3.771,-171.661,127);
INSERT INTO `mob_spawn_points` VALUES (17379580,'Garnet_Quadav','Garnet Quadav',8,-26.691,-3.537,-46.441,127);
INSERT INTO `mob_spawn_points` VALUES (17379584,'Garnet_Quadav','Garnet Quadav',8,2.186,-3.530,-136.485,126);
INSERT INTO `mob_spawn_points` VALUES (17379588,'Garnet_Quadav','Garnet Quadav',8,-235.277,-3.112,-169.650,127);
INSERT INTO `mob_spawn_points` VALUES (17379600,'Garnet_Quadav','Garnet Quadav',8,23.143,-3.553,-119.358,127);
INSERT INTO `mob_spawn_points` VALUES (17379361,'Silver_Quadav','Silver Quadav',7,-234.196,2.961,41.944,8);
INSERT INTO `mob_spawn_points` VALUES (17379362,'Silver_Quadav','Silver Quadav',7,-238.942,2.936,40.698,95);
INSERT INTO `mob_spawn_points` VALUES (17379460,'Silver_Quadav','Silver Quadav',7,-109.994,0.257,-95.516,168);
INSERT INTO `mob_spawn_points` VALUES (17379471,'Silver_Quadav','Silver Quadav',7,-27.375,0.485,-127.596,49);
INSERT INTO `mob_spawn_points` VALUES (17379478,'Silver_Quadav','Silver Quadav',7,-108.236,-0.04,-172.188,88);
INSERT INTO `mob_spawn_points` VALUES (17379490,'Silver_Quadav','Silver Quadav',7,-237.269,2.930,-82.624,127);
INSERT INTO `mob_spawn_points` VALUES (17379491,'Silver_Quadav','Silver Quadav',7,-38.872,2.929,-41.764,40);
INSERT INTO `mob_spawn_points` VALUES (17379497,'Silver_Quadav','Silver Quadav',7,-201.492,2.964,-234.171,127);
INSERT INTO `mob_spawn_points` VALUES (17379502,'Silver_Quadav','Silver Quadav',7,-266.003,-3.430,-99.618,127);
INSERT INTO `mob_spawn_points` VALUES (17379506,'Silver_Quadav','Silver Quadav',7,-278.264,-3.720,-164.780,62);
INSERT INTO `mob_spawn_points` VALUES (17379510,'Silver_Quadav','Silver Quadav',7,-213.559,-3.628,-81.4,118);
INSERT INTO `mob_spawn_points` VALUES (17379514,'Silver_Quadav','Silver Quadav',7,-221.149,0.425,-59.062,127);
INSERT INTO `mob_spawn_points` VALUES (17379518,'Silver_Quadav','Silver Quadav',7,-234.203,-3.378,6.377,114);
INSERT INTO `mob_spawn_points` VALUES (17379522,'Silver_Quadav','Silver Quadav',7,-183.950,-3.585,40.571,127);
INSERT INTO `mob_spawn_points` VALUES (17379526,'Silver_Quadav','Silver Quadav',7,-176.360,-3.604,41.196,127);
INSERT INTO `mob_spawn_points` VALUES (17379530,'Silver_Quadav','Silver Quadav',7,-172.608,-3.121,85.533,127);
INSERT INTO `mob_spawn_points` VALUES (17379534,'Silver_Quadav','Silver Quadav',7,-87.604,-2.724,104.463,8);
INSERT INTO `mob_spawn_points` VALUES (17379539,'Silver_Quadav','Silver Quadav',7,-28.273,-3.511,133.169,0);
INSERT INTO `mob_spawn_points` VALUES (17379544,'Silver_Quadav','Silver Quadav',7,-117.886,-3.537,160.911,127);
INSERT INTO `mob_spawn_points` VALUES (17379548,'Silver_Quadav','Silver Quadav',7,-212.085,-3.678,125.425,127);
INSERT INTO `mob_spawn_points` VALUES (17379553,'Silver_Quadav','Silver Quadav',7,-170.037,-3.651,-45.787,127);
INSERT INTO `mob_spawn_points` VALUES (17379557,'Silver_Quadav','Silver Quadav',7,-112.241,-3.886,-42.422,5);
INSERT INTO `mob_spawn_points` VALUES (17379561,'Silver_Quadav','Silver Quadav',7,-286.6,-3.630,-216.650,35);
INSERT INTO `mob_spawn_points` VALUES (17379566,'Silver_Quadav','Silver Quadav',7,-189.368,-3.524,-217.974,57);
INSERT INTO `mob_spawn_points` VALUES (17379570,'Silver_Quadav','Silver Quadav',7,-44.587,-3.487,-213.370,62);
INSERT INTO `mob_spawn_points` VALUES (17379574,'Silver_Quadav','Silver Quadav',7,-71.614,-3.5,-216.162,127);
INSERT INTO `mob_spawn_points` VALUES (17379578,'Silver_Quadav','Silver Quadav',7,17.740,-3.5,-152.585,127);
INSERT INTO `mob_spawn_points` VALUES (17379582,'Silver_Quadav','Silver Quadav',7,-43.343,-3.666,-58.01,97);
INSERT INTO `mob_spawn_points` VALUES (17379586,'Silver_Quadav','Silver Quadav',7,-248.141,-2.859,-150.123,24);
INSERT INTO `mob_spawn_points` VALUES (17379598,'Silver_Quadav','Silver Quadav',7,36.846,-3.784,-119.128,84);
INSERT INTO `mob_spawn_points` VALUES (17379365,'Zircon_Quadav','Zircon Quadav',9,-155.256,2.922,84.093,127);
INSERT INTO `mob_spawn_points` VALUES (17379366,'Zircon_Quadav','Zircon Quadav',9,-159.283,2.935,85.325,127);
INSERT INTO `mob_spawn_points` VALUES (17379461,'Zircon_Quadav','Zircon Quadav',9,-66.965,0.104,-65.036,127);
INSERT INTO `mob_spawn_points` VALUES (17379472,'Zircon_Quadav','Zircon Quadav',9,-35.733,0.688,-126.219,24);
INSERT INTO `mob_spawn_points` VALUES (17379479,'Zircon_Quadav','Zircon Quadav',9,-67.076,0.062,-171.693,57);
INSERT INTO `mob_spawn_points` VALUES (17379492,'Zircon_Quadav','Zircon Quadav',9,-39.645,2.923,-40.320,127);
INSERT INTO `mob_spawn_points` VALUES (17379494,'Zircon_Quadav','Zircon Quadav',9,-4.615,2.922,-81.103,127);
INSERT INTO `mob_spawn_points` VALUES (17379499,'Zircon_Quadav','Zircon Quadav',9,-277.527,2.922,-236.526,127);
INSERT INTO `mob_spawn_points` VALUES (17379503,'Zircon_Quadav','Zircon Quadav',9,-279.038,-3.705,-186.366,111);
INSERT INTO `mob_spawn_points` VALUES (17379507,'Zircon_Quadav','Zircon Quadav',9,-295.277,-3.5,-130.490,2);
INSERT INTO `mob_spawn_points` VALUES (17379511,'Zircon_Quadav','Zircon Quadav',9,-213.930,0.263,-65.652,41);
INSERT INTO `mob_spawn_points` VALUES (17379515,'Zircon_Quadav','Zircon Quadav',9,-249.678,-3.5,-52.752,79);
INSERT INTO `mob_spawn_points` VALUES (17379519,'Zircon_Quadav','Zircon Quadav',9,-231.184,-3.475,14.421,81);
INSERT INTO `mob_spawn_points` VALUES (17379523,'Zircon_Quadav','Zircon Quadav',9,-96,-3,34,127);
INSERT INTO `mob_spawn_points` VALUES (17379527,'Zircon_Quadav','Zircon Quadav',9,-149,-3,35,127);
INSERT INTO `mob_spawn_points` VALUES (17379531,'Zircon_Quadav','Zircon Quadav',9,-124.871,-3.134,90.776,65);
INSERT INTO `mob_spawn_points` VALUES (17379535,'Zircon_Quadav','Zircon Quadav',9,-66.578,-3.568,74.306,92);
INSERT INTO `mob_spawn_points` VALUES (17379540,'Zircon_Quadav','Zircon Quadav',9,-31.017,-3.545,166.427,127);
INSERT INTO `mob_spawn_points` VALUES (17379545,'Zircon_Quadav','Zircon Quadav',9,-121.621,-2.846,143.255,127);
INSERT INTO `mob_spawn_points` VALUES (17379549,'Zircon_Quadav','Zircon Quadav',9,-187.053,-3.699,164.879,30);
INSERT INTO `mob_spawn_points` VALUES (17379554,'Zircon_Quadav','Zircon Quadav',9,-205.510,-3.227,-5.396,127);
INSERT INTO `mob_spawn_points` VALUES (17379558,'Zircon_Quadav','Zircon Quadav',9,-102.916,-3.542,-37.650,83);
INSERT INTO `mob_spawn_points` VALUES (17379562,'Zircon_Quadav','Zircon Quadav',9,-294.223,-3.504,-206.657,127);
INSERT INTO `mob_spawn_points` VALUES (17379567,'Zircon_Quadav','Zircon Quadav',9,-166.912,-3.354,-215.349,97);
INSERT INTO `mob_spawn_points` VALUES (17379571,'Zircon_Quadav','Zircon Quadav',9,-102.395,-3.076,-183.984,1);
INSERT INTO `mob_spawn_points` VALUES (17379575,'Zircon_Quadav','Zircon Quadav',9,-80.674,-2.988,-187.141,127);
INSERT INTO `mob_spawn_points` VALUES (17379579,'Zircon_Quadav','Zircon Quadav',9,-43.534,-3.336,-88.380,127);
INSERT INTO `mob_spawn_points` VALUES (17379583,'Zircon_Quadav','Zircon Quadav',9,-9.491,-4.414,-91.708,14);
INSERT INTO `mob_spawn_points` VALUES (17379587,'Zircon_Quadav','Zircon Quadav',9,-208.378,-3.724,-159.990,120);
INSERT INTO `mob_spawn_points` VALUES (17379599,'Zircon_Quadav','Zircon Quadav',9,24.772,-3.501,-106.135,113);
