### ISSUE TITLE
delStatusEffectSilent from lua is not actually silent

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#1047]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Cast Dia on a mob, then use Light Shot. It will say the Dia effect has worn off, despite the script for Light Shot using the delStatusEffectSilent binding. This affects all elements of Quick Draw, the SCH weather spells, and possibly other things.

https://github.com/LandSandBoat/server/blob/base/scripts/globals/abilities/light_shot.lua#L59

Not to be confused with the delStatusEffectSilent used in the core. I tested that with engaging a mob while mounted, and I did not get a dismount message, so I would think that is fine.

**Comment by almuth150** [comment]
This issue means https://github.com/LandSandBoat/server/issues/817 would probably not be resolved if the specified changes were made, by the way.

**Comment by claywar** [comment]
Confirmed.  We don't pass any silent param to CStatusEffectContainer::RemoveStatusEffect(), but instead call DelStatusEffect directly.
