### ISSUE TITLE
[ci] Multi-instance startup check does not fail on Warning

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#1050]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Single-instance will fail properly on Warning for missing NPC; however, multi-instance appears to have passed the check.

**Comment by zach2good** [comment]
I think the single instance failure you're looking at is failing on this:
```
Error: 8:12:632][login][error][error] lobbyview_parse: Incorrect client version: got 302110xx_x, expected 302111xx_x (lobbyview_parse:505)
Error: 8:12:632][login][error][error] lobbyview_parse: The client must be updated to support this server version (lobbyview_parse:525)
```

But quite right, we should fail builds on warnings too!

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/server/runs/4353518180?check_suite_focus=true

**Comment by claywar** [comment]
Ahh, quite right with my oversight on the version check failure
