### ISSUE TITLE
[Character Creation][Interaction] Bastok Markets introductory CS overriden by Adoulin introductory CS

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#1069]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

What title sais. The initial CS isn't triggered at all and instead, the Adoulin CS is played.

**Comment by claywar** [comment]
Fixed by #3298
