### ISSUE TITLE
Issue setting up first time server - can't find xi_connect/xi_game?

### ISSUE THREAD

**Issue by meissnereric** [DerpyProjectGroup/topaz#1083]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Hi,

So I'm trying to setup a server/client for the first time so please let me know if I say anything totally nonsense :)
We've been following your Windows 10 server setup guide and Windows 10 client setup guides found on your wikis but have gotten stuck [here](https://github.com/LandSandBoat/server/wiki/Client-Setup-[Windows]#5-connecting-to-a-private-server), on step 5.

We've got the LandSandBoat/server built and running (correctly I think? topax_game.exe seems to run fine and output sensible things). I've also got xi_loader building just fine.

But when I run ```xi_loader``` it starts up fine, prints the copyright messages in main just fine, but then it fails to connect to the server. ```Failed to connect to server!```

I've tried a variety of things but can't quite figure out what's going wrong. It could be something we did wrong on the server setup side, but we didn't change much aside from the MariaDB passwords as directed in your setup wiki, and it seems to be running fine.

A few questions:
* What are xi_connect / xi_game? I can't find those files anywhere in either of the repos, but the instructions say we need to run them before trying to connect locally. Do those files exist, or have things updated to where we don't need them anymore?
* I'm passing ```127.0.0.1``` as the server to xi_loader/xi_checker, because the server is running on the same machine. Is that sensible or is it looking for something else there? Is there a particular port I need to pass in as well? (I've tried adding ```54230``` as the port there but I assume it's the default, and it returns the same error.)

For now we're just doing a local server+client, though we'll want to expand that later.

Thanks a lot for any help, looking forward to being able to play!
Eric

**Comment by zach2good** [comment]
Hi there!

It seems that our docs are kinda out of sync with what the repo actually produces. `topaz_connect`, `topaz_game`, and `topaz_search` are what are produced by this repo, and the executables should appear in the root of the repo after a successful build (with _x64 suffix on windows 64, if that's your build).

`xiloader` (and I guess the checker) are produced by that other project.

Connect: allows you to create accounts, serves you the character select screen, and acts as the inter-process messaging router. This should be up at all times.

Game: this is the main game play logic. Should be up at all times.

Search: handles auction house and /sea searches. Optional, unless you want those things.

127.0.0.1 should be fine as a setting, but it might need the argument: --hairpin. I've never known the specifics of why that's needed, but it's something about connecting to a server on the same network or machine as the client.

Let us know if you need more guidance, and I'll try to update the docs to be more clear soon!

**Comment by TeoTwawki** [comment]
@zach2good hairpin argument is sort of an override for the address, generaly should only be used when the server is setup for external access but someone on the same lan or same machine need to connect. It lets the client use a different address when the server is saying its on the external ip

**Comment by TeoTwawki** [comment]
Exe names on the wiki got caught in a mass find and replace I did for “topaz” but we’ll soon be changing those anyway - I’ll update wiki after we do

**Comment by meissnereric** [comment]
Hey!

Thanks so much for the help folks, it worked like a charm once I knew to start the topaz_connect.exe file! So excited to start playing :D I did not have to use hairpin, and 127.0.0.1 worked fine for the server.

**Comment by meissnereric** [comment]
Can I ask another really simple question here before we close the issue?

How do I set myself or another player as a GM? I can't quite find the answer on your wikis, so if I missed it please point it out to me!

I can figure out how to change variables in the CPP files regarding the server, and I think I understand that *once* I'm a GM I can run things from in game by typing !command, but I can't figure out how to become a GM in the first place? Do I need to run another script to modify the SQL database first?

Thanks again :)
