### ISSUE TITLE
[task] Update LuaJIT and ZMQ

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#1102]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Now that we have access to `CPM.cmake`, it isn't a gargantuan task to add the option to build LuaJIT from source, and use a more up-to-date version. It appears as though development on LuaJIT has resumed and it has received some fixes and updates this year. One of those being the `lightuserdata` thing that will allow it to run on ARM64 -> Raspberry Pi etc.

Anyone getting deps from Ubuntu 20.04 onwards _should_ be getting that version anyway.

I'd like to add a configuration option: `BUILD_LUAJIT_FROM_SOURCE`, for those that want such a thing.
Same for:
- `BUILD_ZMQ_FROM_SOURCE` etc.

**Comment by TeoTwawki** [comment]
> One of those being the lightuserdata thing that will allow it to run on ARM64

_prepares to  run LandSandBoat on ARM64 based NAS hardware_

**Comment by zach2good** [comment]
Started in https://github.com/LandSandBoat/server/pull/1034

**Comment by zach2good** [comment]
> One of those being the lightuserdata thing that will allow it to run on ARM64 -> Raspberry Pi etc.

We talked about this in a discussion recently, as long as you pull recent enough deps, arm64 will work fine 🎉 
https://github.com/LandSandBoat/server/discussions/1138

**Comment by TeoTwawki** [comment]
yup, post was made before I knew about it

**Comment by zach2good** [comment]
Ended up doing this and checking in the new binaries, see you again in another 5 years or so!
