### ISSUE TITLE
somehow, a player on my 75 cap server hit 76

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#1143]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
my settings file has 75 in it. After I updated for xmas had a player able to trigger the next limit break quest and ding 76. Disabled the lb quest to prevent it happening again and then rolled it back. Went looking for something that had the wrong check in the quest script but apparently all I did was break limit breaker in my decaffeinated state.

**Comment by Xaver-DaRed** [comment]
I have been trying to break the logic of this quests but i just couldn't. I don't know how it could happen, unless exp somehow overflowed or something. Exp does very weird things from what i've seen in my testing, but I would think thats unrelated to this.

**Comment by TeoTwawki** [comment]
iunno. he actually had the quest somehow. I wonder if there was a bug _before_ converting to interaction, and he completed it and I never knew till he dinged after.
