### ISSUE TITLE
/tell not going to other player

### ISSUE THREAD

**Issue by ghost** [DerpyProjectGroup/topaz#1146]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I was trying to send tell to another player and they not able to get the /tell. Is there something been missed?

All other chat does work at normal it just the /tell. I found that was update about the /tell but not able to pin point.

**Comment by zach2good** [comment]
Make sure you've read the Contributing Guide guide, and marked the box to confirm you've done so. 

- Using latest retail client: `30211204_0`
- Using a build from Dec 21st: 6e7b68579a90822ae76665e591c2b7209d74af44
- Running `topaz_connect`
- Running `topaz_game`
- Both characters using Ashita-v4-beta, with no additional addons

- ![image](https://user-images.githubusercontent.com/1389729/147569751-a3372748-a7ba-4061-817c-44e1d6d350ca.png)

Everything working as expected.

- Using latest master: 11944bfe44afbcf51569d6f3bbd92fdffe9c0eaa

![image](https://user-images.githubusercontent.com/1389729/147570287-e2d2717d-8500-4a12-8d44-a66373689dc0.png)

Everything working as expected.

Are you using an older client (older than Nov-2020 will cause problems) or using addons used to bypass these client-related problems (tellfix etc.)?

**Comment by ghost** [comment]
Hmm I will double check

**Comment by RAIST5150** [comment]
Just to rule it out,, may want to make sure the other player is not set to any anonymous/hidden modes either.

**Comment by ghost** [comment]
I have reinstall the server files. Did the same with Ashita v3. Made sure FFXI is up to date with the latest Ver. It send the /tell, but it is not received. I am not using any add-on or modify files in any way. so I not sure what I am missing. Attach image shows what happens when sending the /tell. 
Map server does not show a message been sent just [info] [info] parse: 0B6 | 004A 0049 0C from user: Xsoulsin (parse:632)


![Screenshot 2021-12-29 015629](https://user-images.githubusercontent.com/95522524/147635417-d75da125-5803-47e5-8f29-83b09fd34119.png)

**Comment by RAIST5150** [comment]
Can you receive tells sent to yourself?

**Comment by ghost** [comment]
Nope that does not work either. I know mention works on Ashita V4 Beta. I did test with V4 and still same results. So I am not sure what happening on my end. as mention all other chat show up normal. the /tell only thing and mention I changed nothing on my end. Just to note, I did also test with fresh database to rule that out, not sure if that would affect but did test.

**Comment by ghost** [comment]
Ok just wanted to update. Also Linkshell, Party Chat is not working. Everything is up to date.

Say, Yell, Shout is all working, can send and reply. just tell, linkshell, party is not

I have it logging chat, but no message coming

![Screenshot 2022-01-06 155620](https://user-images.githubusercontent.com/95522524/148450830-9db3fce1-b068-4494-9b41-a4093125180c.png)

**Comment by TeoTwawki** [comment]
[changed any message server setting?](https://github.com/LandSandBoat/server/blob/base/conf/default/login.conf#L64)

**Comment by ghost** [comment]
Nope nothing was changed
![Screenshot 2022-01-06 161010](https://user-images.githubusercontent.com/95522524/148452541-6842b123-2684-4eac-8bef-988628d95191.png)

**Comment by TeoTwawki** [comment]
I would think has to be client side problem or firewall at either client or server. I assume by now lobby server has been restarted, probably more than once.

**Comment by ghost** [comment]
It has. I am not sure what could be on client side. unless my firewall is blocking. I made sure that server is allowed for firewall. I am lost for words

I am using Ashita V3 with POL Boot comes with

**Comment by TeoTwawki** [comment]
whats does `/ver` say? and is any plugin used?

**Comment by zach2good** [comment]
Here's something you can try: change the chat audit settings so that they're written to the database, that'll help is narrow down where the problem is

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/server/blob/ba6f5c05fe4810473bd36df3534dd0094658ecbb/conf/default/map.conf#L240

**Comment by TeoTwawki** [comment]
> Here's something you can try: change the chat audit settings so that they're written to the database, that'll help is narrow down where the problem is

from his pic looks like already on. he may need to turn them off - they could be bugged

**Comment by ghost** [comment]
![Screenshot 2022-01-06 162611](https://user-images.githubusercontent.com/95522524/148454439-b1eeac6e-588b-4c89-b38b-0620bad6a1e4.png)


I use AshitaCast, checker, ibar, enternity, dressme

**Comment by claywar** [comment]
Can you grep your files to see if you have 205.205.205.205 listed anywhere as an IP? That seems a bit wonky to me.

**Comment by TeoTwawki** [comment]
k those should be safe. do you connect via `--hairpin` for your server? some need it, some do not. depends on where things are relative to client

**Comment by ghost** [comment]
Teo btw chat logging was off at first. I toggle on incase needed

I do have --hairpin set

**Comment by ghost** [comment]
Claywar where would I check for the 205.205.205.205?

**Comment by TeoTwawki** [comment]
whats zone ip set to, and whats hair pin ip set to?

**Comment by claywar** [comment]
If you have Linux (or WSL) from your root directory of the repo, `grep -R "205.205.205.205" .` else, probably check your confs

**Comment by ghost** [comment]
I am running on Windows. I dont know Linux that well

**Comment by ghost** [comment]
--server legionxi.ddns.net --hairpin

**Comment by TeoTwawki** [comment]
ok thats not quite how you use hairpin normally and may explain the issue. hairpin overides the connection address. I will explain better shortly but in a meeting at work

**Comment by ghost** [comment]
Ok thanks.

**Comment by TeoTwawki** [comment]
```
C:\WINDOWS\system32>ping legionxi.ddns.net

Pinging legionxi.ddns.net [lol censored] with 32 bytes of data
```
The normal usage of hairpin is to have a server set externally available (external IP in `zone_settings`) and then hairpin to the local address. so `lol censored` in zone settings and if your server were on the same machine as your client you would hairpin it to `127.0.0.1` - if you were on a different pc on the same home network as the server, you might use something like `192.168.1.10` (whatever the server is on your LAN).

Now, I do not know that this is the cause of your chat issue. but its defiantly an incorrect usage and we can try correcting it and see what happens.

Also note that in zone settings it has to be the actual ip numbers, not the domain name.

**Comment by ghost** [comment]
zone settings is legionxi.ddns.net so should I change that? 

I have the server running off a laptop

Teo can I ask you edit the message to remove my IP please

**Comment by TeoTwawki** [comment]
bro you can't run a public server without the IP being findable. the internet doesn't work that way.

**Comment by ghost** [comment]
I have setup with No-Ip to route to IP I have set, but I will fix the IP in zone settings that could fix my issue

**Comment by RAIST5150** [comment]
Not sure if you realize, but that IP is publicly available via DNS lookup.  That us how he found it... kinda the point of publishing FQDN's.

https://myip.ms/info/whois/76.164.251.115/k/391583365/website/legionxi.ddns.net

**Comment by ghost** [comment]
Ok that fixed it for the issue was the zone settings

didnt know that would break it

**Comment by TeoTwawki** [comment]
```
C:\WINDOWS\system32>ping google.com

Pinging google.com [142.250.191.206] with 32 bytes of data:
Reply from 142.250.191.206: bytes=32 time=13ms TTL=113
Reply from 142.250.191.206: bytes=32 time=13ms TTL=113
Reply from 142.250.191.206: bytes=32 time=14ms TTL=113
Reply from 142.250.191.206: bytes=32 time=15ms TTL=113

Ping statistics for 142.250.191.206:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 13ms, Maximum = 15ms, Average = 13ms

C:\WINDOWS\system32>ping microsoft.com

Pinging microsoft.com [40.76.4.15] with 32 bytes of data:
```
its not hacking, its a normal part of networking. having the ip doesn't even mean I can even do anything. The rest of the world HAS to be able to resolve the name to an address or nothing can connect.
 a simple `ping` will tell anybody the ip address. the reason to use no-ip is ****not*** to hide the ip, its so that when your ip changes you don't have to inform everyone of the new one - they just use the name.

**Comment by ghost** [comment]
Thanks for help Teo. as all is working.
