### ISSUE TITLE
Race restricted equipment / RSE is not restricted

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#1147]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Players can use equipsets or addons to equip gear that is ineligible to equip for their race. Example, a Galka equipping Taru RSE, or males equipping female wedding gear.

I've kept forgetting about this and whenever I was reminded, I was never able to find someone who knows if current retail blocks this, because I know that old retail also lacked these checks (though you'd get jailed for it). But now I've been informed that current retail does indeed have server-side checks that prevents players from equipping RSE from other races.

**Comment by TeoTwawki** [comment]
Thanks - we've kept forgetting about this also. We had an issue in the previous iteration of development but when that got blown up by drama this issue was one of the casualties.
