### ISSUE TITLE
Minne vs Paeon

### ISSUE THREAD

**Issue by rheinecatsin** [DerpyProjectGroup/topaz#1172]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

Casting Knight's Minne III and IV have effect of  Army's Paeon (+18 and + 30 hp per tick respectively) but no defense increase. Mistake is easy to find in code.

**Comment by TeoTwawki** [comment]
I've made a fix for the effect being wrong (#1171) but you were telling me the power levels were incorrect even after that. Can you elaborate on that here?

**Comment by rheinecatsin** [comment]
Knight Minne IV from a 75 brd with capped wind and sing skills should be a good boost to def (around +100 and +60 iirc).  KMIv gave me +30 and KM III gave +18. Much lower than expected value.

**Comment by rheinecatsin** [comment]
Which are the same value i had from regen bonuses +48.  Def+ bonuses doesnt seem to be scalling and only using 0 level skill values ?

**Comment by Xaver-DaRed** [comment]
That happened becouse Minnes were using calculations for paeons, but with the base values of minnes

The fix should make it alright
