### ISSUE TITLE
Lure of the Wildcat (Jeuno) - Bluffnix not replying

### ISSUE THREAD

**Issue by JinxDojo** [DerpyProjectGroup/topaz#1177]
I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
I have checked the commit log to see if the issue has been resolved since my server was last updated
I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
I have specified what branch this happens on branch: 202102_1 (stable)

Additional Information (Steps to reproduce/Expected behavior) :

I am experiencing an issue with the "Lure of the Wildcat (Jeuno)" quest in which Bluffnix does not "flash his badge." All other characters involved in this quest seem to work properly. The LUA code for Bluffnix seems to imply he should work, but I also see that Gobbiebag logic was removed entirely to its own script, making me unsure how well I really understand the NPC-interaction process.

I experience this on whasf's "Oldschool" server. While the version reports as 202102_1 (stable), whasf does update it regularly (though in what capacity, I do not know), and it was just updated on 2022/01/04. If it helps: there are other players on the server that previously/successfully completed the aforementioned quest.

This is the first issue I'm reporting; I've tried to do as much due diligence as I can. (Unfortunately, without an active IRC channel, I see no way to vet/test possible issues with others before reporting.) I hope my efforts/report will be well-received. Thank you.

**Comment by kaincenteno** [comment]
Welcome @JinxDojo  :D 

It would be of great use if you could ask the server admin for what they see on their end when you try to flash your badge for Bluffnix

**Comment by TeoTwawki** [comment]
There are bugs with NPCs that have involvement in both a quest that was converted to the new system, and one that has not. the converted quests wind up blocking those that were not.

Missions too!
Another example of this is the quest "food for thought" stopping the Chains of Promathia mission from moving forward.

**Comment by JinxDojo** [comment]
Hi Teo & Kain! Thanks for the replies.

Should I still go ahead and ask Whasf for the log? Or is it pretty much a "known issue"? Is there any way I can help fix it? Is there an explanation somewhere on how the code functions? (I assumed the character name and associated action activated the relevant LUA script, but clearly that's not how it works for Bluffnix / Gobbiebags now--perhaps there are multiple binds to each event?). I don't know how much time I might have to contribute, but I'd like to try.

Unrelatedly: where is the best place to submit SQL update requests (specifically: synth_recipes.sql)? On an issue? In the discussions? (I noticed there are discussions here on Github now, and while I still would like to see everyone on IRC again, at least there is a place to ask general questions!)

Finally: is the manner in which I submitted this issue generally acceptable? If so, I have some other things I've noted in my travels that I'd like to submit, but I will understand if you'd prefer I take them to "Discussions" first.

Thanks again!

**Comment by Xaver-DaRed** [comment]
So, there is a new system called "Interaction system".
It's meant to handle quest and missons interactions.
Regularly, onTrigger would handle npc actions, but this system bypasses it when a quest is available.

You can check the converted quests here:
https://github.com/LandSandBoat/server/tree/base/scripts/quests

As for your other question:
IF, and only IF, a recipe isnt implemented or diabled in this repository, you can create either a new issue or a discussion and list them there.
You can check available recipes and if they are disabled or note here:
https://github.com/LandSandBoat/server/blob/base/sql/synth_recipes.sql
Disabled recipes have a 255 lvl requirement in a craft lvl.

**Comment by JinxDojo** [comment]
Thanks for the quick reply, Xaver-DaRed, and the explanation about the "interaction system." Seems a bit complex--I'd be interested in knowing what caused the need for such a system--but this probably isn't the place for that.

As for recipes: is there an explanation somewhere for why certain recipes are disabled? It seems odd, for example, that "Wool Hat" (line 2265) is disabled.

**Comment by Xaver-DaRed** [comment]
It's simple.

When coding and adressing issues with quests or missions, it's much better to have the whole logic of a single quest inside a single file, instead of divided among every single possible npc and mob involved in it.

To that, you have to add that adding logic to an npc implies that the logic inside said npc will grow out of proportion when said npc is involved in a lot of missions and quests.

The way the interaction system works makes it so the logic will cycle among all posible interactions open, wich adresses the issue of blocking quests progress when another, different, quest is open.

It has the side effect of posibly conflicting with not-currently converted quests. It is a work in progress.

As for the recipes.
Disabled recipes were disabled for several reasons:
- becouse there is conflicting information among the 4 main wikis. Be it, required lvls or result amounts.
- becouse over the time, an amount of non-existant "cheat" recipes were aded to the project.

**Comment by RAIST5150** [comment]
> Thanks for the quick reply, Xaver-DaRed, and the explanation about the "interaction system." Seems a bit complex--I'd be interested in knowing what caused the need for such a system--but this probably isn't the place for that.
> 
> As for recipes: is there an explanation somewhere for why certain recipes are disabled? It seems odd, for example, that "Wool Hat" (line 2265) is disabled.

 A lot of unconfirmable recipes got disabled during the last scrape of wiki data a good while back.  We started manually revisiting the disabled recipes a few months back in an open issue (#885).

Unfortunately, we were still running into a LOT of questionable data, and there really hasn't been much wiki discussion on things for many years now.  So it mostly boils down to one or two wiki's with numbers, and those often still have one or more values flagged for verification.

Think we only got to update about 1/3 of the items in the posted file, though we may have been approaching about the halfway mark on reviewing the recipes.

Real life stuff eventually just got in the way of progress again. Hopefully we can get back to it again soon.

**Comment by TeoTwawki** [comment]
> stuff about synth recipes

There are many potential snags (even hypothetical circular reporting where wiki A got its info from somebody who read wiki B) and without someone actively testing on retail we'll never get to the finish line, but these things are best discussed in issues or discussion threads that were made expressly for that topic.

**Comment by Noikar** [comment]
I have a non-sexy fix for this I can PR if you want. I just had him check Lure progress in the Gobbiebag quest script.

**Comment by JinxDojo** [comment]
Hello again. Was this ever fixed? I've been unable to complete this quest--as far as I can tell, the Gobbiebag quests still take priority.

@Lynnea1320 : Assuming no one else minds, I'd like to see your fix posted.

**Comment by Noikar** [comment]
Line 79 in scripts/quests/jeuno/helper.lua
```lua
            [xi.zone.LOWER_JEUNO] =
            {
                ['Bluffnix'] =
                {
                    onTrade = function(player, npc, trade)
                        if  npcUtil.tradeHasExactly(trade, params.tradeItems) or
                            npcUtil.tradeHasExactly(trade, params.tradeStew)
                        then
                            return quest:progressEvent(73, getCompleteDiaglogueId(player))
                        else
                            return quest:progressEvent(43, getPendingDialogueId(player), QUEST_ACCEPTED, 1)
                        end
                    end,
                    onTrigger = function(player, npc)
                        -- Check if they're trying to finish LURE OF THE WILDCAT first.
                        if player:getQuestStatus(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.LURE_OF_THE_WILDCAT) == QUEST_ACCEPTED and not utils.mask.getBit(player:getCharVar("WildcatJeuno"), 12) then
                            player:startEvent(10056)
                            return
                        else
                            return quest:progressEvent(43, getPendingDialogueId(player), QUEST_ACCEPTED, 1)
                        end
                    end,
                },
```

**Comment by JinxDojo** [comment]
Thanks, Lynnea1320. Have you submitted this as a request to merge? (I know the alternative would be to have the server administrator stick in that snippet--but I'm guessing the developers would prefer we try to fix it in the 'base' branch?)

**Comment by zach2good** [comment]
@Lynnea1320 would you mind PRing your fix to `base`? thanks!

**Comment by Noikar** [comment]
I'm in the middle of moving house, if you can remind me in 3 days I'd be happy to.

**Comment by Noikar** [comment]
It looks like there are some other changes to some things since I've been absent from the FFXI server community so I will PR my change and someone else may have to refactor it. I don't work on the servers anymore.

**Comment by claywar** [comment]
Bumping this issue.  Path for resolution is to convert Lure of the Wildcat (Jeuno) to Interaction Framework.  Going to be doing this and ensuring equal priority for the conflicting events
