### ISSUE TITLE
shantotto II crashes server

### ISSUE THREAD

**Issue by MaxFFXI** [DerpyProjectGroup/topaz#1196]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

calling shantotto 2 crashes game server.

2 characters have !addspell 1019. shantotto II trust when used crashes the server. 
tested this on another gm character, did !addalltrusts. called shantotto II, crashed server.

**Comment by kaincenteno** [comment]
no issues summoning shantotto ii in xiweb server

**Comment by RAIST5150** [comment]
Can second that she does not crash us on xiweb... was trying her in an Escha zone after synching to retail tonight (Jan 20, 2022)

**Comment by TeoTwawki** [comment]
release mode vs debug mode: she trips a debug break on the binding because she's not a mob and it didn't get updated yet
