### ISSUE TITLE
Shantotto II not generating her own TP

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#1198]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base branch, on xiweb, client /ver reporting  30211225_1 (but it was synched to retail 01/20/22)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Xiweb server was updated today to include recent PR for Shantotto II to add regular attacks and WS gambits, as well as January's client shifts (among other things).  

Client was also synched to retail tonight as well.

Shantotto II attacks consistently for damage, cast spells, etc. as expected--but she was not generating any TP on her own.

As such, unable to comment on WS gambits.  Even after 6 fights, she did not grab enough hate to get smacked around any either... was still sitting at 0 TP.

**Comment by TeoTwawki** [comment]
> [5:15 PM] Strong: Ahh maybe a new issue I noticed, August and Shantotto II do not receive TP using the attack LUA's. Setting mob:addTP() to the weaponskill sets TP at a flat rate with no increase. Any ideas?
[5:18 PM] TeoTwawki: bug
[5:18 PM] TeoTwawki: the bug being that their "mobskill" which is their melee, is eating tp
[5:19 PM] TeoTwawki: I thought we had it in tracker but sicne we still did not fix guessing it was in previous github repo

**Comment by zach2good** [comment]
For future reference (for August, Shantotto II, and Ajido-Marujido etc.), marking the skill as "special" (flag 4) will fix this. This is what I did for Monberaux's skill in this PR: https://github.com/LandSandBoat/server/pull/1200

**Comment by TeoTwawki** [comment]
@zach2good that field was deprecated 6 years ago and should not be used. Melee specials belong in an entirely separate skill list from regular skills and the core needs and adjustment.

**Comment by TeoTwawki** [comment]
> ~~enum SKILLFLAG
{
    SKILLFLAG_NONE           = 0x000,
    SKILLFLAG_TWO_HOUR       = 0x002, // Special skill (ranged attack / call beast)
    SKILLFLAG_SPECIAL        = 0x004,
    SKILLFLAG_HIT_ALL        = 0x008,
    SKILLFLAG_REPLACE_ATTACK = 0x010,
    SKILLFLAG_DRAW_IN        = 0x020,
    SKILLFLAG_BLOODPACT_RAGE = 0x040,
    SKILLFLAG_BLOODPACT_WARD = 0x080,
};~~

~~putting this here as a self-reminder to audit and prune/replace the outdated ones, but in this case it should have been 16 (0x10) not 4~~

~~4 was used for poorly named handling of ranged attacks that are faked as a skill.~~

`#2439` makes it so flag 0x04 (`SKILLFLAG_NO_TP_COST`) is now always the right answer.

**Comment by kaincenteno** [comment]
so this can be fixed by flipping the flag to 4 in here?

https://github.com/LandSandBoat/server/blob/bf190a7184a4f655e39571f5cdad5e5dd27dc060/sql/mob_skills.sql#L3573

would be nice to have her WS :D

**Comment by TeoTwawki** [comment]
yes
