### ISSUE TITLE
Missing Items in item_weapon.sql

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1205]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Items ID from 22040 to 22046 are missing in item_weapon.sql (note that for item 22045 and 22045 the name is missing, but the item is valid as it has info on japanese table; which is the login campaign item for this month)

**Comment by TeoTwawki** [comment]
super easy to add, nothing special to them except for h2h weapons[ (h2h use a screwy base delay)](https://github.com/LandSandBoat/server/discussions/735)
```sql
  `itemId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` text,
  `skill` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `subskill` tinyint(2) NOT NULL DEFAULT '0',
  `ilvl_skill` smallint(3) NOT NULL DEFAULT '0',
  `ilvl_parry` smallint(3) NOT NULL DEFAULT '0',
  `ilvl_macc` smallint(3) NOT NULL DEFAULT '0',
  `dmgType` int(10) unsigned NOT NULL DEFAULT '0',
  `hit` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `delay` int(10) NOT NULL DEFAULT '0',
  `dmg` int(10) unsigned NOT NULL DEFAULT '0',
  `unlock_points` smallint(5) NOT NULL DEFAULT '0',
  ```
  all fields explained, right there
```sql
INSERT INTO `item_weapon` VALUES (itemId,name,skill,subskill,ilvl_skill,ilvl_parry,ilvl_macc,dmgType,hit,delay,dmg,unlock_points);
```
explanation of dmgType can be found in the [enum](https://github.com/LandSandBoat/server/blob/base/src/map/entities/battleentity.h#L247) for it, easily searchable.

_However..._ No point unless implementing the whole item including its model in `item_equipment` and any enchants or latent, and I refuse to see any more placeholders go in to get forgotten to the end of time.. 

..or be continually reported that they are wrong. :)

**Comment by kaincenteno** [comment]
> super easy to add, nothing special to them except for h2h weapons[ (h2h use a screwy base delay)](https://github.com/LandSandBoat/server/discussions/735)
> 
> ```sql
>   `itemId` smallint(5) unsigned NOT NULL DEFAULT '0',
>   `name` text,
>   `skill` tinyint(2) unsigned NOT NULL DEFAULT '0',
>   `subskill` tinyint(2) NOT NULL DEFAULT '0',
>   `ilvl_skill` smallint(3) NOT NULL DEFAULT '0',
>   `ilvl_parry` smallint(3) NOT NULL DEFAULT '0',
>   `ilvl_macc` smallint(3) NOT NULL DEFAULT '0',
>   `dmgType` int(10) unsigned NOT NULL DEFAULT '0',
>   `hit` tinyint(1) unsigned NOT NULL DEFAULT '1',
>   `delay` int(10) NOT NULL DEFAULT '0',
>   `dmg` int(10) unsigned NOT NULL DEFAULT '0',
>   `unlock_points` smallint(5) NOT NULL DEFAULT '0',
> ```
> 
> all fields explained, right there
> 
> ```sql
> INSERT INTO `item_weapon` VALUES (itemId,name,skill,subskill,ilvl_skill,ilvl_parry,ilvl_macc,dmgType,hit,delay,dmg,unlock_points);
> ```
> 
> explanation of dmgType can be found in the [enum](https://github.com/LandSandBoat/server/blob/base/src/map/entities/battleentity.h#L247) for it, easily searchable.
> 
> _However..._ No point unless implementing the whole item including its model in `item_equipment` and any enchants or latent, and I refuse to see any more placeholders go in to get forgotten to the end of time..
> 
> ..or be continually reported that they are wrong. :)

does this mean all current items in sql have all the correct models with enchantments or latents? else it would be good to have another issue open like the one for guild shops for an audit

**Comment by TeoTwawki** [comment]
> does this mean all current items in sql have all the correct models with enchantments or latents?

It means I'm putting my foot down on the subject and no longer letting everything in vanadiel look like an onion sword.

>  else it would be good to have another issue open like the one for guild shops for an audit

do feel free to create one and list all the items that are currently wrong.
