### ISSUE TITLE
[Assault] "Leujaoam Cleansing"  runic portal and ancient lockbox present before finishing mission

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1227]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

runic portal and lockbox are already present before defeating all worms. Able to get prize and assault points. but when using portal it will lock the client on a black screen (no server error log or crash)

after letting timer of mission run when on black screen it will prompt message of mission failure and take out of zone, but when speaking with "Rytaal" it will congratulate you telling you have been awarded assault points for completing the mission

**Comment by RAIST5150** [comment]
Wonder if the issue with black screen zone out after cleansing isn't a matter of where the scripts are trying to send us, perhaps even the zone-in routines of the zone files themselves?

Loaded ibar addon, and here are the coordinates reported for me when I am sitting in black screen:

Leujaom Sanctum [474.616, 8.500, 39.058]

I used /shutdown and when logging back in, character selection screen shows me as still in Leujaom, but when I load into the game I am actually under the Mire map here:

Caedarva Mire [474.16, 8.50, 39.058]

![Raist_Under_Mire](https://user-images.githubusercontent.com/73744368/159549909-0db76440-bf9d-4804-aa18-0a1c97758d4f.jpg)

**Comment by RAIST5150** [comment]
Appears to be retaining the coordinates for where you were standing during the rune of release on-trigger event, instead of setting it to (0, 0, 0, ZoneID).

Walked around to the other side if it on the next run, checked my position before clicking it and after the zoning/reloading and they all matched.
