### ISSUE TITLE
My Cure 1 is doing Cure IV.. my ranged attacks are causing me to sing to mobs!

### ISSUE THREAD

**Issue by MaxFFXI** [DerpyProjectGroup/topaz#1243]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

**When attempting to use tier one spells (Im using cure for an example in the screenshots, but this also happens with curing waltz 1) the game will constantly attempt to do a tier higher or more. Most commonly, cure 1 attempts to do Cure IV, even though i am only level 40 and cannot use cure IV on red mage. 

In the last two screenshots, my husband and I are "singing" to this crawler.. when in reality, we did a ranged attack. Not sure what happened there lol**

![img_20220204_221137](https://user-images.githubusercontent.com/97651465/152626852-0eefe5ed-e840-485c-a777-d191a27a5506.jpg)
![img_20220204_221150](https://user-images.githubusercontent.com/97651465/152626853-d324e0ee-135b-4caf-aa44-e97709c4e7ca.jpg)
![img_20220204_221206](https://user-images.githubusercontent.com/97651465/152626854-de248d2f-170f-4172-9eaa-17f32a093ec5.jpg)
![img_20220204_221217](https://user-images.githubusercontent.com/97651465/152626856-5af213a5-ec62-4e1e-86ae-56969313977b.jpg)
![img_20220204_222324](https://user-images.githubusercontent.com/97651465/152627107-7853dda8-b794-40d8-8349-3e98ebb4e4c0.jpg)
![img_20220204_222328](https://user-images.githubusercontent.com/97651465/152627110-9f97e7ab-46bf-41dd-8388-013a4c19293b.jpg)

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/152627623-728b9ada-b468-4a3e-9e1a-8dc32f286e5b.png)
That is 100% from your client, we can't make it put that in

**Comment by TeoTwawki** [comment]
ranged attack animations can get screwed up by errors in style locking, or can be a case of a ranged weapon with incorrect mid

**Comment by MaxFFXI** [comment]
> ![image](https://user-images.githubusercontent.com/6871475/152627623-728b9ada-b468-4a3e-9e1a-8dc32f286e5b.png) That is 100% from your client, we can't make it put that in

i didnt type it, it just happens when i hit cure 1. So is this my windower client is not matching the server?

**Comment by TeoTwawki** [comment]
> > ![image](https://user-images.githubusercontent.com/6871475/152627623-728b9ada-b468-4a3e-9e1a-8dc32f286e5b.png) That is 100% from your client, we can't make it put that in
> 
> i didnt type it, it just happens when i hit cure 1. So is this my windower client is not matching the server?

This is likely some addon in your windower automatically sending that chat command for you. `/ma` is the cast command, takes a spell name and a target as input. That command is saying cast cure 4 on self. You likely have a misconfigured addon seeing "cure" and "me" and is coded to try and automatically cure for you on those keywords.

**Comment by MaxFFXI** [comment]
Thank you, i will check my addons. might be shortcut. 
Also, just checked the ranged attack thing. Style lock was causing it. Tossed my boomerang at a bunny instead of singing to it.

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/152627841-4de0c826-0cec-43aa-ada1-516224876619.png)
