### ISSUE TITLE
Invalid Packet Size For `menu_unity` Packet

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#1253]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

See file here: https://github.com/LandSandBoat/server/blob/base/src/map/packets/menu_unity.cpp#L48

The usage here is incorrect as setting the size directly does not correctly make use of the proper id and size packing. Instead, this causes the packet to be treated as `0x8C * 2` which causes the packet builder to crash from reading beyond the packet buffer limit of 260 bytes.

This should instead be set using the newer `id(..)` and `length(..)`  helpers to correct the problem.

The other sets in the file need to be fixed as well:
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L60
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L76
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L92
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L103
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L115
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L132
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L149

**Comment by zach2good** [comment]
Thanks for the report! If someone else doesn't get to it by then, I'll fix this tomorrow 👍
