### ISSUE TITLE
Automaton Tank/Mage WS DMG is 0. Attachments are also still broken.

### ISSUE THREAD

**Issue by AuroraFlare** [DerpyProjectGroup/topaz#126]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on: EVERYTHING

Sorry to bug you guys again haha! The last fixes did fix the ranged attacks and I apologize for not noticing this issue before.
- Automaton Tank frames WS deals 0 damage
- Automaton all Mage frame WS deals 0 damage
- Automaton Harlequin frames WS deals 0 damage
- Attachments are broken
   o Tried Several Attachments like Strobe/Shock Absorber/Flashbulb/etc with no luck

**Comment by claywar** [comment]
This one's a bit of a mess.  There's a couple of things going on that need to be addressed:
1.  Attachment scripts aren't being cached on server start, and won't be executed
2. Automaton abilities and weaponskills are classified as mob_skills, but do not exist in the abilities table.  They're also not being cached on start, and not being executed.
3. automatonweaponskills are not passing attackInfo to weaponskills.lua functions
4. Potential that the same fix for ranged_attack needs to be applied to physical weaponskills as well
5. Automaton controller is firing off a WS before the lua check is completed.  Animation will execute, but the remaining script will not be.
6. Automaton WS check function requires a specific maneuver, but will attempt to execute a weaponskill that doesn't have the forced maneuver requirement (no cycling or checks based on active maneuvers for a "default" WS

Overall, PUP is a mess right now and needs to be severely refactored.

**Comment by claywar** [comment]
I've tested weaponskills with the linked PR, and all seem to be working at the moment.  There's still some additional issues with burden being a bit too high, especially on summon compared to retail these days, but will need to collect some data to confirm it.

Other abilities should work, since the check to call out to the new functions in lua scripts is handled in `CMobEntity::OnMobSkillFinished`; But still need to do some additional testing for those attachment-based abilities.
