### ISSUE TITLE
CoP 6-4 Airship fight is buggy

### ISSUE THREAD

**Issue by Enedin9000** [DerpyProjectGroup/topaz#1262]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**On my private server, solo:**
- Killing Ultima during the Airship fight doesn't trigger CS, could not complete mission.

**On Supernova server, in a party:**
- At most 1 player gets teleported to the next ship. The others remain behind on the mammets/omega ship.
- Did a !bring players w/o zoning them to get them to the right spot for the next fight (Omega/Ultima).
- Omega/Ultima don't spawn. I spawned them. Killing Omega triggered the next CS. Still only one player got teleported to the next ship.
- Spawned Ultima, but killing him doesn't trigger CS, could not complete mission.

**Comment by TeoTwawki** [comment]
related: #698
(issue erroneously says 6-3, but then speaks of the airship fight)

Keeping this one, the other was closed.

**Comment by RAIST5150** [comment]
Just out of curiosity, did the other players try to examine the door to move on to next ship, or was it only the party leader checking the door?

**Comment by Enedin9000** [comment]
> Just out of curiosity, did the other players try to examine the door to move on to next ship, or was it only the party leader checking the door?

We tried both. Didn't seem to change much either way, cuz Omega didn't spawn.

**Comment by RAIST5150** [comment]
Hasn't been converted to interaction yet, so it is broken out into several scripts... having a little trouble following the flow exactly.

Looks like you HAVE to get the CS for each fight to advance the params for the phase changes (checks the last cs run to determine if the values change, which then triggers the proper move and mob spawns).

Sounds like something is knackering with that somehow.  I ran into this once with the rank missions when I killed things too fast (like AOE'ing down all the orcs/quadav/cardians).  IDK if something like that would have been in play with the mammets fight or not, just something I noticed back when I was doing nation missions last year.

Just something to think about if you were just ripping through the mammets, IDK.  I ran mine solo with trusts on SMN, so I didn't rush through it back when I did mine, but that was a good while ago before a lot of cleanups took place.

**Comment by Enedin9000** [comment]
We cap it at 60 so we killed em slowly. The first Ultima I spawned was killed by a pet so we retried w/o pets but didn't work either.
