### ISSUE TITLE
Not able to change Jobs in Mog House, Selbina, Mog Garden

### ISSUE THREAD

**Issue by ghost** [DerpyProjectGroup/topaz#1274]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Not able to change jobs via Mog House, Selbina, Mog Garden after getting latest commit.  When try to select Job Change on Selbina or Mog Garden Menu does not come up.

While in Mog House getting like to change style when select change job
![Screenshot 2022-02-10 181305](https://user-images.githubusercontent.com/98451272/153512686-2e404873-934f-46b5-b65c-483c6c2f2501.png)

**Comment by claywar** [comment]
You will need to update your client.

**Comment by ghost** [comment]
I did try to update I will retry once again. It might not took.

I am on Ver 30220204_0

I was on that Ver before but I force to update and seem to be working now
