### ISSUE TITLE
Can't see my items in mog house/wardrobe!!

### ISSUE THREAD

**Issue by MaxFFXI** [DerpyProjectGroup/topaz#1275]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

Updated my server/client today. My mog house says i have 53/70 items in it, but i cannot see them! originally i couldnt even see my items. Then i tried unloading any windower addons/plugins, still couldnt see my items. 

Logged onto my ALT just to see if i could replicate these results. as shown below, ALT had same issue. 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
![img_20220210_205719](https://user-images.githubusercontent.com/97651465/153526696-9e11c61f-7408-45a2-8d6e-85dd1b9eb9e9.jpg)
![img_20220210_205732](https://user-images.githubusercontent.com/97651465/153526703-7071a3be-eddb-4dc2-8d36-5d0b36c98ef2.jpg)
![img_20220210_205740](https://user-images.githubusercontent.com/97651465/153526710-241362ac-51e4-40d3-8e22-d6f572ce57ba.jpg)
![img_20220210_210307](https://user-images.githubusercontent.com/97651465/153527070-6f533803-3cd3-48b5-917e-8f1d91735e22.jpg)
![img_20220210_210312](https://user-images.githubusercontent.com/97651465/153527073-c1c8b8f2-17db-4cc4-9062-598240f5fbae.jpg)

**Comment by claywar** [comment]
You will need to update your client.

**Comment by MaxFFXI** [comment]
My client is also updated to version 30220204_0 as my server's config>ver suggests

**Comment by claywar** [comment]
Have you updated your DB as well and ran all migrations?  This issue does not occur for me with latest base branch.

**Comment by MaxFFXI** [comment]
Do i need to run visual studio>rebuild? thats the only thing i didnt do. I do update the database and run migrations.

**Comment by claywar** [comment]
Yes.  I would suggest every time you pull code to rebuild.

**Comment by MaxFFXI** [comment]
Let me try that then. I always miss something >_< sorry about freaking out haha

**Comment by TeoTwawki** [comment]
Friendly reminder never to update your client before your server is updated and always check if a recent commit solved an issue before panicking.  :man_teacher:  which is why we had that checkbox in the template

**Comment by MaxFFXI** [comment]
I had thought I had done everything (just overlooked one thing ; ; sorry) 
^^; still rebuilding just to make sure I did everything correctly.
Thank you for being helpful the both of you

**Comment by MaxFFXI** [comment]
That worked! thank you very much!!

![img_20220210_211903](https://user-images.githubusercontent.com/97651465/153528174-b70f8527-fec0-45ee-903d-92e9819c1b15.jpg)
