### ISSUE TITLE
Fishing disable causes clients to hang indefinitely.

### ISSUE THREAD

**Issue by Noikar** [DerpyProjectGroup/topaz#1289]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

With the current way fishing is disabled, clients attempting to fish will hang until they crash their client or are force-zoned by a GM.

**Comment by TeoTwawki** [comment]
fixed in 626ba580a55a60af1589b72f50134450d2adfb46
