### ISSUE TITLE
Since updating to latest server/client version, some of the options from main.lua are ignored.

### ISSUE THREAD

**Issue by Noikar** [DerpyProjectGroup/topaz#1290]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Grounds Tomes are disabled on my server but spawned; gil reward rate is at 1x despite that it's set to 1.25x; home point teleports are off and that setting is working, so it's not all settings.

**Comment by zach2good** [comment]
Make sure you look at this setting, which defaults to zero:
```
    -- Setting to lock content more accurately to the content you have defined above
    -- This generally results in a more accurate presentation of your selected expansions
    -- as well as a less confusing player experience for things that are disabled (things that are disabled are not loaded)
    -- This feature correlates to the content_tag column in the SQL files
    RESTRICT_CONTENT = 0,
```

**Comment by Noikar** [comment]
```-- Setting to lock content more accurately to the content you have defined above
	-- This generally results in a more accurate presentation of your selected expansions
	-- as well as a less confusing player experience for things that are disabled (things that are disabled are not loaded)
	-- This feature correlates to the content_tag column in the SQL files
	RESTRICT_CONTENT = 1,
```

**Comment by zach2good** [comment]
commit (latest): `eea136f1c5537463923fc74c37b714456541d3fc`

`settings/main.lua`
```
    -- FIELDS OF VALOR/Grounds of Valor settings
    ENABLE_FIELD_MANUALS  = 0, -- Enables Fields of Valor
    ENABLE_GROUNDS_TOMES  = 0, -- Enables Grounds of Valor
    ENABLE_SURVIVAL_GUIDE = 0, -- Enables Survival Guides (Not Implemented)
    REGIME_WAIT           = 0, -- Make people wait till 00:00 game time as in retail. If it's 0, there is no wait time.
    FOV_REWARD_ALLIANCE   = 0, -- Allow Fields of Valor rewards while being a member of an alliance. (default retail behavior: 0)
    GOV_REWARD_ALLIANCE   = 0, -- Allow Grounds of Valor rewards while being a member of an alliance. (default retail behavior: 1)

...

    -- Setting to lock content more accurately to the content you have defined above
    -- This generally results in a more accurate presentation of your selected expansions
    -- as well as a less confusing player experience for things that are disabled (things that are disabled are not loaded)
    -- This feature correlates to the content_tag column in the SQL files
    RESTRICT_CONTENT = 1,
```

`Tavnazian Safehold`
![image](https://user-images.githubusercontent.com/1389729/154060305-9f0eaff8-5b38-4bac-a7a8-8176aef769f5.png)

`Ru'Lude Gardens`
![image](https://user-images.githubusercontent.com/1389729/154060054-435897b7-277d-4f12-bfca-7e18436b79f3.png)

Are you looking at books that don't have their entry in `npc_list.sql` tagged correctly? They _should_ all be

**Comment by zach2good** [comment]
>  gil reward rate is at 1x despite that it's set to 1.25x

Which quests did you test this on?

**Comment by Noikar** [comment]
```
	-- FIELDS OF VALOR/Grounds of Valor settings
	ENABLE_FIELD_MANUALS  = 1, -- Enables Fields of Valor
	ENABLE_GROUNDS_TOMES  = 0, -- Enables Grounds of Valor
	ENABLE_SURVIVAL_GUIDE = 0, -- Enables Survival Guides
	REGIME_WAIT 		  = 1, -- Make people wait till 00:00 game time as in retail. If it's 0, there is no wait time.
	FOV_REWARD_ALLIANCE   = 0, -- Allow Fields of Valor rewards while being a member of an alliance. (default retail behavior: 0)
	GOV_REWARD_ALLIANCE   = 0, -- Allow Grounds of Valor rewards while being a member of an alliance. (default retail behavior: 1)
```
The GM that reported it (trying to get him to comment here so he can be more specific about the stuff he tested) mentioned a Grounds Tome in Ranguemont Pass. All grounds tomes are content_tagged as GROUNDS_TOME

re: the quest, he said
> I noticed the bat wings quest gave the traditional 200 vs the like 250 or so you had on before.

**Comment by zach2good** [comment]
```
    GIL_RATE        = 1.25, -- Multiplies gil earned from quests.  Won't always display in game.
```
![image](https://user-images.githubusercontent.com/1389729/154065191-4466a987-354a-43cf-9834-5710c29a4e75.png)

**Comment by zach2good** [comment]
All fine on our end, if you can reproduce on `base` feel free to re-open

EDIT: main->base
