### ISSUE TITLE
Blind II base potency calc

### ISSUE THREAD

**Issue by ciradan** [DerpyProjectGroup/topaz#1309]
From the blind_ii.lua:
 -- Base power
    -- Min cap: 15 at -80 dINT
    -- Max cap: 90 at 120 dINT
    local basePotency = utils.clamp(math.floor(dINT / 3 * 8 + 45), 15, 90)

The "dINT / 3 * 8" part seems wrong. This would mean the span of 75 potency (from 15 to 90) would be accomplished in a dINT span of not quite 30 dINT. That's way too strong and would always be clamped to 90.

Example using this calc: dINT = 50
                                       50 / 3 * 8 + 45 = 178,333

Pretty sure the '3' and '8' need to be swapped:
                                       50 * 3 / 8 + 45 = 63.7
                 dINT = 120: 120 * 3 / 8 + 45 = 90

**Comment by Xaver-DaRed** [comment]
This was fixed. I cant find my own PR, but I did it.
