### ISSUE TITLE
ID Shifts.. is it scripted?

### ISSUE THREAD

**Issue by hooksta4** [DerpyProjectGroup/topaz#1310]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Fresh pull and noticed that QC was throwing errors - 
        CASKET_BASE            = 17629663,
        ORNATE_DOOR_OFFSET     = 17629689,
        CHAINS_THAT_BIND_US_QM = 17629738,
        TREASURE_COFFER        = 17629739,
        ANTICAN_TAG_QM         = 17629761,

Don't jive with npc_list... 

Do you use a script to do the monthly id shifts? Or is it a manual thing? I can adjust manually if need be. 

Thanks!

**Comment by claywar** [comment]
Its a manual thing for those scripts, which is why I absolutely hate magic numbers.

**Comment by hooksta4** [comment]
ooof, ok - is it a pattern thing usually ? Looks like in this instance ANTICA_TAG_QM in npc.list is 9769 

safe to assume they all shift by 8?

**Comment by claywar** [comment]
You would need to check the npc_list database entries and match.  Those were updated, so its just a matter of aligning.

**Comment by hooksta4** [comment]
Ok so last question then for the offset ones... does the offset start at the first instance of item?

**Comment by claywar** [comment]
Yep, that would be my guess

**Comment by hooksta4** [comment]
/wrist 

how do yall do it every month?

**Comment by claywar** [comment]
![image](https://user-images.githubusercontent.com/81713309/154865421-2ddcd223-3ef3-464e-95f6-ce43aedf2973.png)

**Comment by hooksta4** [comment]
Is anyone currently in the process of doing it? I dont want to duplicate efforts

**Comment by claywar** [comment]
Nope, Quicksand Caves was the only place that had shifts last month, so have at it if you want to fix

**Comment by hooksta4** [comment]
Thanks for the info - will send PR in a few

**Comment by zach2good** [comment]
PR went in, closing this 👍
