### ISSUE TITLE
Verify Dancer Crafted Artifact Cutscenes

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#1337]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
We seem to be using CS 498 for multiple events (have current item, and for the final CS).  Need to verify the events from current implementation.

**Comment by zach2good** [comment]
I have DNC50 on retail with no quests completed, I can probably cap these next week

**Comment by zach2good** [comment]
> #1337

Nice

**Comment by claywar** [comment]
Done as a part of conversion to Interaction Framework
