### ISSUE TITLE
fTP replicating weaponskills missing parameter

### ISSUE THREAD

**Issue by Schaedelschaden** [DerpyProjectGroup/topaz#1357]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://www.bg-wiki.com/ffxi/Category:FTP_Replicating_WS

Investigation into the performance of weapon skills has revealed that fTP replicating weapon skills were not receiving bonuses from equipment like the elemental gorgets/belts for all hits performed. When tracking through the calculateRawWSDmg function in weaponskills.lua the wsParams.multiHitfTP parameter was identified and found to be missing from most fTP replicating weapon skills on the list above.

https://github.com/LandSandBoat/server/blob/11a20c304407f6df3ab126c2d2113ef3a8e55451/scripts/globals/weaponskills.lua#L545-L546

Pull Request #1355 addresses the missing parameter for H2H weapon skills but is missing the remaining weapons.

- [X] Archery - Jishnu's Radiance
- [x] Axe - Decimation
- [x] Axe - Rampage
- [x] Axe - Ruinator 
- [x] Club - Hexa Strike
- [x] Club - Realmrazer
- [x] Dagger - Dancing Edge
- [x] Dagger - Evisceration
- [x] Dagger - Exenterator
- [x] Dagger - Pyrrhic Kleos
- [X] Great Sword - Resolution
- [x] Katana - Blade: Jin
- [x] Katana - Blade: Ku
- [x] Katana - Blade: Shun
- [X] Marksmanship - Last Stand
- [x] Polearm - Stardiver
- [x] Scythe - Entropy
- [x] Sword - Chant du Cygne
- [x] Sword - Requiescat
- [x] Sword - Swift Blade
- [x] Sword - Vorpal Blade

**Comment by Kayanesa** [comment]
Pull Request #1380 should take care of Dagger ws

**Comment by Schaedelschaden** [comment]
Closing Issue with the note that H2H fTP replicating weaponskills are still missing the wsParams.multiHitfTP setting due to #1355.
