### ISSUE TITLE
[dbtool] not working in linux

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#137]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
server/tools$ python3 dbtool.py 
`ERROR: Make sure git.exe is available in your system's PATH environment variable.`

**Comment by zach2good** [comment]
TODO: Replace the preflight PATH check with something like this:
```py
def check_for_git:
    failed = False
    try:
        subprocess.call(["git"], stdout=subprocess.PIPE)
    except:
        failed = True
    return failed
```

**Comment by zach2good** [comment]
Fixed in: https://github.com/LandSandBoat/server/pull/138

**Comment by zach2good** [comment]
I used dbtool this morning and everything was as it should be, closing
