### ISSUE TITLE
Update logic for Mhaura NPC - Ekokoko

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#1385]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Ekokoko has two events; however from testing, it appears that the first message is only displayed once ever (not repeated after zoning, logging out, conquest period, etc).  Need to find a clean method of implementing this without using a forever var.

**Comment by Xaver-DaRed** [comment]
So we need methods for at least 3 different default interaction types:
- Initial one-time-only interactions.
- Cycling default interactions. (normally just 2 different events)
- Important once only, reseted on zoning.

**Comment by claywar** [comment]
Closed by #4240
