### ISSUE TITLE
Cannot currently manipulate ROAMFLAGs via scripting

### ISSUE THREAD

**Issue by Era-Lusiphur** [DerpyProjectGroup/topaz#139]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Any

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
There are some instances where to better emulate retail behavior, the ability to manipulate ROAMFLAGs via scripting would be beneficial. It appears we currently lack this ability. This came up as a sidebar in some talks in regards to improving pathing in some PMs. Was asked to drop an issue as a sort of TODO.

A few quick examples where this may be necessary:
The Mothercrystals BCNM fights for CoP, when a player uses Terroranima https://ffxiclopedia.fandom.com/wiki/The_Mothercrystals
Race Runner from Like the Wind https://ffxiclopedia.fandom.com/wiki/Like_the_Wind

A simple set/delete or add/remove function would probably suffice, I'd imagine. 

ROAMFLAG index is located over here, which helps illuminate some of the things we could do with such a function.
https://github.com/LandSandBoat/server/blob/c62f6bdbe65638f5292d62c9a978456ca12dc5f2/src/map/entities/mobentity.h#L52

**Comment by TeoTwawki** [comment]
There are/were functions bound to specific flags but I always felt that was dumb and it should be one binding says “hey I want these value(s) there in that mask”

I dunno if they still exist at all but screw’em

**Comment by zach2good** [comment]
This was merged in with https://github.com/LandSandBoat/server/pull/143
closing
