### ISSUE TITLE
npcUtil Trade functions do not account for future space available

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#142]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If player inventory is full on trade, a failure will occur if an item is awarded on trade complete.

Example:
Inventory Full, required trade is 5 items, onTrade complete awards one item.

Trade 5, and after trade there should be sufficient space to receive one, but failure is still returned.

**Comment by zach2good** [comment]
That's correct no? I can't trade my ambu currency/items when I have a full inventory, even if the end result should be one less space than I started with. (I think)

**Comment by claywar** [comment]
I don't recall it happening in retail, but definitely a good thing to confirm.

**Comment by TeoTwawki** [comment]
Retail exhibits the same behavior in all cases I have ever encountered - requiring space to exit prior to trade initiation disregarding space freed by the trade
