### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by timelessxi** [DerpyProjectGroup/topaz#1421]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm not sure why, but each time a character zones or logs out HEAP CORRUPTION DETECTED.
It does not seem to effect the player at all, and the game does not crash.
After the HEAP CORRUPTION DETECTED message it just continues as normal.

![Screenshot 2022-03-17 101549](https://user-images.githubusercontent.com/64764901/158834629-0174e4f1-f1ff-4746-83ef-243d5c61f911.jpg)

**Comment by zach2good** [comment]
Good timing, we're talking about this internally and github was down when I tried to open this same issue :D

**Comment by RAIST5150** [comment]
Running out of buffers?

**Comment by claywar** [comment]
Fixed in #1425 , Merit-related issue
