### ISSUE TITLE
CoP PM 1-2 Promyvion Spire boss fight 

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#1433]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I have found then when running through CoP, PM 1-2 It allows you to record your data in the large apparatus an proceed onwards in promyvion holla.  I cleared this zone fine and had the appropriate CS's. However the problem was within the other two promyvions dem and mea. I was able to enter each zone and proceed through each level without issues but once i entered the spire of each respective promyvion i was unable to proceed into the boss fights. 

I did a bit of looking around and standard for the game was suppose to be promyvion dem first then the other two as noted in https://ffxiclopedia.fandom.com/wiki/Below_the_Arks 
"Promy-Dem should be your first stop, the others will not let you in as a 1st entry (Mandatory)."
I am however skeptical since it was the only source that had this note and it has been a very long time for me since i ran this mission.
I even went back to promyvion holla just to be certain i didn't have to erase my memory or anything else.   
I also tried rebooting the server as well and that didn't help either.

**Comment by claywar** [comment]
After recent changes, you should not be able to enter a promyvion that you have not completed without sealing memories (be it large apparatus or leaving and using a shattered telepoint).  If you are using GM commands, then this is expected, as you would be bypassing the required checks.  Outside of that, perhaps it was a character that existed prior to the recent commits?

Also, Promyvion can be completed in any order (Dem is not required for first stop)

**Comment by Aeisu** [comment]
I have been running with the database for about two weeks now so i doubt it would be that. I didn't have the gm flag on for holla at all and i never exited unexpectedly either they were all start to finish aside from the bosses in mea and dem that i couldn't enter into. 

I also checked the mission log and somehow it bumped me into the next mission "An Invitation West" as well

**Comment by claywar** [comment]
Oh, then that's easy.  Sealing memories didn't exist two weeks ago.  Implemented in #1404

**Comment by Aeisu** [comment]
I think I may  have bungled something up as well I pushed through one of the bosses as a gm afterwards and it threw me forward into the next mission. so i guess the lesson i need to take away from this is to update m ore frequently (everyday) >.<
