### ISSUE TITLE
Dynamic Entities not interactable if using <space> in the name parameter.

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#1443]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
As title states, creating a dynamic entity with a <space> in the name deems the NPC non-interactable.
_ (underscore) does not appear to be valid either.

**Comment by zach2good** [comment]
Fixed in: #1447
