### ISSUE TITLE
[NPC] Mithra's displaying underscore in their name [base 0b0d3a5]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1448]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

only seen with mithra's when visiting windy today

![mithra1](https://user-images.githubusercontent.com/26943220/159604003-9dba8a6c-e7c1-463b-b4e6-33d9cd0c37c2.png)
![mithra2](https://user-images.githubusercontent.com/26943220/159604006-49c24ea1-74ac-4713-8835-2d39407d65af.png)

**Comment by Xaver-DaRed** [comment]
Probably related: PR #1447
