### ISSUE TITLE
[Transport] Underwater Manaclipper in Bibiki Bay Purgonorgo Isle [base 0b0d3a5]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1450]
![boat](https://user-images.githubusercontent.com/26943220/159611845-099326ed-3a2b-4305-9de1-9a71b19b7208.png)

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

~~boat is not only underwater but I believe it should be rotated 180 degrees~~

**Comment by TeoTwawki** [comment]
all hands abandon ship! we're sinking! 

land sand boats are so much safer, no risk of taking on water.

**Comment by Gradius2** [comment]
It's a very OLD issue/bug.  It affects every NPC on CSes as well.  They walk like zombies on stairs.  I'm pretty sure the bug is from there.
