### ISSUE TITLE
Navmesh - Boat Ride : Agro into CargoHold / Mobs path to Pilot's raised area

### ISSUE THREAD

**Issue by Kalifriki** [DerpyProjectGroup/topaz#1470]
![Bug_Boat_Ver](https://user-images.githubusercontent.com/46100825/160272106-6d505b38-61ed-4841-a795-79e1b616fbef.png)

- [X] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [X] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Navmesh for boat rides (all: Selbina to Mhuara; Mhuara to Whitegate, Whitegate to Nashamu): mobs seem to ignore traditional pathing and are capable of agro into the cargo hold as well as moving into the pilot's perch area.

Behavior has been observed on Dawnbreak & Rebirth.
![Bug_BoatAgro](https://user-images.githubusercontent.com/46100825/160271570-9dd108b0-48dd-4ed0-8eea-be6d1df4b02d.png)

**Comment by claywar** [comment]
It might be a good idea to raise this issue on the navmesh repo here https://github.com/LandSandBoat/xiNavmeshes as well

**Comment by zach2good** [comment]
I've done a little research:

To determine aggro and line of sight stuff, we use `raycasts`, this is a regular raycast:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1389729/160285180-45b996fc-0873-4b1f-b132-30bcfe085be4.png">

Bad raycast:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1389729/160285274-c44c7348-cc96-488b-819c-f13acb37777c.png">

(Note, that raycasts on our navmeshes aren't in 3D space, they're projected along the flat plane of the navmesh)

The navmesh is split up between multiple `regions`. Presumably, a raycast is meant to continue to work between regions (which is fine).

Apart from in this case, where there are regions that shouldn't be connected, being connected:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1389729/160285396-53784f1c-e634-4f09-a7ac-cd6a6f65eb53.png">

Kind of hard to see here, but the start and end markers are on different levels, and there is a white line (success) going between them. There are certain combinations of regions that lead to this, maybe 20% of my attempts. The others act as normal

**Comment by zach2good** [comment]
Better picture:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1389729/160285841-91f1cee5-6c23-4512-9e6b-da0cf0ffb37e.png">

**Comment by zach2good** [comment]
I've spoken about raycasting before, and how un-intuitive it is:

https://docs.unrealengine.com/4.27/en-US/API/Runtime/Navmesh/Detour/dtNavMeshQuery/raycast/

```
Casts a 'walkability' ray along the surface of the navigation mesh from the start position toward the end position.

This method is meant to be used for quick, short distance checks.

If the path array is too small to hold the result, it will be filled as far as possible from the start postion toward the end position.
```

```
Use Case Restriction

The raycast ignores the y-value of the end position. (2D check.) This places significant limits on how it can be used. For example:

Consider a scene where there is a main floor with a second floor balcony that hangs over the main floor. So the first floor mesh extends below the balcony mesh. The start position is somewhere on the first floor. The end position is on the balcony.

The raycast will search toward the end position along the first floor mesh. If it reaches the end position's xz-coordinates it will indicate FLT_MAX (no wall hit), meaning it reached the end position. This is one example of why this method is meant for short distance checks.
```

**Comment by zach2good** [comment]
I think one option we can have as a temporary measure, is this:
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/932810-how-query-different-elevations-using-navmesh-generated-detour-recast.html

If vertical difference is under 4.5 yalms or so, accept the result. This is what a lot of servers do for problem areas.
If the vertical distance is larger than 4.5, but smaller than 8, use the above method to query and see if we're trying to jump between floors, and act accordingly.
If the distance is larger than 8, discard, its very likely to be invalid.

**Comment by zach2good** [comment]
I'm not super jazzed about marking zones, areas or mobs as problem areas and having exceptions for them

**Comment by zach2good** [comment]
Changes merged. You mentioned that you knew of a bunch of problem areas where this sort of thing was as problem, if they still are; please report back and I'll take another look or fine-tune the thresholds for the new code 👍
