### ISSUE TITLE
[chore] BOM Detector

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#1491]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

We need a script that eliminated the constantly-switching byte order mark, and it needs to be hooked up to CI. We also need instructions for how to run a script that fixes it.

https://stackoverflow.com/questions/65841649/detect-byte-order-mark-bom-in-python

**Comment by TeoTwawki** [comment]
note: eastern (Japanese especially) versions of Visual studio choke if the BOM is missing, causes it to think src files are in invalid format until manually told to use utf-8 (and sometime even then it had tried to auto adjust some text already).

Other tools/ides/editors often automatic add or remove the BOM, so its a pain in the rear end.

**Comment by Kayanesa** [comment]
I can confirm that something also chock if you use Unicode Japanese I need to take it off each time I want to make a build.
