### ISSUE TITLE
Navmeshes Repository

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#15]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Topaz. Probably all, by extension

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
2 different sets of Navmeshes exist.

https://github.com/DerpyProjectGroup/xiNavmeshes - Used in DSP
https://github.com/topaz-next/xiNavmeshes - Used in Topaz and Topaz-Next

After the Job Points merge, we seem to be using 2...

![imagen](https://user-images.githubusercontent.com/60053999/115198593-85aa6a80-a0f2-11eb-98d0-8ea921484a37.png)

One is the old DSP navmeshes. The other points to an unknown location.

**Comment by TeoTwawki** [comment]
Fixed by #16 

Happened due to someone renaming it along the way, and the derpy repo having been a fork of dsp from pre-topaz which has also been corrected now.
