### ISSUE TITLE
Docker container needlessly exposes too much

### ISSUE THREAD

**Issue by teschnei** [DerpyProjectGroup/topaz#1509]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

I tried to downplay this in the title, but this is a really serious security issue.  The db container exposes the default db port, with root, and the default root password of "root".  Anyone using this (in the default configuration) will absolutely get their DB ransomwared in a week of it being up.
I know you guys "don't officially support" the Dockerfile, but this is a) a somewhat simple change, and b) absolutely cannot stay the default.  I'm embarassed that this even happened to something I set up.

The game server already overrides the mysql config with the hostname of "db", so as far as I know, there is no reason to expose the db port in the docker-compose file.  I concede that it's possible the db admin portal needs it (or, well, isn't configured to use the right hostname, and maybe this was a workaround?), but I don't use that so I don't know how it connects to the db.

I don't mind making a pull request for this, but it really is just deleting two lines from docker-compose.  And I can't really test the admin portal.

**Comment by m241dan** [comment]
You'll still want to do an expose on it though ya? 
```yaml
expose:
 - "3306"
```
So that containers that are part of the network can still access it.
https://docs.docker.com/compose/compose-file/compose-file-v3/#expose

**Comment by teschnei** [comment]
You don't need any expose line for inter-container networking.  The
hostname of "db" works without it.

**Comment by m241dan** [comment]
Do you know the point of "expose" then if they all have access to each others ports anyway?

**Comment by teschnei** [comment]
Expose is for allowing network traffic from outside of the containers to
connect.  For example, you expose the game/lobby servers ports so outside
connections to the host machine get forwarded to the container.

**Comment by m241dan** [comment]
That's what port mapping does. But "expose" for docker-compose is different: https://docs.docker.com/compose/compose-file/compose-file-v3/#expose.

**Comment by teschnei** [comment]
Ah, I see what's going on, I got a bit mixed up while trying to reply with email while raiding...

According to various SO posts, expose (in docker compose) doesn't actually do anything programmatically, and is just "documentation".  It'll still have the port open on the docker network.  So it can be added if desired, but it doesn't seem to be required.  I've observed no issues with no expose line in the docker-compose.

**Comment by zach2good** [comment]
Is it acceptable to leave the admin panel also 'port'ed on 8080? That feels like only a single indirection away from having 3306 visible

**Comment by zach2good** [comment]
(does anyone use the admin panel?)

**Comment by m241dan** [comment]
> Ah, I see what's going on, I got a bit mixed up while trying to reply with email while raiding...
> 
> According to various SO posts, expose (in docker compose) doesn't actually do anything programmatically, and is just "documentation". It'll still have the port open on the docker network. So it can be added if desired, but it doesn't seem to be required. I've observed no issues with no expose line in the docker-compose.

Ah, understood. Thanks!

**Comment by teschnei** [comment]
It should be fine if it requires logging in (and setting a non-default
password before being able to log in).  It depends on the use case of the
admin panel, I don't know anything about it unfortunately.

**Comment by zach2good** [comment]
Maybe not the ideal outcome for docker users, but since none of the Core team uses docker and can properly support it, we've opted to remove it. Sorry :(
