### ISSUE TITLE
Bastok Rank7-1 Cid Bug

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#152]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
![image](https://user-images.githubusercontent.com/61591648/118816526-d3c6af80-b8e4-11eb-9ff7-04d026214287.png)

**Comment by mrhappyasthma** [comment]
Just skimming the code, I believe it's as simple as a find/replace of `currentMission` with `bastokMission`, which holds `local bastokMission = player:getCurrentMission(BASTOK)`.

**Comment by mrhappyasthma** [comment]
This rename was introduced in https://github.com/LandSandBoat/server/commit/bbb9b9615c3cbd82ae6bfa5d820a9cfb5cb0902f. As of that commit, it was correct.

Then there was a bad merge conflict in https://github.com/LandSandBoat/server/commit/58003c45743854fa2110c6696c47f12f1612acb0, which brought back the old naming and wasn't caught.
