### ISSUE TITLE
Trusts that would typically Dual Wield, or have two H2H attacks, only have one atttack at standard delay.

### ISSUE THREAD

**Issue by Lexaraj** [DerpyProjectGroup/topaz#1521]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

Any Trust that dual wields or has hand to hand attacks only performs a single attack per round and does not perform the left hand attack as normal. Changing the cmbSkill to match that of a dual wielding mob (Orcish Grappler) in the mobpool did not fix.

**Comment by TeoTwawki** [comment]
From discord convo, so information is not lost later:
> [10:55 PM] TeoTwawki: so to me it looks like trustutils.cpp needs that column added in its query here: 
https://github.com/LandSandBoat/server/blob/0c8eaccac20642c3f924ba9437cf74ab9f52b615/src/map/utils/trustutils.cpp#L153
[11:00 PM] TeoTwawki: mobs have theirs happening in zone init: https://github.com/LandSandBoat/server/blob/716e0bff5fe08d9f83ad818e0dce76a674502527/src/map/utils/zoneutils.cpp#L352
