### ISSUE TITLE
Item Mods incorrect for 2 items

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#1548]
I have noticed while inputting my own data for item mods that there were a few entries that were not consistent with the normal mod numbers
#1 Item 23403 has a mod number of 570 which should be 840 for Weaponskill Damage
#2 item 23611 also has a mod of 570 which should be 840 for Weaponskill Damage

I went through the whole table to find any other matching entries and found no others

**Comment by TeoTwawki** [comment]
Template exists for a reason. Please don't go deleting it out like that.

```
<!-- remove space and place 'x' mark between square [] brackets or click the checkbox after saving to affirm: -->
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
```


Now some more info to help with the issue solving:

And its 23402 (Vitiation chapeau +3 ) for that 1st one.

(and 23611 being Mochizuki hakama +3 for the 2nd)

I don't recall why 570 was not used for one of the "all ws" version mods. I think its actually the 1st ws? and all others +1 from it. 840 is all hits, 841 1st hit only. Both are all ws. If I am wrong about 570 being 1st ws, no reason it could not be refactored to have 1 less ID in use by using 2 instead of 3 with teh base ID being one of the "all ws" ones.

```cpp
// Weaponskill %damage modifiers
// The following modifier should not ever be set, but %damage modifiers to weaponskills use the next 255 IDs (this modifier + the WSID)
// For example, +10% damage to Chant du Cygne would be ID 570 + 225 (795)
WEAPONSKILL_DAMAGE_BASE = 570,

ALL_WSDMG_ALL_HITS = 840, // Generic (all Weaponskills) damage, on all hits.
// Per https://www.bg-wiki.com/bg/Weapon_Skill_Damage we need all 3..
ALL_WSDMG_FIRST_HIT = 841, // Generic (all Weaponskills) damage, first hit only.
```
the all 3 comment refers to each ws having its own mod as well iirc. its been awhile since I added those mods.

> This statistic has been inconsistently implemented, but it is always a straight damage multiplier. Most sources only apply to the first swing of the weapon skill, including the additional magic effect for hybrid weapon skills, or applied to all of a magic weapon skill. However, some sources apply to all swings of the weapon skill (like [Magian Trials](https://www.bg-wiki.com/ffxi/Magian_Trials) Weapon Skill Damage +n% weapons).
Even more confusingly, some sources of this that only apply to the first hit of Weapon Skills actually apply to both hits of some Weapon Skills, like [Sturmwind](https://www.bg-wiki.com/ffxi/Sturmwind) and [Atonement](https://www.bg-wiki.com/ffxi/Atonement).


related: https://github.com/LandSandBoat/server/blob/2dbae3a1d7e3de544670f35051620660d5f9205f/scripts/globals/abilities/pets/attachments/flame_holder.lua#L41

looks like pup attachment also using bad mod ID?

**Comment by Aeisu** [comment]
most of the gear i see input into the item_mod.sql file has the 841 modifier i do see a few more entries which are specific gear pieces like head, body, hands, legs, feet that are on the 840 modifier as well. 
So should these be all put to the 841 mod for first hit only since they don't fall into the specific weaponskill or special weapon category? 
where as the weapons that are all wsd% should be on the 840 it seems and there are only 4 specific entries for that is seems.

Odd entries for 840 I see so far are 
33091 INSERT INTO `item_mods` VALUES (23682,840,10);    -- Lanun Bottes +3: Weapon skill damage +10%
34111 INSERT INTO `item_mods` VALUES (25555,840,6);     -- Ratri Sallet: Weapon skill damage +6%
34128 INSERT INTO `item_mods` VALUES (25556,840,8);     -- Ratri Sallet +1: Weapon skill damage +8%

the only entries that seem legitimate for 840 so far based on the above criteria are 
28213 INSERT INTO `item_mods` VALUES (22078,840,15);    -- Exalted Staff: Weapon skill damage +15%
28219 INSERT INTO `item_mods` VALUES (22079,840,18);    -- Exalted Staff +1: Weapon skill damage +18%
28425 INSERT INTO `item_mods` VALUES (22135,840,3);     -- Arasy Gun: Weapon skill damage +3%
28430 INSERT INTO `item_mods` VALUES (22136,840,5);     -- Arasy Gun +1: Weapon skill damage +5%

**Comment by WinterSolstice8** [comment]
all hit WSD for all WS on non-augments is currently only used by https://www.bg-wiki.com/ffxi/WS_Damage_Boost in retail

I wonder if those gear mods were made/added when that bug with regular WSD single hit WSD applying to all hits was around for about a month or two.

simple rule for regular gear (not REMA, not augment, not augment on REMA):
`Weapon Skill Damage +/-`: 841,
`"Weaponskill Name" Damage +/-`: 570 + WS ID

Note that as far as I know, nobody has actually tested augments and proved it's actually all hit. There's no source for that, but we do know augs are jank and are sometimes separate multiplicative terms or apply in ways normal items wouldn't (TP bonus offhand/ranged weapon working for main hand)

**Comment by TeoTwawki** [comment]
also fun times ahead making sure the weapons that are supposed to do "when this is in my main hand only" vs armor that boost w/e actually behave as retail.

**Comment by Aeisu** [comment]
I will let you folks handle the hard stuff like number crunching. I'm more of a put the right number in the right field kind of guy so i will stick to compiling the enormous list of item mods i have going so far @.@
once it is done though it is going to be a chore to verify though.
thanks for the help sorting out these particular modifiers though it will make things simpler as i progress through the list.
