### ISSUE TITLE
entity_update.cpp packet causing client crash in certain zones

### ISSUE THREAD

**Issue by m241dan** [DerpyProjectGroup/topaz#1592]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

In certain zones, like Sealion's Den (and various others), a character that has a lot of "stuff" to it will crash the client when it receives a zone_update packet of a certain variety. I cannot explain why, but for example, relatively naked GM characters do not crash (as frequently), but a fully loaded up character will crash like 85% of the time.

There's a lot of weird things going on here, but I have determined the line that, if commented out, will allow you to NEVER crash.

```cpp
if (PEntity->look.size == MODEL_DOOR ||
    PEntity->look.size == MODEL_ELEVATOR ||
    PEntity->look.size == MODEL_SHIP)
{
    maxLength = 12;
}
```

However, I have tried with a completely fresh server setup + database and still seen this crash. Though it is MUCH harder to reproduce with a naked GM character, had to zone 20 times once but I did see it. I'm afraid, however, that I might have imagined it because I have been trying to suss this out for three weeks with MANY different code + database combinations and a TON of `git bisect` + rebuild to find the specific commit that introduced the issue for me. What I found was that it was this commit (https://github.com/LandSandBoat/server/commit/2578c63224a485a6b1b89997ebf6f61b59df0fa1) which introduced the crash. And from that, additional hackery / tom-foolery found that it was something to do with changing the ```maxLength```.

I guess, to me, it's curious that no one else has reported this issue or screamed at Zach about it so I do worry that it is something that I have done.

**Comment by claywar** [comment]
Have you pulled updates recently? After the initial changes from Zach, I also PR'd a fix for transports.

**Comment by m241dan** [comment]
> Have you pulled updates recently? After the initial changes from Zach, I also PR'd a fix for transports.

Yes, I am fully up to date as of like an  hour ago.

**Comment by m241dan** [comment]
> Have you pulled updates recently? After the initial changes from Zach, I also PR'd a fix for transports.

My initial theory was that it was the transport stuff, so I had commented that out, had it back in, etc. I've tried to many combinations.

**Comment by zach2good** [comment]
Can you send me a dump of the crash please?

**Comment by m241dan** [comment]
Is there a guide on how to get dump from client?

**Comment by zach2good** [comment]
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

https://www.windowscentral.com/how-use-procdump-create-dump-files-windows-10
