### ISSUE TITLE
San d'Oria Mission 8-2 aka Lightbringer

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#1595]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [] I have specified what branch this happens on branch: EDITME

Hi,

I tried to do this a lot times, deleted mission, keys, started all over again, same issues. 

The NMs dolls (Nio-Hum and Nio-A) won't pops up no matter what.

I'm getting this:

```
[04/17/22 08:14:03:598][map][error][navmesh] CNavMesh::findRandomPath startRef is invalid (-237.787994, -2.000000, 8.000000) (159) (CNavMesh::findRandomPosition:348)
[04/17/22 08:14:03:598][map][error][error] luautils::onMobDeath: .\scripts/globals/interaction/interaction_lookup.lua:371: attempt to call local 'fallbackHandler' (a nil value)
stack traceback:
        .\scripts/globals/interaction/interaction_lookup.lua:371: in function <.\scripts/globals/interaction/interaction_lookup.lua:367> (luautils::OnMobDeath:3138)

[04/17/22 08:16:09:610][map][error][navmesh] CNavMesh::findRandomPath startRef is invalid (-237.787994, -2.000000, 8.000000) (159) (CNavMesh::findRandomPosition:348)
```
Also the fallback error is from:
```
-- Main handler function that determines which action should be performed
local function onHandler(data, secondLevelKey, thirdLevelKey, args, fallbackHandler, defaultReturn, targetId)
    local playerArg = args.playerArg or 1
    local player = args[playerArg]
    if not player then -- if no player object is present, we can't do anything in the handler system
        return fallbackHandler(unpack(args))
    end
```

Please, check it out.

**Comment by claywar** [comment]
The error you posted has no relevance to popping those NMs.  The following requirements must be met in order to spawn:
```
                        player:getMissionStatus(mission.areaId) == 5 and
                        player:hasKeyItem(xi.ki.PIECE_OF_A_BROKEN_KEY1) and
                        player:hasKeyItem(xi.ki.PIECE_OF_A_BROKEN_KEY2) and
                        player:hasKeyItem(xi.ki.PIECE_OF_A_BROKEN_KEY3) and
                        (not nioA:isSpawned() or nioA:isDead()) and
                        (not nioHum:isSpawned() or nioHum:isDead())
```

**Comment by Gradius2** [comment]
I checked the key items, deleted them, add them, nothing.  Same for the mission, deleted, then added, to see if would fix it.  Nothing.

CRYSTAL_DOWSER (ID 284)
PIECE_OF_A_BROKEN_KEY1 (ID 285)
PIECE_OF_A_BROKEN_KEY2 (ID 286)
PIECE_OF_A_BROKEN_KEY3 (ID 287)

Nation ID: 0
Mission ID: 21

Of course I checked also:
\server\scripts\missions\sandoria\8_2_Lightbringer.lua

**Comment by claywar** [comment]
This would indicate that either your mission status is not equal to 5, or one or both of the mobs is alive.  I would guess your status is not 5.

**Comment by Gradius2** [comment]
How I check that?

And no, the mobs just won't spawn after checking the door.

**Comment by claywar** [comment]
`!checkmissionstatus <playername> 0`

**Comment by Gradius2** [comment]
I'm getting 24.

**Comment by claywar** [comment]
There isn't a single mission that sets a value that high for San d'Oria.  If you have been GM'ing your way through missions (adding/deleting missions), please take heed of the note that mission status is _not_ reset when applying those functions, and must be manually set.

See: !setmissionstatus

**Comment by Gradius2** [comment]
Well, no doubt something is messed with Lightbringer mission.

**Comment by claywar** [comment]
I have doubt, as I have ran this mission multiple times when implementing it.  Please try to reproduce from scratch, ensuring that your mission status is 0 on start.
