### ISSUE TITLE
[Abyssea] lights.lua trying to index a nil value

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1603]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
Error in listener event DEATH: ./scripts/globals/abyssea/lights.lua:569: attempt to index field 'lights' (a nil value)
stack traceback:
        ./scripts/globals/abyssea/lights.lua:569: in function <./scripts/globals/abyssea/lights.lua:564> (triggerListener:62)
```

**Comment by TeoTwawki** [comment]
I think `xi.abyssea.lights.DropLights(` on that line needs to be `xi.abyssea.DropLights(`

```lua
    mob:addListener("DEATH", "ABYSSEA_DEATH_LIGHTS_CHECK", function(mobArg, player)
		local deathType = mobArg:getDeathType()
		if deathType == xi.abyssea.deathType.NONE then
			deathType = xi.abyssea.deathType.PHYSICAL
		end
        xi.abyssea.lights.DropLights(player, mobArg:getName(), deathType, mobArg)

		xi.abyssea.lights.RemoveDeathListeners(mobArg)
    end)
end

xi.abyssea.DropLights = function(killer, mobName, killType, mob)
```
The line below it `xi.abyssea.lights.RemoveDeathListeners(mobArg)` has the same error

###### side note, I kinda dislike the naming there,

**Comment by claywar** [comment]
Its a mistake on my part after renaming that global for simplicity.  Will fix tonight.

**Comment by claywar** [comment]
There's one other issue going on here, and that requires adding two additional items to settings.  Since this can easily be overlooked, I have added a default value to code as well for the lights drop rate

**Comment by claywar** [comment]
I take that back, not assuming default.

@kaincenteno There's two settings that were added in the Abyssea PRs that need to be added to your current scripts/settings/main
