### ISSUE TITLE
[Abyssea] giveNMDrops function attempting to index a nil

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1606]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
```
[info][lua] Error in listener event DEATH: ./scripts/globals/abyssea.lua:502: attempt to index a nil value
stack traceback:
        ./scripts/globals/abyssea.lua:502: in function 'giveNMDrops'
        ./scripts/mixins/abyssea_weakness.lua:48: in function <./scripts/mixins/abyssea_weakness.lua:47> (triggerListener:62)
```

**Comment by claywar** [comment]
Nil check added 24-Apr-23
