### ISSUE TITLE
Avatar job traits

### ISSUE THREAD

**Issue by eraffxi-personal** [DerpyProjectGroup/topaz#1631]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://github.com/LandSandBoat/server/pull/1628

per convo here, avatars need to have jobs assigned to receive appropriate traits.

**Comment by TeoTwawki** [comment]
the jobs are assigned (possibly wrong jobs..), but the code bolt on a jobs traits might be missing from petutils.cpp

**Comment by RAIST5150** [comment]
Looks like the mob_pools.sql has the jobs assigned.

If I read it correctly, looks like the pet entries puts 
Carbuncle as WHM/WAR (3,1) and the 6 celestial elemental avatars as BLM/WAR (4,1).

So those mjob/sjob values may be getting pulled properly by petutils... not sure about the specific job traits for MAB/MDB, auto regen, etc. though.
