### ISSUE TITLE
Recent update to Base causing Compiling errors

### ISSUE THREAD

**Issue by Bandit42** [DerpyProjectGroup/topaz#1677]
- [] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x ] I have specified what branch this happens on branch: EDITME
![FFXIError](https://user-images.githubusercontent.com/35357152/167256558-dab2e8b0-91ec-4369-bf7c-8bf750940c77.jpg)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Got 2 errors on compiling (make -j 8) in the build folder from Base branch. I did another recompile (make -j 8) and still same errors popup
![FFXIError](https://user-images.githubusercontent.com/35357152/167256609-c09e3967-dc75-47b3-9a2c-77f48e70a3e1.jpg)

**Comment by Bandit42** [comment]
didnt mean to do 2 posts. They're both the same thing

**Comment by zach2good** [comment]
What compiler and version is this? We've tested the build with clang 11, gcc 10 and whatever msvc comes with 2022

**Comment by Bandit42** [comment]
> What compiler and version is this? We've tested the build with clang 11, gcc 10 and whatever msvc comes with 2022
gcc 10 but not sure on the others. I will do a apt upgrade since there are updates and see if that fixes it

![xubuntu_version](https://user-images.githubusercontent.com/35357152/167257498-f4a165a3-6530-41bf-b248-d788c0832858.jpg)

**Comment by Bandit42** [comment]
i upgraded to clang 11 and upgraded to gcc 10 and still get same errors. Even did a an upgrade to build-essentials and still get same errors when compiling again. I did notice that apparently my gcc wont switch to 10 for some reason even though i just updated it

**Comment by claywar** [comment]
Could also try updating your WSL2 image to 22.04 which was release not too long ago (unless that's a different machine)

**Comment by Bandit42** [comment]
Im not using wsl2. i use Unraid for my FFXI VM on my server box. VM was created from scratch and then followed landsandboat guide. ill see if a distro upgrade will work

**Comment by Bandit42** [comment]
i upgraded the distro to xubuntu 22.04 and now it compiled just fine. I do get warning message on cmake but does not interfere with that app. I did have to comment out stdout_with_ansisequence on the login.conf and map.conf as they each threw out a warning message. Restarted connect and server and no warnings were produced. was able to login to my server with no issues

**Comment by claywar** [comment]
Odd.  I just tried building on 20.04 as well with no issue, not sure what's going on there.

**Comment by Bandit42** [comment]
idk. wonder why i was having that issue on 20.04. Might have been my compilers but I couldnt upgrade them so I had to upgrade the distro and then the compilers and that seems to have fixed it

**Comment by Gradius2** [comment]
It compile fine on win10 with VS2022.
