### ISSUE TITLE
[MAP] Ashita tparty addon generating fTP error in logs with trusts

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1678]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

didn't know if i should post this here or submit it with ashita but having several people logged in using this addon creates lots of info logs with this.

[05/07/22 16:39:47:110][map][info][lua] fTP error: TP value is not between 1000-3000!  (print:437)

**Comment by WinterSolstice8** [comment]
I think the problem here is that some trusts can use a WS with TP below 1000, and that error message doesn't really apply to them

**Comment by kaincenteno** [comment]
> I think the problem here is that some trusts can use a WS with TP below 1000, and that error message doesn't really apply to them

I thought that too. After disabling tparty the info message disappears. I can try again later to double confirm this though

**Comment by WinterSolstice8** [comment]
I would take a poll on which trusts your players are using. we can either put in special cases for trusts that use WS at any TP or disable the message altogether for trusts
