### ISSUE TITLE
In abyssea player death is teleported to the entrance incorrectly

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#1733]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When the player is active in Abysssea and dies, the player's corpse will be forcibly teleported to the entrance outside Abysssea

**Comment by claywar** [comment]
Most likely this is due to the visitant status being removed incorrectly on death.  While this shouldn't happen without the appropriate flag, it appears in this case that it is.

Note: Tractoring is considered zoning, and will remove the effect.

**Comment by RAIST5150** [comment]
May have a related issue just happen on my account (xiweb).

Bugged out and crashed the server when I interacted with a ??? in Abyssea Vunkerl looking to pop Khalkotaur (#2116 ). While discussing in discord and poking around in github looking into how things stood for the zone, my character got ejected to Jugner (shows me in Jugner on login screen).  Apparently, all the QM's for A-Vunk are still work in progress.

Now every time I try to log in, it goes straight to R0 and crashes xiweb.

**Comment by Dev-Roland** [comment]
> May have a related issue just happen on my account (xiweb).
> 
> Bugged out and crashed the server when I interacted with a ??? in Abyssea Vunkerl looking to pop Khalkotaur (#2116 ). While discussing in discord and poking around in github looking into how things stood for the zone, my character got ejected to Jugner (shows me in Jugner on login screen). Apparently, all the QM's for A-Vunk are still work in progress.
> 
> Now every time I try to log in, it goes straight to R0 and crashes xiweb.

We've found out more and I just wanted to note it here, for future readers.
The exact cause of Raist's char crashing the server on login was that it still had visitant status while loading a non-abyssea zone. Apparently the zone was freaking out at his Abyssea status and down goes the server.
