### ISSUE TITLE
[abyssea] The initial mission cannot trigger follow

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#1734]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Level >=30 and setting is open abys, players can't trigger the abyssea quest when they enter port jeuno, when I use other methods to trigger cs, and add a quest, visit Joachim, can't get the quest cs, can't get stones

**Comment by kaincenteno** [comment]
I can confirm this issue on base commit [a6039e6](https://github.com/LandSandBoat/server/commit/a6039e615e3dbb12f48eaa6ed5b184934b973299)
