### ISSUE TITLE
[Linkshell] Malformed linkshell name [commit 4ebb14e]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1742]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Meant to open this but the couple week or two PCs in xiweb have noticed malformed named

![image](https://user-images.githubusercontent.com/26943220/168661264-a3a68ab1-a1dc-4e2f-8b3c-1eec41056890.png)

![image](https://user-images.githubusercontent.com/26943220/168661335-2cab5082-cecc-406b-b7ea-1548874df077.png)

**Comment by The-Aerec** [comment]
What does the LS name look like in your DB?

**Comment by kaincenteno** [comment]
> What does the LS name look like in your DB?

looks correct on the DB

![image](https://user-images.githubusercontent.com/26943220/169361588-4018d244-257a-4187-86c2-516cc4583a64.png)

**Comment by The-Aerec** [comment]
Did you ensure client version was correct for the user? (Just checking normal boxes)
