### ISSUE TITLE
Regime GoV / FoV broken by Async SQL calls

### ISSUE THREAD

**Issue by m241dan** [DerpyProjectGroup/topaz#1769]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Attempt to finish a page.

## Expected behavior

Page should complete, it does not.

You either need to start caching Char Vars or not use Async calls here (reverting async calls fixed it, but I'll let you choose your poison for the solution.)

**Comment by claywar** [comment]
All Async calls were disabled (along with the thread they were running on).  Closing this issue
