### ISSUE TITLE
[core] Lua hook for addItem does not properly attempt to write signatures to SQL.

### ISSUE THREAD

**Issue by 0phie** [DerpyProjectGroup/topaz#1777]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Attempt to write a signature to an item via the player:addItem({itemid, signature="stringhere"}) command. Currently will receive an error such as the attached when the item is distributed to the player causing the item to not be given to the player. The signature has been tested via print commands in the map server to verify the string is accurate prior to passing to the addItem hook.

It appears there is an issue with the encoding of these strings as in the example a simple "DynaBastok" is trying to be written to a perpetual hourglass for an era dynamis module. This however affects other items like a Genie Weskit which normally can be signed.

![image](https://user-images.githubusercontent.com/84217630/169706167-64c2bf2c-6bd7-4da5-97e2-80c430bdf529.png)

It appears that the signature field is attempting to write incorrect data to the field in SQL, but even with a short name it appears to be grabbing data from elsewhere in memory causing the issue.

## Expected behavior

When using the lua hook player:addItem({itemid, signature="stringhere"}) should result in a map server message containing "stringhere" instead of what appears to be a corrupted signature value. Thus in this specific case an item should be given to the player with the signature line reading in game with <DynaBastok>.

**Comment by WinterSolstice8** [comment]
works as of latest commit on base, tested with `!exec player:addItem({id=18110, signature="test"})`

do you have commit https://github.com/LandSandBoat/server/pull/1761/commits/984440269a80e35ea67c906ea2144a1212925db5?

**Comment by 0phie** [comment]
> works as of latest commit on base, tested with `!exec player:addItem({id=18110, signature="test"})`
> 
> do you have commit [9844402](https://github.com/LandSandBoat/server/commit/984440269a80e35ea67c906ea2144a1212925db5)?

Thanks, apologies about not seeing the commit. I thought our base was updated not too long ago. I will be pushing a fetch to it and if the issue is resolved I will close this out. Thanks a ton!

**Comment by WinterSolstice8** [comment]
No problem. We went through a bout of "cleanup _all_ compiler warnings" and a couple things like that broke.

**Comment by 0phie** [comment]
It worked! Sorry again about not researching the commits fully.

**Comment by TeoTwawki** [comment]
best way to quickly confirm an issue exists on `base` is to just do a separate clean clone in a new folder with a separate db from the one you experience the issue is, and see if the problem exists there or just the server that may somehow be missing commits (proper updates via git pull do not miss commits, so its either behind on updates or "updating" in an abnormal unsupported manner like cherrypicking or copypasta).
