### ISSUE TITLE
[AH] [SQL] Some items and/or equipment are missing auction house category

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1778]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Place any of these items on auction house:
barrier module 
magniplug 
jug of tantalizing broth 
jug of blackwater broth 
aiwon gauntlets |
rager ledelsens +1
gigantes boots +1
megasco earring

try looking for them on the buy auction house
wont be able to find them
## Expected behavior

Item should show on auction house, but doesn't as their `Ah` column is set to `0`

is the `Ah` column populated manually or does it need a polutils export?

**Comment by TeoTwawki** [comment]
manually, look at existing items and you can see which one is daggers vs helmets etc.

I'll add an enum later so that it can be referred to.

**Comment by kaincenteno** [comment]
> manually, look at existing items and you can see which one is daggers vs helmets etc.
> 
> I'll add an enum later so that it can be referred to.

you'll add enum later? what do you mean? (sorry that part got me confused)

**Comment by TeoTwawki** [comment]
as enum is _an enumeration_ https://www.simplilearn.com/tutorials/cpp-tutorial/cpp-enum

Here are ours currently:
https://github.com/LandSandBoat/server/search?q=enum
