### ISSUE TITLE
Simple fix for CoP

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#1784]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

From CoP script: 3_3_The_Road_Forks.lua

There is a wrong pos for Cradle of Rebirth.

The correct one should be: !pos 319 -25 -13 7

**Comment by claywar** [comment]
This is incorrect, from capture DB matches the correct location on retail which is 320.155,-23.280,-15.884
