### ISSUE TITLE
Linux build not loading Lua modules

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#1798]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. define some modules in modules/init.txt
2. ./xi-map

## Expected behavior

 I expect modules to load as defined in modules/init.txt... It appears they are completely bypassed.

![image](https://user-images.githubusercontent.com/65316697/170088288-e3380835-ca91-4883-b317-c849bfa965a7.png)

**Comment by WinterSolstice8** [comment]
Confirmed
