### ISSUE TITLE
 charplugin::AddItem: Item <18566> is not found in a database (CLuaBaseEntity::addItem:

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#1816]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`item_equipment`

## Expected behavior

Alright full disclosure: newbie here. Just been doing basic item data fills and updates for testing so far.
I was attempting to add a missing item: Crepuscular Scythe . 

INSERT INTO `item_equipment` VALUES (18566, 'crepuscular_scythe',99,119,128,526,0,0,1,0,0);
INSERT INTO `item_weapon` VALUES (18566, 'crepuscular_scythe',7,0,248,248,248,2,1,513,360,0);
INSERT INTO `item_mods` VALUES (18566,431,5);
INSERT INTO `item_mods` VALUES (18566,499,12);  
INSERT INTO `item_mods` VALUES (18566,501,10);  
INSERT INTO `item_mods` VALUES (18566,951,19);   
INSERT INTO `item_mods` VALUES (18566,998,50); 
[items.lua] = CREPUSCULAR_SCYTHE              = 18566,

With all the data in it gives the title error when using !additem, what location am I missing adding info to for this to work correctly?  I didn't see anything related to item data in the lua_baseentity file. The MId is the same as twilight scythe, nothing new there.

**Comment by zach2good** [comment]
You're close, you'll also need to make an entry in `item_basic`

**Comment by Xaver-DaRed** [comment]
you are missing adding it to item_basic table

**Comment by Hinekri** [comment]
Thanks so much, working now!
