### ISSUE TITLE
AOE JA's don't generate enmity in PT

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#182]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: current

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
If you use an AOE JA, such a rampart or warcry solo, you get the expected CE/VE enmity listed in the sql database for abiities.

However, if you are in a party and it hits another member, you get 0 CE/VE

Bonus: AoE buff JA's also don't show up in chat log(no msg set).
I'm using rampart everytime after "!reset".
![image](https://user-images.githubusercontent.com/58101246/119276016-68335980-bbe6-11eb-9e39-915be3e67b68.png)

**Comment by WinterSolstice8** [comment]
![image](https://user-images.githubusercontent.com/60417494/178171855-d3f54791-24e4-4d3f-8c1e-a988a73c804e.png)
This seems to have been fixed since the original report.
