### ISSUE TITLE
home points lost.

### ISSUE THREAD

**Issue by STUDIOEBANS** [DerpyProjectGroup/topaz#1828]
![スクリーンショット 2022-05-29 213919](https://user-images.githubusercontent.com/102587411/170868903-97ef190c-6fb7-4f31-9856-7f4e93025875.png)

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Expected behavior

I don't know if this has anything to do with this log, but when I check my home point, the home point I have been to is gone, and when I move to another location, the newly recorded point is also gone.

**Comment by claywar** [comment]
You have pulled latest.  Please ensure that you have run dbtool to apply required migrations.

**Comment by STUDIOEBANS** [comment]
Thank you very much.

**Comment by STUDIOEBANS** [comment]
Understood, sir.
