### ISSUE TITLE
Not able to receive guild points

### ISSUE THREAD

**Issue by Metal36** [DerpyProjectGroup/topaz#1846]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Attempt to trade requested items for Guild Points.

## Expected behavior

1. Expected to trade requested items, get points.

## Actual behavior

1. Upon trading requested items, nothing happens.
2. When asking Guild NPC about current limits, receive message "You are not eligible to receive guild points at this time". This is the same across several characters and guilds. Same characters were able to get points in the same guilds prior to May 14th, when xiweb server was updated.

**Comment by m241dan** [comment]
Oh, I forgot I had fixed this and didn't share it this weekend.

This has to do with the "remove useless casts" changes.
