### ISSUE TITLE
Temple Cyclas gives Geomancy and Handbell skill.

### ISSUE THREAD

**Issue by ZamAnimal** [DerpyProjectGroup/topaz#1855]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Expected behavior
The Temple Cyclas is the MNK arifact body piece. It currently gives Geomancy and Handbell skill.

**Comment by TeoTwawki** [comment]
We have in the past had some ID overlaps, checking our current files this is not the case now. The server you are playing on may possibly have some outdated files or mishandled an edit conflict and should compare with our current fileset.

itenm_mods.sql : 
```sql
INSERT INTO `item_mods` VALUES (12639,1,41);
INSERT INTO `item_mods` VALUES (12639,2,20);
INSERT INTO `item_mods` VALUES (12639,10,3);
INSERT INTO `item_mods` VALUES (12639,25,5);
INSERT INTO `item_mods` VALUES (12639,123,10); -- Enhances Chakra Effect - Increases VIT mult by 1.0
INSERT INTO `item_mods` VALUES (12639,124,1);  -- Chakra removes Paralysis
```

modifier.h :
```cpp
    DEF        = 1, // Target's Defense
    HP         = 2, // Target's HP

    VIT = 10, // Vitality

    ACC  = 25, // Accuracy

    WIND      = 121,  // Wind Magic Skill
    BLUE      = 122,  // Blue Magic Skill
    GEOMANCY  = 1026, // Geomancy Magic Skill
    HANDBELL  = 1027, // Handbell Magic SKill

    CHAKRA_MULT         = 123,  // Chakra multiplier increase (from gear)
    CHAKRA_REMOVAL      = 124,  // Extra statuses removed by Chakra
```

status.lua :
```lua
    WIND                            = 121,
    BLUE                            = 122,
    GEOMANCY_SKILL                  = 1026,
    HANDBELL_SKILL                  = 1027,
    CHAKRA_MULT                     = 123, -- Chakra multiplier increase
    CHAKRA_REMOVAL                  = 124, -- Extra statuses removed by Chakra
```

Stats the same across all 3 files.

**Comment by TeoTwawki** [comment]
The secret is merits and skill ID handling, apparently.
