### ISSUE TITLE
Commitment Status Effect Fails to apply.

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#1856]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base/scripts/globals/effects`

## Steps to reproduce
 Status Effect for Commitment provides no bonus.

## Expected behavior

**Comment by claywar** [comment]
If you're looking for Experience points bonus, that would be Dedication effect and not Commitment (Commitment is capacity points, and most likely not implemented at this time)

**Comment by Hinekri** [comment]
Sorry I kinda double dipped and edited to separate issues, just looking for the CP bonus here. Thanks for the update.

**Comment by RAIST5150** [comment]
Commitment has not been worked out in base/xiweb yet.  We can get rings and all, but cannot activate them.

IDK if anyone else downstream has a method working yet, but for now I think the only confirmed bonuses we have going atm in base/xiweb are the main nations rank 10 (10% each), job point gifts, the odd RoE rewards, and CP chains.
