### ISSUE TITLE
CoP 7_1 Cutscene Loop.

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#1860]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`scripts/missions/cop`

## Steps to reproduce

On mission 7-1 player can progress from step 1 to final CS at gate and the mission does not complete. CSs are then repeatable from step 1 of 7-1.

## Expected behavior

Final cutscene should progress to mission 7-2.

**Comment by CatsEyeXI** [comment]
Confirmed

**Comment by claywar** [comment]
There are 3 required cutscenes that are required after zoning into Lufaise.  Can you please provide exactly what steps you took?

**Comment by Hinekri** [comment]
After the cutscene in [Lufaise Meadows]
[Tavnazian Safehold] zone in for a cutscene.
Zone into [Sealion's Den] for another cutscene.
Then to [Phomiuna Aqueducts] on the bottom floor for cutscene with Louverance.
Check the Walnut Door at (K-7) on the top floor of [Tavnazian Safehold] for a cutscene with Ulmia.  

After Ulmia all of them can be repeated except the one that give the Ducal ring.

**Comment by claywar** [comment]
I see now, thanks for the update, and not sure where the code to set the appropriate bits disappeared to from when I was testing.  Will have a fix out soon
