### ISSUE TITLE
[x86-release] & [x64-release] builds seems to be broken

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#1868]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Try to build on x86-release or x64-release
![imagen](https://user-images.githubusercontent.com/60053999/171966935-6ab5c7da-58d0-4cae-bf0e-a64486fe81a3.png)

## Expected behavior

<.<

**Comment by Gradius2** [comment]
I could build perfectly until days ago.  It only started to happen from N days from now (from last update).

I won't build every single time, nor update, so I don't know exactly which update it started to happen, but isn't older than a week.

I run FFXI just as a little hobby of mine, this is why I don't update/compile everyday.

And stop falsely accusing people, w/o know it:
https://github.com/LandSandBoat/server/pull/1811#issuecomment-1146450551

**Comment by Xaver-DaRed** [comment]
<.< Unlike you, I know EXACTLY when this broke and why. You've been told all day what the issue was. AKA, there were changes in core, not only lua, when changing the targetable flag. SO no. it isnt false. you didnt build up to now. Not properly, as I stated, i didnt imply malice.
Had you built properly, it would have failed. Thats a fact.
Those errors you got were becouse, for some reason, you only got the lua changes aplied, but not the changes to core, witch require a compile.

**Comment by WinterSolstice8** [comment]
We're working on it, a recent commit fixed a lot of thread issues when trying to exit, but it seems that specifically _only_ release mode (x64/x86) broke on windows. For now, you can build in debug mode. It will be fixed shortly.

**Comment by Gradius2** [comment]
@[WinterSolstice8](https://github.com/WinterSolstice8)

Fixed.  Thanks.  Working perfectly again.
