### ISSUE TITLE
Value Missing in Action Packet

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1877]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Steps to reproduce: (Omicron server)

METHOD 1
1. Load game in Windower with the Battlemod addon loaded
2. Summon trusts (I used Halver/Ayame/Valaineral/Excenmille, though this has happened when I had no trusts out)
3. Fight enemies and this error should trigger roughly once every 3-5 minutes, often within 1~3 seconds of engaging.

METHOD 2
1. Load game in Windower with the Battlemod addon loaded
2. Accumulate 1000 TP
3. Engage an enemy from 6~25 yalms
4. Attempt a WS from out of range
5. This triggers two chat messages. 1) WS attempt. 2) Mob out of range. Either one could be the trigger
6. That should trigger the error in the console

NOTE: The error printed in the console is "_Lua runtime error: battlemod/parse_action_packet.lua:709: attempt to index field '?' (a nil value)_"
Line 709: _local msg_ID = act.targets[1].actions[1].message_

## Expected behavior

Apparently a portion of the action packet is expected to be defined that is undefined in LSB.

**Comment by zach2good** [comment]
Interesting! Thanks for the report, I'll take a look at this when I'm back from holiday if someone else doesn't get to it first

**Comment by Marco889** [comment]
It looks like we may be sending an 0x28 action packet without an action embedded in it.

**Comment by Dev-Roland** [comment]
I updated the issue with a second method. I've isolated out a single action that consistently triggers the error.
I'm not sure if it was the 2nd method that triggered the error all along or if there is more than one trigger. I have a feeling it was the former.

**Comment by WinterSolstice8** [comment]
I was looking at the code earlier, and I did speculate that's possible. Trusts can/do attempt WS when out of range, _particularly_ Valaineral. 

There's a code block to generate an action packet and then populates the targets based on if they are _in range_ or not. I am guessing this means that we need to populate an action with an "out of range" message, cancel the action, or otherwise. Thanks for the repro steps!

**Comment by zach2good** [comment]
Related issue: https://github.com/LandSandBoat/server/issues/2019

**Comment by WinterSolstice8** [comment]
I'll be working on this
