### ISSUE TITLE
Windower Crash Upon Self-Busting COR Rolls

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1879]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Load the game using Windower
2. Have/set main job as COR
3. Use a roll
4. Double-up until it busts
5. The Windower client will freeze and crash-to-desktop before the busting double-up JA begins its animation

NOTE: If you have an alt nearby, also on windower, it does not crash and you can see the double-up and bust animations, indicating that windower can play the animation as long as it's not performed by the current player.
NOTE: This occurs without any addons loaded, potentially simplifying the potential cause to a more core-level issue

## Expected behavior

The current player's roll busts and plays the JA/bust animations without crashing the current player's Windower client

**Comment by Dev-Roland** [comment]
What is the intent on issues like this, where LSB triggers an error in an external tool, such as Windower, that retail does not trigger?
Given how almost everything-LSB already works in Windower, it seems that you have been very accurate in keeping LSB's architecture compatible with the existing tools. I hope this bust issue can be fixed. Thanks!

**Comment by zach2good** [comment]
We 100% want to make sure we're presenting the correct information and packets to Ashita and Windower, so that we're as compatible with them as possible. We tend not to get reports like this (people just sit on them and complain about us being wrong >.>), so thank for reporting!

**Comment by jeffnavy14** [comment]
They are on my server Omicron, trying to crash it now.

**Comment by Dev-Roland** [comment]
Any chance this could be fixed soon since it's a fatal client error?

**Comment by zach2good** [comment]
Does anyone know what happens on Ashita v3 and v4 for this? Does Windower produce any sort of log when it crashes?

**Comment by WinterSolstice8** [comment]
Thanks for the reminder, will look into it tonight.

**Comment by Dev-Roland** [comment]
@zach2good Windower does not populate the Program Files\Windower\crash.log file on this crash. Self-busting on LSB doesn't crash the Ashita client AFAIK, though I don't have specifics more technical than that.
Thanks @WinterSolstice8

**Comment by zach2good** [comment]
Related issue: https://github.com/LandSandBoat/server/issues/2019
