### ISSUE TITLE
Server Crash When Non-Leader Homepoints While Near Apururu Trust

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1882]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Zone into Escha Zi'Tah (zone probably does not matter, but this is where the issue was observed)
2. Join a party with another player
3. Have the party leader summon Apururu (Apururu was the ONLY trust present in said party. Was 5 players/1 trust.)
4. From within casting range of Apururu, have a party member - not the leader - perform the !homepoint command
5. The server crashes at that point (apparently Apururu's code errors out while calculating the player's movement)
NOTE: Unsure if the party leader was/needs-to-be engaged in order to "activate" Apururu's AI in some way.
NOTE: The matching timing of the R0 and the !homepoint was confirmed by another player who saw it firsthand. (me)
NOTE: We have not been able to replicate this so far.

## Expected behavior

The player would warp to homepoint without the Apururu trust crashing the server.

**Comment by zach2good** [comment]
Useful repro steps, thanks! Do you have the stack trace from your crash dump? (in the log file, in the dmp folder, if it successfully generated one)

**Comment by Dev-Roland** [comment]
We turned on the debugger and have tried to reproduce it to obtain the stack trace dump, but have not been able to do so yet, sorry. I'll post it here if we obtain it.

**Comment by CatsEyeXI** [comment]
I'm not sure if relevant or not, but perhaps worth mentioning. NavMesh data used to be optional as a submodule update, but now it seems server will crash if NavMesh is not present and mob tries to navigate to player, and will do this very reliably...

**Comment by zach2good** [comment]
> but now it seems server will crash if NavMesh is not present and mob tries to navigate to player, and will do this very reliably...

Is there an issue raised for this somewhere with a stack trace? When careful pathing was added that introduced some crashes, but those were fixed pretty quickly.

**Comment by CatsEyeXI** [comment]
I'll add an issue with a dump Zach. I didn't want to over do it with all the new issues as I was concerned it would just bring more confusion, I'll get on it though.

**Comment by Dev-Roland** [comment]
It's possible that https://github.com/LandSandBoat/server/pull/2085 caused the crash that this issue was created for. The party leader was a MNK/dnc cleaving in zi-tah with Apururu and could have potentially cured Apururu with a waltz. If that was what happened then the repro steps should have a step 3.5: "_Cure apururu with a dancer's waltz_".

https://github.com/LandSandBoat/server/pull/2113 may have fixed this.

**Comment by WinterSolstice8** [comment]
This has probably been fixed, closing. Reopen if the issue comes back.
