### ISSUE TITLE
Homepoint On-Click Packet Intermittently Missing Variables

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1886]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Load the game using Windower, with the [superwarp addon](https://github.com/AkadenTK/superwarp) activated
2. Repeatedly execute various superwarp warps WHILE next to a homepoint (ex: //hp southernsand, //hp northernsand 2, //hp qufim)
NOTE: Please notice that all commands poke (activate/click) the nearby HP successfully.
NOTE: Please notice that the same command will occasionally work and ocassionally not work, printing out _"Incorrect npc detected. Canceling action._" when it does not work.
NOTE: That printed line is produced when this logic evaluates to true: Line 824 "_if current_activity.poked_npc_id ~= p["NPC"] or current_activity.poked_npc_index ~= p["NPC Index"] then_". So, apparently either the current_activity or p is **intermittently** missing an expected variable or has an incorrect value.

## Expected behavior

The successfully poked HPs will always provide the expected variables in the packets they produce.

**Comment by WinterSolstice8** [comment]
Thanks for the report. It seems this particular use of spamming hp warping exposed a rather obscure assumption in the event packet. The root cause of your error appears to have been that your player's target changed from the home point to nothing.
