### ISSUE TITLE
Mission interactions are failing to init in Windows

### ISSUE THREAD

**Issue by Hokuten85** [DerpyProjectGroup/topaz#189]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Mission interactions are failing to load in windows during the zone init. I believe the issue is in luautils::GetQuestAndMissionFilenamesList.  Window's preferred separator is '\\' so while looping through the directories and calling entry.path(), your path is actually something like: "scripts/missions\\acp\\01_A_Crystalline_Prophecy.lua".
In the loop it's checking for the number of '/' to determine depth, which works on linux, but not windows.  Since the mission files are not at the correct depth, it doesn't add them to outVec to be returned.

I've included a link to what I hacked together for my personal server.  Not sure if there's a more elegant solution.

https://github.com/Hokuten85/Ivalice/commit/3ca4480e9bef3c49b1c43b11dfa37cc473e9b4ec#diff-eeb9cc690647d9c2f5d1415ca5da922f2bbba9b3d3867d51035264276ac2fc05R359

**Comment by zach2good** [comment]
I'd rank none of the current loading and depth-counting as elegant, so if this works on all platforms and fixes the problem then I'm all for it 👍

**Comment by mrhappyasthma** [comment]
FWIW, I had the same issue on my local windows machine. Cherrypicking that workaround fixed it.

Although I'm not expert on windows filesystems so I have no input as to whether this is the "right" fix or not.

**Comment by zach2good** [comment]
I'm happy to take the commit, but I'm a bit concerned that I haven't seen the issue myself on my vanilla Windows machine with MSVC, my WSL instance, or my Mac.

Is there a step I'm missing to repro?

**Comment by mrhappyasthma** [comment]
Try going to Aht Urhgan to start `Luck of the Draw` with `Ratihb`. At head, the quest never triggers for me. Rebuilding with the `luautils.cpp` change from that commit fixes the issue.

I did not notice any errors in the logs or anything, just stumbled upon this similar issue and witnessed a fix with a before/after test.

**Comment by Hokuten85** [comment]
My reproduction steps were
1) start server
2) do mission that uses interactions
3) nothing happens

If I manually adjusted the specific mission lua file, the file watcher would pick up the change and then load the interaction.

But yeah, as @mrhappyasthma mentions there is no error anywhere.
https://github.com/LandSandBoat/server/blob/b16c5043009379cf7cbb7238e8c646224b932385/src/map/lua/luautils.cpp#L387
It just never adds anything to outVec because it fails the isCorrectDepth check
