### ISSUE TITLE
Crashes on Server with no NavMesh data present

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#1890]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Build new server without NavMesh data
2. Pull mob from a distance that causes mob to try to path to you.

![image](https://user-images.githubusercontent.com/65316697/172162021-510d7923-b571-446b-b16f-09075865bb5c.png)

## Expected behavior

Mob should path to player ignoring all obstacles.

**Comment by CatsEyeXI** [comment]
If I understand this bit of code correctly are we explicitly telling the map "if no navMesh then break? (Crash)"

**Comment by TeoTwawki** [comment]
Thats return not break. And even break doesn't mean crash - break, breakpoint, and debugbreak can all behave differently. Typically the latter two breaks stop the execution of the exe while plain ol break stops loops and switches. Returns are to send back a value or to just exit a function.

**Comment by CatsEyeXI** [comment]
> Thats return not break. And even break doesn't mean crash - break, breakpoint, and debugbreak can all behave differently. Typically the latter to breaks stop the execution of the exe while plain ol break stops loops and switches. Returns are to send back a value or to just exit a function.

I missed that, thanks for the explanation Teo
