### ISSUE TITLE
Jeuno Weather NPCs cause client position to freeze

### ISSUE THREAD

**Issue by JinxDojo** [DerpyProjectGroup/topaz#1900]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Inquiring the weather from a Jeuno weather NPC works--but causes the next interaction with an NPC to freeze the client position. (A warp or teleport is required--or a shutdown, of course.) This does not occur with the Bastok weather NPCs. (Others untested.)

**Comment by UynGH** [comment]
Hello, fixed here: https://github.com/LandSandBoat/server/pull/1859. Thank you!

**Comment by JinxDojo** [comment]
> Hello, fixed here: #1859. Thank you!

Thank you, again. I swear this time I searched more--but apparently not well enough.
