### ISSUE TITLE
Missing "You throw away a [item]." message (plus Windower/Shortcuts issue).

### ISSUE THREAD

**Issue by UynGH** [DerpyProjectGroup/topaz#1908]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base` and client updated as of 06/07/22.

## Steps to reproduce

I encountered two issues regarding messages lately. I can separate them if needed.

_First one_: There is no message displayed when you throw away something (might be related to the Recycle Bin).

**Related to Shortcuts with Windower exclusively**
~~_Second one_: When you use a Job Ability or trying to call Trusts while in combat and having hate (these two situations in particular because I tried spells or ranged weapons and it didn't happen) **directly from the menu**, it acts like you tried to fire it two times in a row:
![1 (3)](https://user-images.githubusercontent.com/102221430/172452284-d5ea6302-fd77-40df-9a08-884eb35bc243.jpg)
![2](https://user-images.githubusercontent.com/102221430/172452562-3750b594-b83b-4346-a6c3-11ad327bc71c.jpg)
Note: Work as intended if they are used through direct typed command or macros.~~

## Expected behavior

_First one_:
![3](https://user-images.githubusercontent.com/102221430/172452733-6e4bbbc6-2f5a-4321-8cab-05bdfd67ac2a.jpg)

**Related to Shortcuts with Windower exclusively**
~~_Second one_: Only one of these messages displayed for Job Abilities or Trusts casting while in combat.~~

Thank you!

**Comment by WinterSolstice8** [comment]
The source of this appears to be from addon load order on windower

I can produce it with:
//lua unloadall
//lua load gearswap
//lua load shortcuts
-> use the menu to summon a trust, 0x1A comes twice

//lua unloadall
//lua load shortcuts
//lua load gearswap
-> use the menu to summon a trust, 0x1A comes once

Ashita is affected too, but need more investigation

**Comment by WinterSolstice8** [comment]
Nevermind, Ashita does not have this bug in my setup.

**Comment by WinterSolstice8** [comment]
Update:
I tried to make a minimal repro setup on windower to load up retail and then LSB with fixed scripts to demonstrate the issue and it appears retail does not have this problem and I cannot currently explain why. Retail only sends one packet, not two.

**Comment by WinterSolstice8** [comment]
https://github.com/Windower/Lua/pull/2238 got merged, you'll need to use windower dev or manually merge in the change to Shortcuts to see if the second issue still affects you.

**Comment by UynGH** [comment]
Thanks for going down the rabbit hole, Winter. Edited the title and message accordingly for the last issue.

**Comment by UynGH** [comment]
First part fixed by: https://github.com/LandSandBoat/server/pull/3196
Second part fixed by: https://github.com/Windower/Lua/pull/2238
Thank you, Winter!
