### ISSUE TITLE
!ver command not fit for purpose - replace or remove

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#1928]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

It's a holdover from previous projects, and doesn't do much anymore (if it ever did).

## Expected behavior

A `!ver` that provides clear and useful information, or is removed.

**Comment by TeoTwawki** [comment]
[it was already removed, ](https://github.com/LandSandBoat/server/commit/936040cc1fef3650f98ec2c10d9989fe74ec5ced#diff-ab3ba4e398106bff2bea96af400d7b56806c3a7393a08a86be83c1c9ac14f7ae)and I agreed with a recent request in part and said I would see what we can do but as we do not HAVE a versioning system and at this juncture it didn't make sense to try and implement one, I couldn't make promises. We don't have a "1.0" or other versioning can't manually maintain one every update and can't automate it (that was tried, it didn't work out/get finished).

My desire at this time if to print the servers expected client version as well as some obtainable (and this is where it gets dicey) info about what git commit was last obtained from upstream or _when_ it was.

**Comment by zach2good** [comment]
It would make sense to do this after I refactor settings in the next few weeks

**Comment by kaincenteno** [comment]
Can the reply to "!ver" be the branch + commit number? And be a default command for all users

It will come in handy for when players submit issues =)

**Comment by zach2good** [comment]
We have branch+commit available through the auto-generated `version.cpp`, but that's only useful for servers that make _zero_ changes to their git repo. Checking in setting, a couple of small tweaks, custom modules etc. will start an entirely new "tree" in git and the commits won't align with what we have upstream. 

At that point, all we know is that "they have changed _something_", which isn't super useful. Tracking version numbers by hand (by "release" date or otherwise) also has the same problem, because people are just going to make changes, small or large.

So, all we can really do is keep chanting: "please repro on the latest clean commit from main", otherwise we don't know if we're dealing with a couple of innocent tweaks, or a full-blown franken-repo 🤷 

I can absolutely see the side of just not bothering with the command all together

**Comment by zach2good** [comment]
lol @ I already removed it a month ago: https://github.com/LandSandBoat/server/commit/936040cc1fef3650f98ec2c10d9989fe74ec5ced#diff-ab3ba4e398106bff2bea96af400d7b56806c3a7393a08a86be83c1c9ac14f7ae

Swiss-cheese brain

**Comment by zach2good** [comment]
![image](https://user-images.githubusercontent.com/1389729/173013483-9f5865f7-9c42-492e-83f6-87e60435bb31.png)

I've opted for a `!build` command, rather than `!ver` - since we haven't actually tracked a version for _years_. It's the same information we produce during CMake configuration time, and for crashes.
