### ISSUE TITLE
SCH Ability Perpetuance Unavailable Ingame

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1932]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Set main job to SCH lv 87+
2. View your job abilities
3. Notice that "Perpetuance" is not available

## Expected behavior

Perpetuance would be listed in the job ability list and be usable

**Comment by Dev-Roland** [comment]
I imagine this ability just hasn't been developed yet and, though this is more of a request than an issue at that point, I did not see a section for making request. Sorry if this doesn't fit here.

**Comment by MowFord** [comment]
This is [implemented](https://github.com/LandSandBoat/server/blob/2a8371d5e3c0919299550db17c47dd5231a7d234/scripts/globals/magic.lua#L786)

**Comment by Xaver-DaRed** [comment]
Also in new magic system.

For future reference, anything inside magic.lua should be ignored
