### ISSUE TITLE
No name for equipped look dynamic mobs

### ISSUE THREAD

**Issue by RunAwayDSP** [DerpyProjectGroup/topaz#1939]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Use a equipped look on a dynamic mob and the name will disappear. 
Equipped look:
0x01000A040010262019303A40195008611C700000

## Expected behavior

Name should appear with new look

Entity update packet offset appears to need an adjustment based on of its an equipped look (for renamed mobs)

**Comment by WinterSolstice8** [comment]
Confirmed, I get mob named "W" that would be "Fafnir" from the modified !fafnir command by only changing the following
`look = "0x01001D07570057005700570057009A0000007000",`
![image](https://user-images.githubusercontent.com/60417494/173513674-bd0e3b98-0fac-4d9c-9fb6-508231fb353e.png)

**Comment by zach2good** [comment]
My guess would be this:
in entity_update.cpp
```cpp
    // Send look data
    switch (PEntity->look.size)
    {
        case MODEL_STANDARD:
        case MODEL_UNK_5:
        case MODEL_AUTOMATON:
        {
            ref<uint32>(0x30) = ::ref<uint32>(&PEntity->look, 0);
        }
        break;
        case MODEL_EQUIPPED:
        case MODEL_CHOCOBO:
        {
            this->setSize(0x48);
            memcpy(data + (0x30), &(PEntity->look), 20);
        }
        break;
        case MODEL_DOOR:
        case MODEL_ELEVATOR:
        case MODEL_SHIP:
        {
            this->setSize(0x48);
            ref<uint16>(0x30) = PEntity->look.size;
            memcpy(data + (0x34), PEntity->GetName(), (PEntity->name.size() > 12 ? 12 : PEntity->name.size()));
        }
        break;
    }
```

In lua_zone.cpp:
```
    if (table["look"].get_type() == sol::type::number)
    {
        PEntity->SetModelId(table.get<uint16>("look"));
    }
    else if (table["look"].get_type() == sol::type::string)
    {
        auto look = stringToLook(table.get<std::string>("look"));
        std::memcpy(&PEntity->look, &look, sizeof(PEntity->look));
    }
```

^ We need to set the model type, so the name and look can be put in the right place in the packet

**Comment by zach2good** [comment]
Or setting the right size, or whatever
```cpp
    if (table["look"].get_type() == sol::type::number)
    {
        PEntity->SetModelId(table.get<uint16>("look"));
        PEntity->look.size = MODEL_STANDARD;
    }
    else if (table["look"].get_type() == sol::type::string)
    {
        auto look = stringToLook(table.get<std::string>("look"));
        std::memcpy(&PEntity->look, &look, sizeof(PEntity->look));
        PEntity->look.size = MODEL_EQUIPPED;
    }
```

^ Maybe? It might need to inspect the look string, to see if it's actually equipped (checking the gear slot offsets)
