### ISSUE TITLE
🐛 TONS of inaccurate gear uploaded 

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#1942]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Commits on Jun 7, 2022

    [Update item_mods.sql](https://github.com/LandSandBoat/server/commit/d52636287f44f78acda43cab16c1cfe4eaed379d) 

@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 3 days ago

[Update Missing description](https://github.com/LandSandBoat/server/commit/5dd1d87c4717cf0dbbe4afb4901a72b44c144cba)
@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 3 days ago

[Update item_mods.sql](https://github.com/LandSandBoat/server/commit/362b095659ec3c811c5bbf7a92ef9157ad3afd35)
@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 3 days ago

[Update item_mods.sql](https://github.com/LandSandBoat/server/commit/027d02dcd0e153d70a876ace65d9cdc2700aa3b1)
@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 3 days ago

Commits on Jun 6, 2022

    [Update locations for gear](https://github.com/LandSandBoat/server/commit/8871700af293eb16009fba8e65d635a736eda662) 

@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 4 days ago

[Gear Update](https://github.com/LandSandBoat/server/commit/f5fc19cc26bb10f69b899dcf6618bef781a910a9)
@[Xxsoulsin](https://github.com/LandSandBoat/server/commits?author=Xxsoulsin)
Xxsoulsin committed 4 days ago

## Expected behavior

I have added custom modded gear to our server over the past 2 weeks or so, often with inaccurate stats - pre-augmented boosts - testing "pet" additions, 1 piece set bonus and more. 

I dont know who this Xxsoulsin person is but they never should have pushed any of this into live data to be lost forever and overpowered beyond the visual stats.

I see bope12 already removed our "pet fix" rings as 'godmode' rings from the pull Xxsoulsin uploaded. There are MANY MANY MANY more items there that are incorrect and if not pulled likely to stay that way forever.

**Comment by Hinekri** [comment]
Looks like they didnt exist until 4 days ago and only jumped in to slam live with all the custom stuff I have done lol..

**Comment by Xaver-DaRed** [comment]
I'll go through them all and remove the innacurate/custom ones

**Comment by TeoTwawki** [comment]
@Hinekri  we know, we saw it earlier this morning

**Comment by Hinekri** [comment]
I just now saw the godmode ring I made and instantly knew it came from my module files. Wanted to let you know asap, it wasnt one of the GMs on our server, so that guy just wanted some submission credit I guess.  Thanks

**Comment by TeoTwawki** [comment]
This is a problem with large sets of item mod coming in at once, they usually aren't 100% verified before merge button is in. typically reviewers will check some see it legit and figure contributor has checked their work well. 

Some kind of tool to prevent human error during input of new items and or a limit to how many mods can come in on a single pr is needed as human eyes just get tired on larger pr's. 

Still, I think its been years since we accidently merged in accidental custom soooo we had a good run before having to reset the "this many days since accident" sign. ^^;

**Comment by Hinekri** [comment]
Lol! I was wondering how it got past the approval point, figured it was just so many lines someone just assumed it was good to go and accepted it.

**Comment by Hinekri** [comment]
Is there any recourse to the "author" that stole my data and submitted as his own? Even though it was custom and not legit im still kinda ticked there.

**Comment by jeffnavy14** [comment]
whelp so much for submitting our stuff, seems like some one did it for us...

**Comment by TeoTwawki** [comment]
> Is there any recourse to the "author" that stole my data and submitted as his own? Even though it was custom and not legit im still kinda ticked there.

unsure, can't really undo the commit, just fix it after the fact. And we don't have anything like an incident post mortem doc at this time. we def weren't interested in any custom and would have liked the retail accurate stuff to be properly attributed when it came in.

**Comment by Hinekri** [comment]
Figured there would be a Ban button to prevent more uploads from said person.

**Comment by jeffnavy14** [comment]
That was our intention, is to get close first but we were not any where close to being ready to submit.

**Comment by Hinekri** [comment]
Yeah needed a full 'audit' to check the legit stats, remove aug/set bonuses and any extras before it went in. We hadnt even finished the list of "whats been added" for our own use yet id just been pumping out set after set.

**Comment by Hinekri** [comment]
@Xaver-DaRed Sorry for the audit headache, plan was for me to update them for retail after I finished the rest, guessing we might need to go private so this doesnt happen again as I add more stuff daily.

**Comment by TeoTwawki** [comment]
> Figured there would be a Ban button to prevent more uploads from said person.

Xxsoulsin appears to have deleted his github account, but I don't think a ban would have been needed. He or She is probably very embarrassed.

**Comment by TeoTwawki** [comment]
Xaver's audit and correction of the involved mods has been merged now.

**Comment by TeoTwawki** [comment]
Some steps have also been taken to make it more difficult to slip wrong mods past review, including tooling to label mods by Claywar

**Comment by Xaver-DaRed** [comment]
I'm all in favor of imposing some kind of reasonable limit to the amount of modifiers added in a single PR

There's a limit to how many mods can be checked without loosing concentration, interestest and the will to live.

**Comment by TeoTwawki** [comment]
Same. But best to limit total items added rather than total mods - don't want any half items.
