### ISSUE TITLE
🐛 [Navmesh] [Error]  Several Escha RuAun mobs can't find paths

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1948]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

Logs from ximap

```
[06/11/22 07:05:21:191][map][error][navmesh] CPathFind::FindPath Entity (IceSpirit - 17961254) could not find path (FindPath:356)
[06/11/22 07:05:21:590][map][error][navmesh] CPathFind::FindPath Entity (DarkSpirit - 17961233) could not find path (FindPath:356)
[06/11/22 07:05:22:391][map][error][navmesh] CPathFind::FindPath Entity (IceSpirit - 17961278) could not find path (FindPath:356)
[06/11/22 07:05:23:190][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961103) could not find path (FindPath:356)
[06/11/22 07:05:23:590][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961093) could not find path (FindPath:356)
```

## Steps to reproduce

Zone into Escha RuAun
Check your ximap server log for a 1-6 errors every 3-5 seconds

You will sometimes see the mobs being swallowed by the floor. Specially if the walk on areas with steps.

## Expected behavior

Zone into Escha Ruaun
Check ximap server log

No navmesh errors every second. ( Some areas have this issue but with a player being in this area a lot i have seen that most of my logs are because of this area)

**Comment by The-Aerec** [comment]
I'm guessing this is the BST / SMN pet following master path errors that happen in every zone

**Comment by kaincenteno** [comment]
thanks @zach2good  looks like the smn/pet following master is fixed with thePR you submitted last week :D but still happening to this specific mobID Eschan_Ilaerns_Euvhi - 17961058

looks like the navmesh on the staircase something going wrong with the navmesh of this specific starcase  at 375, -20, -124 in  Escha Ru'Aun as mobs dissapear for a couple seconds to the reappear (most likely falling off map)

![Screen Shot 2022-06-17 at 7 57 50 AM](https://user-images.githubusercontent.com/26943220/174324396-fab42fd5-75b8-4d28-a785-3383912b42b1.png)
![Screen Shot 2022-06-17 at 7 52 32 AM](https://user-images.githubusercontent.com/26943220/174324535-458900f0-69ee-4158-a985-edfbb4658b44.png)


![Screen Shot 2022-06-17 at 7 52 13 AM](https://user-images.githubusercontent.com/26943220/174324471-6c78e032-5c6d-4d46-a481-8f8ebdfd1f77.png)

it mostly happens with this tiny monster maybe cuz of where its collision point is with the staircase but it also happens with the other bigger mob

**Comment by zach2good** [comment]
Should be fixed in https://github.com/LandSandBoat/server/pull/1990
