### ISSUE TITLE
🐛 POL-0001 errors for char IDs >=2

### ISSUE THREAD

**Issue by jason-colby-brown** [DerpyProjectGroup/topaz#1949]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue

`base`

## Steps to reproduce

Attempt to login with character id of >= 2 in chars table. These are all characters for a single account, in my use case.  Char id 1 is able to login without issue.

## Expected behavior

POL-0001 error occurs, and returned to FFXI title screen with select character, create character, delete character.  Nothing is output/logged in xi_connect or xi_map.

**Comment by Xaver-DaRed** [comment]
what do you mean?
Are you trying to log in 2 characters from the same account at the same time?

**Comment by jason-colby-brown** [comment]
No, I'm the only user for my server, in my case, so don't know if affects any/all accounts for a server. 1 character logging in at a time. char id 1 works fine. char id of >= 2 fails.

**Comment by RunAwayDSP** [comment]
character id of >= 2 or content id

I can reproduce this is error by attempting to make more than 1 character on an account, but I can make a new account and access the server on the 1st contentid for that account
