### ISSUE TITLE
🐛 Aern's Reraise causes Server Crash If Pet is Killer and Pet is Despawned During Reraise

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#1955]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Fight any Aern with the Aern family mixin. 

Attack with Carbuncle
!hp 0 (while ensuring aern is fighting carby)
release carby when aern dies

server crash

## Expected behavior

Aern aggros master since carby is no longer alive. 

No Crash

### Crash DMP

[xi_map.exe_11-6_22-14-49.log](https://github.com/LandSandBoat/server/files/8885094/xi_map.exe_11-6_22-14-49.log)

**Comment by The-Aerec** [comment]
I have this fixed, it will be included in my Sea NM System PR that will be open soon.

**Comment by TeoTwawki** [comment]
for those curious, I spoke with him last night, this is where the crash is from:
1. in the core, a mobs "killer" is NEVER a pet. It will be the pets master instead. 
2. per this change https://github.com/LandSandBoat/server/commit/432058d0ae232b2f0341b1e379e0f9b4a9515eb8#diff-9e1672728e84fb97c8c27c5cd725eac63dbbd564d13f090e32ec15c65da6cddcR27 the value of "killer" is being overwritten with the mobs last target. This bypasses all the safeties of pet-less killer and tries to set enmity and claim to an invalid object.
