### ISSUE TITLE
🔨 Add mountID for Noble Chocobo companion

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1963]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Missing mountID for noble chocobo mount

**Comment by Xaver-DaRed** [comment]
that mount doesnt work like other, regular mounts.
One big clue is how your character is locked in place when summoning it, unlike other mounts

**Comment by kaincenteno** [comment]
yeah i have seen !setmount command to the next one and it shows the char flying without moving xD

**Comment by TeoTwawki** [comment]
> that mount doesnt work like other, regular mounts. One big clue is how your character is locked in place when summoning it, unlike other mounts

its client side doing that tho. my guess is SE copy pasted the chocobo then edited, rather then making the entity they needed form scratch and loading the chocobo model they wanted into it.
