### ISSUE TITLE
🐛 Geodes/Avatarites drop when Mobmod NO_DROPs is set

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#1964]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Give a mob the mobmod: NO_DROPS = 1
Watch mobs still drop avatarites and geodes.

![image](https://user-images.githubusercontent.com/6257062/173241924-9d3eb52c-925b-4e78-ba50-8db913d43b0f.png)
![image](https://user-images.githubusercontent.com/6257062/173241949-b108c0d8-e996-4a04-87b3-2be923e8daaa.png)

## Expected behavior

No drops whatsoever

**Comment by Xaver-DaRed** [comment]
geodes and avatarites are handled in core, similar to crystals and seals. Maybe a config or some other kind of check is needed

**Comment by claywar** [comment]
I think there's mob mods that prevent other drops.  Should probably do the same here

**Comment by The-Aerec** [comment]
Yea i'm just adding the similar core check for the mob mod that weren't included in the geode / shivite section:

Fixed, once again this issue will be closed via my Sea NM System PR thats incoming

**Comment by zach2good** [comment]
> geodes and avatarites are handled in core, similar to crystals and seals. Maybe a config or some other kind of check is needed

I've been thinking about some new settings for:

ENABLE_CRYSTAL_DROPS
ENABLE_GEODE_DROPS
ENABLE_AVATARITE_DROPS

etc.

I don't know if they're redundant or not?

**Comment by claywar** [comment]
Remember, this is mob-specific in this case, not settings

**Comment by TeoTwawki** [comment]
I can fix this this week. I merely forgot to ensure it was checking for that before it reached the portion of the code that rolls for them

**Comment by TeoTwawki** [comment]
> > geodes and avatarites are handled in core, similar to crystals and seals. Maybe a config or some other kind of check is needed
> 
> I've been thinking about some new settings for:
> 
> ENABLE_CRYSTAL_DROPS ENABLE_GEODE_DROPS ENABLE_AVATARITE_DROPS
> 
> etc.
> 
> I don't know if they're redundant or not?

who legit wants to disable crystals? 

mmm I could see maybe for the avatarites and geode tho for crafter reasons but I dunno, its pretty simple to just comment out for servers that don't want it them.

**Comment by TeoTwawki** [comment]
> Yea i'm just adding the similar core check for the mob mod that weren't included in the geode / shivite section:
> 
> Fixed, once again this issue will be closed via my Sea NM System PR thats incoming

Didn't see this at 1st. but I really do not like pr's that include multiple non related things. If you wanna split that out its simple enough it could probably be approved pretty quickly.
