### ISSUE TITLE
🐛 [mob] Lycopodium family shouldn't show engage animation when following PC

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1971]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

walk near lycopodiums
see them stand in attack range and waving their hands
(also looks like they stop aggro after a while and lose interest and walk away, they shouldnt lose interest until you move away from their spawn area)

![Screen Shot 2022-06-12 at 7 05 57 PM](https://user-images.githubusercontent.com/26943220/173267173-d203bec7-525e-4114-9580-78f2a76e336b.png)

## Expected behavior

walk near lycopodiums
they should walk closer than regular attack range.
https://www.youtube.com/watch?v=5fDGpteR4CE

(really bad quality video here)
https://www.youtube.com/watch?v=1v_p6jpzTVM

**Comment by RAIST5150** [comment]
Would note they also trigger avatars/elementals to auto attack like when goldfish follow you in Sea.

Don't recall whether that happened in retail WotG areas, so that may need verification.

**Comment by Omnione** [comment]
I tested this the other day, lycopodiums following do not trigger an avatar to attack, even at lower levels on retail
