### ISSUE TITLE
🐛 Blackmages Tier 6 spells cost 0 MP, instant cast, and doing insane damage.

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#1980]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Not sure exactly when this changed, was reported by someone on our server and just tested/verified by me.
![Kirito_2022 06 13_115141](https://user-images.githubusercontent.com/106329891/173405663-952eac99-209f-402d-9e31-bda21ff3c9f7.png)

I think Aero VI is the only one with a huge boost in it's attack but all of them are instant cast and use no MP now.

Test was also done with zero gear on, no change.

## Expected behavior

MP Should be used as stated. 
Spell casting time should apply.
Aero VI should not be scaled 4x higher than the rest.

**Comment by EpicTaru** [comment]
Tracking back in the history, doesn't look like those spells ever had the values for mpCost or castTime added.  I'll do a PR to add them in momentarily.

**Comment by Xaver-DaRed** [comment]
Aero VI has a typo in it's parameter table entry, that has that unfortunate OP side-effect.

I will fix that in a near-future PR. If anyone want's to tackle giving mp and casting time values in the db for those spells, feel free, but please leave anything regarding the spells folder alone for a few days so I can complete the next rewrite.
