### ISSUE TITLE
Spell Damage currently broken

### ISSUE THREAD

**Issue by AikoSachi** [DerpyProjectGroup/topaz#1983]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

'base'

This was broken on my last pull, and the issue seems to be inside of Server\Scripts\Globals\Spells\spell_damage.lua

Was fixed upon inserting a backup I had locally.

Lines that were changed:

![image](https://user-images.githubusercontent.com/46535607/173449214-6117528d-53a8-4ae5-acb7-55b86f596b11.png)
![image](https://user-images.githubusercontent.com/46535607/173449252-d1f4a724-b04d-4a0c-9d69-58de163b885b.png)

## Steps to reproduce

Cast a spell, It currently does 131071 damage in the log, but it actually does 0 damage.

## Expected behavior

Should be doing damage

**Comment by jeffnavy14** [comment]
Is there a specific spell you used? I tried this on both my live and test server with the latest pulls.
I was able to use Banish III, Holy II, all tier's of fire, water, earth, wind, etc. without issue

**Comment by WinterSolstice8** [comment]
Did you rebuild xi_map? if checkLiementAbsorb was nil due to no binding, it will have undefined behavior.
![image](https://user-images.githubusercontent.com/60417494/173473855-cbc702ea-d5d8-4100-b21b-f305d28a2494.png)

**Comment by zach2good** [comment]
Anything in the server logs?

**Comment by zach2good** [comment]
ie. If something gets nil'd along the way, you could get a complaint about it: `attempt to perform arithmetic on a nil value`

**Comment by CatsEyeXI** [comment]
Could this be related? 

![image](https://user-images.githubusercontent.com/65316697/173886482-1c270159-dd2e-4c44-8bd4-1c10d12cb4bc.png)

**Comment by AikoSachi** [comment]
To answer some questions, I had not rebuilt before this happened.

I did try to rebuild after I saw this but my fork of ASB had some issues when I did and I haven't had time to play with it since.
