### ISSUE TITLE
🐛 Add Spell Can crash the server

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#1986]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

!addspell certain spells

Observer server crash

## Expected behavior

server shouldn't crash.

dmp attached. 

[xi_map.exe_13-6_18-2-38.log](https://github.com/LandSandBoat/server/files/8895747/xi_map.exe_13-6_18-2-38.log)

**Comment by TeoTwawki** [comment]
got an example spell? I've seen this happen when using addspell on trust spells instead of addtrust way back in dsp, and I think I'd seen it when db info was missing but its been multiple years now.

**Comment by zach2good** [comment]
From deep in those logs (I dug these out for you dude, you could have pasted them)

it's from:!addspell 14331

**Comment by TeoTwawki** [comment]
Max id in the clients dat is faaaar below that value. This was super out of bounds (stops at 1023).

**Comment by zach2good** [comment]
Needs an OOB check in charutills::addSpell

**Comment by TeoTwawki** [comment]
> Needs an OOB check in charutills::addSpell

I _almost_ opted to do the check in the lua side instead before deciding to prevent people from making mistakes outside of the GM command too.
