### ISSUE TITLE
🔨 SCH Immanence Ability Available Ingame

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1994]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

The SCH [Immanence](https://www.bg-wiki.com/ffxi/Immanence) is available ingame for a LV 87+ SCH if a stratagem charge is available.
When active, Immanence causes elemental magic to perform its intended skillchain when executed in the correct order.

**Comment by MowFord** [comment]
This is [implemented now](https://github.com/LandSandBoat/server/blob/2a8371d5e3c0919299550db17c47dd5231a7d234/src/map/entities/charentity.cpp#L1150)

**Comment by Xaver-DaRed** [comment]
Also in new magic system.

For future reference, anything inside magic.lua should be ignored
