### ISSUE TITLE
xi_map Starter flash back 

### ISSUE THREAD

**Issue by xuchen0823** [DerpyProjectGroup/topaz#1996]
windows server 2019  Flash back after installation

**Comment by zach2good** [comment]
Hello! We have a block of information that you're meant to fill out when a new issue is created so that we can identify and fix issues faster. You appear to have deleted it.
``` 
I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

Branch affected by issue
base

Steps to reproduce

Expected behavior
```

Can you make sure you go back and read the relevant information, and then return with some steps to help us reproduce and then fix your issue.

Cheers!

**Comment by xuchen0823** [comment]
[06/15/22 02:12:31:933][map][info][status] do_init: begin server initialization (do_init:182)
[06/15/22 02:12:31:935][map][error][error] FAIL. See /scripts/settings/README.md immediately. (do_init:202)

C:\Users\Administrator\Desktop\server\server\xi_map.exe (进程 1240)已退出，代码为 1。
按任意键关闭此窗口. . .

**Comment by xuchen0823** [comment]
thank you @zach2good

**Comment by UynGH** [comment]
Hello and thank you.

Copy the file "main.lua" inside server/scripts/settings/default to server/scripts/settings and edit it.

You probably forgot this step from the Wiki guide (here: https://github.com/LandSandBoat/server/wiki). Happened to me weeks ago.

**Comment by xuchen0823** [comment]
uyngh 1 hello  Optimistic for many times Not resolved thank you

**Comment by xuchen0823** [comment]
@UynGH  thank solve
