### ISSUE TITLE
🐛 Hajduk Ring and Hajduk Ring+1 listed as Earring on AH

### ISSUE THREAD

**Issue by Metal36** [DerpyProjectGroup/topaz#1998]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

List either ring on Auction House

## Expected behavior

Ring should go to Ring category on AH

**Comment by EpicTaru** [comment]
Think I found the issue, testing before I do a PR.
