### ISSUE TITLE
🐛 [Crash] CBattleEntity::isDead [Commit 0688693]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#2001]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

```
[06/15/22 01:25:13:709][map][info][info] parse: 01A | 5811 5810 0E from user: Raist (parse:714)
[06/15/22 01:25:13:709][map][info][action] CLIENT Raist PERFORMING ACTION Ranged Attack (0x10) (SmallPacket0x01A:1156)
[06/15/22 01:25:13:942][map][info][info] parse: 01A | 1CC3 1CB8 0E from user: Crazylady (parse:714)
[06/15/22 01:25:13:942][map][info][action] CLIENT Crazylady PERFORMING ACTION Disengage (0x04) (SmallPacket0x01A:1156)

Thread 1 "xi_map" received signal SIGSEGV, Segmentation fault.
CBattleEntity::isDead (this=0x7f69081dd260) at /server/src/map/entities/battleentity.cpp:100
100	    return (health.hp <= 0 || status == STATUS_TYPE::DISAPPEAR || PAI->IsCurrentState<CDeathState>() || PAI->IsCurrentState<CDespawnState>());
#0  CBattleEntity::isDead (this=0x7f69081dd260) at /server/src/map/entities/battleentity.cpp:100
#1  CBattleEntity::isAlive (this=0x7f69081dd260) at /server/src/map/entities/battleentity.cpp:105
#2  battleutils::RelinquishClaim (PChar=0x7f690837bb80) at /server/src/map/utils/battleutils.cpp:5202
#3  0x0000000000492843 in CCharEntity::OnChangeTarget (this=0x7f690837bb80, PNewTarget=0x0) at /server/src/map/entities/charentity.cpp:795
#4  0x00000000004696b7 in CAttackState::UpdateTarget (this=0x39bf8a80, targid=<optimized out>) at /server/src/map/ai/states/attack_state.cpp:144
#5  0x000000000047cad9 in CState::DoUpdate (this=0x39bf8a80, tick=...) at /server/src/map/ai/states/state.cpp:87
#6  CAIContainer::Tick (this=0x7f69081d3fb0, _tick=...) at /server/src/map/ai/ai_container.cpp:382
#7  0x00000000008352a0 in CZoneEntities::ZoneServer (this=0x160754c0, tick=..., check_regions=false) at /server/src/map/zone_entities.cpp:1508
#8  0x000000000083d4ba in CZone::ZoneServer (this=0x16075350, tick=..., check_regions=false) at /server/src/map/zone.cpp:838
#9  0x000000000083957e in zone_server (tick=..., PTask=<optimized out>) at /server/src/map/zone.cpp:79
#10 0x0000000000430ca8 in CTaskMgr::DoTimer (this=0x7f6908f2c6e0, tick=...) at /server/src/common/taskmgr.cpp:119
#11 0x000000000041dd70 in main (argc=1, argv=<optimized out>) at /server/src/common/kernel.cpp:277
```

**Comment by CatsEyeXI** [comment]
we've seen this as well.
![image](https://user-images.githubusercontent.com/65316697/173730573-76295ab3-ceec-4f4d-a901-118008851b65.png)

**Comment by CatsEyeXI** [comment]
another one

![image](https://user-images.githubusercontent.com/65316697/174214226-dac01a08-f88e-4d04-a6e7-5ca2ddba13d6.png)

![image](https://user-images.githubusercontent.com/65316697/174215613-82c39155-e25e-4d15-ab6a-e65ac5381dec.png)

**Comment by WinterSolstice8** [comment]
Very interesting "entity" there. Thanks.

**Comment by CatsEyeXI** [comment]
```
 	xi_map.exe!CAIContainer::GetCurrentState() Line 310	C++
 	[Inline Frame] xi_map.exe!CAIContainer::IsCurrentState() Line 102	C++
 	xi_map.exe!CBattleEntity::isDead() Line 98	C++
 	xi_map.exe!CBattleEntity::isAlive() Line 103	C++
>	xi_map.exe!battleutils::ClaimMob(CBattleEntity * PDefender, CBattleEntity * PAttacker, bool passing) Line 5142	C++
 	xi_map.exe!battleutils::TakePhysicalDamage(CBattleEntity * PAttacker, CBattleEntity * PDefender, PHYSICAL_ATTACK_TYPE physicalAttackType, int damage, bool isBlocked, unsigned char slot, unsigned short tpMultiplier, CBattleEntity * taChar, bool giveTPtoAttacker, bool isCounter, bool isCovered, bool POriginalTarget, CBattleEntity *) Line 2222	C++
 	xi_map.exe!CBattleEntity::OnAttack(CAttackState & state, action_t & action) Line 1840	C++
 	xi_map.exe!CAttackState::Update(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick) Line 66	C++
 	xi_map.exe!CAIContainer::Tick(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> _tick) Line 382	C++
 	xi_map.exe!CZoneEntities::ZoneServer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, bool check_regions) Line 1515	C++
 	xi_map.exe!CZone::ZoneServer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, bool check_regions) Line 844	C++
 	xi_map.exe!zone_server(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, CTaskMgr::CTask * PTask) Line 80	C++
 	xi_map.exe!CTaskMgr::DoTimer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick) Line 122	C++
 	xi_map.exe!main(int argc, char * * argv) Line 278	C++

```

**Comment by CatsEyeXI** [comment]
would a dump help or do we know why this is happening?

**Comment by WinterSolstice8** [comment]
Dumps always help, more is better. It helps ID if any player reports match what might be going on here to help better reproduce the issue.

**Comment by CatsEyeXI** [comment]
> Dumps always help, more is better. It helps ID if any player reports match what might be going on here to help better reproduce the issue.

http://catseyexi.com/crash/isDeadisAlive.zip 

I saw Valaineral's name pop up in this.. So I'm not sure if this is again somehow trust related.

**Comment by CatsEyeXI** [comment]
Let me know if you have problems downloading that dump.
Players are reporting sometimes they will engage a mob and trusts will just sit there and do nothing, they will have to disengage and re-engage, some say its only when a mob is in a weird position.

**Comment by WinterSolstice8** [comment]
do you know the commit this was made on? need the source to match better

**Comment by CatsEyeXI** [comment]
> do you know the commit this was made on? need the source to match better

https://github.com/LandSandBoat/server/pull/2045
I believe this was the last PR i took into production.

**Comment by WinterSolstice8** [comment]
Thanks. The debugger was very helpful with that dump. I'm looking into a few suspect things.

**Comment by claywar** [comment]
@beneliezer Can you please retest when #2085 is merged?

**Comment by CatsEyeXI** [comment]
> @beneliezer Can you please retest when #2085 is merged?

💯 will do

**Comment by WinterSolstice8** [comment]
The crash dump made me look at a bunch of stuff and stumbled on the enmity container crash. See #2085. It's a bandaid fix for that, and I can't promise that it fixes this exact issue.

But I have to say, without the dump this would not have been caught. Please give them, they're super useful.

That said, your crash was very interesting. Apparently, there was a WHM(?) (they only had club skill) that had a garbage pointer to the _previous_ claim target. I do not know what it is or was, as the pointer was garbage. The step that ultimately showed the crash was a cure cast on a trust, based on a garbage pointer from whatever that player had previously casted upon.

**Comment by CatsEyeXI** [comment]
Thanks for the review and for the effort put forth in troubleshooting this. Some days we get 2-3 of these, others they are back to back... I am absolutely happy to provide dumps so don't hesitate to ask me for them. Uptime is my top priority.

**Comment by WinterSolstice8** [comment]
Ideally you'd give them us every time, the best way is to note your commit and provide a dump, but I realize that it's not always reasonable to do so. But with recurring ones like this, we never got a real dump until now and it already was worth it's weight in gold to me

**Comment by CatsEyeXI** [comment]
I will start providing dumps and commit, no problem.

**Comment by CatsEyeXI** [comment]
Crashes seemed to have slowed down a little bit, but still happening.... New Dump

https://we.tl/t-cA8ijzQuT0

Commit: d2ff2853e1d3f1cc84c1eaf977fc48bd0841ac12

```
>	xi_map.exe!CAIContainer::GetCurrentState() Line 308	C++
 	[Inline Frame] xi_map.exe!CAIContainer::IsCurrentState() Line 102	C++
 	xi_map.exe!CBattleEntity::isDead() Line 98	C++
 	xi_map.exe!CBattleEntity::isAlive() Line 103	C++
 	xi_map.exe!battleutils::RelinquishClaim(CCharEntity * PChar) Line 5240	C++
 	xi_map.exe!CZoneEntities::DecreaseZoneCounter(CCharEntity * PChar) Line 386	C++
 	xi_map.exe!CZone::DecreaseZoneCounter(CCharEntity * PChar) Line 630	C++
 	xi_map.exe!SmallPacket0x00D(map_session_data_t * const PSession, CCharEntity * const PChar, CBasicPacket data) Line 544	C++
 	[External Code]	
 	[Inline Frame] xi_map.exe!std::_Func_class<void,map_session_data_t *,CCharEntity *,CBasicPacket>::operator()(map_session_data_t * <_Args_0>, CCharEntity * <_Args_1>, CBasicPacket) Line 880	C++
 	xi_map.exe!parse(char * buff, unsigned __int64 * buffsize, sockaddr_in * map_session_data, map_session_data_t *) Line 746	C++
 	xi_map.exe!do_sockets(fd_set * rfd, std::chrono::duration<__int64,std::ratio<1,10000000>> next) Line 512	C++
 	xi_map.exe!main(int argc, char * * argv) Line 275	C++

```

**Comment by WinterSolstice8** [comment]
The IsDead/IsAlive is a red herring, but it tells us something important. Thanks, will dig.

**Comment by WinterSolstice8** [comment]
See #2113 for a fix generated by this crash. Essentially, someone zoned after "claiming" a trust that was deleted. That PR disables claiming things that should not be claimed.

**Comment by CatsEyeXI** [comment]
> See #2113 for a fix generated by this crash. Essentially, someone zoned after "claiming" a trust that was deleted. That PR disables claiming things that should not be claimed.

thanks, I'll update once its merged and keep you updated.

**Comment by CatsEyeXI** [comment]
> See #2113 for a fix generated by this crash. Essentially, someone zoned after "claiming" a trust that was deleted. That PR disables claiming things that should not be claimed.

Update: crashes greatly reduced... i had one/two happen while debugger wasn't running but we've been solid for about 30 hours now... so good job, much appreciated. Running in the debugger now and see what the next crash is for...

**Comment by WinterSolstice8** [comment]
I wouldn't be surprised if it were a completely unrelated crash :)

That said, these fixes I've been putting in are mere bandaids. I don't have time as of recent to really rip out the system that these crashes have been related to for Pets and Trusts. Still, the dumps help isolate problems that mere mortals could not possibly understand from such a large codebase, so thanks to you too.

**Comment by CatsEyeXI** [comment]
Update: We are crash free...

**Comment by claywar** [comment]
Closing this issue from the above comment.  Should this reoccur, please reopen
