### ISSUE TITLE
Command setting

### ISSUE THREAD

**Issue by xuchen0823** [DerpyProjectGroup/topaz#2009]
hello need  GM command buy with you script text to find one  @

**Comment by Omnione** [comment]
![auto-translate](https://user-images.githubusercontent.com/10185476/173888373-d05abc1a-447d-4faf-b533-22e399483667.PNG)

**Comment by Xaver-DaRed** [comment]
And please stop deleting the template. It's there for a reason.

**Comment by xuchen0823** [comment]
I need to order purchase item code

**Comment by claywar** [comment]
Please ensure that you have updated and rebuilt your code.  This issue was resolved for characters > than the first slot  by #1951

**Comment by xuchen0823** [comment]
@claywar hello me need !food How to set the purchase code

**Comment by TeoTwawki** [comment]
> hello need GM command buy with you script text to find one @

## **请不要删除模板**
如果你删除模板，我不会帮你



----
translation for BUG:
```
<!-- 删除空格并在方[]括号之间放置'x'标记或保存后单击复选框以确认以下几点：-->
<!-- （应该是这样的：- [x] 我有...）-->
- [x] 我已经关注这个例子，如果需要不破坏格式，我会再次编辑，否则我会被忽略
- [ ] 我已经搜索了现有的 [issues](https://github.com/LandSandBoat/server/issues) 以查看问题是否已被打开，并且我已检查提交日志以查看问题是否已解决 因为我的服务器上次更新
- [ ] 我已阅读并理解 [贡献指南](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## 受问题影响的分支 <!-- 更改存在问题的分支（如果相关）-->

`基地`

＃＃ 重现步骤

<!-- 在此处添加重现步骤 -->

## 预期行为

<!-- 在此处添加预期行为 -->
```

translation for NEW FEATURE:
```
<!-- 删除空格并在方[]括号之间放置'x'标记或保存后单击复选框以确认以下内容：-->
<!-- (应该是这样的:- [x] 我有...)-->
- [x] 我已经按照示例进行了，如果需要我会在不破坏格式的情况下再次编辑它，否则我将被忽略
- [ ] 我已经搜索了现有的 [issues](https://github.com/LandSandBoat/server/issues) 以查看问题是否已被打开，并且我已经检查了提交日志以查看问题是否有 已解决为 I 服务器上次更新
- [ ] 我已阅读并理解 [贡献指南](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## 描述特征

<!-- 在此处添加对该功能的描述，如果需要，还可以添加指向视频、wiki、促销公告等的链接-->
```

**Comment by TeoTwawki** [comment]
> @claywar hello me need !food How to set the purchase code

我想你想要 `!addeffect` 食物是状态效应
(I think you want `!addeffect` food is a status effect)

**Comment by xuchen0823** [comment]
我想设置一个 gm 命令 !food 可以购买吃的 以及物品 的代码

**Comment by xuchen0823** [comment]
merit points and job points Where to start the command
