### ISSUE TITLE
🐛 Magical Avatar BPs dont deal damage

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#2014]
![image](https://user-images.githubusercontent.com/65316697/173886482-1c270159-dd2e-4c44-8bd4-1c10d12cb4bc.png)

_Originally posted by @beneliezer in https://github.com/LandSandBoat/server/issues/1983#issuecomment-1156730643_

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Use magical avatar BP (such as Thunder II), deal 0 damage

## Expected behavior

Deal non-zero damage

**Comment by WinterSolstice8** [comment]
EDIT: this is not the case. see #2023
~~Issue originates from magical avatar BP code, mobMagicalMove now returns a table.~~

**Comment by RAIST5150** [comment]
Confirmed on xiweb, running base current as of last night.

Would note that meteorite (Carbuncle magic blood pact) which has it's script in the same folder but does not use mobMagicalMove does proper damage (just landed 577 on an Eschan Phuabo without swapping out of my meleeing set on 99 SMN).

**Comment by RAIST5150** [comment]
Upon further investigation, it may be something more or other than mobMagicalMove?

Ramuh's Thunderspark was also landing for 0 damage with over 1500TP on hand when called on the same Eschan Phuabo's.  That lua does not call mobMagicalMove, but uses AvatarPhysicalMove.

Meanwhile, Chaotic Strike (also using AvatarPhysicalMove) was able to break 3k damage on them.

**Comment by WinterSolstice8** [comment]
Should be fixed by #2023

**Comment by RAIST5150** [comment]
Just confirmed changes worked for Ramuh after xiweb just rebuilt.

In starter area, thunderspark (3873) and Thunder II (947).

**Comment by WinterSolstice8** [comment]
Thanks for testing!
