### ISSUE TITLE
Can not complete nation trust quest.

### ISSUE THREAD

**Issue by jeffnavy14** [DerpyProjectGroup/topaz#2022]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Talk to Clarion Star
Talk to Naji
Spawn Trust North AND South Gust
Go back to Naji, Does not acknowledge that starter trust was spawned 

## Expected behavior

This appears to effect all of the starter quests, I have both tried this on my live and test server after multiple complaints.

**Comment by jeffnavy14** [comment]
It appears to be something I did wrong with my build

**Comment by Hinekri** [comment]
m:addOverride("xi.globals.spells.trust.naji.onSpellCast", function(caster, target, spell)
    local bastokFirstTrust = caster:getCharVar("Quest[1][92]Prog")
    local zone = caster:getZoneID()

    if
        bastokFirstTrust == 1 and
        (zone == xi.zone.NORTH_GUSTABERG or zone == xi.zone.SOUTH_GUSTABERG)
    then
        caster:setCharVar("Quest[1][92]Prog", 2)
    end

    local trust = caster:spawnTrust(spell:getID())


local power = trust:getMainLvl()
	trust:addMod(xi.mod.DEF, power)
	trust:addMod(xi.mod.MDEF, power)
	trust:addMod(xi.mod.ACC, power*9)
	trust:addMod(xi.mod.ATT, power)
      trust:addMod(xi.mod.WSACC, power*3)
end)

I used the module option to give this trust some much needed stat boost, in doing so it stopped the Naji.lua from reporting the quest var under the 
spell_object.onSpellCast = function(caster, target, spell). 

I added the questvar line to the module info - works now with the custom options (if anyone else in the same situation).
