### ISSUE TITLE
🐛 (Non-Issue) Windower: Produce Packet to Trigger Gearswap Aftercast

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#2028]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Enter a city (Port Bastok and Northern Sandoria confirmed to have this symptom)
2. Load a Gearswap LUA that, for cure, has a precast with Body A, a midcast with no Body, and an idle set with Body B
3. Execute the command "//gs showswaps" to have gearswap print the gearswaps to your chat log
4. Cast "Cure" on yourself
5. Notice that the precast triggered and printed to chat _(the needed packet was sent to the client?)_ and **Body A is equipped**
6. Notice that the midcast triggered and printed to chat _(the needed packet was sent to the client?)_
7. Notice that the aftercast DOES NOT trigger or print to chat _(the needed packet WAS NOT sent to the client?)_ and **Body A is still equipped (Body B was not equipped)**

## Expected behavior

Upon completing the "Cure" spell the server would do what's needed to trigger Gearswap to process aftercast and equip the idle set, equipping Body B.

**NOTE:** _This was just a misunderstanding on mote's lib's functionality; I needed to put valid gear in my sets.idle.Town. This symptom only occurred in town because of that context._

**Comment by zach2good** [comment]
Related: https://github.com/LandSandBoat/server/issues/2019

**Comment by Dev-Roland** [comment]
I know this was mentioned in https://github.com/LandSandBoat/server/issues/2019 but I thought it would be good to keep it separate so that it can be addressed on its own, as it's a high-impact bug since Gearswap is probably the most useful Windower feature. As is, this leaves the player in their midcast gear, which is especially problematic when they have PDT as their idle set because they're on content where they need it.

**Comment by WinterSolstice8** [comment]
![image](https://user-images.githubusercontent.com/60417494/174112683-fe767914-fac7-4a2c-81f1-a154cdbbda1a.png)
Seems to work for me?

**Comment by WinterSolstice8** [comment]
For reference, I checked that with `//gs debugmode` on

**Comment by Dev-Roland** [comment]
Thanks, I noticed conflicting results myself. I first noticed this symptom while in town and it made me think of the gearswap aftercast-issue comment that was posted in the windower forums yesterday and I so posted this issue. But later I noticed that aftercast seemed to work while in a dungeon.

So... This issue appears to be present in towns. It's possible it could be elsewhere, too, I guess. When I cast cure in town I'm left in my precast body. My precast and aftercast have differing bodies in them, but there is no body in the midcast, which makes this easy to spot when casting in town without stylelock on.

I've posted much better repro instructions now. Sorry for the lack of detail and over-broad scope of the original post.

**Comment by WinterSolstice8** [comment]
Ah, okay. There's something more. I'll dig after work. Thanks!

**Comment by WinterSolstice8** [comment]
Can't produce, using WAR/WHM with a Mote based lua, debugmode on, showswaps on, using cure in port bastok

see video with some cool fafnirs hanging out in the back (I realized just now you can't see the arrow change but it's in the log):

https://user-images.githubusercontent.com/60417494/174464438-828e556e-d2d6-41b9-88ee-926cf5b4099b.mp4

relevant sets:
```
	sets.precast.FC.Cure =
	{
		main="Claymore",
		sub="Disciple Grip",
		range="Mizukage-no-Yumi",
		ammo="Wooden Arrow",
		head="Bronze Cap",
		body="Bronze Harness",
		hands="Bronze Mittens",
		legs="Bronze Subligar",
		feet="Bronze Leggings",
		neck="Leather Gorget",
		waist="Warrior's Belt",
		left_ear="Sardonyx Earring",
		right_ear="Sardonyx Earring",
		left_ring="Sardonyx Ring",
		right_ring="Sardonyx Ring",
		back="Wolf Mantle",
	}
	
	sets.midcast.Cure =
	{
		main=empty,
		sub=empty,
		range=empty,
		ammo=empty,
		head=empty,
		body=empty,
		hands=empty,
		legs=empty,
		feet=empty,
		neck=empty,
		waist=empty,
		left_ear=empty,
		right_ear=empty,
		left_ring=empty,
		right_ring=empty,
		back=empty,
	}


	-- Idle sets
	sets.idle = 
	{
		main="Greataxe",
		sub="Tenax Strap",
		range="Artemis's Bow",
		ammo="Bone Arrow",
		head="Faceguard",
		body="Scale Mail",
		hands="Scale Fng. Gnt.",
		legs="Scale Cuisses",
		feet="Scale Greaves",
		neck="Pile Chain",
		waist="Augmenting Belt",
		left_ear="Amethyst Earring",
		right_ear="Amethyst Earring",
		left_ring="Amethyst Ring",
		right_ring="Amethyst Ring",
		back="Rabbit Mantle",
	}
```

**Comment by WinterSolstice8** [comment]
What were the exact items failing to swap? Maybe it's it's some isolated incident and not a general failure.

**Comment by WinterSolstice8** [comment]
Re-read the repro steps and I tried without a midcast:

https://user-images.githubusercontent.com/60417494/174464547-fc7a27a0-bd9d-45d2-b9d9-30459ca9f7b7.mp4

Seems no change

**Comment by Roland-J** [comment]
That would be because there is no issue here, this was a misunderstanding on my part.

The reason this symptom occurs in town for me is because A) mote's lib has a unique idle set for town - _sets.idle.Town_ - and B) my job.lua comes from a template and its sets.idle.Town still has the template's sample equip in it that my character doesn't have, causing it to not be able to equip anything when it ran; it was being triggered but simply had nothing in it that it was able to equip.

Sorry for the misunderstanding. Where's my dunce hat? :)

**Comment by Dev-Roland** [comment]
That would be because there is no issue here, this was a misunderstanding on my part.

The reason this symptom occurs in town for me is because A) mote's lib has a unique idle set for town - sets.idle.Town - and B) my job.lua comes from a template and its sets.idle.Town still has the template's sample equip in it that my character doesn't have, causing it to not be able to equip anything when it ran; it was being triggered but simply had nothing in it that it was able to equip.

Sorry for the misunderstanding. Where's my dunce hat? :)

**Comment by WinterSolstice8** [comment]
No hat, but you get a cookie for making the issue and solving it yourself!

![image](https://user-images.githubusercontent.com/60417494/174843023-b80417e2-9923-439a-9a87-776c77416caf.png)

**Comment by Dev-Roland** [comment]
As for real issues, I am seeing a delay in aftercast from LSB, where there's no delay in retail, when I replace the spell ID of an outgoing nuke. I can't tell what's going on behind the scenes, but something appears to be causing the spell's aftercast to go off when it would have for the original spell rather than the final spell selected. Xaver tested this in retail for me and confirmed that the aftercast was not delayed in retail in this scenario when using the same addon to demote the nuke. Thoughts?

https://user-images.githubusercontent.com/106891580/174843002-ff66fd61-974a-4d9e-81f0-4961238fb663.mp4

.

**Comment by WinterSolstice8** [comment]
oooh that is interesting, I would assume there would be no difference if the spell ID is changed because it's your client changing the ID.. hmmm.... try downgrading T3 to T2 and a different element, just curious if it's one spell ID or not. We have a massive amount of tables that might have arbitrary delays that could be wrong.

**Comment by Dev-Roland** [comment]
So far, I haven't seen any normal casts that equip recasts at the wrong time. It's just when I demote the nuke (make the client change the ID) that it gets stuck into the original spell's delay/casting time. Again, for anyone jumping in at this point, doing the same thing on retail does not produce any delay and aftercast gets equipped at the correct time for the final spell.

Yeah, I confirm that it appears to be an issue that affects all spells, or at least the thunder family. I doubt it would be limited to thunder only, though.

All these spells end up equipping aftercast at the time that the original spell would have, which is typically 0.5-2 seconds after aftercast should equip for the final spell.
Original Spell > Final Spell
T5>T4
T4>T3
T3>T2

**Comment by WinterSolstice8** [comment]
Can you make a separate issue for this? I can check it out some time this week

**Comment by Dev-Roland** [comment]
Done, thanks! https://github.com/LandSandBoat/server/issues/2066
