### ISSUE TITLE
🐛 Superior Level show and calculated incorrectly

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#2029]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

- Initial Occurrence - Leveled all job point categories to max on DRK and checked Su LvL, where it shows Su lvl 15 (as if all leves added together instead of override one another) No master stars displayed either
![DRK lvl 99 Su 15](https://user-images.githubusercontent.com/64471323/174095803-e098dc14-24f1-4b2b-9552-33ee334a7140.jpg)

- Leveled all job points on PUP Su counter climbed as expected with each increase 1-5 and master stars appeared on 2100 job points spent. 
![PUP lvl 99 SU 0](https://user-images.githubusercontent.com/64471323/174095807-575eb801-41f3-4434-82d1-4094318de7da.jpg)
![PUP lvl 99 Su 5 Master](https://user-images.githubusercontent.com/64471323/174095813-f1b3ba59-724f-4eef-9557-572e95293aca.png)

I have only tested this on DRK and PUP so far but i will check all other jobs this evening when i have more time.

## Expected behavior

Su levels increase 1 to 5 and override one another.

**Comment by TeoTwawki** [comment]
> Su levels increase 1 to 5 and override one another.

Should actually be displaying your highest SU unlocked by your JP and not what you have equipped. My main job on retail shows Su3 even naked because that's what job points I got up to on it.

**Comment by Aeisu** [comment]
I started checking Job gifts and what Su levels were given and I found MNK had a whopping Su lvl of 48 so i went digging into the sql files
sql/job_point_gifts.sql - found the problem with three of the values for Su level
Line 140 INSERT INTO `job_point_gifts` (`jobid`, `jp_needed`, `modid`, `value`, `desc`) VALUES (2, 1200, 997, 44, 'MNK_Superior 4');
Line 484 INSERT INTO `job_point_gifts` (`jobid`, `jp_needed`, `modid`, `value`, `desc`) VALUES (8, 50, 997, 11, 'DRK_Superior 1');
Line 980 INSERT INTO `job_point_gifts` (`jobid`, `jp_needed`, `modid`, `value`, `desc`) VALUES (15, 500, 997, 3, 'SMN_Superior 3');

I looked for consistency of values and all Mod 997 values are 1 so i changed these values and went back to check and both DRK and MNK went back to normal operation for shown Su lvl and Master stars appeared properly. 
I also checked SMN to be thorough and it worked normally as well

I have never done a pull request so i will elave that up to the experts, i'm just glad i could find the problem and fix it ^^;
