### ISSUE TITLE
🔨 Support for Dynamic Entities in Instances

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#2030]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Dynamic entities currently don't work in instances, hook them up to instances.

**Comment by KnowOne134** [comment]
no but you can make instance:insertAlly(groupid)
