### ISSUE TITLE
🐛 Incorrect Max CP Per Kill Ceiling

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#2032]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

_(Observed on the Omicron server)_
1. Build a high chain on apex mobs
2. Notice that the CP-per-kill caps out around 25k

## Expected behavior

The CP-per-kill would slowly rise to the retail 65,535 cap. ([Wiki](https://ffxiclopedia.fandom.com/wiki/Job_Points#:~:text=The%20lowest%20possible%20amount%20of%20Capacity%20Points%20received,Job%20Point%20for%20every%2030%2C000%20Capacity%20Points%20earned.))

**Comment by claywar** [comment]
Most bonuses have not been implemented, and without those it is most likely not possible

**Comment by TeoTwawki** [comment]
note that during certain campaigns on retail you can go beyond that cap, but the message will still call it 65535

**Comment by Dev-Roland** [comment]
Thanks, I'll go ahead and close this issue in that case. It can be revisited once all the bonuses have been implemented.
