### ISSUE TITLE
🐛 Dynamic Mobs GetMobByID no longer works

### ISSUE THREAD

**Issue by RunAwayDSP** [DerpyProjectGroup/topaz#2047]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Pull Request #2031 broke the ability to use GetMobByID() on dynamic mobs 

## Expected behavior

use GetMobByID()  and return a value

there needs to be additional shifting done to adjust for the shift done in #2031. I dont know what shifts and where though.

**Comment by zach2good** [comment]
Tagging to other issue: https://github.com/LandSandBoat/server/issues/2019
