### ISSUE TITLE
🐛 Chocobo digging fatige not working (or I'm missing something)

### ISSUE THREAD

**Issue by m241dan** [DerpyProjectGroup/topaz#2051]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

This is more of a, "I'm not crazy?" issue. I think these two lines being Local Vars is a problem, but maybe I'm crazy. Players have reported hitting fatigue, then zoning, and being able to go again.

https://github.com/LandSandBoat/server/blob/36a5fe3be1c76881dbf51181c19d3afd7c153ea2/scripts/globals/chocobo_digging.lua#L811

https://github.com/LandSandBoat/server/blob/36a5fe3be1c76881dbf51181c19d3afd7c153ea2/scripts/globals/chocobo_digging.lua#L829

## Steps to reproduce

1. Dig to the max
2. Zone
3. Dig again because your "[DIG]LastDigTime" is reset to 0, so of course it will be less than last midnight, it's 0.

## Expected behavior

Zoning does not do this.

**Comment by Xaver-DaRed** [comment]
That is correct (as in, you aren't crazy, it happens). This is in process of being fixed

**Comment by m241dan** [comment]
> That is correct (as in, you aren't crazy, it happens). This is in process of being fixed

Any ETA on this? I mean, seems like it's just changing those two lines? Or is the whole system being overhauled?

**Comment by Xaver-DaRed** [comment]
ETA? That's funny.
Anyway...
https://github.com/LandSandBoat/server/pull/1780
The overhaul route for this.

**Comment by m241dan** [comment]
Well, not very helpful in the interim then, eh?

Should I submit a small patch that just fixes this "for now" then?

**Comment by m241dan** [comment]
Infinite digging is MEGA abusable on era servers.

**Comment by Xaver-DaRed** [comment]
Agreed, that's why we are overhauling the whole system. Players wont be happy.
But sure, feel free to post a patch if you want.
Just letting you know where the WIP was.

**Comment by m241dan** [comment]
Kk. Will do, I just didn't want to submit it if it was instantly going to
be rejected because of wip.

**Comment by TeoTwawki** [comment]
> Infinite digging is MEGA abusable on era servers.

I was under the impression just flipping to a char var from a localvar was how era servers were handling it atm. and inf dig isn't that bad - the daily limit wasn't there in 2004, and on my server I prefer it to stay inf.

I will approve of a mini patch for it tho

**Comment by TeoTwawki** [comment]
I will approve of a mini patch for it tho

**Comment by TeoTwawki** [comment]
#2058
