### ISSUE TITLE
🐛 Presto effect remains after skill use

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2062]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Use Presto followed my multiple steps and the effect persists/applies long after it is intended to.

## Expected behavior

Effect should end immediately following the next step used. (Same as abilities like Trick Attack)

**Comment by claywar** [comment]
Resolved by #3279
