### ISSUE TITLE
🐛 Corrupt player db entry crashes server

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2075]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

This is the best guess we could find in the past hour trying to pinpoint the issue. We did a merge with everything commited here up to 1 hour ago and immediately had problems. First the primary LS had a problem: someone noticed the colors were no longer matching and we shortly after had first crash. 

Logins following has these two errors:
![unknown4](https://user-images.githubusercontent.com/106329891/174939089-88b2d497-7ad9-498d-bf45-f6b756715fc6.png)
![unknown3](https://user-images.githubusercontent.com/106329891/174939124-4f87b80c-1a97-4c95-bb85-8507d53de17e.png)

So we removed the LS and GMs started to login after reboot to see what was going on, which prompted constant crashing. ~blahblah~ and we found out as long as no GM permitted char logs in it seems to be ok. The moment any level GM connected map goes down.
![unknown](https://user-images.githubusercontent.com/106329891/174939321-ff5a0b95-01dd-4f89-8158-702dcb1b97dc.png)
![unknown1](https://user-images.githubusercontent.com/106329891/174939329-dc18757d-4b15-4e5d-b12b-b1490d1b5623.png)

[xi_map.exe_21-6_20-1-39.log](https://github.com/LandSandBoat/server/files/8954233/xi_map.exe_21-6_20-1-39.log)

 Still hunting for other possible causes and how to clear, help appreciated.

(Also have a DMP file which it will not let me drop in here.

**Comment by Hinekri** [comment]
Ok it's not GM permissions, its progression. We can login all the new characters and alts without missions completed we want, one GM actually had a flagged alt with nothing done and was able to log in. I have a craft alt with all crafts max / all jobs 99 / master JP on 1 job and it has no problem.  

Other players logging in with deeper mission progression instantly reboots the server, tested this multiple times ~ clean for 30 mins / instant reboot swapping from alt to main.

**Comment by WinterSolstice8** [comment]
check that particular characters entries in the DB. there's some garbage looking results from the log file

```   Local char* quests = "ÛQ3	«œôkb°ÚÎB"
    Local char* zones = "°±îKÚÑÅ÷]±<-ôš"‘wfþØ[?A"
    Local unsigned int length = 0xB9D19AD6C0
    Local char* keyitems = "ßõ4‰Û/Õ.AÇ»$ñæ!ä©\,Jr”œ"
    Local char* abilities = "W"
    Local char* campaign = "Sçe¥Aá€+EÇ§I…çÙ—0ô`/¬"
    Local char* eminence = "Npô!è0Žðwû©ËÌŠ=sÍ ÿ¿³ñ"
    Local char* titles = "sP-"Ÿx#N¨:»&ˆöè®"
    Local char* assault = " é„âý=ç<áJ°u[O¯÷Öjx`-¢¬’4²Mô"
```

**Comment by TeoTwawki** [comment]
db updated via db tool after pull? and rebuilt I presume. Just checking. I'd bet there were more errors than you caught buried in your log after that startup.

**Comment by Hinekri** [comment]
Yes more than once.

**Comment by jeffnavy14** [comment]
After hours of trouble shooting, I was able to get the DB back up and running via the DBtool restore/import option. Only lost players about ~5 hours of progress but its better than weeks. I still do not know what happened.

**Comment by Hinekri** [comment]
*shrug* We took LSB update and something just snapped, I doubt we can ever reproduce exactly what happened but as he said rolled back to a pre-update DB save and got us back on track. Going to close but ill ref here if it ever happens again [fingers crossed it doesnt]. Ty.
