### ISSUE TITLE
🐛 Cannot Trigger Cutscene to Finish RoV 2-6 Desert Winds

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#2114]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Start this process on a character A) with 0 ToAU progress B) that is on [RoV 2-4 Numbering Days](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-4), and C) that is on [PM 3-3 The Road Forks](https://www.bg-wiki.com/ffxi/Promathia_Mission_3-3) _(has only started Sandoria path via zoning into Sandoria)_
2. Click Upper Jeuno's Marble Bridge Door, which starts [RoV 2-5 Inescapable Binds](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-5)
3. Go to the Tenshodo, speak to Faursel, and choose the **"Where is Tenzen"** option to start [RoV 2-6 Desert Winds](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-6)
4. Zone into Aht Urgan Whitegate, receive no RoV 2-6 zone-in cutscene.

_Bonus steps...
5. Zone Into Aht Urgan and also click the Imperial Whitegate **between each step below** to try and fail to trigger [2-6](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-6) and [2-9](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-9) cutscenes.
6. Progress to ToAU 12
7. Finish PM 3-3
8. Finish PM 3-4
9. Finish PM 3-5_

## Expected behavior

Since there is no hindering ToAU or PM progress on said player, the RoV 2-6 cutscene is received upon zoning into Aht Urgan Whitegate, starting [RoV 2-8 The Endless Sky](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-8) (due to the player's original lack of ToAU progress)

**Comment by Dev-Roland** [comment]
On a side note, the [Desert Winds script](https://github.com/LandSandBoat/server/blob/base/scripts/missions/rov/2_06_Desert_Winds.lua) appears to require PM 6-5 "The Warrior's Path" completion, whose completion isn't mentioned as a req anywhere in the wikis for RoV missions; the highest PM completion req listed there is 3-3. However, the wikis do often mention for the player not to be **on** certain PM missions, but no such req is listed for this one.

Perhaps the concept of "_ensure the player **isn't on** x mission(s)_" was mis-coded to "_ensure the player **has completed** x mission(s)"_.

**Comment by claywar** [comment]
Warrior's Path is used for an event parameter, and is not blocking for your issue.  The 'concept' that you mention is xi.rhapsodies.charactersAvailable()

**Comment by Dev-Roland** [comment]
Thanks! It's hard for me to read this code without knowing what goes on in player:updateEvent. All I can see is the parameters going into it and assume what they are used for. This learning curve is real. Thanks @claywar! I wonder what's blocking my issue, then.. /shrug

**Comment by claywar** [comment]
Just reviewed the mission scripts, and the only way this _should_ fail is if xi.rhapsodies.charactersAvailable(player) returns false.

**Comment by Dev-Roland** [comment]
OK, I think I get that one. server/scripts/globals/rhapsodies.lua contains that charactersAvailable function, which uses its own requiredCharacters table to check which characters are required for the current mission. Since my mission log lists Desert Winds as my current RoV mission, and since that table lacks an entry for Desert Winds, wouldn't it just return true on line 389 and let me progress, rather than block, my progress?

@kaincenteno is also stuck on this mission, by the way, indicating that it's not just me.

**Comment by Dev-Roland** [comment]
I see that [RoV 2-5 Inescapable Binds](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-5)'s [mission script](https://github.com/LandSandBoat/server/blob/base/scripts/missions/rov/2_05_Inescapable_Binds.lua) has two possible endings.

**Natural (local) Ending:** Complete (line 75) upon Whitegate zone-in (line 37-70) and reward [RoV 2-7 Ever Forward](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-7) (line 18) (skips RoV 2-6)
**Faursel (external) Ending:** Complete [The Road to Aht Urgan](https://www.bg-wiki.com/ffxi/The_Road_to_Aht_Urhgan) quest, whose [external script](https://github.com/LandSandBoat/server/blob/base/scripts/quests/jeuno/The_Road_to_Aht_Urhgan.lua) moves the player to [RoV 2-6 Desert Winds](https://www.bg-wiki.com/ffxi/Rhapsodies_of_Vanadiel_Mission_2-6) (line 100)

I've only ran into this RoV 2-6 wont-trigger-cutscene dead-end when using the Faursel Ending, for what it's worth. The natural ending worked fine for me last time and I was also in the same exact CoP spot at that time.

**Comment by Dev-Roland** [comment]
Could the issue be with the [player:updateEvent()](https://github.com/LandSandBoat/server/blob/5c6a99b1f4b116edade7bcc8ebaa582e1e8b7289/scripts/missions/rov/2_06_Desert_Winds.lua#L66) call being blocked from triggering event 165's CS due to some other unstated prereqs? After all, [the script itself states that event 164 was observed in the retail caps](https://github.com/LandSandBoat/server/blob/5c6a99b1f4b116edade7bcc8ebaa582e1e8b7289/scripts/missions/rov/2_06_Desert_Winds.lua#L32).

Are the events baked into the game's files or into the server? I haven't found them defined server-side yet. It'd be nice to see what logic event 165 and 164 contain.

**Comment by Dev-Roland** [comment]
I'm still affected by this issue, do we have any info on what could be causing this? The lack of this character having a documented blocking factor makes it seem like I've run into an undocumented blocker.

**Comment by Dev-Roland** [comment]
I confirm that I was able to trigger the Desert Winds CS right after, but not before, we merged 2312. Thanks @claywar!
