### ISSUE TITLE
🐛 Players getting stuck outside map after crashing. 

### ISSUE THREAD

**Issue by TabulaRasaXI** [DerpyProjectGroup/topaz#2123]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

example from a player 
https://www.youtube.com/watch?v=fACr5swUyc4

1.Zone into any zone
2. wait any duration
3. Client crash from what seems to be any source.
4. player logs back in, usually outside of map. POS coords match with the previous zones zonelin to current zone. Looks like Current zone and previous zone in char sql show the same zone after they log back in.  

## Expected behavior

after crash you should be at the zoneline of the zone you just came from.

**Comment by Dev-Roland** [comment]
Sounds like the same issue as https://github.com/LandSandBoat/server/issues/2122 that was also just submitted. What timing, lol!
