### ISSUE TITLE
🐛 New Players not getting items

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#2140]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 
Currently what I have c4aeb1a and I think started possible after 7068053

`base`

## Steps to reproduce

Create New Char's

New Char does get CS

The New Char does not get New Adventurer Title, Starting Gil, Adventurer coupon or starting Gear

Tested multiple race and starting cities

## Expected behavior

Any new char created should get New Adventurer icon "?" and Title New Adventurer, also should get Adventurer coupon and starting gil

**Comment by zach2good** [comment]
Do you have any more details? maybe if there was anything in your logs?

I just started a new Galka in Bastok, got the CS, got the items, got the title:
![image](https://user-images.githubusercontent.com/1389729/176256665-8a53cdf6-b4fa-43d7-b5b6-04b624d3bb7c.png)

**Comment by Mortalelite** [comment]
Ok think I might fixed it. I did repair game files, after you mention worked for you, figure worth a shot to try. Could been some dats for icons that could have affected it. Tested without the dats and it worked. Could been something maybe messed up game files. But incase anyone has that issue maybe repairing game files might help.
