### ISSUE TITLE
🐛 How to filter NavMesh and warning messages from log window

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2165]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
I have the settings configured below, but do not seem to take effect. Am I doing something wrong?

```
xi.settings.logging =
{
    TRACE_NAVMESH = false,
    TRACE_PACKETS = false,
}
```
## Expected behavior
These messages should not appear in the log window.

**Comment by zach2good** [comment]
There's nothing wrong with your config or the filters themselves, we've just not hooked up the filtered loggers to the things that generate the logs -> we need to sit down and decide what is filterable 'spam' and what are errors that need to be logged all the time.

As well as splitting out different categories of trace: navmesh, pathing, sql, packets, actions etc

**Comment by zach2good** [comment]
Related: https://github.com/LandSandBoat/server/issues/1972
