### ISSUE TITLE
🐛 Script error on server startup

### ISSUE THREAD

**Issue by whasf** [DerpyProjectGroup/topaz#2166]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Update to d1949a88ac8551701fb0a235fd9ee850cb26f99a

## Expected behavior

I expected the server to start  normally

Error:
[map][error] ./scripts/globals/survival_guide.lua:17: attempt to index field 'main' (a nil value)
stack traceback:
	./scripts/globals/survival_guide.lua:17: in main chunk (luautils::init:227)

**Comment by zach2good** [comment]
Any other details? I'm not getting this locally, and it's not happening in CI

**Comment by Mortalelite** [comment]
I have did the latest PR and was not getting any error with Survival Guide

**Comment by whasf** [comment]
I found the problem, it was on my side. I kept a file named **/scripts/globals/settings - copy.lua**, it is a copy of the settings file for historical reasons. It seems somewhere some logic changed and you're loading *ALL* lua files now? Either way, I changed the extension of the file to ".luaz" and the startup errors are gone.

**Comment by zach2good** [comment]
Logic changed here: https://github.com/LandSandBoat/server/pull/1945

We load all the default settings files to populate our defaults in cpp land, then we do the same with the user's settings, then we publish them back to Lua for parity

**Comment by zach2good** [comment]
(a reason we load all *.lua files in any directory that can hold lua files is because of the hot-reloading)
