### ISSUE TITLE
RNG unlock quest does not allow the Key Item to be acquired

### ISSUE THREAD

**Issue by mrhappyasthma** [DerpyProjectGroup/topaz#217]
This line is non-nil, so the logic on tiger death never triggers:
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Sauromugue_Champaign/mobs/Old_Sabertooth.lua#L15

Not sure how this worked before, but must have broken at some point in recent history.

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by claywar** [comment]
This is as designed.  This quest is not a kill-the-NM fight, but rather you must be in range and observe it dying naturally.

If anything, a status should be set on spawn for it to naturally die within 3 minutes 
ref: https://ffxiclopedia.fandom.com/wiki/The_Fanged_One

**Comment by mrhappyasthma** [comment]
The guide I followed did not clarify how you weren't supposed to "kill it". i.e. let it die naturally.

Re-testing. This may be WAI.

**Comment by mrhappyasthma** [comment]
Okay yeah. The search result was just unclear. This does work as expected if you wait for it. And does not give the key item if manually killing it (per design).

Thanks for the quick reply! Closing.
