### ISSUE TITLE
🐛 Crafting signature bugged with character names twelve letters or greater

### ISSUE THREAD

**Issue by HaxPrime** [DerpyProjectGroup/topaz#2182]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

A character with an in game name of twelve characters or greater, perform a synthesizes with a high quality crystal. When attempting to trade this crafted item with a signature, the crafted item appears in the trade window with a signature of [PBfSv8UF], it should read as [Sweetwednesday]. Finalizing the trade will cause item to disappear from both players.

Furthermore, when listing items in the players bazaar crafted with a high quality crystal and an in game name of twelve letters or more will cause the listed item to be non purchasable.

Experienced the same issues with characters named twelve letters and fourteen letters long.

## Expected behavior

Items crafted with high quality crystals from characters with names twelve letters or greater should be tradable or purchasable from  their bazaar.

**Comment by WinterSolstice8** [comment]
I could not produce the item disappearing part  -- It simply showed up with the correct signature on my client.

Didn't notice the bazaar issue until I made the PR just now, but I tried it with the changes in place and looks OK.

Thanks for the report. I was suspicious about character string lengths being hardcoded for a while.

**Comment by WinterSolstice8** [comment]
Let us know how it goes if we need to take a second look.
