### ISSUE TITLE
🐛 Cannot progress through CoP 8-2 "A Fate Decided"

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2188]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Upon reaching CoP Mission 8-2 "A Fate Decided", the Escort portion can be completely bypassed by running to the NM (Ix'ghrah) spawn point. After fighting the NM, players should be able to click the Cermet Portal again for a cutscene, but this doesn't happen. (It doesn't seem to increment the "PromathiaStatus" char var. This results in the player being able to fight the NM over and over without progression.

## Expected behavior

After killing the NM, cermet portal should give a cutscene.

**Comment by claywar** [comment]
Chapter 8 has not been audited at this time.  That status var is deprecated for all previous missions, and I won't doubt that the final chapter is broken at this time.

**Comment by CatsEyeXI** [comment]
> Chapter 8 has not been audited at this time. That status var is deprecated for all previous missions, and I won't doubt that the final chapter is broken at this time.

Thanks, I'll advise players that this cannot be completed at this time.

**Comment by Mortalelite** [comment]
I know there is a PR atm but not sure of progress 


https://github.com/LandSandBoat/server/pull/2101
