### ISSUE TITLE
`xi.zone` contains 4 duplicate keys for `RESIDENTIAL_AREA`.

### ISSUE THREAD

**Issue by mrhappyasthma** [DerpyProjectGroup/topaz#221]
I believe the Lua behavior will be to just accept the last entry for the duplicate key.

Currently it's set to four values `189`, `199`, `214`, `219`. I believe `219` will be used.

https://github.com/LandSandBoat/server/blob/094ec9f022916bc86b8d0efee166b626ec560c2c/scripts/globals/zone.lua#L289-L319

**Comment by claywar** [comment]
Just to confirm from CI that this is indeed the case:
```
Checking scripts/globals/zone.lua                 3 warnings

    scripts/globals/zone.lua:289:5: (W314) value assigned to field RESIDENTIAL_AREA is overwritten on line 299 before use
    scripts/globals/zone.lua:299:5: (W314) value assigned to field RESIDENTIAL_AREA is overwritten on line 314 before use
    scripts/globals/zone.lua:314:5: (W314) value assigned to field RESIDENTIAL_AREA is overwritten on line 319 before use
```
