### ISSUE TITLE
🐛 Character Packets not updating until you move.

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#2228]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Make two characters. 
2. Don't move one of them.
3. Approach from further than 50 yalms on the second character.
4. See the first character on the second, but the first character doesn't see the second.
![image](https://user-images.githubusercontent.com/6257062/178021891-15b52214-1f78-4f12-8dc5-d36c82a37f64.png)
![image](https://user-images.githubusercontent.com/6257062/178021914-d92bb266-2cc7-4e20-a73a-79b83c4aad5c.png)

5. Move first character which causes packets to finally update, and then bam second character appears.
![image](https://user-images.githubusercontent.com/6257062/178022042-d83afb9d-cb3a-4cfe-ae79-932be80667b1.png)

## Expected behavior

Characters should appear normally without having to move, once they come within the 50 yalm render distance.

**Comment by Mortalelite** [comment]
I have tested this also and getting same results. Also doing !hide on and off did allow to see other Char again, when testing this

**Comment by WinterSolstice8** [comment]
> I have tested this also and getting same results. Also doing !hide on and off did allow to see other Char again, when testing this

Do you need to do just one or both?

I have much bigger fish to fry right now but I have an inkling of what's going on. Any more details would be nice.

**Comment by Mortalelite** [comment]
> > I have tested this also and getting same results. Also doing !hide on and off did allow to see other Char again, when testing this
> 
> Do you need to do just one or both?
> 
> I have much bigger fish to fry right now but I have an inkling of what's going on. Any more details would be nice.

Well only one was a GM char, but after moving was able to see other char again, besides also doing !hide command without moving. Was just sharing same thing from above post

**Comment by The-Aerec** [comment]
> > I have tested this also and getting same results. Also doing !hide on and off did allow to see other Char again, when testing this
> 
> Do you need to do just one or both?
> 
> I have much bigger fish to fry right now but I have an inkling of what's going on. Any more details would be nice.

Either.

The player who is not moving needs to do something to force a packet update or the other will never show up.

**Comment by CatsEyeXI** [comment]
we are also seeing this...  for example ill be standing around in lower jeuno, there will be 10 other people there but they won't appear until i move...
