### ISSUE TITLE
🐛 SKILLUP_AMOUNT_MULTIPLIER not being factored

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2237]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

I currently have  SKILLUP_AMOUNT_MULTIPLIER = 2
Historically this has meant that the minimum skillup amount should be for 0.2
Following a change a week or two ago (where crafting skillups broke) it seems the multiplier is no longer being factored in.
Players are able to get 0.1's often.

## Expected behavior

minimum skillup amount should be 0.2

**Comment by TeoTwawki** [comment]
Weird, looks like it's still in place
```cpp
// Do skill amount multiplier (Will only be applied if default setting is changed)
if (settings::get<uint8>("map.SKILLUP_AMOUNT_MULTIPLIER") > 1)
{
    SkillAmount += (uint8)(SkillAmount * settings::get<uint8>("map.SKILLUP_AMOUNT_MULTIPLIER"));
    if (SkillAmount > 9)
    {
        SkillAmount = 9;
    }
}
```
https://github.com/LandSandBoat/server/blob/f750a71effffc4ba9728387a90c7beacc2a08856/src/map/utils/charutils.cpp#L3070

**Comment by CatsEyeXI** [comment]
> Weird, looks like it's still in place
> 
> ```c++
> // Do skill amount multiplier (Will only be applied if default setting is changed)
> if (settings::get<uint8>("map.SKILLUP_AMOUNT_MULTIPLIER") > 1)
> {
>     SkillAmount += (uint8)(SkillAmount * settings::get<uint8>("map.SKILLUP_AMOUNT_MULTIPLIER"));
>     if (SkillAmount > 9)
>     {
>         SkillAmount = 9;
>     }
> }
> ```
> 
> https://github.com/LandSandBoat/server/blob/f750a71effffc4ba9728387a90c7beacc2a08856/src/map/utils/charutils.cpp#L3070

yeah... I held off submitting this for a few days but enough people are making noise now :/

**Comment by CatsEyeXI** [comment]
following a discussion about this on discord, it is my understanding that SkillAmount was changed from a float to unit8 with the settings overhaul. I think the solution in my case was to use a whole number (2) instead of 1.5... I'm comfortable closing this if you LSB is.
