### ISSUE TITLE
🐛 Cannot progress through CoP 1-1 "Rites of Life"

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2266]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

I have had several players over the past few days report that they are unable to progress through this mission.
They recall getting the cutscene in Delkfutt but then Monbereux will not give them a CS or the mysterious amulet.
For what it's worth I think these toons started a few months ago, and things have probably changed since then... I'm just a little confused with the new converted missions as to how I can reset their CoP progress so they can start over (if that is the fix).
## Expected behavior

Monbereux should preset a CS and give mysterious amulet

**Comment by Mortalelite** [comment]
I have tested this on Fresh New Char. Was able to get CS and Keyitem. I would say have them double check see if anything they might of missed, client up to date just incase. Take a screenshot of missions.


Also could try command checkmission or checkmissionstatus to see if helps

**Comment by CatsEyeXI** [comment]
I'm going to close this because we are able to navigate around it by deleting the mission and having the player start over. Not much is lost anyway.
