### ISSUE TITLE
🐛 Mobs should not have a required minimum distance between themselves and their target

### ISSUE THREAD

**Issue by CriticalXI** [DerpyProjectGroup/topaz#2268]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Have a mob actively attacking you
2. Move around within that mob's melee attack range
3. Watch it completely reposition itself to ensure there is a minimum distance between itself and you

## Expected behavior

Mobs should only reposition themselves if they are too close to another mob or you move outside of their attack range. If you move around within a mob's melee range, it should just spin to face you rather than move its body entirely. 

An example of this on retail is from this KV capture: https://www.youtube.com/watch?v=UZZDwYNVgUo&t=251s
If you see Commencal gets drawn in and KV just spins to look at him instead of completely repositioning itself.

This issue has an added side effect in game in connection with draw in. If you trigger draw in repeatedly on a mob, you can cause the mob to back itself up over and over off the bounds of the map. Which then will cause the mob to draw you in out of the map.

**Comment by TeoTwawki** [comment]
> If you move around within a mob's melee range, it should just spin to face you rather than move its body entirely.

Well that's not _entirely_ true. Some of this is dependent on entities model size I think. Many things I have fought on retail will circle me till I am not facing them if I take a half step clockwise which I've sworn aloud at my screen about more than once. I don't think the mob should ever back away from the player though - only towards the player as needed.

**Comment by WinterSolstice8** [comment]
please describe a specific reproduction scenario so we can better understand the problem, ideally with an exact mob, specific distances, etc. these are important for what our code does

I think I see what it might be, but simply saying "mobs should not" is not really helpful. There are several hardcoded distance checks which may make it look like "minimum" distance but I would like to have something specific so I can both reference retail and understand the problem. Thanks.

edit: added more info

**Comment by CriticalXI** [comment]
You can reproduce this in game with any mob that draws in. For example, Tiamat. If you move far enough to get drawn in and don't move your character after the draw in, you'll see that Tiamat will reposition herself entirely. The best explanation I can give from observing it in game is what I said, it seems like mobs require there to be a minimum distance between itself and the target it is attacking.

What I would expect is for the mob to just swivel in place to face its target (like you can see KV does in the video I linked), or in the case of a HNM like Tiamat, attack you with the most appropriate body part in relation to where the player is standing. Not back itself up to look at you directly.
