### ISSUE TITLE
🔨 Deprecate "addCharVar"

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#2273]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

While porting https://github.com/LandSandBoat/server/pull/2067, I noticed that Eden doesn't have `addCharVar` or similar, which: "Increments PC's variable by an explicit amount". 

I think it adds unnecessary bloat the the get/set API and we should get rid of it.

**Comment by claywar** [comment]
Just a heads up. This is used in some quests and missions

**Comment by zach2good** [comment]
Sure, I see that, but either:
- We kill it and replace with a get and then a set + n
- We give it a better name like `incrementCharVar`

**Comment by TeoTwawki** [comment]
> While porting https://github.com/LandSandBoat/server/pull/2067, I noticed that Eden doesn't have addCharVar or similar, which: "Increments PC's variable by an explicit amount".

>
> I think it adds unnecessary bloat the the get/set API and we should get rid of it.

that was my opinion back when it was added, and its only positive was saving you from nesting a get with a +1 in the input of set.

https://github.com/DarkstarProject/darkstar/commit/7e2e45638842224cd21e86635840848e74f90ffe

https://github.com/DarkstarProject/darkstar/pull/6236#issuecomment-540265299

https://github.com/DarkstarProject/darkstar/pull/5694/files#diff-62c746dd4db0dff4d74f6c77f0c257a0fc1dfcdb49125541492c590679aa583bL104

I had a similar option about incrementing/decrementing mob mods, as we normally just set them, unlike regular modifers where we add on effect gain and del on effect loss.

**Comment by TeoTwawki** [comment]
> Sure, I see that, but either:
> 
> * We kill it and replace with a get and then a set + n
> * We give it a better name like `incrementCharVar`

+1 for `incrementCharVar`

**Comment by Mortalelite** [comment]
Would this change anything with setCharVar and getCharVar or that stay the same? Just Wondering

**Comment by TeoTwawki** [comment]
> Would this change anything with setCharVar and getCharVar or that stay the same? Just Wondering

we're all fans of get and set pairings. They'd stay.
