### ISSUE TITLE
Error when trying to open custom menu

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#2293]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Attempt to open Custom Menu and get error
` [07/15/22 12:06:31:559][map][warn] Custom menu for Local was provided an empty string. (luautils::HandleCustomMenu:4724) `

The custom menu would allow you teleport to cities.

Was also getting same error with ` !menu `

Nothing was changed besides updating to latest build

## Expected behavior

Should allow you execute menu command in use

**Comment by zach2good** [comment]
I noticed this when I was experimenting with old branches, are you up to date?

**Comment by zach2good** [comment]
Ah I might have accidentally reverted this, this offset should be 21 instead of 20 (I think)
https://github.com/LandSandBoat/server/blob/87b79e28e897f3880759cb6f1952db35cd1ea6e3/src/map/packet_system.cpp#L5190

**Comment by Mortalelite** [comment]
Yep on latest [87b79e2](https://github.com/LandSandBoat/server/commit/87b79e28e897f3880759cb6f1952db35cd1ea6e3)

**Comment by Mortalelite** [comment]
This possible commit could trigger that ba771d3 ?

**Comment by zach2good** [comment]
Yeah those 20's need to be set back to 21's
