### ISSUE TITLE
Old Wounds quest

### ISSUE THREAD

**Issue by Aslenta** [DerpyProjectGroup/topaz#23]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: freedom

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I started have the The General's Secret quest, but talking to Curilla again, even after zoning, she wont give me the Old Wounds quest. On lvl 90 Warrior, above 240 sword skill.

**Comment by claywar** [comment]
Current implementation does not allow for shuffling effect for interactions.  Need new implementation to allow for other interactions to be possible.

**Comment by claywar** [comment]
This issue should most likely be resolved once interaction framework is merged.  Old Wounds quest migration is added.

**Comment by wrenffxi** [comment]
Closed via #95
