### ISSUE TITLE
1:1 Subjob Combos crash Map Server

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2308]
I... could have sworn someone had this issue posted here, came to see the progress/status and I can't find it now.

Playing on servers as 75/75 and 99/99 worked fine until a pull around.. 6/23/22 (basing this off Discord history). 
Ever since using the 1:1 ratio causes map server to instantly close when certain combos are selected (or a player with them attempts to login). We had hoped it was due to the ongoing changes in all the settings and would eventually iron out but as of today there is no change.

I don't recall all the combos that we found cause the problem but 1 I know for certain is RUN/DNC.   

~ Take any build you want, change the SJ ratio to 1:1 and change to Run/Dnc for immediate map server closure.

**Comment by zach2good** [comment]
>  I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored

Don't ignore and delete the template. Template is confirmation you've read the rules. 

> immediate map server closure

Does this produce any logs? Since this is so easy to reproduce, have you debugged to the process to see where the crash is?

**Comment by Hinekri** [comment]
> > I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
> 
> Don't ignore and delete the template. Template is confirmation you've read the rules.
> 
> > immediate map server closure
> 
> Does this produce any logs? Since this is so easy to reproduce, have you debugged to the process to see where the crash is?

I actually didnt have a template populate.. nor did I get the option to select Bug or Enhancement this time I thought it was strange.

 I am sure I tried at some point before but dont have one saved, ill do some crashing tomorrow unless someone beats me to it.

**Comment by Hinekri** [comment]
@zach2good Im getting no report from Debug, nothing shows in my log, nothing populates to my dmp file.. it just closes the map.exe the moment it loads the character. Above my paygrade..

**Comment by WinterSolstice8** [comment]
so the TL;DR of my investigation so far

RUN/DNC has too many recasts. Don't do that.

This may not be able to be fixed due the the size limit on recast packet. We (LSB) may not be able to fix this without deviating from retail and may be unsupported. Will update you later.

**Comment by WinterSolstice8** [comment]
alright so, I'm putting a crash fix in... however.

Some JA timers will not be displayed to clients and you will just have to deal with it. I tried expanding the size of the packet by deviating from retail to give you an avenue to support this with your fork, but the client ignored it.

**Comment by Hinekri** [comment]
Thank You!
