### ISSUE TITLE
🐛 xi.slot.RANGED not implemented in gear_sets.lua

### ISSUE THREAD

**Issue by N3ckB3ard** [DerpyProjectGroup/topaz#2317]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

!additem 19218 - Murderer
!additem 16004 - Supremacy Earring

Both items should reflect set bonus based on gear_sets.lua
id = 49

set item in xi.slot.RANGED is not currently implemented for set bonuses within gear_sets.lua
or in matchtype.earring_weapon

adding in a check for xi.slot.RANGED will still not return modifiers 

NOTE:
https://www.ffxiah.com/item/18449/namioyogi
This item is missing from the ID's table also

## Expected behavior

With the Murderer and Supremacy Earring equipped players should receive set bonuses
STR+6, ATT+4, RATT+4, MATT+2

**Comment by claywar** [comment]
Resolved by gear set refactor
