### ISSUE TITLE
🐛 Crash Dump: UseItem()?  <--- Feel free to edit

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2332]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
https://drive.google.com/file/d/1k64WT73aUE3llKn4bVnyt1QMtz7Zm4OX/view?usp=sharing
```
 	[Inline Frame] xi_map.exe!std::_Tree<std::_Tmap_traits<unsigned short,CBaseEntity *,std::less<unsigned short>,std::allocator<std::pair<unsigned short const ,CBaseEntity *>>,0>>::_Find_lower_bound(const unsigned short &) Line 1590	C++
 	[Inline Frame] xi_map.exe!std::_Tree<std::_Tmap_traits<unsigned short,CBaseEntity *,std::less<unsigned short>,std::allocator<std::pair<unsigned short const ,CBaseEntity *>>,0>>::_Find(const unsigned short &) Line 1346	C++
 	[Inline Frame] xi_map.exe!std::_Tree<std::_Tmap_traits<unsigned short,CBaseEntity *,std::less<unsigned short>,std::allocator<std::pair<unsigned short const ,CBaseEntity *>>,0>>::find(const unsigned short &) Line 1356	C++
 	xi_map.exe!CZoneEntities::GetEntity(unsigned short targid, unsigned char filter) Line 917	C++
 	xi_map.exe!CTargetFind::getValidTarget(unsigned short actionTargetID, unsigned short validTargetFlags) Line 577	C++
 	xi_map.exe!CCharEntity::IsValidTarget(unsigned short targid, unsigned short validTargetFlags, std::unique_ptr<CBasicPacket,std::default_delete<CBasicPacket>> & errMsg) Line 1927	C++
 	xi_map.exe!CItemState::CItemState(CCharEntity * PEntity, unsigned short targid, unsigned char loc, unsigned char slotid) Line 80	C++
 	[External Code]	
 	xi_map.exe!CAIContainer::ChangeState<CItemState,CCharEntity * &,unsigned short &,unsigned char &,unsigned char &>(CCharEntity * & <args_0>, unsigned short & <args_1>, unsigned char & <args_2>, unsigned char & <args_3>) Line 148	C++
 	xi_map.exe!CAIContainer::Internal_UseItem(unsigned short targetid, unsigned char loc, unsigned char slotid) Line 304	C++
>	xi_map.exe!CPlayerController::UseItem(unsigned short targid, unsigned char loc, unsigned char slotid) Line 153	C++
 	xi_map.exe!SmallPacket0x037(map_session_data_t * const PSession, CCharEntity * const PChar, CBasicPacket data) Line 1788	C++
 	[External Code]	
 	xi_map.exe!parse(char * buff, unsigned __int64 * buffsize, sockaddr_in * map_session_data, map_session_data_t *) Line 689	C++
 	xi_map.exe!do_sockets(fd_set * rfd, std::chrono::duration<__int64,std::ratio<1,10000000>> next) Line 497	C++
 	xi_map.exe!main(int argc, char * * argv) Line 281	C++
 	[External Code]	

```

![image](https://user-images.githubusercontent.com/65316697/179431175-1e5d9a4c-3283-464f-a99e-01cee1f9505b.png)

## Expected behavior

Expect not to crash

**Comment by WinterSolstice8** [comment]
looks like this was ran in release mode and the dump isnt super good. What item was it?

**Comment by WinterSolstice8** [comment]
Oh wait, it's just entering a battlefield?

**Comment by WinterSolstice8** [comment]
Do you have any console logs?

**Comment by CatsEyeXI** [comment]
> Do you have any console logs?

i do, i can zip them up and attach them,

**Comment by CatsEyeXI** [comment]
[map-server - Copy.zip](https://github.com/LandSandBoat/server/files/9129125/map-server.-.Copy.zip)

**Comment by CatsEyeXI** [comment]
> looks like this was ran in release mode and the dump isnt super good. What item was it?

The player stated they entered a BC but were frozen in a cutscene (black screen), so they tried to use their warp ring and that caused the R0

**Comment by WinterSolstice8** [comment]
yeah, that tracks with what i'm seeing. I understand why it crashed, but not how it got there. This is pretty puzzling... without a method to reproduce that black screen thing there's not much I can do here.

Essentially, the client thought it zoned into the new area but never actually notified the server (or perhaps, improperly notified the server?), so when the item use packet came in, it tried to query the empty list of entities in the area. The client should've never actually been "let" out of the loading screen for this to happen. I'll need to think a while about how to fix the crash (not necessarily the behavior), but in the meantime unfortunately the only workaround for your player is to have them force terminate if it happens again instead of warping...

**Comment by CatsEyeXI** [comment]
> yeah, that tracks with what i'm seeing. I understand why it crashed, but not how it got there. This is pretty puzzling... without a method to reproduce that black screen thing there's not much I can do here.
> 
> Essentially, the client thought it zoned into the new area but never actually notified the server (or perhaps, improperly notified the server?), so when the item use packet came in, it tried to query the empty list of entities in the area. The client should've never actually been "let" out of the loading screen for this to happen. I'll need to think a while about how to fix the crash (not necessarily the behavior), but in the meantime unfortunately the only workaround for your player is to have them force terminate if it happens again instead of warping...

that's fair... i'll make an announcement and keep adding to this ticket if more information becomes available to me.
