### ISSUE TITLE
Players cannot interact/open treasure caskets in Qufim

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#2335]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`, reported by players in xiweb discord

## Steps to reproduce

Players unable to interact and open chests that spawn on mob death in Qufim

## Expected behavior

Players can interact and open chests that spawn on mob death

**Comment by RAIST5150** [comment]
Looks like treasure casket ID's may be off?  Not sure if it is in the lua or the SQL?

```lua
     npc = 
     { 
         CASKET_BASE = 17293678,
         OVERSEER_BASE = 17293716, -- Pitoire_RK in npc_list
     },
```

SQL starts with a higher number?

```lua
INSERT INTO `npc_list` VALUES (17293684,'Treasure_Casket','Treasure Casket',0,0.000,0.000,0.000,7,40,40,0,4,4,2,3,0x0000C50300000000000000000000000000000000,0,NULL,0);
```

**Comment by zach2good** [comment]
I think it's about time we start doing a lookup for the ID on server start with `zone:queryEntitiesByName`. Handling shifts in the database is already hard, without adding on another step to try and update all the hard-coded IDs in scripts
