### ISSUE TITLE
🐛 Abyssea onTrigger takes single KI and doesn't spawn NMs that requires 2+

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2341]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Attempt to spawn NM in Abyssea that requires more than 1 KI, it takes the first KI in the list from the player and does not pop the NM.

This is all QMs in all zones, single KI NMs can be spawned. 
## Expected behavior
All required KI should be pulled at once and the NM should spawn.

**Comment by Hinekri** [comment]
On an unrelated note: If you click "new issue" from the issue page without being logged in and then use that popup to login... it sends you to a blank issue with no rules template to check off.

**Comment by TeoTwawki** [comment]
If you are in the reddit servers discord theres a related psa I posted about the url. Its a github problem we have control over

**Comment by Mortalelite** [comment]
Not sure if getting same error but this was tested with Briareus
![Screenshot 2022-07-18 193309](https://user-images.githubusercontent.com/108362771/179634041-dac22847-e23a-492f-ab81-49b855a70ebd.png)


Also note does remove first KI like mention and leaves the other 2

**Comment by claywar** [comment]
Yep.  Its not fully implemented yet.  Abyssea is completely use at your own risk.  I only laid the foundation for future work.

**Comment by Mortalelite** [comment]
Um ok I tested this just removing the line 740 in abyssea.lua ` -- player:messageSpecial(ID.text.LOST_KEYITEM, keyItem) ` and Briareus spawned and deleted the 3 KI. Just wanted to share incase can get a fix going

**Comment by Hinekri** [comment]
> Um ok I tested this just removing the line 740 in abyssea.lua `-- player:messageSpecial(ID.text.LOST_KEYITEM, keyItem)` and Briareus spawned and deleted the 3 KI. Just wanted to share incase can get a fix going

Good enough for my server ty.

**Comment by Chronos77** [comment]
Resolved with MR #3793
