### ISSUE TITLE
🐛 Unable to progress WoTG - Mission 4 - The Queen of the Dance.

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2343]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Mission shows in log after completing Cait Sith but checking the Door: "Lion Springs" does not provide the CS to continue.

## Expected behavior
 CS should be provided when examining the door which will allow you to procure the ticket from Upper Jueno and progress.

I have seen a lot of work on WoTG come thru lately and was going to play catch up, this is checked in the mission log as working.

**Comment by claywar** [comment]
```
        check = function(player, currentMission, missionStatus, vars)
            return currentMission == mission.missionId and missionStatus == 0
            and xi.wotg.helpers.meetsMission4Reqs(player)
        end,
```

There's a two possibilities that could cause the CS to not proceed:
1. Required quests were not completed (`xi.wotg.helpers.meetsMission4Reqs()` returned false)
2. (unlikely, if you were just running through them, but) If you were mid-progress on a previous mission, and used a gm command to change missions, then the missionStatus var would not have been reset to 0.

**Comment by RAIST5150** [comment]
Think the naming scheme only changed during the audit in the last few weeks though (missionareaID and such).  Up until then I think it was still using the same log lookups and such when I ran it months and months ago.

IIRC, this one requires a few key NPC dialogues to get the ticket offered to you in the present.  If it hasn't been done yet, may want to retrace steps to make sure they all took properly?
(The Bastok path has some warnings on xiclopedia to this effect.  Basically, it is easy to miss something in these chains sometimes... going through the steps again may help).

**Comment by Hinekri** [comment]
No GM commands used and this is the very first step in this mission. Get Mission from completing the previous > Click Door.

**Comment by RAIST5150** [comment]
But which city/cities regular quest path(s) have you taken, and are you sure they are properly completed?
(Just trying to rule out other potential snags)

**Comment by RAIST5150** [comment]
For example, Sandy path, Wrath of the Griffon, after taking out Cobraclaw, check the ???, go back to Rholont and get military script. (Can go see Wyatt about selling it).

Wait one game day, from completing that Wrath quest and walk back in to Sandy (s) from E. Ron(s) for a CS, then go to the tavern.

Need to confirm proper steps have been completed.

**Comment by Hinekri** [comment]
> But which city/cities regular quest path(s) have you taken, and are you sure they are properly completed? (Just trying to rule out other potential snags)


This mission is triggered automatically after completion of Cait Sith." - from the Wiki

If they were not completed Mission #4 would not be open, "The Queen of the Dance" reports in my mission log so Cait Sith was fully finished  I am not trying to START #4 I am trying to make #4 progress at Step 1.

**Comment by claywar** [comment]
This is not true.  All quest-requisite missions are flagged prior to the required items being completed.

Note: This is from retail as of now, as I have been running and capping quests/missions while implementing.

**Comment by Hinekri** [comment]
> This is not true. All quest-requisite missions are flagged prior to the required items being completed.

Wait.. why would mission 4 open if mission 3 is still in progress, that doesnt make any sense to me?
 The requirements he is talking about are the previous mission entirely and not any steps in between there and here or start of mission and the cutscene.

**Comment by claywar** [comment]
Mission 3 is completed on zoning into Southern San d'Oria S from ERon S.  Mission 4 is the quest-requisite mission.  _If_ you complete the requisite quests, then triggering the Tavern door will progress and complete the mission.

**Comment by Hinekri** [comment]
> Mission 3 is completed on zoning into Southern San d'Oria S from ERon S. Mission 4 is the quest-requisite mission. _If_ you complete the requisite quests, then triggering the Tavern door will progress and complete the mission.

Is the wiki missing all important quest information in-between the CS finishing 3, and the CS that starts as the beginning of 4?  There is no mention of other requirements, flags, quests, related missions or anything else in between these two steps?

 
--
3 | Cait Sith | Cutscene |  
Nation Quest 3 | Light in the Darkness | Boy and the Beast | Knot Quite There | BCNM | Quest | Quest | Adaman Ingot | Carbon Fishing Rod | Platinum Beastcoin
Nation Quest 4 | Burden of Suspicion | Wrath of the Griffon | A Manifest Problem | Quest | Fight | BCNM | Elixir | Military scrip | Mihgo Mithkabob


4 | The Queen of the Dance | Cutscene |

**Comment by Hinekri** [comment]
Walkthrough

    This mission is triggered automatically after completion of [Cait Sith]
    Proceed to Lion Springs Tavern (K-6) in [Southern San d'Oria (S)]

**Comment by claywar** [comment]
It is indeed.  Any time you see a block of quests prior, they are required:
![image](https://user-images.githubusercontent.com/81713309/179879498-61220c96-0f43-4e6f-8762-98ef1a042f5c.png)

**Comment by Hinekri** [comment]
Right, and mission 4 flags AFTER those are completed

**Comment by claywar** [comment]
Incorrect.  The mission is flagged on completion of the mission, but it cannot be completed until those conditions are met.

**Comment by WinterSolstice8** [comment]
The game forces you to do the nation quests (only one branch is required), so if you start bastok line, you can continue only doing bastok line

**Comment by Hinekri** [comment]
Those quests ARE mission number 3, After finishing any pair of national storylines, enter [Southern San d'Oria (S)](https://www.bg-wiki.com/ffxi/Southern_San_d%27Oria_(S)) from [East Ronfaure (S)](https://www.bg-wiki.com/ffxi/East_Ronfaure_(S)). Entering via Home Point, Survival Guide or any other method won't work, you must walk in from [East Ronfaure (S)](https://www.bg-wiki.com/ffxi/East_Ronfaure_(S)).

**Comment by claywar** [comment]
I would encourage you to subscribe to retail.  Please, this is not the case, is not how retail is implemented, and should you play, you will see this.

**Comment by Hinekri** [comment]
Fine let me get over the arguement of what entails mission number 3, I HAVE FINISHED the bastok quests as it is stated to be PART of number 3 in the Wiki.

**Comment by WinterSolstice8** [comment]
so if I understand you, you've finished "Burden of Suspicion", what does your mission log say you're on mission wise for wotg?

**Comment by Hinekri** [comment]
The Queen of the Dance

**Comment by Hinekri** [comment]
At the very least it sounds like Cait Sith may have an early flag, you should not get this mission in log until after the nation quests are complete and then you walk into Sandy[S] which starts this mission. Claywar makes it sound like you can open this mission by walking into Sandy during mission 3 and it will progress before you complete the nation quests.

**Comment by WinterSolstice8** [comment]
I think there is just a communication issue somewhere here

WoTG was a bit different, as soon as you meet the req for the next mission the log updates. So for instance, if you had not completed Burden of Suspicion it would not show "The Queen of The Dance" until you had done so -- this is because of how SE implemented the missions gradually over time, they used that to gate progression and give a hint there's more to come

**Comment by Hinekri** [comment]
Right thats exactly what I expected, the Wiki states, and I was trying to get across. The "quests" that show in the primary log are the optional requirements [depending on nation] of Mission 3 and not inbetween the two.   The final step of Mission 3 is "after the nation quest" in order to have the log update to Queen of the Dance.. which is where I am stuck.

**Comment by WinterSolstice8** [comment]
If i'm wrong or not, I'm going to figure out how to send the server a command so we can figure out exactly what's going on here.

**Comment by WinterSolstice8** [comment]
what's the output of `!checkmissionstatus <playername> 5` ?

**Comment by TeoTwawki** [comment]
The table on wiki has a few known flaws that make the order trip some folks up. I have no idea if that's the cause of anything here. The implementations here are based on actual captures from within retail as people do the content to verify it.

**Comment by Hinekri** [comment]
@Winter it reported a 0, I am running the missions & quests from the very beginning again on a fresh char and another GM is on mission 3 now and will try tonight, getting late ill follow up tmr ty.

**Comment by RAIST5150** [comment]
Surprisingly, xiclopedia seems to do a better job vusually laying out the flow than some sites.  Basically goes in the order of log the mission to get to a bank of quests.  Complete those quests AND the mission to log the next mission, which takes you to the next bank of quests.  Rinse/repeat.

![Screenshot_20220720-003413_Samsung Internet](https://user-images.githubusercontent.com/73744368/179898131-427a0386-0af6-4098-b108-6d20b0339597.jpg)
![Screenshot_20220720-003331_Samsung Internet](https://user-images.githubusercontent.com/73744368/179898160-9b0f66ca-69cd-4bc5-acaa-fddf3140645b.jpg)


Notice how it demonstrates that completion of the Wrath of the Griffon quest I used earlier as an example is one of the prerequisite quests for actually DOING Queen of the Dance.

At present, the Windy and Bastok quests stall early on in their paths.  To progress to the last available fight and mission, it requires taking the Sandy path for now.

And this IS how it functioned in retail back in the day.  I often had to wait on friends to help them clear their nations to progress to fights.

**Comment by zach2good** [comment]
> [Winter] it reported a 0, I am running the missions & quests from the very beginning again on a fresh char and another GM is on mission 3 now and will try tonight, getting late ill follow up tmr ty.

Please be careful who you tag, "Winter" is a different user to @WinterSolstice8. Some poor guy a couple of years ago got really mad because he was being tagged as "Kain" instead of @kaincenteno

**Comment by Hinekri** [comment]
The at-Winter didnt populate anyone so I left the abbreviation to not actually tag him as it wasnt too important lol.   

So the bug seems to be restricted to the Bastok line, after having completed everything up to/including Burden of Suspicion the CS did not prompt.  Completed the Sandy mission series on the same character and the CS worked as intended.
![My project](https://user-images.githubusercontent.com/106329891/179946247-4f2cbfb2-6404-410e-adb6-32913bd3bbe9.jpg)
You can see Cait Sith was still in the log at the time of completing the final nation quest, The Queen of the Dance flags after the quest not prior to.

**Comment by RAIST5150** [comment]
IIRC, Burden of Suspicion is not scripted yet, or somewhere thereabouts--think the path stops right around an event with the senator and dealing with the Galka at the Metalworks.

As I stated earlier, Bastok and Windy paths stall early in their paths and the only way to progress to the latest fight and mission set that are scripted is via the Sandy path.

https://github.com/LandSandBoat/server/tree/base/scripts/quests/crystalWar

Even though a substantial chunk of the interactions missions scripting has been going much further (missions are in a different folder), as of the last few weeks we could only progress as far as the prep stage for the siege turret fight... again, via the Sandy path only.

This isn't a "bug"... more a work in progress that is needing captures/reviews/scripting/testing... work is yet to be contributed for many many things past the core ZM/CoP stages of content.

Pretty much all of it is WIP and continually evolving as people find time to work on it.

**Comment by DriftwoodGaming** [comment]
When finishing WotG Mission 1, the game auto-completed mission 2 and flagged me for Cait Sith (mission3). I was on Burden of Suspicion (Mission2 Quest 2) when talking to Turbulent Storm in the Eldieme Necropolis [S] and telling him "I'm your man." I was given the Blue Recommendation letter for mission "The Fighting Forth" (which the game had auto-skipped me passed) thereby accepting "The Fighting Forth" abandoning "Burden of Suspicion". I did all of the Mission1 quests then all of the Mission 2 quests up to Burden of Suspicion, at which point I was not given this quest again. I tried every point in the quest to 'regain' the mission, waited the game days, re-zoned over and over and went through all of the steps in the mission to see if it would re-flag at some point. Alas it does not. There's still some 'funky-ness' when choosing the Bastok route in WoTG. 
Maybe someone should make a 'feature request' in the hopes that it be looked at by someone more skilled than I? Anyway I thought I would leave my experience in this catalog for future reference. Thanks for reading.

**Comment by RAIST5150** [comment]
Do no recall seeing further progress on the Windy and Bastok paths for quite awhile now... it is likely still only possible to progress on through Purple the New Black and such via the Sandy path.

Should note that though there may be a lot of quest/mission files in their respective folders past where players have managed to progress in game for each expansion, the battlefields required to proceed into those scrpts may not be available yet.

There is still quite a bit on the ToDo lists.
