### ISSUE TITLE
🔨 Make zone:queryEntitiesByName() fast

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#2346]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

We're currently getting a lot of use and safety out of `zone:queryEntitiesByName()` but the current implementation is $O(n)$. We need to bring this down to _at worst_ $O(log n)$, but more likely $O(1)$.

We'll probably want to populate a `std::unordered_map<std::string, std::vector<CLuaEntity>>` at startup, and use that for our lookups.

This however won't work for dynamic entities, so we'd also need a way to force the linear search by name.

**Comment by jmcmorris** [comment]
This is more or less resolved in https://github.com/LandSandBoat/server/pull/2754. `zone:queryEntitiesByName()` now uses memoization so subsequent calls are simply a map lookup which I believe is _O(logn)_.

**Comment by zach2good** [comment]
`find` in `unordered_map` is $O(1)$ on average case, so even better :)

https://cplusplus.com/reference/unordered_map/unordered_map/find/
