### ISSUE TITLE
🐛 Fenrir generates [map][error] luautils::onSpellCast: stack index 2, expected number, received nil

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#2357]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base` on xiweb after rebuild tonight (7/19/22)

## Steps to reproduce

SMN casts Fenrir and [map][error] with onspellcast shows up after Kain rebuilt xiweb tonight.  Asked that it be posted.

## Expected behavior

SMN casting Fenrir does not generate [map][error] onspellcast.

**Comment by RAIST5150** [comment]
```
xigame_1  | [07/20/22 02:36:07:890][map][error] luautils::onSpellCast: stack index 2, expected number, received nil: not a numeric type (bad argument into 'bool(unsigned short, const sol::basic_object<sol::basic_reference<false>> &)')
xigame_1  | stack traceback:
xigame_1  |     [C]: in function 'hasStatusEffect'
xigame_1  |     ./scripts/globals/spells/summoning/fenrir.lua:28: in function <./scripts/globals/spells/summoning/fenrir.lua:25> (OnSpellCast:2475)
```

Does not appear to crash anything.  Fenrir casts, assaults, uses blood pacts, etc. fine.

**Comment by TeoTwawki** [comment]
theres a typo at the line its complaining of (line 28)
