### ISSUE TITLE
🐛 Duplicate chat messages in-game

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2366]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
I couldn't find this reported previously so I thought I'd make a note of it.
Happens at random, and usually resolves by zoning, messages received in the chat window are duplicated a second time.
Issue is present in both Ashita and Windower.

## Expected behavior
Messages should not be duplicated

**Comment by CatsEyeXI** [comment]
As a side note, if you are not logged into Github when clicking "New Issue" it will not ask you to choose which template to use.

**Comment by TeoTwawki** [comment]
I will vouch for this random occurrence. Usually goes away on its own. one common factor I saw among players experiencing it was they all had 1st LS slot empty while having the 2nd LS slot populated, but it usually went away after restarting my server.

I was never able to reproduce it on purpose and the last time I reported it was way back in DSP. Since then I never reported it to the current project's tracker because out of sight = out of mind, forgot about it.

**Comment by TeoTwawki** [comment]
> As a side note, if you are not logged into Github when clicking "New Issue" it will not ask you to choose which template to use.

I had a recent PSA letting ppl know to go to 
`https://github.com/LandSandBoat/server/issues/new/choose`
instead of 
`https://github.com/LandSandBoat/server/issues/new/`

when logged out the button takes you to the latter as well, but anyone following old bookmarks or old links will also land there. Its an issue at githubs end we have no control over.

**Comment by Xaver-DaRed** [comment]
I have seen this happen aswell and it does indeed seem to happen commonly in LS2 with LS1 empty.

Sometimes it "sticks" to the player but most times it fixes itself by simply zoning.

**Comment by CatsEyeXI** [comment]
I asked around some players just now, and it also occurs if you have LS1 populated but not LS2. Another is saying he has 2 LS's equipped    ¯\_(ツ)_/¯

**Comment by TeoTwawki** [comment]
hey this your arm? I think you dropped it, we'll get a surgeon to reattach it: \\

**Comment by personaone** [comment]
I think I've also seen this in the past - the logs that Ashita generates from one of the plugins actually has duplicate entries, for NPC chatter - might be a plugin issue, I never paid much attention to it, just interesting

**Comment by TeoTwawki** [comment]
> I think I've also seen this in the past - the logs that Ashita generates from one of the plugins actually has duplicate entries, for NPC chatter - might be a plugin issue, I never paid much attention to it, just interesting

I've seen it happen to linkshell chat with no plugins or addons loaded. Not even the ashita stock ones - just bare client windowed through it. I last saw it about 2 yrs ago, went away after restart and I've not had a report of it since till this issue.

**Comment by CatsEyeXI** [comment]
ladies and gentlemen, we're having triplets!
![image](https://user-images.githubusercontent.com/65316697/180458740-bc60f525-f9db-45e4-bb84-0c5a357a8cd3.png)

**Comment by zach2good** [comment]
Since this is such an old issue, I guess it has nothing to do with multi-process setups?

One thing we could do (since its probably quite hard to repro) is to do a similar de-duping for message packets like we used to do for char/entity updates.

**Comment by CatsEyeXI** [comment]
just wanted to clarify that we are still running on a single map server process...

**Comment by WinterSolstice8** [comment]
#2377 may help, but unsure with no way to easily reproduce

**Comment by CatsEyeXI** [comment]
> #2377 may help, but unsure with no way to easily reproduce

We haven't seen this issue since you implemented #2377

**Comment by CatsEyeXI** [comment]
I think it's good to close this. Thank you!!!
