### ISSUE TITLE
🐛 Byakko's Haidate drop

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#2374]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Killed Byakko over 20x.  Not a single drop of Byakko's Haidate.  That can't be right.

Too much bullying from the poor cat?

**Comment by Mortalelite** [comment]
` INSERT INTO mob_droplist VALUES (394,0,0,1000,12818,@COMMON); -- Byakkos Haidate (Common, 15%) `

Looks like currently set as 15% drop rate

Most could find is 43% - 45% ballpark, I am not sure of correct range should be 

https://ffxiclopedia.fandom.com/wiki/Byakko and http://ffxidb.com/items/12818

**Comment by Gradius2** [comment]
I see.  15% is pretty wrong btw.  I got it back in 2004 or 2005, it wasn't that hard to see that drop to happen.

**Comment by zach2good** [comment]
If you're going to quote from ffxidb, please make sure you're looking at the TH0 values. The value in that page you linked was the AVERAGE of all the different TH value droprates

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/1389729/180388864-01fe94cc-51fb-460c-b11f-79a2d3c4522f.png">

The value in the db has to be TH0

**Comment by zach2good** [comment]
Note that there is a 100% droprate for TH1, because there must have been only a single uploaded TH1 kill. So these stats aren't gospel, but they're better than nothing if you look at the right parts

**Comment by Mortalelite** [comment]
> If you're going to quote from ffxidb, please make sure you're looking at the TH0 values. The value in that page you linked was the AVERAGE of all the different TH value droprates


Ah ok I didnt know that part showed up, but now I do know. I dont use ffxidb often, keep that in mind

**Comment by claywar** [comment]
Closing this issue, as current implementation appears to conform with existing data.
