### ISSUE TITLE
🐛 Crash when interrupting a player during "packet backlog"

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2390]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Player (Hax) used warp ring, and logged out immediately (he is a GM, so instant logout)
![image](https://user-images.githubusercontent.com/65316697/180700937-4f0fe44f-7cf7-4d07-b1b7-ae2c98570027.png)

Dump:
https://drive.google.com/file/d/1WpOZ0lIh6Q3itLRKJQSjThRoL1Rvm43R/view?usp=sharing

## Expected behavior

Should not crash

**Comment by CatsEyeXI** [comment]
I just experienced this again while !bring-ing a player... I think I caught a good dump too.
https://drive.google.com/file/d/1LdpfP93Y4ro87bQ3kjC5dO193kaUCPkt/view?usp=sharing
Build: 0aa8456a77 
![image](https://user-images.githubusercontent.com/65316697/180912877-78ddd657-8b5f-42c4-9696-29c291c93b0b.png)

**Comment by WinterSolstice8** [comment]
in both dumps
PChar->loc->zone is nullptr which may be affected by #2449

this may not happen anymore, but probably still worth keeping open.  I can't produce it when I try to at least, but these are race condition crashes as described

**Comment by zach2good** [comment]
Can this be closed?
