### ISSUE TITLE
🐛 Spark shop npcs exchange for unexpected values

### ISSUE THREAD

**Issue by HaxPrime** [DerpyProjectGroup/topaz#2397]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Interact with the sparks shop npc
   Rolandienne in Southern San d'Oria (G-10)   
   Isakoth in Bastok Markets (E-11)   
   Fhelm Jobeizat in Windurst Woods (J-10)   
   Eternal Flame in Western Adoulin (H-11)   
2. Menu selection - Exchange A.M.A.N. currencies.
3. Menu selection - Currencies.
4. Menu selection - Sparks of Eminence: 1000.
5. Menu selection - 30000 (Thirty).
6. Menu selection - No.
7. Menu selection - None.
8. Menu selection - Nothing for the nonce.
9. Menu selection - Nothing for the nonce.   
   You are now back into the main menu and the bug is active, you can now select any armor or weapon and purchase them thirty at once.
10. Menu selection - Equ. Lv.1 - 9
11. Menu selection - Cesti. (50)
12. Menu selection - Yes.   
   You obtain 30 pairs of cesti!   

The sparks of eminence are still deducted from the player at the appropriate amount.

## Expected behavior

Sparks shop npcs should add to players one item at a time through the weapon and armor selections.

![ffxi_2022 07 25_15 46 03](https://user-images.githubusercontent.com/108164867/180870765-af48a18d-6639-4656-8d7b-b0ed1c82ebbe.jpg)

**Comment by WinterSolstice8** [comment]
works for me
![image](https://user-images.githubusercontent.com/60417494/180876411-2cf6518e-3377-45ee-8464-0ef76b5279c1.png)

**Comment by CatsEyeXI** [comment]
> works for me ![image](https://user-images.githubusercontent.com/60417494/180876411-2cf6518e-3377-45ee-8464-0ef76b5279c1.png)

The issue is, in retail you are only be allowed to buy one item at a time, and by jumping through the menus the way Hax explained, enables you to buy as many as you want. I recorded the process for reproducing the bug. I don't think this is a high priority bug by any means, but I could see it affecting other menus in the game.


https://drive.google.com/file/d/1MtWBiVXvCnjtcWKf1lRV5JFbAzOtJAPR/view?usp=sharing

**Comment by WinterSolstice8** [comment]
Took a look at this again carefully and found the fix. thanks for the report.

**Comment by arkbg1** [comment]
Removing this workaround contributes to Repetitive Strain Injury that the Mayo Clinic says can require dangerous surgery*. In this case, snitches literally cause stiches. Please consider providing an RSI-friendly solution to convert sparks to gil. 

*For more information on the risks of RSI surgery: https://newsnetwork.mayoclinic.org/discussion/mayo-clinic-q-and-a-repetitive-use-wrist-and-elbow-pain/
