### ISSUE TITLE
Fix duplicate entries for hunts across different zones

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#240]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Some zone comments have the same entry in the hunts table

CI error, some entries in the list are overwritten
```
   scripts/globals/hunts.lua:517:11: (W314) value assigned to field 874 is overwritten on line 522 before use
    scripts/globals/hunts.lua:518:10: (W314) value assigned to field 1130 is overwritten on line 523 before use
    scripts/globals/hunts.lua:817:11: (W314) value assigned to field 898 is overwritten on line 822 before use
```

**Comment by TeoTwawki** [comment]
we need to change the table structure a bit to fix this: the values are for different zones's books.
```lua

        -- Castle Zvahl Keep
        [ 362] = { params = 120161, huntId = 353 },
        [ 618] = { params = 120162, huntId = 354 },
        [ 874] = { params = 120163, huntId = 355 },
        [1130] = { params = 120164, huntId = 356 },
        -- The Boyahda Tree
        [ 370] = { params = 104805, huntId = 357 },
        [ 626] = { params = 122214, huntId = 358 },
        [ 874] = { params = 122215, huntId = 359 },
        [1130] = { params = 139624, huntId = 360 },
```
which is one of the multiple reasons I wanted things keyed by the actual [index value of the regime/hunt/whatchacallit as those are unique](https://github.com/LandSandBoat/server/blob/base/documentation/Regime_IDs.csv#L360)

**Comment by TeoTwawki** [comment]
#401
