### ISSUE TITLE
🐛 Possible Mistake in Job Points Gift &/or Overwritten Modifier?

### ISSUE THREAD

**Issue by Hinekri** [DerpyProjectGroup/topaz#2422]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
I dont know for certain if the Modifier List is wrong or a change was made for GEO and the number was reused on accident or what so posting the issue as a "possible".

INSERT INTO `job_point_gifts` VALUES (2, 550, **959**, 5, 'MNK_Counter Damage');

    // Geo
    CARDINAL_CHANT       = 959,

## Expected behavior

Was searching for the Counter Damage+ modifier to build into the Blu Spell "O.Counterstance" when I found the mod missing and MNK JP pointing to a GEO effect instead.  Counter Damage+ should exist as a standalone mod.

**Comment by claywar** [comment]
Looks like this iss was resolved:
`INSERT INTO `job_point_gifts` VALUES (2, 550, 1047, 5, 'MNK_Counter Damage');`
`COUNTER_DAMAGE       = 1047, // TODO: Increases Damage from Counter Attacks (Percent)`

(Now making it do something is another story)
