### ISSUE TITLE
🔨 We should start using relative links in wiki where possible, instead of full paths

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#2451]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature
In pages that are markdown (`.md`) format,

`[Server Administration](https://github.com/LandSandBoat/server/wiki/Server-Administration)` 

could be just

`[Server Administration](Server-Administration)`

and would still work, and have the added benefit of not being a dead link in the event of a url change (for example, hosting a local copy or forking).

Additionally preceding a filename with a slash tells the markdown engine the file is relative to the repository root rather than relative to the current url. Atm that doesn't matter because all of our articles are in the repository root, but someday we might use subfolders to better organize categories of pages so I thought I should mention this feature.

Note relative linking ONLY works with wiki pages linking to other pages on the same wiki, or links in a repository to other locations in the same repository.

For mediawiki (`.wiki`) formatted pages the syntax would be:

`[[Server-Administration]]`

and

`[[/Server-Administration]]`

**Comment by RAIST5150** [comment]
Not sure if it would be used here or not, but the old ../ navigation to go up levels may still be a thing too.

**Comment by TeoTwawki** [comment]
> Not sure if it would be used here or not, but the old ../ navigation to go up levels may still be a thing too.

that's why I brought up using paths relative to the root: `[text](/somepath/filename)` will work with no dots

**Comment by EpicTaru** [comment]
I'll take this into account as I work thru the wiki.

**Comment by EpicTaru** [comment]
[#12](/LandSandBoat/lsb-wiki/pull/12)
[#14](/LandSandBoat/lsb-wiki/pull/14)
