### ISSUE TITLE
🐛Multiple NPCs no longer visually appearing correctly.

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#2457]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Zone to grand palace of hu xzoi, visually not see doors but can interact with the doors still

Other locations:
Runic portals
Runic seals

![image](https://user-images.githubusercontent.com/6257062/182889913-cbc544cb-128c-46ce-9eed-fa67ee031a6f.png)
![image](https://user-images.githubusercontent.com/6257062/182889957-ec678468-600c-439a-95ef-b764ca7cd77b.png)
![image](https://user-images.githubusercontent.com/6257062/182895545-1da9a8ce-23a0-47e1-9696-4766c2dc15af.png)
![image](https://user-images.githubusercontent.com/6257062/182895809-3fa57d1d-409a-4eef-b61c-17e0e5699186.png)

## Expected behavior

NPCs Visually displayed.

**Comment by CriticalXI** [comment]
Aerec was able to discover that it is possibly related to #2226 as he can see the doors prior to this and not after.

**Comment by Mortalelite** [comment]
I have also tested this and getting same results
