### ISSUE TITLE
🐛 Client crashes upon zone into Rolanberry Fields

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#2471]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

7ad6aa7

## Steps to reproduce

!zone Rolanberry Fields

Zone to Rolanberry Fields from Lower Jeuno or Crawlers Nest

Client will crash upon zone in

Did test Rolanberry Fields [S] no crash 

Nothing in the log with any error

## Expected behavior

Client not to crash upon zone into Rolanberry

**Comment by EpicTaru** [comment]
For reference:

https://discord.com/channels/392903136336936960/883227930828886060/1005445761699430480

**Comment by personaone** [comment]
Can confirm this is the case
