### ISSUE TITLE
Server setup conf folder structure is missing or directions are unclear

### ISSUE THREAD

**Issue by sdyaris** [DerpyProjectGroup/topaz#2473]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Following server install procedures

Following instructions, getting to this step the conf structure is missing:
cp conf/default/* conf/
I did a search of the directories and there is no conf folder.
## Expected behavior
to be able to install server

**Comment by Mortalelite** [comment]
Are you following the steps here https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide to setup server

The Conf is old files and been replaced in Settings Folder per the guide setup

**Comment by sdyaris** [comment]
Where is this stated in the guidw?

**Comment by sdyaris** [comment]
As quoted:
"Now we are going to enter the username and password for sql inside three different files login.conf, map.conf, and search_server.conf

First, copy these config files to the conf folder:

cp conf/default/* conf/"

**Comment by WinterSolstice8** [comment]
What page do you see that text on? I see only "settings" on the quick start guide:

![image](https://user-images.githubusercontent.com/60417494/183305725-1861e495-1890-49ef-a67f-a2092bf9b826.png)

**Comment by TeoTwawki** [comment]
There were VERY RECENT changes to where/how conf settings are stored, just a reminder

**Comment by sdyaris** [comment]
Someone should clean up the install guide then.  I'm going off the link you posted.

**Comment by TeoTwawki** [comment]
> Someone should clean up the install guide then. I'm going off the link you posted.

Someone IS. there's already open work on it.

**Comment by sdyaris** [comment]
https://github.com/LandSandBoat/server/wiki/Server-Setup-and-Maintenance-Linux

**Comment by TeoTwawki** [comment]
https://github.com/LandSandBoat/lsb-wiki/pulls?q=is%3Apr

it's been a busy couple days for the wiki

**Comment by EpicTaru** [comment]
> https://github.com/LandSandBoat/server/wiki/Server-Setup-and-Maintenance-Linux

Currently going thru that file to replace Topaz connotations with LSB connotations, @sdyaris.
