### ISSUE TITLE
🐛 Client returns to title screen while buying from sparkshop and using windower addon treasury

### ISSUE THREAD

**Issue by HaxPrime** [DerpyProjectGroup/topaz#2481]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

- Use windower
- Unload all addons and plugins
- Delete the treasury directory, making sure no settings are causing this
- Download a fresh treasury through the windower gui
-  Load the addon treasury in game
- Interact with sparkshops npc:
  Rolandienne in Southern San d'Oria (G-10)
  Isakoth in Bastok Markets (E-11)
  Fhelm Jobeizat in Windurst Woods (J-10)
  Eternal Flame in Western Adoulin (H-11)
- Purchase a quantity six or more of the same item
- Exit the sparkshop menu
- Client returns to title screen of the game
This produces a warning in the map server for light luggage. 
## Expected behavior
Client should not return to title screen

![map](https://user-images.githubusercontent.com/108164867/183530503-77713847-9fac-4b13-87d0-4aa8fcc5d954.png)
![ffxi_2022 08 08_17 45 17](https://user-images.githubusercontent.com/108164867/183530608-7ba9ca80-224c-46b7-97b0-f88bb3819738.jpg)

**Comment by zach2good** [comment]
You can set `map.LIGHTLUGGAGE_BLOCK` to 0 to disable this.

**Comment by zach2good** [comment]
The reason for this is that when the client sends a `SmallPacket0x03A` it directly results in database activity and generates packets. If there isn't any sort of limit, there's nothing to stop someone spamming the packet (like lightluggage presumably used to) and bogging down the server. 

You could also play with that setting and find out how high you need to set it to have your plugin work as expected.

**Comment by zach2good** [comment]
And thats exactly what `Treasury` is doing:

```lua

stack = function()
    local wait_time = 0

    return function()
        if os.clock() - last_stack_time > 2 then
            packets.inject(packets.new('outgoing', 0x03A))
            last_stack_time = os.clock()
            wait_time = 0
        elseif os.clock() - last_stack_time > wait_time then
            wait_time = wait_time + 0.45
            stack:schedule(0.5)
        end
    end:cond(function()
        return settings.AutoStack
    end)
end()
```

**Comment by WinterSolstice8** [comment]
Alternatively, disable autoStack in Treasury, it's not necessary anymore anyway due to auto sort being a client function by default. `settings.AutoStack`

**Comment by TeoTwawki** [comment]
I've heard treasury's is better than SE's sort, but I think the issue is the frequency which I can see snowballing real bad if someone multiboxes or has multiple persons in the same houshold (packet spam from same IP) and thus tripping the detection. Treasury's own code shows it can be adjusted there in addition to changing the servers limit by increasing that wait time in treasury's lua.

**Comment by HaxPrime** [comment]
Thanks guys for the varied solutions and the explanation of what is happening here.
