### ISSUE TITLE
🐛 Movement speed equipment bonuses stack unexpectedly 

### ISSUE THREAD

**Issue by HaxPrime** [DerpyProjectGroup/topaz#2482]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Equip multiple movement speed bonus items. For this example I used
Danzo Sun-ate +12%
Kinddom Aketon +12% in San d'Oria
Shneddick Ring +18%
This returns an equipment movement speed bonus of +42%. Verified with speedchecker and targetinfo. 
## Expected behavior
Movement speed equipment bonuses should not stack. Only the highest bonus should take effect.
https://www.bg-wiki.com/ffxi/Movement_Speed

![speed](https://user-images.githubusercontent.com/108164867/183533895-b8c49270-f578-4a12-9fc7-34a3cb573e6d.png)
![ffxi_2022 08 08_18 44 55](https://user-images.githubusercontent.com/108164867/183533953-6b25f5b1-d2ec-45d8-9378-390cd3a638c5.jpg)

**Comment by claywar** [comment]
From observation, expected result should be highest single piece equipped, which is 25% (Adoulin zone with the appropriate gear item), or 18% and lower (for all zone)

**Comment by TeoTwawki** [comment]
see also #2501

**Comment by TeoTwawki** [comment]
removed "good first issue" label because given past experiences and average new person skill, I do not feel it is.
