### ISSUE TITLE
🐛I don't know how to generate a crash, it happens regularly every 10-15 minutes

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#2484]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

I don't know how it came about,
## Expected behavior
[xi_map.exe_9-8_18-35-5.log](https://github.com/LandSandBoat/server/files/9289687/xi_map.exe_9-8_18-35-5.log)

I would like to know where the problem is and how to fix it

**Comment by Mortalelite** [comment]
I would advise to update latest https://github.com/LandSandBoat/server/commit/0050386cda37d5dc64e18f150ab6bb36db06b996 and see if still have issues as Crash Log shows https://github.com/LandSandBoat/server/commit/72acac108db452e3b4260b12cde0f554072a1c20

**Comment by WinterSolstice8** [comment]
0050386cda37d5dc64e18f150ab6bb36db06b996 was a _client_ crash, unfortunately. My only suggestion here with what I have is to make sure you've run dbtool to keep the database updated. If it still continues I may need a dump to investigate further.

**Comment by Freetate** [comment]
I customized some monsters to drop lua and mobgroup.sql, will it cause such a crash because some monster refresh methods in Abyss Sea have not been modified correctly
