### ISSUE TITLE
🐛 Extra characters are appended to the end of TELLs

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2492]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

This isn't a new issue, I always assumed it was a result of a mismatch between client and server versions, but since being version locked, the issue persists.

It happens randomly, I'm not sure how to reproduce it, but here's an example...

![image](https://user-images.githubusercontent.com/65316697/183953518-567f551c-9100-4fe9-9e4b-136b29318cc6.png)

## Expected behavior

Should not see any additional characters in tells.

**Comment by kaincenteno** [comment]
from what i remember, this started happening after SE released the help channel (that one that mentors can apply for and only people with new icon on their name get access to)
