### ISSUE TITLE
check command giving unexpected results, mob agro and level outside of the expected range

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#25]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
This has been "reported" in chat many times, but lacked an issues describing it. According to what I was told by the person implementing the change, prior to lv99 there is no such thing as "incredibly easy prey" only easy pray and too weak. But if you run through Xarcabard as a lv75 on a 75 capped server you can draw aggro from lv 46 mobs that check as IEP.

![image](https://user-images.githubusercontent.com/6871475/116002583-6fa41a80-a5c8-11eb-9d37-301a24c589e4.png)

## This issue shall serve as a cache all for related reporting until we're 100% sure the level ranges for `/check` are 1:1 retail accurate.

**Comment by AppleCrumble1** [comment]
Torama in LoO con as TW when lvl 57 to 60 on 6 dif chars but act like IT when engaged taking a while to kill.
Death cap, bark spider, mandy, rabbit, crab,  crawler and goobue in the tree 1st zone, all have mixed tw to IT++ on chars lvl 54 to 57 both out of party in party and lvl synced. Con normally(lvls they should be) to a lvl 67 outside of party but con tw or normal within party. Wont give xp to party if lvl synced to one of the 54 to 57 but if sync to the 67 will give xp rate of a 67 sync party.

**Comment by claywar** [comment]
@TeoTwawki Can you provide a checklist of mobs to verify against? Can check against retail, so that we can normalize data

**Comment by TeoTwawki** [comment]
@claywar in xarc as a lv75 rdm, the ghosts, demons, and floating eyes checked IEP. skeletons were TW. did not think to check gigas and elemental but the result was definitely level based - anything lv 46 or above was checking IEP. the skeletons connec 44 are their highest, and conned TW.

**Comment by AppleCrumble1** [comment]
![Custard_2021 04 29_111413](https://user-images.githubusercontent.com/45308457/116535917-3e835d00-a8dc-11eb-9e6f-5110876e0b5f.png)
The level 95 too weak bat agroed as normal to sound

**Comment by TeoTwawki** [comment]
level 95 AND too weak, does not compute!

**Comment by AppleCrumble1** [comment]
![Custard_2021 04 30_085400](https://user-images.githubusercontent.com/45308457/116665643-ed35a500-a991-11eb-9ce9-6ae086c795a5.png)
LoO, level 60 synced party checks on all xp valid mobs :(

**Comment by AppleCrumble1** [comment]
![20210430_090045](https://user-images.githubusercontent.com/45308457/116666318-b90eb400-a992-11eb-876a-dff16e44e68a.jpg)
Exactly  same mobs but checked with lvl synced to a 69

**Comment by TeoTwawki** [comment]
![Teoru_2021 07 18_192917](https://user-images.githubusercontent.com/6871475/126085421-ce26c757-f7d6-468e-8273-dee85e9c9e22.png)

so 1 level HIGHER resulting in our `Incredibly Tough` mobs becoming `Too Weak`.

**Comment by TeoTwawki** [comment]
affected mobs that check "too weak" not only don't give exp despite the actual level being higher, but they also do not agro.

**Comment by TeoTwawki** [comment]
after I got one level, that lv 26 crab went from too weak to IT

edit: I was lv 20 before, 21 after the ding. anything greater than 5 lv above is checking tw

**Comment by TeoTwawki** [comment]
this def has nothing to do with level sync, as we were not sync'd:

![image](https://user-images.githubusercontent.com/6871475/126087765-4367d260-155f-466f-bd24-c22d7491ff4c.png)

I also double checked that part/solo didn't even matter.

Apologies for the notification spam, just sorta documenting as I go.
