### ISSUE TITLE
🐛 [NPC] Quest The Vicasque's Sermon player getting stuck and making UI disappear

### ISSUE THREAD

**Issue by GravesXI** [DerpyProjectGroup/topaz#2500]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

This is done on a LSB fresh base server no mods or addons 

## Steps to reproduce

talk to Abioleget and get the CS to start the quest  and talk to him again right after and your UI will disappear and will get stuck reproduced when the npc was talked to before you gave the peas to the other npc in the quest

## Expected behavior

![03765BF7-FB89-45DD-85C4-A884A7F2796E](https://user-images.githubusercontent.com/1095718/184061108-df8faf22-9791-43ea-b398-df35930d1515.jpg)
![AA866C1F-CDBE-41FC-875A-0321D859F7ED](https://user-images.githubusercontent.com/1095718/184061115-0c4786a8-abae-47fd-bd6d-aeaeeae324b6.jpg)

**Comment by claywar** [comment]
Quest was rewritten and verified as working. If the client is still freezing, then this might be related to any client side add-ons or modding done.
