### ISSUE TITLE
🔨 Destroying dynamically created NPC's.

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2503]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

We are able to summon and !hp 0 dynamic mobs, but it would be useful if we could extend the same functionality to NPC's and make them disappear, die, or deactivate.

**Comment by zach2good** [comment]
What are you trying to achieve here, do you need to free up IDs?

My intention for NPCs was to be declared up front at startup and then switched on/off with their status as needed.

That was also the original intention for mobs, but I only added id reuse for Horizon to be able to implement era dynamis with dynamic entities

**Comment by CatsEyeXI** [comment]
We put a lot of custom content on dynamic NPC's, occasionally when we deploy something new we'll discover a bug in the code and it would be helpful to shut down that NPC until the issue is resolved.

I noticed that FileWatcher does detect changes to modules, and says it's "re-running" them, but I've yet to see it actually update an active dynamic entity. (I'm not sure if that's the intended purpose or not)

An example use case (in a custom setting) would be to enable a timed "portal" to send a player somewhere.

**Comment by zach2good** [comment]
If you want to turn off NPCs at will, you can do this with any entity in the game:

- Get their ID somehow: `!exec print(target)` etc. = `[08/12/22 09:49:41:827][map][lua] CLuaBaseEntity(TYPE_NPC | 17639680 | DE_Horro | Horro) (lua_print:145)`
- ![image](https://user-images.githubusercontent.com/1389729/184300199-3aa6eb99-ae70-4105-96cf-608ff549944b.png)
![image](https://user-images.githubusercontent.com/1389729/184300266-d31cb15b-39a5-41e6-991d-029d0af639b5.png)
![image](https://user-images.githubusercontent.com/1389729/184300305-371e8094-1e4e-440e-9955-f48f80e0436e.png)

You get given the NPC/Mob object when you create a dynamic entity, so you can attach that to the global object for easier access.

```lua
xi.custom = xi.custom or {}
xi.custom.Horro = zone:insertDynamicEntity({...
...
xi.custom.Horro:setStatus(xi.status.DISAPPEAR)
xi.custom.Horro:setStatus(xi.status.NORMAL)
```

> I noticed that FileWatcher does detect changes to modules, and says it's "re-running" them, but I've yet to see it actually update an active dynamic entity. 

If you have a module that is applying things on `onInitialize`, like adding new NPCs, a module reload will override `onInitialize`, but `onInitialize` is only called during server start. So a custom NPC won't receive any changes.

If you wanted hot-reloadable onTrigger/onTrade logic for NPCs or Mobs, you'd have to get sneaky with how/when you define and apply that logic.

```lua
-- your_module.lua

local onTriggerFunc = function(player, npc)
    -- NOTE: We have to use getPacketName, because the regular name is modified and being used
    --     : for internal lookups
    player:PrintToPlayer("Welcome to New GM Home!", 0, npc:getPacketName())
end,

m:addOverride("xi.zones.GM_Home.Zone.onInitialize", function(zone)
    super(zone)
    zone:insertDynamicEntity({
        objtype = xi.objType.NPC,
        name = "Horro",
        onTrigger = onTriggerFunc
    })
end)

-- Internally, the cache entry for Dynamic Entries is prepended with "DE_"
-- This might get upset on startup, since `xi.zones.GM_Home.npcs.DE_Horro` probably doesn't exist when this script is first run
xi.zones.GM_Home.npcs.DE_Horro.onTrigger = onTriggerFunc
```
```txt
[08/12/22 10:01:58:479][map][info] [FileWatcher] RE-RUNNING MODULE FILE modules/custom/lua/test_npcs_in_gm_home.lua (luautils::CacheLuaObjectFromFile:519)
```
![image](https://user-images.githubusercontent.com/1389729/184301844-c675393a-c1e0-43a6-a923-23f8cf449f35.png)

**Comment by CatsEyeXI** [comment]
Wooow... Thanks! This is super handy, appreciate the detailed write up.
