### ISSUE TITLE
🐛 <DNC AF Quest: Comeback Queen>

### ISSUE THREAD

**Issue by N3ckB3ard** [DerpyProjectGroup/topaz#2512]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

 
https://github.com/LandSandBoat/server/blob/ff257cf51c312c5b186e203410318b066ccf3f1c/scripts/quests/jeuno/Comeback_Queen.lua

!addquest 3 98
(If needed !completequest 3 97 playername to clear check to progress)
speak with proper NPC's while using !checkvar playername Quest[3][98]Prog

Laila = Quest[3][98]Prog 0
Harmodios = Quest[3][98]Prog 1
Laila = Quest[3][98]Prog 2
--!checkvar playername Quest[3][98]Timer--
--!setvar playername Quest[3][98]Timer (Timer value -1)--
Beat Dance battle (Spam first two options in CS)
--automatically zone--
Quest[3][98]Prog jumps to 5
--automatically zone--
Quest[3][98]Prog jumps to 11 breaking the quest from completion and the player from receiving the AF body

This Var will jump from 2 to 5, then 5 to 11

## Expected behavior

Quest[3][98]Prog 7 or 8 will reward the player with the item. We do not make it here

**Comment by claywar** [comment]
Changes to incrementcharvar binding do not pass the correct value to the charutils function.  Fix incoming.
