### ISSUE TITLE
Unknown error crashes！！！！！！

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#2522]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Unknown error crashes, occur frequently, but don't know why

=== Call stack ===
Address           Frame             Function
00007FFE04A99319  000000281A17BC10  RaiseException+69 ()
00007FF7D31CD9DC  000000281A17BC40  WheatyExceptionReport::WheatyCrtHandler+2C (C:\server\src\common\WheatyExceptionReport.cpp, line 330)
00007FFDF288AF0F  000000281A17BCA0  _invalid_parameter+CF ()
00007FF7D31E4ED9  000000281A17BCE0  std::clamp<float,std::less<void> >+99 (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\algorithm, line 9808)
00007FF7D31E0A8F  000000281A17BD20  std::clamp<float>+3F (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\algorithm, line 9828)
00007FF7D36C6772  000000281A17BEE0  CAttack::ProcessDamage+D82 (C:\server\src\map\attack.cpp, line 601)
00007FF7D3246F11  000000281A17C380  CBattleEntity::OnAttack+DE1 (C:\server\src\map\entities\battleentity.cpp, line 1837)
00007FF7D3253D2F  000000281A17C3D0  CCharEntity::+5F (C:\server\src\map\entities\charentity.cpp, line 929)
00007FF7D3220E8A  000000281A17C500  CAttackState::Update+10A (C:\server\src\map\ai\states\attack_state.cpp, line 66)
00007FF7D3234121  000000281A17C540  CState::DoUpdate+51 (C:\server\src\map\ai\states\state.cpp, line 89)
00007FF7D3237B14  000000281A17C640  CAIContainer::Tick+2F4 (C:\server\src\map\ai\ai_container.cpp, line 404)
00007FF7D37A0189  000000281A17D4E0  CZoneEntities::ZoneServer+1A09 (C:\server\src\map\zone_entities.cpp, line 1516)
00007FF7D37AB16D  000000281A17D550  CZone::ZoneServer+3D (C:\server\src\map\zone.cpp, line 847)
00007FF7D37A84A4  000000281A17D5C0  zone_server_region+94 (C:\server\src\map\zone.cpp, line 90)
00007FF7D31C0139  000000281A17D700  CTaskMgr::DoTimer+1B9 (C:\server\src\common\taskmgr.cpp, line 122)
00007FF7D31807DA  000000281A17F800  main+20A (C:\server\src\common\kernel.cpp, line 283)
00007FF7D38052C9  000000281A17F850  invoke_main+39 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 79)
00007FF7D380521E  000000281A17F8C0  __scrt_common_main_seh+12E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 288)
00007FF7D38050DE  000000281A17F8F0  __scrt_common_main+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 331)
00007FF7D380533E  000000281A17F920  mainCRTStartup+E (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp, line 17)
00007FFE05DD7974  000000281A17F950  BaseThreadInitThunk+14 ()
00007FFE0878A2F1  000000281A17F9D0  RtlUserThreadStart+21 ()
[xi_map.exe_14-8_12-44-32.log](https://github.com/LandSandBoat/server/files/9332709/xi_map.exe_14-8_12-44-32.log)

Crash dump file link: https://wetransfer.com/downloads/b2ac7cd4cf2b655b7de5c70b374b222a20220815154435/ab799ba688c92452b7ce0d969c10b4b120220815154508/65e46c

![QQ截图20220815235226](https://user-images.githubusercontent.com/89332550/184669644-ec2fbc06-7250-4afc-8118-53829128454c.png)

**Comment by WinterSolstice8** [comment]
Can't help much here without the crash dump file that's generated, the log file alone doesn't tell me much.

**Comment by Freetate** [comment]
> 如果没有生成的故障转储文件，这里无济于事，仅日志文件并不能告诉我太多。
where can i find crash dump file, i upload

Or how the crash dump file should be generated,？

**Comment by CatsEyeXI** [comment]
> > 如果没有生成的故障转储文件，这里无济于事，仅日志文件并不能告诉我太多。
> > where can i find crash dump file, i upload
> 
> Or how the crash dump file should be generated,？

While the xi_map process is running, open visual studio and from the debug menu select "Attach to Process".
Find xi_map in the process list and attach to it. When a crash is encountered, it will be caught in the debugger for you to review. You can save the dump by selecting "Save Dump As" from the File menu. Take this .dmp file, and zip it up along with your xi_map.pdb and xi_map.exe and share here.

When you attach it here, please also do a !build in game so we know what commit you are on.
