### ISSUE TITLE
🐛 Logic using MAGIC_TAKE listener is executed twice 

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2531]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Spoke about this briefly in discord, here's what @DiscipleOfEris came up with:
```
There are two points in the code when it gets triggers
CMagicState::Update() and luautils::OnMagicHit()
luautils::OnMagicHit() gets called in CBattleEntity::OnCastFinished()
Yeah, looks like MAGIC_TAKE is getting called twice, in two different places at the same time.
MAGIC_TAKE is the only triggerListener in luautils 
```
## Expected behavior

The logic inside this function should only be executed once

**Comment by TeoTwawki** [comment]
Note: this behavior used to be _expected_ if onMagicHit is in the script (even if empty), however per chat in discord he doesn't have that function in his script, so it feels likely to me that at some point a rework changed how onMagicHit gets called (or listener "moved" but duplicated) resulting in this.

**Comment by DiscipleOfEris** [comment]
The `MAGIC_TAKE` event is emitted in `luautils::OnMagicHit()` *only* after `MAGIC_TAKE` is emitted in `CMagicState::Update()`. There's no reason to have the listener trigger in `luautils::OnMagicHit()` since it's always guaranteed to have already just triggered.
