### ISSUE TITLE
Player DRG: Wyvern is despawned upon zoning

### ISSUE THREAD

**Issue by SirGouki** [DerpyProjectGroup/topaz#2535]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Be DRG
2. Call Wyvern
3. Zone
4. Wyvern is gone.

## Expected behavior

The wyvern is supposed to stay with the player until desummoned/logged out/KOd or the player is KOd.  1 exception to this (the only one I know of) is when zoning into a town, the mob is "put away" and comes back out when they leave the town into a field zone.

**Comment by DiscipleOfEris** [comment]
I opened an identical issue at the same time. #2536
