### ISSUE TITLE
🐛 Login server stops handling new connections after a while

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2541]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

I don't think this is a new issue. We just probably never stayed "up" long enough in the past to really notice it. Began noticing this first following the improvements made to clean up sessions to keep the fd count from climbing.

```
[08/16/22 10:53:58:612][login][error] connect_client: accept failed (code 10024)! (connect_client:751)
[08/16/22 10:53:58:853][login][error] connect_client: accept failed (code 10024)! (connect_client:751)
[08/16/22 10:53:58:982][login][error] connect_client: accept failed (code 10024)! (connect_client:751)
[08/16/22 10:54:01:284][login][error] connect_client: accept failed (code 10024)! (connect_client:751)
```

Based on the code here, it doesn't appear normal for `fd == -1` 
```
    fd = sAccept(listen_fd, (struct sockaddr*)&client_address, &len);
    if (fd == -1)
    {
        ShowError("connect_client: accept failed (code %d)!", sErrno);
        return -1;
    }
```

Admittedly I know nothing about this, but did we run out of fd's and that is why the error was generated?

## Expected behavior

No errors expected

**Comment by zach2good** [comment]
This is a super duper old bug that we've never really found the cause for, we are never releasing fd's under certain conditions. I put in some logging to try and track it down (fd count etc.) but we've never been able to repro it locally.

There is a really janky fix: auto restart your login server every couple of hours :(

**Comment by TeoTwawki** [comment]
> Admittedly I know nothing about this, but did we run out of fd's and that is why the error was generated?

if you run out of sockets (which by default stop at 1024) it will say `"New socket <number here> is greater than can we handle!"` instead.

Edit:

Actually, I see contradictory information regarding `code 10024` with some use of it for "duplicate connection" and some for "too many open sockets". I wonder if our check order is wrong so the correct message never gets hit.

**Comment by TeoTwawki** [comment]
I think my initial reply is wrong, and somehow this id indeed exceed the max sockets. But I don't see how/why at all.

@CatsEyeXI next time this happens ping us here, I want to check something if I can before you have to reset it.

**Comment by CatsEyeXI** [comment]
> I think my initial reply is wrong, and somehow this id indeed exceed the max sockets. But I don't see how/why at all.
> 
> @CatsEyeXI next time this happens ping us here, I want to check something if I can before you have to reset it.

will do

**Comment by CatsEyeXI** [comment]
@TeoTwawki pinging you per your request.

**Comment by CatsEyeXI** [comment]
![image](https://user-images.githubusercontent.com/65316697/186821967-4f6ba27e-d700-4ebb-9a64-f6f9757a3431.png)
