### ISSUE TITLE
🐛 <BUG> The recurring and unknown reason xi_map crashes!

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#2542]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

I'm using LSB from 4 days ago, only customized the abyssea monster script, and hidden a few NPCs, I've tested these changes over and over again without any problems.

I don't know why the crash often occurs, the shortest time is a few minutes, the longest time is more than 10 hours, the following is the error dump file

https://wetransfer.com/downloads/ce8f1dc152bbfe860d409015272f2b7820220816151252/61d5613a9d0236e31db7f05b5c4cbfb420220816151320/722aab

https://wetransfer.com/downloads/8d3f7d7f10c9a7748513d300840754b720220816151659/a70901b69f7b4bfd445281f8a8f6d87120220816151726/b83186

It's a crash in two time periods, but I guess the problem should be one

## Expected behavior

I'm going crazy
I really can't solve it myself, so I hope I can get the cause of the problem here and get the solution to the problem, thank you very much!

**Comment by WinterSolstice8** [comment]
Both crash dumps appear to be within checks for [Restraint](https://www.bg-wiki.com/ffxi/Restraint), I can't reproduce the crash on my end in a random zone, will look more into it later.

**Comment by Freetate** [comment]
> Both crash dumps appear to be within checks for [Restraint](https://www.bg-wiki.com/ffxi/Restraint), I can't reproduce the crash on my end in a random zone, will look more into it later.

Thank you so much, this has been bugging me for a long time, driving me crazy!
