### ISSUE TITLE
Wrong MH zone and Client Crash

### ISSUE THREAD

**Issue by SirGouki** [DerpyProjectGroup/topaz#2546]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Make a new character
2. Make it a GM
3. use !changejob JOB 75 (where JOB is any valid Job shorthand, such as RDM)
4. enter moghouse (I did this in southern sandy)
5. go through the RoV cutscene

After the cutscene plays, you will be in your mog house, but the zone is the zone you entered it from.  If you try to zone out, it causes a client crash.

Reloading the character seems to place the character in the correct MH zone.

## Expected behavior

Character should be in the proper MH zone.

**Comment by TeoTwawki** [comment]
This is a result of mog houses not being a true zone. They are the zone you entered from, legit. In retail its more of a sub-zone.

So your GM command increased your level making you meet the requirements for that cs, but when you moved into the mog you "rezoned" into what is technically the same zone, normally not possible to make this trip. We can probably add a check for mog house to its conditional tho to avoid confusion.

**Comment by TeoTwawki** [comment]
Wanna try the PR I just opened @SirGouki ?
