### ISSUE TITLE
🔨 LGTM.com is going away

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#2553]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

I just saw this:

> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. 

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

I guess we'll need to update stuff

**Comment by EpicTaru** [comment]
How sad, what acronym are we gonna be able to use now?  GHCS doesn't have the same ring to it as LGTM does!
