### ISSUE TITLE
🐛 System Messages not being relayed reliably in multi-process setup

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2563]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Zones I wasn't able to send a system message in, Reisenjima Henge, Escha RuAun.

![image](https://user-images.githubusercontent.com/65316697/185727045-c510f89d-72eb-425a-a1bc-565e1c1a3de9.png)

## Expected behavior

Messages should work across processes

**Comment by WinterSolstice8** [comment]
smells like firewall/network configuration, messages like this are "multi process" by default, they go through a separate process even if you only have one xi_map running all instances. Likely zmq can't reach the process that isn't running on the same machine

**Comment by CatsEyeXI** [comment]
Hmm... Maybe something in the conf files. I'll have a look tomorrow to double check. No firewall running on the machine and machine is on a public IP.

**Comment by TeoTwawki** [comment]
The outgoing message isn't coming back to same exe instance you ran it from, traffics stopped somewhere on that instance of the exe. Your screenshot only shows the senders perspective, but I doubt a 2nd char in the zone (or other zones) would see it either. Almost certainly a network traffic problem of some kind.

**Comment by CatsEyeXI** [comment]
> The outgoing message isn't coming back to same exe instance you ran it from, traffics stopped somewhere on that instance of the exe. Your screenshot only shows the senders perspective, but I doubt a 2nd char in the zone (or other zones) would see it either. Almost certainly a network traffic problem of some kind.

Yeah, I can't send myself tells either...

**Comment by CatsEyeXI** [comment]
It's working now, and I **swear** that all I did was restart the login server. >.>
![image](https://user-images.githubusercontent.com/65316697/185742637-0a754716-3ee9-420f-8c4b-ddec6541c8a0.png)

**Comment by EpicTaru** [comment]
Wonder if above issue as well as this issue (linked) are being caused by same issue?

https://github.com/LandSandBoat/server/issues/2492

**Comment by TeoTwawki** [comment]
> Wonder if above issue as well as this issue (linked) are being caused by same issue?
> 
> #2492

nope. but I think it may be related to their other lobby issue where characters suddenly can't log in.
