### ISSUE TITLE
🐛 Crash when releasing trusts during Level Up animation (race condition?)

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2571]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

It was our own @SirGouki that found this while playing. Per his explanation:
`the level up effect was still on the screen when I hit the macro to do /retr
as soon as I hit it R went 0`

Dump:
https://drive.google.com/file/d/1-uiH1-122lzdPygwGz8OBx24gXWe8mM8/view?usp=sharing

Build a86c9818a

## Expected behavior

Trusts should finish leveling up before obeying /retr command (this is an assumption based on what i think the problem is)

**Comment by zach2good** [comment]
Notes:

```
 	[Inline Frame] xi_map.exe!gambits::CGambitsContainer::{dtor}() Line 225	C++
 	[Inline Frame] xi_map.exe!std::default_delete<gambits::CGambitsContainer>::operator()(gambits::CGambitsContainer *) Line 3125	C++
 	[Inline Frame] xi_map.exe!std::unique_ptr<gambits::CGambitsContainer,std::default_delete<gambits::CGambitsContainer>>::{dtor}() Line 3233	C++
 	xi_map.exe!CTrustController::~CTrustController() Line 60	C++
 	[External Code]	
 	xi_map.exe!CBaseEntity::~CBaseEntity() Line 59	C++
 	[External Code]	
>	xi_map.exe!CZoneEntities::ZoneServer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, bool check_regions) Line 1492	C++
 	xi_map.exe!CZone::ZoneServer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, bool check_regions) Line 847	C++
 	xi_map.exe!zone_server(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick, CTaskMgr::CTask * PTask) Line 80	C++
 	xi_map.exe!CTaskMgr::DoTimer(std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>> tick) Line 122	C++
```

`zone_entities.cpp`, `CZoneEntities::ZoneServer`
```cpp
                for (EntityList_t::const_iterator it = m_charList.begin(); it != m_charList.end(); ++it)
                {
                    CCharEntity* PChar = (CCharEntity*)it->second;
                    if (distance(PChar->loc.p, PTrust->loc.p) < 50)
                    {
                        PChar->SpawnTRUSTList.erase(PTrust->id);
                        PChar->ReloadPartyInc();
                    }
                }

                delete trustit->second;              // <-- here
                trustit->second = nullptr;
                m_trustList.erase(trustit++);
```

Gambits container is still populated, as is POwner inside the trust that is being deleted. TrustList seems fine. Can't see anything obviously wrong at first glance

**Comment by SirGouki** [comment]
@CatsEyeXI trusts do not level up with the player, you have to recast them (hence the /retr all as I leveled).

I will also note, this is extremely hard to reproduce, as I tried for a good while on my LAN server and never made it happen.

**Comment by CatsEyeXI** [comment]
> @CatsEyeXI trusts do not level up with the player, you have to recast them (hence the /retr all as I leveled).
> 
> I will also note, this is extremely hard to reproduce, as I tried for a good while on my LAN server and never made it happen.

yep, im aware...

**Comment by CatsEyeXI** [comment]
@SirGouki  can we close this out? Seems like such a 1/million chance.
