### ISSUE TITLE
🔨 <Item_Mods Updated>

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#2575]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

Added in some item mods in and around the 18000 - 19000 (ffxiah number) area, not sure how to do a pull request and i don't want to mess anything up.

**Comment by EpicTaru** [comment]
Do you have a link to the branch you added these mods onto?  Someone else can PR them for you and co-author a PR.

**Comment by EpicTaru** [comment]
And this convo can probably be moved to a Discussion. 

https://github.com/LandSandBoat/server/discussions/new

**Comment by Aeisu** [comment]
best left in the hands of the experts ^^
https://github.com/Aeisu/LSB_Item_Mod_Revisions

I will close this off to clear up space and continue on slogging through the code.
