### ISSUE TITLE
🐛 Mother Globe's LUA crashes the server when zoning into The Shrine of Ru'Avitau

### ISSUE THREAD

**Issue by Schaedelschaden** [DerpyProjectGroup/topaz#2577]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Pull the LSB base branch from the repository.
2. Compile the server.
3. Load the server.
4. Enable debugging in Visual Studios and attach it to xi_map.exe.
5. Type `!zone 178`.
6. Observe xi_map.exe crashing on zone in.

## Expected behavior

Players zoning to The Shrine of Ru'Avitau should not be crashing the server.
Mother Globe attempting to set positions for the Slave Globes should not be crashing the server.

Visual Studio generated the following debugging information:
![devenv_5ggDQRA2lW](https://user-images.githubusercontent.com/16365541/185819593-c243f507-085c-40dd-be84-c944e869b308.png)

Mob information was obtained from the `DoRoamTick` function.

The CNavMesh `validPosition` function is causing an exception due to a read access violation.
![devenv_LfEpHTKx1h](https://user-images.githubusercontent.com/16365541/185819930-cff94374-3e61-45da-ae6a-0e5dd4534989.png)

Commenting out the `calculateValidSlaveGlobePositions` function in scripts\zones\The_Shrine_of_RuAvitau\mobs\Mother_Globe.lua caused errors in the LUA but did not cause the server to crash when a player zoned into The Shrine of Ru'Avitau.
https://github.com/LandSandBoat/server/blob/a1de81fca66f71e525a36eba58eed4c46ce5654e/scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua#L48-L69

**Comment by WinterSolstice8** [comment]
looks like navmesh is missing, is your submodule updated? (this probably shouldn't crash)

try: `git submodule init` and `git submodule update`

**Comment by TeoTwawki** [comment]
that check of `if (!navmesh)` followed by returning true was intended to evade exactly this crash problem - if no navmesh, all points are valid, no obstacles to avoid

**Comment by WinterSolstice8** [comment]
```
bool CLuaZone::isNavigablePoint(const sol::table& point)
{
    // clang-format off
    position_t position
    {
        point["x"].get_or<float>(0),
        point["y"].get_or<float>(0),
        point["z"].get_or<float>(0),
        point["moving"].get_or<uint16>(0),
        point["rot"].get_or<uint8>(0)
    };
    // clang-format on

    return m_pLuaZone->m_navMesh->validPosition(position);
}
```

real crash is `m_NavMesh` being null and not being checked if not null. I'm guessing this should return false and warn if m_navMesh is null

**Comment by Schaedelschaden** [comment]
Winter's suggestion of `git submodule init` and `git submodule update` did work for resolving the crash, thank you Winter!

Should I mark this as resolved in any way or leave it open for a potential check inside `isNavigablePoint`?

**Comment by WinterSolstice8** [comment]
We should absolutely have a better fix so people can know they are missing navmesh rather than a mystical crash. Go ahead and leave it open.

**Comment by WinterSolstice8** [comment]
p.s. @Schaedelschaden Navmeshes are apparently supposed to be optional, which I didn't know the history of. If things act differently than you expect with mob pathing and you don't like it you can remove the navmeshes and it will go back to the old behavior.
