### ISSUE TITLE
🐛 MR in Promy's only send to 1 of the 3rd islands.

### ISSUE THREAD

**Issue by hooksta4** [DerpyProjectGroup/topaz#2591]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

It should transport entire party to same island and not be like a 50/50 thing per player. Not sure if its an ontime thing or not??

## Expected behavior

Not a multilevel dungeon. There are five islands. To reach the [Spire of Dem], you must travel through four of the islands. There are two possible islands that can be reached when entering a memory stream on the second island. Whichever third island you end up on will take you to the final island, bypassing the alternate third island.

**Comment by Xaver-DaRed** [comment]
I fixed this when I rewrote promyvions.
