### ISSUE TITLE
Survival Guides are broken

### ISSUE THREAD

**Issue by AuroraFlare** [DerpyProjectGroup/topaz#262]
- [X] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [X] I have specified what branch this happens on branch: EVERYTHING

When talking to a survival guide it doesn't work.

What I did for a temp fix was:
In the survival_guide.lua i changed local survivalGuides, zoneIdToGuideIdMap = require("scripts/globals/survival_guide_map") back to require("scripts/globals/survival_guide_map") and it worked. However I'm assuming this change was on purpose for the lua refactoring.

**Comment by claywar** [comment]
Interesting that it worked on your end, since those are both local variables being returned.  Which survival guide NPC was giving you an issue?

**Comment by zach2good** [comment]
(Admittedly, I didn't test this change when I did it 👀 ...)

**Comment by AuroraFlare** [comment]
I was using the Aht Urhgan survival guide :) 

Edit: Can confirm it was also not working for W. Ronfaure and Bastok Mines from other players!

**Comment by claywar** [comment]
```
[01/Jun] [15:46:50] [Error] luautils::onTrigger: .\scripts/globals/survival_guide.lua:102: attempt to index upvalue 'zoneIdToGuideIdMap' (a nil value)
stack traceback:
        .\scripts/globals/survival_guide.lua:102: in function 'onTrigger'
        ./scripts/zones/Northern_San_dOria/npcs/Survival_Guide.lua:10: in function 'fallbackHandler'
        .\scripts/globals/interaction/interaction_lookup.lua:404: in function <.\scripts/globals/interaction/interaction_lookup.lua:367>
        ```
Investigating

**Comment by TeoTwawki** [comment]
> (Admittedly, I didn't test this change when I did it 👀 ...)

zach2bad now
![image](https://user-images.githubusercontent.com/6871475/120381608-acaeab80-c2f0-11eb-8672-7c791a295b93.png)

Edit: managed to quote wrong post

**Comment by claywar** [comment]
@dgeek Thank you very much for this report!  #263 should address this issue.

**Comment by claywar** [comment]
Updated method of addressing to avoid confusion in the future.  The map file now returns an object which contains those two tables.  Updated the survival guide lua to reference properly.
