### ISSUE TITLE
🐛 Script/Skillchain error shows mob id instead of target name

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2626]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

`base`

## Steps to reproduce
I was writing a skillchain and alias script. I forgot to add /ws in script so this happens when I am executing them, it shows the mob id number in /say.  So after I fixed and added /ws and it works normal, showing the monster name instead of mob ID. It was Goblin Mugger I think.

## Expected behavior

Shows monster name when [t]

![mob id](https://user-images.githubusercontent.com/40586417/187778569-033d8a4b-6ba5-44a9-afa9-259aeec1fd0f.jpg)
![sc](https://user-images.githubusercontent.com/40586417/187778595-a101990f-a1c2-4e88-8a82-de73a8ee89af.jpg)
![alias](https://user-images.githubusercontent.com/40586417/187778605-d32e15a3-a7a4-4e29-b870-eb6b7a7eae24.jpg)

**Comment by WinterSolstice8** [comment]
This isn't an LSB bug

**Comment by Zofra2020** [comment]
Oh it isnt? my bad

**Comment by WinterSolstice8** [comment]
Arguably, it's a "feature" -- <t> translates to an ID internally and sometimes with addons it leaks out like that. No worries
