### ISSUE TITLE
🐛 SaveZonesVisited does not register Escha ZiTah (and possibly other zone ids > 250)

### ISSUE THREAD

**Issue by neuromancerxi** [DerpyProjectGroup/topaz#2627]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Check SQL Char > zones blob
2. Zone into Escha ZiTah
3. Zone out of Escha ZiTah
4. Note SQL Char > zones blob is unchanged

Initial thought is m_ZonesList doesn't support larger than uint8.

https://github.com/LandSandBoat/server/blob/base/src/map/entities/charentity.h#L309

Testing Script (~/scripts/commands/haszone.lua):

```lua
--------------------------------------------------------------------------------------------------
-- func: haszone
-- desc: checks zone data
---------------------------------------------------------------------------------------------------

cmdprops =
{
    permission = 1,
    parameters = "i"
}

function onTrigger(player, id)
    if player:isZoneVisited(id) then
        player:PrintToPlayer(string.format("Player has been to zone: %i ", id), xi.msg.channel.SYSTEM_3)
    end
end
```
`!zone 288`
`!zone 33`

`!haszone 288` will return an error in console log: `hasBit: value (288) is out of range (hasBit:250)`
`!haszone 33` will return `Player has been to zone: 33`

## Expected behavior

Zoning into Escha ZiTah should register an update in SQL Char > zones

**Comment by TeoTwawki** [comment]
possibly blob expansion needed in addition to larger cast

**Comment by claywar** [comment]
With those recent zone reappropriations, did we increase the size?

**Comment by claywar** [comment]
@neuromancerxi Can you try changing the array length to 37?  It seem's we're OBO on that zone, but I'm also swamped at the moment.  (36*8 == 288, so one greater than the max array index).

**Comment by neuromancerxi** [comment]
Widening it from 36 to 37 in charentity and zone_visited seems to work:

![image](https://user-images.githubusercontent.com/3996176/187824136-112545a9-ea54-41e3-9c73-3ca6550bd59d.png)

Would we need a migration for this change, or can I submit the two 36->37 changes without one?
