### ISSUE TITLE
🐛 Anillah NPC(cloth craft guild)

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2639]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

NPC Anillah

`base`

## Steps to reproduce
Talked to this NPC to get recipe, after I clicked amateur, my character froze cant move or open menu. So I tried again, same result.

## Expected behavior

Tell me the recipe!
![Amateur](https://user-images.githubusercontent.com/40586417/188042801-10da6663-4212-4bf5-9f02-83530c086679.jpg)
![cloth craft npc bug Anillah](https://user-images.githubusercontent.com/40586417/188042808-51be80d3-5e5a-41d1-9bb2-8082ac23e9be.jpg)
![information synthesis](https://user-images.githubusercontent.com/40586417/188042809-3dca4c8c-af26-4c54-9279-620a1de52873.jpg)

**Comment by Zofra2020** [comment]
Well kinda related but just different NPC next to Anillah. Gives no info about it too.
![weaverTerude-Harude](https://user-images.githubusercontent.com/40586417/188338954-de41c66d-cbd2-4890-afee-ab941b04acb9.jpg)

**Comment by claywar** [comment]
For non-list items, can't help that.  Either we have enough entries for crafts or we don't.
