### ISSUE TITLE
🐛 Beastmaster ability disappear

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2644]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
## Branch affected by issue 
`base`
## Steps to reproduce

Running 4 BST and they are level 26.  I don't know what really causes this.  I am running a sync party so maybe the level sync feature when I level up causes this.  So, couple of my ability disappear on 2 characters but other 2 characters is normal.  I tried turn off level sync to see if skill comes back, it doesn't.  Tried to zone other area, doesn't work too. So I relogged and the ability didn't come back either. So, I restarted the client, doesn't work either.  Restarted the server, doesn't work either.  If you can point me where I can find the log to cause this issue, I would gladly to provide.
1 char lost both call beast and bestial loyalty.
1 char lost only bestial loyalty.(now lost call beast after change job method)
Call beast and Bestial Loyalty is level 23 skill.
Is there way to give those character ability back?(delete aix.dat in user folder will get this back but bug will still come)

![lvl 26](https://user-images.githubusercontent.com/40586417/188242061-69d67018-a0e5-423e-8f62-774feac80923.jpg)
![nocallnoloyal](https://user-images.githubusercontent.com/40586417/188242062-9e5349cb-fc2a-4468-8078-c78d838f80ec.jpg)
![yescallnoloyal](https://user-images.githubusercontent.com/40586417/188242063-3aec5c26-b2c3-477d-8a4a-6c28859418bd.jpg)

## Expected behavior
Ability should not disappear.(probably because of addon/plugins conflicts)

**Comment by Zofra2020** [comment]
Update: I deleted both user aix.dat in user folder and those abilities comes back
Update2: When getting bestial loyalty and call beast back, sometime the pet command disappear even you have pet out. Getting those bugs more and more. Affects all 4 chars as well.

**Comment by Zofra2020** [comment]
![27bstloseabilities](https://user-images.githubusercontent.com/40586417/188332931-b5537789-fd9a-4165-8351-1412e98bf4c4.jpg)
27 bst lost all ability but 2 on 1 char.

**Comment by Zofra2020** [comment]
I stopped playing bst for awhile because of this. So I start playing summoner, I guess the issue is still the same. However, when i summon carby again, the ability comes back(sometimes).

![smn pet ability disappear](https://user-images.githubusercontent.com/40586417/189239093-abcab631-36e4-4eb5-844e-c9284b6c51e5.jpg)

**Comment by Zofra2020** [comment]
![ws too](https://user-images.githubusercontent.com/40586417/189435803-2effa73a-048f-4854-890c-d73f8f444292.jpg)
weaponskills too, disappearing or get bugs like this...

**Comment by TeoTwawki** [comment]
Close your game and everything else fully.

Open an admin level command prompt (search cmd, right click it, run as admin)

`DISM.exe /Online /Cleanup-image /Restorehealth`

`sfc scannow`

There is just no way more we would be seeing the same thing as you if it were a program bug in the server software. The fact deleting a file at the client temporary fixes things is a hint that maybe your os or hdd is having a problem.

**Comment by TeoTwawki** [comment]
Git hun isn’t letting me edit so:

`sfc /scannow`

Needs the slash and 2 n

**Comment by TeoTwawki** [comment]
GitHUB jfc spellcheck! No more posting from an iphone...

**Comment by Zofra2020** [comment]
I'm using window 11 and 1tb SSD Drive
I didn't touch anything about that issue.  I only adjust the exp rate, drop rate, wardrobe, all those things.
I'm using ashita v3.
![ver](https://user-images.githubusercontent.com/40586417/189451914-c0dd2ddb-b261-41f0-98ef-30bac64faec4.jpg)
![scan](https://user-images.githubusercontent.com/40586417/189451921-3083fc3a-deb9-4f7c-9202-65311624474a.jpg)

**Comment by TeoTwawki** [comment]
those 2 commands ruled out damage to win11's OS files. what addons and plugins you use with ashita v3 ?

**Comment by Zofra2020** [comment]
![addon](https://user-images.githubusercontent.com/40586417/189453358-de3d43a9-52ab-467b-b205-68c71569bf7b.jpg)
![plugin](https://user-images.githubusercontent.com/40586417/189453369-3c8d9a40-f9bd-442c-9768-eed8a7197c29.jpg)

**Comment by TeoTwawki** [comment]
thats.. lets try this another way. using cmd again,  I want you to launch the pol.exe from ashita directly. you won't have any addon or plugin and you'll need to put `-- server urlHere` on the command line after the exe. See if you can make the bug happen again while in that state.

**Comment by Zofra2020** [comment]
You mean xiloader?  The resolution is off hehe.  I guess I cant multi box this way without multisend but sure I'll try play solo and test.
![polxiloader](https://user-images.githubusercontent.com/40586417/189454975-72faa448-274f-487f-98b3-15d0680fa268.jpg)

**Comment by TeoTwawki** [comment]
it defaults to what ffxi's registry settings are when launched without ashita. and yes that is xiloader - ashita just pre-renames it so that 3rd party stuff that looks for "pol.exe" in memory can find it.

**Comment by TeoTwawki** [comment]
this also might be stupid of me to ask but has a file check been run? And was this a typical install from SE's installer, or some server's own installer?

**Comment by Zofra2020** [comment]
I use SE/playonline website to download those 1exe and 4.rars.
http://www.playonline.com/ff11us/download/media/install_win.html
And yes I did delete 0.dat and run file check with pol

**Comment by Zofra2020** [comment]
I switched to windower and see if the issue still come. I just started today, so far no problem.  Will keep testing and see.  It could be some plugins/addon in ashita causing this issue. Cannot say right now after testing smn and bst more this week.

**Comment by WinterSolstice8** [comment]
Things that might cause this in your pics for Ashita were xipivot which can load old/wrong DATs for UI and/or items, etc and "Dats.dll" which screams suspicious to me. Did you ever play on a private server other than your own with that Ashita install?

**Comment by TeoTwawki** [comment]
> I switched to windower and see if the issue still come. I just started today, so far no problem. Will keep testing and see. It could be some plugins/addon in ashita causing this issue. Cannot say right now after testing smn and bst more this week.

bear in mind the reason I wanted to test with the bootloader alone was that windower and ashita often have equivalent addons/plugins that players are likely to use if the switch to the opposite platform, one of which could be doing something that is the trigger for the issue.

**Comment by TeoTwawki** [comment]
back when the ci was travis there actually used to be something I could embed in the commit message to tell it to skip a check.

**Comment by TeoTwawki** [comment]
wtf github

**Comment by Zofra2020** [comment]
Yeah, It could be xipivot.  I played some on catseye then switched to my own private server.  As for bootloader alone, the resolution is way off, I cant play like that.  I tried change the resolution in ffxi config, regedit no luck. Only way I can do is launch ashitav3 but loads nothing(default script blank).  Yeah, I plan to test ashita after Im done with windower(if theres no issue).  Then I can test 1 plugin/addon a time to find the culprit.  Sadly, the ffxidb plugin doesn't seem to work with private server, it connects for a few seconds then closes. EDIT: I was able to get ffxidb working by blocking windower's update connection and use older version of ffxidb.

**Comment by claywar** [comment]
Not to sound blunt, but this project does not support any addons or plugins from other things you may be using.  We use them, yes, but that is not something we can fix unless there's an error in our codebase regarding packets.

I use Windower as a default on both my local testing environment and in retail without issue (and I'd honestly love to be using Ashita for some of its features).

**Comment by Zofra2020** [comment]
I have no problem with Windower with this for few days. So probably somewhere in Ashita's addon/plugin causing this issue. Its possible that it is xipivot. So this is non-relate with LSB so I will just close this. @claywar I have nothing against Ashita, I have used both and I liked both.
