### ISSUE TITLE
<XI_MAP> Character unable to load if death

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#2653]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Log in with char.
Go outside
Get killed by mob
Close Session (without raising or going back to homepoint)
Log back in with char.
Char won't load. Error code: FFXI-3001

## Expected behavior

Should be able to log back in still dead

**Comment by WinterSolstice8** [comment]
I could only produce this once, every other time it worked as expected

**Comment by kaincenteno** [comment]
for it's the moment i die. and then if i try to log back in again it will give me black screen. then I log off and everything is okay. Dunno if it has to do with it not being a clean log off and still char still showing online. will try again
