### ISSUE TITLE
🔨 Implement more accurate Ul'xzomit roaming behavior

### ISSUE THREAD

**Issue by DiscipleOfEris** [DerpyProjectGroup/topaz#2668]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

My FFXI Capture request was completed (except for confirmation that clusters are a slotted drop). See https://www.youtube.com/watch?v=Qa66dBOMplM

Observations:

 * The respawn on both Ul'xzomit mothers and babies is 5 minutes, not 16 minutes. Was there a patch that reduced spawn times, or was the wiki just wrong (not surprising)?
 * Mother roams continuously without pause.
 * Babies follow toward the mother on a slightly meandering path. They don't specifically try to get behind her.
 * Babies follow continuously without pause except when too close.
 * If mother gets too close (crosses back over them) the baby will stop. They will not specifically turn to face the mother.
 * The babies seem to follow the same path (with slight offset) and thus stick together pretty closely while following, unless one ends up much further than the other.
 * The slight offset the babies have from eachother seems to be a static world coordinate offset, rather than relative to mother.
 * Babies and mothers have same health (~4000-4500)
 * When the mother despawns, the babies detach and roam (separately) with a similar continuous roaming pattern to the mother.
 * When the mother respawns, the babies will return to following her no matter the distance. They don't *seem* to warp.
 * When the babies respawn, they will return to following the mother, no matter the distance. They don't *seem* to force spawn next to mother.
 * The babies can respawn whether the mother is in combat or not.
 * Babies link within what looked like roughly ~5 yalms. Only really noticeable when a baby respawns.

Assumptions:

 * I didn't ask for a test on whether the babies can respawn while the mother is dead. I'm going to assume they can, and will just reattach when the mother spawns.

**Comment by TeoTwawki** [comment]
> The respawn on both Ul'xzomit mothers and babies is 5 minutes, not 16 minutes. Was there a patch that reduced spawn times, or was the wiki just wrong (not surprising)?

quite possibly either or BOTH o.o due to people editing the wiki based on things they assumed. we'll have to check retail.

**Comment by DiscipleOfEris** [comment]
> > The respawn on both Ul'xzomit mothers and babies is 5 minutes, not 16 minutes. Was there a patch that reduced spawn times, or was the wiki just wrong (not surprising)?
> 
> quite possibly either or BOTH o.o due to people editing the wiki based on things they assumed. we'll have to check retail.

I've been crawling over the patch notes, and only normal mobs in dungeons of original areas had their respawn timers reduced. CoP areas should be unchanged from launch. There's a possibility that wiki editors (and players) assumed Al'Taieu is a "dungeon" and thus has the standard dungeon respawn timers for all mobs. So maybe *all* mobs in Al'Taieu have the "outdoors" respawn of ~5 mins instead. Alternatively, this is just an Ul'xzomit thing that people didn't notice, and all the other mobs have 16 minute respawns.

**Comment by TeoTwawki** [comment]
> I've been crawling over the patch notes, and only normal mobs in dungeons of original areas had their respawn timers reduced. CoP areas should be unchanged from launch. There's a possibility that wiki editors (and players) assumed Al'Taieu is a "dungeon" and thus has the standard dungeon respawn timers for all mobs. So maybe _all_ mobs in Al'Taieu have the "outdoors" respawn of ~5 mins instead. Alternatively, this is just an Ul'xzomit thing that people didn't notice, and all the other mobs have 16 minute respawns.

Even then despite patch notes it wasn't universal because sometime last year (I think? maybe year before that. time flies when you are overworked!) we found some mobs that didn't match what everyone expected but this was only after someone went willynilly changing them to 5 on wiki's and in prs. I have no idea how many might be wrong in the project now. So I just check everything now, just in case. Later today or this weekend I can log into retail and look.
