### ISSUE TITLE
🔨 Disable fishing quests/missions when fishing is disabled

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#2686]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Currently Sandoria mission 3-2 is enabled by default, and fishing is disabled by default. Would be great if a check of the fishing being enabled or disabled can be added to this mission and an audit of other missions/quest that need fishing to prevent PCs from being on a quest/mission accept but unable to be completed

**Comment by TeoTwawki** [comment]
for most servers its completable anyway, because like the crystal bass is sellable so most put it on AH or make it attained another way.

the one that really gets ppl? pld af quest. everyone forgets that till they get a player that is stuck on it lol.

**Comment by SirGouki** [comment]
We've got fishing enabled, and players keep getting stuck on it (PLD AF2 - A Boy's Dream) because they use ffxiclopedia and it tells them to get the odonto near the beginning of the quest... and this breaks the progression.

I remember 14 years ago when I used to tell people to use ffxiclopedia, and I'm regretting it every day now.

**Comment by TeoTwawki** [comment]
> We've got fishing enabled, and players keep getting stuck on it (PLD AF2 - A Boy's Dream) because they use ffxiclopedia and it tells them to get the odonto near the beginning of the quest... and this breaks the progression.
> 
> I remember 14 years ago when I used to tell people to use ffxiclopedia, and I'm regretting it every day now.

https://github.com/topaz-next/topaz/issues/974#issuecomment-747227313

let's make a new issue - that one slipped by in the cluster of topaz project drama sessions
