### ISSUE TITLE
🐛 Garuda Prime- lvl 20 fight(Trial-Size Trial by Wind)

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2719]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 
`base`

## Steps to reproduce
I went to get mini fork of wind from rabao npc.  Went to fight trial level 20 garuda but he casts aero IV which is level 72 BLM spell. He should be casting aero 2 instead.
![20 smn garuda aero 4](https://user-images.githubusercontent.com/40586417/190276686-d84898c0-ce06-43d4-9b72-8f73a955f7a5.jpg)
https://ffxiclopedia.fandom.com/wiki/Summoner:_Level_20_Avatar_Battles_by_Andres#Third_Battle:_Garuda

After I died, I went back and I wasn't able to trade mini fork to Proto Crystal?
![fork smn 20 garuda](https://user-images.githubusercontent.com/40586417/190276637-933d918e-d744-456b-a8ab-aee1038ab876.jpg)

https://www.bg-wiki.com/ffxi/Mini_Fork_of_Wind

## Expected behavior
Aero II instead of Aero IV?
Can use fork again after death?

**Comment by TeoTwawki** [comment]
avatars have skills to fake their spells (because that's what happens on retail too) so it's a mistake in the skill list - probably using same list as the higher level prime.

It would help if all the rows were properly labeled the those who came before us..
```sql
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,867);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,868);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,869);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,870);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,871);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,872);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,873);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',37,874);

INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',324,872);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',324,873);
INSERT INTO `mob_skill_lists` VALUES ('Avatar-Garuda',324,874);

INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,867);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,868);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,869);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,870);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,871);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,872);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,873);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,874);
INSERT INTO `mob_skill_lists` VALUES ('Pet-Garuda',382,875);

INSERT INTO `mob_skill_lists` VALUES ('Mob_Avatar_Garuda',718,869);
INSERT INTO `mob_skill_lists` VALUES ('Mob_Avatar_Garuda',718,871);
INSERT INTO `mob_skill_lists` VALUES ('Mob_Avatar_Garuda',718,873);
```

**Comment by WinterSolstice8** [comment]
>> https://www.bg-wiki.com/ffxi/Mini_Fork_of_Wind
>> Can use fork again after death?

> After completing the quest, or failing the quest, you keep the Mini Fork of Wind. It is not useful, so it should be thrown away. 

Looks like it's a one-time use item and you have to get another once you entered with one

**Comment by Zofra2020** [comment]
Might want to check other kind Avatars's coding too to see if it is the same situation as this.
