### ISSUE TITLE
🐛 Trial of The Magians 4718, 4719, 4698, 4699

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#2720]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Trade Valor Gauntlets +1 to Magian Moogle to begin Upgrade Trial quest 4719
See that the reward is an EXP Ring..... those thieving bastard moogles -.- 

## Expected behavior

Trade Valor Gauntlets +1 to Magian Moogle 
See that the reward is Valor Gauntlets +2 

![img_20220915_113044](https://user-images.githubusercontent.com/64471323/190446468-867439be-2d4c-406c-bb4e-9cc8008f60f6.jpg)

**Comment by Aeisu** [comment]
I found the problem, it lies int he Magians.sql
Line 546 and 547
INSERT INTO `magian` VALUES (4718,15108,0,0,0,0,0,0,0,0,**10796**,0,0,0,0,0,0,0,0,1306,0,50,0,0); -- NQ
INSERT INTO `magian` VALUES (4719,14915,0,0,0,0,0,0,0,0,**10796**,0,0,0,0,0,0,0,0,1307,0,30,0,0); -- HQ

The rewards are incorrect values the lines should read 10696 for Valor Gauntlets +2 not 10796 for Decennial Ring

INSERT INTO `magian` VALUES (4718,15108,0,0,0,0,0,0,0,0,10696,0,0,0,0,0,0,0,0,1306,0,50,0,0); -- NQ
INSERT INTO `magian` VALUES (4719,14915,0,0,0,0,0,0,0,0,10696,0,0,0,0,0,0,0,0,1307,0,30,0,0); -- HQ

https://www.ffxiah.com/item/10696/vlr-gauntlets-2
https://www.ffxiah.com/item/10796/decennial-ring

**Comment by Aeisu** [comment]
![img_20220915_155948](https://user-images.githubusercontent.com/64471323/190497851-768c7af6-aefd-4f19-9a87-d8a42afa0cce.png)
looks like changing the numbers worked

**Comment by Aeisu** [comment]
found another one with the wrong reward 
![img_20220915_163751](https://user-images.githubusercontent.com/64471323/190504544-ddaf19f0-8da6-4e49-a038-5e5166a0da62.png)
 
Magian.sql Line 597 598 should be 10694 not 10794 for Duelist Gloves +2

INSERT INTO `magian` VALUES (4698,15106,0,0,0,0,0,0,0,0,10794,0,0,0,0,0,0,0,0,1306,0,50,0,0); -- NQ
INSERT INTO `magian` VALUES (4699,14913,0,0,0,0,0,0,0,0,10794,0,0,0,0,0,0,0,0,1307,0,30,0,0); -- HQ

INSERT INTO `magian` VALUES (4698,15106,0,0,0,0,0,0,0,0,10694,0,0,0,0,0,0,0,0,1306,0,50,0,0); -- NQ
INSERT INTO `magian` VALUES (4699,14913,0,0,0,0,0,0,0,0,10694,0,0,0,0,0,0,0,0,1307,0,30,0,0); -- HQ

https://www.ffxiah.com/item/10694/dls-gloves-2
https://www.ffxiah.com/item/10794/blenmots-ring

![img_20220915_164743](https://user-images.githubusercontent.com/64471323/190505942-d1aedae6-d867-4734-9f9a-6211124de925.png)

**Comment by Era-Lusiphur** [comment]
Related to #1586
