### ISSUE TITLE
🐛 Weaver's Belt

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2745]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Weaver's Belt not shown in list an option to purchase at novice rank for weaving guild.
Spinning, Fletching, Cloth Purification, Cloth Ensorcellment did show up in the list.
Weaving Belt is not a key item? but there is no other option other than Crystal/Keyitem available to purchase?

## Expected behavior
Weaver's Belt should show in list an option to buy with guild point at novice rank.
https://www.bg-wiki.com/ffxi/Hauh_Colphioh

![weaving belt](https://user-images.githubusercontent.com/40586417/190876222-f1a308d9-4b67-4312-b6ab-670efb9c17ab.jpg)

**Comment by Zofra2020** [comment]
Update: it shows up when apprentice rank which suppose to be novice

![Weaverbeltapprentice](https://user-images.githubusercontent.com/40586417/190879540-ece5e9b8-a0a7-4fe2-a8d6-839d6b96f657.jpg)

**Comment by Zofra2020** [comment]
It is same thing for Leathercraft's novice rank not showing the Tanner's belt. Apprentice rank shows it.  Might be same situation for all other craft guild. https://www.bg-wiki.com/ffxi/Alivatand

**Comment by claywar** [comment]
Current crafting guild implementation has a lot of opportunities, and appears to have not been updated for quite some time.  Stay tuned.
