### ISSUE TITLE
Cannot cast trust magic, elementals and other summons

### ISSUE THREAD

**Issue by GanimanSwift** [DerpyProjectGroup/topaz#2757]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Try to cast a trust, elemental, Fenrir or a few other summons.

This appears in the logs:

`
[09/19/22 19:01:25:245][map][error] luautils::OnCanUseSpell: ./scripts/globals/canusespell_override.lua:113: attempt to index a nil value
stack traceback:
        ./scripts/globals/canusespell_override.lua:113: in function 'getSpellJobPointCostForJob'
        ./scripts/globals/canusespell_override.lua:131: in function <./scripts/globals/canusespell_override.lua:125> (OnCanUseSpell:3927)
[09/19/22 19:01:25:245][map][warn] luautils::onMagicCastingCheck, spell (fenrir) has no lua file, it cannot be cast. (OnMagicCastingCheck:3705)
`
Or..
`
[09/19/22 19:06:17:052][map][error] luautils::OnCanUseSpell: ./scripts/globals/canusespell_override.lua:113: attempt to index a nil value
stack traceback:
        ./scripts/globals/canusespell_override.lua:113: in function 'getSpellJobPointCostForJob'
        ./scripts/globals/canusespell_override.lua:131: in function <./scripts/globals/canusespell_override.lua:125> (OnCanUseSpell:3927)
[09/19/22 19:06:17:052][map][warn] luautils::onMagicCastingCheck, spell (dark_spirit) has no lua file, it cannot be cast. (OnMagicCastingCheck:3705)
`

The lua files exist.

Results in a chat log message like: [Player] cannot cast Fenrir.

## Expected behavior

The magic works

**Comment by WinterSolstice8** [comment]
I know what's wrong and working on fix. I think load order is not consistent on different platforms and exposed a problem.

**Comment by GanimanSwift** [comment]
Thanks for your assistance. I will be waiting for your fix. If there is a PR I can probably test if you need.

**Comment by GanimanSwift** [comment]
@WinterSolstice8 I tried to merge in your branch from the PR. It looks like some of the log messages have cleared up, but am still unable to cast:

```
[09/20/22 00:27:52:079][map][warn] luautils::onMagicCastingCheck, spell (ice_spirit) has no lua file, it cannot be cast. (OnMagicCastingCheck:3705)
[09/20/22 00:28:18:350][map][warn] luautils::onMagicCastingCheck, spell (curilla) has no lua file, it cannot be cast. (OnMagicCastingCheck:3705)
[09/20/22 00:28:27:016][map][warn] luautils::onMagicCastingCheck, spell (fenrir) has no lua file, it cannot be cast. (OnMagicCastingCheck:3705)
```

Also seems like when summoning Siren I get Ramuh.

**Comment by WinterSolstice8** [comment]
Short term hack fix may be emptying the contents of/deleting `scripts\globals\canusespell_override.lua` and restarting xi_map. you'll lose job point spells that way but that's not a big problem relatively

**Comment by GanimanSwift** [comment]
Commenting out the contents of that file or deleting the file causes xi_map to crash.

**Comment by WinterSolstice8** [comment]
Does it crash like that with any error message? I've been trying to reproduce this issue as described a second time to try to understand it better but I just can't seem to get it to happen.

**Comment by WinterSolstice8** [comment]
Can you upload a log file when this is happening? log folder should contain it.

**Comment by WinterSolstice8** [comment]
FYI: I don't think `scripts\globals\canusespell_override.lua` had anything to do with it. They don't even use the same namespace as spells (or at least what is generating your error message)

**Comment by GanimanSwift** [comment]
I found a place where I did a bad merge, log files started to reveal for me after some other changes I tried. Reverted and corrected. Will mark this close. The other error is cleaned up 👍
