### ISSUE TITLE
🔨 Verify requirements to obtain Valkurm Sunsand

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#2788]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature
Previous implementation required player to zone after obtaining sunsand, this needs to be verified along with the messages for obtaining, triggering the qm with a sunsand in inventory, and triggering during non-dust weather.

**Comment by WinterSolstice8** [comment]
QM vanishes during weather that's not earth, reappears when it comes back

during earth weather, from my logs:

`[14:23:16] Obtained: Pinch of Valkurm sunsand.`
-> second click
`[14:23:18] Just a pile of sand.`

3 characters were able to get it within a 15 second window

can't confirm zoning from my logs

**Comment by claywar** [comment]
Addressed the default action in 2787, leaving issue open to confirm zoning logic

**Comment by claywar** [comment]
Added zoning logic back since item is no longer rare in the same PR, closing this with #2787
