### ISSUE TITLE
🔨 [QoL] Survival Guide map flashing icon

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#2798]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Currently, you can collect the teleportation books. But you are unable to see on the map if you have already collected it or not. All teleport books whether you have unlock them will keep on flashing.

Just like crystal teleport points, these books will have to stop flashing if you have already touched it at least once.

This would be really helpful so if you are in a map and you have forgotten to visit the book, you can do so.

**Comment by claywar** [comment]
Got those working locally now, just need to implement the remaining items as well (waypoints, etc) and will resolve.

**Comment by claywar** [comment]
Waypoints are going to need a bit of a refactor for how we store them to get them to stop flashing.  Going to handle that separately from this issue.

**Comment by kaincenteno** [comment]
awesomeness, thank you @claywar 😄
