### ISSUE TITLE
🐛 Atop the Highest Mountains(level 55 limit break quest)

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2850]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Window 11

## Branch affected by issue 

`base`

## Steps to reproduce
Start level 55 quest from Maat
go to Xarcabard
Those 3 NM's defending frigicite from ???'s
Boreal hound, Boreal Tiger, and Boreal Coeurl not roaming far enough for me to grab frigicite without engaging.
I remember that in retail I used to use mount to grab item without fighting.

## Expected behavior
Should able to grab frigicite without fighting any NM

**Comment by Xaver-DaRed** [comment]
While we are here... This mobs do not roam freely.

In retail, they follow a very clear path, consisting on walking to point A, changing rotation from left, to right to center and then walking to point B, repeat rotation process, and so on.
