### ISSUE TITLE
🐛 /heal not working?

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2851]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Window 11

## Branch affected by issue 

`base`

## Steps to reproduce

After I fight with Boreal Tiger and Boreal Hound, my party got hurt and was working to heal for 3rd fight but it seems not working?  The newest update patch(10/1/22) made them broken or some spells or something from those NM's makes /heal not working after fighting? As you can see I timed on each screenshot.. about 2 minutes 30 second apart from those screenshots and not healed at all.

## Expected behavior

should able to /heal hp and mp
![time 1](https://user-images.githubusercontent.com/40586417/193431213-25c97e04-43a5-4e3f-8fe0-a7ac2cebbc75.jpg)
![time 2](https://user-images.githubusercontent.com/40586417/193431216-d7fffdf1-eb86-45d1-bf23-c446fb27fe8e.jpg)

**Comment by WinterSolstice8** [comment]
probably had disease from rot gas
https://www.bg-wiki.com/ffxi/Category:Hound
https://www.bg-wiki.com/ffxi/Disease

**Comment by Zofra2020** [comment]
![image](https://user-images.githubusercontent.com/40586417/193431354-5cc6d243-ce06-4c7f-9150-8646c9e0ee0a.png)
They have no disease icon so maybe it makes that heal hp/mp not working until log out?
Edit: I just tested to relog, doesn't work.

**Comment by WinterSolstice8** [comment]
Dunno if this is your server, but what's `HEALING_TICK_DELAY` set to in `settings\map.lua`?

I can heal no problem on unmodified base

**Comment by Zofra2020** [comment]
yes it is my server.
![image](https://user-images.githubusercontent.com/40586417/193431584-02bbc8e6-2108-436d-a770-4272a66cbc91.png)

**Comment by WinterSolstice8** [comment]
do you have a character with GM?

target a player effected and use this command from your gm char's chatbox `!exec print(target:hasStatusEffect(xi.effect.HEALING))`

that will print true or false to your server's console. true means they've already got the status effect, which they shouldn't have it
just trying to rule things out

**Comment by WinterSolstice8** [comment]
`!exec print(target:getStatusEffects())` is another one that will just print all status effects of a target to the log. For instance, this is what I see when I am /healing

`[10/01/22 16:34:42:673][map][lua] table{ CLuaStatusEffect(794) } (lua_print:157)`

**Comment by WinterSolstice8** [comment]
More debugging commands for you to try,

`!exec print(target:getMod(xi.mod.HPHEAL))` this is the "Healed HP+" mod, which can be negative in theory. Should print 0 naked without any status effects.

when healing:
`!exec print(target:getStatusEffect(xi.effect.HEALING):getTick())` prints 10,000 for me, which I guess is that "tick delay" config.

**Comment by WinterSolstice8** [comment]
And finally, something you don't need a GM char for:

Open `scripts\globals\effects\healing.lua`

modify the on effect tick function:

```
effect_object.onEffectTick = function(target, effect)
    local healtime = effect:getTickCount()
    
    if healtime > 2 then
        print("healing effect tick before status effect check")
        -- curse II also known as "zombie"
        if not(target:hasStatusEffect(xi.effect.DISEASE)) and target:hasStatusEffect(xi.effect.PLAGUE) == false and target:hasStatusEffect(xi.effect.CURSE_II) == false then
            print("healing effect tick after status effect check")
```

This covers everything I can think of without more input about what might be wrong.

**Comment by TeoTwawki** [comment]
does the game stand your char back down or do you rest forever with nothing happening?

sounds like the latter, just being sure

**Comment by Zofra2020** [comment]
Sorry I was away for couple hours.
![image](https://user-images.githubusercontent.com/40586417/193434337-e9349d83-966f-4dd6-ae59-0a28f958e337.png)

**Comment by Zofra2020** [comment]
> 

I can stand or sit... I can sit forever and not heal at all.

**Comment by WinterSolstice8** [comment]
Aha, I think you just need to rebuild xi_map. That was a recent addition https://github.com/LandSandBoat/server/pull/2742

It adds a core binding, which you can't get just from lua updates.

**Comment by Zofra2020** [comment]
Yep that is it.  I rebuild with vs 2022 and now it works

I guess close this?

Should I be rebuilding every time after getting lua updates through powershell?
