### ISSUE TITLE
🐛 Abyssea blue pyxis adding way too much time

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#2855]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known) 

Linux

## Branch affected by issue 

`base`, noticed on xiweb

## Steps to reproduce

Enter Abyssea, request visitant status, and begin building lights to build up to getting time extensions from blue pyxis.  Notice they grant way more than the 10 minutes mentioned in the text message.

As shown in the screen grab, the first one I opened after being in there for 60 minutes took time remaining from 60 to 59,845 (added 59,785).  After being in there for over an hour without adding any more time, I still had well over 59,000 minutes remaining.  Fortunately, this glitch does not carry over when you exit/return (gets maxed at 120).

## Expected behavior

Time extension from blue pyxis grants retail appropriate time, in line with the in-game message when opened (ie: 10 minutes)

![Raist_2022 10 01_Aby_TE_prob](https://user-images.githubusercontent.com/73744368/193441866-8bd2f468-321f-48e3-838f-8de479fc921f.jpg)

**Comment by WinterSolstice8** [comment]
bad parens?

`local newDuration = (oldDuration + tonumber(10 * 60)) * 1000`

**Comment by WinterSolstice8** [comment]
![image](https://user-images.githubusercontent.com/60417494/193443839-8b51af61-49b3-4885-9fc4-91987f24b328.png)
yup. bad parens. fix incoming.
