### ISSUE TITLE
🐛 Lookup errors on fresh build?

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2885]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows10 

## Branch affected by issue 

`base`

## Steps to reproduce

Just merged latest commit into my repo, built, updated DB, and getting these errors on startup... If i launch my old executable there are no errors.

![image](https://user-images.githubusercontent.com/65316697/194080363-31a90b4c-45af-4756-8417-27d022cecbce.png)

## Expected behavior

No errors on startup?

**Comment by zach2good** [comment]
Aside from one accidental formatting error, `base` is building and booting up correctly
https://github.com/LandSandBoat/server/actions/runs/3190033296

**Comment by TeoTwawki** [comment]
> If i launch my old executable there are no errors.

review your update steps you take, see what you missed

**Comment by CatsEyeXI** [comment]
hmm... even after resetting the db its still doing it... ill try nuking the whole thing and starting over.

**Comment by WinterSolstice8** [comment]
log message sounds like permissions issue on db, wrong user and/or password?

**Comment by CatsEyeXI** [comment]
Just on those dynamic lookups? I copied configs from working build. Server
still finishes booting. I had to step out for a bit but I will test on a
clean pull in a bit.

**Comment by WinterSolstice8** [comment]
It says that SELECT was denied to your user for specifically mob_spawn_points, it pretty much has to be permissions

maybe need a 
`GRANT ALL PRIVILEGES ON xidb.* TO 'xi'@'localhost';"` except with your db and username replaced

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/194111771-1d712c06-485e-4889-9583-a78fd3adb33b.png)

can only really be permissions

**Comment by CatsEyeXI** [comment]
> ![image](https://user-images.githubusercontent.com/6871475/194111771-1d712c06-485e-4889-9583-a78fd3adb33b.png)
> 
> can only really be permissions

i swear i'm not crazy 🤣 ... next step is i dump everything fresh db and everything... will update once i figured it out

![image](https://user-images.githubusercontent.com/65316697/194116349-32e1673d-8782-466c-8a56-4f742bcad403.png)

**Comment by CatsEyeXI** [comment]
i think i see the problem... it's trying to reference a database called xidb... not the one i have defined in my settings?
this is a fresh clone from lsb base only thing brought in were my settings.
i also reset the database... only difference mine is called tpzdb not xidb...

**Comment by CatsEyeXI** [comment]
confirmed that after renaming database to xidb, the sever boots fine... did we hard-code the database name anywhere recently?
maybe when doing these dynamic lookups?
![image](https://user-images.githubusercontent.com/65316697/194121414-485fbdb3-cdf9-4258-941a-f7a98715d236.png)

**Comment by WinterSolstice8** [comment]
https://github.com/LandSandBoat/server/blob/31318665eea1836347e383787f502711720501c0/src/map/lua/luautils.cpp#L794
Looks like it does expect xidb, yeah. a really old migration also expects xidb too

**Comment by TeoTwawki** [comment]
> https://github.com/LandSandBoat/server/blob/31318665eea1836347e383787f502711720501c0/src/map/lua/luautils.cpp#L794
> 
> Looks like it does expect xidb, yeah. a really old migration also expects xidb too

`xidb.` portion doesn't belong, that's an easy fix but I dunno about the migrations, haven't seen that.

**Comment by claywar** [comment]
Working on adding additional lookups for some of the low-hanging fruit right now.  Will fix in that PR unless someone beats me to it
