### ISSUE TITLE
🐛 Castle Zvahl Bailey/Keep Teleporter pad

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2889]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)
Window 11

## Branch affected by issue 

`base`

## Steps to reproduce

For Sandoria mission 5-2(shadow lord)

Walk through the Castle Zvahl Baileys--> Zvahl Keep ---> Right before Throne Room
The teleporter platform in Zvahl Keep teleports you to next segment automatically(no yellow mark on ground).  The first 3 teleport automatically teleports you to correct place.  The 4th teleporter teleports you completely random location in the area which is not suppose to.

## Expected behavior
1. Shows yellow icon teleport pad on ground randomly time at each location then will teleport you away.
2. 4th teleporter should send you correct 4th spot

https://www.bg-wiki.com/ffxi/San_d%27Oria_Mission_5-2
https://youtu.be/26jb_8rEN4g?t=2377

**Comment by TeoTwawki** [comment]
Offset might a gotten mixed up on the last one. there is another TelePad people normally never use (may not even realize it exists!) that would drop you semi randomly like that, but it's not supposed to be that one.

The 4th should also put you at the top of the stares of point D on the map (as shown in the video) with the 1st being the exact center of the room with 5 teleporters in it. the northwest one is reach by going down the stairs, and sends you back to the beginning of the teleport trip. The random port is in another area people usually don't go to, not connected to the normal trip to Shadownlord fight.

**Comment by TeoTwawki** [comment]
```lua
    -- TODO: Change this regions to radials.
    zone:registerRegion(1, -301, -50, -22, -297, -49, -17) -- central porter on map 3
    zone:registerRegion(2, -275, -54,   3, -271, -53,   7) -- NE porter on map 3
    zone:registerRegion(3, -275, -54, -47, -271, -53, -42) -- SE porter on map 3
    zone:registerRegion(4, -330, -54,   3, -326, -53,   7) -- NW porter on map 3
    zone:registerRegion(5, -328, -54, -47, -324, -53, -42) -- SW porter on map 3
    zone:registerRegion(6, -528, -74,  84, -526, -73,  89) -- N porter on map 4
    zone:registerRegion(7, -528, -74,  30, -526, -73,  36) -- S porter on map 4
```
huh...

Need to go in game to really check, but at a glance this looks odd

edit: partly because the regions weren't ordered in the order you'd actually hit the telepads. oof.

**Comment by TeoTwawki** [comment]
partly because the regions weren't ordered in the order you'd actually hit the telepads. oof.

**Comment by TeoTwawki** [comment]
so hey 2 yrs later I finally went on retail and checked and rechecked all the porters. I've made a PR correcting all this.
