### ISSUE TITLE
🔨 Dynamic Lookup - Replace DB entries in query containing - with _

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#2890]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature
Some mob and NPC names don't conform with lua needs for enum declaration, replace `-` in names with `-` in query

```
UPPER(REPLACE(name, '-', '_'))
```

Test Target: AYNU_KAYSEY (Aynu-Kaysey, Caedarva Mire)

**Comment by zach2good** [comment]
Also a good opportunity to pull put the xidb names I left in
