### ISSUE TITLE
🐛 Sabotender Enamorado not flagged as NM

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2892]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

window 11

## Branch affected by issue 

`base`

## Steps to reproduce

6-1 Sandoria mission
I checked and there is a couple cases on this mob but not about "NM" class

/check the sabotender enamorado and it will tell  you level and difficulty.

https://www.bg-wiki.com/ffxi/Sabotender_Enamorado
https://www.bg-wiki.com/ffxi/San_d%27Oria_Mission_6-1
## Expected behavior

should say "Impossible to Gauge!"?
![image](https://user-images.githubusercontent.com/40586417/194179684-daf1abfb-42fc-4158-afcc-af26cfe78e45.png)

**Comment by TeoTwawki** [comment]
theres a column in mob_pools that needs set to make it check correctly
```sql
  `mobType` smallint(5) unsigned NOT NULL DEFAULT 0,
```
(15th field)


```cpp
enum MOBTYPE
{
    MOBTYPE_NORMAL      = 0x00,
    MOBTYPE_0X01        = 0x01, // available for use
    MOBTYPE_NOTORIOUS   = 0x02,
    MOBTYPE_FISHED      = 0x04,
    MOBTYPE_CALLED      = 0x08,
    MOBTYPE_BATTLEFIELD = 0x10,
    MOBTYPE_EVENT       = 0x20
};
```
https://github.com/LandSandBoat/server/blob/b4473b2390d025282e10560de0222a218b59030a/src/map/entities/mobentity.h#L68

**Comment by Zofra2020** [comment]
Hehe, I was trying to use correct term but at least you understand what I mean.

**Comment by TeoTwawki** [comment]
:+1:
