### ISSUE TITLE
🐛 COR Trusts are failing to grant Phantom Roll effects to members

### ISSUE THREAD

**Issue by N3ckB3ard** [DerpyProjectGroup/topaz#2897]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

 W10

## Branch affected by issue 

`base`

## Steps to reproduce

 Spawn Trust Qultada
Engauge a monster
Qultada will use Phantom roll ability
The effect will apply to members then be removed (Note the Phantom Roll effect # will be different on separate trusts)
![image](https://user-images.githubusercontent.com/98081508/194423778-c381400b-d7eb-4019-923d-2795122d4acb.png)

Reverting the changes made in PR #2811 will resolve the issue and allow trust roll effects to apply to members
## Expected behavior

 Spawn Trust Qultada
Engauge a monster
Qultada will use Phantom roll ability
The effect will apply to members

**Comment by WinterSolstice8** [comment]
what chat addon are you using for that? I see the param is indeed wrong when I look at the action for each target

battlemod thinks nothing is wrong, though it might not actually individually check the targets param
![image](https://user-images.githubusercontent.com/60417494/194428463-00c03506-9d9b-4819-a326-f3576b49cc05.png)

will look into it

**Comment by N3ckB3ard** [comment]
> what chat addon are you using for that? I see the param is indeed wrong when I look at the action for each target
> 
> battlemod thinks nothing is wrong, though it might not actually individually check the targets param ![image](https://user-images.githubusercontent.com/60417494/194428463-00c03506-9d9b-4819-a326-f3576b49cc05.png)
> 
> will look into it

It is battle mod for windower
