### ISSUE TITLE
🐛 Mission trigger "onZoneIn" is not working as expected

### ISSUE THREAD

**Issue by N3ckB3ard** [DerpyProjectGroup/topaz#2919]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

 Windows 10
Build x64 Debug

## Branch affected by issue 

`base`

## Steps to reproduce

This issue was tested with a fresh LSB pull within the hour
I ensured my missionStatus was set to 0 before testing this mission

Example of one mission not working:
https://github.com/LandSandBoat/server/blob/base/scripts/missions/rotz/08_Return_to_Delkfutts_Tower.lua
!addmission 3 16

-- Gilgamesh                     : !pos 122.452 -9.009 -12.052 252
-- Aldo                              : !pos 20 3 -58 245
-- Lower Delkfutt's Tower : !zone 184

When we zone into Lower Delkfutt's Tower we expect to trigger "onZoneIn" to receive CS 15
This event does not happen. "Rezone" did not trigger this event.
!checkmissionstatus <self> 3 reflected 0
I used "!cs 15" to set my missionStatus to 1

!zone 179
When we zone into Stellar Fulcrum we expect to trigger "onZoneIn" to receive CS 0
This event does not happen. "Rezone" did not trigger this event.
!checkmissionstatus <self> 3 reflected 1
I used "!cs 0" to set my missionStatus to 2

defeated the battlefield and was immediately teleported out. I appeared in the Stellar Fulcrum then was immediately teleported back to my location with out receiving any further CS. My mission status was then updated to 3

Based on the mission code my mission should have been set to complete but I am still on Mission 16 in my logs as CS 17 was not triggered.
I used !goto <t> to test a "Rezone" to see if I would trigger the CS but it did not trigger

I used "!cs 15" after leaving the battle and this updated my mission to complete

## Expected behavior

 onZoneIn to trigger when called

**Comment by claywar** [comment]
This issue impacts all onZoneIn events defined in Interaction framework.  Offending code is:
![image](https://user-images.githubusercontent.com/81713309/194979428-bd51a7e9-0243-4273-98b3-dbb186f011a2.png)

We are currently investigating this change, and are ensuring that it does not impact the new battlefield rework by changing.
