### ISSUE TITLE
🔨 Trust: Create Shield Block function

### ISSUE THREAD

**Issue by GodModeXI** [DerpyProjectGroup/topaz#2926]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

- Trust shield block enhancement.
- Observations through discussion:
- Through retail observation and captures by Strong/Neckbeard. Specific trusts lack the logic to perform shield block procs. 
![image](https://user-images.githubusercontent.com/99501957/195351403-f3128145-3cfb-46e4-b878-31b66760355c.png)
![image](https://user-images.githubusercontent.com/99501957/195351445-98792d7a-b71e-45c4-8f5b-9c8e61d7203d.png)
![image](https://user-images.githubusercontent.com/99501957/195351475-ee83aca9-b224-4829-a951-3c07d94208c9.gif)
- Battleutils: isBlocked, as observed by @TeoTwawki has logic for PC object types, and a messy copy for PET objects, but lacks logic for TRUST objects all together.
- (https://github.com/LandSandBoat/server/blob/e7ef57e59458fec605840b21c52636f4072f731a/src/map/utils/battleutils.cpp#L2070)
- Battleultis: GetBlockRate, as observed by @TeoTwawki contains logic and formula calculations for shield block rates for PC / PET / MOB type objects but lacks logic for TRUST objects all together.
- (https://github.com/LandSandBoat/server/blob/e7ef57e59458fec605840b21c52636f4072f731a/src/map/utils/battleutils.cpp#L1786)

- Request for enhancement:
- clean up logic for non PC object types for shield block rates that do not consider shield mastery, or shield item slot. A separate exception formula should be generated to override shield size / mastery considerations and create a new calculation to emulate a formula that applies to non PC object types in a similar way.

**Comment by TeoTwawki** [comment]
> Battleutils: isBlocked, as observed by @TeoTwawki has logic for PC object types, 

isBlocked is ok, places its called not so much

the pet stuff was inside the shield mastery block of takeDamage, and I am not sure any pet ever actually has that trait

start of discord convo in case reference is needed: [link](https://discord.com/channels/392903136336936960/832349765718900827/1029461068969422879)
