### ISSUE TITLE
Sublime Sushi HQs don't match what's listed on BG Wiki

### ISSUE THREAD

**Issue by Arnd-SN** [DerpyProjectGroup/topaz#2952]
Looking at the recipe for Sublime Sushi here:

https://www.bg-wiki.com/ffxi/Sublime_Sushi

Depending on which ingredients you use, there are two different outcomes for HQ rates.

For example:

Using Ground Wasabi HQ1 should be Sublime Sushi x6

But using Wasabi HQ1 should be Sublime Sushi +1

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

**Comment by RAIST5150** [comment]
The more common sources are in agreement.  Both recipes NQ results with an 4x NQ product... it is the HQ results that differ between them:

Ground Wasabi: nq x4, nq x6, hq x2, hq x4

Fresh Wasabi:  nqx4, hq x4, hq x6, hq x8

Sources:
http://wiki.ffo.jp/html/35033.html
https://ffxiclopedia.fandom.com/wiki/Sublime_Sushi
https://www.bg-wiki.com/ffxi/Sublime_Sushi
(Auction site did not list a results breakdown)

Currently in our SQL:

```sql
INSERT INTO `synth_recipes` VALUES (74057,0,2040,0,0,0,0,0,0,0,90,4099,4241,620,1652,4318,4379,4384,4480,4570,5164,6468,6468,6469,6469,4,6,2,4,'Sublime Sushi'); 
INSERT INTO `synth_recipes` VALUES (74058,0,2040,0,0,0,0,0,0,0,90,4099,4241,620,1652,4318,4379,4384,4480,4570,9200,6468,6468,6469,6469,4,6,2,4,'Sublime Sushi');
```

About as far as I got looking into this before my phone started to bog down something fierce...  

Looks like the recipe using fresh wasabi needs to be identified and have the HQ results/ID's edited appropriately.

**Comment by Arnd-SN** [comment]
The second two sources you list support my argument. If that’s how it’s supposed to be so be it, just seemed odd that two sources show different hq results depending on recipe.Sent from my iPhoneOn Oct 16, 2022, at 3:21 PM, RAIST5150 ***@***.***> wrote:﻿
The more common sources are in agreement on them... both recipes NQ results with an 4x NQ product:
Ground Wasabi: nq x4, nq x6, hq x2, hq x4
Fresh Wasabi:  nqx4, hq x4, hq x6, hq x8
Sources:
http://wiki.ffo.jp/html/35033.html
https://ffxiclopedia.fandom.com/wiki/Sublime_Sushi
https://www.bg-wiki.com/ffxi/Sublime_Sushi
(Auction site did not list a results breakdown)
Currently in our SQL:
INSERT INTO `synth_recipes` VALUES (74057,0,2040,0,0,0,0,0,0,0,90,4099,4241,620,1652,4318,4379,4384,4480,4570,5164,6468,6468,6469,6469,4,6,2,4,'Sublime Sushi'); 
INSERT INTO `synth_recipes` VALUES (74058,0,2040,0,0,0,0,0,0,0,90,4099,4241,620,1652,4318,4379,4384,4480,4570,9200,6468,6468,6469,6469,4,6,2,4,'Sublime Sushi');
About as far as I got looking into this before my phone started to bog down something fierce...

**Comment by RAIST5150** [comment]
It actually happens with a handful of cooking recipes... some even result in a different HQ version, not a different quantity (ie: icecap/snowy/flurry rolanberry).

Having 3 sources in agreement is should be enough for someone to submit a PR to adjust the Wasabi recipe... the other is already in alignment.
