### ISSUE TITLE
🐛 crash related to md5 decipher on map server?

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2956]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

These crashes don't seem to be related to any particular character action.  Most of the references I find in the dump lead me to believe this is somehow related to the map server trying to decipher encrypted packets. 

Perhaps this log entry right before the last crash might shed some light? No guarantees :)

DUMP: https://drive.google.com/file/d/1853FMAMlCW_GQJuJJ7bfqa3T4IyXsvQW/view?usp=sharing
Build: mods-cc6c445ea4-dirty

![image](https://user-images.githubusercontent.com/65316697/196068853-45aa4215-36c7-463e-be56-d7344081cb17.png)

## Expected behavior

No Crash

**Comment by WinterSolstice8** [comment]
![image](https://user-images.githubusercontent.com/60417494/196071607-188f7eef-cfd6-471f-a1b4-4fede095b57b.png)

`TSource Engine Query` is a query packet for source engine games. This shouldn't be crashing you, and oddly, this md5 is within a try/catch block. It shouldn't be crashing _at all_

**Comment by CatsEyeXI** [comment]
> ![image](https://user-images.githubusercontent.com/60417494/196071607-188f7eef-cfd6-471f-a1b4-4fede095b57b.png)
> 
> `TSource Engine Query` is a query packet for source engine games. This shouldn't be crashing you, and oddly, this md5 is within a try/catch block. It shouldn't be crashing _at all_

Alright, it was the best assumption I could come up with for the sake of filling out the issue form. Hopefully the dump i provided has some more details..

**Comment by 234044174** [comment]
![image](https://user-images.githubusercontent.com/32334072/196093193-53a14edf-89f7-4664-a13e-57901b6b1d55.png)
