### ISSUE TITLE
🐛 Sneak Attack doesn't proc on normal attacks

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2973]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Fresh pull,
Reset DB
Create new character
Use Sneak attack with normal attack behind mob, will not proc, but effect wears off.

## Expected behavior

Sneak attack should proc a guaranteed critical hit when behind the mob. Currently only works with WS's.

**Comment by N3ckB3ard** [comment]
In a fresh pull of Base SA will not work

Reverted:
src/map/entities/battleentity.cpp

Lines: 1694 - 1696 (Deleted)
Lines: 1983 - 1989 (Reverted)


(PR #2873)
Only reverted images below

![image](https://user-images.githubusercontent.com/98081508/197338931-c6c550fc-3183-49fd-877b-302b643a4c53.png)
![image](https://user-images.githubusercontent.com/98081508/197338938-2ff9e6d2-470c-4d5e-b001-abd12ebcbf29.png)

Results:
SA wears off before damage is applied. Current Base
![image](https://user-images.githubusercontent.com/98081508/197339418-df2f08c1-82f4-4b4d-ba58-6ffb54772dcb.png)
SA wears off after damage is applied. This Build was directly from the history of the PR Base
![image](https://user-images.githubusercontent.com/98081508/197339529-2ace4bc7-6821-40a7-aaed-b2b87e776861.png)

**Comment by WinterSolstice8** [comment]
Whoops, my bad. Didn't realize that removed SA effect before it should've.
