### ISSUE TITLE
🐛 Server crashing on boot while trying to initialize zone

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2981]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Server crashed last night and failed to auto restart, upon inspecting the logs, it seems to be hitting some DEBUG condition repeatedly while trying to initialize... dump appears to mention some regional npc and makes a reference to setCostume().

```
[10/20/22 07:41:31:690][map][lua] Getting respawn time from server vars: Argus 1666275273 (lua_print:153)
[10/20/22 07:41:31:690][map][lua] Getting respawn time from server vars: Leech_King 1666284496 (lua_print:153)
[10/20/22 07:41:31:691][map][lua] Getting respawn time from server vars: Serket 1666289446 (lua_print:153)
[10/20/22 07:41:31:695][map][lua] Getting respawn time from server vars: Bune 1666420191 (lua_print:153)
[10/20/22 07:41:31:696][map][lua] Getting respawn time from server vars: Lord_of_Onzozo 1666271891 (lua_print:153)
[10/20/22 07:41:31:698][map][error] HIT DEBUG CONDITION: m_PBaseEntity->objtype != TYPE_PC (CLuaBaseEntity::setCostume:4658)
=====================================================
!!! CRASH !!!
Exception code: C0000005 (ACCESS_VIOLATION)
Fault address: 00007FF784A91F42 01:0000000000020F42
Process Name: C:\catseyexi\xi_map.exe
Full crash report: C:\catseyexi\dmp\xi_map.exe_20-10_7-41-31.log
Memory dump: C:\catseyexi\dmp\xi_map.exe_20-10_7-41-31.dmp
Time of crash: 2022/10/20 07:41:31
Process Uptime: 16 seconds
Processor: AMD Ryzen 9 5900X 12-Core Processor
Number Of Threads: 8
OS: Windows 10 Professional (Version 10.0, Build 19044)
Process Memory Usage: 1327MiB / 49152MiB
Git Branch: mods
```

https://www.bg-wiki.com/ffxi/Apairemant

(https://drive.google.com/file/d/1oU39W9CXpLonfUVxfq0zFfuRpkXRAWNU/view?usp=sharing)

## Expected behavior

Server should not crash on startup

**Comment by CatsEyeXI** [comment]
![image](https://user-images.githubusercontent.com/65316697/196942471-76960d63-4741-4c16-a786-147b627dba21.png)

**Comment by TeoTwawki** [comment]
why would your server be trying to set a players costume _before its even loaded, when no player could exist yet?_

**Comment by CatsEyeXI** [comment]
it's a good question.. all of my mods are in modules, let me pull them all and see if that changes anything.

**Comment by CatsEyeXI** [comment]
no change :(
and no reference to setCostume() at all in any of our lua scripts. still crashes with the whole modules folder moved out.

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/196943982-44d09fb9-0afc-4a54-a162-251fb5ff730f.png)

**Comment by TeoTwawki** [comment]
do you have the old harvest festival stuff enabled?

it looks like someone at your server with the access to, tried to make it work and has it trying to costume the NPCs

**Comment by CatsEyeXI** [comment]
> do you have the old harvest festival stuff enabled?
> 
> it looks like someone at your server with the access to, tried to make it work and has it trying to costume the NPCs

bingo. thank you brother, can't thank you enough.

This must have been left on from a failed attempt sometime last year or something.. It's like a ticking time bomb waiting every year.

**Comment by TeoTwawki** [comment]
the debug break used to prevent it reaching the packet push and make it obvious what was the matter, and I had disabled the event itself back in dsp. it really isn't that hard to fix it up, except that the npc's can't undo the costume without a server restart due to not being able to set player type models currently. going to close this, as its less a bug at our end than an unfinished feature. I'll write up a doc for what needs to happen soon™ or see if I can just tackle it myself if I have the time.
