### ISSUE TITLE
🐛 Central Apollyon - No one but leader can join battlefield

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2989]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

W10

## Branch affected by issue 

`base`

## Steps to reproduce

#2941 @jmcmorris Per Testing instructions, I was able to join the BCNM but remaining party members could not.
Everyone receives the BCNM status icon, but the entry point is non responsive once the leader enters.
This was tested on the most recent clean LSB clone.

I was able to enter myself, then !bring the remaining party members and successfully fight Omega, but the Loot crate at the end would not open.

## Expected behavior

All subsequent group members should be able to join.

**Comment by CatsEyeXI** [comment]
![image](https://user-images.githubusercontent.com/65316697/197106466-f3f9b9d5-0e85-43e8-ae6a-18bc3294469d.png)

**Comment by jmcmorris** [comment]
Thanks for the report. I'll check it out tomorrow!
