### ISSUE TITLE
🔨 Refactor away all calls to XI_DEBUG_BREAK_IF

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#2994]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

After removing the "Oh, a condition we don't like, time to die!" functionality from XI_DEBUG_BREAK_IF in https://github.com/LandSandBoat/server/pull/2990, we should refactor away that style of usage in favour of "Oh, that's bad, we're going to ignore that entire action and log out some information about it"

**Comment by TeoTwawki** [comment]
since it no longer actually breaks, it should probably get renamed as well.

**Comment by claywar** [comment]
I think the idea might be to just log output in a condition, and return out gracefully

**Comment by TeoTwawki** [comment]
I mean,
```
// define a break macro for debugging
#define XI_DEBUG_BREAK_IF(_CONDITION_)                               \
    if (_CONDITION_)                                                 \
    {                                                                \
        ShowCritical("HIT DEBUG BREAK CONDITION: %s", #_CONDITION_); \
    }
```
there is no break happening here. we should probably stop calling it a break. that's all.
