### ISSUE TITLE
🐛 NM Ancient Vessel hit points total should be 12.000

### ISSUE THREAD

**Issue by Hatberg** [DerpyProjectGroup/topaz#3004]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows 10

`base`

## Steps to reproduce

Spawn an Ancient Vessel at Quicksand Caves at location !pos -504 20 -419 208
!spawnmob 17629642

## Expected behavior

Currently Ancient Vessel spawns at 8030 HP as per FFXIClopedia report. 

Video proof from https://www.youtube.com/watch?v=j1IzAVjeFq0 shows this should be closer to 12.000 HP
Propose to up the HP to 12.000.

Damage transcript:
66
91
16
16
142
18
144
74
18
141
106
1303
136
18
114
65
221
150
108
108
1105
192
78
88
191
113
105
1496
263
118
1586
207
76
100
226
1627
1581
Total damage received on Empty Vessel: 12207

**Comment by claywar** [comment]
From capture:
`[HP Track] Killed 17629642 (Ancient Vessel): 10194~11710HP, Est.HP: 11475 (Mthd: L)`

12000 seems reasonable, but I'd say 8000 (current implementation) is too low.

**Comment by zach2good** [comment]
Looks valid to me 👍
