### ISSUE TITLE
🔨 Refactor Tidal Talisman onItemCheck

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#3024]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature
Current implementation:
```
itemObject.onItemCheck = function(target)
    local result = 56
    local zone = target:getZoneID()
    if (zone == 238 or zone == 239 or zone == 240 or zone == 241 or zone == 242 or -- Windurst
        zone == 234 or zone == 235 or zone == 236 or zone == 237 or -- Bastok
        zone == 230 or zone == 231 or zone == 232 or zone == 233 or -- San d'Oria
        ((zone == 243 or zone == 244 or zone == 245 or zone == 246) and target:hasKeyItem(xi.ki.AIRSHIP_PASS_FOR_KAZHAM)) or -- Jeuno
        zone == 248 or -- Selbina
        zone == 249 or -- Mhaura
        zone == 250 or -- Kazham
        zone == 50 or -- Aht Urhgan Whitegate
        zone == 53) -- Nashmau
        then result = 0
    end
    return result
end
```

Table data and iterate, use enum for zone IDs

**Comment by TeoTwawki** [comment]
> iterate

should be able to just grab via index key

**Comment by TeoTwawki** [comment]
*grab

**Comment by claywar** [comment]
Absolutely.  Was one of the less-than-pleasant blocks I saw while doing CI work.  Looking at it now, we know the zone, so its just direct lookup from table (and need to check airship pass status for 4 zones)
