### ISSUE TITLE
🐛 Mob Traits are only set on Initial spawn

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#3027]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue

`base`

## Steps to reproduce
Check a mob for a trait after starting up server, see the trait set. Kill/despawn mob and respawn it. Trait isn't set afterwards.

![image](https://user-images.githubusercontent.com/6257062/197435494-79652655-0a7b-45c0-b3d6-85aec565798d.png)

![image](https://user-images.githubusercontent.com/6257062/197435765-8ab38b64-04a0-46b4-b0d4-10c86fc70bb6.png)

## Expected behavior

Mob traits always assigned on spawn.

**Comment by TeoTwawki** [comment]
~~they should be recorded in the mobs initialization snapshot (becomes default state, to avoid re-running same code), which gets used every repop before onMoBSpawn runs.~~ _actually I suspect we'd have edge cases involving variable levels anyway_

I'm _(still)_ puzzled how this wouldn't be noticed much much sooner.

**Comment by TeoTwawki** [comment]
so among other funny things winter found, apparently adding traits on repops was being attempted but failing because the old zero'd out ones were never cleared
