### ISSUE TITLE
🐛 [NPC] Shataru-Potaru weird behaviour

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3040]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

GNU/Linux

## Branch affected by issue 

`base`

## Steps to reproduce

go pay a visit to Shataru-Potaru and see him move weirdly

```lua
local pathNodes =
{
    { x = 150.716, y = -2.500, z = 130.594 },
    { x = 150.995, z = 130.387 },
}
```

## Expected behavior

Im asking @Daywhite83  in xiweb to see how he acts in retail. my assumtion is that he doesnt move but does a wait/rotation. Will update this issue once we receive the accurate behaviour

**Comment by kaincenteno** [comment]
closing this, he actually walks really bad on retail too 😆

**Comment by WinterSolstice8** [comment]
It's not a bug, it's a feature

**Comment by kaincenteno** [comment]
yeah saw that theres a bug broken also on retail that goes underwater. Clearly SE gave up on old areas.

https://youtu.be/2K_v-Yfk-xc
