### ISSUE TITLE
🐛 Mog House NPC non-responsive

### ISSUE THREAD

**Issue by jason-colby-brown** [DerpyProjectGroup/topaz#3050]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

`Ubuntu 22.04`

## Branch affected by issue 

`base`

## Steps to reproduce

Interact with Mog NPC in any Mog House. Confirmed in South Sandy, Port Bastok, and AU Whitegate. Mog house menu with storage, change jobs, etc. does not appear.
(Tested Selbina Nomad Moogles as well. They're fine.)

## Expected behavior

Usual mog house menu to be presented.

**Comment by RAIST5150** [comment]
Moogle in the moghouse?

Worked fine for me last night in Bastok on xiweb.

Kain rebuilt in Linux late on 10/25 Windows 10 client updated with retail about a week or so ago (October release from SE).

**Comment by jason-colby-brown** [comment]
Yes, stopped working as of today 10/27 after updating with current base commit https://github.com/LandSandBoat/server/commit/1b3509254a60993bcc7e2cd22ec9f1b62633a71e. Previous update was roughly 10/22 or 10/23 and was working fine after that.

**Comment by RAIST5150** [comment]
Odd indeed.

Looks like #3035 is the last merged PR that Kain's pull synched up through (was waiting for the ones about NPC's/patrolling to merge before rebuilding).

So it would likely be something in the last handful of merges over the last ~48 hours, unless something went sideways with the recent rebuild?

**Comment by jason-colby-brown** [comment]
Rebuild went fine, no errors. No error is logged by xi_map either when interacting with mog house moogle.

**Comment by 0phie** [comment]
Did a bit of preliminary testing using the Moogle inside of the Bastok Mines MH, looks like it never hits luautils::OnTrigger(CCharEntity* PChar, CBaseEntity* PNpc) now. Still investigating further, however just wanted to point out that the lua hook is not getting any breakpoints hit when talking with these NPCs specifically.

**Comment by zach2good** [comment]
Useful information from discord:
```
OpheliaXI:
Tried a few debug prints at least and they never even hit for Moogles inside of Moghouses for onTrigger, so luautils::OnTrigger never gets called.
Interesting note, onTrade appears to work fine which rules out an issue with DB name mismatches
```

**Comment by claywar** [comment]
```
if (PNpc != nullptr && distance(PNpc->loc.p, PChar->loc.p) <= 10 && (PNpc->PAI->IsSpawned() || PChar->m_moghouseID != 0) && PNpc->status == STATUS_TYPE::NORMAL)
```

Recent change requires status type normal for Moogles, which default to disappear in database.  Moving the required status to:
```
if (PNpc != nullptr && distance(PNpc->loc.p, PChar->loc.p) <= 10 && ((PNpc->PAI->IsSpawned() && PNpc->status == STATUS_TYPE::NORMAL) || PChar->m_moghouseID != 0))
```

Testing with potential fix incoming
