### ISSUE TITLE
🐛 Conquest Traveling Merchant NPCs do not work correctly

### ISSUE THREAD

**Issue by Frankie-hz** [DerpyProjectGroup/topaz#3051]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
- Open Conquest map to check Nation Ranks
- When any two nations are tied for first go to the Nation that is in 3rd place and see all the traveling NPCs are up.

## Expected behavior
- If two nations are tied in first then no traveling NPCs should be showing.
Example: https://ffxiclopedia.fandom.com/wiki/Valeriano

https://github.com/LandSandBoat/server/blob/base/scripts/globals/conquest.lua#L600
This line should be < and not >. Right now the sort is backwards causing the 3rd place nation to show.
When correcting the sort it still seems to be failing at:
`                    if id == firstPlaceZone and not IsConquestAlliance() then`
`                        entity:setStatus(xi.status.NORMAL)`
`                    end`
The NPC is still showing up to the nation that is listed first in the sort table.

![image](https://user-images.githubusercontent.com/105882754/198338331-79c1fd9e-747f-406a-9921-475e7fd71d6e.png)
![image](https://user-images.githubusercontent.com/105882754/198338402-340b4c45-553e-47c5-9a46-17616daa274f.png)

**Comment by TeoTwawki** [comment]
I think this is the line you were trying to link https://github.com/LandSandBoat/server/blob/base/scripts/globals/conquest.lua#L600
not sure what happened with that github url in the OP

**Comment by Frankie-hz** [comment]
> I think this is the line you were trying to link https://github.com/LandSandBoat/server/blob/base/scripts/globals/conquest.lua#L600 not sure what happened with that github url in the OP

Updated.

Seems adding a
`        local secondPlaceZone = rankings[2][2]`

and changing it to:
![image](https://user-images.githubusercontent.com/105882754/198341265-ec782fa1-2a8a-482d-950f-5b9208b5db48.png) works. Not sure if there is something wrong with the IsConquestAlliance() though.
