### ISSUE TITLE
🐛 [XI_MAP] Accounts_Session table will show disconnected user when not cleanly shutdown/logoff.

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3054]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

GNU/Linux

## Branch affected by issue 

`base`

## Steps to reproduce

* Disconnect the user abruptly.
* Check account_session table. You will see the session still there.

## Expected behavior

* Disconnect the user abruptly (force close window, power off machine, etc)
* Check account_session table. It should no longer see the account online.

**Comment by TeoTwawki** [comment]
There is a timeout people often do not wait for (or not wait long enough for) before the map server decided you are gone for reals. This happens on retail as well. What does NOT happen on retail, is that sometimes when you user tries to get back in "too soon" it'll get stuck forever.

Often it is also required to fully close out the game client - logging back in from the ffxi top page/char select is extremely unreliable.

In most cases, manually deleting the session row will fix it. More extreme stick-age can require restarting the server exe's.

And if you dc before ever hitting the map server, no session is really made but the socket can be stuck (that table is for online characters, despite being named "account" sessions). A giveaway the char isn't really there is when its targid is zero. It is only zero if the char has disconnected or the session is corrupted (in certain cases, multiboxing can corrupt the session).

Another way to get a ghost-session (and see it get stuck) is when someone has left their client up after a disconnect, spamming the reconnection attempt that would eventually fail on retail but is wholly unhandled on private servers: in your log this is preceded by hundreds of errors about invalid keys. 


This has more to do with the map server honestly.
