### ISSUE TITLE
🐛 [TRUST] [BATTLEFIELD] Trusts no longer able to be summoned for Maat Fight

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3060]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

GNU/Linux

`base`

## Steps to reproduce

Add key item "Rhapsody in Umber"
Trade item to enter fight.
Enter battlefield
try summoning a trust
You wont be able to

## Expected behavior

Be able to summon trusts while on battlefield (https://ffxiclopedia.fandom.com/wiki/Rhapsody_in_Umber) when having rhapsody in umber.

**Comment by Daywhite83** [comment]
also lets u fight him uncapped at lv 99
