### ISSUE TITLE
🐛 Can't install MariaDB anymore

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#3063]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

Had to format my PC, so I'm performing a fresh install, but now isn't posible to install MariaDB anymore:
```
c:\server\tools>py -3 -m pip install mariadb
Collecting mariadb
  Using cached mariadb-1.1.4.zip (97 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: mariadb
  DEPRECATION: mariadb is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for mariadb ... error
  error: subprocess-exited-with-error

  × Running setup.py install for mariadb did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      using environment configuration "C:\Program Files\MariaDB 10.9"
      Found MariaDB Connector/C in '"C:\Program Files\MariaDB 10.9"'
      running install
      C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
...
...
      .\include\mariadb_python.h(27): fatal error C1083: Cannot open include file: 'mysql.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mariadb
```
If I use --use-pep517 I get the same problem.  Also, there is no mariadb_python.h at all.

**Comment by Gradius2** [comment]
Installed pyproject.toml, as for wheel:

Requirement already satisfied: wheel in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (0.37.1)

Still getting error:
Building wheel for mariadb (pyproject.toml) did not run successfully

**Comment by zach2good** [comment]
I cleared my pip cache, uninstalled python, installed latest, updated to latest pip and got a slightly different error:
```ps
PS C:\Users\zrtoo> py -3 -m pip install mariadb
Collecting mariadb
  Using cached mariadb-1.1.4.zip (97 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 3
  ╰─> [1 lines of output]
      Could not find InstallationDir of MariaDB Connector/C. Please make sure MariaDB Connector/C is installed or specify the InstallationDir of MariaDB Connector/C by setting the environment variable MARIADB_CC_INSTALL_DIR.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I got around this by installing the latest mariadb C connector: https://mariadb.com/downloads/connectors/

Setting the env var that it asked for: `$Env:MARIADB_CC_INSTALL_DIR="C:\Program Files\MariaDB\MariaDB Connector C 64-bit"`

and then everything worked as expected: ` py -3 -m pip install mariadb`
```
PS C:\Users\zrtoo> py -3 -m pip install mariadb
Collecting mariadb
  Using cached mariadb-1.1.4.zip (97 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: mariadb
  DEPRECATION: mariadb is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for mariadb ... done
Successfully installed mariadb-1.1.4
```

I'm still on MariaDB 10.6, might be worth downgrading to that if you're on bleeding edge (10.6 is the LTS release)

**Comment by cocosolos** [comment]
Weird, according to the [docs](https://mariadb.com/kb/en/about-mariadb-connector-c/):

> In [MariaDB 10.2](https://mariadb.com/kb/en/what-is-mariadb-102/) and later, MariaDB Connector/C is distributed with MariaDB Server packages.

FWIW that [particular error](https://github.com/mariadb-corporation/mariadb-connector-python/blob/1.1/mariadb_windows.py#L58-L62) looks like it's related to registry keys.

**Comment by Gradius2** [comment]
> I got around this by installing the latest mariadb C connector: https://mariadb.com/downloads/connectors/

Thanks a lot, that sorted out the issue.
