### ISSUE TITLE
Forge Your Destiny (Sam unlock) quest npc not responding

### ISSUE THREAD

**Issue by Snugglesffxi** [DerpyProjectGroup/topaz#308]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: /scripts/zones/Norg/npcs/Ranemaud.lua

Go to norg, talk to NPC Jaucribaix to accept Sam unlock quest
Go to NPC Aeka (norg) and get item: Oriental Steel
Tallk to Ranemaud (norg) and get not response. 

He's supposed to give you item Sacred Sprig but his script doesn't complete and he is therefore unresponsive.

I pulled this error from the log

```
[Error] luautils::onTrigger: stack index 2, expected number, received nil: not a numeric type (bad argument into 'bool(unsigned short, const sol::basic_object<sol::basic_reference<0> >&)')
stack traceback:
        [C]: in function 'hasItem'
        ./scripts/zones/Norg/npcs/Ranemaud.lua:36: in function 'fallbackHandler'
        .\scripts/globals/interaction/interaction_lookup.lua:404: in function 
<.\scripts/globals/interaction/interaction_lookup.lua:367>```

**Comment by claywar** [comment]
Fixing now.  Seems like the sacred sprig item wasn't defined in items.lua

**Comment by Snugglesffxi** [comment]
> 
> 
> Fixing now. Seems like the sacred sprig item wasn't defined in items.lua

thanks! I feel really silly for not looking that up. sorry

**Comment by claywar** [comment]
Was actually a typo on my part, currently named `SACRED_SPRING`

**Comment by Snugglesffxi** [comment]
well now i feel even worse because i swear i triple checked lmao

**Comment by claywar** [comment]
Apparently I really like springs.  Fixed another typo in the PR for qm2 in Zi'Tah

**Comment by TeoTwawki** [comment]
![](https://i.imgur.com/2ecec.gif)
