### ISSUE TITLE
🐛 Certain player attack hits, don't show hit animation or sound

### ISSUE THREAD

**Issue by The-Aerec** [DerpyProjectGroup/topaz#3084]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Windows

## Branch affected by issue 

`base`

## Steps to reproduce

!changejob war 1

equip a bronze sword

go outside any starting nation, immortal yourself and a start hitting a mob.

Watch as certain low damage 'hits' don't play the hit animation or sound. But others do.

Video showing issue:
https://youtu.be/PkmArauQHeU

## Expected behavior

All hits should play hit animation / sound

**Comment by kaincenteno** [comment]
oh wow i never noticed. good find :D

**Comment by WinterSolstice8** [comment]
can't reproduce, or i'm extremely unlucky. I might write an addon so I can do this afk for hours

how often does this happen? does it happen after you unload all plugins/addons?

**Comment by WinterSolstice8** [comment]
also, is this with your client that has modded dats for era? does it happen without xipivot loaded?

**Comment by RAIST5150** [comment]
Hate to beat a dead horse some more, but also... what is the frame rate situation?

Network packet flow rate/consistency?

Devil's advocate thing to rule out potential pacing issues that could be hitching at the client or somehow through the network(s).

EDIT:
Had to watch it again from history on the TV.  For some reason, it would only go to 360p on the phone...  and STILL dropped 5 frames according to YT's stats--couldn't even make out the FPS counter until I loaded it at 1080p on the TV.  Just saying... sometimes weird things happen we aren't immediately aware of.

**Comment by The-Aerec** [comment]
Only mod I currently have is bubs HD basic**
FPS30
No packetflow

**Comment by TeoTwawki** [comment]
I noted that it happened right as the skillup occurred. another possibility is a mistake causing a lv1 thf/thf bunny to somehow guard or shield block, which was touched recently. It was also the attack round both enemies attacked at the same time, and I know we have difficulties with overlapping animations that has been a thing for over 7 yrs (something with packets, I dunno).

Might be helpful to immortal the bunny and player and the cheat acc stat of both to get a more consistent picture of what trips the bug. I had to watch that vid 3x and then still needed winter to point out to me which swing it happened on. There was just so much missing going on.

**Comment by TeoTwawki** [comment]
@The-Aerec looked to us like the bunny was mistakenly shield blocking, which it doens't have animations in its model for. if this still happens after the pr that just went in, we'll reopen.
