### ISSUE TITLE
Status effects cap at 19 hours / 65535  seconds (uint 16)

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#311]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Status effects should not be capping at such a low duration. They should be capping at 72 hours because some effects last up to 72 hours:
https://www.bg-wiki.com/ffxi/Emporox
https://www.bg-wiki.com/ffxi/Abdhaljs_Seal

**Comment by Snugglesffxi** [comment]
are these the only effects that last that long?

**Comment by TeoTwawki** [comment]
pretty simple solution: increase bitsize of field.

**Comment by zach2good** [comment]
I had a quick look around from DB to Core to Scripting, and I couldn't see where we're dropping to a 16-bit type?

EDIT: It's unsigned 32-bit all the way up, as far as I could (quickly) see

**Comment by TeoTwawki** [comment]
now that I think about it the 19hr mark they stated already exceeded 16 bits: 68400. but I think internally it gets stored as milliseconds for some part of it? but a uint32 already holds enough to handle that even in milliseconds.

**Comment by zach2good** [comment]
Could this be it?
https://github.com/LandSandBoat/server/blob/base/sql/status_effects.sql#L29
```sql
`min_duration` smallint(5) unsigned NOT NULL DEFAULT 0,
```

It's stored as 16-bit in the db, (presumably, as seconds, since it's multiplied by 1000 when it's loaded) and then held as 32-bit in memory. If this was the case, they'd max out as 18.2 hours in the db:
https://github.com/LandSandBoat/server/blob/db7d27f01498d2492119a618202285cb1b4cc557/src/map/status_effect_container.cpp#L103-L145

EDIT: Nope, doesn't look like it, that's the minimum time a status can be. No other parts of the duration-chain are 16-bit 🤷

**Comment by TeoTwawki** [comment]
need to expand it still then, just fewer parts to make the change than expected

**Comment by ShiyoKozuki** [comment]
Made a status 99999  duration, 9 hour 34 minute duration duration.
99999 % 65536 = 34463

34463 / 60 = 574 min

Made a status 65535,  18.2 hours duration

The item I tested this on was anniversary rings dedication effect.

**Comment by claywar** [comment]
65535/3600.  This time is in seconds, and therefore 65535 would be expected 18.2 hours.  A status effect set to 259200 duration (72 hours) is displayed properly in the client.

Procedure: Set Anniversary Ring item script duration to 259200, see EXP buff set to 72h.

Performing as expected, closing this issue as it was most likely addressed in prior work
