### ISSUE TITLE
🐛 Proto-Omega not giving title and not showing time

### ISSUE THREAD

**Issue by GravesXI** [DerpyProjectGroup/topaz#3157]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

trade the 4 chips and have the keyitems  to enter Central Apollyon when enter the countdown timer never appears, and upon killing it you never receive title 

![Graves_2022 11 07_145924](https://user-images.githubusercontent.com/1095718/200404525-1fdd68ae-fc3a-4d3b-a4a0-2301f9086178.png)

![Graves_2022 11 07_145833](https://user-images.githubusercontent.com/1095718/200404429-4baa318e-880d-4cdc-8c6c-fb7c41f57091.png)

## Expected behavior

should get title and should see the countdown title

**Comment by zach2good** [comment]
Presumably, this will be adding:
```
entity.onMobDeath = function(mob, player, optParams)
    if player then
        player:addTitle(xi.title.APOLLYON_RAVAGER)
    end
end
```
to `scripts\zones\Apollyon\mobs\Proto-Omega.lua`

and
```
    data.showTimer = true
```
into the `Limbus:new({` block of `scripts\battlefields\Apollyon\central_apollyon.lua`

I don't know the content or whether or not that's appropriate, @jmcmorris ?

EDIT: Timer for central, not CS

**Comment by cocosolos** [comment]
Limbus doesn't show a timer, just time remaining when you open a time extension chest. As for the title, I think the way it's currently coded is supposed to grant the title when the chest is opened and not on kill. Not sure if this is the correct behavior but can confirm in about 20 mins.

**Comment by TeoTwawki** [comment]
2 cents: would not at all mind being "better than retail" by showing timer in places SE did not anyway, so long as it functions correctly, and the difference is documented

**Comment by GravesXI** [comment]
It doesn't show after killed or after chest opened tried going in from both sides with red card and with black still no title

**Comment by jmcmorris** [comment]
Limbus doesn't show timer on retail. I disabled the timers to be retail accurate and they were not working 100% since Limbus has time extensions.

@zach2good New battlefield framework has a `title` param that can be set that is granted upon victory. I can make a PR for this.

**Comment by cocosolos** [comment]
Just to confirm the boss should give the title when it dies, not the winning cutscene.

**Comment by GravesXI** [comment]
Yeah it should but it doesn't

**Comment by jmcmorris** [comment]
If we're certain the title is added after defeating Proto-Omega and not upon opening the Armoury Crate at the end then it should be done like what Zach suggested in the `onMobDeath`.

**Comment by GravesXI** [comment]
Yeah it's always been on kill

**Comment by cocosolos** [comment]
Even though it's not the correct spot, [it _should_ be adding the title during the winning cutscene currently](https://github.com/LandSandBoat/server/blob/5bcfc25760e9dd32e268f4bebe1b4af60a98395c/scripts/battlefields/Apollyon/central_apollyon.lua#L30) so it seems like there may be an issue with that if it's not currently giving you the title at all.

**Comment by GravesXI** [comment]
Yeah it's not giving at all on kill or on exit after opening
