### ISSUE TITLE
Dragoon wyvern does not target trusts with Status Removal breaths. (Possible Fix Included)

### ISSUE THREAD

**Issue by Kentai713** [DerpyProjectGroup/topaz#3197]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Have a defensive type wyvern (pure mage subjob). Have a trust in party inflicted with poison (chosen because wyverns get this remove breath at level 1). The dragoon must not be afflicted with poison, blind, paralyze, curse or disease (depending on level) so the afflicted trust is targeted with the removal breath. Do any weaponskill. The wyvern will not remove the status effect from the trust.

## Expected behavior

If a trust in the drg/mage's (defensive wyvern type) party is inflicted with a status ailment (poison at lv 1, blind at lv 20, paralyze at lv 40, curse at lv 60, disease at lv 80) and the dragoon has none of the mentioned status ailments the wyvern should remove one of them when the dragoon uses a weaponskill. The issue here seems to be that in line 130 of pets/wyvern.lua player:getParty() is called when player:getPartyWithTrusts() should be called instead.

**Comment by WinterSolstice8** [comment]
![image](https://user-images.githubusercontent.com/60417494/201978913-fe68ce30-721b-45be-b58f-75fb271fa441.png)
retail does not do this
