### ISSUE TITLE
Zdei don't use Reactor cool

### ISSUE THREAD

**Issue by Enedin9000** [DerpyProjectGroup/topaz#3213]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Steps to reproduce

Fight Zdei, get em into their non-bar or non-ring mode (mobsub 0 or 1).
They only ever use Optic Induration.

## Expected behavior

They should also use Reactor Cool.

## Code

I think this is due to onMobSkillCheck never returning 0. In all other mob abilities it's coded like this: if such and such then return 1 (dont use), if anything else, return 0. Here the return 0 is missing, hence it never returns 0, I think. I whacked em for an hour and only ever saw Optic Induration.

![image](https://user-images.githubusercontent.com/16270541/202303821-b57e5f1b-fd8d-4b91-9b5b-cebde9493cab.png)

**Comment by TeoTwawki** [comment]
it's because a different type of magic pot will only use it while in a specific animation state and the lua was coded to handle that without considering this one ***or*** this type of magic pot was never made to use an alt animation state.

If we just return zero all pots can use it at all times, which is wrong.

**Comment by TeoTwawki** [comment]
If we just return zero all pots can use it at all times, which is wrong.

**Comment by Enedin9000** [comment]
Oh so some do still use it? Just not all of em?
