### ISSUE TITLE
🐛 Bastok mission 3-3 (Jeuno) will not complete

### ISSUE THREAD

**Issue by killeonP** [DerpyProjectGroup/topaz#3224]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

After receiving the cutscene in Lower Delkfutt Tower's basement, returning to Ru'Lude Gardens and clicking on (Door: Bastokan Emb.) will not proceed and complete mission but instead just say "You have no letter of introduction."

## Expected behavior

Clicking on the Door: Bastokan Emb. should proceed and complete the mission.

**Comment by zach2good** [comment]
Just to check before we start looking into this, this is with an updated LSB install, with the current retail client?

**Comment by killeonP** [comment]
The server I'm on was updated Nov 6th, client update wasn't needed for that update but was updated the week prior if I remember. I experienced this mission problem right at end of Oct (probably 29th) but then I was away a week and did other things when I returned. I've checked the commits to see if anything mentioned the mission and/or NPCs in this mission line.

**Comment by Xaver-DaRed** [comment]
Type /ver in-game to get the client version.

Nothing we can really do for you if you are a player and not testing this on a local server where you can check player variables and such.

What I would recommend, though, is to re-examine the door in delkfuts tower to see if the cutscene triggers again.
If it doesnt, I would make absolutely sure you are examining the correct door at your embassy. Its a common issue for players to examine a wrong door at a wrong embassy.

And always remember that, sometimes, the guides are wrong. Specially the ones in xiclopedia. not saying they are wrong in this concrete case, but, always something to remember.

**Comment by killeonP** [comment]
Understood, thanks. I'll wait until admin does next update and see if he can look at variables right after then go from there.

**Comment by TeoTwawki** [comment]
> Nothing we can really do for you if you are a player and not testing this on a local server where you can check player variables and such.

Adding to this: Follow up with whoever runs your server you play on, they can help determine if there's something to report to us.
