### ISSUE TITLE
🐛 Updating OBS Crashes Game

### ISSUE THREAD

**Issue by PotatoQueenAbzug** [DerpyProjectGroup/topaz#3237]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue 

`base`

## Steps to reproduce

Launch outdated version of OBS while Horizon is running. 
Update OBS to latest version
Game crashes

## Expected behavior

Game should not crash when background app is updating. I think. (I'm not very tech-savvy around this stuff).

**Comment by TeoTwawki** [comment]
The FFXI _client_ is known to crash when screen resets happen - we don't make that software, SE does. It's built on old dirext8 and they never updated it. If you are saying the _server_ end is crashing on update, I would question why you are trying to do this on the server while its running.

**windows:** bee-beep: do you want to allow this software to make changes to your computer?
**ffxi:** BLARG I AM DEAD x_X
