### ISSUE TITLE
🐛 Crashes resulting from Trusts

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3247]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win10

## Branch affected by issue 

`base`

## Steps to reproduce

I have attached two dumps, in one case seems that PTarget was 'null'. I wasn't able to make sense of the second crash, seems that something may have went wrong in the action queue. I've included full map-server log. I do see one message in there regarding a binding that was renamed (SetAutoAttack) which I will fix on my end... This accounts for both the errors in Prishe.lua as well the the trusts.lua module. 

Our last LSB pull was here:
https://github.com/LandSandBoat/server/pull/3191

Dumps:
https://drive.google.com/file/d/1z-62TCrdgnIFMSWvciNmjH4RbvnZBTdS/view?usp=share_link

## Expected behavior

No crashes

**Comment by zach2good** [comment]
> I do see one message in there regarding a binding that was renamed (SetAutoAttack) which I will fix on my end... This accounts for both the errors in Prishe.lua as well the the trusts.lua module.

Highly highly recommend leaving LSB's CI on, it'll catch all of this sort of thing before it makes it out to players

**Comment by zach2good** [comment]
Ah, you have it, you just need to make sure you block any PRs that don't adhere to them:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/1389729/203069672-6a97cee7-d6f2-46b7-91a4-79b03cdd712a.png">

**Comment by CatsEyeXI** [comment]
> Ah, you have it, you just need to make sure you block any PRs that don't adhere to them: <img alt="image" width="773" src="https://user-images.githubusercontent.com/1389729/203069672-6a97cee7-d6f2-46b7-91a4-79b03cdd712a.png">

I've been meaning to spend time to figure out how to properly implement and enforce the CI, i just keep sidetracked regularly. It's on my plate for things to do.

**Comment by zach2good** [comment]
From the dumps, one is relevant (`xi_map_11-20-22.dmp`):
`packetName = "UkaTotlihn"` is trying to use `CAbilityState::Update` while in state: `status = DISAPPEAR (2 '\x2')`

The other crash (`xi_map_11-21-22.dmp`) is:
`name = "Tenzen"` in `m_zoneID = ZONE_SEALIONS_DEN (32)` in `CAIContainer::Tick` in `CAIActionQueue::handleAction(queueAction_t & action)`, trying to eventually use
```cpp
void CBattlefield::SetLocalVar(std::string const& name, uint64_t value)
{
    m_LocalVars[name] = value;
}
```

But the `name` of the LocalVar it's trying to set hasn't been correctly pulled out of Lua, so there's a problem in some Lua that he's using somewhere.

**Comment by CatsEyeXI** [comment]
update: i cherry picked these changes and rebuilt this morning... running in debug mode again and will report back

**Comment by CatsEyeXI** [comment]
no crashes since, thanks Zach
