### ISSUE TITLE
🐛 Zdei cannot use Reactor Cool now.

### ISSUE THREAD

**Issue by TonzoffunCE** [DerpyProjectGroup/topaz#3268]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

@jmcmorris 
Since the changes to the zdei mobs from this commit:

https://github.com/LandSandBoat/server/pull/3091/commits/7dbaed2f38bd013a48eebdfdcd8a0ea57158394c

The zdei mobs no longer are able to access the Reactor Cool mob ability (which Blue Mages can learn).

The solution is to add "return 0" after line 14 in the reactor_cool.lua:

https://github.com/LandSandBoat/server/commit/20052d842ff13ceae3b77eabde943281775e3a8e

Also, the Eschan Zdei seem to not do anything but auto attack atm, maybe something to do with the change to their functionality as well?

## Expected behavior

Zdei mobs should be able to use Reactor Cool ability.

**Comment by Enedin9000** [comment]
Identical to https://github.com/LandSandBoat/server/issues/3213
