### ISSUE TITLE
🐛 CS - Apollyon: Party members can't interact with mobs/players after the first CS Apollyon is completed upon reset.

### ISSUE THREAD

**Issue by JayTDawgzone** [DerpyProjectGroup/topaz#3276]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

1. Create a party with at least one other character.
2. Enter either Apollyon Zones:
    - HP #2 `!pos -600 -0.5 -600 38` 
    - HP # 3 `!pos 600 -0.5 -600 38`
3. Get black/red card for corresponding entrance, cosmo cleanse, and a metal chip. Give cosmo cleanse and card(s) to party member(s)
    - Cosmo Cleanse `!!addkeyitem cosmo_cleanse <t>`
    - Black Card `!addkeyitem black_card <t>`
    - Red Card `!addkeyitem red_card <t>`
    - Metal Chip `!additem 2127`
4. Trade the metal chip to the Swirling Vortex and enter CS - Apollyon
5. Complete CS Apollyon 1 time, then repeat steps 1-4.
6. After entering the second time, the instance will start to bug for all party members that didn't initiate the instance until map server is restarted.

Issues that occur after attempting CS Apollyon again:

 For the party member that traded the chip and initiated the instance:
    - All mobs can cast spells/use abilities on this party member and cast spells and use abilities on the mobs.
    - This party member can NOT cast spells/abilities on party members, and party members can NOT cast spells/abilities on them.  (Spells can be cast but they will never complete)

For all other party members that entered after the player that initiated the instance:
    - Mobs can NOT cast spells/use abilities on them, but they can be auto attacked. (Spells can be cast but they will never complete)
    - Can cast spells/abilities on all other players in the instance except for the one that initiated.
    - Can NOT cast spells/use abilities on any of the mobs.   (Spells can be cast but they will never complete)

2nd party member can't interact with mob (spell never finishes casting)
![Pukegirl_2022 11 26_130201](https://user-images.githubusercontent.com/55102118/204109227-081d928e-ec89-48c7-90f9-0e4edbe3285f.png)

2nd party member stuck in casting animation when curing the player that initiated the instance. Mobs are also seen stuck in casting animations.
![Pukegirl_2022 11 26_130236](https://user-images.githubusercontent.com/55102118/204109381-b3d75a05-ab52-4034-a9b0-9684e45a7e30.png)

1st player to enter the instance behaves somewhat normally, they just can't interact with other party members.
![JayTDawgzone_2022 11 26_130255](https://user-images.githubusercontent.com/55102118/204109471-60ed8609-7a5c-4b63-93a4-7d54a3fb5863.png)
![JayTDawgzone_2022 11 26_131656](https://user-images.githubusercontent.com/55102118/204109482-34163950-ddfe-4744-8539-7f979bded6f9.png)

## Expected behavior

CS Apollyon behaves correctly the first time someone initiates the instance upon server reset. Party members should be able to enter and interact with the mobs & player that initiated the instance.

**Comment by CatsEyeXI** [comment]
@jmcmorris i just wanted to make sure you saw this. This is happening on base lsb.

**Comment by jmcmorris** [comment]
I have seen and will look into it when I have time.

**Comment by CatsEyeXI** [comment]
> I have seen and will look into it when I have time.

<3
