### ISSUE TITLE
🐛 Selections in custom menus do not trigger on the JP client.

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3314]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win 10

## Branch affected by issue 

`base`

## Steps to reproduce

Reproduced using Ashita v4
I use sandbox mode so I'm overriding my registry keys to toggle Japanese language on like this:

```
;---------------------------------------------------------------------------------------------------
; Japanese Client
;   Please uncomment the line below in order to switch to the Japanese client
;
[(PlayOnline|PlayOnlineUS|PlayOnlineEU)\\(Square|SquareEnix)\\PlayOnlineViewer\\Settings$]
; Language=dword:00000000
```
I suppose in theory you can just adjust actual key in the registry to accomplish the same result.

Launch the game in JP and try to interact with a custom menu. It will pop but you cannot make any selections.

Video:
https://drive.google.com/file/d/1TFShDHsDbTRYMzUiA0AAjsSVEiv54IA2/view?usp=sharing

## Expected behavior
Custom menus should work regardless of client language

**Comment by zach2good** [comment]
I don't think we have an official stance on supporting the JP client, so it's a 'oh that's cool' if it works at all.

Since you have the JP client set up this'll be a good exercise for you to practice your debugging!

Custom menus are hijacking a special type of chat message sent from GMs. If you interact with a custom menu, a 'custom menu context' is set on the char, which is then checked in combination with the next tell thay comes in. Presumably one of these two steps fails on the JP client.

This is where you'll need to breakpoint and inspect what condition isn't getting hit:
https://github.com/LandSandBoat/server/blob/929c2c5ec4898286b46429f98419d6b81565ea4e/src/map/packet_system.cpp#L5267

**Comment by CatsEyeXI** [comment]
Thought I would update this with some new information. One of my japanese players came forward with this addon that resolves the issue. Not sure if the same logic could be ported into LSB so the addon is not necessary. Just a thought.

```lua
addon.version = '0.1';
addon.name    = 'lsbcustommenufixjp';
addon.desc    = 'Enables JP client to operate custom menus.';
addon.author  = 'DB';

require('common');
local ffi = require('ffi');

ffi.cdef[[
    typedef struct packet_outgoing_tell_t {
        uint32_t Header;
        uint16_t Unknown1;
        char     TargetName[15];
        char     Message[];
    } packet_outgoing_tell_t;
]];

ashita.events.register('packet_out', 'packet_out_cb', function(e)

    if (e.id == 0x0B6 and not e.injected) then
        local telldata = ffi.cast('packet_outgoing_tell_t*', e.data_modified_raw);
        if
            ffi.string(telldata.TargetName, 12) == "_CUSTOM_MENU" and
            telldata.TargetName[12] == 0x00
        then
            local message = ffi.string(telldata.Message);
            -- Replace "結果" (Shift-JIS) by "Result".
            message = message:gsub("%):" .. string.char(0x8C, 0x8B, 0x89, 0xCA) .. "%(", "): Result (");
            -- Replace "キャンセル" (Shift-JIS) by "Canceled.".
            message = message:gsub("%(" .. string.char(0x83, 0x4C, 0x83, 0x83, 0x83, 0x93, 0x83, 0x5A, 0x83, 0x8B) .. "%)", "(Canceled.)");
            -- Assemble packets with replaced response messages.
            ffi.copy(telldata.Message, message);
            local inject_packet = ffi.string(telldata, ffi.sizeof('packet_outgoing_tell_t') + #message):totable();
            -- Inject new repsponse packet. 
            AshitaCore:GetPacketManager():AddOutgoingPacket(0xB6, inject_packet);
            -- Block the original response message packet.
            e.blocked = true;
            return true;
        end
    end
end)

```

**Comment by zach2good** [comment]
Presumably fixed in https://github.com/LandSandBoat/server/pull/4173
