### ISSUE TITLE
🐛 Entering a Battlefield After Party Engages Teleports Player to Empty Battlefield

### ISSUE THREAD

**Issue by panicstevenson** [DerpyProjectGroup/topaz#3332]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Have two players, have the first player start a battlefield and the other player waits outside. Begin the battlefield with the first player. The second player then interacts with the entrance NPC and is teleported inside. The player will receive this message:

![image](https://user-images.githubusercontent.com/8849608/205792952-900a398d-be71-4b02-82af-d35a8c691398.png)

The second player will be unable to use the exit NPC to leave.

## Expected behavior

Print the message but leave the player outside of the battlefield.

**Comment by jmcmorris** [comment]
I was working on this earlier and have a local fix along with a few similar fixes.
