### ISSUE TITLE
🐛 Cactrot Rapido doesn't link despite being configured to do so in DB.

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3342]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue 

`base`

## Steps to reproduce
1. Grab a local Sabotender
2. Stand right on Cactrot's path and notice he will not aggro

![image](https://user-images.githubusercontent.com/65316697/206800092-8cb72bc7-10a2-44e7-a116-7ce9db838d36.png)

## Expected behavior

Should link with other Sabotenders.

**Comment by TeoTwawki** [comment]
_edited for correctness_
They are the same family in db so if we turn on linking in pools they link both directions. if we sperate families then they don't link proper, and if we use the superlink mod its still wrong. In retail he will link to them, but they won't link onto him or each other. All our link methods have either all of them link or none of them link.

The options atm are be a little bit non retail, or handle in in script in onMobRoam (him) or onMobFight (the other cactaurs) and we didn't want to do that every tick checking of other stuff was in line of sight...This is an oldie, you can find various discussions and script examples in both dsp's old discord and the reddit discord. And it it hadn't imploded, topaz's old discord (sad)

Long term linking methodology needs to change or new functionality/mod(s) added

**Comment by CatsEyeXI** [comment]
> they aren't same "family" in db, so the link fag in pools won't work 

Both Sabotenders and Cactrot Rapido are family '212' in the DB. Is that what you mean?

**Comment by TeoTwawki** [comment]
I said it backwards but yeah its a problem weather they are or aren't either way we can't have them link via db for reason above. All our linking code is doing things that don't quite do what retail does with this guy.

edited my previous post

**Comment by Gradius2** [comment]
This is a very old bug.  I tried over 6 months ago... still there.

**Comment by TeoTwawki** [comment]
its like 6yrs old now

which is older than this iteration of the project

**Comment by TeoTwawki** [comment]
which is older than this iteration of the project
