### ISSUE TITLE
🐛 Monsters can dispel petrify from a player

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3344]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

![image](https://user-images.githubusercontent.com/65316697/206864852-4945fcc2-a47c-464b-93cb-e902b2feb794.png)

## Expected behavior

Petrify should only be dispelled when other players cast Dispel on petrified target.

**Comment by zach2good** [comment]
Can you reproduce this without a custom mob? because I can't:

```lua
-- Go to a mob that has MP (I went to Castle O)

-- Cast Breakga
!exec target:castSpell(365, player)

-- Cast Dispelga
!exec target:castSpell(360, player)
```

I put breakpoints inside `EFFECT CStatusEffectContainer::DispelStatusEffect(EFFECTFLAG flag)` and never incorrectly had `petrification` appear in the dispel list, only the relevant `protect`, `shell`, etc.

**Comment by zach2good** [comment]
Unless Helga has gone off the rails:
![image](https://user-images.githubusercontent.com/1389729/206867355-533ca9f1-4b07-4497-89a7-77635f4297b6.png)

**Comment by zach2good** [comment]
Are your status_effect.sql flags correct? 
```sql
INSERT INTO `status_effects` VALUES (7,'petrification',8388640,7,0,2,10,0,4,1,0);
```
```cpp
enum EFFECTFLAG
{
    EFFECTFLAG_NONE            = 0x00000000,
    EFFECTFLAG_DISPELABLE      = 0x00000001,
    EFFECTFLAG_ERASABLE        = 0x00000002,
    EFFECTFLAG_ATTACK          = 0x00000004, // disappears upon attacking
    EFFECTFLAG_EMPATHY         = 0X00000008, // effect can be copied to wyvern by use of merited Spirit Link
    EFFECTFLAG_DAMAGE          = 0x00000010, // disappears upon being attacked
    EFFECTFLAG_DEATH           = 0x00000020, // disappears upon death/ko
    EFFECTFLAG_MAGIC_BEGIN     = 0x00000040, // disappears upon spellcasting start
    EFFECTFLAG_MAGIC_END       = 0x00000080, // disappears upon spellcasting complete
    EFFECTFLAG_ON_ZONE         = 0x00000100,
    EFFECTFLAG_NO_LOSS_MESSAGE = 0x00000200, // Suppress effect worn off message.
    EFFECTFLAG_INVISIBLE       = 0x00000400, // invisible effect
    EFFECTFLAG_DETECTABLE      = 0x00000800, // invisible, sneak, deo
    EFFECTFLAG_NO_REST         = 0x00001000, // prevents resting, curse II, plague, disease
    EFFECTFLAG_PREVENT_ACTION  = 0x00002000, // sleep, lullaby, stun, petro. Not implemented
    EFFECTFLAG_WALTZABLE       = 0x00004000, // for healing waltzable spells
    EFFECTFLAG_FOOD            = 0x00008000,
    EFFECTFLAG_SONG            = 0x00010000, // bard songs
    EFFECTFLAG_ROLL            = 0x00020000, // corsair rolls
    EFFECTFLAG_SYNTH_SUPPORT   = 0x00040000, // Synthesis Image Support
    EFFECTFLAG_CONFRONTATION   = 0x00080000,
    EFFECTFLAG_LOGOUT          = 0x00100000,
    EFFECTFLAG_BLOODPACT       = 0x00200000,
    EFFECTFLAG_ON_JOBCHANGE    = 0x00400000, // Removes effect when you change jobs
    EFFECTFLAG_NO_CANCEL       = 0x00800000, // CAN NOT CLICK IT OFF IN CLIENT
    EFFECTFLAG_INFLUENCE       = 0x01000000, // Influence effects - e.g. Signet, Sanction, Sigil, Ionis
    EFFECTFLAG_OFFLINE_TICK    = 0x02000000, // Duration elapses while offline
    EFFECTFLAG_AURA            = 0x04000000, // Is an aura type effect
    EFFECTFLAG_HIDE_TIMER      = 0x08000000, // Sends "Always" in the packet, even though timer is tracked
    EFFECTFLAG_ON_ZONE_PATHOS  = 0x10000000, // removes the effect zoning into a non instanced zone
};
```

**Comment by CatsEyeXI** [comment]
Ill get back to you shortly, thanks

**Comment by CatsEyeXI** [comment]
Now I can't reproduce it either..  I wonder if the timing where my petrify wore off was coincidental. My apologies, I'll re-open if I can get this reproduced again. Thanks for checking.
