### ISSUE TITLE
extend_valid_targets errors [DBtool] [commit 678d59d]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#340]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
Finished importing!
Checking migrations...
Running migrations for Extend validTargets from tinyint to smallint...
Traceback (most recent call last):
  File "dbtool.py", line 658, in <module>
    main()
  File "dbtool.py", line 652, in main
    express_update()
  File "dbtool.py", line 395, in express_update
    update_db(silent, True)
  File "dbtool.py", line 412, in update_db
    run_all_migrations(silent or express)
  File "dbtool.py", line 487, in run_all_migrations
    migration.migrate(cur, db)
  File "/server/tools/migrations/extend_valid_targets.py", line 16, in migrate
    cur.execute("ALTER TABLE item_usable MODIFY COLUMN validTargets SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';")
  File "/.local/lib/python3.8/site-packages/mysql/connector/cursor.py", line 547, in execute
    self._connection.handle_unread_result()
  File "/.local/lib/python3.8/site-packages/mysql/connector/connection.py", line 1286, in handle_unread_result
    raise errors.InternalError("Unread result found")
mysql.connector.errors.InternalError: Unread result found
```

**Comment by zach2good** [comment]
@ffxijuggalo Please don't post issues in closed PRs, when there is an open issue (which I linked you to)

> Failed to mention this is occuring on the everything branch. my extend_valid_targets.py file contains this

`everything` hasn't been updated yet. You can see the changes here if you want to apply them before `everything` gets updated: https://github.com/LandSandBoat/server/pull/345/files

```
import array
import mysql.connector

def migration_name():
return "Extend validTargets from tinyint to smallint"

def check_preconditions(cur):
return

def needs_to_run(cur):
cur.execute("SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'item_usable' AND COLUMN_NAME = 'validTargets';")
row = cur.fetchone()[0]
return row == "tinyint"

def migrate(cur, db):
cur.execute("ALTER TABLE item_usable MODIFY COLUMN validTargets SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';")
cur.execute("ALTER TABLE spell_list MODIFY COLUMN validTargets SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';")
db.commit()
```

**Comment by kaincenteno** [comment]
something i just realized, is this import really needed? Cuz I thought item* and spell* tables are not character related so they just get re-imported as a whole which shouldgive the correct type.

**Comment by zach2good** [comment]
That... is actually a very good point... I'm a 🤡 hahaha

**Comment by kaincenteno** [comment]
this was removed in https://github.com/LandSandBoat/server/pull/1382
