### ISSUE TITLE
🐛 Dying before setting a homepoint, Sends player to Zone 0 on respawn.

### ISSUE THREAD

**Issue by ffxijuggalo** [DerpyProjectGroup/topaz#3417]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Create a new character. Go out and fight a mob and die. Respawn, you'll end up in Zone 0 stuck in midair. GM is needed ingame to fix player's position.

## Expected behavior

Same as above except when you respawn, you end up in your starting nation.

**Comment by WinterSolstice8** [comment]
Looks like this happens if intro CS is disabled based on the code

**Comment by ffxijuggalo** [comment]
> Looks like this happens if intro CS is disabled based on the code

I'll enable that, then test a new character dying to see if it still occurs.

**Comment by claywar** [comment]
So question, how is a new player dying during that initial event?

**Comment by ffxijuggalo** [comment]
> So question, how is a new player dying during that initial event?

Lvl 1 and didn't make it past the first mob.

**Comment by ffxijuggalo** [comment]
> > Looks like this happens if intro CS is disabled based on the code
> 
> I'll enable that, then test a new character dying to see if it still occurs.

Tested this myself just a few minutes ago.
Started a new character, with NEW_CHARACTER_CUTSCENE set to 0 on the server.
Died without setting a homepoint first, respawned in zone 0

Started a new character, with NEW_CHARACTER_CUTSCENE set to 1 on the server.
Died without setting a homepoint first, respawned in Northern San' Doria
