### ISSUE TITLE
Charged rings (echad, warp, etc.) stopped working

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#343]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Canaria updated today (everything branch), rings worked fine last night.

**Comment by kaincenteno** [comment]
Just wanted to note here that there is no debug message in topaz_game when using the items.

We are in everything branch [commit 678d59d]

```
cur.execute("ALTER TABLE item_usable MODIFY COLUMN validTargets SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';")
cur.execute("ALTER TABLE spell_list MODIFY COLUMN validTargets SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';")
 ```
 was executed manually as the script failed.
