### ISSUE TITLE
🐛 Xarcabard Outpost NPCs missmatch

### ISSUE THREAD

**Issue by pixelyami** [DerpyProjectGroup/topaz#3438]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

## Branch affected by issue 

`base`

## Steps to reproduce

The Nation in control of Valdeaunia region does not place the correspondent Flag/NPC at the Outpost

| Nation in control |          Flag       |                    (npcid) NPC                      |
| ------------------- | --------------- | ---------------------------------------- |
| San d'Oria            | Beastmen       | (17236292) Magumo-Yagimo, W.W. |
| Bastok                  | San d'Oria      | (17236290) Jeantelas, R.K.                 |
| Windurst              | Bastok            | (17236291) Kaya, I.M.                        |
| Beastmen             | Windurst        |                **_no NPC_**                           |

## Expected behavior

The Outpost Flag/NPC should reflect the Nation in control of the Valdeaunia Region.

**Comment by claywar** [comment]
Fixed by #3905
