### ISSUE TITLE
🐛 Lots of onMobDeath error (fallbackHandler)

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#3464]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

OS: Windows11

## Branch affected by issue 

`base`

## Steps to reproduce

I'm getting lots of error while killing mobs.  You can also try !hp 0 (mob target) too. Tested on last version as today.

![error](https://user-images.githubusercontent.com/11011463/210282363-7ef02074-dad2-48f6-8431-2426551cc8ec.png)

**Comment by TeoTwawki** [comment]
this is from pets, who are technically mobs. And easy way to silence it is to give them a dummy blank script with an empty onMob Death function defined

**Comment by Gradius2** [comment]
> this is from pets, who are technically mobs. And easy way to silence it is to give them a dummy blank script with an empty onMob Death function defined

Pets?  I was killing gobs, worms, undeads, etc.

**Comment by TeoTwawki** [comment]
Like I see that anytime I dismiss a bst or smn pet. are you teh sole player on your server?

I'm not getting any such error in my log from killing stuff at random - including worms gobs undead etc


It will happen on any mob that doesn't have the function. which happens to be a lot of pets atm, and anything custom made would do it if not given it as well.

**Comment by Gradius2** [comment]
Yes, I was alone as nin/war.

**Comment by zach2good** [comment]
I just went and did `!hp 0` on every kind of regular mob in KRT; no errors.

As Teo says:
> this is from pets, who are technically mobs. And easy way to silence it is to give them a dummy blank script with an empty onMob Death function defined
> Like I see that anytime I dismiss a bst or smn pet

Goblin Gruel (pet):
```
[01/02/23 22:50:44:896][map][error] luautils::onMobDeath: .\scripts/globals/interaction/interaction_lookup.lua:382: attempt to call local 'fallbackHandler' (a nil value)
stack traceback:
        .\scripts/globals/interaction/interaction_lookup.lua:382: in function <.\scripts/globals/interaction/interaction_lookup.lua:378> (luautils::OnMobDeath:3487)
```

If you're getting these errors on your regular mobs, something is very very wrong, if you have custom stuff on; take it off and try again.

(the errors on pet death are expected and are harmless noise)

**Comment by TeoTwawki** [comment]
its harmless noise on every occurrence really, but theres not yet a good way to avoid it while keeping useful errors we would want to see (dummy scripts is a band-aid/workaround)

I actually didn't realize mob's pets did it to. I'd been seeing it mainly on players pets. So that stands to reason any mob that doesn't have the function probably does it too. /shrug

**Comment by Gradius2** [comment]
> If you're getting these errors on your regular mobs, something is very very wrong, if you have custom stuff on; take it off and try again.

The only custom stuff I'm using is "remastered" graphics.

**Comment by TeoTwawki** [comment]
Graphics aren't server side, so not what we're talking about.

Any modified or made up new mobs etc - that'd be "custom"

**Comment by Gradius2** [comment]
Exactly... Aside graphics, nothing has been changed.

**Comment by TeoTwawki** [comment]
look, he only said IF there was anything, roll it back. If there is not, there isn't anything to get defensive over.

Your graphics changes aren't even relevant so we don't need to be having this discussion.

**Comment by TeoTwawki** [comment]
In any case, its perfectly safe to ignore until we make changes to have cleaner logs. Or you can make dummy scripts to make it stfu now.

**Comment by Gradius2** [comment]
"stfu" you said?  How a "contributor" can act like that ?!

**Comment by Gradius2** [comment]
> In any case, its perfectly safe to ignore until we make changes to have cleaner logs. Or you can make dummy scripts to make it stfu now.

"stfu" you said? How a "contributor" can act like that ?!

> there isn't anything to get defensive over.

Who is been "defensive over" ?!?!?

**Comment by zach2good** [comment]
> Or you can make dummy scripts to make it stfu now.

To make the program stfu with logging so much, he wasn't being rude to you.

**Comment by Gradius2** [comment]
> > Or you can make dummy scripts to make it stfu now.
> 
> To make the program stfu with logging so much, he wasn't being rude to you.

Well, I would never use such term even for a log or program.

**Comment by TeoTwawki** [comment]
> "stfu" you said? How a "contributor" can act like that ?!

Unless your name is "it" you have zero to be offended over.
