### ISSUE TITLE
🐛 Even More Gullible's Travels Quest - Cutscene broken

### ISSUE THREAD

**Issue by TonzoffunCE** [DerpyProjectGroup/topaz#3472]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

When attempting to start the quest "Even More Gullible's Travels" (progression quest for the Opo-opo Crown), the opening CS does not advance and locks the client. It does not flag the quest as "Accepted".

## Expected behavior

When starting this quest, the cutscene should play through and the quest should be accepted by the player.

**Comment by claywar** [comment]
Have you removed addons and turned off any framerate changes?

**Comment by TonzoffunCE** [comment]
Player has confirmed that no enternity addon has been used and frame rate was set to 30 fps. I have not confirmed that ALL addons have been removed while trying this, I can have this be tested and reply back if desired?

**Comment by claywar** [comment]
Please do.  This smells like an issue with addons, but there's always the possibility of something else.  I've had some events that Windower just doesn't like as well in the past, and had to run with just xiloader (there's one in SoA missions)

**Comment by TonzoffunCE** [comment]
Will test and report back, thanks.

**Comment by TonzoffunCE** [comment]
Confirmed that this is still an issue with no addons loaded.
