### ISSUE TITLE
🔨 Add CI checks for old/deprecated functions

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#3475]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

As an example: `getn()`
Used to get the number of entries in a table.
It isn't used anymore in mainline LUA. (Current use is `#table_name`)

I'm sure there's many other examples of functions we don't want to be using anymore.

**Comment by zach2good** [comment]
Addressed in https://github.com/LandSandBoat/server/pull/3476

I had a look at deprecated functions in Lua 5.1, Lua 5.2 and a little into what exists in LuaJIT, this is fine for now
