### ISSUE TITLE
🐛 Document time zone assumption for server and/or change guild pattern logic

### ISSUE THREAD

**Issue by TracentEden** [DerpyProjectGroup/topaz#3500]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Essentially, if the server local timezone (specifically value gotten by localtime_r in linux or localtime_s in windows) is not set to JST (japan standard time), there can be synchronization issues with guild item changing and guild point counter resetting (see this ASB [PR](https://github.com/AirSkyBoat/AirSkyBoat/pull/2605) for more detail). The options are to either document that the server should have JST timezone or to make a change like the aforementioned PR. Though given that the client has hardcoded expectations about certain events happening at certain JST times, probably safest to do both (in case a non-JST server would cause some other unexpected client issues). More detail about the hardcoded client restrictions at https://github.com/project-topaz/topaz/pull/1215, https://github.com/project-topaz/topaz/issues/552, https://github.com/project-topaz/topaz/issues/875, https://github.com/project-topaz/topaz/pull/914, and https://github.com/project-topaz/topaz/pull/1211

**Comment by cocosolos** [comment]
This was a previously fixed issue, looks like the changes accidentally got reverted in #2067. It shouldn't be necessary to change the server timezone since there now exists a whole set of JST time functions for things that require it (there's still a few things that use os.date that probably shouldn't but aren't exactly important), the ASB PR should be sufficient.

**Comment by cocosolos** [comment]
Just some other notes related to this issue, there's only a few things left that use system time (in the core anyway): an unused fishing function called [GetSundayMidnightTimestamp](https://github.com/LandSandBoat/server/blob/ee7720544952f96027f411a15df90be0c21778a5/src/map/utils/fishingutils.cpp#L156) and the [conquest map packet](https://github.com/LandSandBoat/server/blob/c487c38cef5c6e6ab3a39e55acd3aa88d854904b/src/map/packets/conquest_map.cpp#L113) with a function called [GetNexTally](https://github.com/LandSandBoat/server/blob/de8785519e78779164eac70f6eb0499a4d8b18f7/src/map/conquest_system.cpp#L636) (this should be GetNextTally).
