### ISSUE TITLE
🐛 DNC abilities not working correctly.

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3512]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win10

## Branch affected by issue 

`base`

## Steps to reproduce
```
Issue 1) Wild Flourish is unusable

Attempting to activate Wild Flourish results in the message "You have not earned enough finishing moves to perform that action", the ability fails to activate, and no finishing moves are consumed.

Expected behavior: Readies target for a skillchain (Chainbound) for up to 3 seconds.  Also, expected to cost 2 finishing move charges.


Issue 2) Building Flourish has no effect

Building Flourish will activate, consume all available finishing moves (1-5), and have no apparent effect on weaponskill damage.

(Was tested no reliable/significant damage difference)

Expected Behavior: Consumes up to 3 finishing moves and provides a boost on next weapon skill:
    1 Finishing move: Accuracy+40
    2 Finishing moves: Accuracy+40 and Attack+25%
    3 Finishing moves: Accuracy+40, Attack+25%, and Critical Hit Rate+10%.


Issue 3) Divine Waltz consumes the incorrect amount of TP

Divine Waltz is usable at 400 TP, but appears to consume TP based on the amount of players/trusts affected. 
Solo: 400 TP
1 Trust: 800 TP
2 Trusts: 1200 TP
3 Trusts: 1600 TP
4 Trusts: 2000 TP
5 Trusts: 2400 TP

Expected behavior: AOE heal with power close to a Curaga.  Cost is supposed to only be 400TP, and the cost is not supposed to be dependent on the amount of trusts/player affected.
```
## Expected behavior

I believe these were all working as of a few updates ago (for us).
Not sure what has changed. Expected behaviors are in line, above.

**Comment by Xaver-DaRed** [comment]
This was fixed
