### ISSUE TITLE
🐛 Mog House "Change Floors" option available after completing only one exit quest

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#3514]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch

`base`

## Steps to reproduce

- Complete only 1 exit quest
- The "Change Floors" option is available when you try to leave the mog house in the area you completed the quest
- As of https://github.com/LandSandBoat/server/pull/3463, it will just dump you back in the MH first floor with no ill effect
- It's still possible to do the 3 quests, get the CS, and then be able to _actually_ change floors

![image](https://user-images.githubusercontent.com/1389729/213578201-6521cd9e-51a6-48e7-9cfa-0c1410c780cc.png)

## Expected behavior

The option should be greyed out until its properly usable

**Comment by GravesXI** [comment]
Found an issue with MH after the change floors was added. you can't exit the Mog House if you pick Select an area to exit to and pick the area you entered from it puts you in a loop of just staying in your MH I have a video I can post in ffxi private server as well if needed it's to big to post in here

**Comment by zach2good** [comment]
Oh yeah, confirmed; things act strangely in that situation, but seem to work OK if you select the first page option for "Area you came from"
