### ISSUE TITLE
🐛 losmeshes empty directory 

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#3533]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

Started server today and got this ./losmeshes/ directory isn't present or is empty (do_init:283)

I checked and it's empty.  I never saw that before.  So I'm confuse.

Update didn't pulled anything from that directory.  Checking the source, I can see there are some files here (on github).

**Comment by Gradius2** [comment]
Downloaded the code (as zip) right now, and that directory is empty.

**Comment by Xaver-DaRed** [comment]
Both losmeshes and navmeshes are submodules
If you are going to download the project as a zip, you have to download those aswell by clicking on them and downloading them in the same way you downloaded the project

**Comment by zach2good** [comment]
> Downloaded the code (as zip) right now, and that directory is empty.

The project is a working git repo, when you download as a zip you're stripping away all of the git information. Thats why we don't list this as a way to set up your server in the setup guides.

This PR:
https://github.com/LandSandBoat/server/pull/3524

Adds a new submodule folder, which doesn't get pulled normally with a git update. Theres a new maintenance task in `dbtool.py` that will update your submodules for you, or you can use the command: `git submodule update --init --recursive --progress`

**Comment by zach2good** [comment]
Though, while its very rare that we update our submodules, it could be made clearer on the wiki: <https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide#to-update>

I'll PR that new command in now, just for completions sake

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/lsb-wiki/pull/56

**Comment by Gradius2** [comment]
git submodule update --init --recursive --progress

Did the trick, thanks.
