### ISSUE TITLE
🐛 Custom Menus Fail On JP Language

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#3570]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

Latest

## Steps to reproduce

  - Run a client in Japanese language.
  - Perform `!afkcheck` on the character.
  - It will always fail to check properly regardless of what option is selected.

## Expected behavior

  - Expected is they would pass if proper option is selected.

This is currently broken because of how LSB is handling the response packet. The client responds differently when it is set to Japanese language. For example, the AFK check response will look like this instead:

```
GMTELL(Atomos):Ž¿–â(AFK Check: Please pick true statement (30s)):Œ‹‰Ê( 6 + 10 = 16)
```

The current parsing to pull the answer from the response is only setup to handle English in LSB:
https://github.com/LandSandBoat/server/blob/3980492af34c0efaa31ae386d9ac4a25c2c3d0ca/src/map/lua/luautils.cpp#L5357

**Comment by kaincenteno** [comment]
isn't jp text ids also different than the ones that we have hardcoded? (cuz otherwise would be good just blocking japan clients from logging in as the experience might not be as good)

**Comment by TeoTwawki** [comment]
> isn't jp text ids also different than the ones that we have hardcoded? (cuz otherwise would be good just blocking japan clients from logging in as the experience might not be as good)

not exactly; for the most part client knows what do to for things like cs events without there being a separate jp version of it - same ID. Message special strings I think its just showing the English one, but I am not sure. In many cases that'd be the case on retail Anyway. Any PrintToPlayer strings, if you attempt to put in non English text it'll get garbled due to codepage issues (SE uses a modified form of ShiftJiS so the characters bytes do not align properly) so we would need some special handling to account for that like polutils does.

**Comment by zach2good** [comment]
@atom0s do you have the string available for when someone on a JP client cancels out of a custom menu? I'm having some trouble getting a JP client set up, so I'll just regex it

**Comment by atom0s** [comment]
Canceling out looks like this:
```
GMTELL(Atomos):Ž¿–â(AFK Check: Please pick true statement (30s)):Œ‹‰Ê(ƒLƒƒƒ“ƒZƒ‹)
```

The parts of the message for the JP client are the ShiftJIS-packed bytes for the following:

  - `8E BF 96 E2` - `Ž¿–â` - Translates to: `question`
  - `8C 8B 89 CA` - `Œ‹‰Ê` - Translates to: `result`
  - `83 4C 83 83 83 93 83 5A 83 8B` - `ƒLƒƒƒ“ƒZƒ‹` - Translates to: `cancel`

A useful site for dealing with the ShiftJIS packed strings in FFXI is: http://freaka.freehostia.com/charset_js.html

_You can give it the raw hex bytes of a packed string and it will unpack and convert it to the proper Japanese text, then can use Google Translate, or similar, to know what it actually says._

**Comment by atom0s** [comment]
For reference, here is the clients raw !afkcheck responses in the different states on the JP client:

**Option Selected**
```
GMTELL(Atomos):Ž¿–â(AFK Check: Please pick true statement (30s)):Œ‹‰Ê( 5 +  4 =  9)

0000h: 47 4D 54 45 4C 4C 28 41 74 6F 6D 6F 73 29 3A 8E  GMTELL(Atomos):Ž 
0010h: BF 96 E2 28 41 46 4B 20 43 68 65 63 6B 3A 20 50  ¿–â(AFK Check: P 
0020h: 6C 65 61 73 65 20 70 69 63 6B 20 74 72 75 65 20  lease pick true  
0030h: 73 74 61 74 65 6D 65 6E 74 20 28 33 30 73 29 29  statement (30s)) 
0040h: 3A 8C 8B 89 CA 28 20 35 20 2B 20 20 34 20 3D 20  :Œ‹‰Ê( 5 +  4 =  
0050h: 20 39 29 00                                       9).
```

**Canceled (Hit Escape Instead Of Picking An Option)**
```
GMTELL(Atomos):Ž¿–â(AFK Check: Please pick true statement (30s)):Œ‹‰Ê(ƒLƒƒƒ“ƒZƒ‹)

0000h: 47 4D 54 45 4C 4C 28 41 74 6F 6D 6F 73 29 3A 8E  GMTELL(Atomos):Ž 
0010h: BF 96 E2 28 41 46 4B 20 43 68 65 63 6B 3A 20 50  ¿–â(AFK Check: P 
0020h: 6C 65 61 73 65 20 70 69 63 6B 20 74 72 75 65 20  lease pick true  
0030h: 73 74 61 74 65 6D 65 6E 74 20 28 33 30 73 29 29  statement (30s)) 
0040h: 3A 8C 8B 89 CA 28 83 4C 83 83 83 93 83 5A 83 8B  :Œ‹‰Ê(ƒLƒƒƒ“ƒZƒ‹ 
0050h: 29 00 00 00                                      )...
```

**Comment by atom0s** [comment]
> isn't jp text ids also different than the ones that we have hardcoded? (cuz otherwise would be good just blocking japan clients from logging in as the experience might not be as good)

Out-right blocking a version of the client is not really ideal. There are a lot of people using the JP client across several servers.

The client deals with the text ids locally anyway and should be working fine as-is on the JP client. _There may be some edge cases where stuff isn't handled properly but for the most part they should be._

When the client first loads, it has several helper functions that are executed to load DAT information for the general 'static' chunks of strings and other information. This includes loading things such as:

  - Strings: The zones given text tables.
  - Strings: The zones static entity name information.
  - Strings: Status names.
  - Strings: Action / Combat Messages
  - Strings: Emote Messages
  - Strings: Skill Names, /check responses, etc.
  - Strings: Action Effects, Element Names, etc.
  - Data: Weather Information
  - Strings: Monster Skills
  - Strings: Unity Chat

And so on. These loads are done using a special lookup table that is designed to let the client handle per-language lookups using the same base ids. This lookup table is build from a helper function that sets a pointer to a predefined table of DAT ids based on the clients current language, then uses an enum of ids to convert things to the proper index within the table to load.

For example, when loading the zones string tables the function used to do that starts with a few checks based on the current zones id and sub id, and does a lookup to this global index table like this:

```cpp
    if ( zone_sub_no < 1000u || zone_sub_no > 1299u )
    {
        if ( zone_no < 256u )
            dat_id = zone_no + FUNC_Helper_ConvertEnumToFileId(105);
        else
            dat_id = FUNC_Helper_ConvertEnumToFileId(108) + zone_no - 256;
    }
    else
    {
        dat_id = FUNC_Helper_ConvertEnumToFileId(107) + zone_sub_no - 1000;
    }
```

  - `zone_no` being the actual zone id.
  - `zone_sub_no` being the sub-instance id. (Used for things like WoE [P2] and similar.)

As an example, zone 7 is Attohwa Chasm, with no sub-id. So this would land up with:

`dat_id = zone_no + FUNC_Helper_ConvertEnumToFileId(105);`

Doing `FUNC_Helper_ConvertEnumToFileId(105)` will get the current client language base DAT file id for enum entry `105`, which would be: `6420` Then add `7` to that. Which would give:

`6427` - `ROM3\2\17.DAT` for the zones general string table.

Then any time a string lookup is told to happen on the client, it is done against this loaded table using the same indexes shared for both English and Japanese. There are helper functions for doing string lookups, such as: 

`FUNC_XiStrGet(9, 130)`

_Where 9 is the string table id, and 130 is the string index._

**Comment by atom0s** [comment]
Reporting another side-effect that was seen on Horizon. Not a bug on LSB specifically, but rather in the client itself.

There is a bug in the client that will cause it to not properly display the GM tell window, /check messages, OP warp menu, and several other dialog related things based on a bug with the blacklist. If a player has someone blacklisted and that persons character name is modified in the database to include an underscore at the start, it will break / bug any person that had that person blacklisted.

For example, take the following two characters: `Atomos` and `Atomostwo`

  - `Atomos` blacklists `Atomostwo`.
  - `Atomostwo` is potentially banned from the server, and the name is custom marked in the database as banned by editing it to be `_Atomostwo`.
  - `Atomos` will now be in a bugged state once they zone and continue to be bugged until they remove `_Atomostwo` from their blacklist.

Again, this is a bug in the client, not LSB. There is an invalid name compare happening in the client when checking the users blacklist against the name that triggered certain actions. Things like `/check`, opening a GM tell window, opening certain dialog messages like OP warps, etc. are all affected by this bug.

A simple fix/side note is to not rename characters in the database with anything non-alpha character. This check will fail on anything that does not match the following regex: `[A-Za-z]+`

_Edit: To confirm, Horizon had a custom step happening on their server when a player would delete a character, the char would be kept but the name would be changed to `_Name` to free the name up to be used again. Thus, causing the bug with anyone that had the character originally blacklisted._
