### ISSUE TITLE
SW Apollyon not working

### ISSUE THREAD

**Issue by MechaClick** [DerpyProjectGroup/topaz#358]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I updated my server on 6/18/2021 so should be pretty close to being up to date

Grabbed cosmo-cleanse and red card.  Entered SW apollyon but only the party leader was warped over to starting area and the rest of my party could not enter.  There was no mobs or anything in the instance. 
The server was spamming:
[22/Jun] [21:44:14] [Error] luautils::onBattlefieldTick: Unable to find onBattlefieldTick function for rank_2_mission

Hopefully that helps, thanks  :D

**Comment by MechaClick** [comment]
edit: fixed "x"

**Comment by zach2good** [comment]
I was under the impression that all/most of limbus was off by default because it's broken

**Comment by MechaClick** [comment]
ahhhh, I'm using the everything branch and I don't think I ever enabled anything limbus related.
