### ISSUE TITLE
Building server produces error with HTTPServer()

### ISSUE THREAD

**Issue by GanimanSwift** [DerpyProjectGroup/topaz#3598]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu 20.04

## Branch affected by issue 

`base`

## Steps to reproduce

mkdir build
cd build
cmake ..
make -j $(nproc)

```
/opt/server/src/world/http_server.cpp: In constructor ‘HTTPServer::HTTPServer()’:
/opt/server/src/world/http_server.cpp:31:24: error: use of deleted function ‘constexpr std::atomic<_Tp>::atomic() [with _Tp = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >]’
   31 | HTTPServer::HTTPServer()
      |                        ^
In file included from /opt/server/build/_deps/spdlog-src/include/spdlog/details/null_mutex.h:6,
                 from /opt/server/build/_deps/spdlog-src/include/spdlog/common.h:7,
                 from /opt/server/build/_deps/spdlog-src/include/spdlog/spdlog.h:12,
                 from /opt/server/src/common/logging.h:34,
                 from /opt/server/src/world/http_server.h:23,
                 from /opt/server/src/world/http_server.cpp:21:
/usr/include/c++/9/atomic:198:7: note: ‘constexpr std::atomic<_Tp>::atomic() noexcept [with _Tp = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >]’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘’
  198 |       atomic() noexcept = default;
      |       ^~~~~~
make[2]: *** [src/world/CMakeFiles/xi_world.dir/build.make:349: src/world/CMakeFiles/xi_world.dir/http_server.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1063: src/world/CMakeFiles/xi_world.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

## Expected behavior
Successful build

I have done a fresh clone of the repo and repeated these steps. Same results.

**Comment by WinterSolstice8** [comment]
Upgrade to Ubuntu 22.04 and try again.

**Comment by GanimanSwift** [comment]
> 

This did the trick.. thanks. If there is a solution to support LTS releases without having to do dist upgrades, that would also be good. I didn't see anything in the wiki about this, but I might have missed. Thanks again.
