### ISSUE TITLE
Fennella not accepting guild point item fish she requested

### ISSUE THREAD

**Issue by SevenG** [DerpyProjectGroup/topaz#3610]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

ARM for personal server where reproduced, unknown for CEXI where first discovered bug

## Branch affected by issue 

`base`

## Steps to reproduce

Wait for Fennella to request one of the below fish and she won't accept them.

## Expected behavior

Fennella accepts trade and assigned points (she will do this if I clone a row in guild_item_points and I use the right id, or generate a fish with the higher ID).

It appears there are some unstackable versions of fish that got assigned as GP items, but they aren't what we get when we fish them up. Trade works if I giveitem with the higher ID, but a fished fish does not.

Confirmed fish with bad ID and correct:
bhefhel_marlin	5806    ->	4479
bluetail	    5798    ->	4399
gugru_tuna	    5805    ->	4480
monke-onke	    5801    ->	4462
nosteau_herring	5796    ->	4482
ogre_eel	    5795    ->	4481

Likely fish (not asked for them yet on my server or CEXI, but their ID doesn't match other entries out there):
giant_donko	    5800    ->	4306
shining_trout	5791    ->	4354
veydal_wrasse	5804    ->	5141

I'm not very git savvy, but think I can figure out enough to check out the code, fix the .sql files and generate a pull request, but I am probably not the guy to build a .sql patch to fix existing installs.

**Comment by Xaver-DaRed** [comment]
The problem happening is that there are 2 sets of fish. One used in fishing and one used in mog garden.
Same name, different ID.
If you can compile a list, I can fix those

**Comment by SevenG** [comment]
That makes sense, I was wondering why there were two entries to begin with, and why the higher IDs for stackables (Eel, Bluetail) wouldn't stack.  The working IDs should be the lower numbers in that list. I've confirmed Ogre Eel and Marlin on my own server, the rest is just based on my data mining in the SQL posts and other lua sources out in github.
