### ISSUE TITLE
🐛 Eschan Il'aern are not counting for multiple kill RoE Objectives

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#3621]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Linux

## Branch affected by issue 

`base`, noticed on xiweb

## Steps to reproduce

Register the multiple kill Records of Eminence Objectives (ie: daily 20 or 30 kills, the repeatable 200 kill objective)
Go to Escha Ru'aun and start taking out mobs there.  Notice that the Zdei, Gargouilles, and Phuabo all register their kills towards the objectives, but the Il'aern do not.

## Expected behavior

All experience point weilding mobs in the zone register kills towards the mulitple kill objectives.

**Comment by RAIST5150** [comment]
Should note that this may not be due to a recent change... may have been happening for a while now, just have not noticed it before.

Attaching a couple snippets from my log showing the discrepancy.

![Raist_2023 02 20_Angel](https://user-images.githubusercontent.com/73744368/220178878-a3617ae9-24d3-43cd-afd2-a6d07fdc7544.jpg)
![Raist_2023 02 20_Garg](https://user-images.githubusercontent.com/73744368/220178880-c92e06c2-479d-447d-9710-143fa45b1fea.jpg)
![Raist_2023 02 20_Shark](https://user-images.githubusercontent.com/73744368/220178881-661ed30c-8b38-4654-b846-e67e3fbfc545.jpg)

**Comment by CatsEyeXI** [comment]
Such is the case in retail also. You can complete multiple objectives at the same time.

**Comment by RAIST5150** [comment]
That is the problem though--it doesn't work with the Eschan Il'aerns.

The other mobs in Escha Ru'aun register x number of kills against the 20, 30, 200 RoE kill objectives, but not the angels.  As is showing in those logs, they register OTHER objectives (500 damage, magic burst, etc.), but not the ones tracking x number of kills.

**Comment by CatsEyeXI** [comment]
> That is the problem though--it doesn't work with the Eschan Il'aerns.
> 
> The other mobs in Escha Ru'aun register x number of kills against the 20, 30, 200 RoE kill objectives, but not the angels. As is showing in those logs, they register OTHER objectives (500 damage, magic burst, etc.), but not the ones tracking x number of kills.

I'm so sorry, I misread the title.
