### ISSUE TITLE
🐛 [WAR] JA Brazen Rush Lua error, expects number but receives nil

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3638]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

GNU/Linux

## Branch affected by issue 

`base`

## Steps to reproduce

Use Brazen rush
See error log show up.
Looks like it is implemented per https://github.com/LandSandBoat/server/issues/13 so it must be a bug
![image](https://user-images.githubusercontent.com/26943220/221953645-29c82c2c-c3b7-457a-b444-fe9c8090adf2.png)

## Expected behavior

Use Brazen Rush
Everything works as expected, the galaxy is at peace

**Comment by WinterSolstice8** [comment]
`target:addMod(xi.mod.ATTACK, 4 * jpLevel)`
should be `target:addMod(xi.mod.ATT, 4 * jpLevel)`
same with delmod
