### ISSUE TITLE
🐛 Delivery box in disallowed zone soft locks the client

### ISSUE THREAD

**Issue by DriftwoodGaming** [DerpyProjectGroup/topaz#3639]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Simply try to talk with Karlotte in Bastok Markets[S].
When interacting with this NPC you will be stuck in the delivery box scene with any keypress just refreshing the dbox menu.
xi_map server-side says: 
[info] DeliveryBox Action (0f) (SmallPacket0x04D:2290)
[debug] 4d 10 ac 03 0f ff ff ff ff ff ff ff 00 00 00 00 (PrintPacket:198)
[debug] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (PrintPacket:198)
[debug] (playername) is trying to use the delivery box in a disallowed zone [Bastok_Markets_[S]] (SmallPacket0x04D:2300)
## Expected behavior

I would expect you to be at least be able to exit out of the delivery box menu, and optimally be able to use the delivery box.

**Comment by TeoTwawki** [comment]
The bug there is the zone is disallowing it and shouldn't because legit delivery there exists.

its expected that the client could jam up doing disallowed things.
