### ISSUE TITLE
🔨 CURE_POWER setting in main.lua should effect Regen spells.

### ISSUE THREAD

**Issue by DriftwoodGaming** [DerpyProjectGroup/topaz#3645]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature
Right now adjusting the CURE_POWER setting correctly multiplies almost all heals, but ignores Regen spells effectively making them useless if this setting is ever increased, and overpowered if this setting is to be decreased. Would someone be willing to make an adjustment that takes the CURE_POWER multiplier setting into account for Regen spells? 
I.E. When you put this setting to 2.0, then Regen should restore 10 per tick instead of 5 per tick, Regen II should restore 20 per tick instead of 10 per tick, etc. Thank you for reading.

**Comment by Xaver-DaRed** [comment]
No it shouldnt. That setting is for direct healing spells, not for the tick provided by enhancing spells.

**Comment by DriftwoodGaming** [comment]
I can see what you're saying Xaver-DeRed, but do you have any suggestions as to how we could bring Regen in line with any CURE_POWER multiplier changes? When adjusted, this setting drastically changes the value of how effective or ineffective Regen becomes. I'm not dead-set on any one solution, but I would like there to be 'a solution'.

**Comment by TeoTwawki** [comment]
> I can see what you're saying Xaver-DeRed, but do you have any suggestions as to how we could bring Regen in line with any CURE_POWER multiplier changes? When adjusted, this setting drastically changes the value of how effective or ineffective Regen becomes. I'm not dead-set on any one solution, but I would like there to be 'a solution'.

you could just edit regen potency in the script where its set.. or add your own setting and include it in (preferably via a module)

**Comment by RAIST5150** [comment]
Keep in mind with just a WHM's merits and job points alone each of their regen spells can get an extra raw 10 HP/tick AND an extra flat 60 seconds duration (20 ticks). 
 This is outside of any other bonuses that may be gained from gear and such.

Was always a very efficient spell in the raw terms of mp cost and hp recovery... not sure it really needs much more help than SE has already given to it, certainly not in the base branch?

**Comment by Xaver-DaRed** [comment]
Closing this. If anyone wants to boost regen, got to enhancing_spell.lua and edit the effect power in there. Not worth a new setting.
