### ISSUE TITLE
Two Mining Point IDs got shifted in Newton Movalpolis

### ISSUE THREAD

**Issue by CactuarXI** [DerpyProjectGroup/topaz#3659]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
N/A

## Branch affected by issue 

`base`

## Steps to reproduce

Noticed this when I was syncing with LSB. The ID shifts in npc_list.sql from the February 2023 [#3594](https://github.com/LandSandBoat/server/pull/3592#issue-1579493805) patch shifted the IDs of 2 of the mining points in Newton Movalpolis. 

These are the old IDs:

        MINING               =
        {
            16826621, "Was shifted into 16826627"
            16826622, "Was shifted into 16826628"
            16826623,
            16826624,
            16826625,
            16826626,
        },

## Expected behavior

        These are the proper edited IDs below as per the new update matching the new npc_list.sql:
        
        MINING               =
        {
            16826623,
            16826624,
            16826625,
            16826626,
            16826627,
            16826628,
        },

**Comment by zach2good** [comment]
This is a good contender for using `GetFirstID("Mining_Point")`, it would take a little bit of rewriting inside `xi.helm.initZone`, but after the initial init it doesn't look like this list is needed again.

Something like:
```lua
xi.helm.initZone = function(zone, helmType)
    local zoneId = zone:getID()
    local info   = helmInfo[helmType]
    local npcs   = zones[zoneId].npc[info.id] -- Looks up npc.MINING list

--[[ Original Logic
    for _, npcId in ipairs(npcs) do
        local npc = GetNPCByID(npcId)
        if npc then
            npc:setStatus(xi.status.NORMAL)
            movePoint(npc, zoneId, info)
        end
    end
]]--

-- Possible new logic
local baseId = npcs[1]
while true:
        local npc = GetNPCByID(npcId)
        if npc == nil or npc.name != "Mining_Point" then
            return
        end

        npc:setStatus(xi.status.NORMAL)
        movePoint(npc, zoneId, info)

        baseId  = baseId  + 1
end
```

**Comment by timelessxi** [comment]
The proposed code snippet you provided is a good start, but it would need to be modified to use GetFirstID("Mining_Point") to retrieve the IDs, and to stop iterating when there are no more mining points to process. Here is an example of how the code could be modified:
```
xi.helm.initZone = function(zone, helmType)
    local zoneId = zone:getID()
    local info   = helmInfo[helmType]
    local npcId = GetFirstID("Mining_Point")
    while npcId ~= 0 do
        local npc = GetNPCByID(npcId)
        if npc then
            npc:setStatus(xi.status.NORMAL)
            movePoint(npc, zoneId, info)
        end
        npcId = GetNextID("Mining_Point", npcId)
    end
end
```
This modified code retrieves the first mining point ID using GetFirstID("Mining_Point"), then iterates through each mining point using GetNextID("Mining_Point", npcId) until there are no more mining points to process. This ensures that all mining points will be processed regardless of their IDs, and eliminates the need for a hardcoded list of mining point IDs.

**Comment by TeoTwawki** [comment]
@timelessxi we don't want to iterate at all. we want to use the 1st one found as an offset - the others will always be relative to it. ID shifts won't split them up, they will always be the same "distance" from the 1st ID wise.

**Comment by timelessxi** [comment]
@TeoTwawki Are there always 6 mining points

**Comment by TeoTwawki** [comment]
> @TeoTwawki Are there always 6 mining points

Currently yes. The client dats show 6 resource node NPCs in each zone you can do a particular type in - 6 mining points in Ifrit's Cauldron, 6 Logging Points in East Ronfaure etc.

Even if a future zone had more or less, we'd easily be able to handle that too using some tabling of which total is in which zone ID.
