### ISSUE TITLE
ongoing issues with recently updated server

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#366]
See: https://github.com/LandSandBoat/server/discussions/363 and https://github.com/LandSandBoat/server/discussions/365

@beneliezer

**Comment by CatsEyeXI** [comment]
Thanks, as stated, user is able to crash server on demand by trading AMAN voucher to AMAN reclaimer (the wrong NPC).

**Comment by claywar** [comment]
This issue impacts all trade interactions where the NPC script or Quest/Mission does not contain a valid onTrade function.

**Comment by CatsEyeXI** [comment]
do you mind explaining how this works? do one of you gentlemen work on a patch for this? is there something i can do in the meantime to prevent the crashes?

**Comment by TeoTwawki** [comment]
> 
> 
> do you mind explaining how this works? do one of you gentlemen work on a patch for this? is there something i can do in the meantime to prevent the crashes?

We suspect an interaction between 2 frameworks recently introduced that can have this as a consequence if some bit of script is missing when it gets called. Which should have safely given you an error message about said missing bit of script otherwise.

**Comment by zach2good** [comment]
> do you mind explaining how this works? 

Typically; we'll fix bugs when we have time. We're all volunteers with jobs and other commitments that we can't/won't drop because our hobby project is on fire.

Luckily, this time, you were able to provide a very useful stack trace, we found the bug, and it's a one-line fix. Clay had some time to look at it, so a fix should be up and merged pretty fast. If it was more insidious or hard to repro: :man_shrugging:

**Comment by CatsEyeXI** [comment]
excellent.. im new to participating in the git workflow, so will i know once the fix was merged? and then, how do i update my code? will all of my settings and conf/* be protected? i modified some shop.lua and a few others for instance and don't want that overwritten. Also please indiciate if I'll need to reboot...

**Comment by zach2good** [comment]
> im new to participating in the git workflow

Before anything else, please google and read some guides on how git works, and how to use git: we use it for every aspect of development and updates. A little time invested now will save you a lot of heartache later.

> so will i know once the fix was merged?

First, a pull request will be opened, which can be seen here https://github.com/LandSandBoat/server/pulls

Once it's merged, the commits from that PR will be visible here: https://github.com/LandSandBoat/server/commits/base

It's not up yet, but I imagine it will be fairly soon

> how do i update my code?

We have a guide for this here: https://github.com/LandSandBoat/server/wiki/Server-Setup-and-Maintenance-%5BLinux%5D#update

> will all of my settings and conf/* be protected?

The `conf/*` folder is ignored by git, so they'll only be removed if you delete them by hand (or by accident)

>  I modified some shop.lua and a few others for instance and don't want that overwritten.

Thats handled in the guide, with stash push/pop

> Also please indiciate if I'll need to reboot...

If you're doing any maintenance, you should always take down your server, run dbtool, rebuild your core etc. If you do updates to a live system, your players might witness _unimaginable horror_

**Comment by zach2good** [comment]
> @claywar claywar mentioned this issue now
> Add additional safety to luautils::onTrade #367

Clay beat me to it, this just has to pass CI (our automated build and run checks), then we'll merge it

**Comment by CatsEyeXI** [comment]
thanks guys... all patched up
