### ISSUE TITLE
Bibiki Bay - Mob ID Shifts, NPC ID Shifts, mobs that shouldn't exist & drop changes.

### ISSUE THREAD

**Issue by Delkathus** [DerpyProjectGroup/topaz#3689]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
***
- [x] Triple checked to make sure it wasn't just a me issue having old sql's issue.

Looks like a nice ID Shift occurred during marches update, NPC ID's also have been shifted and Air Tank now are supposed to drop from `Hobgoblin Venerer`'s as `Hobgoblin Blaggard`'s were removed from the game.

- January 2022 `Hobgoblin Blaggard`'s were removed from the game making the Air Tank item unobtainable temporarily until they were moved to `Hobgoblin Venerer`'s. Blaggard's are still in the zone but seem to be occupying some of the Locus mobs ID's. **Source**: [https://www.bg-wiki.com/ffxi/Hobgoblin_Blagger](url)

![image](https://user-images.githubusercontent.com/5308906/227289384-87c7a110-0b25-419c-b75f-5b0ee3aaac93.png)

***
Look at where the Locus Mobs should start in Bibiki Bay @ F-8 on the Map.

## Expected behaviour

Correct Mobs in zone, their names and Air Tank drop on correct mob.

**Comment by CatsEyeXI** [comment]
Current client version is 30230328_0? Because it looks fine to me...

![image](https://user-images.githubusercontent.com/65316697/232658261-4662d527-5944-432e-a0af-d1841aa71b2e.png)

**Comment by Xaver-DaRed** [comment]
Client mismatch issue. Closing
