### ISSUE TITLE
🐛 Max Merits still limited to 15 upgrades in merits.sql after merit.cpp was adjusted to acount for 45

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#3697]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Linux
## Branch affected by issue 

`base`, noticed on xiweb

## Steps to reproduce

Players still unable to upgrade Max Merits beyond 15 times even after merits.cpp was recently updated to account for 45 upgrades (75 total for category 00).  Details/links will be included in follow up post below.

## Expected behavior

Players should be able to upgrade Max Merits 45 times, along with both HP and MP 15 times (75 combined for the category).

**Comment by RAIST5150** [comment]
From the top of merits.sql:

```sql
--
-- Table structure for table `merits`
--

DROP TABLE IF EXISTS `merits`;
CREATE TABLE `merits` (
  `meritid` smallint(5) unsigned NOT NULL,
  `name` char(25) NOT NULL,
  `upgrade` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `value` smallint(5) NOT NULL DEFAULT '0',
  `jobs` int(10) unsigned NOT NULL DEFAULT '0',
  `upgradeid` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `catagoryid` tinyint(2) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`meritid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `merits`
--
-- ORDER BY:  `meritid`

INSERT INTO `merits` VALUES (64,'max_hp',15,10,1048575,0,0);
INSERT INTO `merits` VALUES (66,'max_mp',15,10,1048575,0,0);
INSERT INTO `merits` VALUES (68,'max_merits',15,1,1048575,9,0);
```

As was determined in discussion #3682, which got addressed in PR #3685 , players should be able to apply 45 upgrades to max merits in category 00, which required merit.cpp to be updated to 75 for that category's combined limit.  Unfortunately, the SQL entries that govern the individual upgrade was also still set to 15 instead of  45, so players would still not be able to properly max out this entry.

So the upgrade field for this entry needs to be changed from 15 to 45:

```sql
INSERT INTO `merits` VALUES (68,'max_merits',45,1,1048575,9,0);
```

**Comment by TeoTwawki** [comment]
_frustrated noises_

**Comment by TeoTwawki** [comment]
I was about to PR the change before remembering the 30 in the settings is supposed to be added in to reach 75..

`15+15+(15+30=45)=75`

(╯°□°)╯︵ ┻━┻

setting is broke I guess

**Comment by RAIST5150** [comment]
sometimes there are a lot of pieces to the puzzle... makes it easy to miss something.  This has turned out to be quite a squirelly one though.

**Comment by TeoTwawki** [comment]
> sometimes there are a lot of pieces to the puzzle... makes it easy to miss something. This has turned out to be quite a squirelly one though.

I dunno if I was wrong to say we needed the 1st pr now. pretty annoyed by this one.

**Comment by TeoTwawki** [comment]
apparently not the 1st time it broke either:
https://github.com/LandSandBoat/server/commit/2aa4b063c5a646b5b3309e8aac63704eb93b0df3#diff-5039fb3a8d20fb1a4723d7c658416717edf7fe58d14cb109e94dbe91e72cce8eR38

https://github.com/LandSandBoat/server/search?q=MAX_MERIT_POINTS
```cpp
ref<uint8>(0x0C) = settings::get<uint8>("map.MAX_MERIT_POINTS") + PChar->PMeritPoints->GetMeritValue(MERIT_MAX_MERIT, PChar);
```
```cpp
if (m_MeritPoints == settings::get<uint8>("map.MAX_MERIT_POINTS") + GetMeritValue(MERIT_MAX_MERIT, m_PChar))
```
I don't know why it isn't being applied. That looks like its being checked and added in properly to me.

**Comment by RAIST5150** [comment]
It looks straight forward on the surface... but then it throws a curveball at you.

Want me to reopen that original max merit discussion thread for brainstorming?

**Comment by TeoTwawki** [comment]
no, its better as an issue - I should have converted that 1st discussion into one before.

**Comment by TeoTwawki** [comment]
Xaver thinks we were right the 1st time after testing it himself, we're goin with it and seeing what if anything is fubar'd after. I don't remember what I saw when I tried this that made me think the fix was wrong.

**Comment by Xaver-DaRed** [comment]
We were right because merits are capped on 2 places.
- The individual merit level (in this case, max level would be 45)
- The category level (in this case, HP/MP/max_merit category, 75 levels combined among the 3)

We fixed the category cap, which was set at 45 (missing 30 levels, no matter where they were aloted)
But the specific merit that handles max merits was ALSO still caped at 15 in the database. So that was missing.

**Comment by TeoTwawki** [comment]
> But the specific merit that handles max merits was ALSO still caped at 15 in the database. So that was missing.

But isn't its supposed to have only 15 upgrades? Teo brain doing `15+15+(15+30=45)=75` 
```
[1→2→3→4→5→5→5→5→5→7→7→7→9→9→9]
Max combo: 75
Max per item: 15 (45 Maximum Merit Points)

    Max HP (+10 per upgrade)
    Max MP (+10 per upgrade)
    Maximum Merit Points (+1 per upgrade)
        This option follows a different progression than HP and MP.
        [1→3→5→7→9→12→15→18→21→24→27→30→33→36→39→42→45→48→51]
```

**Comment by TeoTwawki** [comment]
Don't be like Teo kids, don't look at clopedia after telling other ppl to not use clopedia.

they claim 15 per item in the category. when merit upgrades go above 15 and somehow even looking at my in game dude on retail it wasn't clicking.
