### ISSUE TITLE
Windows Mission 10 - Kupipi not handing bauble KI

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#372]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Please forgive me in advance, if I am not explaining anything properly.. I'm a fast learner.

Issue: This issue pertains to the Windurst Mission 10 "To each his own right". Kupipi does not present the player with xi.ki.STARWAY_STAIRWAY_BAUBLE. Where appropriate as experienced by several players.

Solution: Admittedly, I don't really know what I'm doing, but I was able to get the player to progress by removing the 'and missionStatus == 0' as seen below:

```
        elseif currentMission == xi.mission.id.windurst.TO_EACH_HIS_OWN_RIGHT then
--        elseif currentMission == xi.mission.id.windurst.TO_EACH_HIS_OWN_RIGHT and missionStatus == 0 then   
            player:startEvent(103, 0, 0, xi.ki.STARWAY_STAIRWAY_BAUBLE)
```

**Comment by TeoTwawki** [comment]
might be because wm10 was never completely implemented (the last boss fight wasn't working last I knew). so entirely possible this was an editors way of stopping you from reaching the broken parts.

**Comment by CatsEyeXI** [comment]
> might be because wm10 was never completely implemented (the last boss fight wasn't working last I knew). so entirely possible this was an editors way of stopping you from reaching the broken parts.

based on the wiki all nation missions are marked as implemented (green check)
https://github.com/LandSandBoat/server/wiki/What-Works

where can i find an updated status?

**Comment by TeoTwawki** [comment]
> 
> 
> > might be because wm10 was never completely implemented (the last boss fight wasn't working last I knew). so entirely possible this was an editors way of stopping you from reaching the broken parts.
> 
> based on the wiki all nation missions are marked as implemented (green check)
> https://github.com/LandSandBoat/server/wiki/What-Works
> 
> where can i find an updated status?

mistakes may have been made in assuming it worked 100% there isn't another place to direct you too. its also possible it was "fixed" but I missed the memo. but you finding it not working before there suggests its not worthy of that green check yet.

**Comment by claywar** [comment]
The final fight for Windurst is indeed broken, similar to how San d'Oria 9-2 was as well recently; this was reported from Canaria recently.  There might be something in git history to work off of, but haven't had the time to investigate.

**Comment by CatsEyeXI** [comment]
> The final fight for Windurst is indeed broken, similar to how San d'Oria 9-2 was as well recently; this was reported from Canaria recently. There might be something in git history to work off of, but haven't had the time to investigate.

ive also had several people unable to progress from sandy 6-2, rank bar is full, but guard won't offer mission. additionally if i try to !addmission forcibly, it doesn't stick in their log... 

are there debug messages anywhere for missions? id like to understand them better.

**Comment by TeoTwawki** [comment]
has anyone been force completing missions via commands?

**Comment by claywar** [comment]
This is a good point, because those GM commands do *not* reset missionStatus, same with addMission

**Comment by TeoTwawki** [comment]
> 
> 
> This is a good point, because those GM commands do _not_ reset missionStatus, same with addMission

I should add a warn to those

**Comment by CatsEyeXI** [comment]
> has anyone been force completing missions via commands?

these are new players, i dont think my team starting playing around with gm commands until after we ran into the issue...

**Comment by claywar** [comment]
`elseif currentMission == xi.mission.id.windurst.TO_EACH_HIS_OWN_RIGHT and missionStatus == 0 then`

Did you, or can you check what the missionStatus value for that player was at that time?  GM command !checkmissionstatus

**Comment by TeoTwawki** [comment]
all missions will normally start life (as in fresh flagged, no cs events or steps taken since it being added to log) with status of zero. thereafter, each non optional step will modify that variable. when the mission is completed, we send a complete mission command plus we zero out the variable for the next mission.

**Comment by CatsEyeXI** [comment]
> `elseif currentMission == xi.mission.id.windurst.TO_EACH_HIS_OWN_RIGHT and missionStatus == 0 then`
> 
> Did you, or can you check what the missionStatus value for that player was at that time? GM command !checkmissionstatus

Coming up as San d'Oriah 0? 

![image](https://user-images.githubusercontent.com/65316697/123338643-3714b480-d517-11eb-8c48-92c5779c1dc8.png)

**Comment by claywar** [comment]
If your nation is San d'Oria, then absolutely you're going to have issues trying to run Windurst missions.  That's just not going to work.

!checkmissionstatus (with no args) defaults to the nation you have selected: `logInfo = GetMissionLogInfo(player:getNation())`

**Comment by TeoTwawki** [comment]
those traitors, defecting for cookies. That what the name is from right? sandy's oreos.


Did you specify the right parameters to the command? `!checkmissionstatus {player} {log ID} {index}` from looking at its default helptext

**Comment by TeoTwawki** [comment]
> 
> 
> If your nation is San d'Oria, then absolutely you're going to have issues trying to run Windurst missions. That's just not going to work.
> 
> !checkmissionstatus (with no args) defaults to the nation you have selected: `logInfo = GetMissionLogInfo(player:getNation())`

ah, I didn't even realize we did that. TIL.

**Comment by CatsEyeXI** [comment]
> those traitors, defecting for cookies. That what the name is from right? sandy's oreos.
> 
> Did you specify the right parameters to the command? `!checkmissionstatus {player} {log ID} {index}` from looking at its default helptext

derp... it says 9...

**Comment by TeoTwawki** [comment]
so if its 9, they got 9 from something. try erasing the mission they are stuck on and setting var to 0, then have them flag from scratch. after that follow them through it and see if/where they come to a stop and get stuck at. Still pretty sure they can't get that final battle though.

As an aside the good news is this will get reworked+finished in the future anyway. its a ways off, as its not that far along but missions have been being converted to a newer better framework that helps eliminate common problems.

**Comment by CatsEyeXI** [comment]
> so if its 9, they got 9 from something. try erasing the mission they are stuck on and setting var to 0, then have them flag from scratch. after that follow them through it and see if/where they come to a stop and get stuck at. Still pretty sure they can't get that final battle though.
> 
> As an aside the good news is this will get reworked+finished in the future anyway. its a ways off, as its not that far along but missions have been being converted to a newer better framework that helps eliminate common problems.

just an honest question, but to your knowledge, are the other "big" servers using the same code? is it safe to say that everyone's mission progress is kinda borked?

**Comment by CatsEyeXI** [comment]
ultimately, i guess you can close this... i thought i had something for you, sadly it seems i didnt lol

**Comment by TeoTwawki** [comment]
> just an honest question, but to your knowledge, are the other "big" servers using the same code? is it safe to say that everyone's mission progress is kinda borked?

While pretty much everyone is using the same code\* we haven't been getting much in the way of bugs for them over the last oh I want to say 8 months ish. 

When reported, most of them tend to be very minor or player error (or server owner error, but even then its usually players or GMs did things they didn't know about). In fact we have had a very recently updated server have multiple players go through most of the nation missions start to finish without any bug reported to us.


###### \*Even those using "alternative forks" because both this project and those forks have that same identical code [from](https://github.com/DarkstarProject/darkstar) the [previous](https://github.com/project-topaz/topaz)  iterations [of](https://github.com/topaz-next/topaz) the [project](https://gitlab.com/ixion-development/ixion/)

**Comment by TeoTwawki** [comment]
> 
> 
> ultimately, i guess you can close this... i thought i had something for you, sadly it seems i didnt lol

Well on the upside I learned that GM command is supposed to auto detect your current nation if not given a log ID, but fails to do so. So in a way you did find a bug!

**Comment by CatsEyeXI** [comment]
> > ultimately, i guess you can close this... i thought i had something for you, sadly it seems i didnt lol
> 
> Well on the upside I learned that GM command is supposed to auto detect your current nation if not given a log ID, but fails to do so. So in a way you did find a bug!

i'm happy for that, at least.

**Comment by CatsEyeXI** [comment]
> so if its 9, they got 9 from something. try erasing the mission they are stuck on and setting var to 0, then have them flag from scratch. after that follow them through it and see if/where they come to a stop and get stuck at. Still pretty sure they can't get that final battle though.
> 
> As an aside the good news is this will get reworked+finished in the future anyway. its a ways off, as its not that far along but missions have been being converted to a newer better framework that helps eliminate common problems.

would you mind explaining a bit more thoroughly how i would go about resetting someone's mission progress? let's say they are stuck on sandy mission 6-2, full rank bar,  are not being offered next mission by guard... 
Both missionstatus and current mission are 0.

**Comment by TeoTwawki** [comment]
both `!checkmission` and `!checkmissionstatus` say zero?

**Comment by CatsEyeXI** [comment]
he switched nations.. :( i guess ill circle back when the issue crops up again.. in the meantime if theres any advice you can offer (kind of like we did with gdb for my issue before) to help collect the most information, that would be helpful

**Comment by claywar** [comment]
Actually, there might be an issue there that needs to be addressed.  Its quite possible that we're not resetting mission status when a player changes nations.  I'll look into that.

UPDATE: Just checked the code for nation change, and it requires both missionStatus to be 0, and currentMission to be `NONE` (65535) to change.  This logic does *not* exist in the GM command though.  Could that have been used to change nations?

**Comment by RAIST5150** [comment]
Re: Sandy 6-2 to 7-1 progression, may want to confirm if they got all the CS for the end of 6-2.  As in after returning to the door in KRT, go back to Trion's door for a CS (listed as optional on wiki), then go back to the gate guard to end the mission.

Ran Sandy straight through to Rank 10 fairly recently, and that was the path I took.  Sometimes we see where specific paths need to be taken for things to progress properly... what may be posted as optional on a wiki may actually be needed here.

**Comment by CatsEyeXI** [comment]
are !checkmission and !checkmissionstatus expected to align? 
Another player asked for us to move him past the dragon fight (broken) so we manually set him to rank 3.. 
Should i just be communicating to my players that they will not be able to normally progress through missions at this time?

![image](https://user-images.githubusercontent.com/65316697/123457779-472da200-d5b2-11eb-9798-ffead91f1123.png)

**Comment by TeoTwawki** [comment]
one is the active mission id, the other is its variable value

**Comment by zach2good** [comment]
MissionStatus is a block of information used to track things inside a mission, it should be wiped between every mission.

As far as I was aware, every nation should work at least up to rank 6 for zilart access (we haven't had any complaints about any of them for a while (across previous projects too))

**Comment by TeoTwawki** [comment]
RAIST5150 brings up a good point with optional steps sometimes mistakenly being required - and this is one thing being corrected as missions get rewritten

**Comment by zach2good** [comment]
I faintly recall that mainline cutscenes break and fall apart if you aren't using a modern/correct client version. Make sure you're doing that - I've ran and tested the rank 2 dragon fights many times and never had any issues (while doing the big scripting refactor)

**Comment by RAIST5150** [comment]
Yeah, I ran Sandy Rank 10 right at 3 weeks ago (June 3rd, was posting about the AoE kills being too fast and knackering up phase 2), so it was doable 3 weeks ago with only a few minor gotchas like an optional dialogue not firing, mass killing the horde of orcs at once not playing nice and such.  Only the first few ranks are running with the new mission lua format, so if you make it to rank 6, you are on that older code that was working a few weeks ago.

The only know "hard" block I have seen the last few weeks on Canaria (everything branch) was the second phase of Windy 9-2's fight, which is known and pending investigation/tweaking.

So there may be something outside the server-side base/everything code impacting the issue, like improper client version or something didn't get populated properly when the server was built/updated to current release?

**Comment by Xaver-DaRed** [comment]
Most common reasons for mission 2-3 (any nation) to fail are:
- Enternity and/or 60 fps addon/plugins
- Incorrect client version.

**Comment by CatsEyeXI** [comment]
> Most common reasons for mission 2-3 (any nation) to fail are:
> 
> * Enternity and/or 60 fps addon/plugins
> * Incorrect client version.

thanks, i posted this in my known issues channel on discord, hopefully it saves me some GM calls lol

**Comment by CatsEyeXI** [comment]
I've done some more research on this, here's some more information.
1. If you start the mission in Bastok, then do the Sandy -> Windy legs, you will not get the dark key as expected.
2. If you start in Windy, then do the Sandy -> Bastok legs, you get to the BC but cannot Enter (mission does not trigger the BC)

In the latter case, I asked the player to provide his client version and made sure he had no addons enabled (he did turn off his 60fps plugin after taking the screenshot, no change), also attached his missionstatus.

![image](https://user-images.githubusercontent.com/65316697/123701491-e9a68900-d82f-11eb-80d8-d549d41c4511.png)
![image](https://user-images.githubusercontent.com/65316697/123701591-0a6ede80-d830-11eb-98de-fe2d261cdbb6.png)
![image](https://user-images.githubusercontent.com/65316697/123701623-16f33700-d830-11eb-8b00-0fa5e7071ded.png)

**Comment by CatsEyeXI** [comment]
No dark key given ...

![image](https://user-images.githubusercontent.com/65316697/123706265-0c3ba080-d836-11eb-90aa-b303c8855489.png)

**Comment by claywar** [comment]
I feel like this issue is trying to track two different things.  Is this about Windurst Rank 9-x missions or 2-3?

**Comment by CatsEyeXI** [comment]
i apologize if i am getting mixed up, my heads been spinning with all of these issues recently. this pretains to the 2-3 missions. If you'd like me to create a new issue for that with this information, im more than happy to.
