### ISSUE TITLE
🐛 WoTG Quest Bonds That Never Die - Length of Jugner Ivy not obtainable from logging

### ISSUE THREAD

**Issue by Aeisu** [DerpyProjectGroup/topaz#3726]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

base - b40e6b5166

## Steps to reproduce

Begin Quest - Bonds That Never Die by speaking with Rholont
Check Shimmering Pondweed in Pashhow Marshlands S for CS
Check Overgrown Mushrooms in Jugner Forest S for CS
Try logging in Jugner Forest S for Length of Jugner Ivy (Key Item 1075)
Receive message that Item 1075 does not exit while logging

## Expected behavior

Begin Quest - Bonds That Never Die by speaking with Rholont
Check Shimmering Pondweed in Pashhow Marshlands S for CS (Note: Excenmille gets on a none existent chocobo here in the CS)
Check Overgrown Mushrooms in Jugner Forest S for CS
Try logging in Jugner Forest S for Length of Jugner Ivy
Receive Key Item LEngth of Jugner Ivy from logging in Jugner Forest S

Code: There is a small issue with server\scripts\missions\wotg\helpers.lua
Line 105 - 109 currently read like this

            zoneId == xi.zone.EAST_RONFAURE_S and
            not player:hasKeyItem(xi.ki.LENGTH_OF_JUGNER_IVY) and
            xi.quest.getVar(player, xi.quest.log_id.CRYSTAL_WAR, xi.quest.id.crystalWar.BONDS_THAT_NEVER_DIE, 'Prog') == 1
        then
            npcUtil.giveItem(player, xi.ki.LENGTH_OF_JUGNER_IVY)

Problem: the script wants a player to go to East Ronfaure S to log the Key Item then tries to give them a none existent Item not an existing Key Item

Line 105 - 109 should read like this

            zoneId == xi.zone.JUGNER_FOREST_S and
            not player:hasKeyItem(xi.ki.LENGTH_OF_JUGNER_IVY) and
            xi.quest.getVar(player, xi.quest.log_id.CRYSTAL_WAR, xi.quest.id.crystalWar.BONDS_THAT_NEVER_DIE, 'Prog') == 1
        then
            npcUtil.giveKeyItem(player, xi.ki.LENGTH_OF_JUGNER_IVY)

Solution: Change the lua to this and everything will work as expected, proper zone on line 105 and key item instead of item on line 109

**Comment by RAIST5150** [comment]
O.o  did someone script the Ghoyu's Reverie instanced fight for progressing In a Haze of Glory and not share it upstream?

That has been the snag for xiweb testing all scripts beyond that point... the required fights are not available yet.

**Comment by Aeisu** [comment]
I have been bypassing the battlefields by forcing the progress values in Heidi to test out the CS's and progress to see if anything needs adjustment since I have no clue how the battlefields are even put together.

**Comment by RAIST5150** [comment]
Ahh...  you may run into more weirdness like that. As noted in the haze of Glory script, some things are not confirmed and some assumptions were made pending confirmation with retail capture and such.

All of that is a big work in progress still.

**Comment by Aeisu** [comment]
I  have just been following https://ffxiclopedia.fandom.com/wiki/Category:Wings_of_the_Goddess_Missions so far to check for little errors and such so that once the battles are implemented the rest should work along with it. But we all know how bad the wiki can be so further captures are definitely required for the final check of it all.
