### ISSUE TITLE
Trust Koru-Moru Sub 75 Phalanx Behavior

### ISSUE THREAD

**Issue by ghost** [DerpyProjectGroup/topaz#375]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide]

Line 36 in Koru-Moru's Trust Lua results in him spamming Phalanx I on himself due to lacking the spell Phalanx II unless he's level 75. This occurs no matter who the hate target is. Changing the line to read
 
`mob:addSimpleGambit(ai.t.TOP_ENMITY, ai.c.NOT_STATUS, xi.effect.PHALANX, ai.r.MA, ai.s.SPECIFIC, xi.magic.spell.PHALANX_II)`

fixes this issue. 

Edit: Also apologies for the multiple edits, first time here.

**Comment by ghost** [comment]
The following should be noted -- this only fixes his self spam. A side effect of this change is that he won't cast tier I phalanx on himself in the event he pulls hate. That needs looked into, but this line allows him to cast Phalanx II on the member with hate in the party without going nuts (given level 75+). Level 74 and below he just doesn't use any tiers of phalanx.

**Comment by Era-Lusiphur** [comment]
Looked into this, despite a scripting fix being in place now with PR #381  . Koru-Moru isn't supposed to have Phalanx 1 at all per both wikis, with a pretty fleshed out looking list on BGwiki here: https://www.bg-wiki.com/ffxi/BGWiki:Trusts#Koru-Moru

I've got a PR for some new trusts and I can throw the adjustment for this in with them. I've caught a few trusts with some spell list issues, so this should probably be a good spot to look into troubleshooting them beyond their scripts for the near future until they all get cleaned up.

**Comment by Era-Lusiphur** [comment]
This one can be closed out now. Resolved fully.
