### ISSUE TITLE
🐛 Sneak Attack doesn't apply to Physical Blue Magic

### ISSUE THREAD

**Issue by kelppo** [DerpyProjectGroup/topaz#3753]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Arch Linux (tested commit 093fb451de4a42ca7314c0e20b125749ebbccac1 my own system)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Become BLU/THF
2. Use Sneak Attack
3. Cast a Physical Blue Magic from behind a monster
4. Sneak Attack buff remains and the Blue Magic damage doesn't seems to be affected

## Expected behavior

Sneak Attack buff should be consumed upon casting Physical Blue Magic and if the player is positioned properly the Blue Magic should crit, I originally found this issue in CatsEyeXI but apparently it also affects LSB.

**Comment by MowFord** [comment]
This is resolved by https://github.com/LandSandBoat/server/pull/4970

**Comment by Xaver-DaRed** [comment]
This was fixed in PR 4970
