### ISSUE TITLE
🐛 Missing lizards in Davoi

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#3758]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
n/a

## Branch affected by issue 
`base`

## Steps to reproduce
Head to x 164  y 0.3  z -16 in Davoi. notice there are only 2 of the 4 lizards that should be present. 1 of the 2 present ones is a placeholder for an Orc NM so he's still spawnable at least.

## Expected behavior
There are four ~~lights~~ _lizards._

I think the 2 missing ones have simply been given incorrect positions in the database, either by a missed shift many moons ago or by a capture that happened after they'd been pulled way far away.

**suggested solution:** re-do a cap and set new pos.

**Comment by TeoTwawki** [comment]
oops, I missed the x and got the bot.

**Comment by siknoz** [comment]
Know it's a bit late but capped this if you still need - 

Zone - Davoi - War Lizards Spawn Check
https://youtu.be/oWEEt0_SXms
https://www.dropbox.com/scl/fi/4tvs02i7r6llwdm7s31pt/Davoi-War-Lizards-Spawn-Check.zip?rlkey=k01d56o31fwjb1iipj03fvl0x&dl=0
