### ISSUE TITLE
🐛 Xarcabard CS with Cornelia has wrong model

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3774]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

## Branch affected by issue 

`base`

## Steps to reproduce

teleport to dynamis xarcabard for the first time
you will see a xarcabard
you will cs the wrong cornelia in the CS (https://ffxiclopedia.fandom.com/wiki/Cornelia?so=search)

## Expected behavior

The right corenilia should show up instead (https://ffxiclopedia.fandom.com/wiki/Cornelia_(Mythril_Musketeer))

**Comment by WinterSolstice8** [comment]
which CS id?
