### ISSUE TITLE
🐛 [XI_MAP]  sql error with traverser_start 

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3775]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

`base`

## Steps to reproduce

```
[04/16/23 02:48:35:045][map][error] Query: UPDATE char_unlocks SET traverser_start = unix_timestamp() WHERE charid = 936; (QueryStr:317)
[04/16/23 02:48:35:045][map][error] mysql_real_query: SQL_ERROR: Incorrect datetime value: '1681613315' for column `xidb`.`char_unlocks`.`traverser_start` at row 1 (1292) (QueryStr:318)
```
![Screenshot from 2023-04-15 19-59-45](https://user-images.githubusercontent.com/26943220/232264074-f7879821-d282-4789-92e1-9918abb987ca.png)

Unknown, posting here in case someone sees the same error and can get more info from their logs

## Expected behavior

No errors

**Comment by TeoTwawki** [comment]
I'll look into this later, datetime issues with the db columns in multiple places have been on my todo list for a long time now, time to get'r'done

**Comment by TeoTwawki** [comment]
I started to dig into all things datetime and found that field isn't even defined as a datetime field, its `int(10)` instead. And I get why - compared to everything we use datetime fields for this is special, it needs to exist prior to being filled in with a time where as the other tables are always going to have the row "born" with the current time.

Traverser stone handling changed when it got retail-accurate corrected, so I'm not so familiar with it anymore.

**Comment by TeoTwawki** [comment]
@kaincenteno check your database table field, does it say the type is INT or datestamp or what? on LSB its normally INT(10)

**Comment by kaincenteno** [comment]
thanks @TeoTwawki  you are right, i have it as 

![Screenshot from 2023-04-21 14-05-17](https://user-images.githubusercontent.com/26943220/233734745-51550024-e208-4d6e-85c9-4fb19023a781.png)

looks like i have it as timestamp as it should be according to this migration script:
https://github.com/LandSandBoat/server/blob/dede054882dfa57271c4d67f8f0d7884247542df/tools/migrations/026_abyssea_unlocks.py#L24

is this a problem that was created by that migration script as the char_unlocks create the int https://github.com/LandSandBoat/server/blob/9bc6b5f9c74f57543febd84a8c755031665455ec/sql/char_unlocks.sql#L16 ?

**Comment by TeoTwawki** [comment]
huh. if we migrated it to another type we should have the file saying that - or if we migrated FROM timestamp TO int, there would be a migration the opposite direction. @claywar I summon thee when you ain't busy

**Comment by TeoTwawki** [comment]
@kaincenteno sorry its been awhile, but can you set yours to match whats in the `char_unlocks.sql` version in your previous post and not whats in the migration file, and see if the message happens then?

**Comment by mjsalerno** [comment]
hello @TeoTwawki, @claywar  sorry to comment on an old closed issue but i still believe there is a problem with traverser stones.

the select queries all do SELECT unix_timestamp(traverser_start)
and that fails if it is an int column since that function expects a date/datetime, then the cpp code returns a 0 and no stones can ever be accumulated

on top of that when the player logs in the traverser_start column is always set to the last login time because of the code:

`if
    player:hasCompletedQuest(xi.questLog.ABYSSEA, xi.quest.id.abyssea.A_JOURNEY_BEGINS) and
    player:getTraverserEpoch() == 0
then
    player:setTraverserEpoch()
end
`
since getTraverserEpoch always returns 0

i would fix it and open a PR but im not sure how you want to go about fixing it

**Comment by WinterSolstice8** [comment]
Can you dump and upload a row effected by this bug?

Thanks

**Comment by mjsalerno** [comment]
@WinterSolstice8 I dont think the data will be very useful since it is just a unixtime. the bug is with the code not the DB. But here is the row anyway
[char_unlocks.csv](https://github.com/user-attachments/files/18291586/char_unlocks.csv)

**Comment by claywar** [comment]
Found the issue, and not sure why the previous methods are no longer working, but #6638 should resolve.  Do note that char_unlocks is a protected table, so if you have int type for traverser_start, you'll need to manually change this to timestamp

**Comment by BoundingS** [comment]
Sorry I posted a Q&A on this and maybe that wasn't the place, but I am now getting this SQL error for any character.  I had to roll it back to make the error go away.

**Comment by mjsalerno** [comment]
the `traverser_start` column in the `char_unlocks` table needs to be a timestamp data type.

im guessing there should be another migration made to change the bad ones

**Comment by BoundingS** [comment]
Is that a fix that has to be done on LSB side or something to edit on our side?
And thank you :)

**Comment by mjsalerno** [comment]
the migration should be done on the LSB side but you can fix your db now by running these on your DB

`ALTER TABLE xidb.char_unlocks DROP COLUMN traverser_start;`
`ALTER TABLE xidb.char_unlocks ADD traverser_start TIMESTAMP DEFAULT 0 NULL;`

i would make a backup just in case though

**Comment by claywar** [comment]
Just to followup, set the default value to 0, not null
