### ISSUE TITLE
🐛 [TRUST] Sometimes get stuck at begining of battle not facing enemy

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#3803]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

`base`

This is not a 100% occurance behavior but sometimes trusts get stuck looking away from enemy or far away, but after a couple seconds then they go back to follow enemy. Havent kept track of how often this has been happening for but its noticeable if you are underlevel and need the extra trust to behave properly

Look at ayame and ukah on pic bellow.

![Screenshot from 2023-04-22 16-22-47](https://user-images.githubusercontent.com/26943220/233811783-8628a947-fc29-4775-a70e-df7c62805493.png)
![Screenshot from 2023-04-22 16-24-28](https://user-images.githubusercontent.com/26943220/233811784-aa18fb02-bd50-49b2-bcf5-4e1926ce9631.png)

unsure if the same happens on retail but i assume trust always follows enemy (if they are physical attackers)

**Comment by kaincenteno** [comment]
can happen to more than 1 TRUST at a time

![Screenshot from 2023-04-22 17-14-51](https://user-images.githubusercontent.com/26943220/233812752-6a06ea78-1309-4680-9c2a-fba1b212fa1c.png)

**Comment by RAIST5150** [comment]
I noticed it most often when there were odd landscape physics/objects in the way.  Almost like that annoying brick in Jueno that stops you dead in your tracks when on auto run... like trust(s) got hung up on something and you would have to reorient the mob after grabbing hate to get everyone back on board again.

Seemed to work out better if I could get my trusts out in front of me before doing a range pull on a mob.  Once I engaged, shuffle the mob around a bit while I had hate to try getting the trusts spread around the mob, in a half or even full circle.  Range pull the mobs, but avoid hitting it with main weapon until the mob was back in that spot again.

Was more ideal to have a camp where I could basically stay in one spot, range pulling nearby mobs.  When doing a roaming pull (or worse, roaming camp) it could become more problematic.  Seemed like if the trust couldn't see the mob or find a bee-line to it, they would not participate in the next fight unless you shuffled things around to get them unstuck. Merit/cp farming turtles/worms in the back of Gustav is one of those scenarios where sometimes Ayame would be sitting on TP and staring off into space.

I did all my leveling before the Line of Site adjustment to navmesh went live.  I imagine it may be easier to reproduce some similar behavior with that in play now.  Get a trust behind a tree/bush/rock/etc. To see if it will face/move to the mob properly.

**Comment by CatsEyeXI** [comment]
confirmed

**Comment by RAIST5150** [comment]
This got really messed up tonight with Qultada.

He got stuck weird at the corner of a wall in Escha Ru'aun.  Stayed just out of melee range, but was able to use ranged attacks fine.

Strange series of events kept him from firing WS openers.  Got to 3000 TP and appeared to have the biggest brain fart.

Stopped using rolls and would not dump the TP.  Just sat there wiggling back and forth, pausing occasionally to shoot.

Resummoning would reset him... managed to get him stuck again... rinse and repeat.

So long as I could keep him free and in the open, all was good.

**Comment by noisiver** [comment]
This should be reopened, its still happening.

![image](https://github.com/LandSandBoat/server/assets/5157047/60152b68-db5f-42c4-bf75-3ea5821a6ed2)

The best way to see this happen very frequently is to use trustengage 1

The difference for me is that they never correct themselves unless the mob is close enough for them to attack it - i.e if the mob is pulled towards them and get within melee range. That's true regardless of trustengage setting.
