### ISSUE TITLE
🐛 Magian Trial 4201: luautils::onEventFinish stack index 2, expected number, received nil:

### ISSUE THREAD

**Issue by whasf** [DerpyProjectGroup/topaz#3825]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Server 2016

## Branch affected by issue 

`base`

## Steps to reproduce

User tried to complete Magian Trial 4201 but did not receive the reward.
On the server there is a lua error:

```
[04/26/23 18:18:22:992][map][error] luautils::onEventFinish stack index 2, expected number, received nil: not a numeric type 
stack traceback:
	[C]: in function 'addItem'
	./scripts/globals/magiantrials.lua:379: in function 'deliveryCrateOnEventFinish'
	./scripts/zones/RuLude_Gardens/npcs/Delivery_Crate.lua:24: in function 'fallbackHandler'
	.\scripts/globals/interaction/interaction_lookup.lua:400: in function <.\scripts/globals/interaction/interaction_lookup.lua:378> (luautils::OnEventFinish:2252)
```

## Expected behavior

I expect the player to receive the reward.

**Comment by RAIST5150** [comment]
Need to edit the issue's summary.

The problem is about getting abyssea feet +1 for thief

Initial look at this, there seems to be an error in magian.sql:

```sql
INSERT INTO `magian` VALUES (4201,12093,0,0,0,0,0,0,0,0,11249,0,0,0,0,0,0,0,0,842,0,8,0,0); -- +1 Feet
```

base feet: 12093 is raider's poulaines

reward: 11249 is raider's poulaines +1

Item to trade: 842 is giant bird feathers?

raider seal feet is actually 3195

Quantity to trade: 8 each

There may be more to the issue than just changing it from feathers to the cotrect ID for the seals. This  was the first thing I thought to check on via my phone.

Someone would need to test the impact of this change by acquiring the proper items and attempting to complete the trial after making the correction in their test environment.

**Comment by gweivyth** [comment]
@BlubParadox This is another one you could do.

**Comment by yourlocalfox** [comment]
I'll look into it

**Comment by yourlocalfox** [comment]
> Item to trade: 842 is giant bird feathers?
> raider seal feet is actually 3195
> Quantity to trade: 8 each
 
 Looking at the file and other trials, that's not normal IDs, when I worked on Trial 4718, I didn't need to touch the requisite item at all, and it worked, but checking the ID it looks for, it's looking for Dark Beads (1306) in the file, but in game it's still checking for Forgotten Touch (3495), so maybe Magian.SQL is just doing stuff weird for specifically the requisite item? 
 
 I'm not sure, i'm still trying to learn this codebase.

**Comment by yourlocalfox** [comment]
I just tested it, I didn't get an error and received the correct reward for 4201 without changing anything.

**Comment by RAIST5150** [comment]
> I just tested it, I didn't get an error and received the correct reward for 4201 without changing anything.

Claywar was working on converting things away from SQL.  May have already been converted to lua?

EDIT:
Listed correctly in the new magianobjectives.lua

```lua
[4201] = { check = checks.checkTradeTrials, reqs = { itemId = set{ 3195 } } }, -- 0 -> +1 (Raider's Seal: Ft.)
```

**Comment by gweivyth** [comment]
Welp that'd do it.  We were both scratching our heads cause the db entries were still wrong but it just...worked.

**Comment by RAIST5150** [comment]
Sounds like this can be closed now.
