### ISSUE TITLE
🐛 AH sorting broken

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#3856]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows Server 2019

## Branch affected by issue 
`base`

## Steps to reproduce
Browse rings at AH, notice items aren't sorted. Choose to sort by level. notice rings STILL aren't sorted, be confused try to reset then re-sort, exit and re-enter AH, give up after a few minutes. Note that the order DOES change, just not correctly.

## Expected behavior
See highest level rings at the top, lower level rings below.

**Comment by CynicaGaming** [comment]
We noticed sorting has all items that are in stock sorted by level at the top then a separate section of items out of stock sorted at the bottom, could this be what you are experiencing?

**Comment by TeoTwawki** [comment]
part of it. but multiple things were wrong to the point I rolled back my AH to an older version. Some items would simply never show, even if the setting that controls hiding items was OFF.
