### ISSUE TITLE
🐛 Static cast of mob name to const char* causes utf-8 compatibility issue

### ISSUE THREAD

**Issue by towbes** [DerpyProjectGroup/topaz#3881]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10 - Japanese Locale
**I understand that this is not an officially supported build, and that switching to US locale would fix this issue.  I am posting this to share what I've found while trying to build in Japanese locale.**

## Branch affected by issue 

`base`

## Steps to reproduce

1. Set windows language administrative settings to Japanese Locale.
2. To build successfully, remove the special characters　十二 from line 578　in chrono.h
3. Change line 558 in chrono.h -> use standard character 'us'
4. After successfully building and importing default database with dbtool.py, make the following changes to luautils.cpp :

Line 546: auto path = std::filesystem::u8path(filename);
Line 706: if (!std::filesystem::exists(path))

This will utilize utf-8 encoding for filesystem paths.  After rebuilding map.exe and running, a crash will happen when loading NPC mob scripts

![devenv_heNArnep8N](https://github.com/LandSandBoat/server/assets/7587673/59a2e8bf-8b92-49e1-b445-54af0ca839ed)

## Expected behavior

The issue looks to be happening in line 321 of zoneutils.cpp

PNpc->name       = sql->GetStringData(2); // Internal name

![devenv_RV02wJ0e4C](https://github.com/LandSandBoat/server/assets/7587673/6a0832dd-2823-4a1e-abfc-47dabc8c6f37)

The entry in the SQL database is:

![heidisql_gCBdiPeVWD](https://github.com/LandSandBoat/server/assets/7587673/551fcec5-5021-46f7-b2e7-c95358a517c0)

This later causes the filename to get created in a broken way:

![devenv_FDQp2u6dA6](https://github.com/LandSandBoat/server/assets/7587673/732bf016-ee25-4815-97cf-5d2522059938)

**Comment by zach2good** [comment]
Even after compiling, presumably runtime errors arise because Asian (and other?) character sets will take up 16 bit wchars and _everything_ we do with filesystem stuff is 8 bit chars.

**Comment by zach2good** [comment]
Also,
```
PNpc->name = sql->GetStringData(2); // Internal name
```

Is probably the first db call where we are pulling out string data I think, this is normally where things explode when there are database/locale issues.

I've been considering whether or not it's worth putting in a 'trap' db call before this with some error logging around it to more clearly tell people to go back to an EN locale

**Comment by towbes** [comment]
Thanks for the feedback zach.  It might be helpful to point people in that direction, as it is required to have system set in JP locale in order to type in japanese in the client (as far as my experience with setting up jp client).   The errors do point towards wchar/char conversion issues but not always super obvious that locale was the cause.

I thought there might be some hope with using u8path in the filesystem calls, but that doesn't seem to be the only issue.  I also tried modifying how the data was getting pulled from the SQL to try to convert, but if that's the case I think that would have to be done in a lot of places and probably end up causing issues elsewhere, so maybe not worth pursuing.
