### ISSUE TITLE
🐛 Summoning Magic Cast Time Merits Not Doing Anything

### ISSUE THREAD

**Issue by judgemack** [DerpyProjectGroup/topaz#3889]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

 Windows10

## Branch affected by issue 

`base`

## Steps to reproduce

See very short attached video for reproduction of the issue. Add points into the Group 1 Summoner Merit trait Summoning Magic Cast Time then attempt to cast magic using a timer. You will see the summoning magic cast time remains at 7 seconds which is the default.

## Expected behavior

Summoning Magic Cast Time should be reduced by 5% per merit level

https://github.com/LandSandBoat/server/assets/131217099/4a59e264-faa6-4373-8555-49c9fb067710

**Comment by RAIST5150** [comment]
Hmm... something is off, perhaps lag or the animation is skewing the perception or something?

Note that the cool down timer is popping up around the 5 second mark... this is when the spell is actually registered as having been cast.  The closest frame I could get showing that cooldown timer is at 5.19sec.

Fenrir's base cast time is  5 seconds:

```sql
INSERT INTO `spell_list` VALUES (297,'fenrir',0x00000000000000000000000000000100000000000000,5,86,8,128,1,38,15,5000,5000,0,0,288,2000,0,0,1.00,50,165,0,0,NULL);
```
(The 5000 entries are for cast and recast times)

How many merits were spent (text is really small on my phone)?

Keep in mind it is only 5% per merit, and there may be other factors in play as well (Fast Cast, Haste, etc.)

**Comment by Minasojo** [comment]
In the OP's video, they have spent 5 merits total for Summoning Recast time (25% total)

I myself have a Summoner with Fenrir and 0 merits spent for Summoning Recast time. 

Timing from start of cast to when the re-cast time triggered was 6 seconds.

With a 25% reduction I think that would calculate out to meaning the OP should have been closer to 4.5 seconds when the re-cast timer appeared.

**Comment by judgemack** [comment]
This is certainly bugged. In era, the cast time for Fenrir is 7 seconds, which is what the timer in the video shows. Developer Tiberon looked at the ASB and doesn't think the merit points are doing anything.

**Comment by Minasojo** [comment]
While on this subject, I replicated this test with Haste (given from Garuda's Hastega) applied and the casting time remained a constant 6 seconds. (to test Raist's comment)

What differed however was that the recast time itself was reduced from 30 seconds to 25 seconds.

If Haste is supposed to grant any reduction in spellcasting time (at least for Summoning magic) it doesn't seem to be applying. (which appears to be correct behavior)

**Comment by judgemack** [comment]
Haste does not improve cast time. Only recast time. "Fast Cast" improves cast time. This merit in discussion is supposed to improve cast time, but it is currently not having any effect.

**Comment by claywar** [comment]
Merit is referenced nowhere, so its highly likely this is not implemented.

**Comment by RAIST5150** [comment]
Out of curiosity, is there a substantial difference if you /RDM with some fast cast gear?

If the traits/bonuses are implemented, no merits and full Teal set with Fast Cast II trait active should give the same 25% reduction in cast time as a naked SMN/WHM with 5/5 merits in cast time reduction.

If nothing else, could give a frame of reference for the expected result of the merits.

**Comment by WinterSolstice8** [comment]
It looks like `CalculateSpellCastTime` does not check for summoning magic spellgroup and there is no mod for it -- it is unimplemented as Clay says, however normal Fast Cast should apply.

**Comment by RAIST5150** [comment]
> While on this subject, I replicated this test with Haste (given from Garuda's Hastega) applied and the casting time remained a constant 6 seconds. (to test Raist's comment)

Was more a point to be mindful of other factors that can come into the picture... like subjob traits and gear bonuses.

Sometimes there is more at play than we realize on the surface... like how the casting time is actually registering right at the 5 second mark and not the 6 or 7 seconds for the animations to run their course, and how we can time movement with the progress bar to start running before we see a spell animation fire on our screen.

**Comment by WinterSolstice8** [comment]
haste doesn't change cast time, only recast
fast cast does both

**Comment by judgemack** [comment]
Please note this post is to report a specific bug for the dev team to address. Please direct discussions to the discord channel. Reiterating, the bug posted here is that the Summoner's Group 1 merit trait "Summoning Magic Recast Time" is currently not working. A developer looked at the ASB and doesn't think putting merit points into the ability is doing anything.

**Comment by claywar** [comment]
That's correct. Its not.  There's no implementation for it at all, as Winter has said.

**Comment by MowFord** [comment]
this is [implemented](https://github.com/LandSandBoat/server/commit/1ffa00a448f66f902e55d772db2527138ad6919b)

**Comment by Xaver-DaRed** [comment]
As Mowford said, this is implemented now.
