### ISSUE TITLE
🔨 Add Gentoo Linux installation guide to Experimental Platforms section in the Quick Start Guide

### ISSUE THREAD

**Issue by claybie** [DerpyProjectGroup/topaz#3900]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

I have written a guide for getting LandSandBoat setup on Gentoo Linux. I would have done a pull request for this, but it seems GitHub does not allow that for wikis. Hopefully it is simple enough to clone my version of the Quick-Start-Guide below:

https://github.com/claybie/LandSandBoat-wiki/blob/master/Quick-Start-Guide.md

**Comment by WinterSolstice8** [comment]
you have to make a PR to this repo
https://github.com/LandSandBoat/lsb-wiki

**Comment by claybie** [comment]
Thank you.
