### ISSUE TITLE
🐛 shell is not adding to the magic resistances

### ISSUE THREAD

**Issue by EDGECOM666** [DerpyProjectGroup/topaz#3916]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Expected behavior

I noticed that shell is not adding to the magic resistances. (maybe its me?)

before casting
![Spell_Shell_Before](https://github.com/LandSandBoat/server/assets/6508087/545a759f-134b-4d63-a777-acbddea42ca8)

After casting
![Spell_Shell_After](https://github.com/LandSandBoat/server/assets/6508087/91eadfbe-4426-4f63-8bf3-28d77cf5b86d)

just for fun I casted barfira just to make sure the server was not glitched or my client and it added fire resist.
![Spell_Barfire](https://github.com/LandSandBoat/server/assets/6508087/7d55e886-e5fc-4f6c-b1af-c55a773af493)

If I remember correctly it 2% per spell level 

Shell I  =2%
Shell II = 4%
Shell III = 6%
Shell IV = 8%
Shell V = 10%

**Comment by Xaver-DaRed** [comment]
I don't think Shell is supposed to raise any elemental resistance/MEVA, nor display it there in the equipment window.

**Comment by EDGECOM666** [comment]
I remember when it first came out it did raise them stats but that could of changed with new formulas and stuff. I been searching to find out o.0 but no luck. if it not a bug just ignore me lol

**Comment by TeoTwawki** [comment]
you are mis-remembering whm merits involving barbells adding magic defense

[> Description: Each level of this enhancement increases the potency of Bar spells and adds a Magic Defense Bonus of 2, to a maximum of +10.](https://ffxiclopedia.fandom.com/wiki/Bar_Spell_Effect_(Merit))
