### ISSUE TITLE
Dock Windows Test.ahk

### ISSUE THREAD

**Issue by EDGECOM666** [DerpyProjectGroup/topaz#3918]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows 10

## Branch affected by issue 

`base`

## Expected behavior

Dock Windows Test.ahk
you need to change the target dir on line 504 from:
"C:\Users\FFXI\AppData\Local\Programs\Python\Python311\server\"

to

"%homedrive%%homepath%\AppData\Local\Programs\Python\Python311\server\"

otherwise it will fail because it will assume the current user is FFXI

**Comment by zach2good** [comment]
What's this for? We don't have any autohotkey stuff in the repo?

**Comment by EDGECOM666** [comment]
I just did a pull request and its in there

**Comment by EDGECOM666** [comment]
omg I Am a DERP! I forgot to delete the old test folder some stuff just ignore me sorry
