### ISSUE TITLE
🐛 BLU cannot use Burst Affinity to Magic Burst mobs that have been Skillchained.

### ISSUE THREAD

**Issue by Valitra** [DerpyProjectGroup/topaz#3948]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Unknown

## Branch affected by issue 

`base`

## Steps to reproduce

Use Burst Affinity on BLU. 
Use Magical Blue Magic Spells on a Skillchained enemy.
No additional damage or recognition of Magic Burst on enemy.

## Expected behavior

Use Burst Affinity on BLU. 
Use Magical Blue Magic Spells on a Skillchained enemy.
Enemy should be affect by additional damage/accuracy from a Magic Burst.

**Comment by TeoTwawki** [comment]
We'll see if it can be fixed before resorting to wholesale reversion. The only thing stands out to me is that the location of a status delete for it was moved to a different place but it is tough on the eyes trying to read that diff.

There is a lot I coudl say here, to you, to Enedin, to the guy that was asked to make an issue and instead posted a laugh emoji... All in all I am not liking anyones reaction but I do not want the potential for drama on our tracker or statements likely to draw other persons here to argue/defend themselves as most reasonable people would. **So we're going to focus on just the bug and ignore everything else. If anything else happens that is not bug related, I'll lock thread in a heartbeat so we're not distracted by it while we work.**

**Comment by RAIST5150** [comment]
Out of curiosity, can you burst OK off of someone else's chain without Burst Affinity?

A thought that hit me when is I saw this in magic.lua:

```lua
    if
        spell:getSpellGroup() == 3 and
        not (caster:hasStatusEffect(xi.effect.BURST_AFFINITY) or caster:hasStatusEffect(xi.effect.AZURE_LORE))
    then
        return burst
    end
```

**Comment by TeoTwawki** [comment]
@RAIST5150 the casting blue mage has to have affinity up for it to count but the game doesn't care who's started or ended the chain its happening on.

**Comment by RAIST5150** [comment]
That "not" in the conditional check is what prompted me to question if bursting happens without Affinity up though... try to rule out potential places to look for problems.  Weed out what is working properly and what not.

Get this on discord periodically... only one scenario is reported out of mutiple possibilites that may give useful clues to an elusive issue.

4 possible states to check (with/without Burst Affinity/Azure Lore), and only one was reported (Affinity up).

Does that snippet allow them to burst without Affinity up as it appears to suggest?  If it is indeed behaving that way, this may need to be investigated further.

**Comment by Xaver-DaRed** [comment]
A few things to comment on here:
- BLU was in a worse state than it is now. That is not to say it is currently in a good state. It isn't. However, at this point in time, what BLU needs is a nuclear rewrite. For that to happen, weaponskills needs a nuclear rewrite first, for obvious reasons.
Said rewrite is currently happening.
- I was the one that warned Enedlin about this rewrite. May be why he refuses to touch blue magic any further, and I can't blame him.
- This is not the place to report users or any drama from outside of this repository. The issue report is appreciated, but it should have been left at that.
- Finally, as mentioned before, BLU is eventually going to get a rewrite that will make it so we can easily adjust the spells and that will make it so spells behave as they should (considering available information ATM) Bottom line: Work is being done, it is not an abandoned project.

**Comment by TeoTwawki** [comment]
I would like to add that the burst issue turns out to be easily fixable.

**Comment by Valitra** [comment]
I apologize, I was asked to look into this and got incensed when I saw what happened. I should have taken a step back but got blinded. I didn't think I could get help with this because of that. Thank you all so much and I will definitely keep it professional in the future. Again, thank you thank you thank you. 

Also, is it okay if I clean up the submission to just what is necessary?

**Comment by Xaver-DaRed** [comment]
Yes, do clean it please
