### ISSUE TITLE
🐛 map server crashes when player zones out

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3950]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win10

## Branch affected by issue 

`base`

## Steps to reproduce

Maybe related to #3942 ?

We pulled in LSB updates this morning and having a new issue. Exact conditions unknown. 

Players have reported zones going down multiple times. Upon investigation, I can see in the logs that a player zones out just before the map server auto restarts. I have debuggers attached to some instances now, hopefully i'll be able to produce a crash dump.

1:
![image](https://github.com/LandSandBoat/server/assets/65316697/2ac84851-1880-4961-982e-1df92e4fc6e4)

2:
![image](https://github.com/LandSandBoat/server/assets/65316697/60e212b3-5761-4464-b206-a653d303170a)

## Expected behavior

Zones should not crash when players zone out.

**Comment by CatsEyeXI** [comment]
Root cause identified. Thanks.

**Comment by zach2good** [comment]
Anything we should be concerned with?
