### ISSUE TITLE
🐛 char_history entry prevails after character deleted

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#4007]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu 22.04

## Branch affected by issue 

`base`

## Steps to reproduce

* delete a character.
* character gets deleted.
* create a new character.
* char unable to be created. See logs in xi_connect 
`mysql_real_query: SQL_ERROR: Duplicate entry '1571' for key 'PRIMARY' (1062) (QueryStr:318)`
* check tables containing char data, see that there's still an entry referring to char just deleted in char_history
![image](https://github.com/LandSandBoat/server/assets/26943220/6f6a73ba-d848-4015-bdb8-bbf894094bed)

## Expected behavior

* delete a character
* character gets deleted
* create a new char
* no errors, able to log in with new char

**Comment by TeoTwawki** [comment]
Check your triggers in your database, this should be present https://github.com/LandSandBoat/server/blob/base/sql/triggers.sql#L53

**Comment by kaincenteno** [comment]
> Check your triggers in your database, this should be present https://github.com/LandSandBoat/server/blob/base/sql/triggers.sql#L53

looks valid from the current triggers

![image](https://github.com/LandSandBoat/server/assets/26943220/37ccb2b5-df29-4467-b050-351a68da44cb)

**Comment by TeoTwawki** [comment]
is your char_history table innodb format or myisam?

**Comment by kaincenteno** [comment]
> is your char_history table innodb format or myisam?

InnoDB

**Comment by TeoTwawki** [comment]
k I'm out of ideas for the moment then. That trigger should have removed the row causing the problem. And InnoDB is row level locking, not table level, so it would not have been locked by something else during the request to delete.
