### ISSUE TITLE
🐛 Eperdur; "Acting in Good Faith" does not give "Scroll of Teleport-Mea"

### ISSUE THREAD

**Issue by Valitra** [DerpyProjectGroup/topaz#4009]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

UNK

## Branch affected by issue 

`base`

## Steps to reproduce

Take "Acting in Good Faith" from Gantineux in Windurst Waters.
Go to Eldieme Necropolis and use "Spirit Incense" on a torch.
Return to Gantineux and get the "Gantineux's Letter" Key Item.
Talk to Eperdur in Northern San d'oria Cathedral.
--Error begins--
He talks to you about meeting Virnage from "Altana's Sorrow."
Receive "Scroll of Teleport-Dem"

## Expected behavior

Take "Acting in Good Faith" from Gantineux in Windurst Waters.
Go to Eldieme Necropolis and use "Spirit Incense" on a torch.
Return to Gantineux and get the "Gantineux's Letter" Key Item.
Talk to Eperdur in Northern San d'oria Cathedral.
He talks to you about meeting Gantineux from "Acting in Good Faith."
Receive "Scroll of Teleport-Mea"

## Extra
I tried talking to Virnage to see if he would flag his quest so I could test if his would give "Scroll of Teleport-Mea." However, an inspection of my Quests reveals that "Altana's Sorrow" is completed and "Acting in Good Faith" is still flagged. I do not, by recollection, remember flagging "Altana's Sorrow" at any point. I hope this helps.

**Comment by yourlocalfox** [comment]
Has anyone else been able to reproduce this bug? I've just attempted to and got the correct item, and an inspection of Eperdur.lua shows that he should be giving the correct item.

**Comment by claywar** [comment]
After looking into this, the only way to have completed Altana's Sorrow is indeed to have flagged it, gotten the KI "Letter from Virnage", and then talked to Eperdur.  This event has priority given that it was converted to Interaction Framework, and should you have tried talking to Eperdur again, then your current quest should complete.

Without checking your quest log prior, its impossible (and unlikely) that this occurred without the above.  Closing this issue, and should more information become available, please reopen.
