### ISSUE TITLE
Elemental Magics do no damage to tough or higher mobs but text logs  131071 dmg every time

### ISSUE THREAD

**Issue by vitus0123456** [DerpyProjectGroup/topaz#4012]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

change job to something that can use elemental spells, find a mob that's checked tough or higher level, !stun it then nuke.  The result is the same every time, no damage but text logs show 131071 dmg.

## Expected behavior
a nuke on tough mob should deal damage and text logs should show real dmg numbers.

**Comment by WinterSolstice8** [comment]
Are there any errors in your map log?

**Comment by vitus0123456** [comment]
> Are there any errors in your map log?

yes, these are:
[map][error] luautils::onSpellCast: .\scripts/globals/combat/magic_hit_rate.lua:243: attempt to index field 'levelCorrection' (a nil value)
stack traceback:
	.\scripts/globals/combat/magic_hit_rate.lua:243: in function 'calculateTargetMagicEvasion'
	.\scripts/globals/spells/damage_spell.lua:388: in function 'calculateResist'
	.\scripts/globals/spells/damage_spell.lua:833: in function <.\scripts/globals/spells/damage_spell.lua:816> (luautils::OnSpellCast:2825)

**Comment by WinterSolstice8** [comment]
Do you have a file named `scripts\globals\combat\level_correction.lua`?

**Comment by vitus0123456** [comment]
> Do you have a file named `scripts\globals\combat\level_correction.lua`?

yes, last modified 6/4/2023

**Comment by RAIST5150** [comment]
Unable to duplicate yet on Kain's xiweb server (Ubuntu 22.04) granted we are at least a week or so behind on commits (think last rebuild occurred shortly after boat docking got realigned).

But, this may require a specific environment/setup that I could not duplicate though...

Was on 99 BLM (i118, Mastered), in Escha Ru'aun, pulling Aerns (generally around the level 115 mark or thereabouts?).

Stunned directly via both Stun spells and Brainshaker WS, also put up shock spikes for a couple rounds as a "what if" test.  Even stuck Break on one for good measure.

Tiers 1 through 4 elemental spells were registering damage as expected, as well as a couple elemental weapon skills.

Then went to Gustav tunnel for the tortoises/worms in the back (around level 100-103 targets).  Behaved as expected there as well.

**Comment by vitus0123456** [comment]
Thanks for checking it out.  
I could replicate the problem from another machine with brand new setup and with latest pulls.  I'm not a coder but it looks like we have different pulls then? there are commits just 2 days ago that involved magic hit rate and such.
