### ISSUE TITLE
🐛 Map Server crashing due to missing files

### ISSUE THREAD

**Issue by IceWolf762** [DerpyProjectGroup/topaz#4016]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10 22H2 Build: 19045.3086

## Branch affected by issue 

`base`

## Steps to reproduce

*Server was just created from scratch a couple of hours ago.*
1. Create a brand new character.
2. Map Server crashes, log file states there are missing files:

luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Reisenjima/mobs/Quetzalcoatls_Sibilus.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Reisenjima_Sanctorium/mobs/Cloud_of_Darkness.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Walk_of_Echoes_[P1]/mobs/Odin_Prime.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Walk_of_Echoes_[P1]/mobs/Alexander.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/unknown/Zone.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/49/Zone.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Walk_of_Echoes_[P2]/Zone.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/286/Zone.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Walk_of_Echoes_[P1]/Zone.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/unknown/instances/TEST.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Ilrusi_Atoll/instances/lamia_no_13.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Lebros_Cavern/instances/lebros_supplies.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Leujaoam_Sanctum/instances/orichalcum_survey.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Bhaflau_Remnants/instances/bhaflau_remnants.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Silver_Sea_Remnants/instances/silver_sea_remnants.lua
luautils::CacheLuaObjectFromFile: File does not exist: ./scripts/zones/Ruhotz_Silvermines/instances/fire_in_the_hole.lua

## Expected behavior

Game to load character as normal.

**Comment by WinterSolstice8** [comment]
Upload the entire log file

**Comment by IceWolf762** [comment]
[map-server.log](https://github.com/LandSandBoat/server/files/11809377/map-server.log)
Here you go.

**Comment by claywar** [comment]
Looks like you're not using our repo, or perhaps have modified things.  That's gonna make it a bit complicated, and you might need to reach out to people who made those custom changes for support.

**Comment by TeoTwawki** [comment]
lemee guess, new GM char just did `!addallspells` or `!addallmaps` ?

**Comment by WinterSolstice8** [comment]
> [06/21/23 00:41:15:859][map][critical] Process main tick has taken 2000ms or more. (main::<lambda_a322244016d24f979c57dbe4939239a5>::operator ():254)
Watchdog thread time exceeded. Killing process.

The watchdog tripped, you can increase the timeout by increasing `INACTIVITY_WATCHDOG_PERIOD` in settings/main.lua or disabling it with `DISABLE_INACTIVITY_WATCHDOG = true`

**Comment by IceWolf762** [comment]
Sorted! Thanks to TeoTwawki's comment, I had ALL_MAPS set to 1 in `settings/main.lua`. Setting it back to 0 fixed the issue.

**Comment by TeoTwawki** [comment]
Just fyi, it'll only happen on that 1st login, and the watchdog timeout (and even if its active) are configurable. As for adding KI's lagging up the thread I'll work on that later if nobody beats me to it. You'll also see this from the 2 GM commands I mentioned.

Also please note I'd have never been able to make that guess in a million years if you hadn't posted the additional info winter requested. Consider this your 1st lesson in reading logs 😆 I saw watchdog trip within 3 seconds of that first login and I just knew.

**Comment by IceWolf762** [comment]
> Just fyi, it'll only happen on that 1st login, and the watchdog timeout (and even if its active) are configurable. As for adding KI's lagging up the thread I'll work on that later if nobody beats me to it. You'll also see this from the 2 GM commands I mentioned.
> 
> Also please note I'd have never been able to make that guess in a million years if you hadn't posted the additional info winter requested. Consider this your 1st lesson in reading logs 😆 I saw watchdog trip within 3 seconds of that first login and I just knew.

Thanks for the input! I should have known to post the full log! Still new to GitHub and didn't know you could upload full files! Anyways thanks again, will close. 😊
