### ISSUE TITLE
🐛 make_listen_bind error

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#4020]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11 x64

## Branch affected by issue 

`base`

## Steps to reproduce

I'm fully updated, compiled the last update just few minutes ago, and now I'm getting this:

[06/23/23 12:23:32:109][map][error] make_listen_bind: bind failed (socket #1, port 54230, code 10048)! (makeBind_udp:1221)

I never got such error before.

**Comment by Gradius2** [comment]
Found out the problem.  I was using Simple DNS server, if I shutdown, it works.  So, some kind of conflict?

**Comment by zach2good** [comment]
You'll get a binding failure if the socket trying to be bound (UDP port 54230) is already in use by something else, or if the socket isn't available (like we see somewhat often in our GitHub CI machines).

If your DNS server software uses that port, then it'll conflict and they'll fight over the port.

**Comment by Gradius2** [comment]
Yep, figured that much.
