### ISSUE TITLE
🐛 Grammar issue: Ternary vs Tertiary

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#4045]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

N/A

## Branch affected by issue 

`base`

## Steps to reproduce

I was poking around in the code and I saw `PTernary` listed somewhere, after PPrimary and PSecondary. This is wrong - Ternary is something made up of 3 things, *Tertiary* is the third thing in sequence after Primary and Secondary.

Specifically listing this because it's harmless and makes for a very easy PR for a newbie.

**Comment by claywar** [comment]
Note to whoever picks this up: This isn't just a mass search and replace, as Ternary is used legitimately for some things (Ternary Flourish comes to mind)

**Comment by claywar** [comment]
Closed by #4071
