### ISSUE TITLE
Windurst M1-1 Decline option still accepts the mission

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#406]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When speaking to a gate guard for the first Windurst mission, an accept/decline option is given.  For onEventFinish from Windurst gate guards, a blanket finishMissionTimeline() call is made first, which does not account for this.

M1-1 Accept: Option 1, Decline: Option 31

**Comment by Xaver-DaRed** [comment]
Is this still an issue?
