### ISSUE TITLE
🐛Chigoes do not die with certain attacks.

### ISSUE THREAD

**Issue by Aeltorian** [DerpyProjectGroup/topaz#4095]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue 

`base`

## Steps to reproduce

Do any of the expected behavior on a chigoe and watch it not die. 

## Expected behavior

As a retail To Aht Urhgan function, Chigoes had high evasion so SE decided to add that if you were to land a certain attack on a Chigoe, it'd immediately die. 

Some Sources:

Non-NMs are instantly defeated without an experience point reward when struck with a "Bash"-type [Job Ability](https://www.bg-wiki.com/ffxi/Job_Ability), [Automaton](https://www.bg-wiki.com/ffxi/Automaton) [Job Ability](https://www.bg-wiki.com/ffxi/Job_Ability), any [Weaponskill](https://www.bg-wiki.com/ffxi/Weaponskill), or critical hit.

A [Critical Hit](https://ffxiclopedia.fandom.com/wiki/Critical_Hit) or damage dealing [job abilities](https://ffxiclopedia.fandom.com/wiki/Job_Ability) such as [Jump](https://ffxiclopedia.fandom.com/wiki/Jump), [Shield Bash](https://ffxiclopedia.fandom.com/wiki/Shield_Bash), [Weapon Bash](https://ffxiclopedia.fandom.com/wiki/Weapon_Bash), or any [Weapon Skills](https://ffxiclopedia.fandom.com/wiki/Weapon_Skill) will cause them to instantly fall to the ground. You will not receive [Experience Points](https://ffxiclopedia.fandom.com/wiki/Experience_Points) from them unless they are defeated by depleting their HP.
Some non-damage dealing offensive [job abilities](https://ffxiclopedia.fandom.com/wiki/Job_Ability) such as [Box Step](https://ffxiclopedia.fandom.com/wiki/Box_Step) or [Angon](https://ffxiclopedia.fandom.com/wiki/Angon) will also cause them to fall instantly.
[Automaton](https://ffxiclopedia.fandom.com/wiki/Automaton) versions of [Shield Bash](https://ffxiclopedia.fandom.com/wiki/Shield_Bash), [Flashbulb](https://ffxiclopedia.fandom.com/wiki/Flashbulb), [Strobe](https://ffxiclopedia.fandom.com/wiki/Strobe) and other job abilities will not cause chigoe to instantly fall to the ground.
Does not work on the chigoes found in [Einherjar](https://ffxiclopedia.fandom.com/wiki/Einherjar) or [Bhaflau Remnants](https://ffxiclopedia.fandom.com/wiki/Bhaflau_Remnants).

The only thing I can think on how to code this would be an IF or IS statement that watches for these attacks but I don't know how to translate that into LUA at the moment.

**Comment by gweivyth** [comment]
Here's a PR from Wings that adds listeners for Chigoe (and other ToAU mob families) for their quirks.  Could port this over to fix this issue, or handle it differently if necessary, but would be a good reference point at the very least.

https://gitlab.com/ffxiwings/wings/-/merge_requests/283
https://gitlab.com/ffxiwings/wings/-/merge_requests/2127

**Comment by Aeltorian** [comment]
> Here's a PR from Wings that adds listeners for Chigoe (and other ToAU mob families) for their quirks. Could port this over to fix this issue, or handle it differently if necessary, but would be a good reference point at the very least.
> 
> https://gitlab.com/ffxiwings/wings/-/merge_requests/283 https://gitlab.com/ffxiwings/wings/-/merge_requests/2127

I was thinking that exact thing on needing to add listeners but I don't know how to code that specifically yet. Thanks for this

**Comment by Aeltorian** [comment]
Fat fingered that close button. Whoops

**Comment by Xaver-DaRed** [comment]
This was resolved when chigoes got their family mixins
