### ISSUE TITLE
Balayang link in Fei'Yin

### ISSUE THREAD

**Issue by Aslenta** [DerpyProjectGroup/topaz#41]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: freedom

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Balayang in Fei'Yin do not link nor do they aggro in retail. (It's a very good spot to level up!) 
Here, they do not aggro but they do link.

**Comment by Era-Lusiphur** [comment]
Went to throw this in and cannot find a source for it on the web. Got any source for this?

**Comment by Aslenta** [comment]
Not sure how far you wanted to go for "proof", but this reddit thread links to google sheet which lists Balayang and there is a note/comment that they do not link or aggro. 
https://www.reddit.com/r/ffxi/comments/99u07e/ffxi_leveling_guide/
which links to 
https://docs.google.com/spreadsheets/d/1Uq9vE7tZqMDY-Yl3fQa0TrEOudkz1On_p-ZMX8riLDM/edit#gid=0

This website lists them as linking, but I think to be incorrect. Maybe they used to link; 
https://ffxi.allakhazam.com/db/bestiary.html?fmob=8486

I have done some leveling there when I played retail, and I'm fairly certain I remember them as a non-linking mob. 

Best I could find (for now) is this post on FFXIAH from 2013; 
https://www.ffxiah.com/forum/topic/24557/skilling-up-melee-and-ranged-automatons/2/#2372867

**Comment by claywar** [comment]
I'll take time to verify this weekend, should be easy enough.

**Comment by Aslenta** [comment]
I logged into retail today now that the return to Vana'diel campaign is on to check this. They do not link or aggro. 
Tried to use DashCam but it crashed FFXI the couple of times I tried it.
