### ISSUE TITLE
Release Error

### ISSUE THREAD

**Issue by ffxijuggalo** [DerpyProjectGroup/topaz#411]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Just noticed this error whenever Release is used on summoner.

[30/Jun] [20:22:31] [Error] luautils::onMobDeath: .\scripts/globals/interaction/interaction_lookup.lua:371: attempt to call local 'fallbackHandler' (a nil value)
stack traceback:
        .\scripts/globals/interaction/interaction_lookup.lua:371: in function <.\scripts/globals/interaction/interaction_lookup.lua:367>
        [C]: in function 'despawnPet'
        ./scripts/globals/abilities/release.lua:17: in function <./scripts/globals/abilities/release.lua:16>

**Comment by kaincenteno** [comment]
I can confirm this issue is still present in the current `everything` branch.

```
[09/06/21 17:51:40:275][map][info][action] CLIENT Tevlani PERFORMING ACTION 09 (SmallPacket0x01A:1047)
[09/06/21 17:51:40:383][map][error][error] luautils::onMobDeath: ./scripts/globals/interaction/interaction_lookup.lua:371: attempt to call local 'fallbackHandler' (a nil value)
stack traceback:
        ./scripts/globals/interaction/interaction_lookup.lua:371: in function <./scripts/globals/interaction/interaction_lookup.lua:367>
        [C]: in function 'despawnPet'
        ./scripts/globals/abilities/release.lua:17: in function <./scripts/globals/abilities/release.lua:16> (OnMobDeath:3050)
```

like juggalo mentioned it happens when a PC  summoner's pet is released.

**Comment by kaincenteno** [comment]
unsure if this is still related to summoner but i saw one that refers to interactionlookup today

```
[error][error] luautils::onMobDeath: ./scripts/globals/interaction/interaction_lookup.lua:371: attempt to call local 'fallbackHandler' (a nil value)
stack traceback:
        ./scripts/globals/interaction/interaction_lookup.lua:371: in function <./scripts/globals/interaction/interaction_lookup.lua:367> (OnMobDeath:3138)
```

**Comment by TeoTwawki** [comment]
its coz pets are mobs, but are not accounted for in the interaction system yet so when onMobDeath happens there is nothing there for them. Its safe to ignore for now. Tho the log noise is annoying.

**Comment by kaincenteno** [comment]
> its coz pets are mobs, but are not accounted for in the interaction system yet so when onMobDeath happens there is nothing there for them. Its safe to ignore for now. Tho the log noise is annoying.

Aye >.< the log noise is really bad to parse other errors. Is there a way to stop the noise for this kinda scenario?
