### ISSUE TITLE
🐛 Quest - Jeuno: Bluffnix Gobbiebag blocks Lure of the Wildcat Jeuno progress

### ISSUE THREAD

**Issue by Hatberg** [DerpyProjectGroup/topaz#4119]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

- Speak with Ajithaam - Upper Jeuno (G-5) to start Lure of the Wildcat Jeuno quest
- Speak with Bluffnix - Lower Jeuno (H-9) repeatedly. Bluffnix will only mention Gobbiebags ( /scripts/quests/jeuno/helpers.lua ) and will not progress Lure of the Wildcat ( /scripts/zones/Lower_Jeuno/npcs/Bluffnix.lua )

## Expected behavior

- Should flash Wildcat badge at Bluffnix and progress bitmask accordingly:
/scripts/zones/Upper_Jeuno/npcs/Ajithaam.lua
01000    (H-9) Bluffnix (Gobbiebag quest NPC, in Muckvix's Junk Shop)

**Comment by indblagcher** [comment]
Closing -- duplicate from 2022: https://github.com/LandSandBoat/server/issues/1177

**Comment by Hatberg** [comment]
Closed, duplicate issue
