### ISSUE TITLE
🐛 Dagger WS Energy Drain Haste Effect Is 1min30s Duration At All TP Tiers

### ISSUE THREAD

**Issue by judgemack** [DerpyProjectGroup/topaz#4122]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue 

`base`

## Steps to reproduce

1. Read the in-game description of the WS "Energy Drain"
2. Confirm the era+ help text of WS "Energy Drain" is correct
3. Use WS "Energy Drain" at 1000 TP. Clock duration of haste effect
4. Use WS "Energy Drain" at 3000 TP. Clock duration of haste effect
5. Note that the times at 1000 TP and 3000 TP are equal

## Expected behavior

The buff effect of the WS "Energy Drain" should have a longer duration a higher tiers of TP with 1000 TP being the lowest and 3000 TP being the highest.

**Comment by WinterSolstice8** [comment]
Hello,

I believe you may be a little lost. Did you mean to post your issue here? https://github.com/HorizonFFXI/HorizonXI-Issues/issues

This repo is the upstream of Horizon and ASB and it doesn't look like your issue applies here.

**Comment by zach2good** [comment]
Hi there, we don't have era+, or any era for that matter, upstream (LSB) is purely a retail emulator (with some modules to tweak highly requested things down to era). Your princess is in another castle I'm afraid.

**Comment by TeoTwawki** [comment]
🍄
