### ISSUE TITLE
🐛 Conquest update maths probably wrong after recent rewrite & crash fixes

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#4126]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

All Platforms

## Branch affected by issue 

`base`

## Steps to reproduce

After https://github.com/LandSandBoat/server/pull/4090 I had to put in some emergency crash fixes to stop xi_map coming down in non-conquest zones, and during certain kinds of updates. These fixes fundementally changed how influence is tallied and calculated.

Someone will have to go in and make sure everything is correct after these changes (that exclude city and dynamis regions, I think):
https://github.com/LandSandBoat/server/pull/4102
https://github.com/LandSandBoat/server/pull/4116

## Expected behavior

Conquest math is correct, but also no crashes

**Comment by Skerxan** [comment]
Your recent emergency fixes probably solved it already but I want to add what happened on CatsEye today during/after conquest tally.
First of, it tallied 3 times.
Second, now there are regions with questionmarks when being hovered over, will immediately crash your client.
![Skerx_2023 07 23_170017](https://github.com/LandSandBoat/server/assets/33092280/15c2518d-fd81-4b4c-9ff3-35a54af138eb)
![Skerx_2023 07 23_173316](https://github.com/LandSandBoat/server/assets/33092280/54affc27-0883-4f05-8bb4-5e80e07f0e73)
![Skerx_2023 07 23_173327](https://github.com/LandSandBoat/server/assets/33092280/a63bbe1c-f015-45de-af14-e7d75e12d459)

**Comment by Xaver-DaRed** [comment]
By "Today" you mean "40 minutes ago" right Skerxan?

Would be interesting to know when was the last time Carver updated/pulled from LSB, or cherry picked the conquest fixes

**Comment by Skerxan** [comment]
That's correct.

**Comment by xkoredev** [comment]
How are you observing the math being any different? The original change should not have changed any math, just moved stuff around. I wonder why the triple tallying is happening?

**Comment by Xaver-DaRed** [comment]
Fresh LSB build with fresh database.

Bastok owns 2 regions
Sandoria owns 3 regions
Windurst owns 4 regions
![imagen](https://github.com/LandSandBoat/server/assets/60053999/6c4fb4b1-5e26-460d-a972-056830e84a8e)
![imagen](https://github.com/LandSandBoat/server/assets/60053999/4731f0e1-e144-4e0a-bc46-767ff570780e)

The issues I see:
- Sandoria shouldnt be first. Windurst should.
- Bastok and Windurst should not be allied.
