### ISSUE TITLE
🐛 Can't log in server: Wrong version number (SSL routines), Failed to handshake!

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#4138]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

### Discussed in https://github.com/LandSandBoat/server/discussions/4137

<div type='discussions-op-text'>

<sup>Originally posted by **vitus0123456** July 21, 2023</sup>
After the latest pull, I got this error trying to log in server, any help would be appreciated:

```
[07/20/23 17:54:03:571][connect][warn] Error from127.0.0.1: (167772427), wrong version number (SSL routines) (auth_session::start::<lambda_6d68fe7479b0f0b15a8af243fea0e9c5>::operator ():39)
[07/20/23 17:54:03:571][connect][warn] Failed to handshake! (auth_session::start::<lambda_6d68fe7479b0f0b15a8af243fea0e9c5>::operator ():40)
```</div>

**Comment by zach2good** [comment]
@vitus0123456 When was the last time you pulled, did the changes you recently got include: https://github.com/LandSandBoat/server/pull/3049

which has a hard dependency on updating to https://github.com/LandSandBoat/xiloader/pull/7

I don't know what the errors would be if you didn't upgrade, but that's my first intuition

**Comment by vitus0123456** [comment]
> @vitus0123456 When was the last time you pulled, did the changes you recently got include: #3049
> 
> which has a hard dependency on updating to [LandSandBoat/xiloader#7](https://github.com/LandSandBoat/xiloader/pull/7)
> 
> I don't know what the errors would be if you didn't upgrade, but that's my first intuition

I pulled  around 5 hours ago, I just followed the [guide](https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide) to update server. I have no idea what i got from the pull.

```
To Update
Take down all of your server processes!
Open a PowerShell window and navigate to your server directory.
Stash any changes you've made and pull the latest code from upstream:
git stash
git pull
git submodule update --init --recursive --progress
git stash pop
⚠️ Pay attention! If you stashed any changes, there is a chance you will see the following:

CONFLICT (content): Merge conflict in some file

⚠️ If this happens, you need to manually edit the conflicting files before continuing.

Navigate to server\tools\ and update the database:
py -3 dbtool.py update
Open the server root folder in VS2019/2022.
CMake may reconfigure, wait for it to complete like before.
In the top toolbar, select Build > Build All.
This may take a little while if you have a weaker machine.
You should eventually see Build All succeeded..
```

**Comment by zach2good** [comment]
> which has a hard dependency on updating to https://github.com/LandSandBoat/xiloader/pull/7

Do you have the latest xiloader?

**Comment by vitus0123456** [comment]
with latest xiloader everything works again. Thank you for the pointers, much appreciated.
