### ISSUE TITLE
🔨 Add Fallen Star to HELM to support quest "Wish Upon a Star"

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#4147]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature
Currently, the R/EX item "Fallen Star" does not appear to be available through logging to allow completion of "Wish Upon a Star."  Need to determine drop rate and implement.

**Comment by CriticalXI** [comment]
Checking out Siknoz capture and I just went and did this quest myself on retail. Both of us got the fallen star on the first logging attempt.
