### ISSUE TITLE
King Behemoth onAdditionalEffect Duration Incorrect

### ISSUE THREAD

**Issue by CynicaGaming** [DerpyProjectGroup/topaz#4149]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows Server 2019

## Branch affected by issue 

`base`

## Steps to reproduce

Engage King Behemoth
Wait until his additional effect procs
Observe the duration is 16~ seconds

## Expected behavior
Duration should be ~8 seconds. 

`entity.onAdditionalEffect = function(mob, target, damage)
    return xi.mob.onAddEffect(mob, target, damage, xi.mob.ae.STUN, { chance = 20, duration = math.random(4, 8) })
end`
![Cynica_2023 07 22_123744](https://github.com/LandSandBoat/server/assets/47292146/1fc32c3c-06d1-49b8-9c0a-76e5b6d9649b)

**Comment by CynicaGaming** [comment]
It's worth noting that I think this issue expands much further than just King Behemoth and is an issue with onAdditionalEffect and possibly even modifiers in general. I could be wrong but we've experienced quite a few mods that seem substantially higher than advertised in the mob's LUA.

**Comment by TeoTwawki** [comment]
test commenting out the level correction:  
https://github.com/LandSandBoat/server/blob/base/scripts/globals/mobs.lua#L466C53-L466C53

pretty sure mobs shouldn't get level correct on theirs anyway. and this is mob only code.

**Comment by TeoTwawki** [comment]
*should not

**Comment by CynicaGaming** [comment]
@TeoTwawki That seems to have resolved the issue.
