### ISSUE TITLE
🐛 Intermittent party chat

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4160]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Party chat sometimes becomes unavailable, none of the members receive party channel messages, while other channels such as /tell and /linkshell remain working. The player is not ghosted as they are available in search.

All other channels appear to be working properly

## Expected behavior

Party chat should work in the same manner as other channels.

**Comment by EpicTaru** [comment]
Have you pulled down this PR?
https://github.com/LandSandBoat/server/pull/4136

**Comment by CatsEyeXI** [comment]
i think i just missed this one, will cherry pick it and see if the issue
resolves. thanks

**Comment by CatsEyeXI** [comment]
resolved by #4136

**Comment by zach2good** [comment]
Interesting that this solved your issue, as that was a hard-crash fix. Was your world server constantly dying and then coming back up?
