### ISSUE TITLE
🐛 Party chat is not getting passed through map server instances

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4182]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Form a party across different map server instances (at least 3 people)
Party leader tends to sometimes see the party chat (not sure if this is a red herring)
But most times players in different instances cannot see the party chat sent from another instance.
This is a newish bug. (as of a few weeks)

## Expected behavior

Party chat should be visible across all map server instances

**Comment by zach2good** [comment]
Presumably this is fixed, since people aren't screaming from the rooftops. If this is still valid, please feel free to re-open the issue.
