### ISSUE TITLE
🐛 Archlinux Build dangling reference error

### ISSUE THREAD

**Issue by siuhamlop** [DerpyProjectGroup/topaz#4206]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Linux archlinux 6.4.7-arch1-1

## Branch affected by issue 

`base`

## Expected behavior

Got lot of  `error: possibly dangling reference to a temporary [-Werror=dangling-reference] `
All errors came from /server/build/_deps/spdlog-src/ folder.
I know Archlinux is not a supported platform but hope someone could help me, thanks in advance.
![2023-08-01_10-27](https://github.com/LandSandBoat/server/assets/11884769/0a980501-2fbf-451b-b186-fe11e059b9d2)

**Comment by kaincenteno** [comment]
Hi @siuhamlop,

I don't know how to help in this issue but maybe try setting up an ubuntu LXC container and run it from there?

**Comment by WinterSolstice8** [comment]
I think your only feasible action without going to virtualization is to attempt to use an older GCC, or simply disabling the warning.

It looks like this issue is isolated to an external library that we use. I had attempted to upgrade it to a new version via cmake and it was not a simple upgrade.

There are no promises that upgrading it would actually fix your exact issue and it may be a problem with spdlog

**Comment by zach2good** [comment]
We've since updated to newer versions of spdlog (and internal fmt). If this is still a valid issue, please feel free to re-open this issue.

https://github.com/LandSandBoat/server/pull/4794
https://github.com/LandSandBoat/server/pull/4812
