### ISSUE TITLE
everything branch, Mieuseloir_B_Enchelles.lua calling one of WotG 27 CS events instead of normal dialogue

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#423]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Discovered on Canaria, running everything branch

Mieuseloir_B_Enchelles.lua (S. Sandoria (S), just outside of Lion Springs Tavern) is calling one of the CS from WotG 27 (The Scent of Battle) when you click on him.  When it gets to the black screen at the end, it just kinda hangs.

Had to call /shutdown to get out of it.

Client has not been updated to retail since the last time we synched up, so it does not appear to be a client versioning issue against the server or anything like that (yet).

**Comment by Era-Lusiphur** [comment]
I've noticed some other Southern San d'oria (S) residents on Era were starting events to later missions but neglected to make a note of it. There may be more of these than just these.

EDIT: Farouel just down the street triggers an obviously incorrect event. His buddy right next to him possibly as well (dialogue about a worm).
