### ISSUE TITLE
dbtools keep on running migration for Extended validTargets

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#427]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Extended validTargets migration keeps being ran on every express update.

Checking migrations...
Running migrations for Extend validTargets from tinyint to smallint...

**Comment by Era-Lusiphur** [comment]
I had dbtool hang on an operation yesterday. Did you try closing it and running it second time? Worked for me then.

**Comment by kaincenteno** [comment]
resolved in https://github.com/LandSandBoat/server/pull/1382
