### ISSUE TITLE
🐛 Crash Dump for HandleEnspell?

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4283]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
I've included the wheaty generated dump. I have the full one available as well if needed.

Call Stack:
![image](https://github.com/LandSandBoat/server/assets/65316697/cebc6cb1-6168-4075-8c0a-5d2ac6ecc0ed)

[minidump_enspell.zip](https://github.com/LandSandBoat/server/files/12375231/minidump_enspell.zip)

## Expected behavior

Should not crash

**Comment by zach2good** [comment]
The section in this screenshot has been rewritten since this was opened:
```cpp
                attackerID = PDefender->StatusEffectContainer->GetStatusEffect(daze)->GetSubID();

                if (PAttacker->objtype == TYPE_PC && PAttacker->PParty != nullptr)
                {
                    if (auto* PChar = dynamic_cast<CCharEntity*>(PAttacker))
                    {
                        // clang-format off
                        PChar->ForPartyWithTrusts([&](CBattleEntity* PMember)
                        {
                            if (attackerID == PMember->id)
                            {
                                power = PDefender->StatusEffectContainer->GetStatusEffect(daze)->GetPower();
                            }
                        });
```

If this is still valid, please feel free to re-open the issue.
