### ISSUE TITLE
🐛 [Partial Crash/Map] Conquest regions sometimes have the wrong map icons after recent Conquest re-work

### ISSUE THREAD

**Issue by Frankie-hz** [DerpyProjectGroup/topaz#4308]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Linux/Windows
Mac / ARM etc -->

## Branch affected by issue 

`base`

## Steps to reproduce
This was noticed on a couple live servers (CatsEye and Horion - both using LSB as a base). After pulling in the recently changed conquest rework - during the tally the zones seem to calculate correctly but you get ? or weird icons in the conquest map. Once you hover over it (not in all cases) the client will crash locally.

![image](https://github.com/LandSandBoat/server/assets/105882754/46a6e3a9-1e72-432b-bcb3-fbdbf7030d29)

Please note: I have NOT been able to replicated this locally on any client/server version. 

## Expected behavior
Have the correct region shown on the conquest map.

**Comment by Xaver-DaRed** [comment]
I was pretty sure this was fixed somewhat recently. Did it reparear, or rather, was this observed in a recent pull?

Gonna link the PR just in case...
https://github.com/LandSandBoat/server/pull/4201

**Comment by Frankie-hz** [comment]
We indeed have this pull. The person who wrote the system pulled it into ASB for us and also straight to our liver server. I did a once over of the conquest code and its a 1:1 copy. I wish I could locally replicate it...

**Comment by Frankie-hz** [comment]
It looks like there is garbage being passed from world server to the map at region 18. Kore is taking a look at fixing this.

**Comment by kaincenteno** [comment]
been happening on xiweb for a while, just tested it again

We are on commit [614d620](https://github.com/landsandboat/server/commit/614d620410c8ff2649b0db553894d4067e5a39f9) (10AUG).

Movalpolos on our region map has the Aht Ughan symbol instead of a question mark

**Comment by xkoredev** [comment]
The issue has to do with using uint32 instead of size_t for the type of size() when deserializing conquest data. I will put up a PR ASAP

**Comment by xkoredev** [comment]
https://github.com/LandSandBoat/server/pull/4314

**Comment by xkoredev** [comment]
PR is ready for review. Comments ammended.
