### ISSUE TITLE
🐛 Not able to !mount or !chocobo

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#4312]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Not able to use !mount or !chocobo. It shows you have status effect and does have timer but you are not on any mount.

## Expected behavior

Should be able to ride any !mount or !chocobo

**Comment by RAIST5150** [comment]
This could be related to #4311.  May want to verify /mount after that fix has been applied

**Comment by Mortalelite** [comment]
> This could be related to #4311. May want to verify /mount after that fix has been applied

Looks like been fixed after recent pull, gonna close this.
