### ISSUE TITLE
FileWatcher not detecting changes

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#433]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

FileWatcher not detecting changes for on-the-fly updates. 
I'm on Linux, with 2 separate installations having the same symptom.

**Comment by RAIST5150** [comment]
Seem to remember some issues a while back bound to versioning issues or something... luajit?  Forget exactly...

**Comment by CatsEyeXI** [comment]
I would like to confirm that this is still an issue even with a fresh pull/build from base. (On Linux) Is there anything i can do to help with narrowing down the problem?

**Comment by CatsEyeXI** [comment]
Further investigation: This issue  only appears to affect Linux systems, Filewatcher is working fine on Windows...  Does anyone have cycles to investigate this at all?

**Comment by zach2good** [comment]
There are now multiple reports of FileWatcher not working on native Linux systems, so we will have to swap out our 3rd party implementation for something similar that works, or roll our own.

Luckily, it doesn't look that hard: https://solarianprogrammer.com/2019/01/13/cpp-17-filesystem-write-file-watcher-monitor/

As an aside, FileWatcher is designed and intended to be used as a development tool and is in no way designed to be used on a live server with players running around in it. Just in case you were.

**Comment by TeoTwawki** [comment]
> As an aside, FileWatcher is designed and intended to be used as a development tool and is in no way designed to be used on a live server with players running around in it. Just in case you were.

but I like screwing with players on production..
