### ISSUE TITLE
🔨 Streamline wiki Post-Install and Development sections

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#4333]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

I'm generally very happy with the [Quick-Start Guide](https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide) and how it's linked from the wiki.

I think [Next Steps](https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide#next-steps), [Client Setup Windows](https://github.com/LandSandBoat/server/wiki/Client-Setup-Windows), [Post-Install Guide](https://github.com/LandSandBoat/server/wiki/Post-Install-Guide) and [Development](https://github.com/LandSandBoat/server/wiki/Development) (and associated articles) could flow together better, and be easier to navigate.

I don't have any answers for this short of flattening everything so we end up with the following headers, with ALL ARTICLES LINKED AND VISIBLE FROM THE WIKI FRONT PAGE:

Currently things are laid out like this
```
Home (Front Page):
  General:
    Quick Start Guide (Start here!)
    FAQ
    What Works?
    Contrib. Guide

  Resources

  Development
    (bunch of articles and other forward links from that page)

  Server Setup
    Server Setup Guide
      (forwards you back to the quickstart guide)

  Client Setup
    Windows 10
    Common Concerns

  Server Administration
    Server Administration Landing Page
      (bunch of articles and other forward links from that page)

  CoC
    CoC
```

If we removed all the landing pages, flattened everything out, and then moved all the development articles to the bottom of the list, everything might be quicker and easier to find - and also give us some clarity about what content we have where

**Comment by TeoTwawki** [comment]
my 2 cents:

some bit of categorization and sub-paging can be helpful, but I think the main landing page should be making everything findable and isn't. Its ok to have some category pages that do some explaining, but we should directly link the subpages _also_ - think of it more like a site map. If you already know about the topic in general but need to get to a sub page for a refresher on something, no reason to have to navigate through the category to get to it again. I often have to use the sidebar and expand it to find what I am looking for. Additionally we have what in wiki lingo are called "orphaned pages" which means _it exists but nothing actually links it._

Now technically, the sidebar search section accomplishes (its lists ALL pages) this but that's not where anyone naturally looks and the links lack any kind of context - pure page names.
![image](https://github.com/LandSandBoat/server/assets/6871475/e41422a9-c2d5-45fb-a79e-9f41f9ae8af4)

**Comment by zach2good** [comment]
I feel like the wiki is pretty streamlined these days
