### ISSUE TITLE
🐛 Not able complete RoE Quest

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#4352]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win 10

## Branch affected by issue 

`base`

## Steps to reproduce

Call Alter Ego like Excenmille and get error in Map each time attempt to complete it

![Trust](https://github.com/LandSandBoat/server/assets/108362771/2fba4cfc-09b7-425a-8213-b04234b23bd6)

## Expected behavior

Call Alter Ego and complete the quest

**Comment by claywar** [comment]
If you got std::nullopt return there, then it appears that an invalid entity tried to call it (which would log), or the player didn't have the record.  Can you provide additional information?

I just summoned Excenmille locally, and saw no error

**Comment by Mortalelite** [comment]
> If you got std::nullopt return there, then it appears that an invalid entity tried to call it (which would log), or the player didn't have the record. Can you provide additional information?

Sadly I don't have much info beyond that.  Might be able to get more testing with this. Only noticed when certain RoE was not able to complete. I did only noticed after getting Sandy Trust Permit and went to summon it to complete that quest.

Also get error when trying to complete Rank 1-1 for RoE
![Mission](https://github.com/LandSandBoat/server/assets/108362771/26235ea7-950e-4c9e-ba7c-74b29c4c40d2)

**Comment by claywar** [comment]
Working through it now

**Comment by claywar** [comment]
So something went wrong with manual triggering of records, should have a fix up shortly once I can figure out where things are exactly failing

**Comment by Mortalelite** [comment]
Also update with this when doing Vanquish Multiple Enemies. This was working last night and before did any server updates today

[08/24/23 20:38:32:256][map][error] roeutils::onRecordTrigger: ./scripts/globals/roe.lua:263: attempt to call method 'check' (a nil value)
stack traceback:
	./scripts/globals/roe.lua:263: in function <./scripts/globals/roe.lua:250> (call_onRecordTrigger:94)
[08/24/23 20:38:32:256][map][error] roeutils::onRecordTrigger: ./scripts/globals/roe.lua:263: attempt to call method 'check' (a nil value)
stack traceback:
	./scripts/globals/roe.lua:263: in function <./scripts/globals/roe.lua:250> (call_onRecordTrigger:94)

**Comment by Mortalelite** [comment]
> So something went wrong with manual triggering of records, should have a fix up shortly once I can figure out where things are exactly failing

Ok thanks

**Comment by claywar** [comment]
Something is failing to load on initial boot.  Saving (forcing a hot reload) of roe.lua fixes temporarily, but still working on a permanent fix

**Comment by Mortalelite** [comment]
Ok that is working that way of the temporarily fix

**Comment by claywar** [comment]
Should be fixed by #4355 

If there's any more difficulties please let me know!
