### ISSUE TITLE
future SDT work

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#436]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: N/A

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
While I now consider #428 complete and barring any mistake caught in review I plan no further change to it, I am making this issue to record future work that should eventually happen:

1. The newly made mob_resistances table likely has some redundant entries that could be pruned along with new entries that should be created. I just mass took what was in mob families so presently, the IDs just happen to align.
2. Some monsters have SDT or Resist modifier sin their scripts. This is partly because before now the sql end didn't function and these mobs would have been too easy, and partly because some mobs have abnormal resistances compared to other members of their species. These should be migrated to appropriate resist IDs and set in mob_pools
3.  **Hybrid Elementals are really fubar.** They were set the the wrong mob family and thus only got 1 half of their element values. Additionally, the correct family still had the wrong values as well. SO this got ported into the new resist table as-is. **For those how don't know, these elementals match teir-2 skillchain properties. there isn't Ice or Water - there is a single elemental that is both at the same time. **So there should be half as many of them and with very different resistances.**
4. Scripts that are setup to rotate mob weaknesses should stay - there are not currently bindings to get/set the resistance ID, and while I don't remember the details that was decided against for the time being.
5. SDT is a floating point used as a percentage in the sql where 1.00 equals 100% (normal, full) damage, and 0.50 would be "take half damage". But when you get the modifiers usage, the 8 elemental ones are 0-256 with 256 being "take no damage at all". This is drastically different from the slashing/piercing/blunt/h2h SDT modifiers and the general Damage Taken modifiers. 
6. While the retail game DOES use a 256 scale for _all_ of these things, a 1000 scale is easier to work with and results in fewer mistakes while still being able to reach the same percentages (its just a matter of precision) It is thus preferable for all of these to work the same way and have a 1000 scale. That change is however outside the scope of what I set out to do in `#428` : prevent further mixups between resistance and SDT while giving them their own table apart from mob_family_system
7. there was some debate as to if SDT actually does anything to resist tiers, I do not believe that is the case (seems to be just mixed up terminology on a wiki..) but if it were the case the system still supports it: by setting both modifiers on stuff. We still need 2 modifiers for math reasons regardless.

**Comment by TeoTwawki** [comment]
Updated OP with info about hybrid elementals

**Comment by ShiyoKozuki** [comment]
What does # 7 mean? SDT has an impact on resist tiers - 50% SDT means guaranteed half resist.

**Comment by TeoTwawki** [comment]
> What does # 7 mean? SDT has an impact on resist tiers - 50% SDT means guaranteed half resist.

50% SDT means talking half damage form that damage type. It's not really "a resist" - the poor phrasing on wiki has caused this view.

In our core, what SDT means is _specifically_ just "specific damage taken" as in what type and how much of that damage to mitigate, generally as a percentage. Some poor phrasing and misuse of a 3 letter abbreviation on a certain wiki has lead multiple individuals to confusing it with our resistance modifiers which control the (somewhat random) thresholds for resistance _procs_ where you can get 1/8th or 1/16th an effect duration, effect potency, random nuke resisted (non consistent so not _always_ half damage) and adding more of that mod controls both frequency and how far it is likely to "be resisted" not a % damage taken.

I've made sure we can support multiple views on what SDT "is" without having to do a prohibitive refactor to try and make all of these things stores as a single value and made sure it is well documented in comments where it lives so that future editors understand what the mods actually do when using them. The SDT _mod_ doesn't and shouldn't impact what we call resits here, we use the resist mod for that. If something always takes (and I mean ALWAYS) half damage, you want SDT. If its not always every single time, you want resistance modifier instead. 

If you truly believe both should be happening..you use both. I set it up to support that. Make sense?
