### ISSUE TITLE
🐛 Records of Eminence: Pre-Complete Events Throwing Error When Accepting

### ISSUE THREAD

**Issue by OptimusGrabs** [DerpyProjectGroup/topaz#4364]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu 22.04

## Branch affected by issue 

`base`

## Steps to reproduce

Attempt to accept a RoE objective when the requirements are already fulfilled. Error:

[08/26/23 14:46:17:528][map][error] roeutils::onRecordTrigger: ./scripts/globals/roe.lua:268: attempt to compare nil with number
stack traceback:
        ./scripts/globals/roe.lua:268: in function <./scripts/globals/roe.lua:260> (call_onRecordTrigger:94)
[08/26/23 14:46:19:606][map][error] roeutils::onRecordTrigger: ./scripts/globals/roe.lua:268: attempt to compare nil with number
stack traceback:
        ./scripts/globals/roe.lua:268: in function <./scripts/globals/roe.lua:260> (call_onRecordTrigger:94)
[08/26/23 14:46:22:739][map][error] roeutils::onRecordTrigger: ./scripts/globals/roe.lua:268: attempt to compare nil with number
stack traceback:

## Expected behavior

When accepting the RoE quest it should autocomplete when you have already completed the requirements.

In the roe.lua at the line mentioned it was getting a 'nil' value so I figured it was the line in "params = params or {}" so I added a 0 in the brackets to avoid it having a nil value and it seems to be working for me now, completing the quests that have already been fulfilled and not completing quests that still need reqs. Idk the relevance of doing this or what else it may break but at least for now but RoE pre-completed objectives are working for me. I'm not an expert so take my fix with a grain of salt. Snippet of function below.

```
function xi.roe.onRecordTrigger(player, recordID, params)
    params = params or {}   **<< I changed this to have a 0 in the brackets.**
    params.progress = params.progress or player:getEminenceProgress(recordID)

    local entry = xi.roe.records[recordID]
    local isClaiming = params.claim

    if entry and params.progress then
        local awaitingClaim = params.progress >= entry.goal
```

**Comment by claywar** [comment]
An error in logs is not steps to reproduce.  Can you please provide a procedure?

**Comment by claywar** [comment]
`Attempt to accept a RoE objective when the requirements are already fulfilled.`

Again, please provide a procedure.  While it may not be relevant, a simple step process for what objective you completed, and what you were trying to claim can be helpful when root causing and fixing.

**Comment by OptimusGrabs** [comment]
Apologies. The error was occurring with any uncompleted RoE objectives that I was attempting to accept to complete when the prereqs where already fulfilled.

1. Complete objectives for a RoE quest before accepting it in your Quests menu.
2. Enter Quests menu and open Objective List.
3. Select (for this example) Achievements > Job Levels 1 > Level 30 Warrior.
4. Set Objective? Yes.
5. No info in chat logs, error listed in report above appears server side.
6. Quest stays active in the Current RoE list, can't complete.

Tried the above for many of the quests that were pre-completed, same error for all.

**Comment by claywar** [comment]
All good! Just wanted to make sure I'm attacking from the same angle you're seeing

**Comment by claywar** [comment]
I'd suggest trying to pull latest if you haven't.  Just entered with a fresh character and !changejob war 30 along with your procedure above:
![image](https://github.com/LandSandBoat/server/assets/81713309/da5a89bc-614c-45b7-a490-fc183ee16d5c)

**Comment by OptimusGrabs** [comment]
Sorry, I'm not an expert, I merely dabble so I didn't know fully what you would need. I didn't know specifically what else the function was doing so I wasn't fully sure how the 'or' in the 'params = params or {}' line was going to affect anything else that the brackets may have been left empty for but I just figured I'd toss and integer in there to see if it would work and it seems to be working but I don't know what else that effects that may be fussy about that number there.

Also haha, I did just pull the roe.lua last night when I saw this fix: https://github.com/LandSandBoat/server/issues/4352

I'll grab it again and check it out. Thanks!

**Comment by claywar** [comment]
Thanks again for the report!  Any time there's an issue, we're more than happy to look at it.  There's been a lot of massive shuffling, but so long as there's a procedure to reproduce, and you're running latest, please always feel free to raise an issue!

**Comment by OptimusGrabs** [comment]
New pull of the roe.lua working. About 10-12 hours between my last pull and now haha. Thanks again!
