### ISSUE TITLE
Chocobo Digging doesn't work

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#441]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Chocobo digging consumes greens, performs animation, but never finds any items, and doesn't display any text regarding digging outcome. tried a stack of 99 in various zones.

**Comment by TeoTwawki** [comment]
working just fine for me

**Comment by Era-Lusiphur** [comment]
Is there a particular zone you're expecting results from that it isn't working in?

**Comment by CatsEyeXI** [comment]
tried in S. Gustaberg, Batalia Downs, Yuhutunga Jungle, Western Altepa and burned an entire stack of greens, i didn't come up with anything. to be clear i'm on the latest client and pull from a few days ago... could i be missing anything? rented chocobo vs. mount, etc?

**Comment by TeoTwawki** [comment]
https://www.twitch.tv/videos/1078575858

test with a clean clone instead of your live server? any customization, maybe something is different some seemingly insignificant modification triggered the problem after pulling new on top of it?

**Comment by TeoTwawki** [comment]
Note: the reason Lusi asked about which zone is if a zone has a mistake or missing data in its tables for what digging results are, it would fail.

**Comment by Xaver-DaRed** [comment]
Somewhat related; the EDITME in the last task is suposed to be edited with the name of the branch you are using or, at the very least, to point if the test is being performed on an edited copy.

If you are SURE you have a clean pull, even if from a few days ago, and it still doesnt work and the console log is not returning any error, please provide a copy of the digging script or a link to your repository and I can try to help you out.

**Comment by CatsEyeXI** [comment]
> Somewhat related; the EDITME in the last task is suposed to be edited with the name of the branch you are using or, at the very least, to point if the test is being performed on an edited copy.
> 
> If you are SURE you have a clean pull, even if from a few days ago, and it still doesnt work and the console log is not returning any error, please provide a copy of the digging script or a link to your repository and I can try to help you out.

my bad for missing the EDITME... i'm going to do a clean pull and see what i can do... will report back later. thanks

**Comment by CatsEyeXI** [comment]
[06/Jul] [16:03:05] [Error] luautils::onChocoboDig: ./scripts/missions/amk/helpers.lua:141: attempt to index local 'targetPos' (a nil value)
stack traceback:
        ./scripts/missions/amk/helpers.lua:141: in function 'chocoboDig'
        ./scripts/globals/chocobo_digging.lua:968: in function <./scripts/globals/chocobo_digging.lua:949>


this is on a clean pull, only copied my confs and  settings.lua over. using existing db

**Comment by Xaver-DaRed** [comment]
By existing database, do you mean an old one? Did you run the database tool?

**Comment by TeoTwawki** [comment]
oh HO HO HO!
I have an answer now that you've looked at the log and seen a real error! brb

**Comment by zach2good** [comment]
Sounds like you're part way through AMK and went digging in another zone? If so: looks like a legit bug

**Comment by TeoTwawki** [comment]
for the time being, you can disable this to get around the digging error:

```lua
        -- AMK07
        if ENABLE_AMK == 1 and xi.amk.helpers.chocoboDig(player, zoneId, text) then
            return
        end
```

that, as per your error in your log, is at line 949 of the digging global. and it called on another global itself erroring at line 141 coz its target didn't exist.

**Comment by CatsEyeXI** [comment]
confirmed setting AMK = 0 in settings.lua worked aorund the problem.

**Comment by TeoTwawki** [comment]
nobody noted my Shantotto impression. _sniffle_ thats ok tho, I halped.

**Comment by CatsEyeXI** [comment]
> nobody noted my Shantotto impression. _sniffle_ thats ok tho, I halped.

i see what you did tharr... thanks for the quick diagnosis

**Comment by claywar** [comment]
Not a lua table master, but I think Valk would potentially throw an error with the way its being referenced in that function:
```
    [1] = {
        { x = 141, z =  28 },
        { x = 392, z = -91 },
    },
```
Trying to directly access targetPos.x when there's multiple sub-tables defined
