### ISSUE TITLE
missions/windurst/5_1_The_Final_Seal, line 124 is referencing [xi.zone.CHATEAU_DORAGUILLE]... should be [xi.zone.HEAVENS_TOWER]

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#448]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch:  everything branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Discovered on Canaria, running everything branch.

Windy Mission 5-1.  After Lich fight and receiving the burnt seal, vestal chamber door was not ending mission for a player.  Looks like an edit was missed when mimicking the Sandy flow for the new interactive framework conversion:

missions/windurst/5_1_The_Final_Seal, line 124 is referencing [xi.zone.CHATEAU_DORAGUILLE]... should be [xi.zone.HEAVENS_TOWER] for the _6q2.lua onTrigger at the Vestal Chamber Door to end the mission.

```lua
   -- Mission has been accepted
    {
        check = function(player, currentMission, missionStatus, vars)
            return currentMission == mission.missionId
        end,

        [xi.zone.CHATEAU_DORAGUILLE] =
        {
            ['_6q2'] =
            {
                onTrigger = function(player, npc)
                    if player:getMissionStatus(mission.areaId) == 12 and player:hasKeyItem(xi.ki.BURNT_SEAL) then
                        return mission:progressEvent(192)
                    end
                end,
            },

            onEventFinish =
            {
                [192] = function(player, csid, option, npc)
                    if mission:complete(player) then
                        player:delKeyItem(xi.ki.BURNT_SEAL)
                    end
                end,
            },
        },
```

**Comment by Snugglesffxi** [comment]
gotchu fam :)
