### ISSUE TITLE
🐛 Docs need minor updating for multi-process

### ISSUE THREAD

**Issue by clanofartisans** [DerpyProjectGroup/topaz#4497]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10 and Ubuntu 22.04

## Branch affected by issue 

`base` on Ubuntu, HorizonXI on Windows

## Steps to reproduce / Expected behavior

The directions for launching map instances for multi-process servers [found here](https://github.com/LandSandBoat/server/wiki/Miscellaneous-Server#how-do-i-set-it-up) show running the map executable without the `--ip` command line argument but it seems to actually be required. Running without it will result in querying the database for zones with IP `0.0.0.0`, which causes them to all return true, meaning the map process will load all zones. Using the IP argument with a correct IP ensures that the correct zones get queried and returned. I assume this is just a tiny documentation issue and not a bug but Zach asked me to open the issue here :)

**Comment by clanofartisans** [comment]
Pinging @zach2good simply because he's the one who requested the GitHub Issue.

**Comment by zach2good** [comment]
This is the code we use inside dbtool, which works correctly:
```py
def configure_and_launch_multi_process_by_zonetype():
    db_query(
        f"""
        UPDATE xidb.zone_settings SET zoneport = 54230 WHERE zonetype = 0;
        UPDATE xidb.zone_settings SET zoneport = 54231 WHERE zonetype = 1;
        UPDATE xidb.zone_settings SET zoneport = 54232 WHERE zonetype = 2;
        UPDATE xidb.zone_settings SET zoneport = 54233 WHERE zonetype = 3;
        UPDATE xidb.zone_settings SET zoneport = 54234 WHERE zonetype = 4;
        UPDATE xidb.zone_settings SET zoneport = 54235 WHERE zonetype = 5;
        UPDATE xidb.zone_settings SET zoneport = 54236 WHERE zonetype = 6;
        """
    )

    result = db_query(
        f"""
        SELECT DISTINCT zoneport from zone_settings ORDER BY zoneport ASC;
        """
    )

    ports = result.stdout.split("\n")[1:-1]

    executable = from_server_path(f"xi_map{exe}")

    # fmt: off
    for port in ports:
        print(f"Launching {executable} --log log/map-server-{port}.log --ip 127.0.0.1 --port {port}")
        subprocess.Popen(
            [executable, "--log", f"log/map-server-{port}.log", "--ip", "127.0.0.1", "--port", port],
            shell=True,
            creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP,
            cwd=server_dir_path,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    # fmt: on
```

**Comment by clanofartisans** [comment]
> This is the code we use inside dbtool, which works correctly:
> 
> ```python
> def configure_and_launch_multi_process_by_zonetype():
>     db_query(
>         f"""
>         UPDATE xidb.zone_settings SET zoneport = 54230 WHERE zonetype = 0;
>         UPDATE xidb.zone_settings SET zoneport = 54231 WHERE zonetype = 1;
>         UPDATE xidb.zone_settings SET zoneport = 54232 WHERE zonetype = 2;
>         UPDATE xidb.zone_settings SET zoneport = 54233 WHERE zonetype = 3;
>         UPDATE xidb.zone_settings SET zoneport = 54234 WHERE zonetype = 4;
>         UPDATE xidb.zone_settings SET zoneport = 54235 WHERE zonetype = 5;
>         UPDATE xidb.zone_settings SET zoneport = 54236 WHERE zonetype = 6;
>         """
>     )
> 
>     result = db_query(
>         f"""
>         SELECT DISTINCT zoneport from zone_settings ORDER BY zoneport ASC;
>         """
>     )
> 
>     ports = result.stdout.split("\n")[1:-1]
> 
>     executable = from_server_path(f"xi_map{exe}")
> 
>     # fmt: off
>     for port in ports:
>         print(f"Launching {executable} --log log/map-server-{port}.log --ip 127.0.0.1 --port {port}")
>         subprocess.Popen(
>             [executable, "--log", f"log/map-server-{port}.log", "--ip", "127.0.0.1", "--port", port],
>             shell=True,
>             creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP,
>             cwd=server_dir_path,
>             stdout=subprocess.DEVNULL,
>             stderr=subprocess.DEVNULL,
>         )
>     # fmt: on
> ```

Yep, looks good. The guide on the page I linked just needs updated to include the ip argument like you're doing in dbtool/CI.

**Comment by zach2good** [comment]
Fixing: https://github.com/LandSandBoat/lsb-wiki/pull/85
