### ISSUE TITLE
🐛 xi_connect SSL Keygen build error on Linux

### ISSUE THREAD

**Issue by F0G1V3N** [DerpyProjectGroup/topaz#4499]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Debian 11 Linux 5.10.0-25-amd64 on x86_64

## Branch affected by issue

`base`

## Steps to reproduce

I'm guessing this is just a configuration issue but I followed the Quick Start Guide for Linux. After running:

make -j $(nproc) -k 2>&1 | tee build.log

Build succeeds for everything but xi_connect. Build log:

[  1%] Built target Detour
[  1%] Built target fast_obj_lib
[  3%] Built target Recast
[  5%] Built target spdlog
[  6%] Built target DetourTileCache
[  8%] Built target DetourCrowd
[ 14%] Built target efsw
[ 15%] Built target DebugUtils
[ 22%] Built target xi_search
[ 29%] Built target xi_world
[ 29%] Linking CXX executable ../../../xi_connect
[ 94%] Built target xi_map
/usr/bin/ld: /tmp/xi_connect.KqQfmK.ltrans8.ltrans.o: in function `certificateHelpers::generateSelfSignedCert()':
/root/landsandboat/server/src/login/cert_helpers.h:74: undefined reference to `EVP_PKEY_Q_keygen'
/usr/bin/ld: /tmp/xi_connect.KqQfmK.ltrans17.ltrans.o: in function `asio::ssl::context::use_rsa_private_key_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, asio::ssl::context_base::file_format) [clone .constprop.0]':
/root/landsandboat/server/build/_deps/asio-src/asio/include/asio/ssl/impl/context.ipp:1073: undefined reference to `EVP_PKEY_is_a'
collect2: error: ld returned 1 exit status
make[2]: *** [src/login/CMakeFiles/xi_connect.dir/build.make:494: ../xi_connect] Error 1
make[2]: Target 'src/login/CMakeFiles/xi_connect.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:992: src/login/CMakeFiles/xi_connect.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:171: all] Error 2
make: Target 'default_target' not remade because of errors.

Any help is appreciated. Thank you in advance!

**Comment by zach2good** [comment]
At a glance, `EVP_PKEY_Q_keygen` and `EVP_PKEY_is_a` are missing. From the docs, these look to be a part of SSL 3. We might need `#include <openssl/evp.h>` somewhere, or you might need to get the latest openssl from your package manager - I dunno which.

EDIT: Most likely you have an older openssl. Otherwise it would be a different error than `undefined reference`

https://manpages.debian.org/experimental/libssl-doc/EVP_PKEY_is_a.3ssl.en.html

**Comment by zach2good** [comment]
I don't know what the ecosystem is like for Debian, but you need to find a way to install `libssl3`, or upgrade to a version of debian where thats available through the package manager (or is the default)

**Comment by F0G1V3N** [comment]
Thanks for the super fast response. I'm working on getting OpenSSL3 installed on my system. Unfortunately, it isn't available when I do an apt search. I did find some documentation on getting the source and compiling it locally. I'll keep you updated.

**Comment by cocosolos** [comment]
Debian 11 stops getting official security updates in July, it might be worth upgrading so you'll have the latest (by Debian standards) packages. [See here if you need help with that.](https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.html)

**Comment by F0G1V3N** [comment]
First off, thank you both for your suggestions. I ended up scrapping my first attempt with Debian 11 because I broke many things in an attempt to get OpenSSL3 to work. Keep in mind, I'm am newbie to linux in general.

I made a fresh install of Debian (Bookworm) 12.1 (which comes with OpenSSL 3.0.9) and followed the Quickstart Guide. However, there were a couple of gotchas:

1. I did have to add the Debian Bullseye main repository to get g++-10 using apt.

2. I also had to run the 'pip3 install -r server/tools/requirements.txt' command in a python3 virtual environment. Instructions can be found here: https://docs.python.org/3/library/venv.html.

After those changes, everything compiled properly. Thank you again!

**Comment by cocosolos** [comment]
> 1. I did have to add the Debian Bullseye main repository to get g++-10 using apt.

I think g++-10 was just a minimum requirement, that should probably just be updated to just `g++` at this point.

> 2. I also had to run the 'pip3 install -r server/tools/requirements.txt' command in a python3 virtual environment. Instructions can be found here: https://docs.python.org/3/library/venv.html.

This is generally a good idea anyway, especially on Debian since global Python modules are installed from Debian repo and are likely out of date. Another thing the guide could probably be updated on.

Thanks for the feedback and glad you got it working!

**Comment by zach2good** [comment]
Yeah, I believe we had an issue with G++8 or 9, which is long gone by this point, so we can probably just specify g++.

I agree with using py venv in general as best practice, but enough people stumble on even installing python correctly - so another line (unless it can be rolled into a big ol' oneliner) on the initial setup wouldnt be ideal.
