### ISSUE TITLE
🐛 [Battlefields] BSNM40 Royal Jelly - Double Queen Jelly

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#4510]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

- The mini jellies were standing and working correctly more or less around the arena.
- There was also a Queen Jelly in the middle of the arena and attacks you when aggroing the minis.
- I fought the Queen while the minis went to the middle and they waited until I killed the Queen.
- Afterwards they did their thing and transformed into another Queen Jelly and had to kill her too.

![Skerx_2023 09 16_020432](https://github.com/LandSandBoat/server/assets/33092280/b8d05956-a53e-4bad-b80f-df50d70915ed)
![Skerx_2023 09 16_020554](https://github.com/LandSandBoat/server/assets/33092280/c7be88d4-b88f-4aae-9e11-e35abffc6825)
![Skerx_2023 09 16_020559](https://github.com/LandSandBoat/server/assets/33092280/67208e43-36f0-4456-9b89-239d81fdf365)
![Skerx_2023 09 16_020651](https://github.com/LandSandBoat/server/assets/33092280/ef2e12a6-c687-4016-ada3-4199b5e59034)
![Skerx_2023 09 16_020737](https://github.com/LandSandBoat/server/assets/33092280/f66ae786-9fb2-4262-afaf-243dcdc2ebbc)

I suppose it is the same bug which causes pets of other BCNMs to spawn in your fight like in Maat? Idk.

Server CatsEye

## Expected behavior

There shouldn't be a Queen Jelly at the beginning of the battle.

**Comment by zach2good** [comment]
BSNM40 Royal Jelly is disabled on `base` because it's incomplete.

https://github.com/LandSandBoat/server/blob/base/scripts/globals/bcnm.lua#L278

You'll need to talk to whoever wrote the implementation that's being used on CatsEye.

**Comment by CatsEyeXI** [comment]
appreciating you doing your due diligence in reporting this @Skerxan but many of our BCNM's are custom and as such not contributed up to LSB. It's always worth asking on stuff like this before opening an issue here... I certainly appreciate your good faith in reporting the issue though, I'll look into it.

**Comment by Skerxan** [comment]
My bad then. Didn't expect BSNMs to be custom and thought they were only enabled. Then this can be closed if custom.
