### ISSUE TITLE
🐛 [XIMAP] logging.LOG_WARNING failed to lookup key

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#4536]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

## Branch affected by issue 

`base`

## Steps to reproduce

run ximap (with default logging settings in default folder)

```
[2023-09-22 01:36:00.750] [error] [error] [settings.h:157] Settings: Failed to look up key: logging.LOG_WARNING, using default value: "false"
[2023-09-22 01:36:00.750] [error] [error] [settings.h:157] Settings: Failed to look up key: logging.LOG_WARNING, using default value: "false"
```

## Expected behavior

no errors from reading logging file. It doesnt complain about any other key inside the logging file, only for the LOG_WARNING one.

![image](https://github.com/LandSandBoat/server/assets/26943220/bf5ef280-c6bd-4899-8906-7bbd87fada37)

Recreating this issue as I cant reopen the original issue https://github.com/LandSandBoat/server/issues/3511

default logging file placed in correct settings folder

**Comment by Cuponoodle101** [comment]
I was getting this and resolved it on my install.

I put this at the bottom of my logging.lua just before the }.

    SQL_SLOW_QUERY_LOG_ENABLE   = true, -- true/false. If true, slow SQL queries will generate warning or error logs if they exceed the durations listed below.
    SQL_SLOW_QUERY_WARNING_TIME = 100,  -- uint (milliseconds).
    SQL_SLOW_QUERY_ERROR_TIME   = 250,  -- uint (milliseconds).

**Comment by kaincenteno** [comment]
> I was getting this and resolved it on my install.
> 
> I put this at the bottom of my logging.lua just before the }.
> 
> ```
> SQL_SLOW_QUERY_LOG_ENABLE   = true, -- true/false. If true, slow SQL queries will generate warning or error logs if they exceed the durations listed below.
> SQL_SLOW_QUERY_WARNING_TIME = 100,  -- uint (milliseconds).
> SQL_SLOW_QUERY_ERROR_TIME   = 250,  -- uint (milliseconds).
> ```

oooo i'll try that on the next server rebuild :D

**Comment by kaincenteno** [comment]
> I was getting this and resolved it on my install.
> 
> I put this at the bottom of my logging.lua just before the }.
> 
> ```
> SQL_SLOW_QUERY_LOG_ENABLE   = true, -- true/false. If true, slow SQL queries will generate warning or error logs if they exceed the durations listed below.
> SQL_SLOW_QUERY_WARNING_TIME = 100,  -- uint (milliseconds).
> SQL_SLOW_QUERY_ERROR_TIME   = 250,  -- uint (milliseconds).
> ```

looked at the logging.lua, those settings are already at the bottom of it prior to the end curly brace, same issue.

```
[2023-10-05 23:54:42.167] [error] [error] [settings.h:157] Settings: Failed to look up key: logging.LOG_WARNING, using default value: "false"
[2023-10-05 23:54:42.167] [error] [error] [settings.h:157] Settings: Failed to look up key: logging.LOG_WARNING, using default value: "false"
```

**Comment by Gradius2** [comment]
Why did you closed?

It was really fixed or not?

I'm getting this, fresh build on vm with Debian 12 fully updated.
