### ISSUE TITLE
Convert addGil + messageSpecial combinations to npcUtil.giveCurrency()

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#454]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

There's a lot of places in scripts where this combination is used, and also adds `GIL_RATE` calculations.  This can all be simplified by using `npcUtil.giveCurrency()`, which will send the appropriate message and apply rate changes.

Raising this for tracking as a TODO for future self.

**Comment by Era-Lusiphur** [comment]
Great idea. Small request if possible. Add an argument to disable multiplying the reward by GIL_RATE for specific uses of the function if awarding gil.
