### ISSUE TITLE
Some bard songs don't have scripts

### ISSUE THREAD

**Issue by Snugglesffxi** [DerpyProjectGroup/topaz#456]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

From the spell data table, the following **Bar Status** songs don't have scripts and therefore can't be cast:

```lua
    FOWL_AUBADE           =  405, -- resist sleep
    HERB_PASTORAL         =  406, -- resist poison
 -- CHOCOBO_HUM           =  407, -- not in game (mob spell?)
    SHINING_FANTASIA      =  408, -- resist blind
    SCOPS_OPERETTA        =  409, -- resist silence
    PUPPETS_OPERETTA      =  410, -- resist silence (2?)
 -- JESTERS_OPERETTA      =  411, -- not in game
    GOLD_CAPRICCIO        =  412, -- resist petrify
 -- DEVOTEE_SERENADE      =  413, -- not in game
    WARDING_ROUND         =  414, -- resist curse
    GOBLIN_GAVOTTE        =  415  -- resist bind

```
We have all the bones (I'm pretty sure) in place to make the scripts and I have no problem making scripts for them but I've run into an issue where there just isn't any data or testing for accurate values on these songs. (there isn't any for their white magic counterparts either really).

Starting to see why nobody has really taken up the mantle to do them. What do you guys think of taking the math/power we use for carols and applying it to these? 

```lua
spell_object.onSpellCast = function(caster, target, spell)
    local sLvl = caster:getSkillLevel(xi.skill.SINGING) -- Gets skill level of Singing
    local iLvl = caster:getWeaponSkillLevel(xi.slot.RANGED)

    local power = 20

    if (sLvl+iLvl > 200) then
        power = power + math.floor((sLvl+iLvl-200) / 10)
    end

    if (power >= 80) then
        power = 80
    end
```

Otherwise we can probably make up our own formula maybe based on the [Barstatus.lua](https://github.com/LandSandBoat/server/blob/094ec9f022916bc86b8d0efee166b626ec560c2c/scripts/globals/spells/barstatus.lua)

But this leaves the question of what should we do with Puppet's Operetta as it's a high level version of Scop's.

Here's a mock-up script I made using the math/power we use for carols -- but I am absolutely open to not using this formula if we have a better plan:

```lua
-----------------------------------
-- Song: Goblin Gavotte
-- Enhances resistance against bind for party members within the area of effect.
-----------------------------------
require("scripts/globals/status")
require("scripts/globals/magic")
require("scripts/globals/msg")
-----------------------------------
local spell_object = {}

spell_object.onMagicCastingCheck = function(caster, target, spell)
    return 0
end

spell_object.onSpellCast = function(caster, target, spell)
    local sLvl = caster:getSkillLevel(xi.skill.SINGING) -- Gets skill level of Singing
    local iLvl = caster:getWeaponSkillLevel(xi.slot.RANGED)

    local power = 20

    if (sLvl+iLvl > 200) then
        power = power + math.floor((sLvl+iLvl-200) / 10)
    end

    if (power >= 80) then
        power = 80
    end

    local iBoost = caster:getMod(xi.mod.ALL_SONGS_EFFECT) 
    power = power + iBoost*8

    if (caster:hasStatusEffect(xi.effect.SOUL_VOICE)) then
        power = power * 2
    elseif (caster:hasStatusEffect(xi.effect.MARCATO)) then
        power = power * 1.5
    end
    caster:delStatusEffect(xi.effect.MARCATO)

    local duration = 120
    duration = duration * ((iBoost * 0.1) + (caster:getMod(xi.mod.SONG_DURATION_BONUS)/100) + 1)

    if (caster:hasStatusEffect(xi.effect.TROUBADOUR)) then
        duration = duration * 2
    end

    if not (target:addBardSong(caster, xi.effect.GAVOTTE, power, 0, duration, caster:getID(), 0, 1)) then
        spell:setMsg(xi.msg.basic.MAGIC_NO_EFFECT)
    end

    return xi.effect.GAVOTTE
end

return spell_object
```

Finally -- While making the mock-up I had a burning question... Are we sure bard songs are using both SINGING *and* WIND/STRING instrument skills? (maybe another issue entirely, but I thought I'd ask.)

PS I absolutely did not get annoyed at the skillup script wiggin' out when it tried to play these songs and then proceed to go down a very deep rabbit hole. 🙄

**Comment by Xaver-DaRed** [comment]
As you've noticed, most bards songs follow the same pattern. All enhancing songs, pattern1 and all enfeeble songs, pattern 2.

There is a plan slowly in mottion to move all that logic out of the individual scripts and instead use a global file, to avoidcode repetition and, at the same time, make the code easier to read.

But yeah, I can confirm there are missing scripts.

**Comment by Xaver-DaRed** [comment]
As for your second question

>     local sLvl = caster:getSkillLevel(xi.skill.SINGING) -- Gets skill level of Singing
>     local iLvl = caster:getWeaponSkillLevel(xi.slot.RANGED)
> 
>     local power = 20
> 
>     if (sLvl+iLvl > 200) then

As you can see in the last line, it is adding up both singing skill and the skill used in ranged slot, AKA either string or wind, depending on instrument type equiped.

**Comment by Snugglesffxi** [comment]
oh i thought that was just taking the mods on the horn/harp! perfect. 

What do you think about the mock script? should I just put them in under that logic, until we have the future globals in place? (I can't imagine anyone actually uses these songs)

**Comment by Xaver-DaRed** [comment]
The script itself is fine. I do not know if we atually have the GAVOTE effect or not, but the script should work.

**Comment by Snugglesffxi** [comment]
>I do not know if we atually have the GAVOTE effect or not, but the script should work.

Yeah,i checked beforehand, unless i'm mistaken we have all the proper bones in place for each effect.
