### ISSUE TITLE
🐛 Ferry Transport Broken

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4563]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows10

## Branch affected by issue 
`base`

## Steps to reproduce
Purchase Manaclipper ticket to any destination, you will zone into the manaclipper, but at the end of the transport you will return to the docks where you boarded.

![image](https://github.com/LandSandBoat/server/assets/65316697/d76eff0a-1b70-4004-9f03-2e9f7bbafac3)
![image](https://github.com/LandSandBoat/server/assets/65316697/a6beb449-1fa5-4309-a49b-f793555ad584)
![image](https://github.com/LandSandBoat/server/assets/65316697/dbe1b2bf-e9cc-4217-ac45-fac94bc08e59)

## Expected behavior

Ferry should transport you to desired destination.

**Comment by CatsEyeXI** [comment]
Confirmed happens on a fresh LSB build with no modules loaded
![image](https://github.com/LandSandBoat/server/assets/65316697/82b05fa9-35ae-4da1-accc-e9499b94e95b)

**Comment by claywar** [comment]
The only "destination" for Manaclipper is Purgonorgo.  Reef and Dhalmel Rock are tours that do indeed return you to Sunset docks.
