### ISSUE TITLE
Dynamis mobs will turn to face you when staggered

### ISSUE THREAD

**Issue by Era-Lusiphur** [DerpyProjectGroup/topaz#459]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Any

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Dynamis mobs should remain frozen in place after being staggered until the effect wears off.

**Comment by TeoTwawki** [comment]
most types of staggers/procs should be using the same state that terror does in order to be retail accurate. just in general. I believe that **not** happening is why this issue exists.

**Comment by Era-Lusiphur** [comment]
Quick glance at Dynamis global shows Terror being added for 30 seconds. Or at least it looks like there's an attempt to. Do we have a way to impose NO_TURN or some other fix for the same duration?

https://github.com/LandSandBoat/server/blob/63b6e1b2f225d4211847e3b6150f27502052bc8a/scripts/globals/dynamis.lua#L736

**Comment by TeoTwawki** [comment]
that is such facepalm. it should NOT be the actual status effect to do it

**Comment by ShiyoKozuki** [comment]
Slept mobs do too
