### ISSUE TITLE
🐛 Character variables not resetting when timestamp has passed

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4647]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 1

## Branch affected by issue 

`base`

## Steps to reproduce

1. Delete CharVar CONQUEST_RING_RECHARGE
2. Trade an empress band to conquest NPC, he should recharge it.
3. Manually update the expiry field on CONQUEST_RING_RECHARGE to 60 seconds from now
4. Speak to NPC after one minute and you'll still be unable to recharge your ring

## Expected behavior

Variable should expire once current time has passed the timestamp.

Possible result of #4570 ?

**Comment by zach2good** [comment]
When you manually update the timestamp, are you doing that in Lua or in SQL?

**Comment by zach2good** [comment]
I don't remember the guts of the new expiry system, but I imagine were periodically checking our caches with a system task, and checking on lookup - so if the changes happen through sql, there's no way for the cache to see them until a character zones.

If the changes happen through Lua, then there's an issue certainly

**Comment by cocosolos** [comment]
In regards to conquest:

I think there's an edge case in `NextJstWeek`. Since the day of the week as returned by all the time functions starts with Sunday at 0, and conquest reset is Monday JP time (Sunday morning for US).
https://github.com/LandSandBoat/server/blob/2b45287b702fcf2118d59588216a73267a3118c5/src/map/lua/luautils.cpp#L1438-L1446

`jstWeekday` is going to be 0-6, so `NextJstWeek` is always going to return at least 24hrs away.
Compare to RoE reset: https://github.com/LandSandBoat/server/blob/2b45287b702fcf2118d59588216a73267a3118c5/src/map/roe.cpp#L465-L468

Which is similar to how conquest tally used to be calculated before it was changed in #4570 :
```lua
function getConquestTally()
    local lastTally = (JstWeekday() + 6) % 7
    local daysToTally = 6 - lastTally
    return getMidnight() + (daysToTally * (60 * 60 * 24))
end
```
I think the `NextJstWeek` may be a little ambiguous now that it's not explicitly tied to conquest, since it's not really the `JstWeek` you would expect everywhere else because of the offset start. Maybe `NextWeeklyReset` or something, since designating that it's JST isn't really important.

**Comment by CatsEyeXI** [comment]
I made a small gm command to update the timestamp.

```lua
commandObj.onTrigger = function(player)
    local currentTs = player:getCharVar('CONQUEST_RING_RECHARGE')
    local newTs     = os.time() + 60

    player:PrintToPlayer(string.format('Original Timestamp: %i -- New Timestamp: %i.', currentTs, newTs), xi.msg.channel.SYSTEM_3)
    player:setCharVar('CONQUEST_RING_RECHARGE', newTs)
end
```

![image](https://github.com/LandSandBoat/server/assets/65316697/2dc30bb5-31f6-405c-9991-2245efa4a33a)

I'm still unable to recharge my ring once the stored time elapses.
I'm using https://www.epochconverter.com/ to convert the Unix time.

**Comment by claywar** [comment]
`player:setCharVar('CONQUEST_RING_RECHARGE', newTs)`
`void CLuaBaseEntity::setCharVar(std::string const& varName, int32 value, sol::object const& expiry)`
`void CLuaBaseEntity::setCharVarExpiration(std::string const& varName, uint32 expiry)`

If you're trying to set an expiration, you're using the wrong function (or not enough parameters).

**Comment by CatsEyeXI** [comment]
> `player:setCharVar('CONQUEST_RING_RECHARGE', newTs)` `void CLuaBaseEntity::setCharVar(std::string const& varName, int32 value, sol::object const& expiry)` `void CLuaBaseEntity::setCharVarExpiration(std::string const& varName, uint32 expiry)`
> 
> If you're trying to set an expiration, you're using the wrong function (or not enough parameters).


I updated the call to include the correct parameters and then I was able to recharge, however upon running the command again, getting the charvar returned 1?

`player:setCharVar('CONQUEST_RING_RECHARGE', 1, newTs)`

![image](https://github.com/LandSandBoat/server/assets/65316697/d675f185-eef9-45de-9973-4de10b759009)

**Comment by claywar** [comment]
I don't believe you understand.  Timestamp is _not_ the value of the charvar.  So getting it will either return the value you set (1) or 0 if it has expired (since it is removed)

**Comment by CatsEyeXI** [comment]
Ohh, i see... Is this an exclusive problem to us then?

**Comment by claywar** [comment]
For your GM command, yes.  The correct method to reset the time would be setting the value to 0.
`player:setCharVar('CONQUEST_RING_RECHARGE', 0)`

If you needed to be more granular and modify an existing one, you would use `setCharVarExpiration('CONQUEST_RING_RECHARGE',newTs)`
