### ISSUE TITLE
🔨 Add port number to dump tombstones

### ISSUE THREAD

**Issue by clanofartisans** [DerpyProjectGroup/topaz#4648]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

Would be great to have this information in the log file to see quickly where the issue was without having to go spelunking into the actual dump. Mentioned it on Discord and @zach2good recommended it open an issue for it.

Thanks!

**Comment by zach2good** [comment]
Related, but a mighty PITA last time I tried to implement: https://github.com/LandSandBoat/server/issues/1973

**Comment by zach2good** [comment]
Closed with https://github.com/LandSandBoat/server/pull/4716
