### ISSUE TITLE
Healing Ruby no longer triggers animation or heal effect for Carbuncle

### ISSUE THREAD

**Issue by HopefullyHeroic** [DerpyProjectGroup/topaz#4654]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

Get Carbuncle, summon carbuncle, have HP missing, try to use Healing Ruby. It uses the MP for skill activation but doesn't activate the heal or animation

## Expected behavior

Should activate heal and animation as well as take MP.

**Comment by UmeboshiXI** [comment]
Can confirm. Attempted to use Healing Ruby on a fresh LSB, Carbuncle does nothing but the ability takes MP and puts BP Ward on cooldown. No Lua errors. Shining Ruby, Glittering Ruby and Healing Ruby II seem to work as intended.

**Comment by RAIST5150** [comment]
Confirmed this oddity on xiweb... Ubuntu 22.04 server, windows 10 (22H2) client (ver 30231003_0).  Think Kain rebuilt server Sunday.

Ability ID 512 and I think animation 6 in abilities.sql.  

IDK if either of those could be wrong and throwing something off... get a bit crosseyed looking in that file.  Looked like valid target (3) is correct... assuming it is following same scheme as spells with the same limitations (like phalanx ii).

**Comment by HopefullyHeroic** [comment]
> Confirmed this oddity on xiweb... Ubuntu 22.04 server, windows 10 (22H2) client (ver 30231003_0). Think Kain rebuilt server Sunday.
> 
> Ability ID 512 and I think animation 6 in abilities.sql.
> 
> IDK if either of those could be wrong and throwing something off... get a bit crosseyed looking in that file. Looked like valid target (3) is correct... assuming it is following same scheme as spells with the same limitations (like phalanx ii).

Yeah I've looked for any inconsistency I can find in each lua that pertains to the ability, summoners, avatars, etc. I've also scoured the database and cannot for the life of me figure out why this ability isn't working. 
I do think that part of the healing formula is incorrect, in that the lua asks for targets level when dealing with healing calculations when I think it's supposed to be pet's level, as Healing Ruby II uses pets level. this change obviously wasn't enough to get it to work though, but should be factored in as well should anyone find the answer.

**Comment by RAIST5150** [comment]
Leaning towards abilityID (or something similar that could shift) being a potential candidate, at least in part.  They have been known to change before (was 496 in legacy DSP code...HR2 was 501).

**Comment by HopefullyHeroic** [comment]
~Further testing reveals that after you hit level 30, Healing Ruby starts working. Perhaps this is relating to it's split, level-dependent formula?~
Upon further further testing, it was not in fact my level that changed it, it was whether or not I was in a party. 
Healing Ruby doesn't work when not in a party. When in a party with trusts(and I assume other characters) it functions as normal.

**Comment by WinterSolstice8** [comment]
Probably related to #4683

**Comment by HopefullyHeroic** [comment]
> Probably related to #4683

Ayyyyye probably? That'll be dope to have a fix for it. It's been bugging me for days.

**Comment by HopefullyHeroic** [comment]
https://github.com/LandSandBoat/server/pull/4683 did in fact fix this issue, thank you!
