### ISSUE TITLE
🐛 Off hand weapon or strap is unequipped on zone

### ISSUE THREAD

**Issue by Alsbuser** [DerpyProjectGroup/topaz#4675]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Mac

## Branch affected by issue 

`base`

## Steps to reproduce

Equip a weapon or strap in the sub weapon slot. Zone. You should now have that strap or weapon unequipped (see below additional info). It may not happen if the unordered map provides the right order back on zone, so you may have to try different combinations. Lower level gear, or perhaps container slot may play a factor in how the hash is created in the unordered map

## Expected behavior

Equipment should stay as equipped in other zones when zoning.

Additional info: The issue seems to be with the LoadEquip method in charutils. Specifically the logical strategy to keep the sql return inside an unordered map called "equipSlotData". Since the unordered map isn't going to reliably output the main weapon first in the loop, you end up in situations where sub weapon slots that can't be equipped without a main weapon (anything not a shield I believe) never get re-equipped on character load.

**Comment by RAIST5150** [comment]
Would note there is a discussion thread where we found a way to duplicate it on demand... have not had a chance to test different gear sets yet but it was easy to force it in our PJ's

#4611

**Comment by Xaver-DaRed** [comment]
This was fixed in PR 6044
