### ISSUE TITLE
Interaction: Zilart mission 17 - Awakening

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#470]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base, Everything.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The way the mission is coded leads to the CSs to be able to be viewed more than once.
The CSs are triggered automaticaly on region enter.

This is the check:

>         check = function(player, currentMission, missionStatus, vars)
>             return currentMission == mission.missionId and missionStatus < 3
>         end,

AKA, so long as the mission variable is lower than 3.

This are the onEventFinish:

> player:setMissionStatus(mission.areaId, player:getMissionStatus(mission.areaId) + 2)

> player:setMissionStatus(mission.areaId, player:getMissionStatus(mission.areaId) + 1)

Both just add +1 or +2 to the variable, with no further checks. This means that the first CS you watch can be triggered again by simply re-entering the region.

**Comment by claywar** [comment]
Adding utils.mask.hasBit checks for missionStatus for these two events

**Comment by claywar** [comment]
Fixed in #472
