### ISSUE TITLE
🐛 I'm stuck in Monstrosity

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4714]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Use Relinquish, get sent to zone 0
!monstrosity has the same effect

## Expected behavior

I'm assuming I should leave monstrosity...

**Comment by zach2good** [comment]
Change your main job to something other than JOB_MON, delete your char_monstrosity row from the db, and then you'll be able to zone back to safety

Safeguards added in https://github.com/LandSandBoat/server/pull/4723
