### ISSUE TITLE
🐛 Digits from Examining Locked Treasure Casket are Truncated

### ISSUE THREAD

**Issue by misterperson** [DerpyProjectGroup/topaz#4742]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated

## OS / platform the server is running (if known)

Ubuntu 22.04

## Branch affected by issue 

'base'

## Steps to reproduce

1. Examine a locked treasure coffer.
1. Examination produces a numeric value constraint on the lock combination (e.g. greater than 40, second digit is 2, etc).

## Expected behavior

The digit produced by examination is not truncated.

## Client Message Log
```
Obtain this item?
Tallmountain defeats the Balloon.
The chest is locked.
You have a hunch that the first digit is .
The chest is locked.
You have a hunch that the second digit is even.
The chest is locked.
You have a hunch that the combination is greater than 4.
The chest is locked.
You have a hunch that the combination is greater than 4.
```

**Comment by TeoTwawki** [comment]
1. what zone? (if it happens in multiple, still need one of them)
2. what does the game say when you use `/ver` ?
3. does server up to day with most current LSB ?

**Comment by UmeboshiXI** [comment]
I have had someone report this on my server as well. Have not had time to look into it yet.

Server Version: October 2023 (Client Version: 30231003_0)

Zone: East Ronfaure 

![image](https://github.com/LandSandBoat/server/assets/42159425/9b3c8e3b-0d28-44a3-9f22-667fd2b63657)
![image](https://github.com/LandSandBoat/server/assets/42159425/fd5781ed-7a79-44c7-a8a4-9434aa5141ed)

**Comment by misterperson** [comment]
1. Tahrongi Canyon, Inner Horutoto Ruins, East Sarutabaruta
2. 30231102_2
3. To my knowledge the server (xiweb) keeps up-to-date with LSB doing weekly rebuilds.

**Comment by misterperson** [comment]
Here's the code snippet where casket hint logic seems to run through.
https://github.com/LandSandBoat/server/blob/6376a3c29b7d4ab3a6340284d1b5e2318a19f4cf/scripts/globals/caskets.lua#L796-L949

**Comment by misterperson** [comment]
The logic seems fine, but I couldn't follow the call hierarchy of player:messageSpecial which could be formatting numbers incorrectly.

**Comment by Mortalelite** [comment]
I tested few zones myself, I was not getting same results. If it helps I am using Windows for a Local.

Ver `30231102_2`
Build `6376a3c`

My test server just little behind on few commits

Yhoator_Jungle
![Yhoator_Jungle](https://github.com/LandSandBoat/server/assets/108362771/a72aa9bb-ed68-4a1f-a325-959ea4ab36ff)

East_Sarutabaruta
![East_Sarutabaruta](https://github.com/LandSandBoat/server/assets/108362771/f654cc1d-43ed-4b9b-9d6e-7d96e88500a4)

Inner_Horutoto_Ruins
![Inner_Horutoto_Ruins](https://github.com/LandSandBoat/server/assets/108362771/1622d7ea-9e1b-4abb-b6f6-be7856e24d57)

**Comment by kaincenteno** [comment]
@misterperson can you try again today since we rebuilt again? (think last rebuilt before that was sunday)

**Comment by misterperson** [comment]
Built latest server with 100% casket chance and tested with latest client. Seems fixed
