### ISSUE TITLE
🐛 Party only player spells and abilities can be cast and used on all alliance members

### ISSUE THREAD

**Issue by TracentEden** [DerpyProjectGroup/topaz#4748]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Player can cast/use party-only spells and abilities (like refresh) on all alliance members. I think the issue is based on this conditional code in `CCharEntity::ValidTarget`

```cpp
    if ((targetsParty || targetsAlliance || hasPianissimo) &&
        (isSameParty || isSameAlliance || isPartyPetMaster || isSoloPetMaster) &&
        isDifferentChar)
    {
        return true;
    }
```

I think fix could be like this (was tested to work on horizon repo)

```cpp
    if ((((targetsParty || hasPianissimo) && (isSameParty || isPartyPetMaster)) ||
         (targetsAlliance && isSameAlliance) || isSoloPetMaster) &&
        isDifferentChar)
```

I do not know if I can PR this myself because I already have ASB as my fork of LSB and ASB does not have the previous commits that introduced this bug. 

Thanks to Siknoz for confirming the bug on LSB!

## Expected behavior

Should only be able to cast/use party-only spells and abilities on party members.

**Comment by zach2good** [comment]
Related: https://github.com/LandSandBoat/server/pull/4600

**Comment by zach2good** [comment]
The spells in question aren't flagged for alliance, right?

**Comment by zach2good** [comment]
Set a breakpoint and find out which condition is letting stuff though, will be interesting

**Comment by Xaver-DaRed** [comment]
Actually...

Isnt that new code (from linked PR) saying:

3 conditions must be met:
- Action has one of 3 valid flags. (Party, alliance or pianissimo)
- Target is a member of 1 of 3 groups (Party, alliance or pet master)
- Target is not the you (You... not)

So the following is possible:

If spell has party flag AND target is alliance member AND taget is not you then true?

^ This is concretely what I think its happening

My point: The new alliance checks should have been separate in a new IF statement

**Comment by TeoTwawki** [comment]
I fixed your code  quote for you in the OP so it gets syntax highlighting now.
