### ISSUE TITLE
🐛 Warp ring animation doesn't play completely

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#4769]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu

## Branch affected by issue 

`base`

## Steps to reproduce

with 1 character:
use warp ring
see animation, animation wont finish playing (will play for like a split of a second), screen will go black to loading screen

Its more noticeable if you have 2 characters:
Have 2 characters  logged in.
have 1 of them use the warp ring.
The warp ring animation is so short that the warping effect doesn't play completely, char just almost disappears

## Expected behavior

Use warp ring.
see animation
allow a couple seconds before screen goes black (no fade to black)
https://youtu.be/zTLLugHJ6zo?si=LhXRvgLDctQxLxlr&t=1205

**Comment by TeoTwawki** [comment]
https://github.com/LandSandBoat/server/blob/d846296a474d23e977b578d167a3ca440596a869/scripts/items/warp_ring.lua#L13

its because this 1 is supposed to be a 2 (or higher)

**Comment by TeoTwawki** [comment]
GoV homing instinct and Scroll of Instant have the same bug btw. Warp Cudgels seem to be fine.

**Comment by TeoTwawki** [comment]
was going to leave this low hanging fruit for some new person to cut their teeth on, but now that I already started timing how long retail warpages take, I'm pr'ing it myself

**Comment by kaincenteno** [comment]
nice thanks @TeoTwawki  n happy shopping day😄
