### ISSUE TITLE
🐛 <Ashu Talif Captain not targetable or attackable>

### ISSUE THREAD

**Issue by ghost** [DerpyProjectGroup/topaz#4790]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated. 
There was an issue opened about this but it was closed with no indication it was fixed. 

## Branch affected by issue 

`base`

## Steps to reproduce

 Play Mission 15 The Ghost Coffin. Enter battlefield. Fight first round of enemies. Captain enemy spawns and try to target (only f8 works). Then attempt to cast Dia. No reaction in logs or from PC. Try using WS, no reaction from PC. /attack does not start and no messages "cannot see target" or "target cannot be attacked".

## Expected behavior

 Target Ashu Talif Captain and promptly send his HP to 0 by using spells, ws or attack.

**Comment by RAIST5150** [comment]
Was an issue opened on The Black Coffin fight for this very problem Summer of 2022, but it got closed by the OP with no explanation:

https://github.com/LandSandBoat/server/issues/1976

Just a few notes to aid with review of some relevant  scripts, as things are a bit spread out for this one

scripts/missions/toau/15_The_Black_Coffin.lua

scripts/zones/Arrapago_Reef/Zone.lua
(conditional statement checks cs to trigger instance zone action)

scripts/zones/The_Ashu_Talif
 (Instance, mobs, etc.)

Also... the OP is coming from xiweb, Ubuntu server (last I was aware, Kain was on v22.04).  Was rebuilt roughly a week ago IIRC (shortly after the GEO unlock quest timestamp check fix was meged)... server and client are in synch with the 2nd November patch cycle from SE.
