### ISSUE TITLE
🐛 Mithkabob shirt cannot be equipped

### ISSUE THREAD

**Issue by Aeltorian** [DerpyProjectGroup/topaz#4814]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win10

## Branch affected by issue 

`base`

## Steps to reproduce

!additem mithkabob_shirt
Try to equip it.

## Expected behavior

Should be able to equip it on any job, any level.

**Comment by claywar** [comment]
Closing this, looks like it was addressed already
