### ISSUE TITLE
🔨 Tredecim Scythe's hidden effect not implemented

### ISSUE THREAD

**Issue by Aeltorian** [DerpyProjectGroup/topaz#4819]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

Every 13th standard melee swing with this weapon is guaranteed to be a critical hit if, it does not miss.

[BG Wiki's Tredecim Scythe](https://www.bg-wiki.com/ffxi/Tredecim_Scythe)
[JP Wiki's Tredecim Scythe](https://wiki.ffo.jp/html/6479.html)

**Comment by zach2good** [comment]
I've shot down an implementation of this in the past because it used a CharVar to track whether or not the hit was a critical. I think it also used a hard-coded ID in core, which is a no-no. 

But these days, we have cached charvars, so there's no performance penalty, and we can add a time expiry to char vars, so they don't have to live forever. Given both of these, I think it's permissible to store (swingCount % 13) as a charvar and have it expire in like.. a month, or something.

**Comment by WinterSolstice8** [comment]
Tredecim Scythe is _not_ augmentable -- most likely this means that the swing count was stored in extdata for the weapon, we could use that system most likely

**Comment by zach2good** [comment]
... why did I never think of that ...

**Comment by zach2good** [comment]
Useful places to look:

`scripts/items/chaosbringer.lua` 

```
addListener('ATTACK', 'PET_WYVERN_ENGAGE', function(player, target, action)
```

**Comment by zach2good** [comment]
Things needed for this:
- A new listener trigger for MELEE_SWING
- A new Lua usertype for lua_attack
- lua_attack only needs setCritical(true/false) for now

This brings forward some work we wanted to do later. Then it would be possible to go:

```lua
onItemEquip:
    player:setListener('MELEE_SWING', function(player, target, attack)
        local item = player:getMainWeapon(...)
        
        -- check its still the right item
        
        local count = item:getExdata()[0]
        if count % 13 == 12 then
            attack:setCritical(true)
        end

        item:setExdata({ [0] = (count + 1) % 13 }) 
    end
```

Something like that
