### ISSUE TITLE
🐛 Trusts should count for latents based on party size

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#4861]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

**Equip Lyft Pole on retail with no party:**

![image](https://github.com/LandSandBoat/server/assets/131182600/c055fad1-5007-4287-83de-d561dde38a1c)

Spawn trusts:

![image](https://github.com/LandSandBoat/server/assets/131182600/c65f9e10-b929-469d-a020-b1cfa815b74f)

See that the latent applies attack based on the party size, including trusts

**Similarly, for latents that require a particular job in the party. Here's "Survivor Earring" with empty party:**

![image](https://github.com/LandSandBoat/server/assets/131182600/9fdefd93-ef1b-46b0-99f3-eb8344bc2138)

and with a pld trust out:

![image](https://github.com/LandSandBoat/server/assets/131182600/f7888e5d-398e-4ac4-88a7-c5aec796bf53)

I am not very familiar with the trust logic/workflow, but if someone who is would guide me in the direction I don't mind tackling this issue.

There's also a handful of incorrect Lyft-specific latents (based on bgwiki, can get someone to confirm on retail when this issue starts getting worked on)

## Expected behavior

LSB properly consider trusts when calculating party size/composition for latents.

**Comment by TeoTwawki** [comment]
good catch

**Comment by TeoTwawki** [comment]
in latent container there is likely a `forParty()` lambda that needs to be made `forPartyWithTrusts()`

**Comment by MowFord** [comment]
Meh, I dug in and it seems like latent processing for party-based stuff takes a number from some other place. There's latent 15 and latent 16, for party size and party members in zone, respectively.

The one that checks for a particular job in the party probably can be fixed with your idea, though
