### ISSUE TITLE
🐛 Missing gear set bonus for Vampirc Mitts/Boots

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#4862]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Equip both, see that you don't get drain/aspir bonus mod: `ENH_DRAIN_ASPIR`

Looking at https://github.com/LandSandBoat/server/blob/base/scripts/globals/gear_sets.lua there is nothing there for vampiric mitts/boots

I can easily add in a PR, but i'm curious about the table indexing. There should be zero reason for the numeric indexes, right?

**Comment by TeoTwawki** [comment]
in theory could probably rework to `["quoted string indexes"]` but what you see now is already cleaned up from even worse older formatting, and we have more important things to do.

**Comment by MowFord** [comment]
my suggestion was just to do away with explicit indexing, I don't think those numbers are _used_ for anything.

i.e. 
```
local gearSets =
{
    [1] = -- Usukane's set (5% Haste)
    {
        items =
        {
            xi.item.USUKANE_SOMEN,
            xi.item.USUKANE_HARAMAKI,
            xi.item.USUKANE_GOTE,
            xi.item.USUKANE_HIZAYOROI,
            xi.item.USUKANE_SUNE_ATE,
        },
        minEquipped = 5,
        mods =
        {
            { xi.mod.HASTE_GEAR, 500 },
        },
    },

    [2] = -- Skadi's set (5% critrate is guess)
    {
        items =
```

would become

```
local gearSets =
{
    -- Usukane's set (5% Haste)
    {
        items =
        {
            xi.item.USUKANE_SOMEN,
            xi.item.USUKANE_HARAMAKI,
            xi.item.USUKANE_GOTE,
            xi.item.USUKANE_HIZAYOROI,
            xi.item.USUKANE_SUNE_ATE,
        },
        minEquipped = 5,
        mods =
        {
            { xi.mod.HASTE_GEAR, 500 },
        },
    },

    -- Skadi's set (5% critrate is guess)
    {
        items =
```

**Comment by TeoTwawki** [comment]
I prefer explicit indexing (as a general pattern). things look like CHAOS to me with no obvious index.

you should have seen the older limbus tables and the older mission functions. insanity. never again.

**Comment by MowFord** [comment]
Fair enough.

Also I haven't confirmed but taking a look at the consolidation functions at the bottom, it looks like gear set bonuses aren't removed upon level sync?

**Comment by TeoTwawki** [comment]
> it looks like gear set bonuses aren't removed upon level sync?

worth testing. make a separate issue report if so.
