### ISSUE TITLE
🐛 [COR Ability] Random Deal not implemented.

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#4864]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Random Deal not implemented. Ability does nothing. Nothing in code.

## Expected behavior

Random Deal should have a chance to reset job abilities as well as have a chance to reset 2 abilities with the proper gear mod.

https://www.bg-wiki.com/ffxi/Random_Deal

**Comment by UmeboshiXI** [comment]
https://github.com/LandSandBoat/server/discussions/5179

Linking for awareness.

**Comment by MowFord** [comment]
This is resolved in https://github.com/LandSandBoat/server/pull/5406 and crash fixed in https://github.com/LandSandBoat/server/pull/5608

**Comment by Xaver-DaRed** [comment]
This was fixed in PR 5406
