### ISSUE TITLE
"NPC" named npcs with current client and server

### ISSUE THREAD

**Issue by ffxijuggalo** [DerpyProjectGroup/topaz#490]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: 30210706_0 everything branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Gondebaud, the trust npc in Southern Sandoria is shown as NPC ingame. My server has been updated as of early this morning to 30210706_0 and the client as well. Database has been updated using the dbtool without issues. At least one other player verified this to be true with their client running on 30210706_0.
![image](https://user-images.githubusercontent.com/22580624/125485174-8459f1c2-6ef9-430c-beac-676c69781b5b.png)

The other player with me in this screenshot is on a different client version and can see Gondebaud's name as normal.
![image](https://user-images.githubusercontent.com/22580624/125485483-52346341-c1a1-4996-bca1-4c9203d73229.png)

Kind of odd so i figured i'd get the issue posted just incase there's something else going on i'm not aware of.

**Comment by Era-Lusiphur** [comment]
Not a huge surprise. Zach basically wrote the update tool over the weekend and focused on text IDs, etc. He was aware that there may be some remaining issues and some randomly shifted NPC IDs were definitely possible. Main focus was enabling fairly smooth general play, as shifted Text IDs mean Caskets don't work, Fishing is awkward, etc.

The rest will be cleaned up when possible and the process will continue to improve. The best gain this weekend is someone can literally download the new version updates, run the tool, and have the majority of the important shifts PR'd in relatively no time!

**Comment by helixhamin** [comment]
It still seems to be present.

**Comment by claywar** [comment]
ID shift issue, this has been resolved for quite some time and closing
