### ISSUE TITLE
game process crashing on login

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#494]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm doing a test migration to a newly built Windows server and running into a crash when trying to log one of my characters in. I followed the steps for debugging with Visual Studio and have attached the dump to the ticket. To be clear I've imported my db from prod, all i changed was zoneip table...

I think dump is too big to attach, so i threw it on my gdrive.

https://drive.google.com/file/d/1L04B7dMStlhhrKax37WZI9lwS11KRBih/view?usp=sharing

Thanks

**Comment by Xaver-DaRed** [comment]
Not to be THAT guy that sais "It works for me"...
But i just did a fresh install of VS, maria and required dependencies on a pc, built the servers just fine, created 2 different databases, 1 using dbtool and the other doing a manual import of tables and in both cases i had no issues.

Since you just changed environment, I would recomend you follow the instalation guide to the letter, make sure you have all the required dependencies, and everything properly configured and try again.

**Comment by zach2good** [comment]
> I followed the steps for debugging with Visual Studio and have attached the dump to the ticket.

https://github.com/LandSandBoat/server/wiki/Debugging#how-to-make-a-dump-file-with-visual-studio-2019
...  for which **you've been asked** to provide a dump file ...

The reason we mention that **we'll ask you** for a dump file (if needed) is that we will also ask you for the corresponding `exe` and `pdb` that the dump was generated from. Without these additional files, the dump is worthless. It's also very rare that we actually need a dump to diagnose problems, I haven't needed to ask someone for one in more than ~2 years.

We've just had someone test a backup-and-import across two different installs using `dbtool` and everything works as expected. Is there anywhere you've deviated from our guides?

(Xaver beat me to it: they did the testing)

_Resources_
https://docs.microsoft.com/en-us/archive/blogs/jimgries/why-does-visual-studio-require-debugger-symbol-files-to-exactly-match-the-binary-files-that-they-were-built-with

**Comment by CatsEyeXI** [comment]
to be clear gentlemen, since the debug points to a memory out of bounds error, are we using the x64 binaries or x86?

**Comment by TeoTwawki** [comment]
> 
> 
> Not to be THAT guy that sais "It works for me"...
> But i just did a fresh install of VS, maria and required dependencies on a pc, built the servers just fine, created 2 different databases, 1 using dbtool and the other doing a manual import of tables and in both cases i had no issues.
> 
> Since you just changed environment, I would recomend you follow the instalation guide to the letter, make sure you have all the required dependencies, and everything properly configured and try again.

additional note: importing your old db onto a new setup probably still needs the db updated via the db tool.

**Comment by TeoTwawki** [comment]
> 
> 
> to be clear gentlemen, since the debug points to a memory out of bounds error, are we using the x64 binaries or x86?

whichever you chose to build - both exist

**Comment by zach2good** [comment]
> to be clear gentlemen, since the debug points to a memory out of bounds error, are we using the x64 binaries or x86?

Defaults to x64

**Comment by CatsEyeXI** [comment]
> > I followed the steps for debugging with Visual Studio and have attached the dump to the ticket.
> 
> https://github.com/LandSandBoat/server/wiki/Debugging#how-to-make-a-dump-file-with-visual-studio-2019
> ... for which **you've been asked** to provide a dump file ...
> 
> The reason we mention that **we'll ask you** for a dump file (if needed) is that we will also ask you for the corresponding `exe` and `pdb` that the dump was generated from. Without these additional files, the dump is worthless. It's also very rare that we actually need a dump to diagnose problems, I haven't needed to ask someone for one in more than ~2 years.
> 
> We've just had someone test a backup-and-import across two different installs using `dbtool` and everything works as expected. Is there anywhere you've deviated from our guides?
> 
> (Xaver beat me to it: they did the testing)
> 
> _Resources_
> https://docs.microsoft.com/en-us/archive/blogs/jimgries/why-does-visual-studio-require-debugger-symbol-files-to-exactly-match-the-binary-files-that-they-were-built-with

[pdb and exe.zip](https://github.com/LandSandBoat/server/files/6816481/pdb.and.exe.zip)

**Comment by CatsEyeXI** [comment]
> > Not to be THAT guy that sais "It works for me"...
> > But i just did a fresh install of VS, maria and required dependencies on a pc, built the servers just fine, created 2 different databases, 1 using dbtool and the other doing a manual import of tables and in both cases i had no issues.
> > Since you just changed environment, I would recomend you follow the instalation guide to the letter, make sure you have all the required dependencies, and everything properly configured and try again.
> 
> additional note: importing your old db onto a new setup probably still needs the db updated via the db tool.

PS C:\server\tools> python.exe .\dbtool.py update
Database is up to date.

**Comment by CatsEyeXI** [comment]
> Not to be THAT guy that sais "It works for me"...
> But i just did a fresh install of VS, maria and required dependencies on a pc, built the servers just fine, created 2 different databases, 1 using dbtool and the other doing a manual import of tables and in both cases i had no issues.
> 
> Since you just changed environment, I would recomend you follow the instalation guide to the letter, make sure you have all the required dependencies, and everything properly configured and try again.

I don't mind you being "that guy", I did follow the guide "to the T". However, there are more variables that are unaccounted for... 
I'm on Windows 2019 Server. Going to try building the x86 binaries and test again.

**Comment by CatsEyeXI** [comment]
And it's only certain characters...  my freshly created character logs in fine, but my GM chars crash it on the loading screen...

**Comment by TeoTwawki** [comment]
well those chars have to have something in common. have you done anything like remove out of era items for your server or other customization's of that nature? it wants to load something form those chars that went kabooms. I haven't looked at the dump yet gonna be a bit.

**Comment by CatsEyeXI** [comment]
> well those chars have to have something in common. have you done anything like remove out of era items for your server or other customization's of that nature? it wants to load something form those chars that went kabooms. I haven't looked at the dump yet gonna be a bit.

not that i can think of, wouldnt all that info be stored in the db? and take your time.. this is a dev environment, that will eventually transition to prod once i iron these issues out.

**Comment by CatsEyeXI** [comment]
and I will also keep messing with it in the meantime, My purpose for opening the ticket is not to suddenly make this "your problem", but maybe one of you has come across it before. As always, appreciate the insight.

**Comment by TeoTwawki** [comment]
your crashdump appears to be a little older than the current build but I could see the place everything exploded in was outside the project, in the windows side of things. Kernel code of windows from an invalid access. This usually means windows was asked to try something impossible like getting a number between 2 otehr numbers where the maximum value is lower than the minimum or something crazy like that. Without knowing the last function to happen in the map server I can't look further than this. I suggest attaching the VS debugger to your process prior to login, and then deliberately inducing the crash. You'll get better info and be able to browse the stack in visual studio. Anyone wanting to run a server long term is going to find this experience useful anyway, so prepare for fun excitement and ohgodTeowhydidyoudothistome  :D

**Comment by CatsEyeXI** [comment]
> your crashdump appears to be a little older than the current build but I could see the place everything exploded in was outside the project, in the windows side of things. Kernel code of windows from an invalid access. This usually means windows was asked to try something impossible like getting a number between 2 otehr numbers where the maximum value is lower than the minimum or something crazy like that. Without knowing the last function to happen in the map server I can look further than this. I suggest attaching the VS debugger to your process prior to login, and then deliberately inducing the crash. You'll get better info and be able to browse the stack in visual studio. Anyone wanting to run a server long term is going to find this experience useful anyway, so prepare for fun excitement and ohgodTeowhydidyoudothistome :D

Hi Teo, thank you for taking the time to look at the dump. I'm sorry it took me a while to respond but I wanted to make sure I could give thorough response. Attached you'll find an archive containing the pdb, exe, and dump of the crash, as well as a screenshot of VS2019 with the exception. 

I went one step beyond and recorded the encounter as well (for extra credit), hoping that might give some additional perspective, in case i was doing something wrong.

This is after a clean pull, none of my configs, or customizations were copied over. All i did was update the db, user/pass in the conf files, import my sql, run the update tool, and let it rip.


Regards,
Carver

https://drive.google.com/file/d/1b8kA9kVV5UiM_PmTYkwAcCNVNHic2KLh/view?usp=sharing

**Comment by TeoTwawki** [comment]
try disabling Records of Eminence - looks like the character has an invalid one flagged somehow
![image](https://user-images.githubusercontent.com/6871475/125796705-7bf04588-4569-45d6-95ec-902806bdea33.png)

**Comment by CatsEyeXI** [comment]
> 
> 
> try disabling Records of Eminence - looks like the character has an invalid one flagged somehow
> ![image](https://user-images.githubusercontent.com/6871475/125796705-7bf04588-4569-45d6-95ec-902806bdea33.png)

You so smart bb... disabling RoE did allow me to login. Why and how 🤣

**Comment by CatsEyeXI** [comment]
![image](https://user-images.githubusercontent.com/65316697/125823516-2c48764d-e5b6-45d6-baa4-c2b73ee03d3e.png)

could this be why?

**Comment by TeoTwawki** [comment]
compare yours to ours on github, whichever file that is that I can't tell from the trimmed screenshot (hey I ain't psychic)

**Comment by CatsEyeXI** [comment]
file on the left is from my current running server, file on the right is current github...

**Comment by CatsEyeXI** [comment]
If I have that RoE set on my character, and the file was updated, wouldn't that render the record invalid?

**Comment by TeoTwawki** [comment]
well yes if your files are mismatched from diff versions all kindsa shit will break..

**Comment by TeoTwawki** [comment]
I really need you to get into a habit of having an entirely separate folder with NONE of your stuff in it, that is untouched and you just "pull" and nothing else (aside form password and diff db name than your actual server copy). if the bug doesn't happen on the untouched one (and no, don't import your db over it either) then we do not have a bug its something you did or didn't do or did wrong in your update process.

**Comment by TeoTwawki** [comment]
if you are pulling from us, normally your only file differences will be: 

1. stuff intentionally changed (confs, settings, custom things)
2. stuff that had an edit conflict with stuff you changed, that you need to take care of
3. saved queries to use on your db like to set zoneip and such

**Comment by CatsEyeXI** [comment]
this is a completely separate install and fresh pull, Teo. I just happened across this difference after you after you mentioned RoE, I went and scanned my currently running server for any possible differences with Meld and found that. 

My question is, if I had that RoE flagged (and not completed), before the lua was 'updated' on GitHub, could this account for the crashing? if so, how can i clear this in my DB to stop the crash on connecting... 

Also, I have taken your advice as of a little while ago and made a custom directory tree with my stuff in it, that I can just plop over a clean installation, and not interfere with your files...

Thanks for your patience...
![image](https://user-images.githubusercontent.com/65316697/125825819-2a259012-c169-428d-817e-3bed451fb008.png)

**Comment by TeoTwawki** [comment]
That string is simply a variable inside of a table - a reference to a number. the number didn't change. it can't break your saved info.

Your bad record didn't come from this, unless you have one part of your code using an old identifier and another part using the new (in which case only one version is valid)

xi.clickMe.IMA_BIG_RED_BUTTON can be named whatever we want to name it, as long as we constantly use the same name. which is why we create conventions like removing special characters that break stuff like apostrophes, and NOT replacing them with underscores (when we find that we fix it)

**Comment by CatsEyeXI** [comment]
This issue has been resolved. A big THANK YOU Teo for all your hard work, I wouldn't be able to operate this server without you and your team. Thanks for bailing me out yet again. /kneel

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/125831696-06595d64-907d-4fdc-92eb-aee08f5979c2.png)


(explain the solution for our descendants)

**Comment by CatsEyeXI** [comment]
Solution was to clear the contents of the eminence row in the 'chars' table.
