### ISSUE TITLE
🐛Possible copy/paste error in fishing util src

### ISSUE THREAD

**Issue by strixnivea** [DerpyProjectGroup/topaz#4963]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

All

## Branch affected by issue 

`base`

## See these permalinks
Should be MOONPATTERN_5?
https://github.com/LandSandBoat/server/blob/ece956579adf1d2f9aa7f97552e2637a070a132c/src/map/utils/fishingutils.cpp#L336

Should be 110 or at least settable and not hardcoded 100?
https://github.com/LandSandBoat/server/blob/ece956579adf1d2f9aa7f97552e2637a070a132c/src/map/utils/fishingutils.cpp#L1079

**Comment by claywar** [comment]
Resolved by #4966
