### ISSUE TITLE
🐛 Sonic Belt +1 not equippable

### ISSUE THREAD

**Issue by glw888** [DerpyProjectGroup/topaz#4964]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`AirSkyBoat`

## Steps to reproduce

<Sonic Belt +1 is craftable, shows in item list, but does not show on equip screen>

## Expected behavior

<Should be equippable>

**Comment by zach2good** [comment]
Works fine for us:
<img width="379" alt="image" src="https://github.com/LandSandBoat/server/assets/1389729/6c7c4801-10d8-495d-9fa3-3fd9876c3f3b">

AirSkyBoat is a different and unrelated project to us, and we have no control over what they do. You should report this to their bug tracker: https://github.com/AirSkyBoat/AirSkyBoat/issues
