### ISSUE TITLE
BRD song power plummets with 256+ instrument skill

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#501]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Cast high level Minuet with 255 wind skill while equipped with a horn, then cast it again with 256+ skill, and watch the attack bonus plummet. This applies to all BRD buff songs that use skill for power, Minuet is just the easiest to see. Exceeding 256 singing skill works as expected, ie. properly.

**Comment by Xaver-DaRed** [comment]
uint8 CLuaBaseEntity::getWeaponSkillLevel(uint8 slotID)

I guess its a matter of changing uint8 to uint16 in bothe lua_baseentity.cpp and .h

**Comment by claywar** [comment]
Absolutely this.  `CCharEntity::GetSkill()` returns uint16, and binding is defined as uint8

**Comment by Snugglesffxi** [comment]
you guys are amazing! on the same note should we just add checks for xi.skill.WIND_INSTRUMENT and xi.skill.STRING_INSTRUMENT in the bard song scripts instead? or do you recommend against it?
