### ISSUE TITLE
Changing zone ports crashes server when you enter mog house

### ISSUE THREAD

**Issue by GanimanSwift** [DerpyProjectGroup/topaz#507]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
If I change zone ports from the default 54230 and enter a mog house from a zone where the port is not default, the server crashes.

To repeat: change all San d'Oria zone ports to something else (I use 54319). Enter mog house from Northern San d'Oria, client will hang on downloading data, server log gets flooded with:

[Fatal Error]  --- gdb backtrace ---

And then finishes with:

[Error]  pipe failed for gdb backtrace: Too many open files

and the server crashes.

If I change all zone ports back to the default 54230 this does not happen.

**Comment by claywar** [comment]
I would suggest getting the backtrace from your core dump and posting it; outside of that, there's not much to work off of.

**Comment by GanimanSwift** [comment]
> I would suggest getting the backtrace from your core dump and posting it; outside of that, there's not much to work off of.

I can try, but you should be able to reproduce this from a fresh install.

**Comment by claywar** [comment]
> > I would suggest getting the backtrace from your core dump and posting it; outside of that, there's not much to work off of.
> 
> I can try, but you should be able to reproduce this from a fresh install.

Seeing as this does not occur for me, and it does for you, perhaps you could provide the stack trace?  If we were crashing on start:
1. CI would have caught it, which it doesn't crash.
2. I would've noticed locally, since I'm developing code on a near-daily basis
