### ISSUE TITLE
🐛 HPP and MPP are calculated incorrectly

### ISSUE THREAD

**Issue by DiscipleOfEris** [DerpyProjectGroup/topaz#5093]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue

`base`

## Steps to reproduce

1. Calculate your max yellow HP threshold, which is the largest HP that is less than 75% of your max HP. (For example, with 1000 max HP, you should be yellow at 749 HP or less).
2. Set your HP to this max yellow HP threshold (749 HP, in the previous example).
3. Observe your HP is white. (`/echo <hpp>` will output 75%).
4. Keep reducing your HP until it finally turns yellow (this will be at 74% HP or less, rather than <75% HP).

Alternatively:

1. Set your current HP to your max HP.
2. Do `/echo <hpp>` (Observe 100%)
3. Set your HP to 1 less than max HP.
4. Do `/echo <hpp>` (Observe 100%)

## Expected behavior

3. Your HP turns yellow. `/echo <hpp>` will output 74%.

Alternatively:

4. `/echo <hpp>` outputs 99%.

## Analysis

The problem is in [`CBattleEntity::GetHPP()`](https://github.com/LandSandBoat/server/blob/base/src/map/entities/battleentity.cpp#L193) and [`CBattleEntity::GetMPP()`](https://github.com/LandSandBoat/server/blob/base/src/map/entities/battleentity.cpp#L209). These functions directly feed into the `CCharHealthPacket`/`0x0DF` packet which informs the client of their HPP (and hence red/orange/yellow/white HP and the output of `/echo <hpp>`).

```C++
uint8 CBattleEntity::GetHPP() const
{
    return (uint8)ceil(((float)health.hp / (float)GetMaxHP()) * 100);
}
```

It is doing `ceil()` whereas it should be doing `floor()`. To account for retail only yielding 0 HPP when your HP is 0 (that is, you're dead), it should look something like this:

```C++
uint8 CBattleEntity::GetHPP() const
{
    if (health.hp == 0)
    {
        return 0;
    }
    
    return std::max<uint8>(1, (uint8)floor((float)health.hp / (float)GetMaxHP()) * 100);
}
```

There could potentially be a variety of knock-on effects from other systems having previously compensated for this inaccuracy, so it probably needs a bit of discussion before fixing.

Possibly affected systems:

* Undead aggro threshold
* HPP latent effects
* Sublimation deactivation
* Mob TP behaviors
* Breath damage
* Spirits Within damage
* Wyvern healing breath threshold (should be 1/2, 1/3, 1/4 rather than HPP from my testing, but that's a separate issue).
* ???

**Comment by TracentEden** [comment]
@DiscipleOfEris Do you happen to know if in retail things such as latent effects use the same HPP logic? I am making a PR to fix this but unclear if the HPP logic for all the systems you mention use the same floor logic.

**Comment by DiscipleOfEris** [comment]
@TracentEden There are actually two types of HP latent triggers. One is based on your HPP (e.g. Medicine Ring), and another is based on a rather arcane formula (e.g. Sorcerer's Ring). You can see where I discussed this a little bit in #5127 comments.

From the glances at the code I've done, player systems fall into two categories: using HPP assuming it works the same as retail and will thus have been wrong all this time and will be fixed by this change, or already coded HP% independently of HPP and will be unaffected by this change. I might have missed something though.

**Comment by TracentEden** [comment]
> @TracentEden There are actually two types of HP latent triggers. One is based on your HPP (e.g. Medicine Ring), and another is based on a rather arcane formula (e.g. Sorcerer's Ring). You can see where I discussed this a little bit in #5127 comments.
> 
> From the glances at the code I've done, player systems fall into two categories: using HPP assuming it works the same as retail and will thus have been wrong all this time and will be fixed by this change, or already coded HP% independently of HPP and will be unaffected by this change. I might have missed something though.

Yeah, I will change the latents to also use HPP formula (except the arcane ones which will use a different HPP formula that will also be in the PR), thanks for your info

**Comment by WinterSolstice8** [comment]
I did notice healing breath was slightly off (it's single to double digit more in favor of the player) but didn't realize it was not tied to hpp interesting. Probably the reasoning I didn't notice during the audit was I was only off by so little that i just chalked it up to rounding errors.

On retail it was always `max HP / 2` for healing sub + drachen armet, and `max hp * .33` without (or on hybrid sub), floored of course.

**Comment by DiscipleOfEris** [comment]
> I did notice healing breath was slightly off (it's single to double digit more in favor of the player) but didn't realize it was not tied to hpp interesting. Probably the reasoning I didn't notice during the audit was I was only off by so little that i just chalked it up to rounding errors.
> 
> On retail it was always `max HP / 2` for healing sub + drachen armet, and `max hp * .33` without (or on hybrid sub), floored of course.

From my retail testing, the healing breath thresholds are actually (floored, of course) Max HP/2, Max HP/3 and Max HP/4. It's not 0.33, it's one third.

**Comment by WinterSolstice8** [comment]
![image](https://github.com/user-attachments/assets/fd3c244e-2154-4460-9e7e-4344a42ce30b)
neat

**Comment by WinterSolstice8** [comment]
I got an HP value where max hp * .75 is a whole number and it reports white hp still, one HP below which is 74.969% reports yellow HP and 74% as you indicated
![image](https://github.com/user-attachments/assets/b68e5386-dc64-4f6d-99ef-7166aef87b6c)

Seems wrong enough to me to just fix it tbh, hpp% isn't used in a ton of places so it probably wont be too hbad

**Comment by WinterSolstice8** [comment]
Looks like most C++ things didn't need adjustment, but a few for Automatons did (mpp and hpp, actually)

**Comment by WinterSolstice8** [comment]
It seems all HP/MP based latent effects are not using GetHPP() (see latent_effect_container.cpp) so those would be unaffected, however since the PR I made about calculating HP/MP came in I think I understand how to get the sorcerer ring latent to work properly now. I still would want to get one (and others with an obvious effect, like medicine ring) before changing the latent

**Comment by DiscipleOfEris** [comment]
> It seems all HP/MP based latent effects are not using GetHPP() (see latent_effect_container.cpp) so those would be unaffected, however since the PR I made about calculating HP/MP came in I think I understand how to get the sorcerer ring latent to work properly now. I still would want to get one (and others with an obvious effect, like medicine ring) before changing the latent

From previous research, the formula for Sorcerer's Ring seems to be pretty arcane. I'd probably make a config setting for "sane" and "retail accurate" if I were coding it myself. But I wasn't able to get my hands on one to test myself on retail so I wasn't able to confirm the research I read. But from their testing, the retail implementation of Sorcerer's Ring is probably bugged, as it seems to ignore HP+/- from a specific one of the earring slots.

EDIT: I looked at my notes, and Sorcerer's Ring seems to ignore HP+/- from the *back* and *right ring* slots.
