### ISSUE TITLE
Chat filters are not persistent

### ISSUE THREAD

**Issue by personaone** [DerpyProjectGroup/topaz#512]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

Chat filters are not permanent and revert on zone, IIRC on retail, this was actually saved per character - does this need a table in the Database? I'm happy to contribute to the project if anyone can guide me.

**Comment by zach2good** [comment]
Hey!

As far as I'm aware, chat filters are a little bit involved and will require capture, SQL and core work to get up and running.

There is an implementation out there already but it's under a license that is functionally incompatible with ours, so we can't use it, or even look at it for crib notes (lest their license leaks into our codebase). One option would be to contact the original author and see if they would be willing to give us a copy of the code that they wrote under our license (GPLv3).

Failing that, the steps to implement this from scratch would be:
- Capture
  - Go onto retail, start capping
  - Zone
  - Change your chat filters
  - Zone again
  - Repeat a couple of times, setting the highest, lowest, and each filter in turn.
- Analyze
  - Using [PVLV](https://github.com/ZeromusXYZ/PacketViewerLogViewer), step through your caps and see if there is any big fat bitfield that changes when you set your filters, and if that same field is sent/received while you're zoning
  - This may or may not be already mapped by [Windower's packet information](https://github.com/Windower/Lua/blob/dev/addons/libs/packets/fields.lua), but likely not
  - Once you've identified the packet in question, you're ready to start coding
- SQL
  - You'll want to represent this new data in `chars.sql` more than likely (unless we have something specific for settings?), and if you're adding data to a "live data" table, you'll need to provide a migration file for `dbtool.py` to use
  - You'll need to identify and use some default filter mask
- Core
  - You'll want to pull the filter information from the db on ZoneIn, and send it to the client
  - You'll need to add a packet handler to `packet_system.cpp` to handle updates, which will likely write to the db (or you can be lazy and store it on the char object, and only write it on zone. But they you run the risk of filters being lost on server crashes 🤷 )

Off the top of my head, that should be it. Though, most sane people just use `BattleMod` to handle all their text and filtering ;)

**Comment by personaone** [comment]
Thanks, can you point me also to the original author of the mentioned implementation? If it’s functional, I’d rather not reinvent the wheel, as they say 😄

**Comment by zach2good** [comment]
I don't know for sure what their github tag is (if they even have one), and I don't want to incorrectly tag a random. If you go ask in the Wings discord who wrote their chat filter handling I'm sure they'll pop up 👍

**Comment by personaone** [comment]
Alright 😁will try there
