### ISSUE TITLE
Confirm Banishing Charm item is consumed or worn after SAM AF3

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#514]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Current behavior for Sam AF3 on fail is to set banishing charm is worn.  Need to confirm if its taken on entry, or set as worn.

**Comment by ShiyoKozuki** [comment]
It's not taken on entry.
https://ffxiclopedia.fandom.com/wiki/A_Thief_in_Norg!%3F
`After the three demons are slain, you receive a Key ItemCharred Helm. The Banishing Charm can now be discarded.`
