### ISSUE TITLE
Mog Safe 2 / Mog House 2nd Floor Needs Properly Implemented

### ISSUE THREAD

**Issue by Era-Lusiphur** [DerpyProjectGroup/topaz#517]
Mog Safe 2 (as well as Mog House 2nd floor) on retail is locked behind the character having completed the three nation's flower girl exit quest. Then you need speaking to your home nation moogle about the 2nd floor, leave, and re-enter your mog house.

Necessary quests:
- Growing Flowers (San d'Oria)
- A Lady's Heart (Bastok)
- Flower Child (Windurst)

Mog House 2nd floor is basically unsupported entirely. Currently, selecting the option to change floors will take you outside of your mog house, having been setup by @teschnei to do so likely to resolve some issue. In commit 4241d7d68672ad8b27acb22e3f7e24f03b02b904 he notes the packet structure hadn't been sorted yet.

Unlocking information from the horses mouth: https://forum.square-enix.com/ffxi/threads/46976-May-14-2015-%28JST%29-Version-Update?p=548832&viewfull=1#post548832

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Any

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by claywar** [comment]
#3546
