### ISSUE TITLE
Limbus: Mobs on each floor all link one mob is pulled

### ISSUE THREAD

**Issue by AuroraFlare** [DerpyProjectGroup/topaz#520]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

Limbus mobs are acting differently when you pull one mob on the floor, all mobs of the same type link floor wide. I am aware that Limbus is still beta, etc. I just wasn't sure if this was part of the instance changes or something different.

**Comment by CatsEyeXI** [comment]
Is Limbus part of everything branch?

**Comment by AuroraFlare** [comment]
Yeah, I've been using Limbus for a while now, one Temenos zone is 100% broken, and Apollyon mainly worked okay. But recently the enemies behavior changed when I did an update a week ago where they all link on the whole floor.

**Comment by jefferyrlc** [comment]
Proper battlefield instancing came with ToAU. Limbus is handled the same way BCNMs are. How LSB wants to handle it is up to them.

**Comment by TeoTwawki** [comment]
There **was** a core side exception to bcnm-wide superlink  specifically for limbus. dunno what happened to that. And at another point in time the auto-superlink was removed from all bcnm game wide (lots of stuff should, and this really shoudl be handled per mob or per bcnm anyway for retail accuracy)

I think you can alter this via mobmod at init time, for a quick fix. Not nessisarily in scritp per mob:  
https://github.com/LandSandBoat/server/search?l=C%2B%2B&q=superlink  
can just use conditionals for limbus area's till its sorted in project

**Comment by AuroraFlare** [comment]
Thank you for this! I actually did try several things in the code, and I couldn't get super link to disable zonetype limbus, i even removed all super links for battlefields and it still did Limbus haha! So I'm wondering if the zonetype is slightly not working? I suppose it has to work a bit to setup mobs and such in the zones. I found a really easy way to make it a mod on all the mobs in the two zones. Not exactly ideal by any means but it gets the job done until this issue would get resolved. 

bool forceLink = (zonetype == ZONE_TYPE::DYNAMIS || zonetype == ZONE_TYPE::BATTLEFIELD || PMob->getMobMod(MOBMOD_SUPERLINK)) && zonetype != ZONE_TYPE::LIMBUS;

i tried this code and it didn't work. I figured this the one would work.

**Comment by claywar** [comment]
I would suggest setting a breakpoint after that assignment and inspecting those values (or check to see what zonetype the area you're in is classified as).  Even if your mobs had that mod, your test code should handle that and that's the only thing that comes to mind.

**Comment by TeoTwawki** [comment]
There are multiple locations setting up mobs to superlink which is why I linked the search page and not a line of a file. 

Here is _[another example](https://github.com/LandSandBoat/server/blob/3ce9681ea0e3e6038908f56da8fec24166d5d4c1/src/map/utils/mobutils.cpp#L850)_

**Comment by AuroraFlare** [comment]
Sorry for the delayed follow up! Thank you I will try it this weekend and see if it works! I appreciate it!

**Comment by CatsEyeXI** [comment]
> Sorry for the delayed follow up! Thank you I will try it this weekend and see if it works! I appreciate it!

Did you ever get a resolution to this? struggling with the same issue on my server...

**Comment by TeoTwawki** [comment]
oh, forgot this issue. definitely fixed (in our repo) as I have been running Limbus and not seeing this happen!

**Comment by CatsEyeXI** [comment]
> oh, forgot this issue. definitely fixed (in our repo) as I have been running Limbus and not seeing this happen!

Hi Teo,

On a fresh pull:
1. copied over my config files and settings/main.lua... 
2. uncommented the apollyon/temenos entries from bcnm.lua 
3. entered NE Apollyon
4. attacked a Mandy

and they all aggro'd me... Am i missing something you can think of?

**Comment by TeoTwawki** [comment]
> 
> 
> > oh, forgot this issue. definitely fixed (in our repo) as I have been running Limbus and not seeing this happen!
> 
> Hi Teo,
> 
> On a fresh pull:
> 
>     1. copied over my config files and settings/main.lua...
> 
>     2. uncommented the apollyon/temenos entries from bcnm.lua
> 
>     3. entered NE Apollyon
> 
>     4. attacked a Mandy
> 
> 
> and they all aggro'd me... Am i missing something you can think of?

I kid you not I just did mandies and I did not have the whole floor agro me, only the ones I just linked on purpose (so i could aoe the little twerps). I and 2 friends have been doing a lot of Limbus lately trio'ing much of Temenos. No serious issues just lots of death when we encounter a smn mob (4-6k astral flows are so unfair...anybody seen my spleen?)

**Comment by TeoTwawki** [comment]
~~No serious issues~~
I do have _one_ player with a serious issue: their bcnm status lasts forever and has the wrong values, but thats got its own issue on the tracker.
