### ISSUE TITLE
🐛 getWeaponSkillType error in log

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#5210]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows server 2019

## Branch affected by issue 
`base`

## Steps to reproduce
Took awhile to find a repro for this. people were guessing at it in the private servers discord weeks ago, and I finally stumbled on exactly how to see it.

Equip a sword + shield and use vorpal blade. No shield = no error.

This line in `xi.weaponskills.calculateRawWSDmg` will throw an error: 
`local offhandSkill = attacker:getWeaponSkillType(xi.slot.SUB)`

I replaced the get with a zero and used vorpal, no error. put things back, vorpal'd again, error back. Took my shield off and used vorpal: no error. put my shield back on, vorpal again errors. So that's where its coming from for sure.

## Expected behavior
Presumably don't get offhand skill when not a weapon, don't throw error

**Comment by TeoTwawki** [comment]
bah, I hit that button too fast again. Hello Mr. Github actions bot.

**Comment by TeoTwawki** [comment]
```patch
     if not wsParams.multiHitfTP then
         ftp = 1
     end

-    local offhandSkill = attacker:getWeaponSkillType(xi.slot.SUB)
+    local offhandSkill = xi.skill.NONE
+    local subEquip     = attacker:getStorageItem(0, 0, xi.slot.SUB)
+    -- Make sure we HAVE an offhand, and its a weapon
+    if subEquip and not subEquip:isShield() then
+        offhandSkill = attacker:getWeaponSkillType(xi.slot.SUB)
+    end

     if calcParams.skillType == xi.skill.HAND_TO_HAND then
         offhandSkill = xi.skill.HAND_TO_HAND
         subTPGain    = mainhandTPGain
     end
```

That seems to handle it. If anyone would like to more thoroughly test and then PR it if good its free real estate - I don't know when I'll have time.

**Comment by MowFord** [comment]
isn't the message a bit erroneous since it is technically a valid slot, just doesn't have a valid item? Would it not be better to just suppress the console log by adding an else in the main section:

![image](https://github.com/LandSandBoat/server/assets/131182600/51d1e785-ea61-4e75-b851-be60ef82fa8b)

**Comment by TeoTwawki** [comment]
would help if I didn't have heaps of memories of things being counted as a weapons that shouldn't have been, and making it impossible to miscast things as one. but yes that looks like a better solution, if you want to test it out and pr it.

anyone remember when all the grips and shields were in `item_weapon.sql`? good times (not -_-)

ed: could possibly also bake in the "use mainhand skill when we're using h2h" here
