### ISSUE TITLE
🐛 Instace cleanup crashes server

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5263]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
It appears that if mobs remain in an instance, a cleanup of the instance crashes the server due to this deconstructor:

![image](https://github.com/LandSandBoat/server/assets/131182600/345eb4ec-9eb2-4290-bcd4-ea5ee0ab9875)

![image](https://github.com/LandSandBoat/server/assets/131182600/07122221-14fd-4353-8a63-efb31773995c)

We've seen it for instance id 6300 as well. Here's a crashdump

https://cdn.discordapp.com/attachments/1152236166817521785/1217858332748939284/toau.zip?ex=66058df5&is=65f318f5&hm=3057548938a7edf2f81505808831f3d9488bc6b3325ed711c289b4565b65492f&

**Comment by MowFord** [comment]
Tried to track down what changed, but here's the PR syncing from LSB for reference: https://github.com/CatsAndBoats/catseyexi/pull/334/files#

**Comment by MowFord** [comment]
Reproducible steps:
`!addkeyitem nyzul_isle_assault_orders`
enter nyzul to a floor
ensure mobs are on the floor (free floor you must climb to the next floor to get mobs)
`!zone <anywhere else>`
after a bit the instance cleans up and triggers the above error

![image](https://github.com/LandSandBoat/server/assets/131182600/b22e783f-fb9f-4d7f-8dfc-33b756cba0e0)


I changed the baseentity deconstructor:

```
CBaseEntity::~CBaseEntity()
{
    auto* tempBattlefield = dynamic_cast<CBattlefield*>(PBattlefield);

    if (tempBattlefield)
    {
        PBattlefield->RemoveEntity(this, BATTLEFIELD_LEAVE_CODE_WARPDC);
    }
}
```

and now we get this crash:

![image](https://github.com/LandSandBoat/server/assets/131182600/1ff8859c-509f-4048-a8d3-85d02eebdc5a)

looks like this new code is implicated:

![image](https://github.com/LandSandBoat/server/assets/131182600/8d4fd04e-dd5c-4897-83f8-7fccd3f4e2ec)

**Comment by MowFord** [comment]
does it within the same cluster, too

**Comment by WinterSolstice8** [comment]
apply this patch for now. The parent class is doing cleanup, rendering the child classes cleanup unnecessary.

I'm running a valgrind check to make sure instances have no other leaks, but it takes forever for that to start specifically when using valgrind
```diff
diff --git a/src/map/instance.cpp b/src/map/instance.cpp
index b70b3df009..1490003b88 100644
--- a/src/map/instance.cpp
+++ b/src/map/instance.cpp
@@ -41,25 +41,7 @@ CInstance::CInstance(CZone* zone, uint16 instanceid)
     m_wipeTimer = m_startTime;
 }
 
-CInstance::~CInstance()
-{
-    for (auto entity : m_mobList)
-    {
-        destroy(entity.second);
-    }
-    for (auto entity : m_npcList)
-    {
-        destroy(entity.second);
-    }
-    for (auto entity : m_petList)
-    {
-        destroy(entity.second);
-    }
-    for (auto entity : m_trustList)
-    {
-        destroy(entity.second);
-    }
-}
+CInstance::~CInstance() = default;
 
 uint16 CInstance::GetID() const
 {
```

**Comment by WinterSolstice8** [comment]
There was nothing in valgrind, so PR soon
