### ISSUE TITLE
🐛 Server Crash on Casting Maiden's Virelai on Charmed Player

### ISSUE THREAD

**Issue by HaxPrime** [DerpyProjectGroup/topaz#5268]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11
## Branch affected by issue 

`base`

## Steps to reproduce
- Get a player character charmed
- Cast "Maiden's Virelai" on the charmed player
![Screenshot 2024-03-16 161947](https://github.com/LandSandBoat/server/assets/108164867/a44cc85a-0e4f-4907-bf8e-84beee514ac7)
![Screenshot 2024-03-16 163022](https://github.com/LandSandBoat/server/assets/108164867/8253776a-ef34-4963-a465-561422640b03)
![Screenshot 2024-03-16 163551](https://github.com/LandSandBoat/server/assets/108164867/ff3da8fa-92e7-46fe-ad9f-d69fa8080e48)
Dump provided in a zip.
https://cdn.discordapp.com/attachments/1093630937138466948/1218705509704663113/m_virelai.zip?ex=6608a2f3&is=65f62df3&hm=97544bd5f186d4af238ad107d92dde11dd8a4425425ce35afeb65f1f58013383&

## Expected behavior
xi_map should not crash from this.

**Comment by TeoTwawki** [comment]
a yeah, charming an already charmed person basically. oops.

**Comment by TeoTwawki** [comment]
we'll also want the resulting situation in the pathfinding to not be possible. Double bug.

**Comment by TeoTwawki** [comment]
@HaxPrime can you give #5270 a whirl and see if it prevents the crash? without the other pr referenced that prevents casting virelai it'll possibly get some non retail behavior (can't say for sure), but you need to not have that in order to test the crash

**Comment by TeoTwawki** [comment]
*whirl

**Comment by HaxPrime** [comment]
> @HaxPrime can you give #5270 a whirl and see if it prevents the crash? without the other pr referenced that prevents casting virelai it'll possibly get some non retail behavior (can't say for sure), but you need to not have that in order to test the crash

Thanks for the quick fixes. Yes running only #5270 prevents the crash. I was able to cast Maiden's Virelai on the charmed player one time. Further attempts gave the "You cannot attack that target." message. 
![image](https://github.com/LandSandBoat/server/assets/108164867/6f11a70d-d5a1-44df-a0b0-201f13488c2c)

**Comment by TeoTwawki** [comment]
thanks 👍
