### ISSUE TITLE
🐛 Automaton counter attack

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5276]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

[This commit](https://github.com/CatsAndBoats/catseyexi/commit/cb71129b272bab98c00c6c45e7580f4cbda6b75e) moved pdif calc to lua, which takes the skill type as a param. I'm curious if there's evidence that automatons use h2h skill explicitly, use a normalized skill for their level, or just simply use `automaton_melee` as the skill for a counter attack.

Currently, since the change, automatons do 1/4 or less of the dmg compared to their normal autoattacks (due to have zero h2h skill i'm sure)

I don't mind making the PR, just wanted to probe about what suggested route there is

**Comment by MowFord** [comment]
as monk with no weapon: 
![image](https://github.com/LandSandBoat/server/assets/131182600/01e62ba8-e746-4d4a-bef9-eba568399561)

as sam with hagun:
![image](https://github.com/LandSandBoat/server/assets/131182600/9463e697-280d-42f2-8463-80ff17933bd6)

**Comment by WinterSolstice8** [comment]
Sorry, missed this issue altogether (work was insane that whole week)

This was an oversight, they should pick the appropriate skill, I'm currently out right now so hopefully I can remember to check this

**Comment by MowFord** [comment]
i am close to a solution, PR incoming
