### ISSUE TITLE
[chore][ci] Startup checks for Windows

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#528]
We have full startup checks for Linux, but not for Windows. Probably a very useful thing to have!

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by claywar** [comment]
Full Windows startup implemented, closing this issue.
