### ISSUE TITLE
🐛 Wyvern missing "readies <> breath" message

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5284]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Summon a wyvern with /rdm, set yourself to hp 1, then case cure. Wyvern will use healing breath but not give a message that it readies the move.

I believe the issue is due to the [refactor here](https://github.com/LandSandBoat/server/commit/0d2b832545099fb997b9ad35fab37c9746127899#diff-6dcde025b8fa98ca89763e9b486dc838aecdd160dbe4d7a3871be5d6d7c91089), but I messed with various flow, recompiled, and couldn't get the ready message back.

I ended up doing a workaround with a simple module, but am interested in getting it fixed here.

```
local m = Module:new("wyvern_adjustments")


m:addOverride("xi.pets.wyvern.onMobSpawn", function(mob)
    mob:addListener("ABILITY_START", "start", function(wyvern, ability)
        wyvern:injectActionPacket(
            wyvern:getID(),
            xi.action.WEAPONSKILL_START,
            121,
            0,
            xi.reaction.HIT + xi.reaction.ABILITY,
            326,
            0,
            ability:getID()
        )
    end)

    super(mob)
end)

return m
```

**Comment by WinterSolstice8** [comment]
Looks like CanUseAbility is returning false because the initial target is nullptr and it gets one later for some reason. That's actually kind of interesting. That's almost certainly a bug that wasn't noticed until now.
