### ISSUE TITLE
Revert Linux build instructions on wiki page --> Server Setup and Maintenance [Linux]

### ISSUE THREAD

**Issue by Kietsu3756** [DerpyProjectGroup/topaz#533]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch:
   -  https://github.com/LandSandBoat/server/wiki/Server-Setup-and-Maintenance-%5BLinux%5D/_history
      - Revert commit  b8d42f2

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The latest change to the wiki page "Server Setup and Maintenance [Linux]" scatters the build artifacts across the project (example of artifacts at the very end).  Are wiki changes  reviewed and approved?
![image](https://user-images.githubusercontent.com/8081092/126877473-2726ae77-c28d-456a-9249-9e18a78e466e.png)

The commands in the previous version should be used so that most of the artifacts are in the /build folder, otherwise an additional .gitignore need to be added for ...

![image](https://user-images.githubusercontent.com/8081092/126877658-22958534-6459-4f50-a421-d83cf547333f.png)

If some someone has already ran the newer commands, they need to clean/remove all the artifacts mentioned below to use the original commands.

~/server$ git clean -dfxn
Would remove CMakeCache.txt
Would remove CMakeFiles/
Would remove Makefile
Would remove ext/CMakeFiles/
Would remove ext/Makefile
Would remove ext/cmake_install.cmake
Would remove ext/detour/CMakeFiles/
Would remove ext/detour/Makefile
Would remove ext/detour/cmake_install.cmake
Would remove ext/detour/libdetour.a
Would remove ext/filewatch/CMakeFiles/
Would remove ext/filewatch/Makefile
Would remove ext/filewatch/cmake_install.cmake
Would remove ext/fmt/CMakeFiles/
Would remove ext/fmt/Makefile
Would remove ext/fmt/cmake_install.cmake
Would remove ext/fmt/libfmt.a
Would remove ext/recast/CMakeFiles/
Would remove ext/recast/Makefile
Would remove ext/recast/cmake_install.cmake
Would remove ext/sol/CMakeFiles/
Would remove ext/sol/Makefile
Would remove ext/sol/cmake_install.cmake
...
Would remove src/CMakeFiles/
Would remove src/Makefile
Would remove src/cmake_install.cmake
Would remove src/common/CMakeFiles/
Would remove src/common/Makefile
Would remove src/common/cmake_install.cmake
Would remove src/common/libcommon.a
Would remove src/login/CMakeFiles/
Would remove src/login/Makefile
Would remove src/login/cmake_install.cmake
Would remove src/map/CMakeFiles/
Would remove src/map/Makefile
Would remove src/map/ai/CMakeFiles/
Would remove src/map/ai/Makefile
Would remove src/map/ai/cmake_install.cmake
Would remove src/map/ai/controllers/CMakeFiles/
Would remove src/map/ai/controllers/Makefile
Would remove src/map/ai/controllers/cmake_install.cmake
Would remove src/map/ai/controllers/libai_controllers.a
Would remove src/map/ai/helpers/CMakeFiles/
Would remove src/map/ai/helpers/Makefile
Would remove src/map/ai/helpers/cmake_install.cmake
Would remove src/map/ai/helpers/libai_helpers.a
Would remove src/map/ai/libai.a
Would remove src/map/ai/states/CMakeFiles/
Would remove src/map/ai/states/Makefile
Would remove src/map/ai/states/cmake_install.cmake
Would remove src/map/ai/states/libai_states.a
Would remove src/map/cmake_install.cmake
Would remove src/map/entities/CMakeFiles/
Would remove src/map/entities/Makefile
Would remove src/map/entities/cmake_install.cmake
Would remove src/map/entities/libentities.a
Would remove src/map/items/CMakeFiles/
Would remove src/map/items/Makefile
Would remove src/map/items/cmake_install.cmake
Would remove src/map/items/libitems.a
Would remove src/map/lua/CMakeFiles/
Would remove src/map/lua/Makefile
Would remove src/map/lua/cmake_install.cmake
Would remove src/map/lua/liblua_bindings.a
Would remove src/map/packets/CMakeFiles/
Would remove src/map/packets/Makefile
Would remove src/map/packets/cmake_install.cmake
Would remove src/map/packets/libpackets.a
Would remove src/map/utils/CMakeFiles/
Would remove src/map/utils/Makefile
Would remove src/map/utils/cmake_install.cmake
Would remove src/map/utils/libutils.a
Would remove src/search/CMakeFiles/
Would remove src/search/Makefile
Would remove src/search/cmake_install.cmake
Would remove src/search/packets/CMakeFiles/
Would remove src/search/packets/Makefile
Would remove src/search/packets/cmake_install.cmake
Would remove src/search/packets/libsearch_packets.a

**Comment by zach2good** [comment]
It appears our hooks for updates to the wiki (and general tracking of changes) are a bit broken, and some changes have gone under the radar.

Yeah, those changes to the instructions for cmake are _beyond wrong_. As is the standard for most development, we use "out-of-source" builds so the main tree isn't polluted, since we use the main tree during runtime for configs, navmeshes and scripts etc.

The build _automatically_ places the final executables (for both Windows and Linux) in the root, those are the only artefacts that will make it out of the build directory, provided the build directory is separate from the main tree.

@beneliezer - please don't mess with instructions you don't understand. We're going to undo those changes and lock the wiki now.

**Comment by claywar** [comment]
Changes reverted, previous page updated to reference "server" as base dir, as opposed to "topaz"

**Comment by zach2good** [comment]
Thanks @Kietsu3756 for finding this 🙏
