### ISSUE TITLE
🐛 Module says not applied in console but does apply.

### ISSUE THREAD

**Issue by hookstar** [DerpyProjectGroup/topaz#5339]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
WIN 11

## Branch affected by issue 
base

## Steps to reproduce
Created a custom module. On server start, right before garbage collect, it spits out Module not applied. However, going through the function, it does apply without issue. I believe the issue may reside in 
                auto lastTable = override.nameParts.size() < 2 ? firstElem : *(override.nameParts.end() - 2);

m:addOverride("xi.zones.Balgas_Dais.bcnms.rank_2_mission.onBattlefieldLeave", function(player, battlefield, leavecode)

## Expected behavior
Not to spit out error when the override is actually applied.

**Comment by WinterSolstice8** [comment]
this appears to be because bcnms in zones aren't loaded at startup, but when they are loaded the override applies, so the message is a false negative

**Comment by hookstar** [comment]
Thank you - makes sense.
