### ISSUE TITLE
🐛 Server Crash upon New Char Create

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#5342]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

With the newest update from the game. When creating a new char and attempt log in after picking starting area, server will crash. Char does save in the Database, When attempt log in again after selecting that char server will crash again. Can log into the Char on Older update just fine and no issues. I have tested this on Two different Window PC's with both updated on latest. I can log in on my main Char on the newest update fine without a server crash, it's just for anyone that is new to the server.

## Expected behavior

Not have the server crash upon logging in a new created char.

**Comment by Mortalelite** [comment]
Just wanted to update. I tested by disable starter CS and still crashed.

**Comment by Mortalelite** [comment]
[xi_map.exe_4-4_17-54-50.log](https://github.com/LandSandBoat/server/files/14877671/xi_map.exe_4-4_17-54-50.log)
Crash Log

**Comment by UmeboshiXI** [comment]
Can confirm, also does it for me as well.

**Comment by ampitere** [comment]
Also occurring for me on a fresh build/install on latest.

**Comment by WinterSolstice8** [comment]
Can you try this patch? my setup is in some super jank state where I can't easily undo my db edits (some fields are gone/changed)

```diff
diff --git a/src/common/database.h b/src/common/database.h
index d00b320701..f0117823ea 100644
--- a/src/common/database.h
+++ b/src/common/database.h
@@ -270,9 +270,12 @@ namespace db
 
         TracyZoneScoped;
 
-        auto blobStr = rset->getString(blobKey.c_str());
-        std::memset(&destination, 0x00, sizeof(T));
-        std::memcpy(&destination, blobStr.c_str(), sizeof(T));
+        if (!rset->isNull(blobKey.c_str())) // This can do very bad things if the blob is NULL.
+        {
+            auto blobStr = rset->getString(blobKey.c_str());
+            std::memset(&destination, 0x00, sizeof(T));
+            std::memcpy(&destination, blobStr.c_str(), sizeof(T));
+        }
     }
 
     // @brief Execute a query with the given query string.
```

**Comment by UmeboshiXI** [comment]
Just tested, the patch allowed me to log into a new char without crashing map.exe. Anything else you want me to try out/test?

**Comment by WinterSolstice8** [comment]
Nah that's good enough, thanks
