### ISSUE TITLE
🐛 [CPP] crash on uninitialized main weapon during attack round

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5380]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

If you log into a char with no weapons equipped and engage with a target. The map server will crash due to this code attempting to index outside of the array

![image](https://github.com/LandSandBoat/server/assets/131182600/333b82c2-8c2a-4810-a77a-05bb1ebdcfe4)

That added code will block the crash, but then your attack round will have no swings.

If you equip a weapon, then unequip it, the h2h round will work like normal. I believe this is related to a change last month here:

![image](https://github.com/LandSandBoat/server/assets/131182600/9fd94c90-521f-4235-baac-a47d65ea35f4)

It appears that weapons are not initialized for players properly. I'm not positive but i'd suspect SLOT_MAIN is the only one that needs to be handle separately, as ranged attacks will check for an actual weapon, as well as shield blocks.

**Comment by WinterSolstice8** [comment]
Those weapons are intentionally not initialized because if you do, that leaks.

The system normally borrows global pointers and doesn't use new/delete, the old code was "new" and the pointer got overridden when you equipped a new weapon (but not deleted)

Probably what we need to do is use the global pointer for unarmed -- call charutils::CheckUnarmedWeapon() in CCharEntity constructor (or at least replicate the logic)

**Comment by WinterSolstice8** [comment]
Just had a quick thought, probably the `charutils::CheckUnarmedWeapon()` should be done after/during char load because the constructor doesn't know what their skill is yet

**Comment by MowFord** [comment]
Right, I didn't mean to imply the change to the entity init was wrong, but yes whatever thing initializes an empty h2h weapon has a race condition with a freshly-loaded char.

I'm not familiar enough to confidently fix this flow.

Edit: I'm not a coder, sorry if I mislabeled it

**Comment by WinterSolstice8** [comment]
this is not a race condition
