### ISSUE TITLE
🐛 Delivery box failing to find charid when preparing to send

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5399]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

When attempting to load an item into the send dbox, you get this error in the client:

![image](https://github.com/LandSandBoat/server/assets/131182600/6701f7c3-d14a-4f9e-a69e-7898ae95d004)

and this error in the log:

![image](https://github.com/LandSandBoat/server/assets/131182600/31e8553f-dd50-47ba-aa7c-1d8918315d5e)

All other references to db::preparedStatement seem to only use numbers in the arg list, not sure if maybe that's the issue? I'll attempt to fix later if nobody comes up with a solution

**Comment by zach2good** [comment]
Presumably caused by this: https://github.com/LandSandBoat/server/issues/5329

**Comment by zach2good** [comment]
```cpp
                auto senderName = str(data[0x10]);

                auto rset = db::preparedStmt("SELECT charid, accid FROM chars WHERE charname = '?' LIMIT 1", senderName);
                if (rset && rset->rowsCount() && rset->next())
                {
```

Similar, roll this back to be `db::query` with `fmt::format`, or whatever the original was. `db::preparedStatement` doesn't seem to encode strings in general

**Comment by zach2good** [comment]
This is the binding code, if you're interested in tinkering: https://github.com/LandSandBoat/server/blob/base/src/common/database.h#L61-L122
