### ISSUE TITLE
Conditional movement speed gear is non-functional

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#5402]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Equip nation Aketon in the appropriate nation, or equip NIN AF boots at the appropriate time (night). No movement speed bonus has been granted, verified by addons. Non-conditional movement speed gear works as expected, and the boost is recognized by the same addons.

## Expected behavior

Conditional movement speed gear should grant the modifier when the condition is met.

**Comment by Xaver-DaRed** [comment]
This is known.
Issue #4766

**Comment by almuth150** [comment]
Ah crap, I searched "movement" and did not see that, because it does not contain that world. Closing.
