### ISSUE TITLE
🐛 Rapid Shot procs do not reduce the total delay to initiate the next ranged attack

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#5404]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Set job to have Rapid Shot trait (from RNG or COR), setup a simple script to fire two+ consecutive ranged attacks with a static amount of time between them, such that a Rapid Shot proc would reduce the wait time between them below the total delay (defined as the sum of pre-shot and post-shot delays). When Rapid Shot procs, you still have to wait the full pre-calculated total delay, despite the pre-shot delay being reduced (ie. Rapid Shot procs reduce the pre-shot delay, but increases the post-shot delay by the same amount to maintain the same total delay).

Example, using a 360 delay bow and 120 delay arrow, without any source of static ranged delay reduction (ie. snapshot and velocity shot), with the following script (for Windower).
> input /ra <t>
> wait 5.3
> input /ra <t>

You may need to adjust the wait time due to latency, but 5.3s was sufficient to reliably be too quick to initiate the next ranged attack every time, 5.4s was most of the time, and 5.5s always started the next ranged attack.

## Expected behavior

Rapid Shot procs should reduce the total delay between shots by the amount that the pre-shot delay was reduced by. ie. when Rapid Shot procs, you should be able to initiate the next ranged attack sooner than if it did not proc.

**Comment by MowFord** [comment]
I've tested this a lot recently!

rapid shot trait/mod gives a chance to reduce the ranged delay by a random amount. In my testing it worked the way it should. 

![image](https://github.com/LandSandBoat/server/assets/131182600/d08d2167-25af-4942-b3e9-7acc928e0232)

Furthermore, the ranged state is broken into 3 phases, aimdelay at the bottom of this screenshot is phase 1, but there's a static phase 2 and phase 3 that are _definitely unaffected_ by ranged delay reductions/rapid shot specifically

**Comment by almuth150** [comment]
I believe the issue comes from further down actually https://github.com/LandSandBoat/server/blob/base/src/map/ai/states/range_state.cpp#L228

![image](https://github.com/LandSandBoat/server/assets/69948957/cd2d7aae-fb9f-40cf-92fb-a14b4dde4135)

When I automate ranged attacks to initiate the next one a fixed amount of time after the previous one completes (which is at the end of phase 2 I believe?) ie. using the Windower addon autoRA, whenever Rapid Shot procs, my next RA fails because it was too soon, where it does not fail when it does not proc. If I were to guess, shouldn't it be updating the time for the later phases by subtracting the delay that Rapid Shot reduced the aim time?

**Comment by MowFord** [comment]
It should, and in my testing did, do what you expect

`m_LastRangedAttackTime` is only updated when a ranged attack state ends, which is adjusted based on aim time.

`m_freePhaseTime` is the phase 3, static delay of 1.1s.

Looks like AutoRA uses a [manually-defined delay](https://github.com/Windower/Lua/blob/4c0ddf45ecafae0b3ef93d8272336a8b1242c02a/addons/AutoRA/AutoRA.lua#L10) which is based on the [previous ranged end packet](https://github.com/Windower/Lua/blob/4c0ddf45ecafae0b3ef93d8272336a8b1242c02a/addons/AutoRA/AutoRA.lua#L66)?

This means you should not be adjusting the Delay value in the addon at all. It should get the finish packet sooner, and still wait 1.5s (1.1s in lsb code, to be precise)

**Comment by almuth150** [comment]
I had to manually increase the delay due to that other bug you found here https://github.com/LandSandBoat/server/pull/5411 but otherwise it works fine as long as Rapid Shot does not proc (ie. was tested on a job without the trait and it did not fail under normal conditions). I'm not quite sure what's going on here that's causing it to fail in that situation specifically.

**Comment by MowFord** [comment]
now i'm intrigued, will test a bit with 100% rapid shot

**Comment by MowFord** [comment]
Seems to function as expected. Curious how your addon behaves with a simpler test: `!setmod ranged_delayp -99`

**Comment by almuth150** [comment]
Okay, after finally getting around to building my own test server instead of relying on someone else's stuff, I was able to determine that this is not, in fact, an issue. Although, I do wonder why the time to initiate the next RA seems to be... "off". I occasionally get the "too soon" message and fail to initiate, and while it felt like it happens more often when Rapid Shot procs, it's not actually happening each time.

I don't know, it feels like there's something going on when automated timing fails on occasion, even locally, but if it's not Rapid Shot, I can't figure it out. I will close this, however, because it's not right, and if I ever uncover anything that points to the actual issue, I will go from there.
