### ISSUE TITLE
Area for quest Transformations unaccesable

### ISSUE THREAD

**Issue by Tarsakh** [DerpyProjectGroup/topaz#543]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

On Canaria server i was trying to do the AF quest for Blue mage "Transformations". Im on the last part where i need to get to the small area of Alzadaal Undersea Ruins via Caedarva Mire. What i can find there is two ways to go east or west of Nashmau.
Both ways needs to talk to a NPC and give a Silver imperial piece to enter. But... I have now tried both of them but the CS that should trigger the NPC moveing away and letting you in is not triggering correcly. The NPC is gone in the CS and so he never moves leaveing you stareing blindly into the cave forever. 
To be able to move you have to force quit the game but once you re enter you are stuck outside anyway with minus the silver piece. 
The NPC are Nasheefa and Tyamah. But if you just look at them they are called instead Runic Seal and Big Iron Gate.  
![image](https://user-images.githubusercontent.com/7287550/127041085-fdbd944f-1109-4581-b4e8-3750ce273871.png)
![image](https://user-images.githubusercontent.com/7287550/127041113-1e6288dc-4be4-45d8-b2ca-084c6ac5ba17.png)

**Comment by nieminin** [comment]
I can confirm this, happened today to myself .
