### ISSUE TITLE
San d'Oria mission 2-1 Vicorpasse not work

### ISSUE THREAD

**Issue by tourmaline3333** [DerpyProjectGroup/topaz#545]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- x[ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I start San d'Oria mission 2-1.
but Vicorpasse tell normal dialog.
Vicorpasse.lua has no especialy script.
I played this mission when dark star project.

this mission do not program on landsandboat yet?

**Comment by tourmaline3333** [comment]
I start San d'Oria mission 2-1.
but Vicorpasse tell normal dialog.
Vicorpasse.lua has no especialy script.
I played this mission when dark star project.

this mission do not program on landsandboat yet?

**Comment by claywar** [comment]
Hello @tourmaline3333, Vicorpass scripting for M2-1 is located in `scripts/missions/sandoria/2_1_The_Rescue_Drill.lua`  BR!

**Comment by tourmaline3333** [comment]
Thank you for your help.
but my issue do not resolve....

I told Yaucevouchat and Galaihaurat. but it's not change.
Please tell me the solution.

**Comment by tourmaline3333** [comment]
1, I told the Guards, and start mission
2, I warped from north Sandoria to Ordelle's Caves
3, I Speak Ruillont.but normal dialog
4, I speak Vicorpass  but normal dialog
5, I speak Yaucevouchat and Galaihaurat and more, but not change..

**Comment by tourmaline3333** [comment]
Sorry, I resolved myself.
6, I speak Equesobillot -> Deaufrain -> vicorpass

**Comment by claywar** [comment]
Could you please use the command `!checkmissionstatus`?  There is a lot of different status, and would like to see where you are in current progress.

**Comment by tourmaline3333** [comment]
Thank you for good command.I will have same progress I try it.

**Comment by lostinspiration** [comment]
I happened to run across this as well. Turns out `!checkmissionstatus` returned a 5ish digit number and I had to reset it. Not sure how it ended up in that state. In searching through the lua for the mission, I noticed that on line [195](https://github.com/LandSandBoat/server/blob/623da64777d09d1ad8384a96043bd8f7c69a9850/scripts/missions/sandoria/2_1_The_Rescue_Drill.lua#L195) it has 
```lua
player:getMissionStatus(player:getNation())
```
instead of 
```lua
player:getMissionStatus(mission.areaId)
``` 
like the rest of the branches. Is this intended or a typo?

**Comment by claywar** [comment]
Assuming you didn't force the adding of the mission, that shouldn't have an impact (though mission.areaId would be cleaner).  Those _should_ be the same from a normal player's perspective, as that mission can only be flagged if their nation is San d'Oria

**Comment by claywar** [comment]
Closing this issue.  If it occurs in the future, please reopen.
