### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#5461]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

**Comment by TeoTwawki** [comment]
how the hell did I fire a blank

**Comment by mogulbgod** [comment]
Happens when you get older.

**Comment by TeoTwawki** [comment]
![](https://media.tenor.com/uPJP8cZDVGcAAAAM/wile-coyote.gif)
