### ISSUE TITLE
Does not support the encoding of other file names?

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#549]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

when Server is runing then i try copy command dir's file to command new file's name has chinese's name then Server will stop !
![image](https://user-images.githubusercontent.com/61591648/127422714-4e6b59cc-f37e-433a-9d9a-6f9f944cc1c1.png)
![image](https://user-images.githubusercontent.com/61591648/127422767-a71bdc93-c235-4b9b-8950-61e4f5dc778a.png)

**Comment by claywar** [comment]
Several discussions and issue raised around this, but unfortunately we do not support wchar in filesystem
