### ISSUE TITLE
🐛 < All Crude Arrows Wrong item ID>

### ISSUE THREAD

**Issue by zDeadHeadFredz** [DerpyProjectGroup/topaz#5513]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Expected behavior

Change value Crude Arrow +5 from 993 to 18186 
crude arrow  18181
crude arrow +1 18182
crude arrow +2 18183
crude arrow +3 18184
crude arrow +4 18185
crude arrow +5 18186
crude arrow +6 18187
crude arrow +7 18188

all these values were wrong in sql when i looked them up in AH also some of them were duplicated ID's. just a small thing but i thought i would mention it.

**Comment by zDeadHeadFredz** [comment]
hmm ok seems even the AH has duplicate item IDS for other items like automaton oil +3 uhhh idk what magic you guys work, but can someone explain how an arrow and automaton oil have the same ids and function cuase i wanted to change a few variables to my liking but heidi doesn't like duplicate ids

**Comment by Xaver-DaRed** [comment]
Not an issue anyway, I dont know where you were looking at.

Item ID 993
![imagen](https://github.com/LandSandBoat/server/assets/60053999/4c5c9c2f-3d1d-400b-96e7-c89625b6fd44)

Those arrows
![imagen](https://github.com/LandSandBoat/server/assets/60053999/a8b4a8af-e50f-41ac-9385-7cc882709aff)

**Comment by zDeadHeadFredz** [comment]
yea I closed it because I figured it out.
