### ISSUE TITLE
TOAU Mission 1 Cutscene messed up

### ISSUE THREAD

**Issue by Endymionls** [DerpyProjectGroup/topaz#553]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When approaching the trigger for Mission 1, character freezes, but cutscene doesn't start. First time, the client crashed. Logging back in, character froze after a few seconds. After a few minutes, received key item Supplies Package without any cutscene, and character moved again.

**Comment by helixhamin** [comment]
Yes, I had the same issue when I tried.
