### ISSUE TITLE
Downward Helix Does Not Give Key Item Ulbrecht’s Mortarboard

### ISSUE THREAD

**Issue by Era-Lusiphur** [DerpyProjectGroup/topaz#554]
Just a note for whoever converts the SCH quest Downward Helix or if a player is confused beforehand, the Indescript Markings in Sauromugue Champaign (S) are supposed to give the player the key item **Ulbrecht's Mortarboard** after the cutscene. Currently, they do not. However, the following NPC Erlene doesn't require them, so players are capable of continuing and finishing the quest. It can just lead to some confusion. 

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Any

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by claywar** [comment]
Fixed by #3725
