### ISSUE TITLE
🐛 Spell interrupt/Spell intterupt reduction is just wrong

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#5540]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

The formula for spell interrupt, and application of SIRD is wrong. I believe the formula would be novel research (unsure about obscure JP blogs) but it is known 102% SIRD results in never getting interrupted period (outside of being moved)

**Comment by Xaver-DaRed** [comment]
This was adressed the best we could in PR #5601
