### ISSUE TITLE
🔨 Implement attacking-closest-available-target for Bind

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#5541]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

See description, bind AI doesnt match retail. The bound mob should target/rotate towards the closest available target and melee things that aren't necessarily the highest on their hate list

**Comment by zach2good** [comment]
Will this use the hate list and then sort by distance? Or is it all possible targets sorted by distance? If it's the latter we'll need spatial partitioning
