### ISSUE TITLE
🔨 Implement supertanking

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#5542]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

Supertanking doesn't exist currently because any aggro adds to the hate list WITH initial hate (this is wrong, an actual aggressive action needs to be taken)

**Comment by cocosolos** [comment]
Isn't this what the `active` bool is for on the enmity object? I swear this used to work.

**Comment by WinterSolstice8** [comment]
> Isn't this what the `active` bool is for on the enmity object? I swear this used to work.

That may be something related to being on the enmity list after logout? Not 100% sure. We do have a way to determine an "aggressive" action after the TH rewrite I did.

I think the real solution here is to make a mob fight its aggroed target but not yet put them on the enmity list because they don't belong there (not yet, at least)
