### ISSUE TITLE
Trusts the same trust will be broke

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#556]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by zanglikun** [comment]
over max trust will be broke too

**Comment by zach2good** [comment]
Sorry, I don't understand what you mean here, can you upload a screenshot of what's wrong?

**Comment by zanglikun** [comment]
![image](https://user-images.githubusercontent.com/61591648/127763504-b0a7b1e6-fb64-49ef-8af6-7c85fd0dac97.png)

**Comment by zanglikun** [comment]
It seems that SMN work is not OK
i'M the new code in base branch

**Comment by zach2good** [comment]
This is intended:
https://ffxiclopedia.fandom.com/wiki/Category:Trust
```
You can only summon one copy of each Alter Ego. This includes when one character has multiple versions (e.g. summoning Zeid II prevents summoning Zeid).
```

If you wanted to customise your server, you could modify this block to allow copies of the same trust:
https://github.com/LandSandBoat/server/blob/base/scripts/globals/trust.lua#L267-L296

Changing `return -1` to `-- return -1`

**Comment by zanglikun** [comment]
i know this code 。It seem do‘t work  I'll pull it again and test it again later
