### ISSUE TITLE
Pickaxes not working?

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#557]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: 
Everything Branch (Canaria)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Canaria, running Everything branch.
Client version 30210706_0

Running through Korroloka for the geomagnetic fount (unlocking SOA access).  Could not use pickaxe at two excavation points along the way.  Escaped to Zeruhn and the same thing happened there as well.

Excavation points respond that you can mine with a pickaxe when you interact with them, but when you try to use one on them they do not respond at all.  The "swishing" sound effect fires off, but no animation or anything else happens after that noise.

**Comment by TeoTwawki** [comment]
you sure its not a npcID/textID/versioning issue on those?

I mean, we aren't full on set for the new version despite that last PR for the text IDs. a few iffy spots in regard to the NPCs still.

**Comment by zach2good** [comment]
Could this be me? I wonder if my amk changes broke more things 👀
