### ISSUE TITLE
🐛 BCNM not cleaning up armoury crates in some cases

### ISSUE THREAD

**Issue by ampitere** [DerpyProjectGroup/topaz#5577]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. Enter a BCNM that has multiple available options
2. Beat the BCNM and get a reward from the armoury crate
3. Enter a different BCNM in the same area
4. Beat the BCNM and get a reward from the armoury crate
5. Enter the first BCNM again (might work for any in the same area) and the armoury crate will still be there

Tested with Balga's Dais in Wild Wild Whiskers and Divine Punishers.

![image](https://github.com/LandSandBoat/server/assets/166072302/45a74f7b-c55c-4c52-8ae8-9d873168598a)
![image](https://github.com/LandSandBoat/server/assets/166072302/d28a36a6-3853-40d3-b088-c4da1c4915c5)
![image](https://github.com/LandSandBoat/server/assets/166072302/d254da68-2b47-47bc-99ec-d2dd34819a72)

## Expected behavior

The armoury crate should not appear when entering a fresh BCNM even if you've already beaten one in the area.

**Comment by claywar** [comment]
The linked PR _might_ fix this, but I was unable to reproduce the issue on base by entering the same battlefield area in Balga's back to back

**Comment by ampitere** [comment]
Were you trying different BCNMs? It seems to only occur if you do one then a different one. I tested your change locally and it doesn't seem to be happening anymore! So should be good to go.

**Comment by claywar** [comment]
That's good news.  But yeah, I went from Wild Wild Whiskers to Divine Punishers without seeing it occur (opposite order, but mimicking the screenshots provided)
