### ISSUE TITLE
🐛 ERROR on update

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#5579]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows11

## Branch affected by issue 

`base`

Performing update today, got this error (never happened before):

cd tools
py -3 dbtool.py update

Traceback (most recent call last):
  File "C:\server\tools\dbtool.py", line 1322, in <module>
    main()
  File "C:\server\tools\dbtool.py", line 1219, in main
    fetch_credentials()
  File "C:\server\tools\dbtool.py", line 283, in fetch_credentials
    port = int(os.getenv("XI_NETWORK_SQL_PORT")) or int(settings["network"]["SQL_PORT"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by zach2good** [comment]
Related to https://github.com/LandSandBoat/server/pull/5574

**Comment by zach2good** [comment]
I've just tested it, fix is this:

```py
    port = int(os.getenv("XI_NETWORK_SQL_PORT")) or int(settings["network"]["SQL_PORT"])
```

to
```py
    port = int(os.getenv("XI_NETWORK_SQL_PORT") or int(settings["network"]["SQL_PORT"]))
```

I'm just about to go to bed, someone please pick this up.
