### ISSUE TITLE
Hunger Strikes does not complete, can keep trading soup for rewards

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#558]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything Branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Canaria, Everything Branch
client version 30210706_1

Westerly Breeze (Western Adoulin NPC) appears to be scripted for the quest series starting with Hunger Strikes, but that first quest does not get flagged as complete to move on to The Starving.

A side effect of this is that you can continue trading him the soup to get the EXP/LP and Bayld rewards over and over.

**Comment by claywar** [comment]
Fixed by #1712
