### ISSUE TITLE
🐛 Opening dbtool.py throws an error

### ISSUE THREAD

**Issue by ampitere** [DerpyProjectGroup/topaz#5586]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. Attempt to open the dbtool.py

```
C:\Users\Ampitere\Downloads\LSB\server\tools>dbtool.py
Traceback (most recent call last):
  File "C:\Users\Ampitere\Downloads\LSB\server\tools\dbtool.py", line 1322, in <module>
    main()
  File "C:\Users\Ampitere\Downloads\LSB\server\tools\dbtool.py", line 1219, in main
    fetch_credentials()
  File "C:\Users\Ampitere\Downloads\LSB\server\tools\dbtool.py", line 283, in fetch_credentials
    port = int(os.getenv("XI_NETWORK_SQL_PORT")) or int(settings["network"]["SQL_PORT"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

## Expected behavior

The dbtool.py runs as expected.

**Comment by cocosolos** [comment]
Pull updates then run again, should be fixed by #5580
