### ISSUE TITLE
🐛 Possessives for players are not right

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#5600]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Take an action or have an action taken on you, see that the message is implying more than one entity (like bat trio vs single bat):

![image](https://github.com/LandSandBoat/server/assets/131182600/e175891c-046d-42ab-8a52-fa9834591eea)

![image](https://github.com/LandSandBoat/server/assets/131182600/79193861-81b1-4fc7-b620-3f032b938349)

![image](https://github.com/LandSandBoat/server/assets/131182600/cf99cd31-9308-4d5b-a040-edf9c128730b)

![image](https://github.com/LandSandBoat/server/assets/131182600/fac8d97b-335c-4eb7-a09c-2660f095e43d)

I assume this is related to the char update packet rewrite.

**Comment by MowFord** [comment]
and one more cause it's funny

![image](https://github.com/LandSandBoat/server/assets/131182600/1f41daba-b381-4dec-a84e-597246e1f6b1)

**Comment by WinterSolstice8** [comment]
try playing with these:

https://github.com/LandSandBoat/server/blob/8cae00cb0aaf768c3532d58218727304f20582eb/src/map/packets/char.cpp#L161
https://github.com/LandSandBoat/server/blob/8cae00cb0aaf768c3532d58218727304f20582eb/src/map/packets/char.cpp#L162
https://github.com/LandSandBoat/server/blob/8cae00cb0aaf768c3532d58218727304f20582eb/src/map/packets/char_update.cpp#L293

I probably set some of them wrong when reading a cap

**Comment by WinterSolstice8** [comment]
It's probably ` packet.Flags2.SingleFlag    = 0;     // Player is a singular thing ` in 0x00D fwiw

**Comment by TeoTwawki** [comment]
![image](https://github.com/LandSandBoat/server/assets/131182600/cf99cd31-9308-4d5b-a040-edf9c128730b)

This used to be a bug on retail for like a year and a half before SE finally fixed it. it was never listed a known issue nor listed in any patch notes lol it was before they opened the official forums for the game. My Nostalgia goggles just turned into nostalgia giggles. Teo Is paralyze. Mob are silence. lmao.

**Comment by WinterSolstice8** [comment]
You could probably use this for some char-specific setting to enable some extremely strange roleplay with this too
