### ISSUE TITLE
🐛 Losing !togglegm upon zoning

### ISSUE THREAD

**Issue by Mortalelite** [DerpyProjectGroup/topaz#5636]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10
## Branch affected by issue 

`base`

## Steps to reproduce

When you have `!togglegm` and you zone it will be removed. You are able to toggle it back on, but once zone again it is removed. This happens on current char.

If you create a new char it does stay when you zone. If you toggle off  `!togglegm` and zone it comes back on

## Expected behavior

Keep `!togglegm` upon zoning

**Comment by Mortalelite** [comment]
I found the issue to be within the char_flags.sql

Your current char does not get a flag unless you manually insert a line for it. But if you set `gmModeEnable` to 1 it stays upon zoning.

If you create a new char and it is marked as a GM, then when you toggle it on. It does stay upon zoning, but once toggle off it stays.

You have go into char_flags and change from 1 to 0 to disable `gmModeEndable`

**Comment by WinterSolstice8** [comment]
"manually insert a line" -- can you elaborate further? are there sql errors in map?

**Comment by Mortalelite** [comment]
If you are in the DB and then go to char_flags and right click to insert row and no errors within map.

**Comment by WinterSolstice8** [comment]
It sounds like you didn't run the migration?

https://github.com/LandSandBoat/server/blob/2309bb1dc18f90b561c976ee749bf788b593e78e/tools/migrations/039_refactor_char_settings.py#L61

**Comment by Mortalelite** [comment]
I ran everything suppose to. But even on a new char when you do `!togglegm` and turn it off and zone, it auto keeps at 1 instead turning to 0

**Comment by WinterSolstice8** [comment]
If you had to insert that row that means the migration didn't run, the query above inserts a new row for all pre-existing characters, and new characters get an entry on that table here:

https://github.com/LandSandBoat/server/blob/2309bb1dc18f90b561c976ee749bf788b593e78e/src/login/login_helpers.cpp#L178

**Comment by Mortalelite** [comment]
Well I would not know how it did run when I updated DB with `py -3 dbtool.py update` and did all the migration at that time. So how would I run that then.

**Comment by Mortalelite** [comment]
I ran`py -3 dbtool.py` just incase and here what I got

![Capture](https://github.com/LandSandBoat/server/assets/108362771/dc6754cb-f713-4b30-b325-bad15aa44a9d)

**Comment by WinterSolstice8** [comment]
hmm... that's really weird. I don't have an explanation for why your char_flags wasn't populated then

**Comment by WinterSolstice8** [comment]
You should run this query on your db just in case:
`INSERT INTO char_flags (charid) SELECT charid FROM chars ON DUPLICATE KEY UPDATE char_flags.disconnecting = char_flags.disconnecting;`

**Comment by WinterSolstice8** [comment]
I think I see the bug. it looks like `db.commit()` isn't called in the migration, I missed it. Apparently this could mean the query just didn't execute. I tested this on Linux, which may behave differently. 

Thanks for the report, you 100% should run the above query.

**Comment by Mortalelite** [comment]
I ran the query. Just booting back up the server to test it

**Comment by Mortalelite** [comment]
Ok it is semi working. When you have `!togglegm` on and turn off before zoning. It comes back on

**Comment by WinterSolstice8** [comment]
I'll look into it after I get home from work

**Comment by Mortalelite** [comment]
Ok no worries. Thanks for looking into it. It is something with the `gmModeEnable` staying as 1 instead going to 0. The `gmHiddenEnable` is working like it suppose to within char_flags.

**Comment by WinterSolstice8** [comment]
I did a 5 second check (still on my lunch break)

in `charutils::SaveCharGMLevel()`
try updating
`_sql->Query(Query, "char_flags", "gmModeEnabled =", PChar->m_GMlevel >= 3 ? 1 : 0, PChar->id);`
to
`_sql->Query(Query, "char_flags", "gmModeEnabled =", PChar->visibleGmLevel >= 3 ? 1 : 0, PChar->id);`

**Comment by Mortalelite** [comment]
Ok that is working

**Comment by Mortalelite** [comment]
Should I make a PR for this or wait to see if come up with another fix?
