### ISSUE TITLE
🐛 Battlefield Entrance in Waughroon Shrine (maybe elsewhere) not reliably triggering for all chars

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#5663]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Reproduction steps are not completely clear to me, however I've managed to record a video demonstrating it.
I have two chars on one account, both GM's, one can interact with the BCNM entrance normally while !togglegm,
the other gets no love. No errors in the logs whatsoever.

This is also affecting normal players.

Happening on a completely clean base build.

https://youtu.be/zTOlpJuus_c

## Expected behavior

Any GM character should be able to trigger the BCNM entrance.

**Comment by UmeboshiXI** [comment]
Just had this happen to me on my test server in Balgas Dais.

I am on a modified build (Catching us up to the latest, currently on the commit where Balgas Dais got converted).

I have 2 chars on this account, both GMs. 1 can interact with the burning circle, the other can't (Whether with orb or !togglegm). Seems restarting does not fix it. No log errors.

**Comment by UmeboshiXI** [comment]
Update: Running query seems to have fixed my issue for now. char_flags was not populated in my database.

 `INSERT INTO char_flags (charid) SELECT charid FROM chars ON DUPLICATE KEY UPDATE char_flags.disconnecting = char_flags.disconnecting;`

**Comment by CatsEyeXI** [comment]
Thanks @WinterSolstice8 for coming to the rescue <3
