### ISSUE TITLE
🐛 Cures doesn't affect party members with Majesty or Accession

### ISSUE THREAD

**Issue by ampitere** [DerpyProjectGroup/topaz#5682]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. !changejob 7 99 or !changejob 20 99
2. Summon a trust
3. Use Majesty or Accession
4. Cast Cure

## Expected behavior

Cure should affect party members with Majesty or Accession active.

This is a result of a change made in https://github.com/LandSandBoat/server/pull/5628 inside of `CTargetFind::validEntity(CBattleEntity* PTarget)` on lines 463-468. Since Cure can be used offensively the `TARGET_ENEMY` flag is sent in regardless of the current target. Using a different spell that works with Majesty or Accession such as Protect works as expected.

**Comment by Xaver-DaRed** [comment]
@WinterSolstice8 
Sorry for the tag, but this may interest you

**Comment by WinterSolstice8** [comment]
Edgecase Fantasy 11... will try to fix tonight, no promises, might be tired from work
