### ISSUE TITLE
🐛 Calling GetFirstID() on an invalid entity will crash the map server

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#5684]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
Add an entry to ID.mob.VALUE = GetFirstID('Something that doesn't exist') will throw the map server into a reboot loop (if running as a service).

## Expected behavior
Should likely throw a Lua error and continue running

**Comment by MowFord** [comment]
https://github.com/LandSandBoat/server/issues/5567

![image](https://github.com/LandSandBoat/server/assets/131182600/060631f6-638e-4738-b15e-6478b7583853)
