### ISSUE TITLE
🐛 Fishing - always lose your catch

### ISSUE THREAD

**Issue by ampitere** [DerpyProjectGroup/topaz#5701]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. !setskill fishing 110
2. !additem 17011
3. !additem 17402
4. !zone Port Windurst
5. Attempt to fish (everything is well under your level here)

![image](https://github.com/LandSandBoat/server/assets/166072302/96d7748e-287f-4c41-bca1-04f52a3e1909)

Reverting this change resolves the issue: https://github.com/LandSandBoat/server/pull/5694

## Expected behavior

Fish should be catchable and not always be lost.

**Comment by Xaver-DaRed** [comment]
![imagen](https://github.com/LandSandBoat/server/assets/60053999/e731cc3f-1d7d-4cdd-bb59-b261957b3a92)
