### ISSUE TITLE
🐛 [Promy] Memory Receptacle throwing error on death causing the event not to trigger

### ISSUE THREAD

**Issue by Frankie-hz** [DerpyProjectGroup/topaz#5740]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

`Unknown`

## Branch affected by issue 

`base`

## Steps to reproduce
Hi everyone, I recently encountered this problem doing the promyvion of the cop missions, when I kill the memory replacemente the portal doesn't activate and this appears as an error, I haven't changed anything and everything as I downloaded from the LSB, could anyone help me ? Thank you

```
[05/15/24 12:54:18:176][map][error] luautils::onMobDeath: ./scripts/globals/promyvion.lua:100: attempt to index field 'MEMORY_STREAMS' (a nil value)
stack traceback:
./scripts/globals/promyvion.lua:100: in function 'receptacleOnDeath'
./scripts/zones/Promyvion-Holla/mobs/Memory_Receptacle.lua:16: in function 'fallbackHandler'
.\scripts/globals/interaction/interaction_lookup.lua:400: in function <.\scripts/globals/interaction/interaction_lookup.lua:378> (luautils::OnMobDeath::<lambda_2>::operator ():3486)
```

Issue submitted by @Themaxdelta here: https://github.com/LandSandBoat/server/discussions/5739

Moved it over to an actual bug report.

Looks like there was a forgotten `MEMORY_STREAMS` left in during rework.

## Expected behavior
Kill receptacle and see portal/event/no errors

**Comment by ampitere** [comment]
https://github.com/LandSandBoat/server/pull/5671

Looks like line 100 was missed in this update.

**Comment by Xaver-DaRed** [comment]
the rework is just unfinished. once its done, it will be fixed

**Comment by Themaxdelta** [comment]
ok thanks guys, can I already insert some changes that perhaps were already present in the past to be able to restore it? Thank you

**Comment by ampitere** [comment]
> ok thanks guys, can I already insert some changes that perhaps were already present in the past to be able to restore it? Thank you

You could revert the commit locally temporarily or just tweak line 100 of promyvion.lua to use the new variable name `MEMORY_STREAM_OFFSET`. Not sure what the correct offset is for that though.
