### ISSUE TITLE
🐛 Set bonuses lost on zone

### ISSUE THREAD

**Issue by ampitere** [DerpyProjectGroup/topaz#5741]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. !additem 15852
2. !additem 15853
3. Equip the rings
4. Zone

## Expected behavior

Set bonuses are retained while zoning.

**Comment by ampitere** [comment]
In my research it does look like `CLuaBaseEntity::addGearSetMod` is getting called on zoning and the modifier is added but the player's stats are not displaying this.

![image](https://github.com/LandSandBoat/server/assets/166072302/7cbb77d5-a75e-4c55-b08a-02553f13adf7)
![image](https://github.com/LandSandBoat/server/assets/166072302/61800da8-32e5-424e-84c2-2f171d41a98d)
![image](https://github.com/LandSandBoat/server/assets/166072302/aff6c9ff-5398-4da9-8ea6-dea9d2f85db0)

First is on zone, second is after re-equipping.

**Comment by MowFord** [comment]
change any gear and it seems to fix it 

![image](https://github.com/LandSandBoat/server/assets/131182600/ecbba644-457f-4520-8245-e31a46975d5f)

after the 2nd zone i removed my feet (kept rings up)

So this is just an issue with the setBonus function not recalculating player hp/mp
