### ISSUE TITLE
Mob (bomb) Berserk is extremely weak.

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#577]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
It's set to +/-1% atk/def.

**Comment by ShiyoKozuki** [comment]
Should be 50%, retail testing shows 50-60% on current beastmaster jug pets.
