### ISSUE TITLE
🔨 Request: Quest Progress check for new Battlefield framework.

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#5777]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

There are some quests that have battlefields associated with them but I don't think we currently have a check for quest progression in the newer battlefield system unless I'm missing/overlooked something.

**Comment by claywar** [comment]
Already coming in https://github.com/LandSandBoat/server/tree/interaction/battlefield-cloisters
