### ISSUE TITLE
🐛 Pet Issue - Main job pup / Pet changes to drg pet on zoneing 

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#5779]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
Having issues with gaining exp when dragoon pet and or trust do physical attacks to a target. In the steps to find the issue I changed my job to Pup. Summoned an automation, waited to for the automation to do a physical attack on the target. Received exp from target. Zoned to a city then back to Dho Gates and now my automation is a dragoon pet and I lose all pet commands. 
## Expected behavior

![pup drg](https://github.com/LandSandBoat/server/assets/75862857/b7474c31-3734-44ee-9cf3-d52a93f45bec)

**Comment by WinterSolstice8** [comment]
Zoning on PUP/DRG or DRG/PUP _used_ to do this, but I can't reproduce. I found zoning was causing an automaton to transform into a fire elemental.

https://github.com/LandSandBoat/server/pull/5786
No idea if it's related. Can try patching it and seeing what happens.

**Comment by Xaver-DaRed** [comment]
Is this still an issue?

**Comment by FFXILevelDown** [comment]
I have not experienced this issue anymore
