### ISSUE TITLE
🐛 Movement Speed Latent Effect Broken

### ISSUE THREAD

**Issue by cocosolos** [DerpyProjectGroup/topaz#5810]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Add Destrier Beret:

```
!additem 11811
```

Equip on job under level 31, note unchanged speed.

## Expected behavior

Latent effects should be checked for speed enhancements.

**Comment by Xaver-DaRed** [comment]
https://github.com/LandSandBoat/server/issues/4766

**Comment by cocosolos** [comment]
Ah sorry I looked but didn't see that.
