### ISSUE TITLE
[improvement] Track "Packet Pressure"

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#584]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
We're talking about overloading the client with packets on mega-pulls in dynamis in this discussion: https://github.com/LandSandBoat/server/discussions/583#discussioncomment-1136395

When I was watching the Tracy graphs for CPU, RAM and Lua Memory usage I thought: I wish we could track how many packets are being queue'd up to be sent...

We can!

Inside `send_parse` we can mark down `PChar->getPacketCount();`

**Comment by RAIST5150** [comment]
Would note for research purposes you can replicate the conditions in normal zones as well.

Delkfutt Tower floors have some nice rooms with lots of mobs that can easily be pulled/linked.  Horototo ruins too... forget which mission it was, think it was an ASA fight that led to a room with a few cardians that still aggro at 99 and rounded up lots of cardians.

These areas can quickly bog things down.

**Comment by zach2good** [comment]
Nomenclature:
```
The big "outer" packet: udp-packet, chunk, BigPacket etc.
The "inner" collection of packets: packet, SmallPacket etc.
```

Continuing my investigation, I've defined a basic "Packet fill rate" metric: `(len(character's packet queue) / len(how much of that queue is delivered in a single send round)) * 100`

If packetfill is at 100%, everything works as expected. All updates generated by the server can fit in a single round of sending to the client, and the client can handle this without issue.

The first few dips are able to be recovered from, but at a certain point, the send queue isn't able to get through its backlog fast enough, and things deteriorate rapidly.

![image](https://user-images.githubusercontent.com/1389729/128487596-38b9d020-6570-4911-a032-a8ec50f3f040.png)

In terms of performance: the server isn't sweating here. It's just doing its job. Algorithmically: We're dropping a lot of data on the floor here.
