### ISSUE TITLE
🐛 Map.exe crash when party member zones.

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#5844]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base` (Unmodified)

## Steps to reproduce

1. Make 2 characters on 2 accounts (Or have a friend help test)
2. Have 2 characters make a party. Have one of them zone in or out of the zone the other is in.
3. See that the server crashes.

![image](https://github.com/LandSandBoat/server/assets/42159425/5a7fd856-d59f-4c73-b4f7-dea684f0799c)
![image](https://github.com/LandSandBoat/server/assets/42159425/d7cb0cb9-9430-4f03-9fdb-2da03054415e)

[xi_map.exe_29-5_6-0-35.dmp](https://github.com/LandSandBoat/server/files/15484689/xi_map.exe_29-5_6-0-35.dmp)

## Expected behavior

Server should not crash.

**Comment by UmeboshiXI** [comment]
I reverted https://github.com/LandSandBoat/server/pull/5796 on my local and tried again with no crashes. Crash likely introduced with something related to this PR changes.

**Comment by zach2good** [comment]
@ampitere

**Comment by ampitere** [comment]
Interesting I definitely tested with 2 party members but I think I had trusts out the entire time when I was. Looking into it.

**Comment by UmeboshiXI** [comment]
Just for clarification, I had no trusts out. Only me and a test char partied up. No gear equipped either (For latent effects)

**Comment by ampitere** [comment]
Seems like the party leader is null at that point when they are the ones zoning.

**Comment by jeffnavy14** [comment]
I just wanted to chime in as well, I also had the same issue on my server and I reverted that commit also and everything went back to normal, same test as Umeboshi there were 2 people in a party and they crashed when one person zones.
