### ISSUE TITLE
🐛 Magical Mobskills returning 0 damage.

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#5845]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base` (Unmodified)

## Steps to reproduce

1. Give a mob with a magical mobskill(Not a breath attack) tp, see that it returns 0 damage.
1b. Summon an avatar with a magical damage blood pact. See that it does 0 damage or gives miss message if "Hybrid" attack( Example: Burning Strike)

Note: No lua errors in log, maybe something is getting 0'd out somewhere. Will look into this more today but if someone has a lead or finds a solution before me, more power to them.

## Expected behavior

Magical mob skills should deal damage.

**Comment by UmeboshiXI** [comment]
After a quick look, baseDamage in mobskills.lua is not being added into the calculations except for mobskills with tpeffect of xi.mobskills.magicalTpBonus.DMG_BONUS.

For mobskills with `xi.mobskills.magicalTpBonus.DMG_BONUS`, a nil error is being thrown since most skills do not have value set in their mobskill file for `tpMultiplier` which was recently added. Adding a nil check in the beginning of the `mobMagicalMove` in mobskills to set a default value will solve this until values get assigned in mobskill files.

**Comment by ampitere** [comment]
Quick way to test any skill on any mob: `!exec target:useMobAbility()`
