### ISSUE TITLE
San d'oria 6-1 Cactuar in SQL as a level 75 mob, should be 62/63 like other nations?

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#585]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything Branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
<sorry if this doesn't mark up properly... doing from phone, will clean up later on PC if needed>

Canaria server, Everything Branch

Western Alteps section
```lua
INSERT INTO `mob_groups` VALUES (32,3430,125,'Sabotender_Enamorado',0,128,0,15000,0,75,75,0); 
INSERT INTO `mob_groups` VALUES (33,1165,125,'Eastern_Sphinx',0,128,0,6400,0,62,62,0); 
INSERT INTO `mob_groups` VALUES (34,4324,125,'Western_Sphinx',0,128,0,6400,0,62,62,0)
```
Outer Horo section
```lua
INSERT INTO `mob_groups` VALUES (60,2120,194,'Jack_of_Cups',0,128,1386,0,0,62,62,0); 
INSERT INTO `mob_groups` VALUES (61,2118,194,'Jack_of_Batons',0,128,1384,0,0,62,62,0); 
INSERT INTO `mob_groups` VALUES (62,2121,194,'Jack_of_Swords',0,128,1387,0,0,62,62,0); 
INSERT INTO `mob_groups` VALUES (63,2119,194,'Jack_of_Coins',0,128,1385,0,0,62,62,0)
```

The Fandom wiki lists the cactuar as 75 with a verification flag, but the BG wiki lists it as 63.  There are testimonies of 75's soloing it, lower level duos, and BST reports of killing it by throwing local Tulwar Scorpions at it (which are mid/lower 50 ranged mobs).

Wikis also.list the other nation targets as level 62 as well.

**Comment by TeoTwawki** [comment]
the suggested change seems reasonable to me.
