### ISSUE TITLE
🐛 Recent Update for recalculateStats()

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#5854]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

In a recent update player:recalculateStats() functionality was added to gear_set. Lua. Due to the positioning of the function, there are no checks as to when to activate this function so in turn it performs the recalculation on every piece of gear swapped out. The effect we are seeing is phantom crash's in the map.exe with no errors, lag when performing gear swaps via Ashitacast, received will spike between 1500-3000, phantom crashing on simple aspects as warping or home point due to movement gear swapping. This is just what we have seen from testing over the last week. 

## Expected behavior

Removed the player:recalculateStats() from within Scripts>Globals>Gear_sets to resolve Received spike between 1500-3000 due to gear swapping via ashitacast. After removing the function our spike holds around 300-400 based on zone and surroundings.

**Comment by zach2good** [comment]
The PR in question: https://github.com/LandSandBoat/server/pull/5744

**Comment by zach2good** [comment]
`recalculateStats()`
```cpp
/************************************************************************
 *  Function: recalculateStats()
 *  Purpose : Recalculate the total Stats for a PC (force update)
 *  Example : target:recalculateStats()
 *  Notes   : See scripts/effects/obliviscence.lua
 ************************************************************************/

void CLuaBaseEntity::recalculateStats()
{
    if (m_PBaseEntity->objtype == TYPE_PC)
    {
        auto* PChar{ static_cast<CCharEntity*>(m_PBaseEntity) };

        jobpointutils::RefreshGiftMods(PChar);
        charutils::BuildingCharSkillsTable(PChar);
        charutils::CalculateStats(PChar);
        charutils::BuildingCharTraitsTable(PChar);
        charutils::CheckValidEquipment(PChar);
        charutils::BuildingCharAbilityTable(PChar);

        PChar->UpdateHealth();

        PChar->pushPacket(new CCharJobsPacket(PChar));
        PChar->pushPacket(new CCharStatsPacket(PChar));
        PChar->pushPacket(new CCharSkillsPacket(PChar));
        PChar->pushPacket(new CCharRecastPacket(PChar));
        PChar->pushPacket(new CCharAbilitiesPacket(PChar));
        PChar->pushPacket(new CCharUpdatePacket(PChar));
        PChar->pushPacket(new CMenuMeritPacket(PChar));
        PChar->pushPacket(new CMonipulatorPacket1(PChar));
        PChar->pushPacket(new CMonipulatorPacket2(PChar));
        PChar->pushPacket(new CCharSyncPacket(PChar));
        
    }
}
```

Called by `xi.gear_sets.checkForGearSet`

**Comment by claywar** [comment]
That's a very expensive function

**Comment by zach2good** [comment]
I rolled back the PR in question so this will no longer happen 👍
