### ISSUE TITLE
Joining a party after 5 trusts summoned. (7th person)

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#586]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

1. An invite was sent to me
2. Party leader got tired of waiting, summoned 5 trusts,
3. i accepted the invite, and became a 7th member and this auto converted to a buggy alliance...

**Comment by CatsEyeXI** [comment]
i want to note that this character IS a GM, but toggled off... not sure if that causes the check to bypass...

**Comment by almuth150** [comment]
This issue is not exclusive to trusts. If there's an outstanding invite, and someone else gets invited and takes the 6th slot, it causes problems that usually leads to a server crash.
