### ISSUE TITLE
Promyvion Holla Memory Recepticle Bug🐛 

### ISSUE THREAD

**Issue by BanditIntInc** [DerpyProjectGroup/topaz#5880]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 
`base`

## Steps to reproduce
Testing the Promyvion Battles, the Memory Recepticle does not open the exit portal.  

Promyvion.lua line 100 returns: attempt to index field 'MEMORY_STREAMS' (a nil value).  Doing a quick find for 'MEMORY_STREAMS' in the project doesn't show up anything aside from the use on line 100 in Promyvion.lua.  Searching for 'MEMORY_RECEPTACLES' (used above) shows a few different IDs.lua scripts where they are defined.  We must be missing the definition for 'MEMORY_STREAMS'.   I see a MEMORY_STREAM_OFFSET = GetFirstID('_0g1'), in IDs.lua.  

Also, the Memory recepticle does not seem to have any battle behavior at all.  It moves up and down like it is supposed to, but it does not attack with the push back ability that it should have.  Looking at the fight logic function at line 67, it seems like the only thing outlined is dropping strays.  Of course I'm still new to the project and haven't been able to confirm.

## Expected behavior
Mob uses pushback ability.
No null, portal opens.

**Comment by Xaver-DaRed** [comment]
Promyvion.lua line 100
![imagen](https://github.com/LandSandBoat/server/assets/60053999/1bea3b1d-61b9-4fdc-a0f0-72115c21dbaa)

You are using an outdated version.

**Comment by BanditIntInc** [comment]
Ah, ok just did a fresh pull.  I guess when I did that earlier, it didn't update on my end.  Funny because I only cloned the repo about a week ago.  Code is there now!  Thank you.

**Comment by Xaver-DaRed** [comment]
Not a bug
