### ISSUE TITLE
after server update character is in a unknown area floating in the air

### ISSUE THREAD

**Issue by vanadieltravel** [DerpyProjectGroup/topaz#5915]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

I updated the server and rebuilt all using Visual Studio 2022. The game starts when I use the new version of xiloader but my character is in an unknown area floating in the air. The same happens when I start a new character the character ends up in an unknown area floating in the air. 

## Expected behavior

My character should be in a game area.
![unknown area](https://github.com/LandSandBoat/server/assets/154706297/ac113626-7bb9-4e89-be4b-457d7e0063e4)

**Comment by WinterSolstice8** [comment]
can't help you without a log file, this usually only happens if something went wrong during a query

**Comment by vanadieltravel** [comment]
Sorry my mistake is a log file

**Comment by vanadieltravel** [comment]
Sorry my mistake. Is a log file of the map server okay? There are some errors there even though the server is running. Maybe I shouldn't have updated the game to the newest version.
[map-server.log](https://github.com/user-attachments/files/15841956/map-server.log)

**Comment by WinterSolstice8** [comment]
Looks like you need to run the dbtool to update your database

**Comment by vanadieltravel** [comment]
Thanks now everything works again, once I did it in the right order. I first reset the database, then restored a full backup, updated the database using the dbtools option did the migrations and rebuilt it in visual studio 2022.
