### ISSUE TITLE
🐛 COP 8-1 Garden of Antiquity Rubious NM Bug

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#5966]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Only 1 tower (L-10, !pos 683.718 -6.250 -222.167 33) seems to spawn the Ruaern NMs. After killing those 3, the player gets a cutscene where the taru's activate the 3 crystal pillars. The other 2 towers just return the default message event.

## Expected behavior

Kill NMs at 3 towers (9 Total), then be able to progress the mission through the Crystaline Field.

**Comment by Mortalelite** [comment]
I know there was these both commits that was recent change with 8-1 c473604 and 614742e 

Anything showing up in the logs with any errors? Is all players getting same issue or random?

Disable any addon or plugins? Client up to date?

**Comment by UmeboshiXI** [comment]
Nevermind sorry, Seems to be an issue on my end. Seems a mission bit got set wrong somehow, will have to find out how to correct it.
