### ISSUE TITLE
Sea Crab Drops Bronze Box When Only Ocean Crab Should

### ISSUE THREAD

**Issue by bendangelo** [DerpyProjectGroup/topaz#5973]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Sea crab drops bronze box.

## Expected behavior

Sea crab should not drop bronze box. Only ocean crab should drop it. 
https://ffxiclopedia.fandom.com/wiki/Scooped!

**Comment by Mortalelite** [comment]
https://ffxiclopedia.fandom.com/wiki/Sea_Crab?so=search

https://www.bg-wiki.com/ffxi/Sea_Crab

Shows on both that Sea Crab drops but when clicking on Bronze Box links shows Ocean Crab. 

Also quest [Scooped](https://ffxiclopedia.fandom.com/wiki/Scooped!) explains that comes from Ocean Crab not Sea Crab

**Comment by bendangelo** [comment]
I also want to add to this. The steal ability on Sea Crabs give beastcoins when it should be salt.

**Comment by DotesMiqotes** [comment]
I'd like to add to this that according to ffxidb, it looks like only 2 of the ocean crab spawns actually drop the bronze box, and sea crab doesn't drop it at all.
[http://www.ffxidb.com/search?q=ocean+crab](http://www.ffxidb.com/search?q=ocean+crab)
[http://www.ffxidb.com/search?q=sea+crab](http://www.ffxidb.com/search?q=sea+crab)

**Comment by Xaver-DaRed** [comment]
This was fixed with PR 6065
