### ISSUE TITLE
Paralyzed Attack Causes Aggro / Claim

### ISSUE THREAD

**Issue by bendangelo** [DerpyProjectGroup/topaz#5985]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

* Try to attack an unclaimed mob
* Your attack is "paralyzed"
* Mob gets claimed and starts attacking

## Expected behavior

* Try to attack an unclaimed mob
* Your attack is "paralyzed"
* Mob does not claimed and doesn't attack

I looked around but couldn't find anything to confirm this behaviour but from my knowledge if you never acted upon the mob then it shouldn't get claimed and attack you.

**Comment by RAIST5150** [comment]
This seen on a non aggressive type of target?  Might make a bit more sense if only on aggressive sight/sound type aggro mobs.

**Comment by WinterSolstice8** [comment]
This is retail behavior (much more obvious when you have trusts and/or a pet and you don't keep hate from not even swinging)
you could pretty easily verify this with a paralyze potion, supposedly 100% proc rate

**Comment by bendangelo** [comment]
> This seen on a non aggressive type of target? Might make a bit more sense if only on aggressive sight/sound type aggro mobs.

Yes on non-aggressive.

**Comment by bendangelo** [comment]
> This is retail behavior (much more obvious when you have trusts and/or a pet and you don't keep hate from not even swinging) you could pretty easily verify this with a paralyze potion, supposedly 100% proc rate

I'm referring to non-aggressive unclaimed mobs. Your first swing is paralyzed but still claims the mob. I hope someone can verify this behaviour.
