### ISSUE TITLE
Su0 players can wear Su 1-5 equipment

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#600]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
 CPP, can you write to get player jobpoint_ Spend can easily detect whether the player's equipment reaches the master level of response. Take care of what you can't wear. Or write a script to obtain the player's master level and forcibly take off the player's advanced Su equipment. If there is a function to obtain jobpoint, I think I can implement it. But there's No... I can understand mysql, but I don't quite understand hexadecimal data.
![image](https://user-images.githubusercontent.com/61591648/128727716-ec056135-b18b-456e-afd2-5e7dfacedd43.png)

https://user-images.githubusercontent.com/61591648/128728960-236181ae-7222-4121-98ae-536281afe8b5.mp4

**Comment by claywar** [comment]
My first guess is that the item in question does not have Su level defined for it.  Many pieces of ilvl gear do not have any of their modifiers associated with it.

**Comment by zanglikun** [comment]
> 我的第一个猜测是该项目没有为其定义 Su 级别。许多 ilvl 装备没有任何与其相关的修饰符。

![image](https://user-images.githubusercontent.com/61591648/128729830-450b3281-bbc7-4887-89da-0199666a0381.png)
it print Yes 。。。  X<

**Comment by zanglikun** [comment]
![image](https://user-images.githubusercontent.com/61591648/128730120-e7d68f47-af78-4739-bc3a-c30f52bcb050.png)
 this function may be retun Real JP Spend but i cant invoke it 。。。。

**Comment by claywar** [comment]
Currently, there is no lua binding for that function, though it would be very easy to implement.  This is example only:

```
uint16 CLuaBaseEntity::getJobPointsSpent()
{
    auto* PChar = static_cast<CCharEntity*>(m_PBaseEntity);
    return PChar->PJobPoints->GetJobPointsSpent();
}
```
You would also need to add the appropriate `SOL_REGISTER()` line in lua_baseentity as well

**Comment by claywar** [comment]
For Sagitta, I am currently unable to reproduce on my end.  I have item in inventory, MNK99, and Su 0 as well; how was the item equipped?

**Comment by zanglikun** [comment]
> For Sagitta, I am currently unable to reproduce on my end. I have item in inventory, MNK99, and Su 0 as well; how was the item equipped?
Not only this piece of equipment, but also all Su equipment. The equipment method in the video is taught by an old Chinese player. I want to repair it and don't want them to wear haha
It seems to be using to save the appearance,

**Comment by claywar** [comment]
Ah, thank you for the feedback.  I will investigate today.

**Comment by zanglikun** [comment]
player:PrintToPlayer(tostring(player:getMod(xi.mod.SUPERIOR_LEVEL)))  this way can get Su level but MNK cant get maste level this is 0

**Comment by claywar** [comment]
That mod is only used by players at the moment, and I found that there is nothing in equipment that lets the server know what Su is required by the item (all is client-side at the moment).  To fix this, I would suggest (and will work) to add Su level field to database in item_equipment, and then check against the required value.

It will take some work to implement, as DB will need all of the Su items data to be entered

**Comment by zanglikun** [comment]
> 该mod目前仅供玩家使用，我发现设备中没有任何东西可以让服务器知道该物品需要什么Su（目前都是客户端）。为了解决这个问题，我会建议（并且会起作用）将 Su 级别字段添加到 item_equipment 中的数据库，然后检查所需的值。
> 
> 这需要一些工作来实现，因为 DB 需要输入所有的 Su 项目数据

thanks ! i will find more questions ^^ and pull it in issues
