### ISSUE TITLE
🐛 "Delete Character" does not remove character from database.

### ISSUE THREAD

**Issue by Binarynova** [DerpyProjectGroup/topaz#6003]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue

`base`

## Steps to reproduce

- Follow Quick-Start Guide for Windows 10 through a successful Build All
- Run server, make a new character
- Log out to Main Menu after gaining control
- Delete character.
- Can no longer access old character in Main Menu (Select and Delete Character options are greyed out).
- Attempt to make new character with the same name: Error code FFXI-3313.

## Expected behavior

After deleting a character that name should be available to a new character.

## More details

Upon further inspection, after choosing Delete Character, HeidiSQL shows that the database row for the deleted character still exists. Several other char_ tables contain data for charid 1 as well (char_exp, char_flags, char_history, and others.)
![image](https://github.com/user-attachments/assets/c52f7c77-3530-4918-b565-3a0dbbc30d68)

DB also contains the following code in the char_delete trigger:
![image](https://github.com/user-attachments/assets/5fae0148-ddc7-496d-97ed-be1d4475b59f)

**Comment by zach2good** [comment]
Sounds suspiciously like this: https://github.com/LandSandBoat/server/pull/3520

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/server/blob/base/src/login/view_session.cpp#L137-L142

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/server/blob/base/src/login/login_helpers.cpp#L151

https://github.com/LandSandBoat/server/blob/base/sql/chars.sql#L51

**Comment by zach2good** [comment]
Looks as though deleting a character doesn't immediately delete it, but makes it unavailable so it can be restored later if needed. Seems like a reasonable thing to do to me.

Even if a server owner keeps very fine-grained backup, restoring a previously deleted character from a backup is a _massive_ pain if someone new has claimed their charid or name (though, I assume we don't fill in gaps in charids, if gaps are even possible).

**Comment by Binarynova** [comment]
Yeah that makes sense. I'm only running into it because I'm using a test character to test fresh character settings (HP/MP/Stats multipliers, etc.).

Does the server delete them after a set amount of time (and is that customizable) or do these characters remain permanently?

**Comment by zach2good** [comment]
I don't know if this was the original intent, but for things like "Return Home to Vana'diel", you can restore years-old characters. We don't have any manual or auto-purge of unavailable character ids/names.

**Comment by zach2good** [comment]
If you want to delete characters, use `char_delete` like you showed in the screenshot

**Comment by zach2good** [comment]
(Which is triggered automatically for you when you remove a row from that chars table)

**Comment by Binarynova** [comment]
Ah that's perfect. Thanks for your time! I'm gonna mark this closed since it's not a bug and there's an easy workaround.

**Comment by cocosolos** [comment]
When a char is deleted the name _should_ open back up, but we don't currently support forced name changes which would be necessary for undeleting a char with a name that has since been taken.

**Comment by WinterSolstice8** [comment]
> When a char is deleted the name _should_ open back up, but we don't currently support forced name changes which would be necessary for undeleting a char with a name that has since been taken.

We do have the reverse engineering to attempt to add that feature now, it could be possible, but AFAIK nobody has a POL packet dump of it happening. We may not need one, though.

**Comment by cocosolos** [comment]
It would cost money, but could use 2 content IDs and a server transfer to force a name change. Also need to go through and make sure char name isn't being used as a unique identifier anywhere. Low priority but just documenting here for the future.
