### ISSUE TITLE
🐛 <Turms Gearset Cannot be Equip>

### ISSUE THREAD

**Issue by Jerseyturo** [DerpyProjectGroup/topaz#6006]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10
![turms-omicron](https://github.com/user-attachments/assets/b89b918f-de06-4530-8da5-bfae1a3b8b95)

## Branch affected by issue 

`base`

## Steps to reproduce

add items to inventory and try to equip using lvl 99 dnc/thf/run 
## Expected behavior

should be able to equip based on jobs in description

**Comment by Xaver-DaRed** [comment]
That gear is SU 3. Whats your SU level?

**Comment by Jerseyturo** [comment]
Wow I completely missed that. I stepped out but it's probably zero.

**Comment by Xaver-DaRed** [comment]
Not an issue, user error.
