### ISSUE TITLE
🐛 Characters "forget" learned spells

### ISSUE THREAD

**Issue by VivalaSRC97** [DerpyProjectGroup/topaz#6010]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 11 

## Branch affected by issue 

`base` (local installation)

## Steps to reproduce

1 - Create a new character
2 - Learn a new spell using a scroll or !addspell if you made your character a GM
3 - Check on the game menu that you know the spell or use it
5 - Zone or logout/shutdown
6 - Log in
7 - Your character "forgot" all the spells learned

## Expected behavior

Your character remembers all the spells learned.

**Comment by Xaver-DaRed** [comment]
Not an issue. User error.

**Comment by WinterSolstice8** [comment]
do you have any errors in your logs?

**Comment by VivalaSRC97** [comment]
Errors in the Map server:
-  [map][error] Query Failed: SELECT char_spells.spellid FROM char_spells JOIN spell_list ON spell_list.spellid = char_spells.spellid WHERE charid = (?) AND (spell_list.content_tag IN () OR spell_list.content_tag IS NULL) (db::preparedStmt::<lambda_1>::operator ():208)
-  [map][error] (conn=1555) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') OR spell_list.content_tag IS NULL)' at line 1 (db::preparedStmt::<lambda_1>::operator ():209)

I did not edit my char_spells.sql and spell_list.sql

**Comment by VivalaSRC97** [comment]
I tried also a fresh re-install and the errors persist.

**Comment by Xaver-DaRed** [comment]
I just compiled the server. This is NOT happening.
You probably have an issue with your database, or missed a step in the guide.
Try following the steps EXACTLY as told in the wiki, including the database installation, using the exact version we recommend, without custom content/code/modules.
If your issue persists, start a discussion: https://github.com/LandSandBoat/server/discussions

![Xaver_2024 07 17_191210](https://github.com/user-attachments/assets/0fad396d-a8d5-442a-b766-9971065f556e)
![Xaver_2024 07 17_191227](https://github.com/user-attachments/assets/a542f04f-e678-4a01-a373-fc66e3f0bf7c)

**Comment by VivalaSRC97** [comment]
I'll try again! Thank you for checking!
