### ISSUE TITLE
Impetus recast set to 360 instead of 300

### ISSUE THREAD

**Issue by Harfainx** [DerpyProjectGroup/topaz#6034]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

All

## Branch affected by issue 

`base`

## Steps to reproduce

Use Impetus. Recast is 6 minutes

## Expected behavior

Use Impetus. Recast is 5 minutes

sql/abilities.sql line 285 recastTime is 360. Should be 300

Base code:
INSERT INTO `abilities` VALUES (269,'impetus',2,88,1,360,31,100,0,240,2000,0,6,20.0,0,1,80,0,0,NULL);

Should be:
INSERT INTO `abilities` VALUES (269,'impetus',2,88,1,300,31,100,0,240,2000,0,6,20.0,0,1,80,0,0,NULL);

**Comment by Xaver-DaRed** [comment]
This was fixed in PR 6073
