### ISSUE TITLE
Magical mobskills deal 0 dmg

### ISSUE THREAD

**Issue by vitus0123456** [DerpyProjectGroup/topaz#6049]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

1. open up _scripts/actions/spells/trust/prishe_ii.lua_ and add _mob:addMod(xi.mod.REGAIN, 1000)_ under spellobject.onMobSpawn for speedup testing purposes.
2. _!immortal_ a mob and engage it, observe Prishe spaming 0 dmg magical WSs

### alternatively

1. open up _scripts/actions/spells/trust/shantotto_ii.lua_ and add _mob:addMod(xi.mod.REGAIN, 500)_ under spellobject.onMobSpawn 
2. observe Shanttoto II melee for 0 dmg.  Her magical WSs deal no dmg and take off shadows from mobs with no possibility of having shadows on (i.e mandragora, Orobon...).

## Expected behavior

magical mobskills should deal dmg

**Comment by vitus0123456** [comment]
for magical mobskills, looks like there is a problem with _xi.mobskills.magicalTpBonus.NO_EFFECT_ .  If replace it with _xi.mobskills.magicalTpBonus.DMG_BONUS, 1_ magical mobskills can deal dmg again.  If it means anything.

**Comment by Xaver-DaRed** [comment]
TY for the report. PR to fix this is ready.
