### ISSUE TITLE
🐛 Trusts are unable to cast spells that players don't normally get

### ISSUE THREAD

**Issue by DotesMiqotes** [DerpyProjectGroup/topaz#6063]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu 22.04

## Branch affected by issue 

`base`

## Steps to reproduce

Add a gambit to a trust for a spell that they should be able to cast, but a player can't with the trust's job and sub job level.

## Expected behavior

Trusts should be able to cast spells based on their level and the min level listed in their spell list.

## Additional Notes
The issue is with spell.cpp line 699 and how it checks the trust main job and sub job levels against what level a player can cast the spell.
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/src/map/spell.cpp#L685-L686
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/src/map/spell.cpp#L699-L702

It's keeping Stun from working on my implementation of Fablinix #6055 .
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/sql/mob_spell_lists.sql#L3504

It will most likely be a problem for the trusts and spells listed below. I'm already planning on implementing these trusts, and am not opposed to including their spell gambits as part of the fix I'm working on.

King of Hearts - RDM/WHM - Firaga I-III (BLM) Firaga IV @ level 92 (mob only)
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/sql/mob_spell_lists.sql#L4132-L4135
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/scripts/actions/spells/trust/king_of_hearts.lua#L14-L16
Noillurie - SAM/PLD - Cure IV (PLD 55) - Can cast it at 84
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/sql/mob_spell_lists.sql#L3569
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/scripts/actions/spells/trust/noillurie.lua#L14-L16
Iroha - SAM/WHM - Protectra V, Shellra V (WHM 75) - Shouldn't have lower level versions (FFXIclopedia and BG-Wiki)
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/sql/mob_spell_lists.sql#L4203-L4212
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/scripts/actions/spells/trust/iroha.lua#L14-L16
Iroha II - SAM/WHM - P5 & S5 Same issue as normal trust, Flare II (BLM 75 reported as near insta cast)
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/sql/mob_spell_lists.sql#L4397-L4407
https://github.com/LandSandBoat/server/blob/17b4bb81602bbb8b653bd4b7f1e51fa53f10636b/scripts/actions/spells/trust/iroha_ii.lua#L14-L16

**Comment by zach2good** [comment]
Since we specify when the trust should get access to the spell in `mob_spell_lists`, we can/should bake that into this check:

```cpp
                // ensure trust level is appropriate+
                if (PCaster->objtype == TYPE_TRUST && PCaster->GetMLevel() < JobMLVL && PCaster->GetSLevel() < JobSLVL)
                {
                    return false;
                }
```

So it becomes something like (expanded out for clarity):

```cpp

const bool isTrust = PCaster->objtype == TYPE_TRUST;
if (isTrust)
{
    // Get their spell list id
    // Go get their spell list
    // Find the current PSpell in there
    // Check what's in their spell list - use the level requirements there instead of what is stored in PSpell
}
```

**Comment by DotesMiqotes** [comment]
Awesome, thank you! I was able to find a place in `mobutils` where I could add the function:
```c++
uint16 GetSpellMinLevel(CMobEntity* PMob, SpellID spellId)
{
    for (std::vector<MobSpell_t>::iterator it = PMob->m_SpellListContainer->m_spellList.begin(); it != PMob->m_SpellListContainer->m_spellList.end(); ++it)
    {
        if (spellId == (*it).spellId)
        {
            return (*it).min_level;
        }
    }
    return 255;
}
```
And then change the level check in spell.cpp to this:
```c++
if (PCaster->objtype == TYPE_TRUST && PCaster->GetMLevel() < mobutils::GetSpellMinLevel(static_cast<CMobEntity*>(PCaster), spell->getID()))
```
It works perfectly so far, and could potentially make this function obsolete, since GetSpellMinLevel() returns the min_level value from the mob's spell list.
https://github.com/LandSandBoat/server/blob/7c799aecd7b21ba42ac67730eb55a645d3129817/src/map/spell.cpp#L812-L823

I've been looking around to see if there is anywhere else I can put that function, and I haven't been able to find any so far. I also wanted to make sure the potential changes looked okay before I put them into a PR.

**Comment by zach2good** [comment]
You can probably use `std::find` and/or a [range-based for loop](https://en.cppreference.com/w/cpp/language/range-for) for `PMob->m_SpellListContainer->m_spellList`, but otherwise seems sane 👍

**Comment by DotesMiqotes** [comment]
I tried both, and unfortunately couldn't get either to work without a few extra steps and variable declarations.
