### ISSUE TITLE
🐛 WS Global / calculateRawWSDmg - xi.mod.WS_DEX_BONUS returning nil

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6082]
WS_DEX_BONUS mod is returning nil on weaponskill global in function calculateRawWSDmg.  
global/weaponskills.lua 489 calculateRawWSDmg
global/weaponskills.lua 802 doPhysicalWeaponskill

when equipping the UTU Grip which contains the mod, it errors out on ws causing 0 dmg. remove the utu grip and or the mod and it will calculate the damage. 

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
Equipped and Unequipped Ute Grip,  removed 957 WS_DEX_MOD

## Expected behavior

![Screenshot_2024-08-06_at_5 36 07_PM](https://github.com/user-attachments/assets/93083de2-11fe-4764-b953-f99b2f319718)

**Comment by WinterSolstice8** [comment]
Can't reproduce on current base branch... hmm

**Comment by WinterSolstice8** [comment]
Found it, needed to use a WS without a DEX mod. your log was helpful, thanks.

**Comment by FFXILevelDown** [comment]
O thank sweet baby Jesus, I thought I had removed all the custom things and tested to ensure it wasn't a self inflicted wound, was about to go thru all of it again to make sure 🤣
