### ISSUE TITLE
🐛 Erroneous clearing of an account session

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#6106]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Got a fun one here.

Exact steps to reproduce:
- two map servers with zones split across them
- have an account with two chars, one in a zone on each map server
- log into char 1.
  - The map server it's on we'll call map server 1
- log out
- repeat previous two steps until you get a message like so: `[error] map_encipher_packet: bad packet from <127.0.0.1> (map_decipher_packet:640)`
  - A pretty reliable way to trigger this condition is to be a GM (so you instant log out) and use an item just before you `/logout`
  - `!additem airborne 12`
  - `/item airborne` then immediately `/logout`
- This causes a session on map server 1 not tied to a PChar. It will be cleaned on the next `map_cleanup`
- log into char 2 on map server 2 before the cleanup happens
- when map server 1 does a cleanup, it runs: `DELETE FROM accounts_sessions WHERE client_addr = %u AND client_port = %u`
- this deletes the accounts_session entry for char 2, since the ffxi client uses the same source port as char 1 when it logs into char 2

screenshot with the two chars replicating the scenario:
![image](https://github.com/user-attachments/assets/236ea5f3-d3e0-4490-8abd-60bdbd23d907)

## Expected behavior

`accounts_sessions` entries should not be removed for unrelated, active characters

**Comment by MowFord** [comment]
Btw asb solved it simply: https://github.com/AirSkyBoat/AirSkyBoat/blob/057bdfb71bb9e6a92a47deac864f5f9d6da884c5/src/map/map.cpp#L1154

I'm not sure the implications of all methods of lsb configuration, since you can probably run multiple map servers on the same port and different ips... But I doubt anyone does that

**Comment by zach2good** [comment]
Unfortunately, this change came in in a _ten thousand line commit_ which smashes together loads of unaffiliated things, probably also wiping all attribution:

https://github.com/AirSkyBoat/AirSkyBoat/commit/f1423a23e20c9b6b02f610bd5394ed90b78f2ca5#diff-95ec1891d78e6e9ffc6f68a5eb4803079621e9f9c4a2a43ffc9b70e7bedeb7be

Winter is probably the best person to think about these sorts of changes, I haven't looked at login flow or session stuff for a long time

**Comment by WinterSolstice8** [comment]
ASB based (horizon) servers have an issue with permanently hung sessions until they are manually cleared in the database (or cleared by a GM command), so maybe their fix isn't complete. I'll be looking into this when im less tired (probably this weekend)

Thanks for the repro steps though, very good
