### ISSUE TITLE
🐛 Monomi: Ichi duration is incorrect

### ISSUE THREAD

**Issue by mogulbgod** [DerpyProjectGroup/topaz#6125]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
All

## Branch affected by issue 

`base`

## Steps to reproduce

Cast Monomi: Ichi, duration is 2 minutes.

## Expected behavior

Monomi: Ichi duration is 7 minutes (420 seconds) after the January 21, 2014 FFXI update. [https://forum.square-enix.com/ffxi/threads/39564-Jan-21-2014-%28JST%29-Version-Update](https://forum.square-enix.com/ffxi/threads/39564-Jan-21-2014-%28JST%29-Version-Update)

**Comment by almuth150** [comment]
Both Tonko spells also have incorrect durations.

**Comment by clanofartisans** [comment]
This was fixed here: https://github.com/LandSandBoat/server/pull/6155

**Comment by Xaver-DaRed** [comment]
ty @clanofartisans
