### ISSUE TITLE
Trust: Qultada, Phantom Roll only affects Trust. Possible Gambits Container issue? 

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#617]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

As title states, I've been trying to become more familiar with the code and figured I'd take a crack and some starting logic for Qultada. I realized that while I can get him to roll, the effects of the rolls only apply to Qultada himself. I could not find any other instances in the current code where a TRUST job ability impacts the entire party.
```

		mob:addSimpleGambit(ai.t.SELF, ai.c.NOT_STATUS, xi.effect.CORSAIRS_ROLL, ai.r.JA, ai.s.SPECIFIC, xi.ja.CORSAIRS_ROLL)
		mob:addSimpleGambit(ai.t.SELF, ai.c.NOT_STATUS, xi.effect.CHAOS_ROLL, ai.r.JA, ai.s.SPECIFIC, xi.ja.CHAOS_ROLL)
		mob:addSimpleGambit(ai.t.TARGET, ai.c.ALWAYS, 0, ai.r.RATTACK, 0, 0, 10)


```

**Comment by zach2good** [comment]
Don't forget to fill in the checkboxes, they're there for a reason
