### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#624]
``
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When a player enters an instance, how can other players join
![image](https://user-images.githubusercontent.com/61591648/129699356-b9f6c692-924a-451a-847d-ad8bb517bd11.png)

setInstance(instance)   You can't let other players join

**Comment by zach2good** [comment]
![image](https://user-images.githubusercontent.com/1389729/129709389-270031ef-da31-4866-8a3c-eaf6ee23118a.png)

Steps:
1. The leader clicks on the entry point (example: https://github.com/LandSandBoat/server/blob/base/scripts/zones/Alzadaal_Undersea_Ruins/npcs/_20m.lua#L15)
2. The leader's registry requirements are checked (https://github.com/LandSandBoat/server/blob/base/scripts/globals/instance.lua#L297)
3. The registry requirements are part of the instance script (https://github.com/LandSandBoat/server/blob/base/scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua#L11)
4. If the leader passes, the party members are checked for their entry requirements (https://github.com/LandSandBoat/server/blob/base/scripts/globals/instance.lua#L308)
5. The party members requirements are checked in the instance script (https://github.com/LandSandBoat/server/blob/base/scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua#L17)
6. If they pass, they'll be teleported into the instance with the leader (https://github.com/LandSandBoat/server/blob/base/scripts/globals/instance.lua#L416-L417)

**Comment by zanglikun** [comment]
Thank you very much. I'll try it and then try debugging

**Comment by zanglikun** [comment]
I tried to let multiple roles enter. I just need to add V: setpos (0, 0, 0, 0, instance: getzone(): getid()) but! The goto command cannot have a practical effect^^
