### ISSUE TITLE
MySQL downtime？

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#625]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
[08/17/21 17:59:32:475][topaz_game_64.exe][critical][stacktrace] 	at Sql_Ping in E:\A\server-base\src\common\sql.cpp: line: 169: address: 0x7FF65EF8DBE0
[08/17/21 17:59:32:475][topaz_game_64.exe][critical][stacktrace] 	at Sql_P_KeepaliveTimer in E:\A\server-base\src\common\sql.cpp: line: 189: address: 0x7FF65EF8DC10
this is logs
Does this seem to be caused by MySQL downtime？

**Comment by zanglikun** [comment]
![image](https://user-images.githubusercontent.com/61591648/129706963-3f79e363-3c97-4c67-a15e-595456e0a97d.png)

**Comment by zach2good** [comment]
Possibly related old issues:
https://github.com/project-topaz/topaz/issues/1152
https://github.com/project-topaz/topaz/issues/1177
https://github.com/topaz-next/topaz/issues/1920

**Comment by zach2good** [comment]
The crash comes from `Sql_Ping -> mysql_ping`, if it can't connect to your MySQL server it will crash ;_;

**Comment by zanglikun** [comment]
I think so, but my server has been running for almost a year. I just upgraded yesterday's code from April this year. So, I'm a little skeptical about code performance. XD
