### ISSUE TITLE
🐛 Warp / Teleport - Status effect expiration handling in status_effect_container.cpp, line 1741.

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6264]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
After updated the server last night - 
Warp 1, 2, Teleport Holla etc causing Status effect expiration handling.
Moved this update over to my test server as well as a LSB base test server to reproduce and rule out custom changes. Problem was persistent in all three servers. 
I reverted PR 6262 & 6249 and did not have this issue, have not diagnosed which file in the PR this issue maybe stemming from.  Additional information below. 

Key Information:
Crash type: Access Violation (C0000005)
Fault address: 00007FF7D3F8D7B6
Process Name: xi_map.exe
Cause: Status effect expiration handling in status_effect_container.cpp, line 1741.
Call stack:
CStatusEffectContainer::CheckEffectsExpiry+327

please let me know if you need additional information, 
thank you

**Comment by WinterSolstice8** [comment]
Will take a look tonight, thought I squashed that specific bug.. hmm

**Comment by WinterSolstice8** [comment]
Thanks for the report -- sorry about the crashes, I knew changing this system was gonna be a bit painful, but it will be worth it for end users to have better zoning

**Comment by FFXILevelDown** [comment]
no worries, thank you for looking at it :)
