### ISSUE TITLE
🐛 Zone.cpp return m_zoneID; nullptr - error

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6313]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Zone.cpp return m_zoneID; nullptr - error
Errors when party members have the status effects and try to zone while under the effect. 
Recreated in multiple zones with multiple Indi Spells such as Indi Regen, Indi Refresh, Recreated while under Level Sync as well. Level sync does not get removed after crash and you are still under the effect when you log back in. Doesn't appear to happen when leader zones though.  Not sure if these two issues are related? See attached debug reports

## Expected behavior

![crash zoning](https://github.com/user-attachments/assets/c1580c05-858d-4db0-8568-7fd1d29b75a1)
![Screenshot 2024-10-03 at 6 50 38 PM](https://github.com/user-attachments/assets/0c4e0da5-f26d-4c4b-b1e3-1695b4e5adb6)
![levelsync crash](https://github.com/user-attachments/assets/92303cce-ee82-4cd9-9773-eed7498df961)

**Comment by WinterSolstice8** [comment]
Does this happen when changing between processes as well as same-process? just making sure before I dig in

**Comment by WinterSolstice8** [comment]
I think I see the bug, standby

**Comment by FFXILevelDown** [comment]
If I understand the question correctly yes, both debugs are separate each capture recreated and resulting in a full server crash.

**Comment by WinterSolstice8** [comment]
I understand why this crash happens now so I'll probably take an afternoon to try to solve it better (I am sure there's going to be more missing zone null checks)

#6315 will fix this immediate crash, at least. It does look like there's a separate bug for keeping level sync if the server crashes, however.

**Comment by FFXILevelDown** [comment]
should I open up another ticket for level sync?
