### ISSUE TITLE
Circle recasts and powers are inconsistent and often incorrect.

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#634]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Holy and Arcane Circles have a 10 minute recast instead of 5 like they're supposed to, and they do not have their power reduced when the job is subbed. Warding and Ancient Circles appear to be correct, as do all of the existing modifiers for duration increase (all +90s for all four circles), along with the base power for all four circles from main job (should be 15% from main job, 5% when subbed).

**Comment by TeoTwawki** [comment]
they were coded to an older spec of the game and not updated for modern times yet. Def needs to happen.

**Comment by ShiyoKozuki** [comment]
Also missing damage bonus and damage reduction to said families.
