### ISSUE TITLE
🐛 Changing zones with Level Sync effect crashes the server

### ISSUE THREAD

**Issue by LoxleyX** [DerpyProjectGroup/topaz#6346]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 
`base`

## Steps to reproduce
Changing zones with Level Sync effect crashes the server.

* Level Sync clean up was moved to Char Entity destructor here: https://github.com/LandSandBoat/server/pull/6282
* However, this caused the effect to be saved in DB and characters had permanent Level Sync effect even after leaving the party or relogging. We also began to experience crashes similar to those in the dump below.

* Attempted to move Level Sync clean up to back to `CZone::CharZoneOut`which continued to produce these crashes

* Attempted to apply this fix to base, which should fix the permanent Level Sync but did not fix the crashes: https://github.com/LandSandBoat/server/pull/6323

```
CZoneEntities::GetCharByID+0 (src\map\zone_entities.cpp, line 1233)
zoneutils::GetChar+2C (src\map\utils\zoneutils.cpp, line 175)
CPartyDefinePacket::CPartyDefinePacket+159 (src\map\packets\party_define.cpp, line 57)
CParty::ReloadParty+2D0 (src\map\party.cpp, line 880)
CLuaBaseEntity::disableLevelSync+4D0 (src\map\lua\lua_baseentity.cpp, line 11022)
sol::function_detail::upvalue_this_member_function<CLuaBaseEntity,void (__cdecl CLuaBaseEntity::*)(void)>::real_call+47 (ext\sol\include\sol\sol.hpp, line 19362)
0001:0000000000001CB0 libluajit_64.dll ()
lua_pcall+AA ()
sol::basic_protected_function<sol::basic_reference<0>,0,sol::basic_reference<0> >::call<,CLuaBaseEntity,CLuaStatusEffect>+BC (ext\sol\include\sol\sol.hpp, line 21002)
luautils::OnEffectLose+325 (src\map\lua\luautils.cpp, line 2483)
CStatusEffectContainer::RemoveStatusEffect+42 (src\map\status_effect_container.cpp, line 621)
CStatusEffectContainer::DelStatusEffectSilent+9B (src\map\status_effect_container.cpp, line 677)
CCharEntity::~CCharEntity+242 (src\map\entities\charentity.cpp, line 332)
CCharEntity::`scalar deleting destructor'+14 ()
CZoneEntities::~CZoneEntities+2B5 (src\map\zone_entities.cpp, line 110)
CZone::~CZone+45 (src\map\zone.cpp, line 145)
CZone::`scalar deleting destructor'+14 ()
```

## Expected behavior
Should be able to zone with Level Sync, if sync target or leader, the effect should deactivate on remaining party members after 30 seconds. The effect should be removed from zoning player instantly.

**Comment by zach2good** [comment]
This went in yesterday https://github.com/LandSandBoat/server/pull/6323

Please let us know if this fixes the crash for you

**Comment by WinterSolstice8** [comment]
Simply zoning out after level syncing doesn't crash anymore but iirc there's some edge case here too

**Comment by LoxleyX** [comment]
Thanks for submitting the fixes. I will update this issue once we've had a chance to update and test everything live.

**Comment by LoxleyX** [comment]
The issue appears to be resolved. Thanks everyone.
