### ISSUE TITLE
🐛 XI-Connect server error when client connects

### ISSUE THREAD

**Issue by whasf** [DerpyProjectGroup/topaz#6351]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows Server 2016 x64

## Branch affected by issue 

`base`

## Steps to reproduce

Updated to 87c3485999143e9c3761389bf76609b6e01e4b84
Built x64-debug (I tried x64-Release as well)
Ran DB update and migrations via dbtool.py
Had a user that is using xiloader 1.1.1 connect, they see "lobby connection failed". On XI-Connect I see: 
[10/13/24 11:17:29:610][connect][error] Inner fatal: set_option: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call. (ConnectServer::ConnectServer:108)

## Expected behavior

I expect client to be able to connect

**Comment by WinterSolstice8** [comment]
Unsupported OS
