### ISSUE TITLE
🐛 Terror Touch mobskill throws an error

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#6379]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
```
luautils::onMobWeaponSkill (mobskill) ./scripts/globals/combat/status_effect_tables.lua:65: attempt to index a nil value
stack traceback:
        ./scripts/globals/combat/status_effect_tables.lua:65: in function 'getAssociatedMagicEvasionModifier'
        ./scripts/globals/combat/magic_hit_rate.lua:491: in function 'applyPlayerResistance'
        ./scripts/globals/mobskills.lua:658: in function 'mobPhysicalStatusEffectMove'
        ./scripts/actions/mobskills/terror_touch.lua:19: in function <./scripts/actions/mobskills/terror_touch.lua:12> (luautils::OnMobWeaponSkill:3803)
```

I think this just means the status effect isn't in the table it looks up resistance by element from, but I have not familiarized myself with any changes since around May. Its been awhile.

## Expected behavior
Mob gives you bad touch and you get an adult instead of a script error 👍

**Comment by TeoTwawki** [comment]
doggone it, I missed them checkboxes.

**Comment by Xaver-DaRed** [comment]
Stupid question, but I have to ask, do you have this PR merged aswell?
https://github.com/LandSandBoat/server/pull/6368

**Comment by TeoTwawki** [comment]
Jesus, I'm becoming a n00b. I blew a merge.
