### ISSUE TITLE
Souleater consumes too much HP when using a multi hit WS

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#639]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
If you use a multi hit WS with enough hits, you drop dead instantly from the WS. I suppose it's not updating to the new current HP on a per hit basis.

**Comment by ampitere** [comment]
This was fixed in: https://github.com/LandSandBoat/server/pull/3668
