### ISSUE TITLE
Level Cap 90 - Dormant Powers Dislodged Broken

### ISSUE THREAD

**Issue by Endymionls** [DerpyProjectGroup/topaz#640]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

When trading the requested items an having the required number of merit points, the cutscene doesn't play through. Camera can be spun around, but movement isn't allowed and items are not consumed. I have to quit the client to move around again.

**Comment by RAIST5150** [comment]
This could be tied to a client version mismatch, especially if you are on the current retail client (August update).  Think we are currently still not fully synched to the July retail client state.

Would be nice if someone can confirm if this behaves differently with older/newer client versions in play.

Also, may want to make sure no plugins are interfering as well (like 60fps, the dialogue skipping one, etc.).

**Comment by Endymionls** [comment]
Yes, unfortunately my computer is running the August update because it's a fresh install. I did not have access to the July update for it.

**Comment by RAIST5150** [comment]
Yeah... we are in a bit of a pickle with how SE likes to change memory locations and shifts ID's around all the time.

They wrote some tools to automate detecting a lot of changes, but there is still a good bit that has to be done manually.  It is much better than it used to be, but still takes time to get us back on track when they make big changes.

Hang in there... they will get to synching things again as soon as they can.  More people are contributing where they can, but it is still a small group doing this "on the side".

**Comment by Endymionls** [comment]
I totally understand. I'm only posting the issue as an "issue", since that's the only way issues can be resolved. I appreciate everyone's hard work on this project. If I were a coder, I'd also be contributing, but that isn't my skillset.

**Comment by Endymionls** [comment]
I was able to verify that this issue is also happening on my laptop that has the July update on it.

**Comment by RAIST5150** [comment]
Hmmm.. that is odd.  Seems we smacked down the taru for someone fairly recently on Canaria (Everything/Base).  

Can't recall if that all went down before or after we tried synching to the July client though.  There were still some unresolved issues with the July 6th client though, so it is possible that is still in play.  But it for sure WAS working in fairly recent months.
