### ISSUE TITLE
Completing Three Paths does not grant Trust: Shikaree Z

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#642]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
After completing all paths in the CoP mission Three Paths, Perih Vashai should give Trust: Shikaree Z. After talking to her with Three Paths complete, she does not give the trust. A review of the code for her does not show anywhere she will give the appropriate trust.

**Comment by RAIST5150** [comment]
A lot of trusts simply are not scripted yet, and a decent chunk of ones that are have a very basic AI in play (no spells/weapon skill gambits written).

https://github.com/LandSandBoat/server/wiki/What-Works
(There is a link further down the page about the state of trusts)

**Comment by helixhamin** [comment]
Oh, I know. I realize it is not ready, but still wanted to mark a tracking issue anyways. One of those "Here is something to mark complete once it is complete", and easy to find out what is missing for people wanting to work on things.

**Comment by claywar** [comment]
Closed by #2200
