### ISSUE TITLE
Issues with Cmake IN visual Studio

### ISSUE THREAD

**Issue by kalvx** [DerpyProjectGroup/topaz#6425]
cmake error when building

**Comment by zach2good** [comment]
I run on win11, so it's not that. This looks as though your firewall or general network setup is blocking the build system from being able to download the extra code it needs to build.

**Comment by kalvx** [comment]
> I run on win11, so it's not that. This looks as though your firewall or general network setup is blocking the build system from being able to download the extra code it needs to build.

I see, I wrote you a message. I'm still having issues with firewall off and also even added an exception. https://discord.gg/Esg9PrCk please assist.

**Comment by WinterSolstice8** [comment]
your image says it "failed to checkout tag" on fmtlib

does this work?

```diff
diff --git a/ext/CMakeLists.txt b/ext/CMakeLists.txt
index 263e87df2b..4a989b122d 100644
--- a/ext/CMakeLists.txt
+++ b/ext/CMakeLists.txt
@@ -68,7 +68,7 @@ endif(TRACY_ENABLE)
 CPMAddPackage(
     NAME fmt
     GITHUB_REPOSITORY fmtlib/fmt
-    GIT_TAG 10.1.1
+    GIT_TAG f5e54359
 ) # defines: fmt::fmt
 
 CPMAddPackage(
```

That commit is the same tag as 10.1.1

**Comment by zach2good** [comment]
Please don't try and solicit support from us on discord, and especially not on our personal accounts on other platforms.

**Comment by kalvx** [comment]
Due to the lack of communication options other than replying public. I have a privacy concerns. Therefore, I am trying to keep my messages private. If you don't want to help than you don't have to help. Also if you have any advice instead would be great.

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kalvx** [comment]
Thanks for the fast responses, I will try to see if i can figure out what you meant soon.

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kalvx** [comment]
I mean obviously I'm pretty desperate to get somewhere since I'm limited time. I apologize

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by claywar** [comment]
So I'm going to be a bit blunt here, but your desperation is not our problem.  The beauty of opensource is you can take what is here and run with it, but it is offered with zero support.  Anything beyond that is a bonus, and should be taken as such.

Looking at your history, you've forked ASB and are coming to us with problems.  That's a bit of a yellow flag in my book, though perhaps I could be wrong.  That out of the way, _no member_ of this organization will ever randomly join a discord you've created to support a project with no background.  That's suspect as hell, and any offer of cash would have to compete with the rates that our day-jobs offer, which are honestly a lot higher than anyone in a hobbyist role is most likely willing to pay.

**Comment by kalvx** [comment]
look I'm not here to debate my history, how I'm acting was trying to donate. Not trying to be difficult. I don't use GitHub often. I know people that use these forums and rather a not in public discussion hence my actions.  I've never requested help anywhere, so this is a first. I've forked files based on a tutorial video. Got nowhere, I understand now you don't agree with donations and help through discord, and I'm frustrated trying to get this to work. I've got help from people that have actually got it to work, and they couldn't figure it out. So I figured it was something more sophisticated. Thats all I was trying to accomplish by saving time. Anyway, seems I'm getting nowhere but complaints. I just wanted to setup my server and the Guide I was following got me same issue as I had on the previous guide.

**Comment by kalvx** [comment]
i think this is the thing it's failing to pull down from git. version 10.1.1 of fmt

https://github.com/fmtlib/fmt/releases

anyone having issues with cmake, when using build all: make sure to download this and replace the files in your main working directory. Reboot Visual Studio as admin make sure  not to have anything blocking or add an exemption. Try again. This fixed it for me so far. Saying that i still dont see my XI files but that may be next.

**Comment by zach2good** [comment]
You **should not** need to go and manually download any dependencies or change the contents of the cmake files.

Our CI build Windows and Linux fine here multiple times a day: https://github.com/LandSandBoat/server/actions/runs/11782919168

In the logs, you can see it going off and downloading the dependencies it needs to use in the build (fmt 10.1.1, etc.)
```
-- CPM: Adding package fmt@10.1.1 (10.1.1)
-- Version: 10.1.0
-- Build type: Debug
-- CPM: Adding package spdlog@1.12.0 (v1.12.0)
-- Build spdlog: 1.12.0
-- Build type: Debug
-- CPM: Adding package recastnavigation@0 (cd898904b[72](https://github.com/LandSandBoat/server/actions/runs/11782919168/job/32819114388#step:4:73)a300011fbb24d578620bafa08ef2c)
-- CPM: Adding package fast_obj@0 (85778da5fc320b7e52885f8e869edc079695cc79)
-- CPM: Adding package argparse@0 (f901d9edb47d45a287ca44d5bab48540c1fcdcce)
-- CPM: Adding package task_system@0 (241acb039152b646589fcbbcfb4d8d8e5bddc815)
-- CPM: Adding package efsw@0 (a064eb20e1312634813c724acc3c8229cc04e0a2)
-- CPM: Adding package jthread-lite@0 (5332bbd46dcba5f028a844795cc0931e9f2ffdf4)
-- Project 'jthread_lite', package 'jthread-lite' version: '0.1.0'
-- CPM: Adding package expected-lite@0 (45a54fac224e5aae5f8e70bb1c2423181ae554da)
-- Project 'expected_lite', package 'expected-lite' version: '0.6.3'
-- CPM: Adding package cpp-httplib@0.15.3 (v0.15.3)
-- CPM: Adding package json@0 (254395e5f7[73](https://github.com/LandSandBoat/server/actions/runs/11782919168/job/32819114388#step:4:74)1b5595e7c11ac4b929c923582114)
-- Using the multi-header code from D:/a/server/server/build/_deps/json-src/include/
-- CPM: Adding package pcg-cpp@0 (428802d1a5634f96bcd0705fab379ff0113bcf13)
-- CPM: Adding package asio@1.28.0 (asio-1-28-0)
-- Set _WIN32_WINNET=0x0A00
-- CPM: Adding package bcrypt@0 (fb50b847ae760f16ab84a36[74](https://github.com/LandSandBoat/server/actions/runs/11782919168/job/32819114388#step:4:75)52027b246df13e1)
-- Populating bcrypt
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.20348.
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: D:/a/server/server/build/_deps/bcrypt-subbuild
```

There is something going on with your system that is stopping this process.

> Reboot Visual Studio as admin make sure not to have anything blocking or add an exemption.

This is what fixed it for you, not going and getting the dependencies yourself.

**Comment by kalvx** [comment]
Thanks for the response. I am not sure what else to do I added the exemption a while ago and it had errored every time it tried to build. Someone sent me a link of the repo of the commit that it was crashing in the process. I just overwrite the files, I downloaded from that depository. No error! but now when it successfully builds all the xi_connect.exe xi_map.exe xi_search.exe xi_world.exe are not populating.  Here is my finish under cmake I guess it is missing something though.


1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="E:\Games\ffxi1.0\server\build\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe"   -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\Games\ffxi1.0\server" 2>&1"
1> Working directory: E:\Games\ffxi1.0\server\build\x64-Debug
1> [CMake] -- CMake version: 3.29.5-msvc4
1> [CMake] -- {fmt} version: 11.0.2
1> [CMake] -- Build type: Debug
1> [CMake] -- Configuring done (0.3s)
1> [CMake] -- Generating done (0.0s)
1> [CMake] -- Build files have been written to: E:/Games/ffxi1.0/server/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.

**Comment by zach2good** [comment]
You have finished the configuration step. This is only preparing the build and not executing the build itself.

Make sure you follow the setup guide _exactly_: https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide

<img width="686" alt="image" src="https://github.com/user-attachments/assets/d2d0e3d1-343d-484f-bd36-b099d6391c78">
