### ISSUE TITLE
Update auto starting server on Linux section to work with LSB

### ISSUE THREAD

**Issue by Grahf0085** [DerpyProjectGroup/topaz#6426]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

The following update to the wiki section titled "Auto-Starting the Server" will allow the server to be auto started on linux. As it stands the that section was meant to work with Topaz. It's missing the xi_world server so a service for it was added. That service is titled "lsb_world.service". Additionally, each instance of "topaz" was replaced with "lsb". I took the liberty to add comments about the User and Group directives.

#### Linux

Linux users can create several systemd services to automate the servers (make sure to update `/path/to/lsb`, and the User/Group):

```ini
#lsb.service

[Unit]
Description=Land Sand Boat - FFXI Server Emulator
Documentation=https://github.com/LandSandBoat/server/wiki/Miscellaneous-Server#linux
After=mysql.service

[Service]
Type=oneshot
ExecStart=/bin/true
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

```ini
#lsb_map.service

[Unit]
Description=LSB Map Server
Wants=network.target
StartLimitIntervalSec=120
StartLimitBurst=5
PartOf=lsb.service
After=lsb.service

[Service]
Type=simple
Restart=always
RestartSec=5
# You can use your regular system user or a custom user you make
# ie User=xiplayer or User=myusername
User=
# omit Group and it will use the Users primary group. Otherwise you can explicitly list it
# Group=
WorkingDirectory=/path/to/lsb
# For multiple map servers:
# - Make a copy of this file for each server. Rename appropriately, e.g. topaz_game-cities.service
# - Add this to a file named ip.txt in the topaz folder, replacing YOUR_PUBLIC_IP with your IP: "IP=YOUR_PUBLIC_IP"
# - Change the zone ports in zone_settings table. A custom.sql file is useful for this.
# - Remove the line below, 'ExecStart=/path/to/topaz_game'.
# - Uncomment and edit the 2 lines below with the appropriate port and log location for each zone server.
#EnvironmentFile=/path/to/topaz/ip.txt
#ExecStart=/path/to/topaz/topaz_game --ip $IP --port 54230 --log /path/to/log/map_server.log
ExecStart=/path/to/lsb/xi_map

[Install]
WantedBy=lsb.service
```

```ini
#lsb_connect.service

[Unit]
Description=LSB Connect Server
Wants=network.target
StartLimitIntervalSec=120
StartLimitBurst=5
PartOf=lsb.service
After=lsb.service

[Service]
Type=simple
Restart=always
RestartSec=5
# You can use your regular system user or a custom user you make
# ie User=xiplayer or User=myregularusername
User=
# omit Group and it will use the Users primary group. Otherwise you can explicitly list it
# Group=
WorkingDirectory=/path/to/lsb
ExecStart=/path/to/lsb/xi_connect

[Install]
WantedBy=lsb.service
```

```ini
#lsb_search.service

[Unit]
Description=LSB Search Server
Wants=network.target
StartLimitIntervalSec=120
StartLimitBurst=5
PartOf=lsb.service
After=lsb.service

[Service]
Type=simple
Restart=always
RestartSec=5
# You can use your regular system user or a custom user you make
# ie User=xiplayer or User=myregularusername
User=
# omit Group and it will use the Users primary group. Otherwise you can explicitly list it
Group=
WorkingDirectory=/path/to/lsb
ExecStart=/path/to/lsb/xi_search

[Install]
WantedBy=lsb.service
```

```ini
#lsb_world.service

[Unit]
Description=LSB World Server
Wants=network.target
StartLimitIntervalSec=120
StartLimitBurst=5
PartOf=lsb.service
After=lsb.service

[Service]
Type=simple
Restart=always
RestartSec=5
# You can use your regular system user or a custom user you make
# ie User=xiplayer or User=myregularusername
User=
# omit Group and it will use the Users primary group. Otherwise you can explicitly list it
Group=
WorkingDirectory=/path/to/lsb
ExecStart=/path/to/lsb/xi_world

[Install]
WantedBy=lsb.service

```

After adding these to `/etc/systemd/system/`, run `systemctl daemon-reload` followed by `systemctl enable lsb_connect lsb_map lsb_search lsb_world`. You can start/stop all the servers at once with `systemctl start/stop lsb` or each individual service separately. To enable auto-start, type `systemctl enable lsb`. Make sure lsb is in a location accessible to the user that will be running the service, and the correct permissions are set.

**Comment by WinterSolstice8** [comment]
You can make a PR to [lsb-wiki](https://github.com/LandSandBoat/lsb-wiki) if you feel so inclined, but thanks for pointing out there's a documentation flaw here

**Comment by Grahf0085** [comment]
> You can make a PR to [lsb-wiki](https://github.com/LandSandBoat/lsb-wiki) if you feel so inclined, but thanks for pointing out there's a documentation flaw here

Thank you I make a PR here: https://github.com/LandSandBoat/lsb-wiki/pull/98/files

**Comment by zach2good** [comment]
This was merged into the wiki
