### ISSUE TITLE
RoV progress stops at Call to Serve mission

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#643]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
RoV mission progress is halted at Call to Serve. When zoning into Port Jeuno after completing the previous mission, you should have a cutscene with Prishe, Ulmia, and Tenzen. This CS does not occur, blocking progress on RoV mission. You should also be given Cipher: Prishe II, which is not added to your inventory on zoning into Port Jeuno. I have tried at various stages of CoP, but it does not occur at any stage. I have reviewed the Port Jeuno code, and do not see this event coded.

**Comment by RAIST5150** [comment]
A very limited amount of content past TAU is currently available in general.  And even TAU is pretty restricted (no assault ranks, and no besieged, etc.).

Pretty much anything past RotZ/CoP is a big work in progress.

https://github.com/LandSandBoat/server/wiki/What-Works

We may be a bit past a few things noted in that table, but it gives a decent idea of where they stand on development.

**Comment by helixhamin** [comment]
Oh, I know. I realize it is not ready, but still wanted to mark a tracking issue anyways. One of those "Here is something to mark complete once it is complete", and easy to find out what is missing for people wanting to work on things.

**Comment by claywar** [comment]
Closing this issue.  RoV can progress through 2-13 (From the Ruins), and is awaiting further caps to implement beyond that.
