### ISSUE TITLE
🔨 VIT to DEF Conversion Ratio

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#6435]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

LSB currently uses 75 era VIT / 2 (2 VIT = 1 DEF). Retail currently uses 2 VIT = 3 DEF.

https://forum.square-enix.com/ffxi/threads/51153-2016.8.3-%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E6%83%85%E5%A0%B1
https://www.bg-wiki.com/ffxi/Vitality
https://ffxiclopedia.fandom.com/wiki/Vitality
https://wiki.ffo.jp/html/313.html

**Comment by RAIST5150** [comment]
Is there an option for such stat calc changes in the settings file with all the other era level options?

**Comment by UmeboshiXI** [comment]
There is no built in option for that at the moment. ATT/RATT are already using retail calculations.
