### ISSUE TITLE
🐛 Custom Menus seem to be broken

### ISSUE THREAD

**Issue by AuroraFlare** [DerpyProjectGroup/topaz#6455]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 11

## Branch affected by issue 
`base`

The menu seems to work incorrectly for all custom menus made in custom lua, etc. GM Home NPC, !menu !afkcheck 

## Steps to reproduce:

1. Login to GM character
2. Type !menu and see it load incorrectly

![Screenshot 2024-11-23 222820](https://github.com/user-attachments/assets/0139ddcd-ed50-415b-8872-83173ffe602e)

## Expected behavior

Should be more like:
   Test Menu (Play effect)
   Option 1: Hearts
   Option 2: Music Notes
   etc. etc.

**Comment by WinterSolstice8** [comment]
![image](https://github.com/user-attachments/assets/c232d7bf-0c1d-420a-a220-cdf450d242ad)
seems to work for me. Are you on the JP client?

**Comment by AuroraFlare** [comment]
That's weird I'll have to look, I'm using Ashita4... in the config for the ini i am using playonline=2 and ashita=2 the install is the NA FFXI right from the NA PlayOnline website. But I must be overlooking something then!

**Comment by WinterSolstice8** [comment]
yeah, same for me

```
[ashita.language]
playonline=2
ashita=2
```

weird. Does it work if you `/unloadall` first?

**Comment by AuroraFlare** [comment]
That seemed to fix it! Must be a Ashita4 plugin/addon breaking it!

**Comment by WinterSolstice8** [comment]
make sure to report back when you've isolated it, I would suspect something that interacts with /tell packets, because that's the mechanism custom menus use

**Comment by AuroraFlare** [comment]
When you mentioned /tell packets I knew exactly what it was! Honestly I never noticed it do anything and just never disabled it. But the addon was Chatfix! Thank you so much for this!
