### ISSUE TITLE
map and connect errors

### ISSUE THREAD

**Issue by justinray1982** [DerpyProjectGroup/topaz#6456]
I keep getting these errors. as soon as i log in. amy help

[map-server.log](https://github.com/user-attachments/files/17895290/map-server.log)
[connect-server.log](https://github.com/user-attachments/files/17895291/connect-server.log)

**Comment by claywar** [comment]
My guess is that this is a bad pull on your end after having made changes.  Our CI runs for every PR, and the lua errors that are being displayed in your logs don't quite match current files.

**Comment by zach2good** [comment]
Answered in https://github.com/LandSandBoat/server/issues/6457

Also please remember not to wipe out all of the checkboxes etc. (You handled this correctly in your following issue)
