### ISSUE TITLE
🐛 Multiple position issues in The Garden of Ru'Hmet's Zone.lua

### ISSUE THREAD

**Issue by Delkathus** [DerpyProjectGroup/topaz#6485]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 10

## Branch affected by issue 
`base`

## Steps to reproduce
1.) Zone in using !zone command or normally into The Garden of Ru'Hmet, you will get teleported to Abyssea - Uleguerand instead of inside of inside the garden *(i am unsure if this was intended or not to prevent unauthorized access)*.
https://github.com/LandSandBoat/server/blob/98a64931d817bcdf3ac5ce569a56b5e4673b22d1/scripts/zones/The_Garden_of_RuHmet/Zone.lua#L134

2.) There are too many declarations in this position call and it assumes the value of 36 as an invalid player and fails. Use `!pos 540, -1, -499.900, 62, 36` and it will give you the invalid player error.
https://github.com/LandSandBoat/server/blob/98a64931d817bcdf3ac5ce569a56b5e4673b22d1/scripts/zones/The_Garden_of_RuHmet/Zone.lua#L222

## Expected behavior
1.) Zone in and be actually in The Garden of Ru'Hmet.

2.) To teleport to the Empyreal Paradox staging area (entrance to the Battlefield).

**Comment by TeoTwawki** [comment]
comma comma comma chameleon... it throws you off, it throws you ooooooo-offff
