### ISSUE TITLE
🐛 Level Sync Not Refreshing properly

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6603]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

When a member of a party under level sync levels up, any member of the party can zone, disband party and get reinvited, zone back in to get level sync and retain all stats, abilities of its original level prior to level sync, checking the persons level will result in it showing its level synced level but stats and job abilities will be of its true level. As long as this does not break level sync and is done quick enough. 

![after](https://github.com/user-attachments/assets/2ea29cc5-15af-4b79-b711-79b823d1a859)
![before](https://github.com/user-attachments/assets/2a3caa33-7662-43a0-a2c6-6a66fe4aab16)

**Comment by WinterSolstice8** [comment]
do you have this commit? https://github.com/LandSandBoat/server/pull/6323/commits/43dd717ba5e82c7ac926c69917b645ba40c57147

**Comment by WinterSolstice8** [comment]
Actually, looking at it closer that might not effect this issue specifically

**Comment by WinterSolstice8** [comment]
I found the bug, or at least one cause. Unknown if there's more than one currently, but it seems that it's a race condition. I can remove the stat calculations out of the race condition to remove it as a possibility, however.

**Comment by FFXILevelDown** [comment]
We've seen the issue on galka, tested the issue on elvan male, and Hume male. Completely over looked the character because we could only recreate when the someone leveled up, and it was almost like they went through the process in enough time to zone back out and break refreshing level sync on zone.

**Comment by FFXILevelDown** [comment]
If they wait to long to zone back out, it works as intended
