### ISSUE TITLE
🐛 Player speed not reflecting Settings

### ISSUE THREAD

**Issue by FFXILevelDown** [DerpyProjectGroup/topaz#6610]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Updated to base and speed does not reflect what is in settings anymore. It defaults player speed to retail regardless of settings. Tried to alter speed in settings, reboot, rebuild etc and no change. 
## Expected behavior

Unless this was intentional, this should allow adjustment of speed thru SPEED_MOD in map.lua settings. The !setspeed command still works :).

**Comment by Mortalelite** [comment]
I also tested this and was no change to speed_mod https://github.com/LandSandBoat/server/blob/base/settings/default/map.lua#L109 using Positive or Negative results. Still ran same speed unless you used the command.

**Comment by GeneralLD** [comment]
Just pulled the update to test this out. The speed adjustment worked however it is not affecting the character animation. I move across the screen at the modded speed set in settings, but the character animation is slower than retail speed. Tested with three different servers up, one with the fix, one before speed adjustment was originally implemented in PR and one without fix but using the speed adjustment from PR and the animation is noticeable.
