### ISSUE TITLE
Trust: Klara has no WSes

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#672]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Based on wiki information, Trust Klara should have the following WSes:
Temblor Blade, Vorpal Blade
These are shown on both ffxiclopedia and BGWiki.

Based on the information in https://github.com/LandSandBoat/server/blob/base/sql/mob_skill_lists.sql none of these are entered for her.

BGWiki also shows Fast Blade, Savage Blade, although this is not confirmed. I am asking captures to check to see if they can get her to use.

**Comment by zach2good** [comment]
You do not need to open issues for every trust that doesn't fully operate, when we have an article that tracks them clearly visible from the 'what works' wiki page.

https://github.com/LandSandBoat/server/wiki/Trusts
