### ISSUE TITLE
Geodes do not drop

### ISSUE THREAD

**Issue by Endymionls** [DerpyProjectGroup/topaz#677]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

Geodes do not drop from any mobs

**Comment by TeoTwawki** [comment]
the ugly yet retail accurate way:  
https://github.com/TeoTwawki/darkstar/commit/9e8ca8f1b3d65e2c4d4a3d72c78da2c71f1af651

the shorter cleaner way but with miinor inaccuracies in processing what order thinsg happen with:  
do it in `scripts/globals/mobs.lua` inside the `onMobeDeathEx()` function

the way I am waiting for before it goes into LandSandBoat: ***???***   
¯\\\_\(ツ)\_/¯ there has to be better option. there just has to.

**Comment by RAIST5150** [comment]
Maybe could add/modify mob pools for elementals that align with proper zones/levels in retail.

Not fond of bandaid approaches like that,  but could be an option if a zone/mob mod doesn't surface by the time we really NEED some form of regular supply of them.  Don't expect we will see things like post level 75 elemental trials in play for quite a while though.

**Comment by RAIST5150** [comment]
Strange thought just hit me... would there be enough room in the flags part of a crystal's SQL to assign something to ID elemental affinity?

Just spitballing... a mod that runs a check on mobdeath if a crystal were to drop on mobs over certain range and day/weather affinity were aligned, could roll to see if the crystal would instead drop as geode/avatarite?

**Comment by TeoTwawki** [comment]
they should definitely not be added to the monsters regular loot pools.

**Comment by TeoTwawki** [comment]
> Maybe could add/modify mob pools for elementals that align with proper zones/levels in retail.
> 
> Not fond of bandaid approaches like that, but could be an option if a zone/mob mod doesn't surface by the time we really NEED some form of regular supply of them. Don't expect we will see things like post level 75 elemental trials in play for quite a while though.

> Strange thought just hit me... would there be enough room in the flags part of a crystal's SQL to assign something to ID elemental affinity?
> 
> Just spitballing... a mod that runs a check on mobdeath if a crystal were to drop on mobs over certain range and day/weather affinity were aligned, could roll to see if the crystal would instead drop as geode/avatarite?

these are not based on the mobs element at all and they should definitely not be added to the monsters regular loot pools. that causes additional problems and winds up very retail-inaccurate.

geodes (and avatarites) drop based on a few conditions having to be met:
if the player is in the level range for them to drop then the game checks if there is an active weather in zone. if there is, that element of avatarite or geode can drop. if there is NOT an active weather effect, then the matching day of the week element can drop.

These occupy a "global" slot that gets does separately than the mobs direct drops (similar to seals and crystals). I believe you can get a Geode OR an avatarite but not both in the same kill.

**Comment by RAIST5150** [comment]
Yeah.  Was just thinking, aside from sky, regular elementals only spawn where weather is present... provided it was targeted/selective and a rare enough drop rate it could be a quick/dirty alternative if they were NEEDED and no good option existed.

By no means proper... but we've seen our share of bizarre custom content added on some servers.  At least that would be a straightforward thing that could be reverted.

**Comment by TeoTwawki** [comment]
well, the code in my branch gets retail behavior mainly - the level, weather, and day all get checked and drops happen. Its an annoyingly large / tall set of switch cases but it "works".

In general, we do not do global drops accurately and this is about the same accuracy as our crystals and seals.

the fast quick easy way involves a simple table and a loop with these some conditions in mobs.lua -  the diff being nMobDeathEx() executes at a different step in the mobs "ermagawd I died _ughhhh...._" order (you'll always get keyitems and drops in a specific order on retail for example, and we do the keyitems in the script end in large part for this to match, but joe average server owner isn't going to care)

**Comment by Xaver-DaRed** [comment]
PR #681

**Comment by TeoTwawki** [comment]
knew I forgot to do something after that pr
