### ISSUE TITLE
aggressive Soldier Crawlers and Rumble Crawlers

### ISSUE THREAD

**Issue by beauxq** [DerpyProjectGroup/topaz#678]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Soldier Crawlers and Rumble Crawlers both should aggro in Crawlers' Nest and should not aggro in Elshimo Island.

https://ffxiclopedia.fandom.com/wiki/Soldier_Crawler
https://ffxiclopedia.fandom.com/wiki/Rumble_Crawler

Right now Soldier Crawlers are aggressive everywhere, and Rumble Crawlers are not aggressive anywhere.

**Comment by TeoTwawki** [comment]
the solution is to break them out into separate pool IDs in mob_pools.sql

as a work aroudn for server owners until that is done, there is a mobmod that can be applied to them on spawn that prevents the AI from agro'ing.
