### ISSUE TITLE
Build issue on Windows, incorrect path for FileWatch.hpp

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#683]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

From my past two builds I've been getting the error below. It seems to me that the path for FileWatch.hpp in luautils.cpp is missing an additional "../" prefix. At least that's what fixes the build for me. 

[build] C:\Repos\server\src\map\lua\luautils.cpp(93,10): fatal error C1083: Cannot open include file: '../../ext/filewatch/filewatch/FileWatch.hpp': No such file or directory [C:\Repos\server\build\src\map\lua\lua_bindings.vcxproj]

**Comment by helixhamin** [comment]
There is already a note in this file:

```
// TODO: Implement FileWatch backend for OSX
#ifndef __APPLE__
// TODO: Fix path
#include "../../ext/filewatch/filewatch/FileWatch.hpp"
std::unique_ptr<filewatch::FileWatch<std::string>> watch = nullptr;
#endif // __APPLE__
```

So, this is already a known issue.

**Comment by Xaver-DaRed** [comment]
He provided a posible solution to the problem. I dont see an issue with this being reported.

**Comment by zach2good** [comment]
I'm more interested in _why_ you'd have to adjust the path on your install anyway. Our CI runs fresh Windows builds multiple times per day without issue, and all mainline devs do their work on Windows, also without issue.

https://github.com/LandSandBoat/server/runs/3475027548
https://github.com/LandSandBoat/server/runs/3475027610

Anything spicy with your?:
- custom changes
- leftovers of failed merges/diff applications/rebasing etc.
- environment variables
- visual studio install (or installs)
- cmake configuration
- cmake cache
- We've had issues with spaces in paths when running from virtual machines, but that isn't the case here `C:\Repos\server\build\src\map\lua\lua_bindings.vcxproj`

When in doubt, nuke your build folder (either called `build` or `out` natively from Visual Studio) and tell VS to rebuild your cache (Project > CMake cache, or something)

**Comment by CatsEyeXI** [comment]
thanks zach ill take a look at the last few items and report

**Comment by helixhamin** [comment]
> He provided a posible solution to the problem. I dont see an issue with this being reported.

Oh no, not saying the report is a problem, just reminding that it's a known issue. Sorry, someone keeps doing that on my issues, even though they are known, so I just thought it would be good to let him know.
