### ISSUE TITLE
Pot-au-feu +1 duration is too short

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#695]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
According to the entry for it on ffxiclopedia, and the highest rated comment on FFXIAH, it should be a 1 hour duration; currently set to 30 minutes. No information about the duration on bgwiki.

**Comment by TeoTwawki** [comment]
easy enough to get retail confirmation of duration and then adjust

**Comment by CatsEyeXI** [comment]
verified in retail should be 60 mins
![image](https://user-images.githubusercontent.com/65316697/133781969-962f338e-4f26-4a7a-a5d5-495d8e26dbe0.png)

**Comment by CatsEyeXI** [comment]
#733
