### ISSUE TITLE
CoP 6-3 Pot BCNM 问题

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#698]
When I use LSB on my private server, COP 6-3 airship BCNM, after the end of the first game, I cannot view the options of the door and cannot enter the next level of work. As a result, 6-3 has to be forced to end, no matter how many I repeat. It can't be completed normally, is this a BUG? I hope it can be fixed. When the problem is solved, I will give feedback~~

**Comment by TeoTwawki** [comment]
it is possible that the NPC for that target has had its ID changed by SE updates. We are not caught up to the current client version and we may have some non matching ones in the client version we last tried to sync to as well.

**Comment by tourmaline3333** [comment]
I have same issue on Client ver 202107 and 202108.
I dont have 202106.

**Comment by jeffnavy14** [comment]
Just wanted to add I have the same issue as well on my servers.

**Comment by TeoTwawki** [comment]
per discussion #696 it appears the stage change between segments of the battlefield have broken

**Comment by GanimanSwift** [comment]
It seems that the `entity.onEventFinish` lua function does not execute after `player:startEvent(11)` finishes. This seems to be a symptom in any part of the battlefield if you can manage to progress past this one break point.

**Comment by zach2good** [comment]
Just investigated this on stream, all of the scripting and layout for this BCNM (stages, cs's, etc.) have all been broken at some point and need rewriting

**Comment by GanimanSwift** [comment]
I managed to get this in a working state. Its not too pretty, but I was able to fix it by basically moving all of the onEventFinish stuff into the bcnm instead of the other places (like mobs) where it wasn't working. It is still hacky (like how the mammet death works and the release function being in there), but probably no worse than it was last time it was in a working state.

I understand Zach said he'd work on this, but if it is worth submitting a PR for my dirty fix in the mean time I can do that. I know it'll all get overwritten anyway for new methods of doing things, but happy to submit in the interim if the maintainers think it is worth it.

**Comment by GanimanSwift** [comment]
also, Omega and Ultima are facing the wrong way when they spawn - probably need a position fix for direction in the mob table

**Comment by zach2good** [comment]
@GanimanSwift if you just push your work to a branch I can pick it up and clean it up for submission

**Comment by GanimanSwift** [comment]
> @GanimanSwift if you just push your work to a branch I can pick it up and clean it up for submission

Haven't pushed this anywhere yet. There is a bug running event 32001 after a win. Seems if you don't have the mission flagged you can exit the bcnm fine, however if you are on the mission, after getting a win event 32001 keeps you in a black screen and never finishes. There must be a bad argument somewhere in here:

`player:startEvent(32001, battlefield:getArea(), clearTime, partySize, battlefield:getTimeInside(), 1, battlefield:getLocalVar("[cs]bit"), arg8)`

Maybe [cs]bit isn't being updated properly somewhere else. Need more time to troubleshoot and clean it up a bit.

**Comment by vlukyniuk** [comment]
I think this is incorrectly associated to 6-3? Should it not be 6-4? Mamet fight works correctly. No cutscene triggered after they are killed. Transitioned to other airship with nothing to do but wait.

**Comment by Skerxan** [comment]
CoP 6-4 One To Be Feared is still broken. You can't enter the second stage.

Also the issue title should be corrected since thats what the person tried to tell us.

**Comment by tourmaline3333** [comment]
Is there anything I can do for a temporary workaround?
