### ISSUE TITLE
SMN cannot cast avatars or elementals in Escha - Zi'Tah or Escha Ru 'Aun

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#709]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything Branch
**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

xiweb (formerly Canaria), running Everything Branch

As title states.  On SMN, cannot summon avatar or elementals in current Escha zones.
<edit:  happens while in normal party as well as solo with or without trusts>
Trust spells work just fine... just cannot use the spells to summon avatars or elementals.
Try to summon say, Fenrir and it gives the generic goldish text message about not being able to use Fenrir.

No other "pet" type of jobs leveled, so no clue if it is a zone flag of sorts, or more job/spell type specific.

**Comment by TeoTwawki** [comment]
zone_misc flag

https://github.com/LandSandBoat/server/blob/base/src/map/zone.h#L449

**Comment by zanglikun** [comment]
![image](https://user-images.githubusercontent.com/61591648/132617032-c150c68b-4498-4fd8-ba99-a199aba14f83.png)

**Comment by TeoTwawki** [comment]
@zanglikun it is a binary mask - it is additive.

2448 = 0x0990 = `MISC_TRACTOR`(0x0010) + `MISC+PET`(0x0080) + `MISC_TRUST`(0x0800)

**Comment by TeoTwawki** [comment]
@zanglikun it is a binary mask - it is additive.

2448 = 0x0990 = `MISC_TRACTOR`(0x0010) + `MISC+PET`(0x0080) + `MISC_TREASURE`(0x0100) + `MISC_TRUST`(0x0800)

**Comment by zanglikun** [comment]
I see. Thank you!

**Comment by RAIST5150** [comment]
Well... that explains a lot.  Misc. Is set to 2048 in the zone settings SQL for both.  So they are set only for Trusts?

Guessing it should have at least Pet (128), Tractor (16) and Mazurka (8) added to make it 2200? Not sure about mounts (4) in Zi'Tah... never experienced the zone in retail.

**Comment by RAIST5150** [comment]
Fix submitted to base branch.  Thanks guys!
