### ISSUE TITLE
How to modify the resistance of NM to a certain kind of magic in LSB！！

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#721]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Take Fafnir as an example below

Here I am modified like this, but I still can’t make NM resist sleep
```lua
-----------------------------------
-- Area: Dragons Aery
--  HNM: Fafnir
-----------------------------------
local ID = require("scripts/zones/Dragons_Aery/IDs")
mixins = {require("scripts/mixins/rage")}
require("scripts/settings/main")
require("scripts/globals/status")
require("scripts/globals/titles")
-----------------------------------
local entity = {}

entity.onMobSpawn = function(mob)
    if xi.settings.LandKingSystem_NQ > 0 or xi.settings.LandKingSystem_HQ > 0 then
        GetNPCByID(ID.npc.FAFNIR_QM):setStatus(xi.status.DISAPPEAR)
    end
    if xi.settings.LandKingSystem_HQ == 0 then
        SetDropRate(918, 3340, 0) -- do not drop cup_of_sweet_tea
    end

    mob:setLocalVar("[rage]timer", 3600) -- 60 minutes
	mob:setMod(xi.mod.SLEEPRES, 1000) 
end

entity.onMobDeath = function(mob, player, isKiller)
    player:addTitle(xi.title.FAFNIR_SLAYER)
end

entity.onMobDespawn = function(mob)
    local ToD = GetServerVariable("[POP]Nidhogg")
    local kills = GetServerVariable("[PH]Nidhogg")
    local popNow = (math.random(1, 5) == 3 or kills > 6)

    if xi.settings.LandKingSystem_HQ ~= 1 and ToD <= os.time() and popNow then
        -- 0 = timed spawn, 1 = force pop only, 2 = BOTH
        if xi.settings.LandKingSystem_NQ == 0 then
            DisallowRespawn(ID.mob.FAFNIR, true)
        end

        DisallowRespawn(ID.mob.NIDHOGG, false)
        UpdateNMSpawnPoint(ID.mob.NIDHOGG)
        GetMobByID(ID.mob.NIDHOGG):setRespawnTime(75600 + math.random(0, 6) * 1800) -- 21 - 24 hours with half hour windows
    else
        if xi.settings.LandKingSystem_NQ ~= 1 then
            UpdateNMSpawnPoint(ID.mob.FAFNIR)
            GetMobByID(ID.mob.FAFNIR):setRespawnTime(75600 + math.random(0, 6) * 1800) -- 21 - 24 hours with half hour windows
            SetServerVariable("[PH]Nidhogg", kills + 1)
        end
    end
end

return entity
```
Even if I set it to -1000, it has no effect. NM can still sleep. All LSB and NM have this problem, and they have no resistance to sleep bind magic.

How can I modify it to make NM resistant to sleep type magic? Please help me. Thank you very much.

**Comment by TeoTwawki** [comment]
give him sleep immunity in mob_pools table of your database. there is a column for immunities, it is a mask where values are added:
https://github.com/LandSandBoat/server/blob/a092ddd5de202a23f9865e2cb40562e0e2af2094/src/map/entities/battleentity.h#L400

```cpp
enum IMMUNITY : uint16
{
    IMMUNITY_NONE        = 0x00,
    IMMUNITY_SLEEP       = 0x01,
    IMMUNITY_GRAVITY     = 0x02,
    IMMUNITY_BIND        = 0x04,
    IMMUNITY_STUN        = 0x08,
    IMMUNITY_SILENCE     = 0x10,   // 16
    IMMUNITY_PARALYZE    = 0x20,   // 32
    IMMUNITY_BLIND       = 0x40,   // 64
    IMMUNITY_SLOW        = 0x80,   // 128
    IMMUNITY_POISON      = 0x100,  // 256
    IMMUNITY_ELEGY       = 0x200,  // 512
    IMMUNITY_REQUIEM     = 0x400,  // 1024
    IMMUNITY_LIGHT_SLEEP = 0x800,  // 2048
    IMMUNITY_DARK_SLEEP  = 0x1000, // 4096
};
```

**Comment by Freetate** [comment]
Do you mean that changing the IMMUNITY value to 400 is immune to sleep?

**Comment by TeoTwawki** [comment]
> 
> 
> Do you mean that changing the IMMUNITY value to 400 is immune to sleep?

add 0x01 to whatever its existing immunity is in mob_pools table in sql database

**Comment by Snugglesffxi** [comment]
fwiw fafnir is sleepable on retail

**Comment by ShiyoKozuki** [comment]
He builds resistance, which isn't coded as a mechanic yet. Don't make him immune to sleep, sleeping wyrms is a strategy people used.

**Comment by TeoTwawki** [comment]
> He builds resistance, which isn't coded as a mechanic yet. Don't make him immune to sleep, sleeping wyrms is a strategy people used.

yeah but out resist system needs work even before accounting for build up and and sleep nuke is the red headed stepchild of the private server community anyway n- ppl see wyrms as "too easy" because of it so what he wanted to know how to do was pretty commonly done.

**Comment by TeoTwawki** [comment]
closed as there is no bug to track here that isn't covered under broader terms elsewhere (we know resistance is messy) and this is basically a discussion telling someone how to do something custom that they wanted
