### ISSUE TITLE
Store HNM ToD's in DB?

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#729]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm lucky to get 3 days uptime on my server so it's pretty rare that the HQ versions of Land Kings actually have a chance to pop. I tried playing around with the code below, but ultimately this allowed both HQ and NQ to be up at the same time. I'm not smart enough to figure this the rest of the way out. Any help would be appreciated. I think that once established, the same logic could be applied to any 24+ hour pop NM's (maybe even all eventually)?

```
zone_object.onZoneIn = function(player, prevZone)
    local cs = -1

    if (player:getXPos() == 0 and player:getYPos() == 0 and player:getZPos() ==
        0) then player:setPos(-60.006, -2.915, -39.501, 202) end

    if (xi.settings.LandKingSystem_NQ == 0) then
        if ((GetMobByID(ID.mob.FAFNIR):isSpawned() == false) or
            (GetMobByID(ID.mob.NIDHOGG):isSpawned() == false)) then
            local ToD = GetServerVariable("[TOD]Fafnir")
            local kills = GetServerVariable("[PH]Nidhogg")
            local popNow = (kills > 6) or (math.random(1, 5) == 3)
            if (ToD <= os.time() and popNow) then
                DisallowRespawn(ID.mob.FAFNIR, true)
                UpdateNMSpawnPoint(ID.mob.NIDHOGG)
                SpawnMob(ID.mob.NIDHOGG)
            elseif(ToD <= os.time()) then
                DisallowRespawn(ID.mob.NIDHOGG, true)
                UpdateNMSpawnPoint(ID.mob.FAFNIR)
                SpawnMob(ID.mob.FAFNIR)
            end
        end
    end

    return cs
end ```

**Comment by TeoTwawki** [comment]
We used to do this. it was _intentionally_ changed. not to hard to customize it back in though. Its just replacing some localVar calls with get/set serverVar, and or setting it in the zone lua. Its real easy 1 line to override spawn time in the onZoneInit script.

```lua
-- Some Random Teo custom NM >.>
GetMobByID(123456):setRespawnTime(900 * math.random(4, 12)) -- 1 to 3 hours in 15 min windows
```

I wouldn't be against some sort of wrapper for the variable like Get/SetToD() that inside it was an easy 1 place switch to decide between localvar and servervar, but I think the default should stay like it is for long winded uncle Teo historical reasons I don't have the energy to type tonight :sweat_smile:

**Comment by zach2good** [comment]
To expand on this a bit:

Here (inside the binding for `setRespawnTime`):
https://github.com/LandSandBoat/server/blob/base/src/map/lua/lua_baseentity.cpp#L12112

You could put in code similar to `SetServerVar`:
https://github.com/LandSandBoat/server/blob/base/src/map/lua/luautils.cpp#L3897-L3906

You'll have access to `PMob`, so you can use `PMob->name` etc.

That'll end up being a one-time global change that backs up all respawn times, then you just have to read them out on spawn. You'll need to be careful to make sure you don't have that sort of code running on every code that isn't an NM, or you'll be running an additional set of DB queries for every mob in the game 👀

**Comment by CatsEyeXI** [comment]
I feel like this can be closed now that the ToD retention module has been introduced.

**Comment by claywar** [comment]
Module implementation for this in #1647

**Comment by zach2good** [comment]
Has this been working as expected?
