### ISSUE TITLE
RNG has A- Archery and Marksmanship skill rank instead of A+

### ISSUE THREAD

**Issue by almuth150** [DerpyProjectGroup/topaz#746]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
[This BG wiki page](https://www.bg-wiki.com/ffxi/Category:Combat_Skills) and [this other page](https://www.bg-wiki.com/ffxi/Ranger) says RNG has A+ in those skills, but the current entries in the skill_ranks table has it set to A-.

**Comment by TeoTwawki** [comment]
It used to be lower on those pages and the files in project never got a PR updating them
https://www.bg-wiki.com/index.php?title=Ranger&diff=next&oldid=364056

https://www.bg-wiki.com/ffxi/Skill_Caps/Ranger didn't get the same update and so is still incorrect also.

_other wiki_ also has a history showing both skillcaps https://ffxiclopedia.fandom.com/wiki/Ranger?type=revision&diff=1561167&oldid=1466113


So we just need skill cap ranks table updated and pull requested: https://github.com/LandSandBoat/server/blob/base/sql/skill_ranks.sql#L14

**Comment by almuth150** [comment]
Fixed in https://github.com/LandSandBoat/server/pull/1131
