### ISSUE TITLE
How to modify to strengthen or weaken the attributes of SMN pet！！！！

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#749]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

do you know how to modify the defense and HP of SMN pets?  Such as modifying the defense and HP or attack power of carbuncle

**Comment by TeoTwawki** [comment]
mob_family_system sql table update ranks for them (pets are also mobs) or modify https://github.com/LandSandBoat/server/blob/base/src/map/utils/petutils.cpp#L451

**Comment by TeoTwawki** [comment]
not a bug

This type of question is better suited for a discussion as it falls under customization.
