### ISSUE TITLE
2_3_2_The_Emissary_Windurst.lua syntax error

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#752]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
            onEventFinish =
            {
                [53] = function(player, csid, option, npc)
                    npcUtil.giveKeyItem(xi.ki.DULL_SWORD)
                end,
```

```
[10/04/21 23:15:25:214][map][info][lua] Error running handler: .\scripts/globals/npc_util.lua:321: attempt to index local 'player' (a number value)  (luautils::print:492)
```

proposed amendment
"DULL_SWORD" and "SWORD_OFFERING" must be exchanged.
```
                    npcUtil.giveKeyItem(player, xi.ki.DULL_SWORD)
                    player:delKeyItem(xi.ki.SWORD_OFFERING)
```

**Comment by Xaver-DaRed** [comment]
I'll check it. I can add it to the PR I just opened
