### ISSUE TITLE
Bastok mission 2-3 not progressing.

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#753]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [ x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Bastok mission 2-3 not progressing.

If the order of progression is Windurst first, then Sandoria
When I talk to Halvar.
2_3_3_The_Emissary_Sandoria2.lua (Event ID:503) does not seem to be executed.

In fact, message 7889 is generated.
Moreover, in some cases I receive one message in one INCOMING and in other cases I receive two messages. Something is wrong with the behavior.

![image](https://user-images.githubusercontent.com/71148313/135905803-a8d816a0-964e-480d-acf0-08b3e833177c.png)

**Comment by Xaver-DaRed** [comment]
That second behaviour is "normal" (Double text) every 2 clicks
It happens becouse Halver's script isn't yet cleaned.

>     elseif (pNation == xi.nation.BASTOK) then
>         player:showText(npc, ID.text.HALVER_OFFSET+1092)
