### ISSUE TITLE
Windurst Quest "A Pose by Any Other Name" complete Get the reward twice.

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#755]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If you complete the quest, you will receive You have obtained two Ancient Blood reward items.
This is probably because there is a double reward code written in "quests/windurst/A_Pose_by_Any_Other_Name.lua" and "zones/Windurst_Waters/npcs/Angelica.lua".

**Comment by claywar** [comment]
Confirmed that your suspicion is correct.  Angelica's script for this quest has not been removed yet.  Will work to correct this.
