### ISSUE TITLE
"Star Onion Brigade" series of quests may be skipped.

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#770]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This will occur in the following steps: 
1. Possess the key item "Old ring". 
2. Complete quest "Truth, Justice, and the Onion Way!".
3. talk to "Kohlo-Lakolo" immediately afterwards (do not switch areas).
4. quest "Onion Rings" will be offered.
Quest "Know One's Onions" and "Inspector's Gadget!" will be skipped.

The following conditional statement is the cause

```
    elseif (OnionRings == QUEST_ACCEPTED or OnionRings == QUEST_AVAILABLE) and player:hasKeyItem(xi.ki.OLD_RING) then
        player:startEvent(430, 0, xi.ki.OLD_RING) --TODO get correct time for quest to expire.
```

It would be desirable to make the following changes

```
    elseif (OnionRings == QUEST_ACCEPTED or OnionRings == QUEST_AVAILABLE) and InspectorsGadget == QUEST_COMPLETED and player:hasKeyItem(xi.ki.OLD_RING) then
        player:startEvent(430, 0, xi.ki.OLD_RING) --TODO get correct time for quest to expire.
```

**Comment by Xaver-DaRed** [comment]
Instead, we could convert them to interaction.
I'll do just that.

**Comment by Xaver-DaRed** [comment]
PR #772
