### ISSUE TITLE
Ninjutsu Magic Bursts are not called out in chatlog

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#777]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

After someone reported that Ninjutsu seems to not magic burst i did some tests.
I tested magic bursting with darkness and hyoton: ni and came to the conclusion that ninjutsu does in fact magic burst and print out the correct dmg numbers BUT **the chatlog doesn't say "Magic Burst!"**

https://ffxiclopedia.fandom.com/wiki/Magic_Burst

**Comment by zach2good** [comment]
Good find, this would be a great way for someone to have a dig around in core:
- Probably `utils/battleutils.cpp`, `spell_container.cpp` or `spell.cpp`

**Comment by ShiyoKozuki** [comment]
Isn't it spell_list.sql msg?

**Comment by Xaver-DaRed** [comment]
in magic.lua

> spell:setMsg(spell:getMagicBurstMessage())

its probably just a matter of ninjutsus not following the same function path as regular nukes, or something

**Comment by ShiyoKozuki** [comment]
https://github.com/LandSandBoat/server/blob/base/sql/spell_list.sql#L373 
`  `magicBurstMessage` smallint(5) NOT NULL DEFAULT '0',`
https://github.com/Windower/Lua/wiki/Message-IDs
https://ffxiclopedia.fandom.com/wiki/Magic_Burst

Enfeebles(including ninjutsu/whm/blm) and blood pacts also don't display the proper messages.

**Comment by claywar** [comment]
Closed by #3391
