### ISSUE TITLE
Dreamland Dynamis enterable without CoP

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#779]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

According to reports, you can enter Dynamis - Qufim, Dynamis - Valkurm, Dynamis - Buburimu and Dynamis - Tavnazia without having completed Chains of Promathia mission 3-5 Darkness Named.
This shouldn't be the case.

https://www.bg-wiki.com/ffxi/Promathia_Mission_3-5
https://www.bg-wiki.com/ffxi/Category:Dynamis#.22Dreamworld.22_Areas

**Comment by zach2good** [comment]
Dunes entry NPC leads to global: 
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Valkurm_Dunes/npcs/Hieroglyphics.lua#L15

Entry method:
https://github.com/LandSandBoat/server/blob/base/scripts/globals/dynamis.lua#L310

There is a check for entry requirements:
https://github.com/LandSandBoat/server/blob/base/scripts/globals/dynamis.lua#L116-L121

Have you set the `FREE_COP_DYNAMIS` setting to 1? or is it malfunctioning and we need to take a look?
https://github.com/LandSandBoat/server/blob/base/scripts/settings/default/main.lua#L141

**Comment by Skerxan** [comment]
My bad, FREE_COP_DYNAMIS was set to 1.
Issue can be closed for now I think.
