### ISSUE TITLE
Wamouracampa family doesn't change form or transform

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#791]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

As of now, Wamouracampa family mobs don't change their form and therefor BLU can't learn `Cannonball` for example.
`"These larval stage Wamoura periodically switch between a curled-up and open form, even when not engaged. When curled up, their special attacks are limited to Cannonball and Heat Barrier."`

```
- Magic Defense is higher when the prince is stretched out, and is lower when it is curled up.
- Hate drops off very fast.
- Adult Wamoura will still link with princes, and vice versa.
```
`"When they are streched out they are in Defensive Stance. They get an increase in Defense and Magic Defense."`

Also, after some undetermined period of time they are actually meant to transform into Wamoura.
`"If left alone for periods of time, adventurers can actually watch the larval wamoura transform into a full adult wamoura in much the same way a caterpillar changes into a butterfly (cocoon and all)."`

It seems there are 2 different types of Adult Wamouras. 1 which come about from transformation and 1 static spawning.
And not all Wamouracampas turn into Wamouras.

https://ffxiclopedia.fandom.com/wiki/Category:Wamouracampa
https://ffxiclopedia.fandom.com/wiki/Category:Wamoura
https://ffxiclopedia.fandom.com/wiki/Wamoura_Prince
https://ffxiclopedia.fandom.com/wiki/Category_talk:Wamouracampa
https://ffxiclopedia.fandom.com/wiki/Category_talk:Wamoura
https://www.bg-wiki.com/ffxi/Category:Wamouracampa

**Comment by Skerxan** [comment]
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Halvung/mobs/Wamouracampa.lua

![Discord_1hfU2fBoPa](https://user-images.githubusercontent.com/33092280/144485048-cb527cb4-a55e-487c-be94-a5e0f3c15645.png)

**Comment by Skerxan** [comment]
Transformation capture.
https://youtu.be/hU6P67dvwyI?t=630

**Comment by siknoz** [comment]
Capped using capture suite -

Zone - Mount Zhayolm - Wamoura Prince change to Wamoura (skip to near the end)
https://youtu.be/KyzgYFoIQek
https://www.dropbox.com/scl/fi/fexzoworwajeipbxwntyl/Zone-Mount-Zhayolm-Wamoura-Prince-change-to-Wamoura.zip?rlkey=ye8ts5gqalhnoswcc5fxb93kd&dl=0

**Comment by Xaver-DaRed** [comment]
This was fixed by JCMorris Wamoura audit
