### ISSUE TITLE
Limit Breaks skippable

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#798]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

A person was able to skip LB 1 and 2 entirely and had to do LB 3 when he reached 60 cap.

We speculate it's because he got pushed above the cap thresholds of 50 and 55 by using Grounds of Valor and/or Records of Eminence EXP rewards.

Some notes:
- He leveled in Crawler's Nest.
- He never zoned in that time period and only got capped at 60 instead of 50 or 55.
- He got the LB 3 quest as his first Maat quest.
- LB 1 and 2 are not in his quest logs.
- Jobs leveled afterswards from 1 to 75 also didn't need LB 1 and 2 anymore since he did LB 5 on his first one.

**Comment by TeoTwawki** [comment]
has the servers settings changed since char creation?

at any point in the past was the characters level forcibly changed by a GM command - either up or down, or possibly by mistake and then fixed after?

just checking things known to break the cap as a side effect before anyone dives into the exp from RoE

**Comment by Skerxan** [comment]
> at any point in the past was the characters level forcibly changed by a GM command - either up or down, or possibly by mistake and then fixed after?

This could be it since there is a custom zone which caps players to 60. Sometimes players stumble into that zone. I completely forgot about it. I am asking the person in question if he was there at some point.

**Comment by TeoTwawki** [comment]
level cap status effect should be safe but any other method was used that might be the cause.

**Comment by Skerxan** [comment]
Yea he was in there and i checked the files and found this part:
```
zone_object.onZoneIn = function(player, prevZone)
    local cs = -1
    local duration = 30 + player:getMod(xi.mod.PERFECT_DODGE)
    player:addStatusEffect(xi.effect.PERFECT_DODGE, 1, 0, duration)
	player:setLevelCap(60)
```
	
Looks like that's the culprit, right?

**Comment by TeoTwawki** [comment]
> Yea he was in there and i checked the files and found this part:
> 
> ```
> zone_object.onZoneIn = function(player, prevZone)
>     local cs = -1
>     local duration = 30 + player:getMod(xi.mod.PERFECT_DODGE)
>     player:addStatusEffect(xi.effect.PERFECT_DODGE, 1, 0, duration)
> 	player:setLevelCap(60)
> ```
> 
> Looks like that's the culprit, right?


Yup! that would do it!

**Comment by TeoTwawki** [comment]
also note using that woudl also LOWER someones cap down to 60 if it was higher! very bad!

you want to use the status effect instead, this is what it was made for.

**Comment by TeoTwawki** [comment]
https://github.com/LandSandBoat/server/search?q=level_restriction

thats the thing you want. I'd suggest use in _after_ zone in, rather than in _on_ zone in.
