### ISSUE TITLE
Interaction: Add helper function for getQuestVar 

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#80]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

Was mulling over this. For separate quests that need to pull variables, would there be value in creating a helper function to provide readability? Since Quest.getVarPrefix is attached to a global, we could implement something like utils.getQuestVar(areaId, questId, value)

This could be useful for Missions as where we need to interact between Zilart/CoP and Apocalypse Nigh chain.

**Comment by KnowOne134** [comment]
Would need areaid, questId, 'naming convention', value
getQuestVar(sandy, lost_boy, Prog)
May as well add a setQuestVar also

**Comment by claywar** [comment]
Thoughts on making this a lua binding as opposed to lua function?  Same effect, but different calling style:
`player:getQuestVar(sandy, lost_boy, Prog)` vs `utils.getQuestVar(player, sandy, lost_boy, Prog)`

**Comment by TeoTwawki** [comment]
> Thoughts on making this a lua binding as opposed to lua function? Same effect, but different calling style:
> `player:getQuestVar(sandy, lost_boy, Prog)` vs `utils.getQuestVar(player, sandy, lost_boy, Prog)`
depends. 

On one hand, you might think about if the utils going to be calling an existing binding anyway? if not, the jump between C++ and lua is more expensive than a pure lua thing, but if its is going to do that anyway then we're doing more steps to get to the same result.

on the other hand, the expense in either case is pretty negligible. so then the real determination comes down to which is a better fit for scripters, and we've added [yet another kind of variable for newbies to get confused about](https://github.com/DerpyProjectGroup/topaz/wiki/Understanding-variables-%E2%80%94-a-brief-guide) so it might be worth it being a utils thing if only to distinguish it a bit better from the others.

**Comment by claywar** [comment]
Makes sense.  Overall, its a fancy wrapper for `getCharVar()`.  So that would cross over regardless.
