### ISSUE TITLE
When organizing a party of two PCs, the party leader cannot summon trust.

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#800]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When organizing a party of two PCs, the party leader cannot summon trust.
When I try to summon it, it says, "Please wait a moment and summon it again, as it is currently recruiting a party. error message is displayed.

For your information, trust has the following specification, but it does not seem to be applicable since the error cannot be avoided by changing the party leader.
"If you recruit another PC to your party, you will not be able to call trust again for 120 seconds.

Specifically, I am getting an error with the following code.

/scripts/globals/trust.lua
```
    -- Trusts not allowed in an alliance
    if caster:checkSoloPartyAlliance() == 2 then
        return xi.msg.basic.TRUST_NO_CAST_TRUST
    end
```

If you comment out the above code, you will be able to summon new trusts while forming a party with a PC, but it will need to be fixed correctly.

**Comment by RAIST5150** [comment]
Hmmm...  that is odd.  Was working fine about a month or so back.  Before we tried resynching the client once or twice. Forget exactly what version we were running against when I did the last Prime/Fen/Diablo run.

Out of curiosity, how does it handle if you have trusts summoned and then invite the other player?

**Comment by eyes-and-brain** [comment]
I tested it again.
We confirmed that if you wait a few minutes after forming a PC-only party, you can call trust.
We apologize for the inconvenience.

**Comment by eyes-and-brain** [comment]
On a minor note, it was unclear whether the exceptions to the following rules applied.

The rule is.
"If you recruit another PC to your party, you may not call a new Trust for 120 seconds."

Exception to the rule.
This restriction only applies to the PC who recruited the member, so if you invite another member into the party and change the leader, the new leader will be able to call Trust without the 120 second restriction.

This is not a party limit, but a limit on the PC you invited.
If you change the area, this time limit will be removed.
