### ISSUE TITLE
Barspells don't apply MDB from merits

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#801]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://github.com/LandSandBoat/server/blob/base/scripts/globals/effects/barfire.lua
Need:
`
 target:addMod(xi.mod.MDEF, effect:getSubPower()) `
and
`
 target:delMod(xi.mod.MDEF, effect:getSubPower())
`

**Comment by claywar** [comment]
This issue only impacts single-target versions of the spell.  At some point there's a global-not-global barspell.lua which does account for these modifiers; however, if the values passed are being handled properly in core remains to be seen.

**Comment by ShiyoKozuki** [comment]
Doesn't work for WHM barspells for me after spending merits on them.
Adding the above code gives me mdb properly.

**Comment by claywar** [comment]
Resolved with magic rewrite
```
    -- Bar-Element
    if spellEffect >= xi.effect.BARFIRE and spellEffect <= xi.effect.BARWATER then
        finalPower = finalPower + caster:getMerit(xi.merit.BAR_SPELL_EFFECT) + caster:getMod(xi.mod.BARSPELL_AMOUNT) + caster:getJobPointLevel(xi.jp.BAR_SPELL_EFFECT) * 2

    -- Bar-Status
    elseif
        spellEffect == xi.effect.BARAMNESIA or
        (spellEffect >= xi.effect.BARSLEEP and spellEffect <= xi.effect.BARVIRUS)
    then
        finalPower = finalPower + caster:getMerit(xi.merit.BAR_SPELL_EFFECT)
```
