### ISSUE TITLE
Para/Slow/blind formulas are wrong

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#804]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6503005&viewfull=1#post6503005

```
Blind (8/28)

As some players have pointed out, there were errors in the information about Enfeebling Magic given a few days ago.
 Listed below is the correct information for Blind/Blind II.

Blind (Amount physical accuracy is decreased)
Lowest value at -80 player MND compared to enemy INT: 5
Highest value at +120 player MND compared to enemy INT: 50

Blind II (Amount physical accuracy is decreased)
Lowest value at -80 player MND compared to enemy INT: 15
Highest value at +120 player MND compared to enemy INT: 90
```

Para:
  local dMND = caster:getStat(xi.mod.MND) - target:getStat(xi.mod.MND)
  local MND = caster:getStat(xi.mod.MND) 
local potency = utils.clamp(math.floor(2 * (MND+dMND)) / 10, 5, 25)

Para II:
 local potency = utils.clamp(math.floor(dMND / 4) + 20, 10, 30)

Slow:
local power = utils.clamp(math.floor(dMND * 75 / 5) + 1825, 730, 2920)  

Slow II:
local power = utils.clamp(math.floor(dMND * 226 / 15) + 2380, 1250, 3510)

Blind:
 local basePotency = utils.clamp(math.floor(dINT * 9 / 40 + 23), 5, 50) 

Blind II:
local basePotency = utils.clamp(math.floor(dINT / 3 * 8 + 45), 15, 90)

**Comment by TeoTwawki** [comment]
additional note: the merits for the tier 2's no longer exist, not sure but thought we count as if full merits after that change. the referenced post is well before the change and the wiki's do not mention. I can't seem to find the official SE statement about it atm (prolly scrolled right past where I needed to be looking, tired a f tonight).

**Comment by ShiyoKozuki** [comment]
They're at max potency unmerited now iirc.

**Comment by Xaver-DaRed** [comment]
This was fixed with the magic rewrite
