### ISSUE TITLE
Silent oils + Prism powders should always last 9m(Not Random)

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#807]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://github.com/LandSandBoat/server/blob/2dbae3a1d7e3de544670f35051620660d5f9205f/scripts/globals/items/pot_of_silent_oil.lua#L16
https://github.com/LandSandBoat/server/blob/2dbae3a1d7e3de544670f35051620660d5f9205f/scripts/globals/items/pinch_of_prism_powder.lua
Tested on retail, always showed up at same duration in tooltip.

Probably same for rainbow powder and deodorizer.

**Comment by TeoTwawki** [comment]
yeah retail updated things a long time ago. I think the spells got the memo way back in dsp, but nobody checked items.
