### ISSUE TITLE
Gaze TP moves should not work on players inflicted with blindness.

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#818]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://ffxiclopedia.fandom.com/wiki/Talk:Distant_Beliefs
`If you're a mage and are going to be focusing on spells, here's the best option to dodge this attack. Take a Blinding Potion. If you are blind, gaze attacks will miss. --RKumono 00:51, June 26, 2010 (UTC)`

**Comment by TeoTwawki** [comment]
#825

**Comment by Xaver-DaRed** [comment]
Not doubting you, but could you provide some evidence of this being a generalized mechanic? (For all gazing mobs, not just one nm, for example)
Also, does it work both ways? As in, do blinded mob gazes work?

**Comment by TeoTwawki** [comment]
https://ffxiclopedia.fandom.com/wiki/Talk:Gaze_Attack

>  I tested this today using Blinding Potions and fighting EP-DC Sand Lizards in Kuftal Tunnel. Baleful Gaze still hit me even with the Blinding Potion's Blind up. And man was that a potent Blind. Over -100 Acc. It was so much I couldn't pin down the number. -Armando 

Diff page on same wiki. They can't both be right. BG has nothing about it that I saw. Someone gonna have to go eat gaze attacks in game on retail.

**Comment by ShiyoKozuki** [comment]
> https://ffxiclopedia.fandom.com/wiki/Talk:Gaze_Attack
> 
> > I tested this today using Blinding Potions and fighting EP-DC Sand Lizards in Kuftal Tunnel. Baleful Gaze still hit me even with the Blinding Potion's Blind up. And man was that a potent Blind. Over -100 Acc. It was so much I couldn't pin down the number. -Armando
> 
> Diff page on same wiki. They can't both be right. BG has nothing about it that I saw. Someone gonna have to go eat gaze attacks in game on retail.

Awww, was hoping this was real.

**Comment by Xaver-DaRed** [comment]
> Awww, was hoping this was real.

For future issues, if you are not sure or have not tested it yourself, do not open an issue until you investigate it.

**Comment by TeoTwawki** [comment]
#shitWIkiSays
