### ISSUE TITLE
Chakra missing chat log message

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#823]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
```
    if ((target:getMaxHP() - target:getHP()) < recover) then
        recover = (target:getMaxHP() - target:getHP())
    end
    player:setHP(player:getHP() + recover)
	ability:setMsg(xi.msg.basic.JA_RECOVERS_HP)
```

**Comment by CatsEyeXI** [comment]
This seems to have already been resolved?
![image](https://user-images.githubusercontent.com/65316697/172287739-da97ea13-18e8-42e6-b3d1-b0f1f3455fd4.png)

**Comment by claywar** [comment]
![image](https://github.com/LandSandBoat/server/assets/81713309/4214ca65-e998-4e08-9eaf-a022fb34212d)
![image](https://github.com/LandSandBoat/server/assets/81713309/b098e06a-7e91-418a-9e62-b72d563ada09)

Not the same issue, but we're not adjusting the max value returned in the message for actual HP restored.  Keeping this open to track that and fix.
