### ISSUE TITLE
Cannot use Curaga V scrolls... missing scroll_of_curaga_v.lua

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#846]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything Branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
xiweb.canaria server, running everything branch.

Granted it is an Abyssea drop, so I maybe have the only one that ever showed up on our server. But that may be changing soon with the legwork that has gone into the abyssea framework.

Problem has persisted through the last two client synch attempts, so finally poked around in sql and scripts looking for it.  There is an entry for it in the spell list SQL, but no globals spell LUA for it (file series ends at curaga iv).

Expecting we may run into a lot of little gotchas like this once the first zone goes into more advanced testing... quite a few spells that need to be farmed in abyssea zones.

**Comment by RAIST5150** [comment]
Should probly clarify... there is a curaga_v.lua for the spell itself.  What is missing is the scroll_of_curaga_v.lua for using the scroll to add spell (11) so we can learn the spell.  Item ID for the scroll is 4819.

**Comment by TeoTwawki** [comment]
without said lua it will fail the check to know if you can learn the spell. copy paste and swap out the spell name/id in the item lua

**Comment by RAIST5150** [comment]
Just submitted a PR for updating item_usable.sql for the spell ID, modeled after the existing curaga entries.  Not sure if I submitted this new file properly though?  It is a simple enough thing to recreate... just need to know if I need to submit it differently?
