### ISSUE TITLE
[INFO] Chat Filters / Related Data & Packets

### ISSUE THREAD

**Issue by atom0s** [DerpyProjectGroup/topaz#855]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: (not a bug)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I am posting the information in regards to how the client handles chat filters to keep them in-sync with the server as they are stored (partially) on the server side. _This is in the effort to see them fixed on private servers, and not rely on third-party addons/plugins to maintain things. I do not have time to work on the server side of things anymore so I am sharing this for someone else whom does have the time and wants to work on it/fix it._

## Preface

FFXI was designed with some configuration data being stored to the server when adjustments are made. Although full usage of this packet seems to be forgotten about, there are a few aspects where it has been used. That being the chat filters and the clients preferred language for finding parties. The client and server handle this configuration exchange with the following packets:

  * Client To Server: `0x00DB`
  * Server To Client: `0x00B4`

At this time, the implementation inside of LSB (and past projects) is incorrect and does not handle the data for these packets properly.

See here:

 * C2S: see here: https://github.com/LandSandBoat/server/blob/340878a6adb4fecdd9bd2e56991041928e2dcd82/src/map/packet_system.cpp#L5244
 * S2C: see here: https://github.com/LandSandBoat/server/blob/340878a6adb4fecdd9bd2e56991041928e2dcd82/src/map/packets/menu_config.cpp#L28

For the client-to-server side of things, this packet actually has multiple 'modes'. (A total of 4 are inside of the client, 2 are currently used that I can trace.)

  * 0 - Chat Filter Update
  * 1 - Preferred Language Update (Chat filters seem to be sent still anyway with this mode but wouldn't rely on it.)
  * 2 - Unknown (Potentially unused.)
  * 3 - Unknown (Potentially unused.)

## Mode 0 - Chat Filters

When the client opens the chat filter window, it is populated from the games internal configuration object manager, this uses the configuration values with the following ids:

 * 50
 * 51
 * 52
 * 53
 * 71

These hold the chat filter masks, as well as the 'hold' and 'chime' information. The server does not seem to hold onto anything other than if the filter is on or off. (It does not store hold/chime data from basic testing. The client stores this locally instead.)

When changes are made and the window is closed, the client updates the configuration table with the updated values via:

```cpp
int __thiscall sub_101923F0(int *this)
{
  FUNC_Config_SetValue_Wrap(50, this[12]);
  FUNC_Config_SetValue_Wrap(51, this[13]);
  FUNC_Config_SetValue_Wrap(52, this[14]);
  FUNC_Config_SetValue_Wrap(53, this[15]);
  return FUNC_Config_SetValue_Wrap(71, this[16]);
}
```

When this happens, a callback is triggered on the data which invokes the clients packet updater to send a configuration update:

```cpp
int __cdecl sub_101A4880(int a1, int a2)
{
  if ( a1 == 50 )
  {
    if ( !(unsigned __int8)sub_100E2930(&a1) || !a1 )
      return 1;
    *(_DWORD *)(a1 + 4) = a2;
  }
  else if ( a1 == 51 )
  {
    if ( !(unsigned __int8)sub_100E2930(&a1) || !a1 )
      return 1;
    *(_DWORD *)(a1 + 8) = a2;
  }
  else
  {
    if ( a1 != 53 || !(unsigned __int8)sub_100E2930(&a1) || !a1 )
      return 1;
    *(_BYTE *)(a1 + 1) ^= (*(_BYTE *)(a1 + 1) ^ (8 * a2)) & 0x18;
  }
  if ( !(unsigned __int8)SendConfig_Mode0_ChatFilters() )
    nullsub_12(aConfigSendFail);
  return 1;
}
```

Mode 0, as stated above is used for chat filters which is sent via:

```cpp
char __cdecl SendConfig_Mode0_ChatFilters()
{
  char result; // al

  if ( dword_104D2618 )
    result = Packet_Outgoing_0DB_CharConfig(0, (*(uint32_t*)((uint32_t)::GetModuleHandleA('FFXiMain.dll') + 0x4D2618) + 0x28A20)); // 2nd param is generally zero..
  else
    result = 0;
  return result;
}
```

The packet handler to send `0x00DB` from the client is setup like this:

```cpp
char __cdecl Packet_Outgoing_0DB_CharConfig(char mode, int param)
{
  if ( !dword_104D2618 )
    return 0;

  // Prepare the buffer for the packet..
  auto packet = FUNC_BuildOutgoingPacket(219, 1, 1);
  if ( !packet )
    return 0;

  // Populate the packet buffer data..
  const auto cfg = (*(uint32_t*)((uint32_t)::GetModuleHandleA('FFXiMain.dll') + 0x4D2618) + 0x28A00);

  *(uint32_t*)(packet + 0x04)   = 0;
  *(uint8_t*)(packet + 0x05)    = 0;
  *(uint8_t*)(packet + 0x06)    = mode; // 0 = Chat filters, 1 = Preferred Languages, 2+3 = Unknown but in the client.
  *(uint32_t*)(packet + 0x08)   = *(unit32_t*)(cfg + 0x00); // Name+Config Mask
  *(uint32_t*)(packet + 0x0C)   = *(unit32_t*)(cfg + 0x04); // Chat Filter Mask
  *(uint32_t*)(packet + 0x10)   = *(unit32_t*)(cfg + 0x08); // Chat Filter Mask
  *(uint32_t*)(packet + 0x24)   = param;

  // Mark the packet as ready for queueing/to be sent..
  FUNC_QueueOutgoingPacket_Wrap((int)packet, 40, 0);

  return 1;
}
```

## Mode 1 - Preferred Language

When the client alters the preferred languages they wish to party with, the following is called: _(Set via Menu > Party > Languages)_

```cpp
/**
 * @param {int} langs - The languages mask of what the client has enabled.
 *
 * @note
 *      These are set via Menu > Party > Languages
 */
char __cdecl SendConfig_Mode1_PreferredLanguage(int langs)
{
  return Packet_Outgoing_0DB_CharConfig(1, langs);
}
```

The preferred languages value is stored in the client configuration table as id: 152

The language mask values are:

  * 0x01 - Japanese
  * 0x02 - English
  * 0x04 - German
  * 0x08 - French
  * 0x10 - Other

## Mode 2 & 3 - Unknown

At this time, there does not seem to be references to these modes being invoked. They may have been unfinished configuration storages as the packet is larger than what is currently put to use. Mode 0 and 1 only use a small amount of the packet. There is still around 16 bytes of unused space that could be for other configuration data they had planned to sync to the server.

# Server To Client Configuration Update

When the server sends the client back their configuration information, it is sent via: `0x00B4`

```cpp
char __cdecl Packet_Incoming_0B4_CharConfig(int a1, int a2, int packet)
{
  *(_DWORD *)(a1 + 0x28A00) = *(_DWORD *)(packet + 0x04);   // Name+Config Mask
  *(_DWORD *)(a1 + 0x28A04) = *(_DWORD *)(packet + 0x08);   // Chat Filter Mask
  *(_DWORD *)(a1 + 0x28A08) = *(_DWORD *)(packet + 0x0C);   // Chat Filter Mask
  *(_WORD *)(a1 + 0x3C7EC) = *(_WORD *)(packet + 0x10);     // Linkshell Flag. (See notes below, this should be 0.)
  *(_BYTE *)(a1 + 0x28A1C) = *(_BYTE *)(packet + 0x12);     // Area Code (Used with help desk menu.)
  return 1;
}
```

This is what the linkshell breaking looks like when `0x3C7EC` is set to anything other than 0:

![https://i.imgur.com/6XjWHgi.png](https://i.imgur.com/6XjWHgi.png)

![https://i.imgur.com/kW3656k.png](https://i.imgur.com/kW3656k.png)

This is checked with the following chat handler function to prefix the linkshell messages with their given [1], [2], [3] tag:

```cpp
char *__cdecl sub_100E1A70(char *Buffer, char chatMode, char disablePrefix)
{
  char *result; // eax

  result = Buffer;
  *Buffer = 0;
  if ( !disablePrefix )
  {
    switch ( chatMode )
    {
      case 5: // Linkshell 1
        result = (char *)sprintf(Buffer, ::a1); // [1]
        break;
      case 27: // Linkshell 2
        result = (char *)sprintf(Buffer, ::a2); // [2]
        break;
      case 30: // Linkshell 3
        result = (char *)sprintf(Buffer, ::a3); // [3]
        break;
    }
  }
  return result;
}
```

The value stored in the `0x3C7EC` offset based address is used as a means to disable the linkshell prefix in the above function. Which means it appears this value should currently always be 0, and that prehaps, extended chat options were planned but never implemented. _(Disabling the prefix causes other aspects to break making this seem like an unfinished feature as seen in the pictures above.)_

The value stored in the `0x28A1C` offset based address is the client 'area code'. This appears to be used only with the help desk menu related interactions. This value is only set from the server and is generally 2. Otherwise, the client only ever defaults this value to 0 until it has received a `0x00B4` from the server with an updated code id to use. The client has a function that is used with the help desk that dumps some information that is uploaded to the server. This value is marked/named as 'AREACODE'.

If I were to take a guess, this appears to probably be a region based id/code to tell a GM what part of the world you are in. Perhaps this was used to handle telling a GM how to greet someone (ie. Good morning, Good afternoon, Good evening, etc.) or something similar. A way to test this if it is even used anymore would be to connect to retail and monitor what this value is while using a VPN. Connect from multiple different areas across the world and see if you ever get anything other than 2. (This does not seem to be tied to your client language at all.)

_This should be all the information needed to get chat filters working properly as well as to update the other incorrect data currently present for the packets involved._

_Note: Other data may be present in the packet, but the client does not expect/use it. This is strictly based on reversed information that the client is actually using._

**Comment by atom0s** [comment]
Tagging https://github.com/LandSandBoat/server/issues/512 for reference for when this is looked into. (Will fix that issue as well.)

**Comment by ghost** [comment]
Here's my original chat filter research made from retail packet inspection in June.

Say/Shout/Yell/Emote/Job emote/Others' Synthesis and Fishing/Others' Lotting Results are filtered on the server. First five can be implemented by not sending the packet to anybody with the respective filter on; synth is similar but you should always see your own synthesis and fishing results regardless of settings; lotting results are sent to everyone, except those with it filtered will get a packet with the other lotters' names (the lotter's name at 0x26 in the treasure lot packet D3) nul'd out. Messages from GMs should possibly not be filtered.

Assist E/J, Campaign and Alter Egos were not tested.

For the most part, it looks like battle messages are handled on the client, except status effect messages may need some additional consideration? I have not looked into that yet.

```
Chat Filters flags, 10 bytes, starting at the second byte of MenuConfig
 2 3 4 5 6 7 8 9 a b
mcmcmccfcfcfcfcfcfcf
00000001000000000000 say
00000000000000000008 assist j
00000000000000000010 assist e
00000008000000000000 emotes
00000002000000000000 shout
00000000000000000001 yell
00000010000000000000 special actions started on/by you
00000020000000000000 special actions effects on/by you
00000040000000000000 attacks by you
00000080000000000000 missed attacks by you
00000000010000000000 attacks you evade
00000000020000000000 damage you take
00000000008000000000 special actions started on/by party
00000000200000000000 special action effects on/by party
00000000400000000000 attacks by party
00000000800000000000 missed attacks by party
00000000000100000000 attacks evaded by party
00000000000200000000 damage taken by party
00000000000001000000 special actions started on/by allies
00000000000400000000 special action effects on/by allies
00000000000800000000 attacks by allies
00000000001000000000 missed attacks by allies
00000000002000000000 attacks evaded by allies
00000000004000000000 damage taken by allies
00000000000000000200 special actions started on/by foes
00000000000000000100 special action effects on/by foes
00000000000000100000 attacks by foes
00000000000000200000 missed attacks by foes
00000000000000400000 attacks evaded by foes
00000000000000800000 damage taken by foes
00000000000000080000 special actions started on/by others
00000000000000040000 special action effects on/by others
00000000000010000000 attacks by others
00000000000020000000 missed attacks by others
00000000000000010000 attacks evaded by others
00000000000000020000 damage taken by others
00000000000002000000 special actions started on/by npcs
00000000040000000000 special action effects on/by npcs
00000000080000000000 attacks by npcs
00000000100000000000 missed attacks by npcs
00000000000004000000 other's synthesis and fishing results
00000000000008000000 lot results
00000000000000000400 campaign-related data
00000000000000000800 tell messages deemed spam
00000000000000001000 shout/yell messages deemed spam
00000000000000008000 job-specific emote
00000000000000000002 messages from alter egos
08000000000000000000 check notices  (1 - not a flag, but a counter)
10000000000000000000 bazaar notices (2 - not a flag, but a counter)
18000000000000000000 countdowns     (3 - not a flag, but a counter)

All filters set:
180004FBFFFF3FFF9F1B

All filters unset:
00000400000000000000

***Clarification to above***
MenuConfig (the four bytes marked `mc` below) and ChatFilter (the 8 bytes marked `cf`) below are sent together in 0x00A (Zone In), 0x0B4 (Menu Config), and 0x0DB.  The System Lv. X chat filter bits are stored in the second byte of MenuConfig.

For now making the assumption that Chat Filter is 8 bytes and not 7. The last byte has always been observed to be 0 so far.


Incoming (to client) - 0x00a (Zone In), sent after a zone, etc.
0A820100AAAAAAAABBBB0040E7FB24C29A99A1C0B4087443000000003832640000050000000000000001000000000000EE000000590300009B3CC7602BBF96240000EE000107B710B720B730B740A050C261C271008097009700970097000000000000000000000001000000F6010B0080000B000F00170000000000000000000200000056656C796E00000000000000000000000000000043A4122C00000000F5A7220020A003003800230101000300070000001301020D7FB67B000132290F0E10480101250E0132320101620071005F0065005D00500053006B009A005200740044005A004C00170700001400000001000000mcmcmcmccfcfcfcfcfcfcfcf01000000

Incoming (to client) - 0x0b4 (Menu Config), sent in reply to 0x0db and 0x0dc, etc.
B40C0300 mc mc mc mc cf cf cf cf cf cf cf cf 00 00 01 00 02 00 00 00
          4  5  6  7  8  9 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17
            18 00 04 FB FF FF 3F FF 9F 1B 00             01 - Japanese \
         01 - NFLAG_INVITE                ^^ unused?     02 - English  | Party > Languages (search.language) bit flags
         02 - NFLAG_AWAY                                 04 - German   | 0x00 -> ignore / do not overwrite
         04 - NFLAG_ANON                                 08 - French   |
         18 - unknown                                    10 - Unknown  /
            08 - NFLAG_SYSTEM_FILTER_L \ System Lv. X Chat Filter
            10 - NFLAG_SYSTEM_FILTER_H /
            40 - NFLAG_AUTOTARGET
            80 - NFLAG_AUTOGROUP
                  02 - NFLAG_MENTOR
                  04 - NFLAG_NEWPLAYER
                  08 - NFLAG_DISPLAYHEAD
                  20 - NFLAG_RECRUIT

Outgoing (from client) - 0x0db, sent when client changes chat filters
DB14030000000100 mc mc mc mc cf cf cf cf cf cf cf cf 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
                  8  9  a  b  c  d  e  f 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27
                    18 00 04 FB FF FF 3F FF 9F 1B 00                                                 01 - Japanese \
                 01 - NFLAG_INVITE                ^^ unused?                                         02 - English  | Party > Languages (search.language) bit flags
                 02 - NFLAG_AWAY                                                                     04 - German   | 0x00 -> ignore / do not overwrite
                 04 - NFLAG_ANON                                                                     08 - French   |
                 18 - unknown                                                                        10 - Unknown  /
                    08 - NFLAG_SYSTEM_FILTER_L \ System Lv. X Chat Filter
                    10 - NFLAG_SYSTEM_FILTER_H /
                    40 - NFLAG_AUTOTARGET
                    80 - NFLAG_AUTOGROUP
                          02 - NFLAG_MENTOR
                          04 - NFLAG_NEWPLAYER
                          08 - NFLAG_DISPLAYHEAD
                          20 - NFLAG_RECRUIT

*Random observation - if the 0x0B4 reply changes the client's state, the client will send an updated 0x0DB
```
