### ISSUE TITLE
Manipulator is bugged and doesn't patrol

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#859]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Even fixing this line doesn't fix him for me.
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Temple_of_Uggalepih/mobs/Manipulator.lua#L68

**Comment by TeoTwawki** [comment]
I'll fix him - he starts off pathing correct but when he gets stopped he fails resuming properly

**Comment by TeoTwawki** [comment]
#867 & #2740 should have this working now, open new issue if something is still wrong
