### ISSUE TITLE
Worm shouldn't cast in melee range

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#863]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

family Worm mixin

```
        local targ = mob:getTarget()
        if targ then
            if mob:checkDistance(targ) < 3 then
               mob:SetMagicCastingEnabled(false)
            else 
                mob:SetMagicCastingEnabled(true)       
            end
          end
                 

```

**Comment by TeoTwawki** [comment]
For desert worms, your assertion is correct. But its not every worm game wide. Worm behaviors aren't universally consistent in retail: Many will still cast, but less often.

Related is an issue about caster mobs opening their aggro with an immediate cast. 

I had started to document it back in an old topaz issue before someones meltdown demotivated me. topaz next imported that issue but I could not longer edit my post and had already been away from the task too long. https://github.com/topaz-next/topaz/issues/2222#issuecomment-747261721

Worms in Koroloka and Qufim will point blank nuke (or rasp) me if they are alive long enough to do so. 
_(note to self: go time it and see if timing is constant too)_

**Comment by Xaver-DaRed** [comment]
So, this is only true for certain worms, is what I got from digging arround Teo's comments in different PRs and chats.
