### ISSUE TITLE
DNC AF Quest "Comeback Queen" doesn't progress

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#866]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Player reports this:
`"Started dancer af3 quest "Comeback Queen" and got the initial cutscene and key item from Laila. I then went to Harmodios in Bastok where I got the next cutscene, but when I go back to Laila she tells me to go to Harmodios and the cutscene just repeats itself over again so I'm unable to continue the quest."`
`"No lure of the wildcat active and yes I talked to the other two dancers"`
`"She just keeps saying to pass wyatt's proposal to the owner of the music shop in bastok markets."`

https://github.com/LandSandBoat/server/blob/base/scripts/zones/Bastok_Markets/npcs/Harmodios.lua
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Upper_Jeuno/npcs/Laila.lua
https://ffxiclopedia.fandom.com/wiki/Comeback_Queen
https://ffxiclopedia.fandom.com/wiki/Talk:Comeback_Queen
https://www.bg-wiki.com/ffxi/Comeback_Queen
https://www.bg-wiki.com/ffxi/Talk:Comeback_Queen

**Comment by Omnione** [comment]
First things first do you still have the War Hoop?,
If no, redo that first, then try again.
If yes, report back and it can be looked at further.

**Comment by Skerxan** [comment]
The player in question has her War Hoop still, yes.

**Comment by RAIST5150** [comment]
Was the KI Wyatt's Proposal given?

**Comment by Skerxan** [comment]
Yes, it's under temporary key items.

**Comment by RAIST5150** [comment]
Would hazard a guess Harmodios is not setting the charvar to 2?

Looks like a charvar of 1 triggers 490, and then 490 triggers 491, which updates the charvar to 2.

So basically, get 2 events from Harmodios that would set you up for going back to Laila?

Perhaps talking to Harmodios twice back to back will trigger the extra event?

Possible there could be an issue of ordering in the script as well?  The call for 490 on charvar 1 and the expected follow up for 491 and update to charvar 2 is broken up by the vending portion of Harmodios script.  There is an "else" after 490 that goes through his shop, and then all this follows after all that ends:

```lua
entity.onEventFinish = function(player, csid, option)
    if csid == 430 then
         player:setCharVar("WildcatBastok", utils.mask.setBit(player:getCharVar("WildcatBastok"), 10, true))
    elseif csid == 490 then
        player:startEvent(491)
    elseif csid == 491 then
        player:setCharVar("comebackQueenCS", 2)
    end
end
```
Flow for it just seems a bit odd... like it may have potential to back out of the script before 491 can be called/detected to update charvar to 2?

**Comment by hooksta4** [comment]
If you switch the player:setCharVar("comebackQueenCS", 2) to the elseif csid == 490 it will work correctly I believe. 

491 is not a typical cs, its just a line that says "A collaboration of circus and dance, huh? Now that's something.... "


    elseif csid == 490 then
        player:startEvent(491)
		player:setCharVar("comebackQueenCS", 2)
    elseif csid == 491 then
    
    I suck at github so Ill just leave this here and hopefully someone who is better at it can do it. Tested and confirm worked on test server. 
![Capture](https://user-images.githubusercontent.com/13935086/141230971-7662e1dd-2294-41b7-adaf-c72420e5879c.PNG)

**Comment by claywar** [comment]
Closing this issue after recent commit.  There are still open issues for this quest though to handle minigame.
