### ISSUE TITLE
Berserk and Defender should be stackable

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#868]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://ffxiclopedia.fandom.com/wiki/Talk:Berserk
https://ffxi.allakhazam.com/wiki/Defender

https://github.com/LandSandBoat/server/blob/base/sql/status_effects.sql#L93
Fixes it:
```
INSERT INTO `status_effects` VALUES (56,'berserk',41,56,0,0,0,0,1,0,0);
INSERT INTO `status_effects` VALUES (57,'defender',41,57,0,0,0,0,4,0,0);

```

**Comment by TeoTwawki** [comment]
I complained about this 2 projects ago and then forgot about it.

**Comment by TeoTwawki** [comment]
you don't need to have their own effect IDs in the type field. That field just tells it to erase that effect ID. I just PR'd putting 0 to that field. I didn't make and flag changes (I not your snippet changes defenders flags) as I am solely handling the stacking.
