### ISSUE TITLE
[Limbus] logged out players do not get kicked out on logging back in after the battle end

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#886]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: All

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. enter any Limbus battlefield
2. log out.
3. log back in long after your "bcnm" has ended
4. be amazed as you are trapped forever in a bcnm with no mobs and no exit till a GM moves you out.

**Comment by zach2good** [comment]
This might also be an issue for people who DC in instances
