### ISSUE TITLE
[Suggestion] Add Craft-related caps/settings to main.lua

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#889]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

As the name suggests, it would probably be a nice addition to be able to have some crafting-related settings.
For example setting the max cap for the main craft or sub crafts. Changing from the modern 110/70 back to 100/60. Or choose how many Main crafts are allowed. Change how fishing is exempt from the main craft and do that with other crafts.
I know you can change most of these manually but ya know, consistency.
Just to throw some ideas.

**Comment by TeoTwawki** [comment]
https://github.com/LandSandBoat/server/blob/base/conf/default/map.conf#L143

covered in conf, because server needed to know outside of scripts

**Comment by Skerxan** [comment]
Ahh I see, thanks for the info! You can close this then if it's impossible or redundant.
