### ISSUE TITLE
Loot allocation for NM "No'Mho Crimsonarmor"

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#891]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Loot specifications for NM "No'Mho Crimsonarmor" are as follows.
**It has a 100% chance of dropping "Bonze's Circlet" or "Pixie Mace".**

However, when we actually tested it, we found the following cases.
- Nothing is dropped.
- Drops both "Bonze's Circlet" and "Pixie Mace".

**Comment by TeoTwawki** [comment]
Thats a surprise I don’t think  I’ve ever seen him not drop the circlet but neither item is rare flagged so can’t be a case of already carrying it.

**Comment by Skerxan** [comment]
That special drop mechanic isn't working afaik. Our server also dropped both Pixie and Defending at one point. Which means that TH is affecting them. Don't know if it's a known issue.

**Comment by TeoTwawki** [comment]
> That special drop mechanic isn't working afaik. Our server also dropped both Pixie and Defending at one point. Which means that TH is affecting them. Don't know if it's a known issue.

I read the issue report as saying what happened on retail.

We have the drop group feature working now after years on not having it, however not all loot pools in the sql table were updated for it.

If the issue is its supposed to be one or the other but is not, that is easily fixed!
