### ISSUE TITLE
[Assault] Leujaoam Cleansing - blocked ice gate and not map [base 0e6ea5d]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#897]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I know Assault is on its early implementation but wanted to submit anything i find 😄 

Assault mission Leujaoam Cleansing cannot be completed as an ice path is blocked off.

No map is given when going inside the instance.

![clensing](https://user-images.githubusercontent.com/26943220/139566060-cfdf5880-4208-478d-9023-2171341517db.PNG)

**Comment by Omnione** [comment]
Shouldnt be able to call trust either

**Comment by KnowOne134** [comment]
Ok. I know issue, I can fix maps and door way later today. 
Not sure how we want to handle maps though. In retail they appear temp only when in zone and remove when leave. 
On eden I just add them on mission Giver if you don't have it and never take them away

**Comment by kaincenteno** [comment]
thanks @KnowOne134  i can confirm this as resolved with #901
