### ISSUE TITLE
[Assault] Vendors don't deduct Assault Points

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#899]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When you got enough Assault Points and try to buy an item which intervenes with the prompt shown in the screenshot then it won't deduct the points but you get the item.

```
local choice = items[item]
            if choice and npcUtil.giveItem(player, choice.itemid) then
                player:delAssaultPoint("LEUJAOAM_ASSAULT_POINT", choice.price)
            end
```

Bonus problem: As you can see the prompt even triggers on [ALL] jobs gear.

![xiloader_TKQQu5MUts](https://user-images.githubusercontent.com/33092280/139590466-9e578dac-0aae-4b6a-b098-4bf8eb86ef11.png)

**Comment by KnowOne134** [comment]
```local choice = items[item]
            if choice and npcUtil.giveItem(player, choice.itemid) then
                player:delAssaultPoint("LEUJAOAM_ASSAULT_POINT", choice.price)
            end```

this is old code updated on base is now

```local choice = items[item]
            if choice and npcUtil.giveItem(player, choice.itemid) then
                player:delAssaultPoint(xi.assaultUtil.assaultArea.LEUJAOAM_SANCTUM, choice.price)
            end```

i am checking now and on my 3rd npc i did find an error to submit though, but other are working correctly

**Comment by Skerxan** [comment]
So I updated all the Assault NPCs with the new code. Now when I purchase an item **it will deduct the points but I don't get the item anymore**... Tried with several of them. Also all of them give me the "not right job" prompt. Did I overlook anything? Any other scripts I should look into? 
This is as DRG:
![xiloader_DGb8Hb8ABG](https://user-images.githubusercontent.com/33092280/139925583-213f9578-b70d-43eb-a7e7-3014eb2d5054.png)

**Comment by KnowOne134** [comment]
Do you have an error in the map log?

**Comment by KnowOne134** [comment]
Do you have an error in the map log?

**Comment by Skerxan** [comment]
No error whatsoever :/

**Comment by claywar** [comment]
Most likely there's some missing parameters which cause that 'You can't equip' dialog.  Might be worth capturing more info from retail to cover that.

**Comment by KnowOne134** [comment]
I know how to fix the can't wear issue I just haven't. I forget about it
becuase eternity addon skips it entirely and I never see it to implement

**Comment by KnowOne134** [comment]
ah, looks like i made the canEquip on eden, sample:
```lua
function onEventUpdate(player, csid, option)
    if csid == 277 and option >= 16386 and option <= 180226 then
        local item = bit.rshift(option,14)
        local choice = sales[item]
        local assaultPoints = player:getAssaultPoint(ILRUSI_ASSAULT_POINT)
        local canEquip = player:canEquipItem(choice.itemid) and 2 or 0
        
        player:updateEvent(0,0,assaultPoints,0,canEquip)
    end
end
```

**Comment by KnowOne134** [comment]
adding the code for can/cant equip but unchanged the rewards code and i can gain the items you tried, so there is something wrong on your end
![image](https://user-images.githubusercontent.com/35616771/139999986-1cd81beb-e7eb-4c9f-a801-2b5ab8effe7c.png)

**Comment by Skerxan** [comment]
I updated to the most recent version and now it seems to work. Thanks One!
