### ISSUE TITLE
Mob Astral Flow avatar is not despawned if mob killed before ability triggers

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#908]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Precondition: Mob is SMN with job_special mixin

Procedure:
1. Have mob trigger Astral Flow (New avatar summoned)
2. Defeat mob before Astral flow ability is used (right after spawning avatar)

Results:
1. Avatar is not despawned on mob death
2. Avatar is not despawned upon leaving battlefield (if BCNM)

Evidence of mob persisting after leaving battlefield can be seen with findPath errors in log:
![image](https://user-images.githubusercontent.com/81713309/139687403-951f8de1-8166-4c07-8ace-50da16d321c1.png)

**Comment by TeoTwawki** [comment]
knew I was forgetting something when I made  #903  lol

**Comment by TeoTwawki** [comment]
merged issues
