### ISSUE TITLE
Windurst Quest "Glyph Hanger" The reward specifications are outdated

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#915]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The current implementation is

- If you don't have "Map of the Horutoto Ruins".
Give "Map of the Horutoto Ruins"
- If you have "Map of the Horutoto Ruins".
Nothing?

The new specifications are as follows
- If you don't have "Map of the Horutoto Ruins".
Give "Map of the Horutoto Ruins" +  Experience 2000
- If you have "Map of the Horutoto Ruins".
Experience 2000

**Comment by TeoTwawki** [comment]
This updated reward is true for every map quest. I have no idea which (if any) have been updated, or if they all have the same reward amount.

**Comment by claywar** [comment]
I was working under the assumption that this was the case with the current implementation.  Checking now
