### ISSUE TITLE
[Limbus] Enter with a party

### ISSUE THREAD

**Issue by Chronos77** [DerpyProjectGroup/topaz#919]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Make a party
Enter with the first player in limbus (i try with Apollyon SW)
Enter with the second player 

In the game chat:
![image](https://user-images.githubusercontent.com/1618002/140435544-c6dca7b9-824c-41cb-a099-d468ae35cd58.png)

In the log server:
`[11/04/21 23:37:37:780][map][warning][warning] SmallPacket0x17: Incorrect NPC(1025,5) type(4) (SmallPacket0x017:716)`

Screen of the first player:
![image](https://user-images.githubusercontent.com/1618002/140435961-0ac063f9-46de-4633-9573-9b2de601212e.png)

Screen of the second player:
![image](https://user-images.githubusercontent.com/1618002/140436028-1c3d7c08-e045-416d-b5dd-1c788b18a206.png)

And first player cannot cast spell on the other player

If it can help, i have try with another BC and it's working....

**Comment by TeoTwawki** [comment]
[After they exit, does one of them have BCNM status forever?](https://github.com/LandSandBoat/server/issues/635#issuecomment-953155370)

**Comment by TeoTwawki** [comment]
also @Chronos77 does this only happen when multiboxing for you?

I've been clearing limbus with a party without issue, but one of my players trips this bug every single time they enter.

@AppleCrumble1 now that we have a 2nd person this happens to, we need to figure out what you both have in common!

**Comment by ghost** [comment]
I would like to mention that I am not able to enter with a party. and stuck on loop for battlefield that can not leave.

**Comment by TeoTwawki** [comment]
> I would like to mention that I am not able to enter with a party. and stuck on loop for battlefield that can not leave.

a GM or server admin needs to delete the battlefield status off affected characters if its the same bug I saw.

**Comment by ghost** [comment]
Ok thanks. Just question what would that be under. Only way I get to go away reload the DB.

**Comment by Brierre** [comment]
Are you a gm?  !deleffect 254

**Comment by ghost** [comment]
I am set as a GM. I will keep that in mind. was just weird that my buddy could enter but then I could not. will try again later

**Comment by Brierre** [comment]
Was your buddy stuck with battlefield status after he left the first time?
You only get locked out after the initial lockout if you've got a residual
status effect.

**Comment by ghost** [comment]
he zoned in and then I got message for light faint and I could not enter. But I will try again once able to and report the outcome

**Comment by XsoulsinX** [comment]
Ok I went to test solo and I can no enter it. I do meet requirements. If I toggle on GM it shows up all the floors but can not enter when toggle off GM. Not sure what I am missing

**Comment by Xaver-DaRed** [comment]
This issue only happens on SW Apollyon, becouse it's glitched on enter.
Note for future me: "Close this once you finish Apollyons"
