### ISSUE TITLE
[Bug] Jeuno Holiday music not working

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#936]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

the holidays approaching reminded me that Jeuno zones alternate song for December doesn't change and stays with the original one

https://github.com/LandSandBoat/server/blob/2dbae3a1d7e3de544670f35051620660d5f9205f/scripts/zones/Lower_Jeuno/Zone.lua#L28

**Comment by TeoTwawki** [comment]
As a work around move it out of `onZoneIn()` and into `afterZoneIn()`

The existing code _used to_ work but some timing changes and when packets land broke it.

Future plans are for a new binding that acts on the zone object instead of the player, so that the player will receive the appropriate music packets when they zone change because thats what it will read from the zone in packet. The existing binding sends an extra packet, which was not exactly retail.

**Comment by kaincenteno** [comment]
> As a work around move it out of `onZoneIn()` and into `afterZoneIn()`
> 
> The existing code _used to_ work but some timing changes and when packets land broke it.
> 
> Future plans are for a new binding that acts on the zone object instead of the player, so that the player will receive the appropriate music packets when they zone change because thats what it will read from the zone in packet. The existing binding sends an extra packet, which was not exactly retail.

i think i tried that before and it makes the music stop when zoning in and restarts afterZoneIn. I don't remember but I can try. Just wanted to open up the bug so it's documented :smile: 

thanks Teo :smile:

**Comment by TeoTwawki** [comment]
yeah its a little glitchy right as you arrive but a second later its playing normally. I used the same hack on demi.
