### ISSUE TITLE
New character sequence is skipped if first login attempt fails

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#938]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Delete character in existing slot
2. Create a new character in the same slot, and attempt to enter game

Separate issue is that for some reason, initial login attempt on the new character fails for a period of time; This seems to recover after a few minutes, but each time Packet 0x00A is processed, playtime is incremented and updated.  When the character is finally able to login, playtime will be != 0, and new player sequence will be skipped.

**Comment by TeoTwawki** [comment]
```lua
    -- FIRST LOGIN (START CS)
    if player:getPlaytime(false) == 0 then
        if NEW_CHARACTER_CUTSCENE == 1 then
            cs = 0
        end
```
we could add a variable to new chars that gets removed after having seen the cs, similar to how we handle moghouse first time explanation.

As for the initial login failure, thats been around for nearly a decade now but I've personally never had it happen to me through countless test chars and multiple servers. I wonder if the server has to have some load going on to trigger it. (I played era when it was midsize before it became gigantic, and all other server I tried including my own have been small)

**Comment by claywar** [comment]
It seems time-dependent, but I can reliably reproduce it on my end now.  Character exists/has logged in in slot 3 (not sure if relevant), delete char, and within ~5min create a new character in the same slot.

I wonder if there's something that's not being cleaned up within that time frame.
