### ISSUE TITLE
Rolanberry Turkey (food) not usable, missing multiple elements to make usable

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#943]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Got some of these during last login campaign, but cannot use them.

https://ffxiclopedia.fandom.com/wiki/Rolanberry_Turkey
Food Effects: (4 hours, All Races)

    STR +10
    Attack +20% (Max. 120 @ 600 Base Attack)
    Ranged Attack +20% (Max. 120 @ 600 Base Ranged Attack)
    Counter +10
    Resist Amnesia +10

It is present in item_basic.sql:
```lua
INSERT INTO `item_basic` VALUES (6576,0,'turkey_with_rolanberry_sauce','rol._turkey',1,26184,0,1,0);
```
It shows proper data on it when you view it in inventory and such, just does not appear to have the relevant LUA and SQL entries to be able to use them. Initially, thought it might be a group food, but the wikis still list it as player only.  So it may be something that could be loosely modeled after existing 4hr foods (roast turkey, etc.)

I expect we have some means of handling the counter effect/mod, but there was a question in discord as to whether we have the resist amnesia effect/mod coded yet to be able to mark it up or not.  There does not appear to be an addMod scripted for the baramnesia spell effect, so this may be true?

I did spot entries for resisting amnesia in item_mods.sql though.  Not sure if any of that data could be useful in marking up this food item and possibly the baramnesia spell effect or not though:

```lua
INSERT INTO `item_mods` VALUES (10546,1,27); -- URJA GLOVES, DEF:27 AGI+6 Attack+5 Enhances "Resist Amnesia" effect
INSERT INTO `item_mods` VALUES (10546,253,1); -- RESAMNESIA
INSERT INTO `item_mods` VALUES (10547,1,28); -- STHIRA GLOVES, DEF:28 AGI+7 Attack+6 Enhances "Resist Amnesia" effect
INSERT INTO `item_mods` VALUES (10547,253,1); -- RESAMNESIA
INSERT INTO `item_mods` VALUES (11815,253,1);     -- Resist Amnesia +1 ?
INSERT INTO `item_mods` VALUES (22264,253,10);    -- Mantoptera Eye: "Resist Amnesia"+10
INSERT INTO `item_mods` VALUES (26836,253,20); -- Resist Amnesia +20
INSERT INTO `item_mods` VALUES (26837,253,25); -- Resist Amnesia +25
```

**Comment by TeoTwawki** [comment]
In the item script:
```lua
item_object.onItemUse = function(target)
    target:addStatusEffect(xi.effect.FOOD, 0, 0, duration_in_seconds_here, item_ID_here)
end

item_object.onEffectGain = function(target, effect)
    target:addMod(xi.mod.STR, 10)
    target:addMod(xi.mod.FOOD_ATTP, 20)
    target:addMod(xi.mod.FOOD_ATT_CAP, 120)
    target:addMod(xi.mod.FOOD_RATTP, 20)
    target:addMod(xi.mod.FOOD_RATT_CAP, 120)
    target:addMod(xi.mod.COUNTER, 10)
    target:addMod(xi.mod.AMNESIARES, 10)
end

item_object.onEffectLose = function(target, effect)
    target:delMod(xi.mod.STR, 10)
    target:delMod(xi.mod.FOOD_ATTP, 20)
    target:delMod(xi.mod.FOOD_ATT_CAP, 120)
    target:delMod(xi.mod.FOOD_RATTP, 20)
    target:delMod(xi.mod.FOOD_RATT_CAP, 120)
    target:delMod(xi.mod.COUNTER, 10)
    target:delMod(xi.mod.AMNESIARES, 10)
end
```

**Comment by TeoTwawki** [comment]
it will also need an entry in the item_usable.sql table

**Comment by CatsEyeXI** [comment]
I'd like to implement this, looks like a simple add, but the item is only available from the greeter moogle during select login campaigns, meaning i would not be able to accurately capture the animation from retail. can we assume this until a later time? or would you prefer holding off on adding the item until that data is available?

**Comment by TeoTwawki** [comment]
Do foods have diff use animations? I'd never noticed/paid attention. Even so, you can get away with copying the value from a similar food and putting a todo comment if the animation is wrong. I have a couple of these and when I finally use them, I can fix it if nobody else has.
