### ISSUE TITLE
PLD Majesty implementation, currently not working correctly

### ISSUE THREAD

**Issue by AppleCrumble1** [DerpyProjectGroup/topaz#946]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

PLD majesty is in the game but doesn't actually work as per retail. the ability is there but the additional effects of the ability do not work as intend as retail, timer, icon and the circle shows but when casting any cure or protect spell while under the effect it doesn't make it an aoe heal on self, party or alliance members the potency or reduction in timers isn't effected either. 
Could anyone look into implementation of this ability please?

Thank you for your time

**Comment by RAIST5150** [comment]
Looks like another item that hasn't gotten the status effect/mod scripted yet.

Noticed this on a couple spells I was planning to audit later this week to see if I could PR them.  May be able to address this one too, provided I can find the necessary entries/syntax to edit in.

EDIT:
Looks like this was a work in progress at one point, but certain pieces were missing.  Spotted the effect/status entries that I would expect to be used (part of the chain is commented out).  Not sure if we need the job_utils entries though (like we have for Warcry and such)... so reluctant to touch this myself  without knowing for certain what is still needed.

**Comment by AppleCrumble1** [comment]
Did this ever get fixed correctly?

**Comment by TeoTwawki** [comment]
~~only partial: the aoe stuff hasn't been done, but the potency and cast reduction has~~

**Comment by TeoTwawki** [comment]
oh nope, I'm wrong I just needed to filter search better: https://github.com/LandSandBoat/server/blob/b3eebcb0bf735c4203c1e5950bc9155fac2bd6fc/src/map/utils/battleutils.cpp#L5658

its all there.
