### ISSUE TITLE
Runic Portal sends you to the wrong Staging Point

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#947]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Mamool takes you to Halvung, Halvung takes you to Dvucca, and Dvucca goes to Mamool.

https://github.com/LandSandBoat/server/blob/base/scripts/zones/Aht_Urhgan_Whitegate/npcs/Runic_Portal.lua

**Comment by Skerxan** [comment]
I think I found the problem. I don't know how to change assault.lua without breaking it. @KnowOne134 

This is in teleports.lua:
```
xi.teleport.runic_portal =
{
    AZOUPH  = 1,
    DVUCCA  = 2,
    MAMOOL  = 3,
    HALVUNG = 4,
    ILRUSI  = 5,
    NYZUL   = 6,
}
```
https://github.com/LandSandBoat/server/blob/base/scripts/globals/teleports.lua

This is in assault.lua:
```
xi.assaultUtil.assaultArea =
{
    LEUJAOAM_SANCTUM           = 0,
    MAMOOL_JA_TRAINING_GROUNDS = 1,
    LEBROS_CAVERN              = 2,
    PERIQIA                    = 3,
    ILRUSI_ATOLL               = 4,
    NYZUL_ISLE                 = 5,
}
```
https://github.com/LandSandBoat/server/blob/base/scripts/globals/assault.lua

**Comment by claywar** [comment]
Need to check the old assault branch.  I know I fixed it there previously, and there were some other enums that needed re-ordering
