### ISSUE TITLE
Dancer AF quests neep proper implementation of the dance minigames.

### ISSUE THREAD

**Issue by Xaver-DaRed** [DerpyProjectGroup/topaz#972]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
As title sais. When converting this quests to interaction, we have to be mindful that this minigames exist and can actually be failed.

**Comment by Skerxan** [comment]
I am not sure if I should post it here but this feedback just came in:

`"The last Dancer Artifact Quest, Comeback Queen, hangs on the last cutscene and just gives a black screen.  This is for the Dancer's Casaque.  I've tried multiple times and it always gets stuck on a black screen.  I'm updated to the most recent retail client."`

**Comment by claywar** [comment]
I'd say there's a high change that they're related.  Going to try to make some time to get some caps of it this week, but if anyone beats me to it, just make sure to fail a couple of times.

**Comment by claywar** [comment]
Closing this issue since the quest has been rewritten since then and verified as functioning. If it is still freezing, would recommend checking client add-ons and mods
