### ISSUE TITLE
rotz "Awakening" I need to find out the start condition of the cutscene

### ISSUE THREAD

**Issue by eyes-and-brain** [DerpyProjectGroup/topaz#978]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

In the current implementation, the cutscene starts when you enter certain coordinates of "Tenshodo of Lower Jeuno".
https://github.com/LandSandBoat/server/blob/f98d90c88cfadcb1a4e8536bcdd184e1bb3ef0fd/scripts/missions/rotz/17_Awakening.lua#L47-L56

However, the cutscene dialogue summary site states that the starting condition is to "examine Door:Tenshodo H.Q".
https://w.atwiki.jp/magichappy/pages/210.html

**Comment by Xaver-DaRed** [comment]
Yep, that seems to be the case.

https://www.youtube.com/watch?v=82wnpIxBfp0
Minute 4:10

More recent video
https://www.youtube.com/watch?v=4uQaKyTcwL0
Minute 9:50

**Comment by eyes-and-brain** [comment]
Thanks for the information. I've just watched the video.
Indeed, the cutscene starts with "Examine Door:Neptune's Spire".
